// DRAFT (Opus author, gated pipeline AUTHOR step) — Averroes (Ibn Rushd) philosophy thinker read.
// Structurally identical to src/app/philosophy/thinker/_reads/aquinas.ts (the model). Drops
// straight into the provisional reader. Every factual claim is mapped to its fact-pack section in
// audits/philosophy-pipeline/averroes-thinker-fact-ledger.md. Authored ONLY from that ledger;
// nothing from memory. Consistent with the era read at src/app/philosophy/faith-reason/ (goes
// DEEPER on Averroes, never restates).
// FACT DISCIPLINE: no public-domain English translation of any Averroes work exists, so all
// Averroes wording here is PARAPHRASE with NO quotation marks. The only verbatim quote is Dante's
// PD Inferno IV.144 line (attributed to Dante, not Averroes); the other epigraphs are the read's
// own house-voice framing. The "double truth" myth is corrected in the hook, the break, and ch5.
// Inline *italics* and **bold** are rendered by the page. eyebrow = "Aristotelians".

import type { PhiNarr } from '@/components/philosophy-reader'

export const AVERROES: PhiNarr = {
  "title": "Averroes",
  "throughline": "He spent his life on one wager: that the most rigorous reason and the revealed Law are two roads to a single truth, and that since truth cannot contradict truth, philosophy has every right to exist alongside religion rather than cowering before it. When a famous book tried to prove that the philosophers were not just wrong but unbelievers, he wrote the rebuttal. When scripture seemed to clash with what reason had demonstrated, he argued that scripture must be read allegorically, not that reason must be silenced. He defended Aristotle so exhaustively, line by line, that Latin Europe stopped using his name and just called him the Commentator.",
  "hero": {
    "fig": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Andrea_di_bonaiuto%2C_apoteosi_di_san_tommaso_d%27aquino%2C_11_averro%C3%A8.jpg",
    "cap": "Averroes, detail from Andrea di Bonaiuto's fresco of the Triumph of Saint Thomas Aquinas (c. 1365–67; Spanish Chapel, Santa Maria Novella, Florence; photograph by Sailko, CC BY 3.0). The turbaned scholar with his book and scroll is one of the figures laid out beneath the enthroned Aquinas as a vanquished heretic. That is the Christian program of the painting, not a neutral portrait, and no likeness of Averroes made in his lifetime survives, so this (like every image of him) is a later imagining by people who knew him only through his books.",
    "alt": "Fresco detail of a seated turbaned, bearded scholar holding a red book and a scroll, hand raised to his cheek in a thinking pose"
  },
  "hook": [
    "In the 1190s an old man in Córdoba watched his life's work burned. Ibn Rushd had been chief judge of the city, court physician to the caliph, and the most exhaustive interpreter of Aristotle the world had yet produced. Now a tribunal had condemned his teaching, ordered his books fed to the fire, and banished him to a small town nearby. Philosophy itself was declared a danger to the faith. The man who had spent decades arguing that reason and religion were friends had been answered, for the moment, by the censor.",
    "He was rehabilitated before he died in 1198, and the verdict that mattered came later anyway, from an unexpected direction. His own civilization largely set him aside; Latin Christian Europe took him up with both hands. Within a few decades his commentaries on Aristotle were translated into Latin and devoured in the new universities, and they were so thorough, so indispensable for actually understanding the Greek, that scholars stopped bothering with his name. Aristotle was simply *the Philosopher*. Ibn Rushd was simply *the Commentator*. No one needed to ask which commentator.",
    "What he had defended was a single, dangerous idea: that philosophy has a *right* to exist, that human reason pushed to its limits is not the enemy of revealed religion but a second road to the same truth. The most famous attack on the philosophers, a book that called their boldest conclusions outright unbelief, had nearly closed the road for good. Averroes wrote the rebuttal, defended Aristotle against it inch by inch, and argued that where scripture seems to contradict what reason has proved, the answer is to read the scripture more carefully, not to stop reasoning.",
    "And then history played a strange trick on him. The doctrine he is most often saddled with, the famous \"double truth\" (that a thing can be true in philosophy and false in religion at the same time), is one he never held. He held the opposite, and said so flatly. The phrase was hung on him by the bishop who condemned his Latin followers, and it stuck so well that the caricature outlived the man. Untangling what Averroes actually argued from what was later pinned on him is most of the work of understanding him."
  ],
  "brk": {
    "beforeLabel": "Philosophy is a threat to the faith, to be reined in or shut down",
    "afterLabel": "Philosophy is the faith's own ally, and the two reach one truth together",
    "paragraphs": [
      "By the late twelfth century the standing of philosophy in the Islamic world was in real trouble, and the reason had a name. A century earlier al-Ghazali (around 1058 to 1111), one of the most respected theologians Islam ever produced, had written a book called *The Incoherence of the Philosophers*. It was not a hostile outsider's rant; it was a brilliant insider's demolition, written by a man who understood the philosophers' arguments as well as they did. It went through twenty of their key positions and argued that on these matters the philosophers had not proved what they claimed, and on three of them it went further and declared the teaching outright unbelief: that the world is eternal and uncreated, that God knows only universal kinds and not individual things and events, and that there is no bodily resurrection. To call a position unbelief (*kufr*) was not an insult; it was a charge with teeth, because the punishment for apostasy was death.",
      "Both sides of that fight deserve their strongest case, because al-Ghazali was not being stupid. The philosophers he was attacking, above all [Avicenna](/philosophy/thinker/avicenna) (era 2, chapter 3), had taken the Greek inheritance and run it hard, and the conclusions really did sit awkwardly with revealed religion. If the universe never began, what is left of the doctrine of creation? If God knows only the general laws and not the falling of each particular sparrow, what is left of providence? al-Ghazali also struck at the philosophers' confidence in cause and effect itself, arguing that the link between a cause and its effect is not a necessary connection at all but a habit God customarily keeps: it is not the fire that burns the cotton but God, who creates the burning at the moment the fire touches. Pull that thread and the whole machine of Aristotelian science, in which things act by their own natures, comes loose. After al-Ghazali, defending philosophy in a pious society looked less like scholarship and more like a liability.",
      "Averroes's break is to refuse the choice between abandoning philosophy and smuggling it. He does not retreat into the view that faith and reason occupy sealed rooms that never speak. He does not claim that reason can prove the whole of religion either. He makes a harder claim: that reason and the revealed Law are two routes to *one* truth, and that since the same God is the author of both the world reason studies and the scripture revelation delivers, the two cannot finally contradict each other. Where they seem to collide, one of two things has gone wrong. Either the reasoning was not actually a demonstration, or the scripture has been read too literally and needs to be interpreted, read for its deeper sense rather than its surface. The concrete move that makes this work is his rule for reading scripture: **where the apparent meaning of a revealed text conflicts with something reason has genuinely demonstrated, the text must be taken allegorically.** Truth does not contradict truth, so the conflict can only be apparent, and the work is to locate the mistake. That is the engine of his whole defense, and it is the exact opposite of the \"double truth\" he would later be blamed for. There are not two truths to juggle. There is one, and philosophy is one of the two honest ways to reach it."
    ]
  },
  "chapters": [
    {
      "num": 1,
      "title": "The judge of Córdoba",
      "epigraph": {
        "text": "A dynasty of judges produced, at last, the man who would judge between reason and the Law itself.",
        "attribution": "— framing Averroes's judicial inheritance"
      },
      "blocks": [
        {
          "p": "He was born in 1126 in Córdoba, in Muslim Spain (al-Andalus), into a family that had run the city's courts for generations. His grandfather, who died the year Thomas was not yet alive to hear of, had been **chief qadi** (the chief judge) of Córdoba; his father held the same office. (The grandfather, confusingly, shared his name and died the very year the grandson was born.) To be born an Ibn Rushd was to be born into the law: the religious law of Islam, the *sharia*, administered in the courts by judges trained in its texts and its reasoning. Averroes would follow that road. He served as a judge in Seville and in Córdoba, and rose, like his grandfather, to be chief qadi of Córdoba. The man who would spend his life arguing that philosophy and the Law belong together was, by profession, an officer of the Law."
        },
        {
          "p": "The dynasty he served was the **Almohads**, a Berber Muslim dynasty out of North Africa that had swept into Spain and displaced the previous rulers around the time of his childhood. They were his patrons, and the relationship is the hinge of his whole career. Through the philosopher and physician **Ibn Tufayl** (a friend at court, author of the famous philosophical novel *Hayy ibn Yaqzan*, about a child raised alone on an island who reasons his way to the truth), Averroes was introduced, around 1169, to the caliph **Abu Yaqub Yusuf**. The caliph, the story goes, had been struggling with the works of Aristotle and complained how hard they were to follow. Ibn Tufayl suggested the young Averroes was the man to fix that, to go through Aristotle and make him clear. The vivid version of that scene, with the caliph's exact words preserved, comes from a later biographer and belongs to the tradition rather than the record. But the commission itself is solid, and it set the course of the rest of his life. A ruler asked for a clearer Aristotle, and got the clearest Aristotle anyone has ever written."
        },
        {
          "p": "He was not only a judge and a commentator. He was also a working **physician**, and a serious one. In 1182 he succeeded Ibn Tufayl as court physician to the caliph, and his medical encyclopedia, the *Kitab al-Kulliyat* (\"The General Principles of Medicine\"), became a standard work. Translated into Latin as the *Colliget*, it was printed and used in European universities for centuries. The detail kills the picture of the philosopher as a pure abstraction-spinner. Averroes spent his days settling lawsuits, diagnosing patients, and advising a king, and he wrote his vast philosophical output around the edges of a crowded public life. The mind that worked out the most rigorous defense of reason in the medieval world was the mind of a busy professional."
        },
        {
          "p": "It ended badly, at least for a while. Around 1195, under a later caliph, **Abu Yusuf Yaqub al-Mansur**, the wind turned against him. A tribunal condemned his teachings, his books were ordered burned, and he was banished to **Lucena**, a town near Córdoba. Philosophy was officially declared suspect. Historians generally read the episode as politics more than theology: the caliph was preparing for war and needed the support of conservative jurists, and sacrificing the court philosopher was a cheap way to buy it. The disgrace did not last. He was restored to favor before the end, and he died in 1198 in Marrakesh, in North Africa, where the dynasty had its seat. His body, by tradition, was later carried back across the strait to Córdoba for reburial. The home of the judges took back its most famous son, though it would be Latin Europe, not al-Andalus, that kept his thought alive."
        }
      ]
    },
    {
      "num": 2,
      "title": "The Commentator",
      "epigraph": {
        "text": "\"Averroìs, che 'l gran comento feo.\" (\"Averroes, who made the great commentary.\")",
        "attribution": "— Dante Alighieri, Inferno IV.144 (c. 1320), placing Averroes among the virtuous pagans of Limbo"
      },
      "blocks": [
        {
          "p": "The work that earned Averroes his title is enormous and, on the surface, unglamorous: he wrote *commentaries* on Aristotle, books that go through Aristotle's books and explain them. There is a reason this was needed and a reason it was hard. Aristotle had been dead nearly fifteen hundred years. His Greek was compressed, technical, and often maddening; large stretches read like lecture notes, because that is roughly what they are. And Averroes could not even read them in the original, since he did not know Greek. He worked from **Arabic translations** of Aristotle, themselves often made by way of an intermediate Syriac version, so he was interpreting a translation of a translation of one of the most difficult thinkers who ever lived, and getting it astonishingly right."
        },
        {
          "p": "He did it at three levels, and the three-tier scheme shows a teacher's mind at work. There were **short commentaries** (epitomes), brisk summaries that boil a work down to its essentials. There were **middle commentaries**, paraphrases that restate Aristotle's argument in clearer, fuller prose, smoothing the lecture notes into readable exposition. And there were the **long commentaries**, the great ones, which print Aristotle's text in chunks and then unpack each chunk line by line, weighing every phrase, resolving every apparent contradiction, arguing with previous interpreters. (Recent scholarship cautions that this neat three-level picture does not quite capture how varied his actual practice was, so it is best taken as the standard map rather than an exact law.) The long commentaries are where Averroes does his deepest and most original work, because reading Aristotle that closely forced him to take positions of his own, and some of those positions (chapter 5) were explosive."
        },
        {
          "p": "Why bother explaining a dead Greek pagan with such devotion? Because Averroes was convinced that [Aristotle](/philosophy/thinker/aristotle) (era 1) had very nearly gotten the structure of reality *right*, that here was a human being who had pushed unaided reason about as far as it could go, and that recovering him exactly was therefore a service to truth. His attitude to Aristotle was not slavish. He corrected him where he thought he had erred, and he hammered earlier Muslim philosophers, above all [Avicenna](/philosophy/thinker/avicenna), for diluting Aristotle with Neoplatonic ideas (the layered, mystical cosmos of emanations that [Avicenna](/philosophy/thinker/avicenna) had grafted on; era 2, chapter 3). Averroes wanted Aristotle pure, Aristotle himself, scraped clean of the additions. That purist devotion is exactly what made him so valuable to the next civilization that found him."
        },
        {
          "p": "That civilization was Latin Christendom, and the takeover was total. Beginning in the 1220s his commentaries were translated into Latin, notably by **Michael Scot**, and they hit the new universities of Paris and Oxford like a delivery of live ammunition. To understand Aristotle, who was himself only then flooding back into the West, a scholar needed Averroes. And he proved so indispensable that medieval writers simply stopped naming him. Aristotle became *the Philosopher*; Averroes became *the Commentator*; and when a scholastic text says \"the Commentator holds,\" everyone in the room knew exactly whose voice was meant. Dante, writing his vision of the afterlife around 1320, placed him among the noble pre-Christian and non-Christian minds in the gentlest circle of Hell, summing him up in a single line, *who made the great commentary*. The man banished from Córdoba had become a fixture of the Christian imagination."
        }
      ]
    },
    {
      "num": 3,
      "title": "The incoherence of the Incoherence",
      "epigraph": {
        "text": "To answer a book called The Incoherence of the Philosophers, he wrote a book called The Incoherence of the Incoherence. The title is the whole argument in miniature.",
        "attribution": "— framing the al-Ghazali duel"
      },
      "blocks": [
        {
          "p": "The central intellectual drama of Averroes's life was a fight with a man who had been dead for fifteen years before it began. **al-Ghazali** (around 1058 to 1111) had been one of the towering theologians of Islam, and his book *The Incoherence of the Philosophers* (*Tahafut al-Falasifa*) was the most effective attack on philosophy the tradition had produced. Its power lay in its fairness. al-Ghazali first mastered the philosophers' own arguments, stated them as strongly as they would themselves, and only then turned them inside out, trying to show that the philosophers had not actually *demonstrated* the grand conclusions they paraded as proven. He worked through twenty such positions. On three he raised the stakes to the maximum, declaring the teaching not merely mistaken but unbelief: the eternity of the world, the claim that God knows only universals and not particular things, and the denial of bodily resurrection."
        },
        {
          "p": "His sharpest blow landed on causation itself, one of the deepest arguments in medieval philosophy, and it anticipates a move David Hume would make six centuries later (era 3, chapter 7). The plainest case of cause and effect imaginable is fire touching cotton, and the cotton burning. Everyone says the fire *caused* the burning. But what is actually *observed*? Only this: the fire is present, and then the burning is present. The fire's touch and the cotton's catching are seen together. What is never seen, al-Ghazali argues, is the alleged *necessary connection* between them, the invisible link that *forces* the second to follow the first. Succession is observed; necessity is inferred; but the necessity is not in the data. So perhaps there is no power in the fire to burn at all. Perhaps it is **God** who creates the burning, directly, every single time, in the customary order he has freely chosen to keep, so that what looks like nature's machinery running on its own is really God's habit, renewed instant by instant. This position is called *occasionalism* (the fire is merely the *occasion* on which God acts, not the cause). And if it holds, then the whole Aristotelian picture of a world of things acting by their own natures collapses, and with it the philosophers' confidence that they can read off how reality *must* behave."
        },
        {
          "p": "Averroes answered the whole assault with a book whose title is a counterpunch: *The Incoherence of the Incoherence* (*Tahafut al-Tahafut*). His method was to print al-Ghazali's arguments and refute them in sequence, and his deepest objection was a charge of bad faith about *method*. al-Ghazali, he argued, had won by playing dialectician, scoring debating points and stirring doubt, rather than by giving genuine demonstrations of his own. And on causation Averroes saw a catastrophe that al-Ghazali had not reckoned with. To deny that things have real natures and real causal powers is not merely to embarrass the philosophers; it is to destroy *knowledge itself*. To know something just *is* to know its causes, to grasp *why* it is what it is. A world where fire has no power to burn, where things have no stable natures, is a world about which nothing can be understood at all, only a sequence of bare happenings with no *because* behind them. Defending causation, for Averroes, was not defending a technicality. It was defending the possibility of science, of explanation, of reason having any grip on the world."
        },
        {
          "p": "On the specific charges he gave specific answers, and they show how he actually reconciled philosophy with faith rather than just asserting that he could. On the eternity of the world he argued, with Aristotle, that the question is subtler than a flat yes or no, and that the philosophers' \"eternity\" and the theologians' \"creation\" are not as far apart as al-Ghazali made them sound, since on both views the world depends utterly on God. On God's knowledge he argued that the human distinction between knowing-the-universal and knowing-the-particular simply does not apply to a divine mind, which knows in a way unlike any creature's, so the dilemma is a category mistake. The pattern is consistent: where reason and revelation appeared to collide, Averroes went looking for the misreading on one side or the other, certain in advance that a real demonstration and a true scripture could not actually contradict, because both are true and truth does not contradict truth. That certainty is the subject of the next chapter, where he turns it into a public argument for philosophy's right to exist."
        }
      ]
    },
    {
      "num": 4,
      "title": "Two roads, one truth",
      "epigraph": {
        "text": "Truth does not contradict truth. Where a proof and a verse seem to fight, somebody has misread the verse.",
        "attribution": "— paraphrase of the governing principle of the Decisive Treatise"
      },
      "blocks": [
        {
          "p": "If *The Incoherence of the Incoherence* was Averroes defending philosophy from a specific attack, the *Decisive Treatise* (*Fasl al-Maqal*) is Averroes putting philosophy on trial and arguing for an acquittal as a matter of law. The full title is roughly *The Decisive Treatise, Determining the Connection Between the Law and Wisdom*, and the lawyerly framing is deliberate. Averroes the chief judge writes it as a *legal* opinion. The question before the court is whether studying philosophy is permitted, forbidden, or required by Islamic law. His verdict is striking: for those with the ability to do it, philosophy is not merely permitted but *obligatory*. Scripture itself, he argues, repeatedly commands the believer to reflect on creation and reason about it, and the most rigorous form of that reasoning just *is* philosophy. The Law does not forbid philosophy. The Law orders it."
        },
        {
          "p": "The load-bearing principle underneath is the one Averroes keeps returning to, and the *Decisive Treatise* states it with full force: **truth does not contradict truth.** Revelation comes from God. The world that reason studies also comes from God. So a genuine demonstration (a real proof, not a plausible-sounding argument) and a true revealed text are both true, and two truths cannot contradict each other. It follows that whenever the apparent, surface meaning of a scriptural verse seems to clash with something reason has actually demonstrated, the clash must be only apparent, and the resolution is fixed in advance: the verse is to be read **allegorically**, interpreted for its inner meaning rather than its literal one. The demonstration stands; the scripture is read more deeply. Reason is never asked to recant a proof to save a literal reading. This is exactly backwards from the caricature in which Averroes lets reason override faith. He lets *demonstration* correct a *misreading*, which is a very different thing, and he does it precisely because he is so sure the two can never really conflict."
        },
        {
          "p": "He guards the doctrine against an obvious objection, and the guard is the most controversial and most easily misread part of his theory. The objection is that if scripture can be read allegorically, every believer will start explaining away whatever he dislikes. Averroes answers by dividing people into three kinds according to *how they are persuaded*, not how clever they are. There are the **demonstrative** few, the philosophers, who can follow a strict proof and who alone are qualified to interpret a verse allegorically when a demonstration requires it. There are the **dialectical**, the theologians, who reason by probable argument and debate. And there is the great **rhetorical** majority, who are moved by vivid images and preaching, and who should take scripture at its plain, apparent sense, because allegory in their hands would not enlighten them but only unsettle their faith with doubts they have no tools to resolve. Allegorical interpretation, on this view, is a delicate instrument for trained hands, not a public toy. And here Averroes turns the knife on his old opponent: the real damage, he argues, was done by **al-Ghazali**, who broadcast subtle theological disputes and allegorical readings to a popular audience that was never equipped for them, sowing exactly the confusion that interpretation is supposed to prevent."
        },
        {
          "p": "The three-classes doctrine has an ugly side: it builds a permanent hierarchy of knowers, in which the philosopher quietly grasps truths that the masses are deliberately kept from, and that has struck many later readers as elitist and condescending. It is also, in its own terms, a serious attempt to solve a real problem: how a society can house both demanding philosophy and ordinary piety without each wrecking the other. Whatever its faults, the architecture is the precise opposite of \"double truth.\" Averroes is not saying the philosopher believes one thing and the believer another. He is saying there is *one* truth, that scripture and demonstration both deliver it, that they are pitched at different audiences in different registers, and that where the registers seem to clash the trained reader reconciles them by interpretation. One truth, three audiences, two honest roads. The confusion of that careful position with its cartoon opposite became its own strange afterlife (chapter 5)."
        }
      ]
    },
    {
      "num": 5,
      "title": "One mind for all, and the truth he never taught",
      "epigraph": {
        "text": "He was condemned in Córdoba for one doctrine, and condemned in Paris for another he did not hold. Both verdicts outlived the man.",
        "attribution": "— framing Averroes's two afterlives"
      },
      "blocks": [
        {
          "p": "Averroes's single most notorious philosophical claim grew out of the most difficult passage in all of Aristotle, the discussion of the intellect in the work *On the Soul* (*De Anima*). The puzzle Aristotle left half-finished is this: when a human being *thinks*, grasping a universal concept like \"triangle\" or \"justice\" (not this particular triangle drawn in sand, but triangularity as such), what exactly is doing the thinking? Aristotle had distinguished two aspects of intellect: a *potential* side that can receive any concept whatever, and an *active* side that does the work of pulling the universal out of sense-experience, abstracting \"triangle in general\" from the particular triangles we see. He never fully explained how they relate, or whether they are parts of each individual soul or something else. Working through the long commentary, Averroes reached a conclusion that he himself flagged as new and bold, one he said he had found in no thinker before him."
        },
        {
          "p": "The conclusion was this: the **potential intellect**, the part that receives universal concepts, is not a private faculty inside each person's head. It is a single, immaterial, eternal substance, *one and the same for all human beings*. (This is often called the *unity*, or *unicity*, of the intellect, or *monopsychism*, from the Greek for \"one soul.\") The reasoning has genuine force. A universal concept, to *be* universal, has to be received without being chopped down to a particular. But anything housed in a particular lump of matter (a specific brain, a specific person) gets individualized by that matter, turned into *this* person's particular mental state. So the receiver of genuine universals cannot itself be a particular material thing tied to one body. It must be immaterial, and if it is immaterial and outside the individuating grip of matter, there is no principle left to make it *many*: there is just one of it, shared. Each person hooks into that one shared intellect through the **mental images** thrown up by his own particular body and senses, which is why thinking still feels like *mine*, even though the intellect doing it is held in common. It is a strange, austere, genuinely subtle picture, and Averroes built it not to provoke but because he thought the logic of universals forced it."
        },
        {
          "p": "The alarming consequence is what made it infamous. If the only intellect that survives the body's death is a *single shared* substance rather than each person's own, then there is no individual mind to carry on after death, and the doctrine appears to wipe out **personal immortality**: no private individual soul goes anywhere, because the thinking part was never the individual's to begin with. To a Christian (or a Muslim, or a Jew) staking everything on personal survival and personal judgment, this was intolerable. It is the doctrine that drew [Aquinas](/philosophy/thinker/aquinas) (era 2, chapter 4) into the field with a whole treatise aimed straight at it, *On the Unity of the Intellect Against the Averroists* (1270). [Aquinas](/philosophy/thinker/aquinas) argued that on Averroes's view it would not be *this man* who understands, since the understanding is happening in a shared substance and not in the individual, and that the obvious fact that *I* think, that thinking is genuinely my own act, refutes the whole construction. [Aquinas](/philosophy/thinker/aquinas) held instead that the intellect is the form of each individual body, so that each person truly thinks and truly survives. The two of them disagreed inside a shared inheritance: [Aquinas](/philosophy/thinker/aquinas) had learned his Aristotle in no small part *from* the Commentator he was refuting."
        },
        {
          "p": "His followers in Latin Europe carried his name into a fight he had not started. By the mid-thirteenth century there was a current in the arts faculty at the University of Paris, associated above all with **Siger of Brabant** and **Boethius of Dacia**, that pushed Aristotle (read through Averroes) hard toward conclusions that scraped against Christian doctrine, including the eternity of the world and the unity of the intellect. Modern scholars often prefer to call them \"radical Aristotelians\" rather than \"Averroists,\" but the label stuck at the time, and it drew fire. Bishop **Étienne Tempier** of Paris condemned a list of propositions in 1270 and a far longer list, 219 of them, in 1277, in one of the most famous acts of intellectual censorship of the Middle Ages."
        },
        {
          "p": "One myth has shadowed Averroes ever since. The doctrine of **\"double truth\"** (the claim that one and the same proposition can be true in philosophy and at the same time false in theology, so that a thinker could affirm something *as a philosopher* and deny it *as a believer*) is the thing every textbook hangs on Averroes and the Averroists. **He did not hold it.** He held its exact opposite: one truth, reached by two roads, reconciled by interpretation. The phrase comes not from Averroes but from Tempier. The bishop's 1277 preamble accused his targets of saying things were true \"according to philosophy\" but not \"according to the faith,\" as though they juggled two contrary truths, and later historians gave that accusation its catchy name. It was a charge laid against opponents, a description of a position put in their mouths, not a doctrine anyone is known to have actually professed. The verdict of modern scholarship is blunt: no Latin Christian medieval thinker ever upheld the double-truth theory, and the real Averroes, far from teaching it, had spent the *Decisive Treatise* arguing that there is only one truth and that demonstration and scripture cannot finally disagree. The caricature is almost the precise negative of the man."
        }
      ]
    },
    {
      "num": 6,
      "title": "What survived him",
      "epigraph": {
        "text": "His own world set him aside; a foreign one took him up. The Commentator's longest argument was the one his books kept making after he was gone.",
        "attribution": "— framing Averroes's legacy"
      },
      "blocks": [
        {
          "p": "Averroes died in 1198 having seen his books burned and his philosophy declared a danger, and in his own civilization the long-term verdict was, broadly, that the burners had won. The confident, Aristotle-grounded philosophical project he represented did not become the mainstream of later Islamic thought; other currents, including the more mystical and the more theological, carried the day. It is one of the quieter ironies of intellectual history that the thinker Arabic-speaking Islam largely set aside became, for several centuries, indispensable to Christian Europe. The recovery of Aristotle that remade the medieval West, that gave [Aquinas](/philosophy/thinker/aquinas) his tools and reorganized the universities, ran straight through the commentaries of a Córdoban judge."
        },
        {
          "p": "Averroes had a third inheritance, in the Jewish world. Averroes's near-contemporary **Maimonides** (1138 to 1204), the greatest Jewish philosopher of the age, read him with admiration and steered Jewish readers toward him, and over the following generations Averroes's commentaries were translated into Hebrew and pored over. The philosopher **Gersonides**, in the fourteenth century, wrote *super-commentaries*, commentaries on Averroes's commentaries on Aristotle, layering interpreter upon interpreter upon the original Greek. For medieval Jewish thought, the influence of the Commentator was second only to that of Maimonides himself. The man who could not get a hearing at home was being studied intently in three languages and three faiths."
        },
        {
          "p": "The shape of his achievement comes clear against the rival synthesis it helped provoke. Averroes had argued that philosophy is the believer's friend and that, handled by the right people, reason and revelation reach one truth together. [Aquinas](/philosophy/thinker/aquinas) would build the great Christian version of almost exactly that conviction, using almost exactly Averroes's Aristotle, while fighting Averroes tooth and nail on the unity of the intellect and refusing his three-tiered division of knowers. The disagreement is as instructive as the agreement. Both men believed reason and faith could not ultimately conflict; they divided over how, and over what reason left for revelation to supply. The medieval argument about whether the life of the mind is permitted, and how far it may go, was in large part an argument conducted *through* Averroes, by people building on him and people refuting him, often in the same breath."
        },
        {
          "p": "The final irony is the cleanest. The doctrine he is most remembered for, the \"double truth,\" he never taught; the most rigorous thing he actually built, the case that there is a single truth and that philosophy has an honest road to it, was half-forgotten under the caricature. He had defended the right of human reason to follow its arguments to the end without being shut down by the censor, and the censor, in Córdoba and again in Paris, kept getting the last word in his own lifetime and just after it. But the books outlasted the verdicts. Centuries after the fire in Córdoba and the condemnations in Paris, scholars across three traditions were still working line by line through the commentaries of the man they had simply called the Commentator, which is the longest argument he ever made, and the one he won."
        }
      ]
    }
  ]
}
