// GENERATED gated transport of the "Berkeley" philosophy thinker deep-read (kind: THINKER).
// Authored Opus from audits/philosophy-pipeline/berkeley-thinker-fact-ledger.md ONLY, per
// audits/philosophy-content-pipeline.md (the gates: make-them-GET-it, born-verified
// quotes, honest-framing). Structurally identical to hume.ts (the model). Goes DEEPER
// than the era-3 read (src/app/philosophy/rationalists-empiricists/narrative.ts), never
// restates it. Inline *italics* and bold markdown are rendered by the page. Figure
// captions are gated fact-pack content; alt text is presentational. Berkeley wrote in
// English and both works are public domain (Project Gutenberg #4723, #4724); every
// quotation below is verbatim from those texts, cited by section/dialogue. Material not
// in the fact pack carries [VERIFY] and must be cleared by the coordinator before ship.

import type { PhiNarr } from '@/components/philosophy-reader'

export const BERKELEY: PhiNarr = {
  "title": "Berkeley",
  "throughline": "An Anglican bishop who looked at the material world everyone took for granted and announced that it does not exist. Not that the world is unreal: the tree, the table, the apple are as real as ever. But there is no *matter* under them, no inert stuff propping up our perceptions, because to be is to be perceived. An apple just is its look and feel and smell and taste, and nothing underneath. The world is real, shared, and law-governed, and it is made entirely of minds and their ideas, held in being by the greatest mind of all. He took Locke's empiricism one step further than Locke dared, and the step landed somewhere nobody expected: a universe with the matter taken out and God left holding it up.",
  "hero": {
    "fig": "https://upload.wikimedia.org/wikipedia/commons/5/5d/John_Smibert_-_Bishop_George_Berkeley_-_Google_Art_Project.jpg",
    "cap": "George Berkeley, painted by John Smibert around 1727, the year before Berkeley sailed for Rhode Island to raise money for a college that never opened. National Portrait Gallery, Washington, D.C. (NPG.89.25).",
    "alt": "Oil portrait of George Berkeley, a young clergyman in dark clerical dress with a white collar, looking toward the viewer",
    "portrait": true
  },
  "hook": [
    "Of all the claims in the history of philosophy, this one sounds the most like a man having everyone on. There is no matter. Not hidden matter, not matter we cannot quite reach, but no matter at all: the solid stuff that floors and stones and bodies are supposedly made of does not exist, has never existed, and the very idea of it is a confusion. A young Irish clergyman published this in 1710, argued it again in 1713 in a book staged as a friendly debate, and spent the rest of a long and respectable life insisting he meant it literally.",
    "What makes the position more than a stunt is that it was not built to shock. It was built to *defend*, and to defend the most ordinary view there is. George Berkeley thought he was the one man in Europe taking common sense seriously and the philosophers were the ones who had lost their minds. The plain person says the table is exactly what he sees and feels, no more. It is the philosopher who insists on a second table, an invisible material one, lurking behind the visible one and causing it. Berkeley's whole project was to knock that second table away and leave the plain person with the one he started with.",
    "He came at it through John Locke, the English philosopher of the previous generation who had argued that every idea in the human mind comes from experience and none is stamped in at birth. Berkeley accepted that completely. Then he asked the question Locke had not pressed: if every idea comes from experience, where is the experience that gives us *matter*? Trace the idea of an unperceived material substance back to the sensation that produced it, and nothing shows up, because all anyone ever perceives is sensations. Matter is a word with no experience behind it. Run Locke's own rule without flinching, and matter has to go.",
    "The result was a system most people met as a paradox and a few read closely enough to find airtight, or at least very hard to refute. Samuel Johnson, the great man of English letters, is said to have kicked a stone and declared \"I refute it thus,\" which refutes nothing, since the felt resistance of the stone is precisely one of the ideas Berkeley was talking about. The harder anyone pushed on the argument, the more it held, and the more uncomfortable it became, because it did not feel like it could possibly be true and no one could quite say which step was wrong.",
    "Berkeley was a bishop, and that matters for understanding why he wanted this. He thought materialism led straight to atheism: if the world is just self-running stuff, God becomes a spare part. Take the matter out, and the order of the world has nowhere to come from except a mind, which is to say from God, who turns out to be doing the work matter was supposed to do. So the bishop who abolished the physical universe did it to make room for the divine one, and the strangest metaphysics of the age was, in his own eyes, a piece of plain piety."
  ],
  "brk": {
    "beforeLabel": "Behind our perceptions lies a material world",
    "afterLabel": "There is no matter; to be is to be perceived",
    "paragraphs": [
      "Before Berkeley, the existence of matter was not a thesis anyone argued for. It was the floor everyone stood on. The ordinary view, and the scientific one, and Locke's, all agreed on the same picture: out there is a world of material objects, made of solid mind-independent stuff, and that stuff causes our perceptions and roughly resembles them. The stone is really there whether or not anyone looks; what we see is a copy of it, produced in us by the real thing. Matter is the name for what stays when every mind is gone. On this picture, perceptions are the surface and matter is the bedrock, and the job of knowledge is to read the bedrock off the surface.",
      "The position Berkeley is about to deny feels less like a theory than like breathing. Of course there is matter. Knock on the table and the resistance is right there, hard and external and indifferent to anyone's wishes. The whole power of the material picture is that it explains so much at once: why experience is *orderly* (the stuff behaves by fixed laws), why it *persists* (the stuff stays when the room empties), and why it is *shared* (two people in a room see one table because there is one material table for both). Matter is the single assumption that makes the world of experience hang together. Locke held it, Newton's physics ran on it, and it looked less like a claim than like the precondition of all the other claims.",
      "Berkeley's break is to take empiricism's own first rule, the rule Locke built the whole program on (every idea must trace back to the experience that produced it), and turn it on the one idea empiricism had never thought to question: matter itself. Trace the idea of material substance to the experience behind it. It cannot be done. All anyone ever perceives, by sight or touch or any sense, is colours, shapes, sounds, textures, which is to say ideas (*Principles* §4). No one has ever perceived the supposed inert stuff *underneath* the ideas, because the moment it is perceived it is just another idea. Worse, the stuff is supposed to *resemble* our ideas, and that is incoherent, because an idea can be like nothing but another idea (*Principles* §8); a colour can resemble only a colour, never a colourless something. Matter answers to no possible experience, resembles nothing we could ever meet, and does no work that minds and ideas cannot do without it. So it goes.",
      "What is left after matter is removed is not nothing, and this is the move that turns a wrecking job into a system. The order, the persistence, and the shared-ness that matter was invented to explain still need explaining, and Berkeley supplies a different cause: not dead stuff but a living mind. The ideas of sense arrive whether we will them or not, in steady law-governed trains we did not author, which means they are produced in us by another and far greater spirit (*Principles* §§29-30). That spirit is God, who perceives all things always and so holds the world in being when no human is looking (*Principles* §48). The before-picture had two layers, ideas on top and matter beneath. The after-picture keeps the ideas, deletes the matter, and puts God where the matter was. The world is exactly as full, as real, and as reliable as it ever seemed. It is simply mental all the way down."
    ]
  },
  "chapters": [
    {
      "num": 1,
      "title": "The bishop who took common sense seriously",
      "epigraph": {
        "text": "\"Since this revolt from metaphysical notions to the plain dictates of nature and common sense, I find my understanding strangely enlightened.\"",
        "attribution": "— Philonous, in Berkeley's Three Dialogues Between Hylas and Philonous (1713)"
      },
      "blocks": [
        {
          "p": "He was born on 12 March 1685, near Dysart Castle in County Kilkenny, into the Anglo-Irish gentry (the Protestant, English-descended families who held land and office in a mostly Catholic Ireland). He went to school at Kilkenny College and then to Trinity College Dublin, where he became a Fellow, and where, still in his twenties, he wrote almost everything he is remembered for. The pace is the first surprising thing about Berkeley: the radical system arrived early and the rest of a long life was spent on other work. *An Essay Towards a New Theory of Vision* came in 1709, on how the eye and the touch together build our sense of distance and size. *A Treatise Concerning the Principles of Human Knowledge*, the systematic statement of the philosophy, came in 1710. *Three Dialogues Between Hylas and Philonous*, the same case restaged as a debate for a wider public, came in 1713. He was under thirty, and the work was done."
        },
        {
          "p": "The label that has stuck to that work is idealism, and it is the single most misleading word in philosophy, because it has nothing to do with having ideals or living by high principles. Philosophical idealism is the view that reality is fundamentally *mental*: that what ultimately exists is minds and their contents, not mind-independent matter. Berkeley's particular version goes by two further names. Subjective idealism marks that the things we call physical objects exist only as they are perceived by some mind. Immaterialism marks the negative half of the same claim: there is no material substance, no inert stuff existing on its own behind our perceptions. The two names point at one position from two sides, and the position is the whole of his philosophy."
        },
        {
          "p": "Berkeley never thought of that position as an attack on the ordinary world. He thought of it as a rescue of the ordinary world from the philosophers. In the *Three Dialogues* his own spokesman describes the conversion he wants the reader to undergo: \"I have quitted several of the sublime notions I had got in their schools for vulgar opinions. And I give it you on my word; since this revolt from metaphysical notions to the plain dictates of nature and common sense, I find my understanding strangely enlightened.\" (\"Vulgar\" there means ordinary, the opinions of plain people, not coarse.) The plain person says a cherry is its colour, its smell, its sweetness, its softness, the whole bundle of what is tasted and touched and seen, and nothing more. It is the learned man who insists there must be, in addition, an unsensed material cherry behind all that, holding the sensations on. Berkeley sides with the plain person and against the learned man, and calls this common sense."
        },
        {
          "p": "His life after Trinity ran along two tracks, the churchman and the visionary, and they met in one grand failure. He was ordained in the Church of Ireland, travelled Europe as a tutor, and then, in the 1720s, conceived a plan to found a college in Bermuda to train clergy for the American colonies and for Native Americans. It was the great enterprise of his middle years. He raised subscriptions, won a promise of a parliamentary grant, and in 1728 sailed across the Atlantic and settled in Newport, Rhode Island, to wait for the money. He waited about three years. The grant never came, the project collapsed, and he went home. He was made Bishop of Cloyne, in County Cork, in 1734, and served the diocese for the better part of two decades. His last well-known book, *Siris* (1744), wandered from the medical virtues of tar-water all the way up to metaphysics and was a bestseller in its day, which is its own quiet joke: the philosopher who denied matter ended up famous in his lifetime for recommending a tonic. He died at Oxford on 14 January 1753."
        },
        {
          "p": "One more thing about the man frames everything he argued, because it supplies the motive. Berkeley was a bishop, and he was convinced that the materialism of his age led by a short road to atheism. If the world is nothing but self-sufficient stuff, grinding along under its own laws, then God is left with nothing to do, a spare part bolted onto a machine that runs fine without him. Berkeley's answer was to remove the machine. Take the matter out, and the order of nature has nowhere to come from but a mind, which is to say from God. The argument that abolishes the physical universe was, in its author's intention, an argument *for* God, and he said so plainly: the only existence he denied, he wrote, was the one that gave \"the Atheist\" \"the colour of an empty name to support his impiety\" (*Principles* §35). The metaphysics and the piety are the same move."
        }
      ]
    },
    {
      "num": 2,
      "title": "An apple is its look, feel, smell, and taste",
      "epigraph": {
        "text": "\"A certain colour, taste, smell, figure and consistence having been observed to go together, are accounted one distinct thing, signified by the name APPLE.\"",
        "attribution": "— George Berkeley, A Treatise Concerning the Principles of Human Knowledge, §1 (1710)"
      },
      "blocks": [
        {
          "p": "Berkeley builds his whole world out of two kinds of thing, and the entire system is a matter of refusing to admit a third. The first kind is ideas. In his usage an idea is not a thought floating free of the senses; it is any object of perception whatsoever, the colour actually seen, the warmth actually felt, the sound actually heard. The red of a sunset is an idea. So is the hardness met when a hand presses a table. The second kind is minds, also called spirits or souls: the things that *have* the ideas, that perceive and will and remember. \"This perceiving, active being is what I call MIND, SPIRIT, SOUL, or MYSELF,\" he writes, and a mind is \"a thing entirely distinct\" from its ideas, the thing \"WHEREIN THEY EXIST\" (*Principles* §2). Ideas and the minds that perceive them: that is the entire inventory of the universe. There is no third category, and the missing third category is matter."
        },
        {
          "p": "Start with an ordinary object, because the whole position can be seen in one apple. What is an apple? Berkeley answers in the very first section of the *Principles*: \"a certain colour, taste, smell, figure and consistence having been observed to go together, are accounted one distinct thing, signified by the name APPLE.\" An apple is a set of sensible ideas (a particular red, a particular sweetness, a particular roundness and firmness and scent) that experience has found reliably travelling together. The mind notices the cluster, ties the members under one name, and treats the bundle as a single thing. \"Other collections of ideas constitute a stone, a tree, a book, and the like sensible things\" (*Principles* §1). The object is the bundle. It is not a thing that *has* the look and feel and taste on top of being something else underneath. The look and feel and taste, gathered together, are all there is."
        },
        {
          "p": "The point lands hardest when one asks what would be left of the apple after subtracting every sensible quality. Take away the colour, since colour is only ever something seen. Take away the taste, the smell, the felt firmness, the shape, since each of those is only ever something sensed. After everything perceptible has been removed, the materialist says there is still *something* there, the bare apple-stuff, the substrate that was wearing all those qualities. Berkeley's reply is that this leftover is not a mysterious deep thing; it is nothing at all. Strip a thing of every quality that could ever be perceived and what remains is not a hidden core but an empty word. The apple was the qualities. There was never an apple-in-itself wearing them."
        },
        {
          "p": "This is the famous slogan, stated in his own words in *Principles* §3, the line the rest of the system hangs from. Asking what \"exists\" means for a sensible thing, Berkeley answers by example: \"The table I write on I say exists, that is, I see and feel it; and if I were out of my study I should say it existed, meaning thereby that if I was in my study I might perceive it, or that some other spirit actually does perceive it.\" For a sensible thing, to exist just *is* to be perceived, or to be perceivable by some mind. \"For as to what is said of the absolute existence of unthinking things without any relation to their being perceived, that seems perfectly unintelligible. Their ESSE is PERCIPI, nor is it possible they should have any existence out of the minds or thinking things which perceive them\" (*Principles* §3). *Esse est percipi*: to be is to be perceived. The being of a table, a tree, an apple is not some property it has off on its own; its being is its being-perceived, and the notion of it existing wholly unperceived is, Berkeley says, not false but unintelligible, a string of words that fails to describe anything."
        },
        {
          "p": "It helps to see what the slogan does *not* claim, since this is exactly where it gets misread. It does not say the apple is a hallucination, or that wishing changes it, or that it pops out of existence the instant a person blinks. The claim is narrower and stranger: that the *kind of being* a sensible thing has is the being of something perceived, the way the being of a pain is to be felt. No one looks for the pain that exists when nobody feels it; a pain just is a felt thing. Berkeley says the table is the same. Its existence and its being-perceived are not two facts, one causing the other. They are one fact under two descriptions."
        }
      ]
    },
    {
      "num": 3,
      "title": "Why there is no matter",
      "epigraph": {
        "text": "\"An idea can be like nothing but an idea; a colour or figure can be like nothing but another colour or figure.\"",
        "attribution": "— George Berkeley, A Treatise Concerning the Principles of Human Knowledge, §8 (1710)"
      },
      "blocks": [
        {
          "p": "Berkeley's opponent is not the plain person but the philosopher, and the philosopher's picture is precise. On that picture there are two tables. There is the table of experience, the seen and felt one, made of ideas in the mind. And there is, behind it, a second table made of matter: an inert, unthinking, mind-independent substance, which exists whether or not anyone perceives it, which causes the ideas of the first table, and which the ideas roughly copy. Matter is the substrate, the stuff the perceptible qualities are pinned to, the thing that goes on existing in the dark and empty room. This is Locke's picture and Newton's and common educated opinion's, and it is genuinely powerful, because the material substrate is what seems to explain why experience is orderly, why it persists, and why two people share one world. Berkeley has to dismantle all of that, and he does it with two strokes."
        },
        {
          "p": "The first stroke is to ask the materialist a simple question and watch the answer fail. Berkeley grants the whole framework and applies the empiricist's own standard: every legitimate idea must be traceable to some experience that gave it. So, from what experience does the idea of *matter* come? \"What are the fore-mentioned objects but the things we perceive by sense? and what do we PERCEIVE BESIDES OUR OWN IDEAS OR SENSATIONS? and is it not plainly repugnant that any one of these, or any combination of them, should exist unperceived?\" (*Principles* §4). Everything ever delivered by any sense is a sensation, an idea. No one has ever perceived the *matter* under the sensations, and no one could, because to perceive it would be to turn it into one more sensation. The supposed substrate is by definition the one thing that can never appear in experience. By the empiricist's own rule, an idea with no possible experience behind it is empty, and so the idea of matter is empty: a word, not a thing."
        },
        {
          "p": "The second stroke closes the last escape, the idea that even if matter cannot be perceived, our perceptions might still *resemble* it, be little copies of the unseen stuff. Berkeley's answer is the hinge of the entire philosophy, and it is one short sentence: \"an idea can be like nothing but an idea; a colour or figure can be like nothing but another colour or figure\" (*Principles* §8). Resemblance holds only between things of the same kind. A colour can resemble a colour, a sound a sound, a shape a shape. But matter is by hypothesis *not* an idea, not a colour or sound or shape, but a colourless, soundless, unsensed substance. So our ideas cannot resemble it, any more than the colour blue can resemble a smell or a number. The copy theory dies on contact: there can be no likeness between a perceived idea and an unperceived non-idea, because likeness across that gap is not a hard fact to establish but a meaningless one. Matter cannot be perceived, and it cannot even be the thing our perceptions copy. Nothing is left for it to do."
        },
        {
          "p": "From those two strokes the conclusion is forced. \"From what has been said it follows there is NOT ANY OTHER SUBSTANCE THAN SPIRIT, or that which perceives,\" because \"for an idea to exist in an unperceiving thing is a manifest contradiction, for TO HAVE AN IDEA IS ALL ONE AS TO PERCEIVE\" (*Principles* §7). The qualities that were supposed to live in matter (colour, shape, motion) are ideas, and ideas can exist only in something that perceives, so they cannot exist in an unperceiving substance. There is no unthinking substratum holding them up. \"The very notion of what is called MATTER or CORPOREAL SUBSTANCE, involves a contradiction in it\" (*Principles* §9). Matter is not merely unproven or unknowable. It is, on examination, a self-cancelling idea, like a round square: unperceived perceptions, a colour that no one could ever see."
        },
        {
          "p": "There is one more target, because the cleverest materialists had a fallback, and Berkeley takes it too. Some philosophers (Locke among them) divided the qualities of a thing in two. Primary qualities (extension, figure, motion, rest, solidity, number) they took to be really in the material object, genuinely out there, with our ideas copying them. Secondary qualities (colour, sound, taste, smell) they admitted were only in the mind, sensations stirred up in us by the primary ones. Berkeley accepts the second half and then turns it against the first. Try, he says, to picture an object that has *only* primary qualities: a thing with shape and motion but no colour at all, no degree of light or dark, nothing visible or tangible. It cannot be done. Extension and figure come to us always wrapped in colour and felt texture; the primary qualities cannot even be imagined stripped of the secondary ones, which means they are no more separable from the mind than colour is. \"Extension, figure, and motion are ONLY IDEAS EXISTING IN THE MIND\" (*Principles* §9). The line that was supposed to leave at least the geometry of matter standing in the real world erases itself. All qualities are mind-dependent. There is no quality left over to hand to matter, and so, a third time, there is no matter."
        }
      ]
    },
    {
      "num": 4,
      "title": "Then where does the world go when no one is looking",
      "epigraph": {
        "text": "\"There may be some other spirit that perceives them though we do not.\"",
        "attribution": "— George Berkeley, A Treatise Concerning the Principles of Human Knowledge, §48 (1710)"
      },
      "blocks": [
        {
          "p": "The objection everyone reaches for first, Berkeley reached before everyone. If to be is to be perceived, then the moment no one perceives a thing, it stops existing. Leave the study and the table winks out. Shut every eye in the house and the furniture is annihilated, to be created again when someone looks. The world would flicker on and off with attention, popping into being and out of it thousands of times a day. That is plainly absurd, and it looks like a clean refutation of the whole system. Berkeley states the objection in exactly those terms and treats it as the serious problem it is."
        },
        {
          "p": "His own version of the puzzle is sharper than the popular one. (\"If a tree falls in a forest and no one is around to hear it, does it make a sound?\" is a much later catchphrase, traceable to the early twentieth century, and Berkeley never wrote it; the falling-tree slogan is a popularization of his problem, not his sentence.) What Berkeley actually wrote is a trap for the objector. \"Surely there is nothing easier than for me to imagine trees, for instance, in a park, or books existing in a closet, and nobody by to perceive them,\" the objection runs. Berkeley agrees it is easy, and then springs the catch: \"BUT DO NOT YOU YOURSELF PERCEIVE OR THINK OF THEM ALL THE WHILE?\" (*Principles* §23). The attempt to imagine an unperceived tree fails the instant it is tried, because the imagining *is* a perceiving of the tree. To conceive the tree existing unconceived would be to conceive it and not conceive it at once, and that, Berkeley says, is \"a manifest repugnancy.\" One can no more think of a genuinely unthought-of object than one can quietly leave the room one is standing in. The objector cannot even frame the scenario he claims is obvious."
        },
        {
          "p": "That clears away the bad version of the objection, but it leaves the real one, which Berkeley owes a serious answer: granting all that, does the table still exist when *I* walk out and stop perceiving it? His answer is the keystone of the system, and it is the point where the bishop's God stops being a motive and becomes a working part. The mistake, he says, is to think that \"perceived\" means perceived *by me*. \"Though we hold indeed the objects of sense to be nothing else but ideas which cannot exist unperceived, yet we may not hence conclude they have no existence except only while they are perceived by US, since there may be some other spirit that perceives them though we do not\" (*Principles* §48). To be is to be perceived by *some* mind, not necessarily a human one. \"Wherever bodies are said to have no existence without the mind, I would not be understood to mean this or that particular mind, but ALL MINDS WHATSOEVER.\" There is a mind that perceives everything, always, without a blink: God. The table does not flicker out when the room empties, because the room is never empty. God perceives it. The world is held steadily in being by the divine mind, and human perceiving comes and goes within a perceiving that never stops."
        },
        {
          "p": "Berkeley does not simply assert God to plug the hole; he argues to God from the texture of ordinary experience, and the argument is the part of the system that keeps it from collapsing into the claim that the world is just one's private dream. The ideas of sense, he points out, are not up to us the way the ideas of imagination are. \"When in broad daylight I open my eyes, it is not in my power to choose whether I shall see or no, or to determine what particular objects shall present themselves to my view\" (*Principles* §29). A person can summon a unicorn in imagination and banish it at will, but cannot, eyes open in daylight, decide to stop seeing the room or to see a different one. The ideas of sense are forced on us, from outside the will. \"There is therefore some other will or spirit that produces them.\" And those forced ideas do not arrive in chaos; they come \"in a regular train or series,\" steady, ordered, coherent, and \"these we learn by experience\" as \"the laws of nature\" (*Principles* §30). The order and the involuntariness of experience are the evidence: ideas this reliable, this independent of any human wish, this law-governed, must be authored by a mind vastly greater than ours."
        },
        {
          "p": "This is what separates Berkeley's idealism from solipsism (the lonely view that nothing exists but one's own mind and its contents). The reason the world feels solid, public, and indifferent to our wishes is not that it is made of inert matter; it is that it is made of God's ideas, communicated to our minds in a fixed order we did not write and cannot edit. Two people see one table because God presents the same ordered ideas to both. The stone is hard against the foot because God's perceiving sustains exactly that idea of resistance, on schedule, whether or not anyone wants it. Everything matter was hired to explain (order, persistence, the shared single world) Berkeley re-explains as the steady activity of a perceiving God. The matter is gone. The work it did is being done by something that, on Berkeley's view, was doing it all along."
        }
      ]
    },
    {
      "num": 5,
      "title": "The world is mental, not unreal",
      "epigraph": {
        "text": "\"Whatever we see, feel, hear, or anywise conceive or understand remains as secure as ever, and is as real as ever.\"",
        "attribution": "— George Berkeley, A Treatise Concerning the Principles of Human Knowledge, §34 (1710)"
      },
      "blocks": [
        {
          "p": "The deepest misunderstanding of Berkeley, and the one his framing has fought from his own century to this one, is that he made the world unreal, a dream, a phantom show, a denial that anything is really there. He spent whole sections of the *Principles* heading it off, because he saw it coming. The objection he quotes against himself is precisely this: that on his principles \"all that is real and substantial in nature is banished out of the world,\" that the sun and moon, houses and rivers and mountains and our own bodies, become \"so many chimeras and illusions on the fancy\" (*Principles* §34). If the table is just ideas, surely the table is not really *there*."
        },
        {
          "p": "His answer could not be flatter. \"By the principles premised we are not deprived of any one thing in nature. Whatever we see, feel, hear, or anywise conceive or understand remains as secure as ever, and is as real as ever. There is a RERUM NATURA\" (a nature of things, a real world) \"and the distinction between realities and chimeras retains its full force\" (*Principles* §34). And again, removing all doubt about what is and is not being denied: \"I do not argue against the existence of any one thing that we can apprehend either by sense or reflexion. That the things I see with my eyes and touch with my hands do exist, really exist, I make not the least question. The only thing whose existence we deny is that which philosophers call MATTER or corporeal substance\" (*Principles* §35). Berkeley does not subtract the tree. He subtracts the matter the philosophers added *behind* the tree. The tree, which is what anyone ever actually meets, stays exactly where it was, exactly as solid, exactly as real. Only the invisible extra layer, the one nobody ever perceived anyway, is gone, and Berkeley's claim is that nobody will miss it, because nobody was using it for anything but \"trifling and disputation.\""
        },
        {
          "p": "He still owes an account of the difference between real things and mere fancies, since both are now ideas, and he gives one without bringing matter back. A real thing differs from an imagined one not by being made of different stuff but by *how the idea behaves*. \"The ideas imprinted on the Senses by the Author of nature are called REAL THINGS; and those excited in the imagination being less regular, vivid, and constant, are more properly termed IDEAS, or IMAGES OF THINGS\" (*Principles* §33). The ideas of sense are stronger, steadier, more orderly, more coherent, and crucially not up to us; the ideas of imagination are faint, fitful, and obey the will. The real sun is the one that rises on schedule whether or not anyone wants it, presented in the fixed order of nature by God. \"The sun that I see by day is the real sun, and that which I imagine by night is the idea of the former\" (*Principles* §36). Reality is not a deeper material backing behind the idea; it is a property of the idea itself, its force and order and independence from our wishes. The real is the vivid, law-bound, God-given; the unreal is the faint and self-summoned. Matter is needed for neither."
        },
        {
          "p": "Berkeley restated the whole case for a wider audience in the *Three Dialogues*, and the names of the two speakers carry the argument. Hylas (from the Greek for matter) defends material substance and is talked out of it step by step. Philonous (Greek for lover of mind) is Berkeley, and at the end he draws the conclusion the whole system was built to reach: from his own existence and the order of his ideas, he says, \"I do, by an act of reason, necessarily infer the existence of a God, and of all created things in the mind of God\" (Third Dialogue). The subtitle of the book states the target without disguise: it is written \"in opposition to sceptics and atheists.\" The sceptic is answered because Berkeley has closed the gap between perception and reality that scepticism feeds on; on the material picture, one can always worry that the real table is forever hidden behind the perceived one, but if the table just *is* the perceived one, the worry has nothing to grip. The atheist is answered because the world, drained of self-running matter, can be sustained only by a mind. Berkeley's idealism is not a slide toward unreality. It is, in his hands, the cure for it, and a proof of God besides."
        },
        {
          "p": "The famous attempt to refute him shows how thoroughly the position was misheard, and how hard it is to land a blow on. Samuel Johnson, told of Berkeley's doctrine, is reported by his biographer James Boswell to have kicked a large stone hard enough to rebound from it and declared, \"I refute it thus.\" (Boswell records the episode in his *Life of Johnson*, published in 1791.) The gesture is beloved and proves nothing, because the stone's hardness, its resistance, the recoil felt in the foot, are precisely the sensible ideas Berkeley was talking about, sustained in their lawful order by God. Berkeley never denied the stone or the felt resistance; he denied only that there is unperceived matter under them. Johnson kicked an idea, felt an idea, and announced a refutation of a claim Berkeley had not made. The episode is the perfect monument to the standard misreading: it treats immaterialism as the denial of the physical world, when immaterialism is the denial only of the *matter* the philosophers had buried beneath it."
        }
      ]
    },
    {
      "num": 6,
      "title": "What Berkeley left to Hume",
      "epigraph": {
        "text": "\"There is not any other substance than spirit, or that which perceives.\"",
        "attribution": "— George Berkeley, A Treatise Concerning the Principles of Human Knowledge, §7 (1710)"
      },
      "blocks": [
        {
          "p": "Berkeley sits in the middle of a line of three, and his place in it is the cleanest way to see exactly what he did and exactly where he stopped. The line is the British empiricists. Locke opened it by arguing that the mind comes into the world empty and every idea is written on it by experience, with no knowledge stamped in at birth. He cleared away innate ideas and the rationalists' confidence that pure reason could deliver the world unaided. But Locke kept two things Berkeley would not: material substance, the stuff behind the ideas, and the primary-secondary qualities distinction that left geometry and motion really out there in the matter. Locke ran the empiricist program partway and then planted his feet."
        },
        {
          "p": "Berkeley took Locke's own rule (every idea must answer to an experience) and refused to plant his feet where Locke had. He turned the rule on matter itself and found that matter answers to no experience and resembles nothing perceivable, and so he deleted it (Chapter 3). One step past Locke, and the material world is gone, replaced by minds, ideas, and God. This is the thing to hold onto about Berkeley: he is not a wild man inventing a fantasy. He is the most *consistent* empiricist of the three so far, the one who took the shared starting point and followed it where Locke flinched. His result looks insane and his method is the soberest possible: he simply declined to make an exception for the one idea everyone wanted to keep."
        },
        {
          "p": "But Berkeley flinched too, and where he flinched fixes his position in the line, because the next man would not flinch there either. Berkeley dissolved *material* substance, the stuff behind the ideas of the outer world. He did not dissolve *spiritual* substance. Minds, on his account, are perfectly real things: the self is a genuine enduring spirit that has the ideas, God is the supreme spirit that sustains them, and these are the bedrock the whole system rests on. He had argued that an unperceived material substrate was an empty idea answering to no experience. He did not turn that same question on the perceiving self. He never asked: from what experience does the idea of the *mind*, the bare self that supposedly has all the ideas, derive? He kept spirit as solid ground while melting matter out from under everything else."
        },
        {
          "p": "That unasked question is precisely what David Hume would ask a generation later, and it is why Berkeley leads into Hume as directly as Locke leads into Berkeley. Hume takes Berkeley's exact tool, the demand that every idea show the experience behind it, and turns it on the one substance Berkeley had spared. He looks inward for the self that has the perceptions and finds only the perceptions, never the perceiver, and concludes that the self is no more a real underlying substance than matter was: it is a bundle of passing perceptions and nothing else. The solvent Berkeley used on matter, Hume uses on mind. Berkeley pulled the floor from under the outer world and left the inner self standing on God; Hume pulls the floor from under the self as well, and does not put God back. The era's empiricism runs downhill from Locke through Berkeley to Hume, each man applying the same rule one notch more relentlessly than the last, until at the bottom there is no matter, no self, and no rational ground for expecting tomorrow to resemble today. (The Hume read picks the story up there.)"
        },
        {
          "p": "What Berkeley himself leaves behind is one of the strangest and most durable positions in philosophy, and its durability is the surprise. It was met, in his lifetime and long after, as a paradox to be waved away, an obvious error whose flaw any sensible person could feel even if no one could name it. The naming never quite came. Generation after generation has set out to refute *esse est percipi* and come back having kicked a stone. The argument that there is no matter, only minds and their ideas, turns out to be far harder to break than to mock, because each step is built from premises the materialist already granted: that all we ever perceive is ideas, that an idea can resemble only an idea, that a thing stripped of every sensible quality is nothing. Berkeley assembled those admitted pieces into a conclusion almost no one can accept and almost no one can defeat. He was a bishop who set out to save common sense and God from the philosophers, and he did it by proving, from the philosophers' own starting points, that the solid world they were so sure of was made of mind the whole time."
        }
      ]
    }
  ]
}
