'use client'

// The Battle of Camden (August 16, 1780), battle sections · American
// Revolution, southern campaign. The low point: the wrong-road march that beat
// the army, the hour in the pines, and the reputation that died with the army.
// Produced through the war content pipeline (audits/war-content-pipeline.md):
// fact pack → author → critic gates (fact-check + storytelling +
// newcomer-clarity + framing, parallel) → reconcile → revise. Data only;
// rendered by the shared <BattleSectionReader>. House voice: no em-dashes;
// side-tags combatants only, once on first mention per section. HANDLE-WITH-CARE
// framings per the fact pack: Gates was 53, never "sixty"; strength "between
// three and four thousand, about two-thirds militia," anchored to the 3,052
// return, never "7,000" as a strength claim; the route choice told as
// defensible-in-purpose, disastrous-in-effect, not pure stupidity; the molasses
// meal kept at Williams's level (a hungry army given the wrong meal on the wrong
// night), never "dysentery decided the battle"; the militia rout told without
// the "cowards" sneer; the deployment error as historiographical consensus;
// de Kalb "some eleven wounds" credited to du Buysson; the Gates ride carries
// BOTH the documented rally attempts and Hamilton's mockery, never simple
// cowardice nor blameless; NO de Kalb deathbed quote, NO Cornwallis spoken
// tribute, NO Washington-at-the-grave line (all apocrypha) — only du Buysson's
// documented British civility; Cowpens planted (militia asked the impossible)
// but never narrated. Quotes are attributed to their source (Williams's 1822
// Narrative for the council/return/route/militia lines; Hamilton's Sept 6, 1780
// letter; Watts's 1834 pension statement; Tarleton's and Stedman's histories;
// du Buysson's captivity letter). NO map blocks (maps come later); inline
// figures are born-verified artifacts/portraits only.
// Sources: audits/war-pipeline/rev-camden-factpack.md.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const CAMDEN_NARR: Record<string, Narr> = {
  'the-wrong-road': {
    eyebrow: 'Camden · Before',
    title: 'The march that beat the army',
    blocks: [
      { p: 'On May 12, 1780, Charleston surrendered with the entire southern Continental army, more than 5,000 men, the largest American surrender of the war. Three months later, the southern colonies had no field army at all and a British conquest that looked complete on paper: South Carolina garrisoned, Georgia already royal again, British posts strung across the interior with Camden the most important depot among them. Congress had to build a second army from nothing, and to command it, in June 1780, it reached for the most famous name available.' },
      { p: 'That name was Horatio Gates (American), the "hero of Saratoga." His victory over a British army in upstate New York in 1777 had been the turning point of the war in the North and the proof that brought France into the war; it had also made him, for a faction in Congress, a rival to George Washington himself. Now the Continental Congress (the governing body of the thirteen colonies during the war) voted him the southern command without consulting Washington, who wanted Nathanael Greene (American) for the job. The choice carried a buried irony that the next two months would expose. Gates was a careful administrator who had won his great victory largely on the strength of defensive ground and someone else\'s fighting; the southern command would ask him to maneuver a half-trained army in the open, which was the one thing his reputation had never actually tested. He was fifty-three, not the sixty of later legend.' },
      { fig: '/war-img/rev-camden-dekalb.jpg', cap: 'Johann de Kalb, the French-army professional who built and held the southern army before Gates ever arrived, then died commanding its right wing. He had crossed the Atlantic with Lafayette in 1777, and would be buried at Camden with full military honors, British officers attending.', credit: 'NYPL print after the Peale likeness · public domain · Wikimedia Commons' },
      { p: 'The army Gates inherited was not nothing, and it was not his work. It had been built and held together by Johann de Kalb (American), a Bavarian-born professional soldier in French service who had crossed the Atlantic with the young Marquis de Lafayette in 1777. In the spring of 1780 de Kalb had marched the Maryland and Delaware Continental division, roughly 1,400 ragged, half-starved veterans who were the cream of Washington\'s infantry, south from Morristown, too late to save Charleston, and had then kept the force alive for months on next to no food. "I have struggled with a good many difficulties for Provisions," he wrote. He had judged an immediate move on Camden too risky without supplies and meant, if he moved at all, to swing west through the friendly, well-fed Salisbury and Charlotte country. Gates superseded him on arrival on July 25, 1780. De Kalb took it as a professional, said nothing on the record, and took the right wing under the new commander.' },
      { p: 'Gates\'s own orders christened the force the "Grand Army," and he acted as though it numbered the roughly 7,000 of his paper returns. The reality was less than half that, and most of it was militia, the part-time citizen soldiers who turned out with their own muskets and could go home when their term ran out. Two days after taking command, on July 27, Gates marched, and the first and largest of his decisions was which road to take.' },
      { p: 'He chose the direct road to Camden. It was about fifty miles shorter than the alternative, and it ran through pine-barren country that Otho Holland Williams (American), Gates\'s deputy adjutant general and the man whose 1822 Narrative is the indispensable American account of the campaign, described as "by nature barren, abounding with sandy plains, intersected by swamps, and very thinly inhabited." It was also politically hostile country, thin in the Whig farms that fed and recruited a Patriot army. His officers, backing de Kalb\'s earlier plan, urged the longer western route through Salisbury and Charlotte: Whig country, full of food and potential recruits. They put the objection in writing. Gates promised a council of officers to discuss it and never called one.' },
      { p: 'The choice was not simple stupidity, whatever it became in the retelling. Gates believed supply assurances he had been given by North Carolina officials, and the direct road was the fast way to cover Caswell\'s exposed North Carolina militia, with whom he made junction on August 7. The trouble was that the supplies were not there. The army marched through stripped country on green corn, unripe peaches, and the lean cattle it could find in the woods, with flour almost nonexistent. By the standard accounts, officers thickened their soup with the hair powder out of their own kits. The army that would fight at Camden had been sick and hungry for weeks before it ever saw the enemy.' },
      { p: 'The hunger set the trap for the most famous detail of the campaign, and it is one worth keeping at its honest size. On the evening of August 15, with no rum to issue, the commissaries served out a gill (about a quarter pint) of molasses per man, with cornmeal and fresh beef. Williams recorded it plainly: "one gill of molasses per man, and a full ration of corn meal and meat, were issued to the army previous to their march, which commenced, according to orders, at about ten o\'clock at night of the 15th." The quick-baked bread, the half-cooked beef, and the molasses worked through the men\'s bowels all through the night march, and soldiers fell out of the ranks in the dark. The popular version, that mass dysentery or the molasses itself lost the battle, is an embellishment on what Williams actually wrote. The true and bad-enough version is a hungry army given exactly the wrong meal on the wrong night.' },
      { p: 'That night march had a destination short of a battle. At Rugeley\'s Mill, also called Clermont, about thirteen miles north of Camden, Williams brought Gates the field return, the count of men actually present and fit. It showed 3,052 rank and file fit for duty, against the roughly 7,000 Gates had supposed. By Williams\'s recollection Gates answered that there were enough for his purpose, and ordered the army to march at 10 p.m. to seize a defensible position at Saunders Creek, north of Camden. He was not, that night, planning a head-on dawn assault on the town. He even subtracted from his own strength the day before, detaching about 400 men, including 100 Maryland Continentals, to support Sumter\'s raid on the British supply line.' },
      { p: 'What Gates did not know was that Cornwallis (British) had decided to do exactly the same thing in the opposite direction. Warned by Lord Rawdon (British) that Gates was bearing down on Camden, the earl had raced up from Charleston, reached the town on the night of August 13, and taken personal command of about 2,200 fit men. Rather than abandon his depot, he resolved to attack, and he too ordered his army to march at 10 p.m. on August 15, to surprise Gates at Rugeley\'s Mill. Both armies set out the same hour, on the same road, marching toward each other in the dark.' },
      { p: 'The heads of the two columns ran together at about two in the morning, some five miles north of Camden on the Great Wagon Road, the long road that was the spine of the whole backcountry. Tarleton\'s dragoons were at the British point. At the American point, unusually, Gates had put the cavalry of Armand\'s Legion (American), the remnant of Pulaski\'s corps under the French volunteer Charles Armand. In the firefight the cavalry recoiled into the infantry behind them; the flanking light infantry under Lt. Col. Charles Porterfield (American) of Virginia steadied the line, and Porterfield was mortally wounded, dying of the wound later in British captivity. Then both armies pulled apart to wait for daylight, each now knowing exactly where the other stood.' },
      { p: 'Prisoners told Gates he faced Cornwallis with about 3,000 men, more than he actually had. Gates called his general officers together in the dark and, by Williams\'s account, asked them, "Gentlemen, what is best to be done?" Only Brigadier General Edward Stevens (American) of the Virginia militia answered aloud: "Gentlemen, is it not too late now to do any thing but fight?" No one, de Kalb included, whatever his private doubts, argued for retreat. And in truth a night retreat, in contact, with raw militia, would have been its own disaster. The army that had been beaten by the road now waited in the dark for the light that would finish the work.' },
      { pill: '/war-revolution/battles/charleston', plabel: 'Charleston: the first southern army, lost three months before' },
    ],
    meanwhile: { region: 'The South Carolina backcountry', title: 'The war was already burning', body: 'Camden did not start the fire in the South, and its loss did not put it out. While Gates marched, the backcountry was already at war: at Ramsour\'s Mill in June, Patriot militia broke a much larger Loyalist rising; at Huck\'s Defeat in July, backcountry men destroyed a hated Legion detachment and electrified the region; Sumter mauled a garrison at Hanging Rock in August. The conquered province was rising before Gates ever reached it, which is why the destruction of his field army, total as it was, did not end the war it was sent to fight.' },
  },

  'the-hour': {
    eyebrow: 'Camden · The battle',
    title: 'An hour in the pines',
    blocks: [
      { p: 'The ground at first light favored the smaller army. Both lines drew up in open, park-like longleaf pinewood astride the Great Wagon Road, with both flanks resting on the boggy margins of Gum Swamp. The swamps made the front narrow, and a narrow front protected the flanks of the smaller force and threw away the American advantage in numbers. The pines were open enough to march and fire through, which mattered, because it meant raw militia would have to stand in the open against what was coming.' },
      { p: 'Horatio Gates (American) drew his line by the convention every European-trained officer followed, and the convention destroyed him. By custom each army posted its best, most senior troops on its own right. So Gates put his Continentals (the full-time regulars) on the right under Johann de Kalb (American), with Gist\'s 2nd Maryland Brigade and the Delaware Regiment; the North Carolina militia held the center; and the roughly 700 Virginia militia under Edward Stevens (American), who had reached camp only two days before, held the left, with Armand\'s horse behind them and Smallwood\'s 1st Maryland Brigade in reserve on the road. Cornwallis (British) followed the same convention, posting James Webster (British) with his best regulars, the light infantry, the 23rd Royal Welch Fusiliers, and the 33rd Foot, on the British right. The two conventions met in the middle of the field with a fatal result: the rawest American troops, the militia of the left and center, now stood directly opposite the best regulars in America, while Gates\'s own best men faced the weaker British wing. With the larger militia mass, Gates paid for the symmetry and Cornwallis did not.' },
      { p: 'It is the placement historians treat as the central tactical failure of the day, and Alexander Hamilton (American) skewered it within weeks, writing privately of Gates that he had put "his best troops placed on the side strongest by nature, his worst, on that weakest by nature, and his attack made with these." A commander who knew his militia, as Greene and Daniel Morgan would soon show they did, would not have asked green men to stand in open pinewoods against a bayonet charge by veteran regiments, with no second line behind them to catch them when they broke.' },
      { p: 'They broke at once. At first light Williams (American), by his own account, urged Gates to strike Webster\'s wing while it was still shaking out into line, and Stevens\'s Virginians were ordered forward. Webster\'s regulars answered the way regulars answered: a volley, a cheer, and a bayonet charge straight at the militia. In Williams\'s words, the British advance "threw the whole body of the militia into such a panic that they generally threw down their loaded arms and fled in the utmost consternation." The word that stings is loaded: most of the Virginia militia never fired a shot. The North Carolina militia in the center went with them, all but one regiment beside the Continentals, which stood and fought. The Virginians\' total loss for the day was three wounded, the exact measure of how instantly the line dissolved.' },
      { p: 'It was not cowardice so much as arithmetic. The men were raw, many of them sick and hungry, posted in the open with no second line, and asked to receive a bayonet charge by the best infantry on the continent. One of them, the militiaman Garret Watts (American), said as much in a federal pension statement decades later, and his honesty is the truest record of the moment: "I confess I was amongst the first that fled. The cause of that I cannot tell, except that everyone I saw was about to do the same. It was instantaneous. There was no effort to rally, no encouragement to fight."' },
      { p: 'The rout of some 2,000 militia poured straight back over and around the reserve and the command post, where Gates had taken station behind his line. He and the North Carolina commander Caswell tried to rally them. An aide recorded Gates riding twenty yards behind the line to turn them, then trying again further back; Thomas Jefferson, as governor of Virginia, reported to Congress that Gates made "utmost and unremitting exertions to rally them" that "proved ineffectual." Then the flood of fleeing men carried the general away with it. Gates said he meant to re-form the army at Clermont, thirteen miles back; the mass never stopped running. From there he rode for Charlotte. What he had left on the field, he could not see, because it was happening on the far wing, in the smoke.' },
      { p: 'On the right, nobody had told the Continentals the battle was already lost. While the militia dissolved behind them, de Kalb and Gist\'s six hundred to nine hundred Marylanders and Delawares threw back Rawdon\'s (British) first attack and then counterattacked into his line, by several accounts nearly breaking it and taking some fifty prisoners; Cornwallis had to ride in personally to steady his Volunteers of Ireland. For a few minutes, on that wing alone, the Americans were winning.' },
      { p: 'Then Webster, instead of chasing the broken militia, wheeled his victorious regulars to the left and brought them down on the Continentals\' now open flank. Smallwood\'s 1st Maryland reserve, hit while it was still coming up, was driven apart from the rest and could never close the gap. The Continentals fought on in the smoke-filled pines, flanked on both sides, for the better part of an hour, which against those odds is the whole measure of what they were. De Kalb\'s horse was killed under him; a saber cut laid his head open; on foot, he kept his men in the fight and led them in a final bayonet counterattack. Only then did Cornwallis loose Tarleton\'s (British) dragoons against their rear, and the last formation on the field came apart. In Tarleton\'s own later words, "rout and slaughter ensued in every quarter."' },
      { p: 'De Kalb fell with some eleven wounds, eight from bayonets and three from musket balls, the count given by his aide, the Chevalier du Buysson, who threw himself over the fallen general, shouting his rank to stop the killing, and took wounds of his own. British soldiers were already stripping the general when officers intervened. Cornwallis had him carried into Camden and treated by his own surgeons. Of the conduct of his captors du Buysson wrote, "Lord Cornwallis and Rawdon treated us with the greatest civility." De Kalb died of his wounds in Camden on August 19 and was buried with full military honors, British officers attending the funeral. The army he had built and held together for months had outlived him on the field by about an hour.' },
      { p: 'No formed American unit left the field. But men got out: Gist took about a hundred Continentals off in a body through Gum Swamp, where the cavalry could not follow, and small parties cut their way out under officers like John Eager Howard and Robert Kirkwood, names worth holding, because they return at Cowpens five months later. Roughly half the Continentals who fought got away as individuals. The army did not.' },
    ],
    meanwhile: { region: 'The far wing, in the smoke', title: 'Two battles at once', body: 'Camden was really two battles fought a few hundred yards apart that never knew about each other. On the left and in the center, the militia broke so fast that the fight there was over before it began, three wounded the whole tally. On the right, where the Continentals never got the word, the battle was hard and very nearly won, and ran a full hour longer. The same field produced the most shameful rout and one of the most stubborn stands of the war, side by side, separated by a curtain of pine smoke.' },
  },

  'the-low-point': {
    eyebrow: 'Camden · After',
    title: 'The reputation that died with the army',
    blocks: [
      { p: 'The destruction did not stop when the line broke. Banastre Tarleton (British) loosed his Legion cavalry up the Wagon Road after the fugitives and rode the wreck down for some twenty-two miles, past Hanging Rock, sabering men and seizing wagons. A British officer present in the campaign, the commissary and historian Charles Stedman, left the record of the road afterward: "The road for some miles was strewed with the wounded and killed who had been overtaken by the legion in their pursuit. The numbers of dead horses, broken waggons, and baggage scattered on the road formed a perfect scene of horror and confusion." The army\'s entire train was lost, all seven or eight guns, some 200 wagons, the baggage, and the papers.' },
      { p: 'Two days later came the coda. On August 18, Tarleton surprised Sumter\'s (American) camp at Fishing Creek on the Catawba, the same Sumter whose raid Gates had detached 400 men to support. About 150 of Sumter\'s men were killed or wounded, and some 300 captured, the gains of the previous days all retaken; Sumter himself escaped half-dressed on an unsaddled horse and rode into Charlotte alone. In seventy-two hours the British had wiped out both organized American forces in South Carolina.' },
      { p: 'And Horatio Gates (American) was already gone. He reached Charlotte, sixty miles from the field, the evening of the battle, and Hillsborough, North Carolina, where the state government sat and where he set about collecting the wreck and calling for supplies, on August 19, about 180 miles in three days. He opened his report to Congress in the only words for it: "In the deepest Distress and Anxiety of Mind, I am obliged to acquaint your Excellency with the Total Defeat of the Troops under my Command."' },
      { p: 'The ride became the thing he was remembered for, and the man who made it so was Alexander Hamilton (American), who wrote of Gates with savage contempt three weeks after the battle: "But was there ever an instance of a General running away as Gates has done from his whole army? And was there ever so precipitous a flight? One hundred and eighty miles in three days and a half. It does admirable credit to the activity of a man at his time of life. But it disgraces the General and the Soldiers." It was lethal, and it was unfair in the way that the cleverest things often are. The same record that gives us the ride also gives us the rally: eyewitnesses and Jefferson\'s official report agree that Gates tried, with his own and Caswell\'s help, to turn the militia before the flood carried him off, and the question of where else a beaten commander should have gone but to the seat of government and the nearest supplies is a real one. Henry Lee later judged Hillsborough exactly the right place to rebuild. The fairest verdict was the one the army\'s own officers reached: more unfortunate than criminal. But Hamilton\'s line was funnier, and it was the line that stuck.' },
      { fig: '/war-img/rev-camden-greene.jpg', cap: 'Nathanael Greene, the general Washington had wanted for the South all along. Congress gave Gates the chance and then, after Camden, gave the command to Greene, who would never beat Cornwallis in a single battle and would still drive him out of the Carolinas.', credit: 'period portrait · public domain · Wikimedia Commons' },
      { p: 'Congress moved on October 5, 1780, ordering a court of inquiry into Gates\'s conduct and authorizing Washington to name a successor. Washington named Nathanael Greene (American), the man he had wanted all along, on October 22; Greene reached Charlotte and took command on December 3, 1780, finding about 2,300 men on the rolls and perhaps 1,500 fit. The court of inquiry was never actually convened. Greene and the southern officers declined to treat Gates as a criminal, Congress repealed the inquiry resolution in 1782, and Gates rejoined the main army briefly. He never held a field command again. The hero of Saratoga had ridden into the South with the largest reputation in the army and ridden out without it; his reputation died with the army he lost. He had one more private grief that autumn: his only son, Robert, died in October, weeks after the battle.' },
      { p: 'There is a turn buried in the disaster, which is why Camden matters beyond the scale of the rout. The lesson of the battle was not that militia are useless. It was narrower and more usable than that: militia, in open ground, in a main line, against a bayonet charge, with no second line to catch them, was a sentence of rout. The man who absorbed it was Daniel Morgan, who joined the southern army that autumn. Five months later, at a place called the Cowpens, he would take everything Camden had gotten wrong and invert it, putting his militia out in front, asking them for two volleys and no more, and promising them that once they had fired they could fall back behind the Continentals. He would turn Camden\'s failure into the most perfect small battle of the war. But that is another page.' },
      { p: 'For now, the ledger read all one way and still did not say what it seemed to. The second southern army in four months was destroyed; South Carolina was garrisoned, Georgia royal, North Carolina apparently open. Camden was the British high-water mark in the South. And yet Cornwallis (British) had won a province that was already burning behind him. Within days the partisan Francis Marion freed a column of Maryland prisoners from their Camden-bound escort. Within two months the over-mountain men destroyed Patrick Ferguson at Kings Mountain. Within five months Morgan won at the Cowpens, and Greene began the long campaign that would march Cornwallis out of the Carolinas and toward Yorktown. The field army was gone. The war in the South was not.' },
      { pill: '/war-revolution/battles/kings-mountain', plabel: 'Kings Mountain: the backcountry\'s answer, seven weeks later' },
    ],
    meanwhile: { region: 'Bethesda Presbyterian Church, Camden', title: 'De Kalb\'s grave', body: 'Johann de Kalb was buried at Camden in 1780 with full military honors, and there he stayed for forty-five years. In March 1825 his remains were moved to the yard of Bethesda Presbyterian Church in Camden, under a monument designed by the architect Robert Mills. The cornerstone was laid by the Marquis de Lafayette, the same young Frenchman who had crossed the Atlantic with de Kalb in 1777, then touring America as the nation\'s guest a half-century on. The man who built the army that died at Camden lies under the town the battle is named for, his grave marked by a hand that had known him at the very start.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={CAMDEN_NARR}
    id={id}
    slug="camden"
    battleName="Camden"
    date="August 16, 1780"
    theatreId="rev-battles"
    battleId="rev-camden"
    theatreHref="/war-revolution/battles"
    accent="var(--rev-battles)"
    endHref="/war-revolution?theatre=rev-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}

/* FACT LEDGER — inline section figures to fetch (NOT shipped to readers):
 *  - /war-img/rev-camden-dekalb.jpg  ["before" beat] · de Kalb portrait ·
 *      File:Maj._Gen._the_Baron_De_Kalb_(NYPL_b12349155-421541).jpg (3072×4762, PD, NYPL, after Peale) ·
 *      portrait orientation · subject to verify: Johann de Kalb. (Canonical small alt: File:Johann de Kalb.jpg, Peale 1782, 429×533.)
 *  - /war-img/rev-camden-greene.jpg  [aftermath beat] · REUSE of in-repo rev-monmouth-greene.jpg (already copied to prefix) · Nathanael Greene.
 *  NOT YET PLACED but available as born-verified artifact inlines if the image pass wants them
 *  (NO generated maps per brief; these are primary artifacts, not locators):
 *    · Faden/Tarleton 1787 PLAN of the battle: File:Plan of the battle fought near Camden, August 16th, 1780. LOC gm71000641.tif
 *      (3082×3408, PD; TIFF→convert; caption "engraved 1787, London", verify plate line).
 *    · Surviving Great Wagon Road trace: File:Great Wagon Road at Camden Battlefield.jpg
 *      (2988×5312 PORTRAIT, CC BY-SA 4.0, Pi3.124 2017 — ATTRIBUTION REQUIRED; inline only, never hero).
 */
