'use client'

// Jonesborough — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const JONESBOROUGH_NARR: Record<string, Narr> = {
  'the-last-railroad': {
    eyebrow: 'Jonesborough · The stakes',
    title: 'The Last Railroad Into Atlanta',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -85.3, lonMax: -83.5, latMin: 32.9, latMax: 34.2 },
        states: [
          { name: 'Georgia', tone: 'focus', label: 'GEORGIA', labelLon: -84.8, labelLat: 33.1 },
          { name: 'Tennessee' }, { name: 'Alabama' }, { name: 'South Carolina' }, { name: 'North Carolina' },
        ],
        dots: [
          { name: 'Jonesborough · Aug 31 – Sep 1, 1864', lat: 33.522, lon: -84.354, heavy: true, anchor: 'middle', dy: 24 },
          { name: 'Lovejoy\'s Station', lat: 33.42, lon: -84.315, color: '#8a8175', anchor: 'start' },
          { name: 'Atlanta', lat: 33.749, lon: -84.388, color: '#8a8175', anchor: 'middle', dy: -16 },
        ],
      } },




      { p: 'By the end of August 1864, after four months of marching, digging, and bleeding across the hills of north Georgia, the city of Atlanta was very nearly surrounded and still would not fall. The reason was a railroad. An army the size of the one outside Atlanta does not live off the land it stands on; it eats what the trains bring. Every cartridge, every barrel of pork, every replacement rifle that kept the Confederate defenders fed and armed came in over the rails, and a city that loses its rail supply cannot be held no matter how thick its walls. The whole campaign came down to a simple, brutal arithmetic: cut the lines into Atlanta, and Atlanta has to be abandoned.' },
      { p: 'Major General William T. Sherman, commanding the three Union armies grouped under the grand title of the Military Division of the Mississippi, had spent the summer doing exactly that, severing the rail lines into the city one by one. By late August he had cut every line but one. The survivor was the Macon &amp; Western Railroad, which ran south out of Atlanta down through a small town called Jonesborough, roughly 20 miles (32 km) below the city. (The town is spelled “Jonesborough” in the period and in every history of the battle; the modern Georgia town has shed an o and is now “Jonesboro.” The old spelling is used here for the fight.) That single line was Atlanta’s last open artery. As long as it ran, Atlanta could be fed. Sever it, and the city was finished.' },
      { p: 'Sherman could have battered himself bloody against Atlanta’s fortifications instead. He chose the railroad. Rather than assault the works head-on, he swung the bulk of his armies in a wide wheeling march to the south and west, a great curling sweep around the city’s flank (the side or end of an army’s line, as opposed to its front), aimed not at Atlanta at all but at the Macon &amp; Western near Jonesborough. The plan was unglamorous and exactly right: get astride that last railroad, tear it up beyond quick repair, and the prize would fall on its own.' },
      { fig: '/war-img/jonesborough-overview.png', cap: 'Sherman swings the bulk of his armies south and west around Atlanta to reach the Macon & Western Railroad at Jonesborough, the city’s last open supply line.', credit: 'Map: Stuff Happened' },
      { p: 'It is worth being plain about what these two armies were fighting over, because a rail junction is a thing you capture, not a thing you fight a war for. The Confederacy existed to preserve and extend slavery: eleven states had broken from the United States rather than accept any limit on the enslavement of Black people, and they built their armies to defend that. Atlanta was the Confederacy’s arsenal-and-railroad heart, where the war matériel of a slaveholding republic was forged and shipped, and Hood’s army stood in front of it to keep that war effort alive. The Union came to take the city as one more cut into the body of that republic. By the end of this story that purpose will be standing on the roads south of Atlanta in human form, thousands of people walking themselves out of bondage.' },
      { p: 'When Sherman’s army materialized down at Jonesborough, threatening the last line, General John Bell Hood (South), commanding the Confederate Army of Tennessee inside Atlanta, did the only thing he could: he sent a force to drive the Federals back off the railroad before they could break it. The man he sent was Lieutenant General William J. Hardee (South), with two corps, Hardee’s own and that of Lieutenant General Stephen D. Lee (South), no relation to the famous Lee in Virginia. (A corps is the largest building block of a Civil War army, several divisions and tens of thousands of men under one general.) Their orders were simple and desperate: clear the Federals off the Macon &amp; Western, or watch Atlanta die.' },
    ],
    meanwhile: { region: 'the Atlanta Campaign', title: 'The four months behind this town', body: 'Jonesborough did not come out of nowhere. It was the last act of the Atlanta Campaign, which had opened back in May 1864 as Sherman pushed south out of Tennessee toward the city. All summer it had been a war of maneuver, flank then dig in then flank again, across Resaca, Kennesaw Mountain, Peachtree Creek, and the fighting around Atlanta itself, with the two sides grinding each other down mile by mile. By late August both armies were worn thin and the campaign had narrowed to this one question: the last railroad. Four months of marching had funneled the whole thing down to a rail line through a town 20 miles off that most Northerners had never heard of.' },
  },

  'hardees-stand': {
    eyebrow: 'Jonesborough · August 31',
    title: 'Hardee’s Stand',
    blocks: [
      { p: 'The Union got to Jonesborough first. Major General Oliver O. Howard (North), commanding the Army of the Tennessee, one of Sherman’s three armies, reached the town ahead of the Confederates and put his men to work doing the single most important thing infantry could do in this war: digging. Entrenchment meant throwing up dirt into a defensive line, a rampart with a trench behind it, so that the men inside fight from cover while anyone who comes at them has to cross open ground. The lay of the land matters for everything that follows: Atlanta sits to the north; Jonesborough and its railroad run north to south below it; and the Flint River runs just to the west of the town. The Union army had crossed the Flint from the west to reach Jonesborough, so the Federals faced east and the Confederate attacks would come at them from that side. Howard dug in on the approaches near the river. By the time the Confederates arrived, the Federals were behind dirt and waiting.' },
      { p: 'The Confederates came up through the morning of August 31, Hardee’s (South) corps by dawn, Lee’s (South) by afternoon, and around three in the afternoon their attack opened: artillery first, then the infantry rolling forward. Lee’s corps struck the entrenched Union line and, for a moment, got somewhere, overrunning the Union picket line (the thin screen of soldiers thrown out ahead of the main line). And then it ran into the dirt. The Federals behind their entrenchments poured rifle and artillery fire into the charging ranks, and the attack came apart against the works the way attacks against works came apart all through this war.' },
      { p: 'Then the human heart of the first day, and it is documented. The Confederate infantry, having seen what one charge across that open ground cost, would not make a second one. Officers urged them forward; the men refused to renew the charge. This was an army that had been bled white over four months of retreat and slaughter, and the rank and file had learned, in their bones, the price of running at entrenched men with rifles. They had paid it once. They would not pay it again, whatever the order.' },
      { p: 'Off on the Confederate left the attack unraveled even faster. Brigadier General Mark Lowrey’s (South) division, swinging wide, ran into a wall of fire from the dismounted cavalry of Brigadier General Judson Kilpatrick (North), troopers fighting on foot with Spencer repeating rifles, lever-action weapons that fired several rounds before reloading where an ordinary rifle-musket fired one, so that a thin line of them threw out a volume of fire far beyond their numbers. Staggered by it, Lowrey’s men veered off west, crossed the Flint River, and were halted on the far bank by a Union division of the XVII Corps, the whole left wing of the attack wasted, chasing the wrong direction across a river.' },
      { h: 'Ten to One', eyebrow: 'The cost of the charge' },
      { p: 'By evening it was finished. Hardee (South) called off further assaults. The Confederate attack of August 31 had been, in the sources’ word, easily repulsed. The Union lost somewhere around 175 men killed and wounded for the whole day. The Confederates lost on the order of 1,700 to 2,200. Lee (South) alone estimated roughly 1,300 casualties in his corps, with Hardee’s corps losing several hundred more on top of that. That is something close to a ten-to-one exchange, the economics of the Civil War in a single afternoon, the cost of throwing flesh at fortifications, paid out at Jonesborough the same way it was paid at a hundred other earthwork lines.' },
      { p: 'That night Hood (South), still inside Atlanta and now afraid that Sherman might be massing to assault the city itself, made a phantom-haunted decision: around two in the morning he recalled Lee’s corps (South) from Jonesborough back to Atlanta. The threat to Atlanta was never a frontal assault. It was the railroad, and the order stripped Hardee of half his force just as the real crisis arrived. The real crisis had already happened, a few miles to the south, that very afternoon, and no one in Atlanta knew it yet.' },
      { h: 'The Federals Had Cut the Last Railroad', eyebrow: 'The act that doomed the city' },
      { p: 'While the attack out front was being shredded against the entrenchments, the corps of Major General John M. Schofield (North) and Major General David S. Stanley (North) reached the Macon &amp; Western south of the fighting and tore up the track, ripping out the rails so no train could run. The last open artery into Atlanta was severed, the city could no longer be fed or held, and Atlanta was already lost, hours before its defenders had any idea. Hardee was now to hold the field alone the next day with barely half an army.' },
    ],
    meanwhile: { region: 'the phantom threat', title: 'Hood’s middle-of-the-night order', body: 'Hood broke his own army defending against an attack that was never coming. Fixated on the idea that Sherman might mass to storm Atlanta’s fortifications head-on, Hood pulled Lee’s corps back to the city in the small hours of September 1, stripping Hardee of half his force on the very front where the real blow would land. The threat to Atlanta had never been a frontal assault. It was the railroad, and the railroad was already cut. Hood guarded the wrong door while the house was burning, and left Hardee to face a far larger Union army with about 12,000 men.' },
  },

  'the-line-breaks': {
    eyebrow: 'Jonesborough · September 1',
    title: 'The Line Breaks',
    blocks: [
      { p: 'Morning on September 1 found Lieutenant General William J. Hardee (South) in an impossible position. Lee’s corps was gone, marched back to Atlanta in the night, and Hardee was left to defend a front roughly two miles (3 km) long with about 12,000 men against a Union force far larger. He stretched his line as thin as it would go, and a line stretched that thin has a fatal feature. At one point the entrenchments bent outward into a salient, an angle that juts toward the enemy like the prow of a ship. A salient is the weak point of any defensive line, because the men holding its apex can be fired on from two directions at once and assaulted from two directions at once. Holding the apex of this one was the brigade of Brigadier General Daniel C. Govan (South).' },
      { p: 'Sometime after four in the afternoon, the blow fell on exactly that spot. The XIV Corps, a corps of Major General George H. Thomas’s (North) Army of the Cumberland, commanded by Brigadier General Jefferson C. Davis (North), went in against the salient. (This Jefferson C. Davis is the Union general of that unfortunate name; he is no relation whatever to Jefferson Davis the Confederate president, and his name comes up again before this story ends.) The attack was no clean parade-ground charge. Brigadier General William P. Carlin’s (North) division had to push forward through dense underbrush and thick woods that broke up the lines and slowed the advance, while Brigadier General James D. Morgan’s (North) division came on from the west.' },
      { fig: '/war-img/jonesborough-the-break.png', cap: 'September 1: Estey’s brigade strikes Govan’s salient from the north while Morgan’s division closes from the west, surrounding the apex of Hardee’s line.', credit: 'Map: Stuff Happened' },
      { p: 'The breakthrough came from the north. A brigade under Colonel George P. Estey (North), roughly 1,139 men, assaulted the salient from above while Morgan’s division (North) struck it from the west, the two converging on Govan’s apex from two sides at once. Estey’s regiments overran the Confederates holding the point and punched clean through, and with Morgan’s men closing from the other face, the salient was suddenly not a defensive angle but a trap. Govan’s brigade (South), the whole apex of Hardee’s line, was surrounded inside it.' },
      { p: 'What followed was rare: not a position taken, but a brigade taken. Govan (South) himself and roughly 600 of his men were swept up as prisoners, along with about eight cannon, among them Key’s Arkansas Battery and Swett’s Mississippi Battery. A brigadier general captured with the bulk of his command, guns and colors and all, was an entire piece of the Confederate line scooped up off the field and marched to the rear.' },
      { p: 'The break did not run all the way through, though, and the reason was Major General Patrick Cleburne (South), “the Stonewall of the West,” the most respected fighting general in Hood’s army. Cleburne led the Tennessee brigade of Brigadier General Alfred J. Vaughan (South) into the gap and halted the Federal advance before it could roll up the rest of the line, while on the eastern sector another Confederate brigade rallied and threw back a Union brigade coming at it. The break was contained, but Hardee’s line was shattered, and the men who plugged the hole could not undo what the capture of Govan’s brigade meant. There is a private grief folded into Cleburne’s stand here: three months later, on November 30, at Franklin, Tennessee, Cleburne would be killed leading his men against another set of entrenchments. The Confederate cemetery at Jonesboro that holds this battle’s dead bears his name.' },
      { pill: '/war-civil-war/western/franklin', plabel: 'Franklin: where Cleburne fell, three months later' },
      { p: 'The Union did not finish the job it might have. Major General David S. Stanley’s (North) IV Corps came up slowly through the thick woods on the east, and rather than driving in to cut off Hardee’s whole battered corps, the Federals dug in instead of exploiting the breakthrough. It was a missed chance to bag everything Hardee had left. Hardee’s line was broken; his army was not destroyed. That distinction would matter for the rest of the war.' },
    ],
    meanwhile: { region: 'a brigade taken whole', title: 'Govan goes to the rear', body: 'Positions changed hands in this war by the hundreds; whole brigades, with their general, did not. When Estey’s and Morgan’s men closed the salient around Govan’s apex, what they captured was not a hill or a road but a piece of the Confederate army intact: Brigadier General Daniel Govan (South) himself, roughly 600 of his men, about eight guns, and the colors. An entire chunk of Hardee’s line was scooped up off the field and marched to the Union rear. Govan would later be exchanged and return to the war, but the brigade that held the apex was gone, and the line it had anchored was shattered.' },
  },

  'atlanta-is-ours': {
    eyebrow: 'Jonesborough · September 2–3',
    title: 'Atlanta Is Ours',
    blocks: [
      { p: 'The night of September 1, Lieutenant General William J. Hardee (South) did the one thing left to do: he slipped away. Undetected in the dark, he pulled his broken corps south down the railroad to Lovejoy’s Station and was gone before the Federals knew it.' },
      { p: 'That same night, the news everyone had been marching toward for four months finally arrived inside Atlanta. With the last railroad cut at Jonesborough, the city could not be supplied and could not be held, and General John Bell Hood (South) ordered it abandoned. His garrison marched out to the north of the battlefield, by the McDonough Road, in the dark. Before they left, the Confederates destroyed what they could not carry, torching their own stores and ordnance so the Union could not have them. The most spectacular casualty of that demolition was a trapped ammunition train: locomotives and boxcars loaded with ammunition, set ablaze in the yard, that went up in a chain of explosions so enormous the ground shook and the sound carried for miles into the night. It is the war’s iconic image of a city being abandoned to the enemy, the one later generations would recognize from its dramatization in *Gone with the Wind*, a sky full of fire over Atlanta as the army that held it walked away.' },
      { p: 'On September 2, the Union walked in. The XX Corps under Major General Henry W. Slocum (North), the force Sherman had left behind north of the city when he swung the rest of his armies south, occupied Atlanta, and Slocum sent off the first word that the city had fallen. The thing four months of campaigning had been for was done: Atlanta was in Union hands.' },
      { h: 'The Four Words', eyebrow: 'Sherman’s telegram' },
      { p: 'And then Sherman sent the telegram. To Washington, in the first days of September, went the four words that did as much for the Union cause as any victory of the year:' },
      { p: '“Atlanta is ours, and fairly won.”', q: true },
      { p: 'Sherman, to Washington, early September 1864', i: true },
      { p: 'The North was living through a hard summer when those four words arrived. The summer of 1864 had been a catastrophe of morale. The Union’s overall commander, Ulysses S. Grant, had driven his Overland Campaign in Virginia to a bloody stalemate in the trenches around Petersburg, with casualty lists longer than anything the country had ever seen and no victory to show for them. The North was sick of the war. And Abraham Lincoln was facing reelection in November and fully expected to lose. As late as August 23, barely a week before Jonesborough, Lincoln wrote privately that it seemed exceedingly probable he would not be reelected. He had his cabinet sign, sight unseen, a memorandum pledging to cooperate with whoever beat him.' },
      { p: 'Atlanta’s fall reversed all of it, overnight. The most-covered Northern victory of the year landed in the middle of a presidential campaign and detonated the case against the war. The opposition Democratic Party had built its platform on a single declaration, that the war was a failure, and demanded a negotiated peace. Their nominee, George B. McClellan, the army’s own former commander, repudiated the peace plank, but the platform was the message. And the platform meant something specific: a negotiated peace in 1864 would have meant leaving the Confederacy in existence and slavery intact. The Union the Democrats offered was a Union that stopped fighting before it finished the thing it had started, the abolition of slavery.' },
      { p: 'The fall of Atlanta blew that platform to pieces. Northern morale surged on the news, Lincoln made emancipation a central issue of the campaign rather than hiding from it, and in November he won not narrowly but decisively, 212 electoral votes to 21, with around 55 percent of the popular vote. The man who had expected to lose carried the country. And because he carried it, the war would be fought through to the end of slavery rather than negotiated to preserve it; the Thirteenth Amendment, abolishing slavery, followed. The battle of Jonesborough, by taking Atlanta, secured that outcome. A rail line cut south of a Georgia town turned a presidential election, and the election decided whether four million people would be freed or left in bondage.' },
      { pill: '/war-civil-war/off-the-battlefield/emancipation', plabel: 'Emancipation: the cause the 1864 election turned on' },
    ],
    meanwhile: { region: 'the army that got away', title: 'Hardee’s defense saved Hood’s men', body: 'There is one honest caveat to all this. Hardee’s (South) stubborn defense on September 1, broken as it was, bought time, enough for Hood (South) to evacuate his Army of Tennessee intact down to Lovejoy’s Station rather than be trapped and destroyed in Atlanta. Some historians have argued that the September 1 fight was, narrowly, a Confederate tactical success on those grounds: Hardee held off a much larger force long enough to save the army. It is a tactical footnote under an uncontested strategic verdict. Jonesborough took the city; it did not take the army, which would march off to fight again, and die, at Franklin and Nashville that winter. Sherman won the prize. Hood saved his men to lose them somewhere else.' },
  },

  'what-it-decided': {
    eyebrow: 'Jonesborough · The meaning',
    title: 'What It Decided',
    blocks: [
      { p: 'Jonesborough cut the last railroad into Atlanta and forced Hood (South) to abandon the city the night of September 1; Atlanta fell on September 2. It was the decisive, climactic battle of the Atlanta Campaign, and, by way of the election it helped decide, one of the most politically consequential battles of the entire war.' },
      { p: 'The strategic payoff was enormous. Atlanta was the Confederacy’s arsenal and rail heart in the Western theater, and its loss was a wound the South could not close. With the city taken, Sherman rested his armies, burned Atlanta’s war infrastructure, and in November set out from its ruins on the March to the Sea, the long destructive sweep across Georgia to Savannah that cut the Confederacy’s heart out and broke the will of the country behind the lines. Jonesborough was the hinge that opened that door.' },
      { h: 'The Roads South, and the People on Them', eyebrow: 'What the victory was for' },
      { p: 'The deepest meaning of the battle is not on the railroad and not even in the election returns. It is on the roads south of Atlanta, in the months Jonesborough set in motion, and it answers the question this story opened with: what these two armies were really fighting over.' },
      { p: 'From the moment Sherman’s columns moved through Georgia, enslaved people freed themselves by the thousands. They walked off the plantations that claimed to own them and into the Union columns, arriving day and night, as whole families and as lone escapees, a caravan of self-emancipated people moving with the army. And they did not merely follow; they helped. They guided the troops down hidden paths, pointed out hidden stores of food and forage, and gave Union scouts the military intelligence of people who knew the country better than any map. This was the war’s purpose walking on its own legs down the roads below Atlanta, what historians now call the largest emancipation event in United States history, the thing the fall of Atlanta set up. The railroad was the object. This was the reason: people turning the war into their own freedom, in real time, by the thousands.' },
      { h: 'Ebenezer Creek', eyebrow: 'The warning under the triumph' },
      { p: 'And then there is the documented horror that ties the whole thing into a single human knot. The Union general whose corps broke Hardee’s line and won this battle was Brigadier General Jefferson C. Davis (North) of the XIV Corps. Three months after Jonesborough, on December 9, 1864, during the March to the Sea, that same general did one of the cruelest things any Union officer did in the entire campaign. His column reached Ebenezer Creek, a deep stream he crossed on a pontoon bridge, a temporary floating bridge of boats. Hundreds of Black refugees, the self-freed people following his army toward safety, were close behind. To be rid of them, Davis ordered the pontoon bridge pulled up the moment his soldiers were across, before the refugees could cross. Trapped between the deep water in front and Confederate cavalry closing from behind, men, women, and children plunged into the creek, and many drowned.' },
      { p: 'The man who won the city that decided emancipation’s political fate also committed one of the march’s most monstrous acts against the very people the war was freeing. The same officer, the same campaign, the freedom and the cruelty bound together in one man on one stretch of Georgia ground. Jonesborough took the city, the city turned the election, the election guaranteed the end of slavery, and the general who broke the line at Jonesborough left hundreds of the freed to drown three months later. The cause of the war was slavery and its ending; the proof of the cause was the thousands walking themselves free on the roads Jonesborough opened; and the warning against any comfortable story about it is Ebenezer Creek.' },
      { pill: '/war-civil-war/off-the-battlefield/freedom-struggle', plabel: 'The freedom struggle: the people walking themselves free' },
    ],
    meanwhile: { region: 'the March to the Sea', title: 'The door Jonesborough opened', body: 'With Atlanta taken, Sherman did not stop. In November he burned the city’s war infrastructure and marched out of its ruins toward Savannah, cutting a swath across Georgia that broke the Confederacy’s will behind the lines and triggered the largest emancipation event in U.S. history. Jonesborough was the hinge on which all of that turned. The battle took a city; the city turned an election; the election guaranteed the war would be fought through to the end of slavery. A single rail line cut south of a Georgia town reached all the way to the Thirteenth Amendment, and, on a creek bank three months later, to one of the war’s most shameful betrayals of the very people it was freeing.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={JONESBOROUGH_NARR} id={id} slug="jonesborough" battleName="Jonesborough" theatreId="west" theatreHref="/war-civil-war/western" battleId="w-jonesborough" accent="#1d4ed8" />
}
