'use client'

// The Battle of Stony Point (night of July 15–16, 1779), battle sections · American
// Revolution. Produced through the war content pipeline (audits/war-content-pipeline.md):
// fact pack → author → critic gates (fact-check + storytelling + newcomer-clarity +
// framing, parallel) → reconcile → revise. Data only; rendered by the shared
// <BattleSectionReader>. House voice: no em-dashes (the one in Wayne's 2 a.m. dispatch
// is the quotation's own); American/British side-tags once on first mention per
// section, combatants only. Apocrypha control per the fact pack: the "Carry me into
// the fort" line is tradition-framed only, never verbatim speech; "little Gibraltar"
// is attributed to the literature, not a named contemporary; the British dead stay at
// the official ~20 (the period American claim of 63 noted as inflated, not used); no
// "Remember Paoli!" cry, no Pompey Lamb, no dog-slaughter order. The 1857 Chappel
// engraving carries its mandatory imagined-eighty-years-later caveat in the caption.
// Locator 1 (tactical: the point and the ferry) opens Section 1; Locator 2 (strategic:
// the Hudson stalemate) opens Section 3; the assault arrows of the locator spec are
// carried by the captions (the locator block draws no route lines).
// Sources: audits/war-pipeline/rev-stony-point-final.md (+ rev-stony-point-factpack.md).

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const STONY_POINT_NARR: Record<string, Narr> = {
  'little-gibraltar': {
    eyebrow: 'Stony Point · The lure',
    title: 'Little Gibraltar',
    blocks: [
      { fig: '/war-img/rev-stonypoint-tac1.jpg', cap: 'Stony Point is a rock surrounded by water on three sides, with a tidal marsh and a single causeway nearly closing off the fourth. Wayne\'s corps assembled at Springsteel\'s farm about a mile and a half west, then split: one column hooked south across the flooded flats, one north along the river, while Murfree\'s two companies fired at the center to pull the garrison toward the causeway. Across the river, Verplanck\'s Point held: the second half of the plan failed, and King\'s Ferry\'s east bank stayed British.', credit: 'Stuff Happened map' },
      { p: 'By the summer of 1779 the war in the north had gone quiet, and the quiet was its own kind of problem. After the battle at Monmouth, in New Jersey, the previous June, the two main armies had stopped fighting general battles in the north for good. General Sir Henry Clinton, the British commander in chief in America, held New York City. George Washington (American), commander of the Continental Army (the rebels\' full-time regular army, as opposed to part-time militia), ringed the city from New Jersey and the Hudson Highlands, the rugged stretch where the river cuts through the mountains north of the city. Neither man could force the other to fight, and Britain\'s real war effort was sliding south, toward Georgia and the Carolinas. What Clinton wanted in the north was a cheap way to hurt Washington, or to make him come out and fight on open ground where British regulars and bayonets would tell.' },
      { p: 'He went looking for it on the Hudson, because the Hudson was the seam of the whole Revolution. The river ran north from New York City up into the heart of the rebellion, and a British army sitting across it could split New England, the furnace of the war, off from the rest of the states. The American answer was the fortress complex being built at West Point, a bend in the river about 50 miles above the city, with a great iron chain (a massive linked boom floated across the river\'s full width on logs) stretched over the water to physically block ships from passing upriver. And the southernmost safe crossing below West Point was King\'s Ferry, where the river narrowed between two points of land: Stony Point on the west bank and Verplanck\'s Point on the east. King\'s Ferry was the shortcut for men, mail, and supplies moving between New England and the mid-Atlantic states; losing it forced everything onto a long detour up through the mountains.' },
      { p: 'So in late May, Clinton took about 6,000 men and a naval squadron up the river and seized both ends of the ferry. The unfinished American blockhouse (a small log fort) on Stony Point was burned and abandoned without a fight; the little garrison of about 70 men across the river at Verplanck\'s surrendered on June 1. Clinton fortified both points, garrisoned them, and waited. West Point was only a dozen miles upriver now, and his real hope was that Washington would come down and fight for the crossing. He sent raiders to burn the Connecticut coast that same month, hitting New Haven, Fairfield, and Norwalk in a week, the same bait on a longer leash. Washington refused all of it. He shifted his army to cover West Point, set up headquarters at New Windsor, and started planning a counterstroke of his own.' },
      { pill: '/war-revolution/two-armies', plabel: '1777: the campaign that made the Hudson the seam of the war' },
      { fig: '/war-img/rev-stony-point-loc-map.jpg', cap: 'A British map of Stony Point and Verplanck\'s Point drawn at the time, from the Library of Congress. The period title gives away whose map it is: the two points "taken possession of, and fortified by His Excellency Sir H— Clinton in June 1779." The river between them was King\'s Ferry, the southernmost safe crossing tying New England to the rest of the states.', credit: 'period British manuscript map · 1779 · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'The thing he meant to hit was a hard target. Stony Point is a rocky promontory rising about 150 feet straight out of the river, surrounded by water on three sides; on the landward side a tidal marsh nearly cut it off, crossed by a single causeway, and at high tide the flats flooded. The British had not built a stone fort there but a field fortification, which for an attacker is bad enough: gun batteries with about fifteen pieces (cannon, mortars, and howitzers), earthen works, and two belts of abatis (felled trees with their sharpened branches turned outward, the period\'s barbed wire) belting the slope. A Royal Navy armed sloop, the Vulture, and a gunboat covered the river approaches. The garrison was a real one too: Lieutenant Colonel Henry Johnson (British) of the 17th Regiment of Foot commanded roughly 600 to 700 men, the 17th at the core, with a Highland grenadier company, a company of Loyalists (Americans who stayed loyal to the king), and Royal Artillery. British officers reckoned the place close to impregnable. The nickname that stuck to it in the histories was "little Gibraltar," after the great rock fortress Britain held in the Mediterranean.' },
      { fig: '/war-img/rev-stony-point-fort-view.jpg', cap: 'A view of the British fortress at Stony Point, published in 1780, within a year of the storming: the most period-authentic image of the place. The point rises about 150 feet straight out of the Hudson, water on three sides, a marsh and a causeway nearly cutting it off on the fourth. British engineers thought it could not be taken.', credit: 'engraved view · 1780 · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'Washington studied it carefully, the way he rarely had the patience to. He reconnoitered the point himself. He gathered intelligence all through July from deserters and local informants, and from Captain Allan McLane (American), who got inside the works under a flag of truce while escorting a local woman and counted what he saw. Then he handed the operation to a man with a specific reason to want it: Brigadier General Anthony Wayne (American), a Pennsylvania tanner\'s son turned brigadier, who had taken command of the army\'s new Corps of Light Infantry on the first of July. The plan Washington gave him fixed the essentials, and they were unusual ones: a night assault, on the flanks where the water covered the approaches, in silence, with the bayonet. The attack was never meant to hold the ground, only to take it, haul off the guns, and walk away, leaving Clinton nothing to besiege. And the muskets would go in unloaded.' },
    ],
    meanwhile: { region: 'The Connecticut coast', title: 'The fires that did not work', body: 'While Wayne\'s corps was assembling, Tryon\'s men were still burning their way along the Connecticut shore, New Haven, then Fairfield, then Norwalk, in part to draw Washington east. It was the same trick as the ferry, on a longer leash, and it failed the same way. Washington would not move the army for the burning towns any more than he had for the crossing. He let the raids run and sent his scalpel the other direction, at the rock on the Hudson.' },
  },

  'unloaded-muskets': {
    eyebrow: 'Stony Point · The storming',
    title: 'Unloaded muskets',
    blocks: [
      { p: 'The Corps of Light Infantry was the instrument the plan needed, and it had been built for exactly this. Light infantry were fast, agile soldiers trained to fight in open formation and move at speed, rather than in the tight shoulder-to-shoulder line, and this corps was the pick of them: re-formed for the 1779 campaign from the picked light companies of the Continental line, young, vetted soldiers drilled to the new standard Baron von Steuben had written into the army the winter before at Valley Forge. A silent night bayonet assault is the single hardest thing the eighteenth-century manual asks of infantry, and this was the corps assembled to do it, in four regiments under Brigadier General Anthony Wayne (American). The first job was simply to arrive unseen. On the afternoon of July 15 the corps set out from Sandy Beach, near Fort Montgomery, about 13 miles north of the point, and marched single file by rough inland tracks behind the Dunderberg, a mountain that screened the route. To keep word from running ahead, Wayne had detachments detain the male inhabitants along the road. No soldier was told the objective until the column halted at Springsteel\'s farm, about a mile and a half west of the point, in the evening.' },
      { pill: '/war-revolution/off-the-battlefield/army-from-nothing', plabel: 'How a starving camp at Valley Forge built the army that could do this' },
      { p: 'The order that made the whole thing possible was also the one that put every man on a knife-edge: the two assault columns would go in with their muskets unloaded. Going at a fortified garrison in the dark with an empty weapon is a thing soldiers have to be talked into, because the bayonet is all they have until they are inside the works. But the logic was exact. A single nervous shot in the dark would wake the garrison and throw the surprise away, so the columns carried cold steel and nothing else, and men who fired or even shouted were threatened with death.' },
      { p: 'Around that one constraint the plan was a piece of clockwork. Three pieces of the corps would do three different things. Two columns would make the real attack, both unloaded and with bayonets fixed, one hooking around the southern flank across the flooded sand flats with Wayne himself, one hooking north along the river under Colonel Richard Butler (American). The one exception to the silence was the center. Major Hardy Murfree\'s (American) two North Carolina companies, the only men in the corps with loaded muskets, would open a noisy fire at the causeway in the middle, to make Johnson think the attack was coming there and pull his reserve the wrong way. Ahead of each assault column went a leading party, the van, with Lieutenant Colonel François-Louis de Fleury (American), the French volunteer engineer, at the head of the south column\'s; and ahead of each van went a forlorn hope, the term for a volunteer advance party the army regarded as almost certainly lost, twenty men whose axemen had to hack lanes through the two belts of abatis under fire before the column could follow. For recognition in the dark, each soldier wore a scrap of white paper in his hat, and the watchword, the prearranged shout that would tell every man in the dark that the fort was taken and the killing should stop, was "The fort\'s our own!"' },
      { p: 'The columns moved out from the farm around half past eleven, into a dark, windy night. The weather did them an unplanned favor: it had pushed the Vulture and the gunboat off their close stations, so the river approaches were clear. Then the plan met the ground. The south column hit water deeper than anyone had expected, two to four feet over the flooded flats, and lost time wading it. British pickets fired the alarm, the works opened up with cannon and musketry on both flanks, and Murfree\'s companies began blazing away at the center exactly as ordered. It worked: Johnson took several companies of the 17th Foot, a large part of his infantry, down toward the noise at the causeway, and the diversion swallowed his reserve at the moment the flanks were coming in.' },
      { p: 'The forlorn hopes went into the abatis with their axes. The work was murderous; one of the twenty-man parties lost most of its men cutting the lanes. But the columns never stopped, because they could not stop to fire, and they went over the works with the bayonet. Fleury was first into the fort and struck the British colors with his own hand; the order of the men behind him was settled afterward, because Wayne had posted cash rewards for the first five inside. Near the inner abatis a musket ball grazed Anthony Wayne across the head and knocked him down, stunned and bloodied. Tradition has him gasping to be carried into the fort to die at the head of his column; what the record shows is that minutes later he was inside it. This was the man who had been bayoneted in the dark at Paoli two years before, his old enemies in front of him now, and he came up the rock with a bandaged head. The two columns met at the summit, the watchword went up, and the resistance came apart. From the first contact to the works being taken was about twenty-five minutes.' },
      { fig: '/war-img/rev-stony-point-assault.jpg', cap: 'The storming of Stony Point in an engraving after Alonzo Chappel, made in 1857, eighty years after the fight: the classic image of Wayne wounded as the column goes over the works. A history print imagined long after the fact, but the scene it stages, the night assault and Wayne\'s grazing head wound, is real.', credit: 'after Alonzo Chappel · engraving · 1857 · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'What happened in those last minutes is the part worth slowing down for. The garrison asked quarter, and got it. These were men who had it in their power, and arguably by the brutal customs of storming a defended work at night the license, to give none. Two years before, Wayne\'s own division had been surprised in the dark and bayoneted at Paoli, in Pennsylvania, an attack Americans called a massacre, and there had been a second such affair at Old Tappan since. The men with the bayonets in their hands had Paoli in their memory. They used the bayonet, because that was the order and the only way in; and when the garrison cried for mercy, they stopped. They killed about twenty of the garrison and took something like five hundred prisoners, the wounded among them, collected and treated.' },
      { p: 'The fort & Garrison with Colo. Johnston are ours—Our Officers & men behaved like men who are determined to be free.', q: true },
      { p: 'That was Wayne\'s whole dispatch to Washington, written from inside the captured works at two o\'clock in the morning. He dated it "Stoney Point, 16th July 1779, 2 OClock A.M." in his own hand, and spelled both the place and his prisoner the way they sounded to him: "Stoney" for Stony, "Johnston" for Johnson. Across the river the other half of the night failed: General Robert Howe (American) was supposed to move on Verplanck\'s Point at the same time, but his orders and his siege guns went astray, the British garrison there held, reinforcements came up from New York, and Howe withdrew. King\'s Ferry\'s east bank stayed British. But the rock the British had called impregnable was taken, in the dark, in under half an hour, with unloaded muskets.' },
    ],
    meanwhile: { region: 'Verplanck\'s Point', title: 'The half that failed', body: 'The plan had two prongs, and only one went home. While Wayne\'s corps was going over the works on the west bank, General Robert Howe\'s column on the east bank, ordered against Verplanck\'s Point, never got its act together: the orders and the heavy guns it needed arrived late or not at all, the garrison held, the British fed in reinforcements, and Howe pulled back. The captured guns on Stony Point were turned on Verplanck\'s and on the Vulture that day, but the east end of the ferry stayed in British hands. The night\'s trophy was the west bank, and only the west bank.' },
  },

  'the-quarter': {
    eyebrow: 'Stony Point · What it meant',
    title: 'The quarter they gave',
    blocks: [
      { fig: '/war-img/rev-stonypoint-tac2.jpg', cap: 'The summer\'s whole maneuver in one frame. Clinton pushed up the Hudson from New York and grabbed both ends of King\'s Ferry, twelve miles below the fortress at West Point, then burned the Connecticut coast, all of it bait to pull Washington down out of the Highlands. Washington never moved the army. He sent his light corps the other way, thirteen miles down the west bank, to take the point back in the dark. A month later Henry Lee copied the raid at Paulus Hook in New Jersey.', credit: 'Stuff Happened map' },
      { p: 'The humanity of our brave Soldiery who scorned to take the lives of a vanquished foe, calling for mercy reflects the highest honor on them and accounts for the few of the enemy Killed on the occasion.', q: true },
      { p: 'That was Anthony Wayne (American), making the restraint the headline of his own report to Washington the day after Stony Point fell. The men of the Corps of Light Infantry had stormed a defended work in the dark, with Paoli and Old Tappan to avenge, and had given the surrendering garrison quarter, and both sides remarked on it and said so in writing.' },
      { p: 'One British voice said the same, from the other side of it. Commodore Sir George Collier (British), who had commanded the naval side of Clinton\'s operation that spring, wrote in his private journal that the rebels "had made the attack with a bravery they never before exhibited, and they showed at this moment a generosity and clemency which during the course of the Rebellion had no parallel." That is the meaning of the night, and it is worth being precise about. There was no massacre; the garrison asked for mercy and received it; the official British dead came to about twenty, not the heaps a storming was expected to leave, even though American accounts at the time claimed three times that number. The low number is the one the record supports, and the low number is exactly what makes the story true. An army that had been bayoneted in the dark, handed the chance to do the bayoneting, chose discipline.' },
      { p: 'The credit fell hardest on a Frenchman. Lieutenant Colonel François-Louis de Fleury (American), the volunteer engineer who had led the south column\'s van and been judged first into the works, was voted a silver medal by Congress. It was the first of the war\'s medals actually struck, made in Paris, and the only one given to a foreign junior officer. Major John Stewart of Maryland (American), who had led the north column\'s van, got the war\'s other silver medal for Stony Point. And Wayne got a gold one. In all, Congress voted thanks to Wayne and the corps and three medals out of only about a dozen it awarded in the entire war, the only single battle that produced three. It ordered the captured stores and ordnance, appraised at more than $150,000 in the inflated paper money of the day, divided among the troops as prize money. Across the states the storming was celebrated as proof of something the army had needed to prove: that the Continental line drilled to Steuben\'s standard could carry out the hardest mission in the manual, a silent night escalade (an assault that goes over a fortification\'s walls instead of through them), and carry it out better, and more humanely, than the British had managed at Paoli.' },
      { pill: '/war-revolution/off-the-battlefield/army-from-nothing', plabel: 'The army that learned to do this, told whole' },
      { p: 'Then Washington gave the place away. He rode down to look at the captured works on July 17 and decided what he had suspected before he ever ordered the attack: that holding Stony Point would tie down more than fifteen hundred men under the guns of the Royal Navy, sitting exposed on the same rock where Johnson had just been taken. It was not worth a garrison. So the army hauled off the captured artillery and stores, razed the works, and withdrew on July 18. The British, under Brigadier General Thomas Stirling (British), walked back in and reoccupied the point on the 19th, three days after losing it. The raid\'s logic held all the same: take the trophy, keep nothing the enemy could besiege. And the rest of it unwound the way Washington had bet. Clinton\'s whole Hudson thrust had bought him nothing. Washington never offered the open battle Clinton had hoped to bait, West Point was untouched and stronger every month, the Connecticut raids were broken off, and in October Clinton pulled his men out of both Stony Point and Verplanck\'s Point and gave up King\'s Ferry for good. The year in the north closed as it had opened: stalemate, with the war\'s momentum draining away to the south.' },
      { p: 'The clearest measure of what the night meant was that other officers copied it. One month later, on August 19, 1779, Major Henry Lee (American) ran a similar midnight bayonet raid against the British post at Paulus Hook, in New Jersey, in the open pattern Stony Point had set: pick your men, go in silent, take the works with the bayonet. Stony Point had become a model. And the place itself is still there. The point that the light corps stormed in the dark is a state historic site now, with the Stony Point Lighthouse standing on it, built in 1826 and the oldest lighthouse on the Hudson, looking down from the rock that the British once called impregnable and held for three days.' },
      { fig: '/war-img/rev-stony-point-lighthouse.jpg', cap: 'Stony Point today, photographed from the site of the British fort. The tower is the Stony Point Lighthouse, built in 1826 and the oldest lighthouse on the Hudson, standing now on the battlefield the light corps stormed in the dark.', credit: 'Ser Amantio di Nicolao · 2014 · Wikimedia Commons · CC BY-SA 3.0' },
    ],
    meanwhile: { region: 'Paulus Hook', title: 'The raid, run again', body: 'A month after Stony Point, Major Henry Lee took a column down to the British outpost at Paulus Hook, on the New Jersey shore opposite New York, and did the same thing Wayne had done: a night march, a silent rush, the works carried by the bayonet, and prisoners hauled away. It was a smaller prize and an even shorter hold, but it made the point twice over. The midnight bayonet raid had become a thing the Continental Army knew how to do, and an idea other commanders now reached for.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={STONY_POINT_NARR}
    id={id}
    slug="stony-point"
    battleName="Stony Point"
    date="July 15–16, 1779"
    theatreId="rev-battles"
    battleId="rev-stony-point"
    theatreHref="/war-revolution/battles"
    accent="var(--rev-battles)"
    endHref="/war-revolution?theatre=rev-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
