// House-voice civ descriptions for the home cards — the dry, declarative,
// turn-at-the-end voice the Art section uses (see lib/art-content.ts `blurb`).
// A civ listed here overrides its navigator subtitle on the home card only;
// civs not listed fall back to `civ.subtitle`.
export const CIV_BLURBS: Record<string, string> = {
  'medieval-japan': "Four centuries when the emperor reigned and the sword ruled: shogun, samurai, and warlord, from Kamakura to the eve of the Tokugawa peace.",
  'islamic-persia': "Conquered by the Arabs, then quietly conquered them back with its own language and learning, and outlasted even the Mongols.",
  'muscovite-russia': "How a tribute-paying town under the Mongol yoke turned itself into the tsardom that would swallow a continent.",
  'age-of-exploration': "Wooden ships crawl down Africa, blunder into the Americas, and force open the Indian Ocean — knitting one connected world, and loosing conquest, silver, and the slave trade upon it.",
  'atlantic-slave-trade': "The largest forced migration in history — twelve and a half million people — and the resistance, revolt, and survival the traffickers never counted on.",
  'latin-american-independence': "Napoleon topples the Spanish crown and a hemisphere fights its way free behind Bolívar and San Martín — then learns that winning the war was the easy part.",
  'prehistoric-japan': "Made some of the world's first pottery, then spent ten thousand happy years as foragers in no rush to invent farming.",
  'ancient-china': "Two rivers, a great deal of millet, and the slow invention of the idea that one family ought to run everything.",
  'minoan-civilization': "Crete's palace people: indoor plumbing, bull-leaping, and a script nobody can read. Then the volcano next door went off.",
  'mesopotamia': "Invented the city, writing, the wheel, and the world's first complaint letter. Between the rivers, naturally.",
  'early-dynastic-egypt': "Two kingdoms become one, the pharaoh is invented, and someone decides to stack stone into a staircase for the dead.",
  'ancient-nubia': "Egypt's neighbour to the south — gold, feared archers, and the kingdom Egypt kept insisting it had already conquered.",
  'early-andean-civilizations': "Raised monumental pyramids in the desert before getting around to pottery. Priorities.",
  'indus-valley': "Grid-planned brick cities with drains and no obvious kings, a script no one can read, and no agreed reason it ended.",
  'elamite-civilization': "Southwest Iran's stubborn rival to Mesopotamia — sacked Ur, got sacked back, and quietly outlasted nearly everyone.",
  'old-kingdom-egypt': "The pyramid age, when the entire state existed largely to bury one man under the biggest pile of stone on Earth.",
  'assyrian-empire': "Ran the ancient Near East on cavalry and siege engines, and advertised the fact by carving their cruelty across the palace walls.",
  'hittite-empire': "A bronze-age superpower that fought Egypt to a draw, signed history's first surviving peace treaty, then vanished so completely that for ages only the Bible remembered them.",
  'ancient-korea': "From a bear who became a woman to the kingdom that finally united the peninsula — Korea's long opening act, half myth and half hard fighting.",
  'new-kingdom-egypt': "Egypt at its imperial peak — warrior pharaohs, a boy king who matters only because his tomb went unrobbed, and the heretic who tried to delete the gods.",
  'shang-dynasty': "China's first dynasty we can actually read about, because they wrote their questions to the gods on bones and cracked them in the fire for answers.",
  'mycenaean-civilization': "The warlords behind the Trojan War legend — gold masks, fortress halls, and a bookkeeping script. Then the whole bronze-age world fell apart at once.",
  'phoenicia': "Sold purple dye and cedar across the Mediterranean and handed everyone the alphabet you're reading this in. Wrote almost nothing down themselves.",
  'vedic-period': "Cattle-herding newcomers whose hymns, memorized word-perfect for a thousand years before anyone wrote them down, became the foundation of Hinduism.",
  'polynesian-voyagers': "Found and settled every habitable speck in the world's largest ocean using stars, swells, and birds — centuries before Europe dared sail out of sight of land.",
  'olmec-civilization': "Mesoamerica's mother culture — carved colossal basalt heads, invented much of what later peoples would copy, and left no clue what they called themselves.",
  'zapotec-civilization': "Flattened a mountaintop to build Monte Albán and wrote one of the Americas' earliest scripts — still mostly unread.",
  'kingdom-of-kush': "The Nubian kingdom that turned the tables and conquered Egypt, ruling as pharaohs for a century before retreating south to build more pyramids than Egypt ever did.",
  'zhou-dynasty': "China's longest dynasty slowly lost its grip, and in the chaos its thinkers — Confucius, Laozi, and rivals — argued out the ideas China would live by for the next two thousand years.",
  'ancient-israel': "Two small hill kingdoms whose temple, kings, and scriptures would outlast every empire that conquered them — which was all of them.",
  'maya-civilization': "Jungle city-states that tracked the planets and wrote real history in glyphs, then mostly walked away from their greatest cities centuries before the Spanish arrived to wonder why.",
  'carthage': "A trading superpower that marched elephants over the Alps to humiliate Rome — and got so thoroughly erased for it that salting the earth became the metaphor.",
  'scythians': "Horse nomads who buried their chiefs in gold and, if the Greeks are to be believed, drank from their enemies' skulls. They left no cities to dig up, only spectacular graves.",
  'ancient-greece': "A few hundred quarrelsome city-states that invented democracy, philosophy, theatre, and the Olympics — and couldn't go a generation without going to war with each other.",
  'celtic-cultures': "Iron-age Europe's dominant culture — fierce, artful, and so allergic to writing that almost everything we know about them was written by the Romans busy conquering them.",
  'ancient-rome': "Started as a village of cattle-thieves, ended ruling the Mediterranean, and spent the whole time insisting it was still a republic long after it obviously wasn't.",
  'late-egypt': "Egypt's long twilight, ruled in turn by Nubians, Assyrians, Persians, and finally Greeks — still building temples to the old gods while the throne kept changing hands.",
  'persian-empire': "The first empire to span three continents, run not on terror but on tolerance and good roads — until a Macedonian kid with a grudge burned the capital down.",
  'qin-dynasty': "Unified China in a decade, standardized everything from the script to the axle-width, buried an army of terracotta soldiers — and collapsed within four years of its first emperor's death.",
  'maurya-empire': "India's first great empire, whose mightiest king won a war so bloody he renounced violence, converted to Buddhism, and carved his regrets onto rocks across the subcontinent.",
  'xiongnu-huns': "The steppe confederation that scared China into building the Wall — and, quite possibly, the same people who turned up centuries later to terrify Rome.",
  'han-dynasty': "Four centuries so defining that most Chinese still call themselves the Han — paper, the Silk Road, and a civil-service exam that outlasted the dynasty by two thousand years.",
  'andean-kingdoms': "Peru's regional cultures — the Moche modeling startlingly lifelike (and frankly explicit) pottery, the Nazca scratching giant figures into the desert only legible from the sky.",
  'post-maurya-kingdoms': "India between empires — a busy stretch of trade, Greek-Indian kingdoms, and the first statues of the Buddha, usually dismissed as a gap between the famous bits.",
  'germanic-tribes': "The tribes across the Rhine that Rome could never quite conquer or ignore — trading partners, hired soldiers, and eventually the heirs who'd inherit the western empire.",
  'ancestral-puebloans': "Built apartment blocks into desert cliffs and roads to nowhere across the Southwest, then left it all — a departure their descendants remember and archaeologists still argue about.",
  'teotihuacan': "The Americas' first true metropolis — a planned city of a hundred thousand whose pyramids awed even the Aztecs, who arrived centuries later and named it without knowing who built it.",
  'kingdom-of-aksum': "An African empire that minted its own coins, raised giant stone obelisks, and converted to Christianity early enough to still be practicing it, unbroken, today.",
  'the-goths': "Migrated from the Baltic to the Black Sea, sacked Rome, founded kingdoms in Italy and Spain — and gave their name to a cathedral style they had nothing to do with.",
  'six-dynasties': "Three and a half centuries of division, when China split north from south, Buddhism sank deep roots, and the poets got very good at writing about decline.",
  'gupta-empire': "India's classical golden age, when mathematicians wrote down zero, astronomers worked out that the Earth spins, and the poetry and temples set a bar nobody since has quite cleared.",
  'byzantine-empire': "The Roman Empire that refused to fall for another thousand years after the western half did — speaking Greek, calling itself Roman, and arguing theology to the very end.",
  'migration-period': "The great reshuffle, when whole peoples picked up and moved across a crumbling Rome, and the map of Europe was redrawn by the refugees and the newcomers.",
  'anglo-saxon-england': "Germanic settlers who turned post-Roman Britain into England — pagan war-bands that became Christian kingdoms, with gorgeous treasure and gloomy poetry to show for it.",
  'early-medieval-europe': "The so-called Dark Ages, neither as dark nor as quiet as advertised — Rome's wreckage, Charlemagne's revival, and then Vikings, Magyars, and Saracens all turning up at once.",
  'middle-horizon-empires': "The Andes' first true empires, Tiwanaku and Wari, who built cities at brutal altitude and a road network the Inca would later get all the credit for.",
  'asuka-nara-japan': "Japan imports Buddhism, Chinese writing, and the very idea of a state from the mainland — then builds a giant bronze Buddha that nearly bankrupts the country.",
  'medieval-india': "Centuries of rival temple kingdoms that out-built one another in soaring stone and traded across the Indian Ocean, while largely missing the storm gathering on the northwest frontier.",
  'vendel-scandinavia': "Scandinavia's quiet centuries before the raids — when the helmets got fancier, the ships got better, and the Vikings were, essentially, getting ready.",
  'gokturk-khaganate': "The first people on record to call themselves Turks — a steppe empire that ran the Silk Road, left the oldest Turkic writing, and split itself in two out of sheer size.",
  'tang-song-china': "China's most cosmopolitan stretch — poetry, gunpowder, paper money, the compass, and the world's largest cities, all while the dynasty kept losing the north to nomads.",
  'swahili-coast': "Coral-stone city-states that grew rich facing the sea, trading African gold and ivory for Chinese porcelain, and speaking a language built for the monsoon trade.",
  'umayyad-caliphate': "In a single century Islam went from one city to an empire stretching from Spain to India — then the family that built it was overthrown by the cousins they'd sidelined.",
  'srivijaya': "A maritime empire that controlled the straits every ship between China and India had to pass through, grew rich on tolls, and left so few ruins we only rediscovered it last century.",
  'al-andalus': "Seven centuries of Muslim Spain, where Arabic poetry, philosophy, and plumbing flourished, and Muslims, Christians, and Jews coexisted about as well as anyone managed in the Middle Ages.",
  'uyghur-steppe': "The steppe's forgotten centuries between the Turks and the Mongols — the Uyghurs who rescued a Chinese dynasty, then got run off and reinvented themselves as oasis traders.",
  'islamic-golden-age': "When Baghdad's scholars translated the entire ancient world, invented algebra, and advanced medicine — until the Mongols arrived and, the story goes, the river ran black with ink.",
  'viking-age': "Scandinavians who raided monasteries, founded cities, reached America five centuries before Columbus, and then largely settled down and got baptized.",
  'heian-japan': "Four centuries when the court perfected poetry, calligraphy, and elaborate seduction, wrote the world's first novel, and quietly let the provinces fall to the warriors who'd soon take over.",
  'mississippian-culture': "North America's mound builders, whose city of Cahokia was bigger than London at the time — and was a grassy ruin, its people gone, long before any European saw it.",
  'khmer-empire': "The empire that built Angkor, the largest religious monument on Earth, and a hydraulic city of a million people — then let the jungle take most of it back.",
  'goryeo-korea': "The dynasty that gave Korea its name, printed books with movable metal type before Gutenberg was born, and bought off the Mongols rather than be destroyed by them.",
  'dai-viet': "Vietnam after a thousand years under China — which it then spent the next thousand defending its independence by beating back the Chinese, the Mongols, and the Mongols again.",
  'high-medieval-europe': "Europe's growth spurt — towns, cathedrals, universities, and the Crusades, all funded by a warming climate and a lot more people than the previous centuries had managed.",
  'delhi-sultanate': "Five Muslim dynasties ruling northern India in turn, fending off the Mongols and raising the Qutb Minar — one sultan even moved the whole capital, then moved it right back.",
  'mongol-empire': "The largest contiguous land empire in history, assembled in a single lifetime by a man who started with nothing — and run, surprisingly, on free trade and a working postal service.",
  'mali-empire': "West Africa's gold empire, whose king Mansa Musa made a pilgrimage to Mecca so lavishly generous it wrecked the price of gold in Egypt for a decade.",
  'yuan-dynasty': "China under Mongol management — Kublai Khan in a Chinese palace, Marco Polo (allegedly) at the door, and a ruling class that never quite learned to govern the place it had conquered.",
  'majapahit': "Java's great empire, founded by a prince who tricked an invading Mongol fleet into doing his dirty work and then turned on them — and went on to claim most of the archipelago.",
  'ottoman-empire': "Six centuries from a frontier warband to three continents — took Constantinople, besieged Vienna twice, and declined so slowly that Europe called it the sick man for a hundred years before it died.",
  'late-medieval-europe': "The bad century — famine, a plague that killed a third of everyone, and a war that ran long enough to need the word Hundred. Out of which, somehow, came the Renaissance.",
  'renaissance-italy': "A handful of feuding Italian city-states, awash in banking money, that set out to remake art and rediscover antiquity — and produced more genius per square mile than seems entirely fair.",
  'aztec-empire': "Built a glittering capital on an island in a lake, ran an empire on tribute and human sacrifice, and fell in two years to a few hundred Spaniards and the enemies it had made.",
  'ming-dynasty': "Threw out the Mongols, built the Forbidden City and most of the Great Wall you see today, sent treasure fleets across the Indian Ocean — then called them home and shut the door.",
  'timurid-empire': "Tamerlane conquered from Delhi to Damascus leaving pyramids of skulls; his grandson Ulugh Beg built an observatory and mapped a thousand stars. Same family.",
  'joseon-korea': "Five centuries of Confucian order under one dynasty, which invented an alphabet so logical a king designed it himself so that commoners could finally read.",
  'inca-empire': "Ran an empire of millions with no money, markets, or writing — just knotted strings, terraced mountains, and twenty thousand miles of road. Built it in a century; lost it in a year.",
  'songhai-empire': "West Africa's largest empire, with Timbuktu as a university town full of books — until a Moroccan army with guns crossed the Sahara and ended it in a single battle.",
  'safavid-persia': "Made Iran Shia more or less at sword-point, turned Isfahan into one of the most beautiful cities on Earth, and gave Persia the religious identity it still carries.",
  'mughal-empire': "Descendants of both Genghis Khan and Tamerlane who ruled most of India in extraordinary splendor, built the Taj Mahal as a tomb, and slowly spent it all.",
  'scientific-revolution': "A century and a half in which Europe stopped asking what Aristotle thought and started measuring — and discovered the universe ran on math, whether the Church liked it or not.",
  'edo-japan': "Two and a half centuries of near-total isolation and total peace under the shoguns — no wars, almost no foreigners, and a culture of woodblock prints, kabuki, and very strict rules.",
  'qing-dynasty': "China's last dynasty, run by Manchu outsiders who doubled its size and ruled a third of humanity — then spent its final century being carved up by everyone with a navy.",
  'enlightenment': "When Europe's thinkers decided reason could fix everything — government, religion, society — and inspired a couple of revolutions to prove it, with mixed results.",
  'russian-empire': "The Romanovs' sprawling colossus — a westernizing tsar, a French-speaking aristocracy, and millions of serfs, expanding across a continent right up until the whole thing came down in a fortnight.",
  'industrial-revolution': "Steam, coal, and factories remade how everything was made — multiplying wealth, soot, and working hours, and turning villages into cities almost overnight.",
  'early-american-republic': "A brand-new republic improvising as it went, working out whether the experiment would hold together, double in size, or come apart at the first serious argument.",
  'antebellum-america': "A booming, expanding nation that could not stop arguing about the one thing it refused to fix — until the argument became the bloodiest war in its history.",
  'modern-india': "From the Crown's most prized colony to the world's largest democracy — which it won, improbably, mostly by refusing to fight for it.",
  'reconstruction': "The decade America tried to rebuild the South and make four million freed people into citizens — a genuine revolution that was abandoned, deliberately, within twelve years.",
  'meiji-japan': "Japan looked at the Western powers, decided to become one rather than be colonized by them, rebuilt itself top to bottom in a generation — then beat Russia to prove it had worked.",
  'korean-modern': "Colonized by Japan, liberated, then split in two by its liberators — one half becoming a global pop-culture powerhouse, the other the most closed country on Earth.",
  'chinese-revolution': "From the last emperor to Mao — civil war, invasion, and revolution, followed by campaigns to remake the country that cost tens of millions of lives.",
  'roaring-twenties': "A decade-long party of jazz, cars, stock tips, and illegal liquor, which ended precisely on schedule with the largest market crash in history.",
  'soviet-union': "The world's first communist state — it industrialized at brutal speed, beat Hitler, put the first human in space, and then, after seventy years, simply voted itself out of existence.",
  'japanese-economic-miracle': "A country bombed into rubble that within thirty years was building the world's cars and electronics and buying up Manhattan — until the bubble it floated on burst.",
  'civil-rights-era': "The Black freedom struggle that, through boycotts, marches, and sheer nerve in the face of fire hoses, forced America to finally start honoring the rights it had promised a century before.",
  'rise-of-china': "How a nation Mao left dirt-poor became the world's factory and second superpower in forty years — by quietly deciding, as Deng put it, that to get rich is glorious.",
  'kievan-rus': "The east Slavic river-trade federation that chose Orthodox Christianity off a sales pitch, became the ancestor Russia, Ukraine, and Belarus all claim — and was erased by the Mongols.",
}
