// GENERATED by scripts/_build-rev-themes.mjs from audits/war-pipeline/rev-<slug>-final.md.
// Do NOT hand-edit — edit the gated -final.md and re-run the build script.
// The American Revolution off-the-battlefield theme narratives, consumed by the dynamic
// off-the-battlefield/[theme] route through the shared <BattleSectionReader>.

import type { Narr } from '@/components/mode/battle-reader'

export const THEME_NARR: Record<string, Narr> = {
  "bill-comes-due": {
    "eyebrow": "A victorious Britain, broke, decides the colonies must pay",
    "title": "The Bill Comes Due",
    "blocks": [
      {
        "p": "Britain had just won the greatest war it had ever fought, and it was nearly broke from winning. On 10 February 1763 the diplomats signed the Treaty of Paris, the agreement that ended the Seven Years' War (known in America as the French and Indian War). On paper the prize was staggering. France was swept off the North American mainland. Britain took all of Canada and every French claim east of the Mississippi River, and pried Florida loose from Spain. From the Atlantic to the great river, the map was suddenly red."
      },
      {
        "p": "Then the accounting started, and the victory began to look like a problem."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/treaty-of-paris",
        "plabel": "The Treaty of Paris & the Proclamation Line"
      },
      {
        "h": "The cost of winning",
        "eyebrow": "A debt that roughly doubled"
      },
      {
        "p": "Wars are paid for on borrowed money. A government at war sells bonds, promises to repay lenders later with interest, and the interest becomes a fixed yearly bill that keeps coming due long after the fighting stops. That running total is the national debt, and the war had roughly doubled Britain's. It climbed from roughly £75 million before the fighting to roughly £130 million by 1763 and 1764."
      },
      {
        "p": "The raw number is hard to feel. What made it bite was the interest. Servicing the debt, just paying the yearly fee on all that borrowing, swallowed more than half the entire national budget. And the people who would normally be asked to cover it were tapped out. British taxpayers at home were already among the most heavily taxed in Europe, between the land tax and a hugely unpopular new tax on cider that had badly damaged the standing of the previous ministry (the team of ministers who run the government). A government could win a war and still spend the peace cornered by its own creditors, and that is roughly where Britain stood."
      },
      {
        "fig": "/war-img/rev-george-iii.jpg",
        "cap": "George III, who came to the throne in 1760 and on whose watch the bill for the war finally came due.",
        "credit": "George III in his coronation robes · Allan Ramsay · public domain"
      },
      {
        "p": "Worse, the spending did not stop when the shooting did. There was now an empire to hold. Britain decided to keep a standing army in North America after the war, a peacetime force of full-time professional soldiers on the order of 10,000 regulars, to garrison the new conquests, watch the frontier, and manage relations with the Native nations of the interior. That army cost something in the range of a few hundred thousand pounds a year. London's reasoning was straightforward: the colonies were the war's chief beneficiaries, France had been driven off their continent, and the army was there for their protection, so they should help pay for it."
      },
      {
        "p": "The colonists would come to see the same army very differently. A standing army kept up in peacetime, quartered among them, looked less like protection than like control. They had not asked for it, and soon enough they would be asked to fund it."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/war-finance",
        "plabel": "The War Debt & the Road to Taxation"
      },
      {
        "h": "The end of the long leash",
        "eyebrow": "Salutary neglect, and the man who ended it"
      },
      {
        "p": "For most of the century before 1763, Britain had governed its American colonies with a remarkably light hand, an approach later given the name \"salutary neglect\" (beneficial inattention, the idea that the colonies prospered, and so did Britain, precisely because London mostly left them alone). The trade laws were on the books. The Navigation Acts (a body of law requiring colonial trade to move on British ships and pass through British ports) had stood for generations. But they were loosely enforced, and the colonies ran their own internal affairs through elected assemblies, one per colony, like a local parliament, that controlled local taxes and even paid the royal governors' salaries. Smuggling, especially of molasses, was so routine it was barely thought of as a crime."
      },
      {
        "p": "After 1763 a new ministry set out to reverse all of it: enforce the trade laws in earnest, raise money directly from the colonies, and pull them under tighter control from London. The man who drove that reversal was George Grenville, and he was, by temperament, exactly the man to do it. He was a trained lawyer and a specialist in money, twice Treasurer of the Navy, the kind of minister who mastered every line of an account and bored the House of Commons half to death reciting them. He came to power in April 1763 with the war debt as the defining problem on his desk, took over the Treasury (the department in charge of the nation's money), and became, in effect, prime minister from 1763 to 1765. He approached the colonies the way he approached everything, as a set of figures that did not yet add up. Before he asked them for a penny he studied the colonial customs system in detail and consulted the colonies' agents in London, and he came away convinced he was being entirely reasonable."
      },
      {
        "fig": "/war-img/rev-george-grenville.jpg",
        "cap": "George Grenville, a meticulous lawyer and finance man who inherited the war debt and concluded the colonies should help pay it down. The print names him Treasurer of the Navy, the post he held twice.",
        "credit": "18th-century mezzotint · public domain"
      },
      {
        "p": "On its own terms, his logic was hard to fault. He was not asking the colonies to retire the debt or even to cover its interest. He wanted a partial contribution toward the cost of the army standing guard on their own frontier. The trouble was not the arithmetic. It was that the colonies elected no members to Parliament (Britain's legislature, the body that wrote the laws and levied the taxes), not one, and Grenville was preparing to tax people who had no vote in the room."
      },
      {
        "h": "A line drawn on the mountains",
        "eyebrow": "The Proclamation of 1763"
      },
      {
        "p": "The first shock did not look like a tax at all. On 7 October 1763, King George III issued the Royal Proclamation of 1763, which drew a line down the crest of the Appalachian Mountains and forbade, at least for the moment, any new colonial settlement to the west of it. The land beyond was reserved as Indian territory, closed to colonial purchase and settlement."
      },
      {
        "p": "The Proclamation had been in the works before the frontier caught fire. What forced it into law was a war already burning in the interior. With the French gone, the Native nations of the Great Lakes and the Ohio Country had risen against the new British presence in a broad, coordinated resistance the British called Pontiac's War, after Pontiac, the Odawa war leader who organized and led the uprising. They fought to halt the settlers pushing onto their land and to force the British into honest terms of trade. London, looking at the cost of fighting them and the cost of the army it had just decided to keep, concluded that the cheapest way to keep the peace was to stop the land grab that kept provoking it. The line was, in part, an attempt to keep faith with Native nations who had just made the price of bad faith very clear."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/pontiacs-war",
        "plabel": "Pontiac's War & the Aftermath for Native Nations"
      },
      {
        "p": "To the colonists, the line was an outrage. Their charters, the founding documents that had created the colonies, claimed land running clear to the Pacific. Veterans had been promised western land for their service. Speculators had fortunes staked on the Ohio Country, among them a young Virginian named George Washington, who privately dismissed the Proclamation as a temporary measure to quiet the Native nations and went on quietly acquiring western claims anyway. For the first time, London was telling colonists where they could and could not go on what they thought of as their own continent."
      },
      {
        "p": "In practice the line barely held. It was poorly enforced, settlers crossed it almost at once, and over the following years it was steadily pushed west. But the principle stung even where the fence leaked. At bottom, the colonists' fury was fury at being told they could not take Native land, and that telling came from a Parliament across an ocean."
      },
      {
        "h": "The first reach into colonial pockets",
        "eyebrow": "The Sugar Act, 1764"
      },
      {
        "p": "In the spring the grievance turned from land to money. On 5 April 1764, Parliament passed the American Revenue Act, known almost universally as the Sugar Act, and at first glance it looked like a gift. It rewrote an old law, the Molasses Act of 1733, which had taxed foreign molasses (the thick dark syrup left from refining sugar, and the raw material of New England's rum trade) at six pence a gallon. That old duty had been so steep that colonial merchants simply smuggled around it, and almost nobody ever collected it. The Sugar Act cut the rate in half, down to three pence a gallon."
      },
      {
        "p": "But the cut was the trick. The lower rate was paired with strict, genuine enforcement. The idea was to set the duty low enough that paying it actually beat the cost and risk of smuggling, so that for the first time the tax would really be collected. A duty colonists had laughed off became, at half the rate, a real bill that came due."
      },
      {
        "p": "And it was a bill for revenue, not for trade. Earlier duties had existed to steer commerce, to nudge merchants toward buying British. The Sugar Act said the quiet part out loud in its own preamble (the opening statement of a law's purpose)."
      },
      {
        "p": "it is just and necessary that a revenue should be raised … for defraying the expenses of defending, protecting, and securing the colonies. — preamble to the Sugar Act, 1764",
        "q": true
      },
      {
        "p": "That was new. It made the Sugar Act, in effect, the first act of Parliament expressly designed to raise money from the colonies rather than merely to regulate their trade."
      },
      {
        "p": "To make the collection stick, the act came with teeth. Colonists had grown up on the common-law right to a jury of their peers, neighbors who heard your case and decided your fate. Under the Sugar Act, merchants accused of smuggling would no longer get one. Their cases were sent instead to vice-admiralty courts (special maritime courts run by a single Crown-appointed judge, with no jury at all), most notoriously the one at Halifax, in Nova Scotia, hundreds of miles from home. The rules there were rigged from the start. The burden of proof was reversed: the accused had to prove the seized goods had been imported legally, rather than the Crown having to prove they had not. And the customs officers and informers who brought the charges took a share of any cargo that was forfeited, a built-in reward for seizing it. To colonists raised on a jury trial and the presumption of innocence, this was less a court than a collection machine, a second alarm sounding underneath the first. And it all landed in the middle of a postwar economic slump, hardest of all on New England, where the rum trade was the spine of the economy."
      },
      {
        "p": "The colonies did not just grumble in private. In 1764 Massachusetts and other assemblies passed formal resolutions and petitioned Parliament directly against the Sugar Act, the first organized institutional protests, an early rehearsal for the united stand to come."
      },
      {
        "h": "The squeeze from the other side",
        "eyebrow": "The Currency Act, 1764"
      },
      {
        "p": "The same year brought a second pinch, this one on the money supply itself. Parliament passed the Currency Act of 1764, which restricted the colonies' power to issue paper money as legal tender (currency a creditor is legally required to accept in payment of a debt). British merchants and creditors had grown tired of being repaid in colonial paper that had lost value since they were owed the money, and the act was meant to protect them. On its face it was a fair enough request, and historians today do not rank colonial debts to British merchants among the leading causes of the Revolution."
      },
      {
        "p": "What made it bite was where it fell, and when. Gold and silver coin was chronically scarce in the colonies, and paper money was how a coin-starved economy did its everyday business. Now the two acts of 1764 worked as a single vise. The Sugar Act demanded its duties be paid in hard coin the colonies barely had, while the Currency Act strangled the paper money they actually used. Squeezed for scarce coin on one side and stripped of usable paper on the other, colonists felt London tightening both jaws at once, in the middle of a postwar slump."
      },
      {
        "h": "The argument begins",
        "eyebrow": "No taxation without representation"
      },
      {
        "p": "Taken one at a time, none of the 1764 measures was ruinous. Taken together, and arriving all at once, they pushed colonists past complaining about the money and into a deeper question about the principle. Did Parliament, a body in which the colonies had no elected voice, have the right to tax them for revenue at all?"
      },
      {
        "p": "The colonists answered with a distinction they would lean on for years. There were, they argued, two kinds of taxes. External taxes were duties on trade, collected at the ports, which they had long accepted as a fair tool for regulating commerce within the empire. Internal taxes were a different animal, a charge laid simply to raise money, and those, they held, only their own elected assemblies could impose on them. The Sugar Act sat uneasily on that line. It was external in form, a duty collected at the port, but internal in purpose, since its declared aim was pure revenue, which made it feel like an internal tax wearing the costume of an external one."
      },
      {
        "p": "Britain had an answer ready. The colonists said they sent no members to Parliament, and that was true. But under the British doctrine of virtual representation, it did not matter. Every member of Parliament, the argument went, represented the whole nation and all its subjects, not merely the few who had voted him in. By that logic the colonists were represented exactly as huge British cities like Manchester and Birmingham were, places that returned no member of their own and yet were held to be spoken for all the same. The colonists rejected this flatly. They wanted actual representation, members they themselves had elected, or no taxes at all. The two doctrines could not be reconciled, and the whole quarrel would turn on the gap between them."
      },
      {
        "p": "Out of that argument came a phrase that settled into words across a dozen colonies at once. In 1764 the Massachusetts lawyer James Otis Jr. published a pamphlet, *The Rights of the British Colonies Asserted and Proved*, one of the earliest and most influential statements of the colonial case. The idea it helped crystallize, that people could be taxed only by a legislature they had voted for, hardened over the next year into a slogan: no taxation without representation. It was less one man's coinage than a conviction settling into words across the colonies at the same time."
      },
      {
        "fig": "/war-img/rev-james-otis.jpg",
        "cap": "James Otis Jr., whose 1764 pamphlet helped turn a tax dispute into a constitutional argument.",
        "credit": "Portrait of James Otis Jr. · public domain"
      },
      {
        "p": "It is worth being clear about what the colonists were, and were not, asking for in 1764. Almost no one wanted to leave the empire. They were not yet Americans demanding independence. They were Britons demanding the rights of Britons, the same protections they believed any subject of the Crown was born to, the right not to be taxed except by their own consent. They thought they were defending the British constitution, not breaking with it."
      },
      {
        "p": "That was where the line sat at the close of 1764. The colonists had drawn a distinction, external taxes they would tolerate, internal taxes they would not, and Parliament had not yet truly tested it. The following year it would, with a tax aimed squarely at the internal side of the line, on the paper of everyday colonial life. It had a name, the Stamp Act, and it would blow the whole argument wide open."
      },
      {
        "pill": "/war-revolution/off-the-battlefield/stamp-act",
        "plabel": "The Stamp Act"
      }
    ],
    "meanwhile": {
      "region": "London",
      "title": "A new king, a new resolve",
      "body": "George III had taken the throne in 1760 determined to govern, not just reign. His ministers looked at a real war debt and a vast new empire and saw one problem they thought they had every right to fix: the colonies had grown used to running themselves, and that was going to stop."
    }
  },
  "stamp-act": {
    "eyebrow": "The internal tax arrives, and the argument blows wide open",
    "title": "The Stamp Act",
    "blocks": [
      {
        "p": "The internal tax the colonists had sworn Parliament could never lay on them arrived on 22 March 1765. Where the Sugar Act of the year before had been a duty on trade collected at the ports, the Stamp Act reached inside the colonies and taxed activity there, landing squarely on the side of the line the colonists had spent a year insisting was theirs alone. There was nothing left to argue about over what kind of tax it was. The argument they had been having in pamphlets and assembly resolutions was about to spill into the streets."
      },
      {
        "p": "It passed easily. Parliament, the British legislature, runs on two chambers: the elected House of Commons and the appointed House of Lords. The Stamp Act cleared the Commons by a wide margin, with 49 opposed, and the Lords passed it without a recorded vote against. To the men in Westminster it was not a provocation but a settled piece of housekeeping, sponsored by George Grenville (the meticulous finance minister of Chapter 1), aimed at the same problem as everything else: the war debt, and the cost of the army Britain was keeping in North America. The act would not take effect until 1 November 1765, which gave the colonies seven months to read it, and to react."
      },
      {
        "fig": "/war-img/rev-stamp-stamp.jpg",
        "cap": "The object itself: a one-penny stamp, crown and scepter and the word AMERICA, that by law had to appear on a long list of everyday paper. Almost none were ever sold.",
        "credit": "British proof of the 1765 one-penny stamp · public domain"
      },
      {
        "pill": "/war-revolution/off-the-battlefield/bill-comes-due",
        "plabel": "The bill comes due"
      },
      {
        "h": "A tax on paper",
        "eyebrow": "Why this one detonated"
      },
      {
        "p": "The mechanism was simple, which was part of why it reached so far. A wide range of paper goods now had to be printed on, or carry, an embossed tax stamp, special stamped paper you bought from a royal distributor. No stamp, no legal validity. The list of taxed items was deliberately broad. It covered legal documents and contracts, court papers, the ship's papers and clearances a merchant needed to move cargo, licenses, newspapers, pamphlets, almanacs, and, down at the level of an ordinary evening, playing cards and dice."
      },
      {
        "p": "That list is the whole story of why this tax detonated where the Sugar Act had only grumbled. The Sugar Act fell mainly on importers of molasses. The Stamp Act fell on the loudest and most literate people in colonial life, and on nearly everyone else besides. Lawyers could not file a paper without it. Printers and newspapermen, the men who set the public mood in type, were taxed on their newspapers, their pamphlets, and their almanacs. Merchants were taxed on the documents that made trade legal. And in the taverns where colonists argued and drank, the cards and the dice were taxed too. The structure of the tax put it squarely on the professions most able to write, print, and argue their way to outrage, and reached the daily life of just about everyone else."
      },
      {
        "p": "Two more features sharpened the grievance. The tax had to be paid in specie (hard coin, gold and silver, as opposed to paper money), and coin was chronically scarce in the colonies, so the act demanded the one form of money colonists had least of. And anyone accused of evading it would be tried in a vice-admiralty court, the juryless tribunal before a single Crown judge that Chapter 1 introduced, the same enforcement colonists had already come to hate under the Sugar Act."
      },
      {
        "p": "Britain did not see any of this as outrageous, and it helps to understand why. The Stamp Act was modeled on a stamp duty that had existed in Britain itself since 1694, first levied under William III and Mary II to help pay for a war against France. Britons at home had been buying stamped paper for some seventy years. From Grenville's side of the ocean, asking the colonies to shoulder a tax their fellow subjects in England had paid for two generations did not look like tyranny. It looked like fairness, finally applied evenly. The colonists, who elected nobody to the Parliament doing the taxing, saw the same act from the opposite shore and called it theft."
      },
      {
        "h": "The colonies catch fire",
        "eyebrow": "Patrick Henry, and a Congress that bows as it objects"
      },
      {
        "p": "The first sparks flew in Virginia. On 29 May 1765, a young, newly seated member of the House of Burgesses (Virginia's elected assembly) named Patrick Henry rose to propose a set of resolutions (formal statements of position, not binding laws) against the Stamp Act. He offered seven resolves. The House, more cautious than he was, adopted only the first four; it passed the fifth and then struck it from the record the next day, once the firebrand Henry had reportedly gone home; and the sixth and seventh, the most radical, it never adopted at all. On paper, Virginia had said something fairly measured."
      },
      {
        "p": "That is not what the rest of the colonies heard. Newspapers up and down the coast printed all seven of Henry's resolves as though every one had passed, including the inflammatory ones Virginia had refused. The shared sense that Virginia had thrown down a bold, near-defiant challenge was built on resolutions Virginia had not actually enacted. The myth traveled faster, and farther, than the fact."
      },
      {
        "p": "Henry's speech that day became famous too, though here the ground is shakier. Tradition holds that he warned the king by invoking the men who had killed tyrants, something to the effect that Caesar had his Brutus and Charles the First his Cromwell, and that George the Third might profit by their example, and that when cries of \"Treason!\" went up he answered that if this be treason, make the most of it. It is a marvelous scene. It is also not securely documented. The fullest version rests heavily on a single account that surfaced long after, and the surviving accounts disagree on the exact words, on which tyrant-killers Henry named, and even on whether he half-apologized to the House afterward. What can be said safely is that Henry gave a defiant, near-treasonous speech that held up the killers of kings as a warning to King George III, and that it drew shouts of treason. The exact lines are tradition, not transcript."
      },
      {
        "fig": "/war-img/rev-stamp-henry.jpg",
        "cap": "Patrick Henry, whose 1765 resolves against the Stamp Act electrified the colonies, partly because newspapers printed resolutions Virginia had refused to pass. This is a later likeness; no one painted Henry from life at the time of the speech.",
        "credit": "Portrait of Patrick Henry, after Thomas Sully · public domain"
      },
      {
        "p": "From 7 to 25 October 1765, delegates from nine of the thirteen colonies, twenty-seven men in all, met in New York City as the Stamp Act Congress. It was the first time representatives of multiple colonies had gathered and acted jointly to oppose a measure from London."
      },
      {
        "p": "What the Congress produced is worth reading closely, because it tells you how far from independence these men still were. They issued a Declaration of Rights and Grievances, agreed in mid-October, and petitioned the King and both houses of Parliament. They claimed the rights of Englishmen: that they could be taxed only with their own consent, given through their own elected representatives; that they were entitled to trial by jury; and that only their own colonial assemblies could tax them. And in the same breath, they professed their loyalty and allegiance to the Crown. This was not a body threatening rebellion. It was a body bowing to the king while it objected to his Parliament, asking, by formal petition, for rights it believed it already held as British subjects."
      },
      {
        "h": "The crowds turn to force",
        "eyebrow": "Effigies, a gutted mansion, and an empire's unease"
      },
      {
        "p": "In Boston the crowds moved first, and hard. On 14 August 1765, a crowd hung an effigy (a stuffed dummy made to represent a hated person) of Andrew Oliver, the man appointed to distribute the stamps in Massachusetts, from a great elm that became known as the Liberty Tree. They paraded the effigy, tore down a building said to be his stamp office, and carried the wreckage to his door. The message was not subtle, and it worked. Oliver resigned within days, first privately and then publicly."
      },
      {
        "p": "This kind of organizing had a name and a network behind it. Out of 1765 came local resistance groups that called themselves the Sons of Liberty, forming in Boston, New York, and elsewhere to coordinate protest and, when they chose, crowd action. The name came from across the ocean. In a February 1765 speech in the House of Commons, the Irish-born member Isaac Barré, who had served in North America during the French war and rose to speak in the colonists' defense, called them \"sons of liberty\" while arguing against the tax. The colonists liked the phrase enough to take it as their own, and the organizing spread along the coast."
      },
      {
        "p": "Twelve days after Oliver's door, the crowd went much further, and crossed a line that troubled even people who hated the tax. On the night of 26 August 1765, a Boston mob attacked the mansion of Thomas Hutchinson, the colony's Crown-appointed lieutenant governor (deputy to the royal governor) and chief justice. They did not just frighten him. They tore the place apart from the inside, splitting the woodwork, breaking down the doors, smashing the furniture, scattering and destroying his library and his papers, and ruining the garden, with the damage later put at roughly £2,200, a fortune at the time. By some accounts they carried off hundreds of pounds in cash as well. By morning one of the finest houses in Boston was a gutted shell."
      },
      {
        "p": "The bitter irony is that Hutchinson privately thought the Stamp Act was bad policy. He had not made it and did not like it. But as a Crown officer he held that a law, however foolish, had to be obeyed until it was repealed (formally cancelled), and for that the crowd nearly destroyed him. Because Hutchinson held his offices by Crown appointment, the attack was also an attack on royal authority itself. It disturbed a great many colonists who opposed the tax just as firmly as the mob did. It was one thing to petition, to boycott, to burn an effigy of an official who could resign and be safe; it was another to ransack the home of a man who agreed the tax was wrong. The crowds that fought the Stamp Act were never one mind. They spanned genuine principle, local grievance, and plain opportunism, and the more respectable opponents of the tax watched the violence with real unease, worried about what they had helped unleash. The quarrel was already, in part, Britons against Britons over what the British constitution required."
      },
      {
        "p": "Whatever the unease, the pressure achieved its object. Up and down the coast, stamp distributors were threatened, hung in effigy, and coerced into resigning before the act could even take effect on 1 November. By the time that date arrived, there was almost no one left to sell the stamps. The result was a tax effectively nullified before it began. Barely any stamps were ever sold or used in the mainland colonies. Some courts and presses briefly suspended business; most simply carried on with unstamped paper as if the law did not exist."
      },
      {
        "p": "The printers turned their predicament into theater. On 31 October 1765, the eve of the act, William Bradford laid out the front page of his *Pennsylvania Journal and Weekly Advertiser* as a tombstone. A skull and crossbones stood in for the hated stamp, with the line that it was \"An emblem of the effects of the STAMP,\" and the page mourned the paper as \"EXPIRING: In Hopes of a Resurrection to LIFE again.\" It was a funeral notice for the press itself. It was also pure performance: Bradford did not actually stop printing, and the *Journal* came out the following week as usual. The death was a protest, not a closing."
      },
      {
        "fig": "/war-img/rev-stamp-tombstone.jpg",
        "cap": "William Bradford dressed his Pennsylvania Journal as a gravestone the day before the Stamp Act took effect, complete with a skull-and-crossbones mock stamp. He kept printing anyway.",
        "credit": "Pennsylvania Journal front page, 1765 · Library of Congress · public domain"
      },
      {
        "h": "The boycott bites",
        "eyebrow": "Hitting Britain where it could feel it"
      },
      {
        "p": "Refusing the stamps killed the tax in America. What got it killed in London was money. Colonial merchants reached for a tool that turned out to be far more powerful than any petition: they stopped buying. In nonimportation agreements, merchants pledged to import no British goods until the act was repealed. New York's merchants agreed first, on 31 October 1765, often counted at roughly two hundred of them, and Boston and Philadelphia followed before the year was out."
      },
      {
        "p": "These were among the first large-scale economic boycotts the colonies had ever organized, and they hit a real nerve. The colonies were a major market for British manufactures, and when that market closed, the order books of British merchants and manufacturers emptied and their workers went idle. Those merchants and manufacturers were also voters and petitioners with the ear of Parliament, and they used it, crowding the lobbies and pressing for repeal not on any constitutional principle but on the plain ground that the act was wrecking their trade."
      },
      {
        "h": "Repeal, and its sting",
        "eyebrow": "The tax goes, the principle stays"
      },
      {
        "p": "By early 1766 the political ground in London had shifted. Grenville was no longer in charge. His ministry (the cabinet of ministers running the government) had fallen back in July 1765, when the king dismissed Grenville and his colleagues and replaced them with a ministry under the Marquess of Rockingham, an aristocratic politician more inclined to find a way out. But the reason had nothing to do with American protest. Grenville fell over a falling-out with King George III, before the worst of the colonial unrest, and it would be a mistake to imagine the colonists had toppled him. What mattered was that the new ministry was more willing to find a way out."
      },
      {
        "p": "The way out came partly through Benjamin Franklin, the Pennsylvania printer and scientist then serving in London as a colonial agent (an unofficial representative a colonial assembly hired to lobby for it in London). On 13 February 1766, Franklin sat for a formal hearing in which members of the House of Commons questioned him directly, answering a long string of questions, commonly counted at well over a hundred. He told the members what colonists had been saying for two years: that the colonies accepted external duties on trade but rejected an internal tax like the stamp tax. His testimony was widely printed and genuinely influential."
      },
      {
        "p": "On 18 March 1766, Parliament repealed the Stamp Act. But it is essential to see why, and to see what Parliament did in the very same breath. Repeal was justified to the members not as an admission that the colonists were right, but on grounds of expediency: the act was strangling British trade and had proven impossible to enforce. To make sure no one mistook a practical retreat for a surrender of principle, Parliament passed, on the same day, the Declaratory Act, which asserted its full authority to make laws binding the colonies \"in all cases whatsoever.\""
      },
      {
        "p": "That phrase is the heart of the matter. Parliament gave up the tax and kept the power. It conceded nothing the colonists had actually been arguing about, the question of whether it could tax them without their consent, and instead restated, in the broadest possible language, the very authority they denied it held. The repeal was real relief, but it was not a colonial victory of principle. It was a retreat on the tax paired with a flat restatement of the very power the colonists denied Parliament held."
      },
      {
        "fig": "/war-img/rev-stamp-repeal-cartoon.jpg",
        "cap": "A London cartoon of 1766 stages the repeal as a funeral, with the dead \"Miss Ame-Stamp\" carried to her grave. The repeal was driven less by principle than by British merchants whose trade the boycott had wrecked.",
        "credit": "\"The Repeal, or the Funeral of Miss Ame-Stamp,\" Benjamin Wilson, 1766 · public domain"
      },
      {
        "h": "What it meant",
        "eyebrow": "A win that settled nothing"
      },
      {
        "p": "When the news reached the colonies in the spring of 1766, New York heard it on 26 April, and the colonists celebrated. They lifted the boycotts and dropped the nonimportation pledges. And the crucial thing about how they celebrated is whom they celebrated as. They rejoiced as loyal Britons who had won a fight inside the empire, by petition and protest and pressure, not as a people taking a step toward leaving it. In gratitude, New York commissioned two statues from a London sculptor (commissioned in the flush of 1766, though both went up only in 1770): one of William Pitt the Elder, a prominent British politician who had spoken against the Stamp Act as a violation of colonial rights, and a gilded equestrian statue of King George III himself, raised on Bowling Green in New York. They were thanking their king and their friends in Parliament. In 1765 and 1766, independence was essentially nobody's goal."
      },
      {
        "fig": "/war-img/rev-stamp-liberty-tree.jpg",
        "cap": "Paul Revere's 1766 engraving of the illuminated obelisk Boston raised under its Liberty Tree to celebrate the repeal. The Liberty Tree, shown on one panel, was the same elm where crowds had hung the stamp distributor in effigy the year before.",
        "credit": "Paul Revere, 1766 · public domain"
      },
      {
        "p": "For all the celebrating, nothing underneath had actually been settled. The colonists thought they had won, and in the narrow sense of the tax they had. But the Declaratory Act sat there in the law books saying, in the plainest words Parliament could find, that it could bind the colonies in all cases whatsoever. The exact power the colonists insisted Parliament did not possess had just been reaffirmed by the same Parliament that pretended to retreat. The constitutional gap that opened in 1764 was still wide open in 1766; the two sides had merely stepped back from the edge of it."
      },
      {
        "p": "What the colonists took away was not just relief. It was a method. They had learned to organize across colony lines, in the Stamp Act Congress and the spreading network of the Sons of Liberty. They had discovered that a coordinated boycott could reach across an ocean and move Parliament where petitions could not. They had a playbook now, written in a single year of crisis, and the unresolved question of who could tax them was not going to stay quiet for long."
      }
    ],
    "meanwhile": {
      "region": "London",
      "title": "A retreat that conceded nothing",
      "body": "To the men in Westminster, repealing the Stamp Act was not backing down on principle. The boycott was hurting British merchants and the tax could not be collected, so they cut their losses. The Declaratory Act, passed the same day, was there to make the point unmistakable: Parliament could still bind the colonies in all cases whatsoever. They thought they had ended a nuisance, not lost an argument."
    }
  },
  "boston-massacre": {
    "eyebrow": "Parliament tries again, this time cleverly, and Boston gets an army",
    "title": "The Townshend Acts & the Boston Massacre",
    "blocks": [
      {
        "p": "Here was the clever part. The colonists had spent the Stamp Act crisis insisting on a distinction between two kinds of taxes: external duties on trade, collected at the ports, which they would accept, and internal taxes laid simply to raise money, which they would not. Parliament had backed down on the Stamp Act but kept the asserted power to bind the colonies \"in all cases whatsoever\" (Chapter 2), and it meant to use that power. So the next minister to reach into colonial pockets decided to tax them on the side of the line they had said was fine, and dare them to object."
      },
      {
        "p": "That minister was Charles Townshend (pronounced \"TOWNZ-end\"), the Chancellor of the Exchequer (the British government's chief finance minister, the official in charge of taxes and the treasury, the senior Cabinet figure who introduces the money bills Parliament then votes on). He was a famous talker, brilliant and reckless, who once gave a speech to the House of Commons so dazzling and so drunk it earned him the nickname \"Champagne Charlie.\" Horace Walpole, a prolific letter-writer and memoirist who chronicled the London political world of his day, said it ran \"an hour, with torrents of wit, ridicule, vanity, lies, and beautiful language.\" In 1767 Townshend set out to call the colonists' bluff."
      },
      {
        "pill": "/war-revolution/off-the-battlefield/stamp-act",
        "plabel": "The Stamp Act"
      },
      {
        "h": "Townshend's gambit",
        "eyebrow": "External duties, with a sharp hidden point"
      },
      {
        "p": "In mid-1767 Parliament passed a cluster of related laws that together became known as the Townshend Acts. The core measure, the Revenue Act, received royal assent on 29 June 1767. It laid import duties on a short list of goods brought into the colonies: glass, lead, paints and painters' colors, paper, and tea. Every one of them was collected at the port as the ship came in. Every one of them was, by the colonists' own definition, an external duty. That was the entire design. Townshend was taking the colonists at their word, taxing only the kind of tax they had publicly said they could live with."
      },
      {
        "p": "The amount of money involved was modest, and the money was never really the point. The point was buried in what the revenue was *for*. The duties were earmarked to pay the salaries of royal governors and judges in the colonies directly, out of the Crown's own collected funds."
      },
      {
        "p": "To see why that was alarming, you have to know where those officials' pay had come from before. For generations the colonial assemblies (the elected local legislatures, one per colony, that ran each colony's internal affairs) had voted the governors' and judges' salaries themselves, year by year. That gave the assemblies enormous leverage. A royal governor who crossed his assembly could find his pay held hostage, and a judge knew who signed his check. The power of the purse was the colonists' single strongest check on Crown officials sent from London. Townshend's duties would cut that cord. A governor paid from London answered to London and could ignore the assembly that no longer fed him. So a tax that looked small was aimed at something large: prying the king's officials loose from local control."
      },
      {
        "p": "The cluster came with enforcement to match. The Commissioners of Customs Act, also of 29 June 1767, created a new five-man American Board of Customs Commissioners, seated at Boston in November 1767, to police the trade laws and collect the duties up close. The board could act without waiting on London, hired more customs officers, and paid informers. To do their searching the customs men leaned on writs of assistance (open-ended search warrants that let an officer search any premises for smuggled goods without naming a specific place or cause), the same general warrants that James Otis, a Boston lawyer who became a patriot hero for arguing against these very search warrants in court in 1761, had famously denounced. None of this was new in kind. What was new was the will to actually enforce it, and to plant the enforcers in the middle of Boston."
      },
      {
        "p": "Townshend himself never saw what his acts set off. He died suddenly of a fever in September 1767, aged forty-two, before any word of colonial resistance could reach him. The gambit outlived the gambler."
      },
      {
        "h": "The colonial answer",
        "eyebrow": "A sharper principle, the homespun boycott, and a vote of 92 to 17"
      },
      {
        "p": "Most colonists refused to take the bait, though not without argument and not all at once. And in refusing it, they sharpened their own case. During the Stamp Act crisis they had drawn the line between external and internal taxes. Now they redrew it. The test, they decided, was not *where* the tax was collected but *why* it was laid. A duty meant to regulate trade was one thing. A duty meant to raise revenue from Americans without the consent of their own assemblies was another, and it was illegitimate whether you collected it at the port or in the parlor. No tax for revenue, external or internal, without consent. Townshend had tried to trap them on a technicality, and they answered by moving the principle out from under him."
      },
      {
        "p": "The clearest statement of that argument belonged to John Dickinson. Parliament could regulate the colonies' trade, he granted; what it could not do was tax Americans for revenue without their consent, by any name, at any port. That was the whole case in a sentence, and Dickinson made it sound like common sense rather than rebellion. He was a wealthy Philadelphia lawyer who wrote under the modest persona of a \"Pennsylvania Farmer,\" precisely so the case would read as plain country wisdom and not as elite lawyering. His tone was moderate, and he urged petition and patient resistance, not violence and not independence. The argument earned its audience. Beginning on 2 December 1767, his *Letters from a Farmer in Pennsylvania* appeared in a Philadelphia newspaper, twelve letters in all, running over the following weeks and then collected as a pamphlet. They were reprinted almost everywhere, in nineteen of the twenty-three colonial English-language newspapers and abroad in London, Dublin, and Paris. Dickinson became the calm, careful face of the colonial case, and he set the terms most colonists argued on."
      },
      {
        "p": "The institutional answer came out of Massachusetts. Early in 1768 Samuel Adams, working with James Otis, drafted what became the Massachusetts Circular Letter, a letter from the Massachusetts House of Representatives to the other colonial assemblies urging them to resist the Townshend taxation together. The Massachusetts House approved it on 11 February 1768 and sent it round."
      },
      {
        "p": "London treated a letter as a rebellion. Lord Hillsborough, newly installed as the first Secretary of State for the Colonies (a cabinet minister created in 1768 specifically to manage America), ordered the Massachusetts House to take the letter back, to rescind it (formally vote to withdraw and cancel it), and instructed the other royal governors to dissolve any assembly that dared endorse it. On 30 June 1768 the Massachusetts House refused to rescind, by a vote of 92 to 17. \"The Massachusetts 92\" became an instant patriot emblem, the number painted on signs and worked into toasts. Governor Francis Bernard answered the defiance by dissolving the Massachusetts assembly outright, and several other royal governors dissolved their own assemblies as those took up the letter. London had set out to isolate Massachusetts and instead handed every colony a shared grievance and a number to rally around."
      },
      {
        "p": "Behind the pamphlets and the votes, the colonists reached again for the weapon that had actually beaten the Stamp Act: the boycott. Merchants revived nonimportation, the pledge to buy no British goods until the duties were repealed. Boston's merchants signed the Boston Non-Importation Agreement on 1 August 1768, and New York joined that year. Philadelphia held out, joining only in 1769 after its merchants had quietly stocked up on British goods first, a delay that was its own small proof that the colonies were not one mind moving together but many interests calculating separately."
      },
      {
        "p": "A boycott of British cloth only works if someone makes the cloth at home. That someone was women. Across the colonies, spinning and weaving became public, political acts. Groups calling themselves the Daughters of Liberty (informal groups of colonial women who took the name to signal patriot loyalty) held spinning bees, gatherings where dozens of women spun thread together in a kind of patriotic performance, and homespun cloth, rough fabric woven in colonial households instead of bought from Britain, turned into a badge of loyalty to the cause. Wearing homespun said which side you were on. This was not decoration around the edges of the real protest. Refusing to buy British goods was the protest, and the women who made the substitutes at home were the ones who made the refusal possible."
      },
      {
        "fig": "/war-img/rev-boston-dickinson.jpg",
        "cap": "John Dickinson, the wealthy Philadelphia lawyer who wrote as a humble \"Pennsylvania Farmer.\" His twelve calm, lawyerly letters denied that Parliament could tax the colonies for revenue by any name, and set the terms most colonists argued on.",
        "credit": "Portrait of John Dickinson, Charles Willson Peale · public domain"
      },
      {
        "h": "The occupation",
        "eyebrow": "A seized sloop, a riot, and regiments in the streets"
      },
      {
        "p": "The new customs board had a miserable time in Boston from the moment it sat down in November 1767. Bostonians harassed the commissioners, crowded them, and intimidated them as a matter of routine. The friction finally caught fire over a ship."
      },
      {
        "p": "The ship was the *Liberty*, a sloop belonging to John Hancock, one of Boston's richest merchants. In May 1768 customs officers boarded her and found only about twenty-five pipes (large casks) of Madeira wine aboard, far less than a vessel her size could carry, which looked very much like most of her cargo had been quietly run ashore without paying the duty. That was the contemporary suspicion, not a proven fact. A month later, with the Royal Navy warship HMS *Romney* now anchored in the harbor, a customs official revised his earlier account, claiming far more had been smuggled. On 10 June 1768 the officers seized the *Liberty*, marked her, and had her towed out under the *Romney*'s guns. Boston erupted. A waterfront riot broke out, the Custom House (the office where the duties were collected) was attacked, and officers were roughed up. The customs commissioners fled for their lives, first out to the *Romney* and then to Castle William, a British military fort on an island just offshore, beyond the reach of the town."
      },
      {
        "p": "This was the riot that brought the army. London, reading the *Liberty* affair and Boston's general defiance as a town slipping out of control, sent regular troops to garrison it. On 1 October 1768 the 14th and 29th Regiments of Foot (infantry units, each several hundred soldiers strong) landed at Long Wharf, about twelve hundred soldiers off a fleet of naval vessels, and marched up King Street into the town. To one hostile observer they came \"with insolent Parade, Drums beating, Fifes playing, and Colours flying,\" though the drums and colors were simply how a regiment came ashore anywhere in the empire. What read as insolence to a Bostonian was routine garrison procedure. A detachment of the 59th Regiment and a couple of artillery pieces came with them. In November two more regiments, the 64th and 65th, arrived, pushing the garrison well over two thousand men."
      },
      {
        "p": "An army in a city is one thing in wartime and another thing entirely in peace. Boston was not under siege and not at war. It was a working port suddenly full of off-duty soldiers competing with local men for scarce day labor, packed into disputed quarters, trading insults and shoves with townspeople who had not asked them to come and did not want them there. That friction did not explode. It ground on, day after day, for sixteen months. The thing to hold onto is the duration. What happened on King Street in March 1770 was not a single spark in dry grass. It was the moment a year and a half of accumulated resentment, on both sides, finally went off."
      },
      {
        "fig": "/war-img/rev-boston-troops-landing.jpg",
        "cap": "Paul Revere's engraving of the British landing of October 1768: warships crowding the harbor and the regiments coming ashore at Long Wharf to garrison a town that was not at war. The occupation ground on for sixteen months before the violence on King Street.",
        "credit": "Paul Revere, \"A View of Part of the Town of Boston… and Brittish Ships of War Landing Their Troops! 1768\" · public domain"
      },
      {
        "h": "The killings on King Street",
        "eyebrow": "A cornered relief party, a pelting crowd, and five dead"
      },
      {
        "p": "The night of 5 March 1770 began with a small, stupid quarrel. A wigmaker's apprentice, a boy of about thirteen named Edward Garrick, called out a British officer over an unpaid bill near the Custom House. The lone sentry posted there, Private Hugh White of the 29th Regiment, told the boy to show some respect. Insults flew both ways, and then White stepped out and struck Garrick on the head with his musket. A crowd began to gather around the single soldier. Church bells rang, which usually meant a fire, and the sound pulled still more people into the street toward White, who now had his back to the Custom House wall and a swelling, angry crowd in front of him."
      },
      {
        "p": "Captain Thomas Preston marched a relief party down to rescue his sentry, a corporal and six or seven privates of the 29th with bayonets fixed to their muskets. They pushed through to White and formed up against the building, and now there were eight soldiers in all, counting Preston, cornered against a wall in the dark with the crowd pressing in."
      },
      {
        "p": "The crowd was not a gentle one. It was made up of waterfront workers, sailors, and young apprentices, the men who had spent sixteen months elbowing these same soldiers for work and space, and they had come spoiling for it. How big the crowd was, nobody can say for certain. There are more than two hundred surviving eyewitness accounts and they disagree wildly, with estimates running from fifty or sixty people up to three or four hundred. Patriot witnesses remembered a small knot of bystanders; the soldiers' defenders remembered a mob. What the accounts agree on is what the crowd did. They pelted the soldiers with snowballs, chunks of ice, oyster shells, and sticks. They jeered. And they dared the soldiers to shoot, shouting \"Fire!\" at men they did not believe would dare. The soldiers were genuinely menaced, cornered, and being hit, by a crowd that was taunting them to do the one thing they would later hang for."
      },
      {
        "p": "Then the dark and the noise took over. Private Hugh Montgomery went down. A club, a chunk of ice, something thrown, no one ever agreed what. He got back to his feet and fired. Then others fired, raggedly, not in any order, not in a volley. What set it off was never settled. Whether Preston gave the word, whether Montgomery shot on his own after being struck, whether someone in the crowd shouted \"fire\" and the soldiers took it for a command, that was the very question the trial would turn on."
      },
      {
        "p": "No order from Preston was ever proven."
      },
      {
        "p": "Five townspeople were killed, none of them armed with a gun. Three died on the spot: Crispus Attucks, a dockworker and sailor of African and Wampanoag (a Native people of coastal Massachusetts) descent; Samuel Gray, a ropemaker; and James Caldwell, a mariner. Samuel Maverick, a seventeen-year-old apprentice, died early the next morning. Patrick Carr, an Irish immigrant who made leather breeches, lingered and died of his wounds nine days later, on 14 March. About six others were wounded. The five dead were buried together after a funeral procession that drew one of the largest crowds colonial Boston had ever seen, and they were laid in a shared grave at the Granary Burying Ground."
      },
      {
        "p": "Crispus Attucks is worth pausing on, carefully, because so much was later piled onto him. What is known is spare: he was of African and Wampanoag descent, born around 1723, worked the docks and the sea, and was at or near the front of the crowd and among the first to fall, often called the first to die. Whether he actually led the crowd toward the soldiers, as later legend insisted, is disputed and probably mythologized. A generation later abolitionists would make him \"the first martyr of liberty,\" and a Crispus Attucks Day was held in Boston in 1858, but that is the work of the 1850s, not testimony from 1770. There is no honest portrait of the man. The one thing that can be said plainly, without reading anything into his own motives, is the bitter fact of it: a man of African descent was among the first to die in a struggle that, when it won, would not free the enslaved."
      },
      {
        "h": "The name and the engraving",
        "eyebrow": "How five killings on a winter night became \"the Massacre\""
      },
      {
        "p": "What happened on King Street was a chaotic, violent nighttime confrontation in which a small, cornered, genuinely menaced relief party fired into a hostile crowd that had been pelting them and daring them to shoot. Five unarmed townspeople died, which is its own terrible fact and does not need exaggerating. It was not a planned slaughter and it was not one-sided. But \"a chaotic nighttime confrontation with deaths on one side\" does not move a crowd. So Boston's patriots gave it a name that did: the Boston Massacre. The word was a choice, and it was the right one for their purpose. A massacre is a deliberate killing of the helpless, which is not what the witnesses described, but it is what the word told everyone who heard it."
      },
      {
        "p": "The picture did the rest. Within weeks Paul Revere, the Boston silversmith and engraver, advertised a print on 26 March 1770 titled *The Bloody Massacre Perpetrated in King Street*. It became the single most effective piece of propaganda of the entire pre-Revolution, and almost nothing in it is true. Revere's engraving shows a neat line of redcoats firing in unison on a clear command, an officer behind them with his sword raised giving the order. It shows a defenseless, well-dressed crowd doing nothing, with no snowballs, no ice, no clubs, no provocation of any kind. It sets the scene in broad daylight, though the killings happened around half past nine at night. It labels the Custom House \"Butcher's Hall\" and adds a musket firing from one of its windows, an atrocity that was alleged and never proven. Every one of those details is wrong, and every one of them was wrong on purpose, chosen to convert a messy street fight into a disciplined execution of innocents."
      },
      {
        "p": "Revere did not even design it. A young Boston artist named Henry Pelham drew the scene first. Revere saw Pelham's drawing, copied it, and rushed his own version to print first, without crediting him. Pelham wrote Revere a furious letter on 29 March 1770 accusing him of the theft, which only underlines the point: the image that taught the colonies what to feel about the Massacre was a copy of a copy, engineered for effect rather than accuracy. It worked anyway. It worked because it was vivid, and because most of the people who saw it were never going to be in a courtroom checking it against the evidence."
      },
      {
        "fig": "/war-img/rev-boston-engraving.jpg",
        "cap": "Propaganda, and deliberately false. Paul Revere's famous engraving shows redcoats firing in a disciplined line on an officer's order, into a passive, defenseless crowd, in daylight, beside a Custom House relabeled \"Butcher's Hall.\" In fact the soldiers were a cornered relief party pelted with ice and clubs and dared to fire, at night, with no order ever proven. Revere copied the design from Henry Pelham and printed it first without credit.",
        "credit": "Paul Revere, \"The Bloody Massacre Perpetrated in King Street,\" 1770 · Library of Congress · public domain"
      },
      {
        "h": "The trial and the half-repeal",
        "eyebrow": "John Adams defends the soldiers, and Parliament keeps one tax"
      },
      {
        "p": "Here the story turns in a direction the engraving would never lead you to expect. When the eight soldiers and their captain came to trial, the man who stood up to defend them was John Adams, a Boston lawyer and as committed a patriot as any in the town. It is hard to overstate how exposed this put him. He was a public Boston patriot agreeing to defend the very soldiers who had killed Boston patriots, in front of the neighbors of the dead. He took the case anyway, with Josiah Quincy Jr., another young Boston patriot lawyer, on principle. If British soldiers could not get a fair trial in Boston, then Boston's claim to be defending the rights of Englishmen was a lie, and the rule of law the patriots said they stood for would be exposed as mob rule wearing a wig. Adams knew the defense might cost him his standing with his own side, and he took it anyway. He judged it afterward \"one of the best Pieces of Service I ever rendered my Country.\" In his closing argument he gave the case its most famous line: \"Facts are stubborn things; and whatever may be our wishes, our inclinations, or the dictates of our passions, they cannot alter the state of facts and evidence.\""
      },
      {
        "p": "The facts, soberly weighed, did not support a charge of murder. Captain Preston was tried in late October 1770 and acquitted, because the prosecution could not prove he had ordered his men to fire. The eight soldiers were tried in November. Six were acquitted outright. Two, Hugh Montgomery and Matthew Kilroy, were convicted only of manslaughter rather than murder. Cornered and provoked, with no deliberate plan to kill ever proven, they had killed unlawfully but not willfully, and that is the line between the two charges. They escaped the gallows by pleading benefit of clergy, an old legal mercy that began as a privilege for clergymen claiming trial in church courts and had hardened by this period into a one-time pardon: a first offender could escape the noose once. To make sure the mercy could only be used once, the court branded each man on the thumb, a permanent mark that the pardon had been spent and could never be claimed again, and released them. The defense was helped, pointedly, by one of the victims. Patrick Carr, the Irishman who took nine days to die, told his doctor before he died that he thought the soldiers had fired in self-defense and bore them no malice, and his dying words were allowed in as evidence. A Boston jury, in other words, looked hard at the killings the engraving called a massacre and declined to call them murder."
      },
      {
        "p": "While all of this played out, London was quietly conceding most of the fight. On 5 March 1770, the very day of the killings, though news of them had not yet crossed the ocean, Lord North (the king's new First Minister, the equivalent of a prime minister) moved in the House of Commons to repeal most of the Townshend duties. The repeal of the duties on glass, lead, paints, and paper became law that spring. But North deliberately kept one of them. The tax on tea stayed on the books, and North argued plainly that it had to, as a token to assert \"the right of taxing the Americans.\" It was the Declaratory Act all over again, scaled down to a single commodity: give up the revenue, keep the principle. Parliament would surrender almost everything before it would surrender the bare claim that it could tax the colonies at all."
      },
      {
        "p": "With the duties cut to tea alone, the boycott lost its reason for being and fell apart. Nonimportation collapsed colony by colony through 1770, in New York, then Philadelphia, then Boston, as merchants tired of the sacrifice declared the fight substantially won. And here the road to revolution does something that is easy to forget, because we know what comes later: it went quiet. A genuine calm settled over the colonies from 1770 onward, and it held for the better part of three years. The crowds went home. The committees stopped meeting. Independence was still nobody's goal, and most colonists still thought of themselves as aggrieved Britons who had won most of their argument and could now get back to business."
      },
      {
        "p": "But not all of it. One small tax was left standing in the law books, deliberately, as Parliament's flag planted in colonial ground: the duty on tea. It was still burning, very low, and it had not gone out."
      }
    ],
    "meanwhile": {
      "region": "London",
      "title": "A penny of principle on a pound of tea",
      "body": "Lord North thought he had defused the colonies cheaply. Repeal the duties that were costing British merchants their American trade, keep the one on tea purely to prove the point, and the agitation would die down. In the narrow sense he was right. The boycotts collapsed and the colonies fell quiet for years. What he had actually done was leave a single, deliberate tax in place as a matter of principle, on the one commodity Americans drank by the ton."
    }
  }
}
