// GENERATED by scripts/_build-rev-themes.mjs from audits/war-pipeline/rev-<slug>-final.md.
// Do NOT hand-edit — edit the gated -final.md and re-run the build script.
// The American Revolution off-the-battlefield theme narratives, consumed by the dynamic
// off-the-battlefield/[theme] route through the shared <BattleSectionReader>.

import type { Narr } from '@/components/mode/battle-reader'

export const THEME_NARR: Record<string, Narr> = {
  "bill-comes-due": {
    "eyebrow": "A victorious Britain, broke, decides the colonies must pay",
    "title": "The Bill Comes Due",
    "blocks": [
      {
        "p": "Britain had just won the greatest war it had ever fought, and it was nearly broke from winning. On 10 February 1763 the diplomats signed the Treaty of Paris, the agreement that ended the Seven Years' War (known in America as the French and Indian War). On paper the prize was staggering. France was swept off the North American mainland. Britain took all of Canada and every French claim east of the Mississippi River, and pried Florida loose from Spain. From the Atlantic to the great river, the map was suddenly red."
      },
      {
        "p": "Then the accounting started, and the victory began to look like a problem."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/treaty-of-paris",
        "plabel": "The Treaty of Paris & the Proclamation Line"
      },
      {
        "h": "The cost of winning",
        "eyebrow": "A debt that roughly doubled"
      },
      {
        "p": "Wars are paid for on borrowed money. A government at war sells bonds, promises to repay lenders later with interest, and the interest becomes a fixed yearly bill that keeps coming due long after the fighting stops. That running total is the national debt, and the war had roughly doubled Britain's. It climbed from roughly £75 million before the fighting to roughly £130 million by 1763 and 1764."
      },
      {
        "p": "The raw number is hard to feel. What made it bite was the interest. Servicing the debt, just paying the yearly fee on all that borrowing, swallowed more than half the entire national budget. And the people who would normally be asked to cover it were tapped out. British taxpayers at home were already among the most heavily taxed in Europe, between the land tax and a hugely unpopular new tax on cider that had badly damaged the standing of the previous ministry (the team of ministers who run the government). A government could win a war and still spend the peace cornered by its own creditors, and that is roughly where Britain stood."
      },
      {
        "fig": "/war-img/rev-george-iii.jpg",
        "cap": "George III, who came to the throne in 1760 and on whose watch the bill for the war finally came due.",
        "credit": "George III in his coronation robes · Allan Ramsay · public domain"
      },
      {
        "p": "Worse, the spending did not stop when the shooting did. There was now an empire to hold. Britain decided to keep a standing army in North America after the war, a peacetime force of full-time professional soldiers on the order of 10,000 regulars, to garrison the new conquests, watch the frontier, and manage relations with the Native nations of the interior. That army cost something in the range of a few hundred thousand pounds a year. London's reasoning was straightforward: the colonies were the war's chief beneficiaries, France had been driven off their continent, and the army was there for their protection, so they should help pay for it."
      },
      {
        "p": "The colonists would come to see the same army very differently. A standing army kept up in peacetime, quartered among them, looked less like protection than like control. They had not asked for it, and soon enough they would be asked to fund it."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/war-finance",
        "plabel": "The War Debt & the Road to Taxation"
      },
      {
        "h": "The end of the long leash",
        "eyebrow": "Salutary neglect, and the man who ended it"
      },
      {
        "p": "For most of the century before 1763, Britain had governed its American colonies with a remarkably light hand, an approach later given the name \"salutary neglect\" (beneficial inattention, the idea that the colonies prospered, and so did Britain, precisely because London mostly left them alone). The trade laws were on the books. The Navigation Acts (a body of law requiring colonial trade to move on British ships and pass through British ports) had stood for generations. But they were loosely enforced, and the colonies ran their own internal affairs through elected assemblies, one per colony, like a local parliament, that controlled local taxes and even paid the royal governors' salaries. Smuggling, especially of molasses, was so routine it was barely thought of as a crime."
      },
      {
        "p": "After 1763 a new ministry set out to reverse all of it: enforce the trade laws in earnest, raise money directly from the colonies, and pull them under tighter control from London. The man who drove that reversal was George Grenville, and he was, by temperament, exactly the man to do it. He was a trained lawyer and a specialist in money, twice Treasurer of the Navy, the kind of minister who mastered every line of an account and bored the House of Commons half to death reciting them. He came to power in April 1763 with the war debt as the defining problem on his desk, took over the Treasury (the department in charge of the nation's money), and became, in effect, prime minister from 1763 to 1765. He approached the colonies the way he approached everything, as a set of figures that did not yet add up. Before he asked them for a penny he studied the colonial customs system in detail and consulted the colonies' agents in London, and he came away convinced he was being entirely reasonable."
      },
      {
        "fig": "/war-img/rev-george-grenville.jpg",
        "cap": "George Grenville, a meticulous lawyer and finance man who inherited the war debt and concluded the colonies should help pay it down. The print names him Treasurer of the Navy, the post he held twice.",
        "credit": "18th-century mezzotint · public domain"
      },
      {
        "p": "On its own terms, his logic was hard to fault. He was not asking the colonies to retire the debt or even to cover its interest. He wanted a partial contribution toward the cost of the army standing guard on their own frontier. The trouble was not the arithmetic. It was that the colonies elected no members to Parliament (Britain's legislature, the body that wrote the laws and levied the taxes), not one, and Grenville was preparing to tax people who had no vote in the room."
      },
      {
        "h": "A line drawn on the mountains",
        "eyebrow": "The Proclamation of 1763"
      },
      {
        "p": "The first shock did not look like a tax at all. On 7 October 1763, King George III issued the Royal Proclamation of 1763, which drew a line down the crest of the Appalachian Mountains and forbade, at least for the moment, any new colonial settlement to the west of it. The land beyond was reserved as Indian territory, closed to colonial purchase and settlement."
      },
      {
        "p": "The Proclamation had been in the works before the frontier caught fire. What forced it into law was a war already burning in the interior. With the French gone, the Native nations of the Great Lakes and the Ohio Country had risen against the new British presence in a broad, coordinated resistance the British called Pontiac's War, after Pontiac, the Odawa war leader who organized and led the uprising. They fought to halt the settlers pushing onto their land and to force the British into honest terms of trade. London, looking at the cost of fighting them and the cost of the army it had just decided to keep, concluded that the cheapest way to keep the peace was to stop the land grab that kept provoking it. The line was, in part, an attempt to keep faith with Native nations who had just made the price of bad faith very clear."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/pontiacs-war",
        "plabel": "Pontiac's War & the Aftermath for Native Nations"
      },
      {
        "p": "To the colonists, the line was an outrage. Their charters, the founding documents that had created the colonies, claimed land running clear to the Pacific. Veterans had been promised western land for their service. Speculators had fortunes staked on the Ohio Country, among them a young Virginian named George Washington, who privately dismissed the Proclamation as a temporary measure to quiet the Native nations and went on quietly acquiring western claims anyway. For the first time, London was telling colonists where they could and could not go on what they thought of as their own continent."
      },
      {
        "p": "In practice the line barely held. It was poorly enforced, settlers crossed it almost at once, and over the following years it was steadily pushed west. But the principle stung even where the fence leaked. At bottom, the colonists' fury was fury at being told they could not take Native land, and that telling came from a Parliament across an ocean."
      },
      {
        "h": "The first reach into colonial pockets",
        "eyebrow": "The Sugar Act, 1764"
      },
      {
        "p": "In the spring the grievance turned from land to money. On 5 April 1764, Parliament passed the American Revenue Act, known almost universally as the Sugar Act, and at first glance it looked like a gift. It rewrote an old law, the Molasses Act of 1733, which had taxed foreign molasses (the thick dark syrup left from refining sugar, and the raw material of New England's rum trade) at six pence a gallon. That old duty had been so steep that colonial merchants simply smuggled around it, and almost nobody ever collected it. The Sugar Act cut the rate in half, down to three pence a gallon."
      },
      {
        "p": "But the cut was the trick. The lower rate was paired with strict, genuine enforcement. The idea was to set the duty low enough that paying it actually beat the cost and risk of smuggling, so that for the first time the tax would really be collected. A duty colonists had laughed off became, at half the rate, a real bill that came due."
      },
      {
        "p": "And it was a bill for revenue, not for trade. Earlier duties had existed to steer commerce, to nudge merchants toward buying British. The Sugar Act said the quiet part out loud in its own preamble (the opening statement of a law's purpose)."
      },
      {
        "p": "it is just and necessary that a revenue should be raised … for defraying the expenses of defending, protecting, and securing the colonies. — preamble to the Sugar Act, 1764",
        "q": true
      },
      {
        "p": "That was new. It made the Sugar Act, in effect, the first act of Parliament expressly designed to raise money from the colonies rather than merely to regulate their trade."
      },
      {
        "p": "To make the collection stick, the act came with teeth. Colonists had grown up on the common-law right to a jury of their peers, neighbors who heard your case and decided your fate. Under the Sugar Act, merchants accused of smuggling would no longer get one. Their cases were sent instead to vice-admiralty courts (special maritime courts run by a single Crown-appointed judge, with no jury at all), most notoriously the one at Halifax, in Nova Scotia, hundreds of miles from home. The rules there were rigged from the start. The burden of proof was reversed: the accused had to prove the seized goods had been imported legally, rather than the Crown having to prove they had not. And the customs officers and informers who brought the charges took a share of any cargo that was forfeited, a built-in reward for seizing it. To colonists raised on a jury trial and the presumption of innocence, this was less a court than a collection machine, a second alarm sounding underneath the first. And it all landed in the middle of a postwar economic slump, hardest of all on New England, where the rum trade was the spine of the economy."
      },
      {
        "p": "The colonies did not just grumble in private. In 1764 Massachusetts and other assemblies passed formal resolutions and petitioned Parliament directly against the Sugar Act, the first organized institutional protests, an early rehearsal for the united stand to come."
      },
      {
        "h": "The squeeze from the other side",
        "eyebrow": "The Currency Act, 1764"
      },
      {
        "p": "The same year brought a second pinch, this one on the money supply itself. Parliament passed the Currency Act of 1764, which restricted the colonies' power to issue paper money as legal tender (currency a creditor is legally required to accept in payment of a debt). British merchants and creditors had grown tired of being repaid in colonial paper that had lost value since they were owed the money, and the act was meant to protect them. On its face it was a fair enough request, and historians today do not rank colonial debts to British merchants among the leading causes of the Revolution."
      },
      {
        "p": "What made it bite was where it fell, and when. Gold and silver coin was chronically scarce in the colonies, and paper money was how a coin-starved economy did its everyday business. Now the two acts of 1764 worked as a single vise. The Sugar Act demanded its duties be paid in hard coin the colonies barely had, while the Currency Act strangled the paper money they actually used. Squeezed for scarce coin on one side and stripped of usable paper on the other, colonists felt London tightening both jaws at once, in the middle of a postwar slump."
      },
      {
        "h": "The argument begins",
        "eyebrow": "No taxation without representation"
      },
      {
        "p": "Taken one at a time, none of the 1764 measures was ruinous. Taken together, and arriving all at once, they pushed colonists past complaining about the money and into a deeper question about the principle. Did Parliament, a body in which the colonies had no elected voice, have the right to tax them for revenue at all?"
      },
      {
        "p": "The colonists answered with a distinction they would lean on for years. There were, they argued, two kinds of taxes. External taxes were duties on trade, collected at the ports, which they had long accepted as a fair tool for regulating commerce within the empire. Internal taxes were a different animal, a charge laid simply to raise money, and those, they held, only their own elected assemblies could impose on them. The Sugar Act sat uneasily on that line. It was external in form, a duty collected at the port, but internal in purpose, since its declared aim was pure revenue, which made it feel like an internal tax wearing the costume of an external one."
      },
      {
        "p": "Britain had an answer ready. The colonists said they sent no members to Parliament, and that was true. But under the British doctrine of virtual representation, it did not matter. Every member of Parliament, the argument went, represented the whole nation and all its subjects, not merely the few who had voted him in. By that logic the colonists were represented exactly as huge British cities like Manchester and Birmingham were, places that returned no member of their own and yet were held to be spoken for all the same. The colonists rejected this flatly. They wanted actual representation, members they themselves had elected, or no taxes at all. The two doctrines could not be reconciled, and the whole quarrel would turn on the gap between them."
      },
      {
        "p": "Out of that argument came a phrase that settled into words across a dozen colonies at once. In 1764 the Massachusetts lawyer James Otis Jr. published a pamphlet, *The Rights of the British Colonies Asserted and Proved*, one of the earliest and most influential statements of the colonial case. The idea it helped crystallize, that people could be taxed only by a legislature they had voted for, hardened over the next year into a slogan: no taxation without representation. It was less one man's coinage than a conviction settling into words across the colonies at the same time."
      },
      {
        "fig": "/war-img/rev-james-otis.jpg",
        "cap": "James Otis Jr., whose 1764 pamphlet helped turn a tax dispute into a constitutional argument.",
        "credit": "Portrait of James Otis Jr. · public domain"
      },
      {
        "p": "It is worth being clear about what the colonists were, and were not, asking for in 1764. Almost no one wanted to leave the empire. They were not yet Americans demanding independence. They were Britons demanding the rights of Britons, the same protections they believed any subject of the Crown was born to, the right not to be taxed except by their own consent. They thought they were defending the British constitution, not breaking with it."
      },
      {
        "p": "That was where the line sat at the close of 1764. The colonists had drawn a distinction, external taxes they would tolerate, internal taxes they would not, and Parliament had not yet truly tested it. The following year it would, with a tax aimed squarely at the internal side of the line, on the paper of everyday colonial life. It had a name, the Stamp Act, and it would blow the whole argument wide open."
      },
      {
        "pill": "/war-revolution/off-the-battlefield/stamp-act",
        "plabel": "The Stamp Act"
      }
    ],
    "meanwhile": {
      "region": "London",
      "title": "A new king, a new resolve",
      "body": "George III had taken the throne in 1760 determined to govern, not just reign. His ministers looked at a real war debt and a vast new empire and saw one problem they thought they had every right to fix: the colonies had grown used to running themselves, and that was going to stop."
    }
  }
}
