'use client'

// Fort Donelson — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const FORT_DONELSON_NARR: Record<string, Narr> = {
  'the-rivers': {
    eyebrow: 'Fort Donelson · The rivers into the South',
    title: 'The Rivers into the South',
    blocks: [
      { p: 'Two big rivers ran straight into the heart of the Confederacy, and the South had posted one smallish fort on each of them to keep the war out. In the first winter of the Civil War, the United States went looking for a back door into the South and found those two — the Tennessee and the Cumberland — lying in plain sight. They run roughly parallel through the Confederate heartland, only about 10 miles (16 km) apart where the South had planted its forts, and both of them point like arrows from the loyal North straight down into Tennessee and beyond. The war in the East was already a slogging, head-on affair, two armies grinding into each other across Virginia. Out West, somebody noticed that you didn’t have to grind. You could float.' },
      { p: 'That somebody, more than anyone, turned out to be a then-obscure brigadier general (a rank one rung below major general) named Ulysses S. Grant (North). He had a partner in the work: Flag Officer Andrew H. Foote (North), the naval equivalent of a general and the senior commander of a brand-new fleet of river gunboats (warships built to fight on rivers, not the open sea). And he had a green light from his superior, Maj. Gen. Henry W. Halleck (North), the cautious commander of the Department of Missouri (the Union’s military command zone for the western theater), who authorized a campaign against the twin river forts. The idea was simple and ruthless: drive gunboats and soldiers up those two rivers, smash the forts guarding them, and you split the Confederacy and cut its supply lines in half. And the thing that whole western line existed to defend, the thing the war was finally about, was slavery. The Confederacy had broken away to keep human beings as property; its generals had strung a defensive cordon (a ring of forts and troops) across Kentucky and Tennessee to protect that slaveholding heartland. The rivers strategy was a plan to crack that cordon open and start strangling the country built on slavery.' },
      { h: 'A fort that fell to boats alone', eyebrow: 'The western strategy' },
      { p: 'The first door came down fast. On February 6, 1862, ten days before Donelson, Foote\'s gunboats steamed up the Tennessee River and reduced Fort Henry more or less by themselves, his ironclads pounding the fort until it quit before Grant\'s foot soldiers could even close the ring around it. An **ironclad** is exactly what it sounds like, a gunboat plated in iron armor so cannonballs bounce off instead of punching through; in 1862 these were new and frightening machines, and at Fort Henry they looked unstoppable. The Confederate garrison (the body of troops assigned to hold a fort) was around 3,400 men, and most of them got out before the trap closed. About 2,500 of them simply marched the 10-odd miles overland to the next fort, Fort Donelson, on the Cumberland, and dug in there.' },
      { p: 'So Fort Henry\'s fall did two things at once. It threw open the Tennessee River to Union gunboats all the way down into Alabama, and it handed the lesson of the moment to both sides: out here, the boats win. Grant decided to do it again at the second door.' },
      { fig: '/war-img/donelson.png', cap: 'The siege of Fort Donelson on the Cumberland: Union lines ring the fort on the land side while Foote\'s gunboats press from the river, and the breakout road runs south toward Nashville.', credit: 'Stuff Happened map' },
      { h: 'A twelve-mile march and a treacherous thaw', eyebrow: 'The western strategy' },
      { p: 'Grant moved his force the roughly 12 miles (19 km) overland from Fort Henry to Fort Donelson on February 11–13, and his men were so sure of the warm spell that had run ahead of the battle that they threw away their overcoats on the march to lighten the load. It was a costly bit of optimism. On the way Foote took the gunboats the long way around by water; on February 12 the army ran into Confederate cavalry under Col. Nathan Bedford Forrest (South) in sharp little skirmishes, and on the 13th there was some light probing (small test attacks) at the fort\'s defenses.' },
      { p: 'Then the weather, which had been lying to everyone, told the truth. On the night of February 13–14 a severe snowstorm rolled in and dropped the temperature to 10–12°F (–12°C), with about 3 inches of snow on the ground and a lot of men no longer carrying the coats they\'d shed. Wounded soldiers left out on the field overnight simply froze where they lay. That is not a figure of speech and it is not a small detail. It is one of the documented horrors of Fort Donelson, and it had barely begun.' },
      { p: 'The boats win. Grant decided to do it again at the second door.', q: true },
      { p: 'At Fort Henry the gunboats had ended the fight by themselves. Grant was about to learn that the second fort had been paying attention.', i: true },
    ],
    meanwhile: { region: 'the Confederate West', title: 'A line drawn across two states', body: 'The man responsible for stopping all this was Gen. Albert Sidney Johnston (South), commander of the entire Confederate Western Department, and his line was a mile wide and an inch deep. It ran from Columbus, Kentucky, on the Mississippi, east to Bowling Green, Kentucky, anchored in the middle by the two river forts, Henry and Donelson. Johnston had roughly 12,000 men under Leonidas Polk (South) holding Columbus and about 14,000 under William J. Hardee (South) at Bowling Green, with the forts as the hinge between them. Johnston himself sat at Bowling Green, far from the fort about to be attacked. And here he made the mistake that doomed the men inside it: after Fort Henry fell, Johnston and his lieutenants privately judged Fort Donelson indefensible — they had decided the Union gunboats were all but unbeatable — and yet he poured some 12,000 more troops into the place anyway, instead of pulling the garrison out while the road was open. It was a half-measure with the worst of both outcomes: enough men sent in to be lost, not enough to win, and no decision to get them out in time. The trap that was about to close on Fort Donelson was partly one the Confederates built for themselves.' },
  },

  'the-gunboats': {
    eyebrow: 'Fort Donelson · The gunboats repulsed',
    title: 'The Gunboats Repulsed',
    blocks: [
      { p: 'On the afternoon of February 14, the gunboats came up the Cumberland to do to Fort Donelson exactly what they had done to Fort Henry, and the river fort was ready for them. This is the reversal at the heart of the whole battle: the same weapon that had won the first fort almost by itself got beaten back from the second one, and beaten back hard. Grant wasn\'t even there to see it — he was downriver in a meeting.' },
      { p: 'The thing the gunboats had to get past was the fort\'s **water batteries**, gun positions dug into the river bluff specifically to shoot at ships. Fort Donelson had two tiers of them stacked on the high west bank of the Cumberland, a lower battery down near the waterline and an upper battery above it, the heaviest gun among them a 10-inch Columbiad (a big smoothbore cannon) in the lower battery, with a rifled 64-pounder (a gun with a spiral-grooved barrel that spins the shot for more range and accuracy than a smoothbore) and a pair of 32-pounders up top. Sitting up on that bluff gave the Confederate gunners a brutal advantage: they could fire *down* onto the boats, plunging shot through the decks, while the river\'s strong downstream current and some flooding made it hard for the gunboats to hold position and aim back.' },
      { h: 'Closing to four hundred yards', eyebrow: 'February 14' },
      { p: 'Foote brought his whole flotilla up: four ironclads (the *St. Louis*, *Carondelet*, *Louisville*, and *Pittsburg*) and three **timberclads** behind them (older gunboats armored with thick wood instead of iron, the *Tyler*, *Conestoga*, and *Lexington*). The attack opened around 3:00 in the afternoon and lasted only about an hour and a half. Foote ran the same play that had worked at Fort Henry, closing right in to within about 400 yards (370 m) of the guns so his fire would tell.' },
      { fig: '/war-img/donelson-gunboats.jpg', cap: 'Foote\'s ironclads close on Fort Donelson\'s water batteries — the guns on the high bluff above the Cumberland poured plunging fire onto the decks below, sending the fleet downriver in less than two hours.', credit: 'Engraving, 1862 · public domain' },
      { p: 'This time it was a fatal mistake. Up close and below the batteries, his boats took the plunging fire full in the face. The numbers are almost comic if you forget there were men inside: the *St. Louis* was hit 59 times, the *Carondelet* 54 times, the *Louisville* 36 times, the *Pittsburg* 20 times. Two of the ironclads had their steering shot away, went unmanageable, and drifted helplessly downriver, and the rest of the flotilla pulled back after them. Foote himself was wounded, struck in the foot by wood splinters when a Confederate shot tore through the pilot house of his flagship *St. Louis* — a hurt he never fully recovered from. On the Union side, 8 sailors were killed and 44 wounded in that hour and a half. In the Confederate water batteries up on the bluff: not a single casualty.' },
      { p: 'That lopsided afternoon rewrote Grant\'s whole plan. Fort Henry had fallen to gunboats alone; Fort Donelson had just thrown the gunboats off the river. There would be no naval shortcut here. If the fort was coming down, the army was going to have to take it the slow, bloody way, on foot, from the land side.' },
      { p: 'The *St. Louis* hit 59 times, the *Carondelet* 54, the *Louisville* 36, the *Pittsburg* 20. In the batteries that did it: zero casualties.', q: true },
      { p: 'The fort had answered the one weapon everyone thought was unbeatable, and it had answered with a shrug.', i: true },
    ],
    meanwhile: { region: 'the trenches', title: 'Cold enough to kill the wounded', body: 'While the gunboats were getting wrecked on the river, the land siege was settling into the same cold that had arrived the night before. The temperature had crashed to 10–12°F (–12°C) with snow on the ground, and the men shivering in the lines on both sides were the lucky ones. The wounded out in the open between the armies, soldiers who couldn\'t crawl back to their own side, froze to death where they had fallen. The fight on the river had a winner and a loser by 4:30 in the afternoon. The cold didn\'t take sides, and it didn\'t stop at sundown.' },
  },

  'the-breakout': {
    eyebrow: 'Fort Donelson · The escape that wasn\'t',
    title: 'The Escape That Wasn\'t',
    blocks: [
      { p: 'By the night of February 14, the men running Fort Donelson had done the math and didn\'t like the answer. The gunboats had been beaten, yes, but Grant\'s army was thickening on the land side by the day, the ring was closing, and at a council of war (a meeting of commanders to decide what to do) around 11:00 that night the Confederate generals agreed the fort was "probably untenable" — impossible to hold. So they made a plan to punch their way out. And then, the next morning, they executed it almost perfectly, opened a clean road to safety, and threw it away. The story of February 15 is the story of an escape that was won and then surrendered before anyone surrendered.' },
      { p: 'The plan had three parts and three generals, which was already a problem. Brig. Gen. Gideon J. Pillow (South) would lead the main assault straight south to seize Wynn\'s Ferry Road, the escape route running toward Nashville; Brig. Gen. Simon Bolivar Buckner (South) would hold the left as the men funneled out; and the senior commander, Brig. Gen. John B. Floyd (South), would coordinate the whole thing. A **breakout** is exactly this, a trapped force attacking outward to tear a hole in the ring around it and march its army through the gap before the enemy can close it.' },
      { h: 'The road thrown open', eyebrow: 'February 15' },
      { p: 'It worked. Around 5 a.m., Forrest\'s (South) cavalry stirred up a diversionary skirmish to the north to draw attention, and around 7 a.m. Pillow threw his full assault into Brig. Gen. John A. McClernand\'s (North) division on the Union right — the southern end of the line, facing the fort. McClernand\'s men bent, then broke backward; by early afternoon the Confederates had shoved the Union right back roughly 1 to 2 miles. The thing the whole plan was for had happened. The Union right was rolled up — the entire flank shoved sideways and backward, the defensive line folding in on itself and collapsing — and with it gone, Wynn\'s Ferry Road lay open and the army\'s path to Nashville was clear. All they had to do now was walk out of it.' },
      { fig: '/war-img/donelson.png', cap: 'The ring around Fort Donelson: Pillow\'s breakout attack rolled the Union right and opened Wynn\'s Ferry Road south before Grant\'s counterattack slammed the trap shut again.', credit: 'Stuff Happened map' },
      { h: 'The order that gave it back', eyebrow: 'February 15' },
      { p: 'Instead, around 1:00 to 1:30 in the afternoon — after a morning of hard fighting, with the road to Nashville standing open in front of them — Pillow ordered the assault troops who had just bled to pry that road open to stop, turn around, and march back into the very trenches they had fought their way out of that morning. Out in the ranks, some of the men had been close enough to the open road to see it: daylight, the way home, no enemy across it. Then the order came down, and they marched away from it, back into the lines they had left at dawn.' },
      { p: 'Most historians call it one of the great command failures of the war, and it deserves to be treated as the genuine controversy it is. Pillow\'s stated reasoning was that his men needed to resupply and reorganize before setting out on the breakout march, and that the road would stay open long enough for them to do it. Floyd accepted the call. Buckner protested it on the spot and was overruled. Pillow himself never admitted any mistake; questioned about it afterward by Floyd, he said he was "conscious of the commission of no errors." Whether it was incompetence, a failure of nerve, or a real-time misjudgment about how long the road would hold, the men who knew best disagree, and the disagreement starts with Pillow insisting nothing went wrong at all. What is not in dispute is the result. The door the army had pried open swung shut while they stood in the trenches resting.' },
      { h: 'Grant comes back', eyebrow: 'February 15' },
      { p: 'Grant had not been on the field for any of this. He\'d been downriver meeting with the wounded Foote to sort out resupply for the battered fleet, and he\'d left no second-in-command, so his division commanders had spent the morning reacting on their own. When he rode back and saw his right broken and his officers shaken, he rode straight into action — and he read the situation in a single, sharp detail: the captured Confederate soldiers were carrying full knapsacks and haversacks, packed with rations for a march. Men loaded for a long journey aren\'t pressing a sustained attack, they\'re trying to leave. The enemy wasn\'t winning. The enemy was running. And whoever moved first now would win the day. (His words to his staff officer Col. J.D. Webster survive in several slightly different versions, all to the effect that the side that attacked first now would be victorious, and the enemy would have to hurry to get ahead of him.)' },
      { p: 'So he attacked first. He ordered counterattacks all along the line: McClernand to rally and retake the ground lost that morning, Brig. Gen. Lew Wallace (North) in the center to shift south and shore him up, and, on the left, Brig. Gen. C.F. Smith (North) to hit the Confederate earthworks (the dirt walls and trenches the defenders had dug) that the breakout had stripped of men. His instruction to Smith was blunt: "All has failed on our right — you must take Fort Donelson." Smith took him at his word, climbed onto his horse out front where his men could see him, and drove his division straight into the outer entrenchments held by the 30th Tennessee, capturing them by evening. By about 5:30 p.m. the Union had retaken most of the morning\'s lost ground, and the trap was back in place, tighter than before. The escape was no longer just thrown away. It was gone.' },
      { p: '"All has failed on our right — you must take Fort Donelson."', q: true },
      { p: 'The Confederates had spent the morning winning their way out, and the afternoon getting walled back in.', i: true },
    ],
    meanwhile: { region: 'the fort', title: 'An army that had just escaped, trapped again', body: 'For the ordinary Confederate soldier inside the perimeter, February 15 was the cruelest kind of day. By midday they had fought hard, paid in blood, and opened the way home. Then they were marched back into the same trenches, and by dark the Union line had not only re-formed but bitten off a chunk of their own outer earthworks on the left. The next morning\'s math, with Smith\'s men now lodged inside the outer defenses, looked like slaughter. Buckner would put it at a 75% casualty rate if the assault came. The men who had won their escape at dawn were, by nightfall, more trapped than when the day began.' },
  },

  'unconditional-surrender': {
    eyebrow: 'Fort Donelson · Unconditional surrender',
    title: 'Unconditional Surrender',
    blocks: [
      { p: 'The Confederate generals met one more time, late on the night of February 15, and this council had the air of a sinking ship. Smith\'s troops were dug into the outer works (the same earthen walls and trenches) on the left; Buckner (South) reckoned that if they attacked in the morning from that newly won position, the defenders could lose three of every four men. The options on the table were the grim short list of a beaten army: keep fighting, try another breakout, or surrender. What happened next turned the surrender of a fort into one of the strangest exits in the war, because the two men in charge decided the one thing they would not do was be there for it.' },
      { h: 'The generals who left', eyebrow: 'February 16' },
      { p: 'Floyd (South) went first, and he had a personal reason to run. Before the war he\'d been U.S. Secretary of War under President Buchanan, and he feared that if the North captured him he\'d be prosecuted for treason or corruption. So he handed command to Pillow and got out, taking the only available steamboat and his two Virginia infantry regiments with him, slipping away early on the morning of February 16. Pillow (South) — who twelve hours earlier had opened the road home and then ordered it closed — took the command Floyd passed him, and he didn\'t hold it long either. Reportedly fearing Northern reprisals just as much, he passed command down again, to Buckner, and chose a small boat and a dark crossing of the Cumberland over a handshake with Grant. Two generals, one after the other, took charge of a surrendering army for just long enough to hand it to the next man and disappear into the dark.' },
      { h: 'Forrest rides through the water', eyebrow: 'February 16' },
      { p: 'Not everyone was willing to surrender, and one man flatly refused. Col. Nathan Bedford Forrest (South), the cavalry commander, said as much out loud: "I did not come here to surrender my command." Instead of waiting for terms, he led around 700 of his cavalrymen out of the trap the hard way, through the icy, waist-deep backwater of Lick Creek (a flooded side channel beside the river), skirting the Union left flank in the cold and the dark. They rode out through water up to their waists, found no enemy anywhere on the way, and were gone. The road home had been right there all night.' },
      { p: 'That clean getaway is the quietly damning part. Forrest\'s escape is the proof of what the night cost the rest of the garrison: many more men could have walked out alongside him, if Pillow hadn\'t ordered the breakout back into the trenches the day before, and if Buckner hadn\'t since posted guards to stop further escape attempts. Most of the army was made to stay and surrender on a road that was still open.' },
      { p: 'The dashing ride is real, and so is the rest of the man. Before the war, Forrest ran one of the largest slave-trading businesses in Memphis (from 1854 to 1860 he sold thousands of enslaved people out of his slave yard there, one of the "big four" traders in the South\'s busiest market). After the war, in 1867, he became the first Grand Wizard of the Ku Klux Klan. The escape through Lick Creek is one image of him. It is not the whole one.', i: true },
      { h: 'An old friend asks for terms', eyebrow: 'February 16' },
      { p: 'That left Buckner, the ranking officer now by default, to do the job the other two had fled. He sent a note across to Grant asking for an armistice (a temporary cease-fire while they negotiated) and a meeting to discuss surrender terms. And here the war turned personal, because Buckner and Grant were old friends. They\'d been at West Point together in the 1840s and served side by side under Gen. Winfield Scott in the Mexican War (the 1846–48 U.S. war with Mexico, the conflict that made the reputations of half the men who would later run the Civil War), including a climb up the volcano Popocatépetl. More than that, Buckner had once rescued Grant: in 1854, when Grant had resigned from the army and ended up broke and stranded at the Astor House hotel in New York City, it was Buckner who vouched for him and covered his hotel bill until his money came through. Now the broke ex-soldier Buckner had bailed out was the general holding his army by the throat.' },
      { p: 'Grant did not let the friendship soften the terms by an inch:' },
      { p: '"No terms except an unconditional and immediate surrender can be accepted. I propose to move immediately upon your works."', q: true },
      { p: 'An **unconditional surrender** means exactly that, no negotiation, no concessions, no agreement to let the defenders march away with their weapons or their pride: give up everything, or be attacked at once. Buckner, who had every reason to expect generosity from an old friend, got none. He called the terms "ungenerous and unchivalrous," but he acknowledged the "overwhelming force" arrayed against him, made a bitter nod to "the brilliant success of the Confederate arms yesterday" (Pillow\'s morning that had won the escape and then lost it), and accepted. The initials lined up too well for the Northern press to resist: U.S. Grant became "Unconditional Surrender Grant," and the nickname stuck.' },
      { p: 'When the two men met at the Dover Tavern, the old friendship resurfaced. Grant offered Buckner the use of his own purse, knowing he was headed for a prison camp; accounts differ on whether Buckner took the money. Grant refused to stage any formal surrender ceremony, asking, in the words attributed to him, "We have the fort, the men, the guns. Why should we go through vain forms?" (The friendship outlasted the war by a long way: Buckner would serve as a pallbearer at Grant\'s funeral in 1885.)' },
      { fig: '/war-img/donelson-dover-hotel.jpg', cap: 'The Dover Hotel, where Buckner surrendered to Grant on February 16, 1862 — the building still stands in Dover, Tennessee.', credit: 'Dover Hotel, Fort Donelson · public domain' },
      { p: 'Two generals fled, one rode out through the ice, and the man left holding the bag was the old friend who had once paid Grant\'s hotel bill.', i: true },
      { h: 'What it bought', eyebrow: 'February 16' },
      { p: 'The scale of what he\'d just taken was staggering. Somewhere between roughly 12,000 and 13,500 Confederate soldiers surrendered at Fort Donelson (sources run as high as 15,000; the most precisely sourced count is about 12,400 captured or missing), along with some 20,000 small arms (rifles and pistols), 48 field guns, 17 heavy guns, and around 3,000 horses. It was the largest mass surrender on the North American continent up to that point in the war. The victory was not free: the North paid for it with roughly 2,700 casualties of its own, about 507 men killed and another 1,976 wounded, many of them on McClernand\'s broken right and in Smith\'s charge against the earthworks.' },
      { p: 'And it broke the South\'s whole western position in days. Johnston\'s (South) Columbus–Bowling Green line had hinged on these forts, and with the hinge gone the line simply collapsed. Nashville — the capital of Tennessee, and the South\'s second-largest industrial city, a rail hub and a major source of iron and munitions — was abandoned almost at once and formally surrendered on February 25, the first Confederate state capital to fall in the war. Columbus was given up by early March, and the entire western cordon was gone, the rivers now open highways carrying Union armies deep into the South. Out of it all rose Grant, lifted from obscurity to national fame in a week, promoted to major general of volunteers and second in seniority in the West only to Halleck. The North had been starving for a real victory, and Fort Donelson, the first major Union win of the war, finally gave it one.' },
      { p: '"No terms except an unconditional and immediate surrender can be accepted."', q: true },
      { p: 'The South lost an army and a capital. The North, at long last, got a winner.', i: true },
    ],
    meanwhile: { region: 'the North', title: 'A country gets its first good news', body: 'For the North, Fort Donelson landed like the first warm day after a long winter. The Union had been short on victories and shorter on heroes, and here, suddenly, was both: a fort cracked open, an enemy army marched off into captivity, and a plain-spoken general whose own initials seemed to spell out his terms. Grant\'s name ran in every Northern newspaper. Story had it he\'d been seen chewing a cigar during the fight, and a grateful public buried him in boxes of them, after which, the accounts say, he became a regular cigar smoker for life. The two men who had thrown the escape away did not fare so well: within weeks Jefferson Davis would strip both of Confederate command — Floyd dismissed from the army outright, Pillow suspended for what the Confederacy itself called grave errors of judgment. History rendered its verdict on that morning quickly, and it agreed with Buckner.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={FORT_DONELSON_NARR} id={id} slug="fort-donelson" battleName="Fort Donelson" theatreId="west" theatreHref="/war-civil-war/western" battleId="w-donelson" accent="#1d4ed8" />
}
