// GENERATED by scripts/_build-rev-phases.mjs from audits/war-pipeline/rev-<phase>-final.md.
// Do NOT hand-edit — edit the gated -final.md and re-run the build script.
// The American Revolution phase-chapter narratives, consumed by the dynamic
// [phase] route through the shared <BattleSectionReader>.

import type { Narr } from '@/components/mode/battle-reader'

export const PHASE_NARR: Record<string, Narr> = {}
