'use client'

// The Battle of Cowpens (January 17, 1781), battle sections · American
// Revolution (southern campaign). Morgan's masterpiece: the textbook sin of
// dividing a weaker army, the three-line defense in depth that scripted a
// militia's flight as bait, and the double envelopment that destroyed Tarleton's
// corps in about an hour. The page's meaning-beat is the Camden inversion: five
// months earlier a general demanded the impossible of militia and lost an army;
// Morgan asked them for two volleys and got everything. Produced through the war
// content pipeline (audits/war-content-pipeline.md): fact pack → author → critic
// gates (fact-check + storytelling + newcomer-clarity + framing, parallel) →
// reconcile → revise. Data only; rendered by the shared <BattleSectionReader>.
// House voice: no em-dashes outside verbatim quotes; side-tags combatants only,
// once on first mention per section. HANDLE-WITH-CARE framings per the fact pack:
// the 499 lashes always "by his own telling" (no British record); the
// swamp/retreat reasoning quoted as Morgan's later self-justification via Johnson
// 1822, with Johnson's own hedge traveling; Thomas Young's campfire lines framed
// as a 62-years-later memoir ("Young remembered"); the "Mark the epaulette men"
// line as the SKIRMISHERS' OWN cry, never an order; the Howard "do men who march
// like that" and Washington "coming on like a mob" lines as 19th-c recollection
// ("Howard remembered," "word came back"); the misheard-order envelopment told
// honestly as half plan, half improvisation; the "American Cannae" only as
// historians' label; the "Tarleton's quarter" cries real but NO revenge massacre
// (Morgan's report + the prisoner arithmetic — the discipline is the meaning);
// the Washington–Tarleton clash held to "believed to be Tarleton" (Howard's
// phrase), the rescuing bugler unnamed, no Cowpens hand-wound asserted; American
// strength always a range (800 his report / ~1,900 Babits); "Bloody Ban" never
// in a period mouth. The Race to the Dan and Guilford Courthouse are SET UP, not
// told (next page). No invented images; no map blocks (locators not authored —
// the generated maps cover the geography).
// Sources: audits/war-pipeline/rev-cowpens-factpack.md.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const COWPENS_NARR: Record<string, Narr> = {
  'the-split': {
    eyebrow: 'Cowpens · The setup',
    title: 'The textbook sin',
    blocks: [
      { p: "By the end of 1780 the American cause in the South had lost two whole armies in eight months. Charleston fell in May, and more than five thousand men surrendered with it, the largest American surrender of the war. Three months later, on August 16, a second army was destroyed at Camden, and the way it died would shape everything that happened at the Cowpens. So the Southern Department was on its third army when Congress, for once, let George Washington choose the man to command it." },
      { p: "He chose Major General Nathanael Greene (American), who reached Charlotte, North Carolina, on December 2 and took command the next day. On paper he had perhaps 2,300 men; barely 1,500 or 1,600 were fit to fight. Cornwallis (British), the British general who held the conquered South, had more troops, better fed and better supplied, and Greene was in no condition to fight him. So Greene did the thing every military textbook forbids: in the middle of December he divided his inferior army in the face of a superior enemy." },
      { p: "The logic was better than it looked. A divided army could eat, foraging two districts instead of one stripped bare. It threatened the British posts from two directions at once. And it forced Cornwallis to divide too, because if he massed against one American wing, the other was loose behind him. By the orders of December 16, Greene detached Brigadier General Daniel Morgan (American) with the light troops, about 600 men: roughly 300 Maryland and Delaware Continentals (the full-time paid regulars of the Continental Army) under Lieutenant Colonel John Eager Howard (American), some Virginia riflemen, and about 80 light dragoons (mounted soldiers trained to fight from horseback) under Lieutenant Colonel William Washington (American). Morgan marched west across the Catawba and the Broad to operate toward the British post of Ninety Six, while Greene took the rest to a camp of repose at Cheraw. In the correspondence Morgan's detachment was called the \"flying army.\"" },
      { p: "Morgan was an unlikely master of war. A New Jersey-born Virginia frontier teamster, \"the Old Wagoner,\" he had driven wagons on Braddock's disastrous 1755 campaign and carried a lifelong grudge against the British Army. By his own often-told tale he had once been sentenced to 500 lashes for striking a British officer, and the drummer miscounted at 499, so Britain still owed him one; he would show the scars, though no British record of the sentence survives, and the story travels as Morgan's own. He had led riflemen to Quebec and opened both battles at Saratoga, resigned in a fury at being passed over for promotion, and come back after Camden as a new brigadier. Now he camped his flying army on the Pacolet River from Christmas Day, and Brigadier General Andrew Pickens's (American) South Carolina militia (part-time citizen soldiers) rode in to join him, with more arriving through January." },
      { p: "Cornwallis answered exactly as Greene had bet he would. From his camp at Winnsboro he sent his best subordinate to destroy Morgan: Lieutenant Colonel Banastre Tarleton (British), commanding the British Legion of Loyalist cavalry and infantry, the most feared man in the southern war. \"Tarleton's quarter\" had become backcountry slang for no quarter at all after the Waxhaws the previous May, where his Legion cut down Virginia Continentals as they tried to surrender; in the Carolinas they called him the Butcher. With about 1,100 to 1,150 men he was to push Morgan away from Ninety Six and run him down, while Cornwallis moved to cut off Morgan's retreat to the northeast." },
      { p: "Tarleton got firm word of Morgan's position on January 12 and pressed hard across rivers swollen with winter rain. He moved so fast, the story goes, that his men ate the breakfast Morgan's troops abandoned on the Pacolet. Morgan fell back, and by the evening of January 16 he was at a place called Hannah's Cowpens, a frontier cattle-grazing ground in the upcountry near the North Carolina line, with the flooded Broad River about six miles at his back and Tarleton camped a few hours behind him. Tarleton would rouse his men at two in the morning for a five-hour night march; by the modern reconstruction his troops reached the field after less than four hours' sleep in 48 hours, and out of food." },
      { p: "To every conventional eye, the position Morgan had chosen was a trap. The Cowpens was open pastureland, a long gentle rise, scattered hardwoods kept clear of underbrush by grazing cattle, no swamp to anchor a flank, and the flooded Broad behind cutting off any line of retreat. Wings in the air, cavalry country, nowhere to run. That, Morgan said afterward, was exactly the point. The justification comes through William Johnson's 1822 biography of Greene, and Johnson hedged whether \"these were really Morgan's reasons,\" so it reads as Morgan's later self-justification rather than a speech on the field." },
      { p: "I would not have had a swamp in the view of my militia on any consideration; they would have made for it, and nothing could have detained them from it... As to retreat, it was the very thing I wished to cut off all hope of... When men are forced to fight, they will sell their lives dearly... Had I crossed the river, one half of the militia would immediately have abandoned me.", q: true },
      { p: "To understand that, you have to understand Camden, because Camden was the lesson the whole battle answers. There, on August 16, the American general Horatio Gates had put some 2,500 Virginia and North Carolina militia, many of whom had never been in a battle, in the line opposite British regulars. When the redcoats came on with the bayonet, nearly the whole militia wing threw down loaded muskets and ran, most without firing a shot. The Continentals' flank was bared, the army's second-in-command went down, and the army simply ceased to exist. The lesson most generals drew was blunt: militia were worthless in open battle." },
      { p: "Morgan drew the opposite lesson. The failure at Camden, he decided, was the ask, not the men. Militia could not stand a bayonet charge, but they could shoot, and most of his were backcountry riflemen with personal scores to settle. So he resolved to ask them for exactly what they could give, two volleys at killing range, and to give them permission, in advance, to leave, with a rally point named behind the hill. The flight that at Camden had been a rout would become, at the Cowpens, the working part of a machine." },
      { p: "Militia companies rode in all that evening, and the camp butchered cattle and roasted beef while Morgan went from fire to fire. One of the men around those fires was Thomas Young, a seventeen-year-old militia dragoon, who set down what he remembered sixty-two years later: Morgan helping men fix their swords, joking with them about their sweethearts, promising that \"the old wagoner would crack his whip over Ben in the morning, as sure as they lived.\" Young remembered the rest of it too." },
      { p: "Just hold up your heads, boys, three fires, and you are free, and then when you return to your homes, how the old folks will bless you, and the girls kiss you, for your gallant conduct!", q: true },
    ],
    meanwhile: { region: 'Camden, South Carolina', title: 'The lesson Morgan answered', body: "Cowpens is best understood as the inversion of Camden. On August 16, 1780, Gates lined up raw militia against British regulars and demanded that they stand a bayonet charge; they ran without firing, and an entire army was destroyed. Most generals concluded that militia could not fight. Morgan concluded that the problem was the order, not the men. Camden asked frightened amateurs to do the one thing they could not do; Cowpens would ask them to do the one thing they could, fire two aimed volleys, and then go. Five months and ninety miles apart, the same kind of men produced opposite results, because one general understood what he had." },
  },

  'the-battle': {
    eyebrow: 'Cowpens · The masterpiece',
    title: 'Three lines, and a scripted retreat',
    blocks: [
      { p: "Morgan's plan was the battle. He arranged his force (American) in three lines up the gentle rise, and the genius of it was that he asked each line only for what it could actually do. He spent the night and the dawn making sure every line knew what the others would do, so that when the front lines fell back, nobody behind them would panic. That briefing was as much the design as the geometry." },
      { p: "The first line was a skirmish line (a loose screen of individual shooters placed ahead of the main body to harass the advancing enemy and fall back before close contact): about 150 picked Georgia and North Carolina riflemen in loose order among the trees, told to fire at about fifty yards and then fall back. By everyone's understanding they aimed at the officers. Johnson's 1822 account has the men themselves crying \"Mark the epaulette men,\" the epaulets being the shoulder ornaments that marked an officer; it was the skirmishers' own exclamation, not an order anyone gave." },
      { p: "The second line, about 150 yards back, was the main body of militia under Pickens. This was the heart of the design. They were asked for two deliberate volleys at fifty yards, and then licensed in advance to retire, around the American left and behind the hill, to reform as a reserve. Every man knew the plan, and knew the cavalry would cover them as they went. The retreat was not a contingency. It was scripted." },
      { p: "The third line, on the crown of the rise another 150 yards behind, was Howard's Continentals and his veteran Virginia and Georgia companies, the steady regulars who would take the charge of an enemy already bled and disordered by the first two lines. And behind a second rise to the rear, invisible from the front and safe from the British guns, Morgan hid William Washington's cavalry, close enough to strike the instant they were needed." },
      { p: "Tarleton's van came up the Green River Road at first light and he attacked straight off the march, with no rest, no breakfast, and almost no reconnaissance: light infantry on his right, Legion infantry in the center, the 7th Royal Fusiliers on the left, his two light 3-pounder \"grasshopper\" guns opening, fifty-odd dragoons of the 17th Light Dragoons on the flanks, and the 71st Highlanders and the Legion cavalry held in reserve." },
      { p: "The first two lines worked exactly as written. The skirmishers bled the first British dragoon probe and fell back into the militia. The British line came on cheering and ran into the militia's two volleys, aimed low, officer-heavy, devastating at fifty yards, and then Pickens's men shouldered off around the left and headed for the rally point, just as planned." },
      { p: "Here came the first danger. Tarleton, certain he was watching the same rout he had seen at every other battle, threw the 17th Light Dragoons after the \"fleeing\" militia, and sabers began falling on the hindmost. (Young was slashed in this melee; his memoir's list of scars is real.) But Washington's hidden cavalry burst over the rise and broke the dragoons off the militia's backs, and the militia made the rally point behind the hill. The bait had been taken, and the man who took it had just lost his light dragoons to a counterstroke he never saw coming." },
      { p: "Now came the famous accident that closed the trap. Tarleton committed the 71st Highlanders around the American right, and Howard ordered his right-flank company to refuse, to bend back, to face them. In the noise the order was heard as a command to withdraw, and company by company the whole Continental line faced about and marched to the rear, in step, muskets shouldered. Morgan rode up demanding whether they were beaten; Howard, as he remembered it, pointed at the unbroken ranks." },
      { p: "Do men who march like that look as though they were beaten?", q: true },
      { p: "Morgan accepted it on the instant, galloped ahead, and staked out a new line for the Continentals to halt and turn on. The double envelopment that follows was therefore half plan and half improvisation: the militia's return was scripted, but the Continental withdrawal was an accident that Morgan and Howard converted into a weapon in the space of a minute." },
      { p: "Because the British, seeing the Continentals fall back, were now certain the day was won. They broke ranks and surged uphill after them in a disordered mass. Word came back from Washington to the rear line, in the phrase the American accounts preserved: \"They are coming on like a mob. Give them a fire and I will charge them.\" At Howard's command the Continentals faced about and fired a volley into the oncoming British at about thirty yards, then went in with the bayonet. Washington's cavalry struck the British right and rear. Pickens's reformed militia came back around onto the 71st on the British left. Three sides closed at once. Historians have called it a small-scale Cannae, after Hannibal's classic double envelopment (an attack that closes in from two sides simultaneously to encircle and destroy), though that is the historians' label, not anyone's judgment on the day." },
      { p: "The British force came apart almost at once. Two days without food or sleep, their officers falling, suddenly surrounded, much of the infantry simply quit where it stood; the modern reading is combat shock. Men dropped to the ground or threw down their arms wholesale. The artillerymen alone fought to the last around their two grasshopper guns, and both guns were taken. The 71st held longest before surrendering. And Tarleton's last card, the Legion cavalry he had kept in reserve, refused his order to charge back in and rode off the field. In under an hour, his command had ceased to exist." },
    ],
    meanwhile: { region: 'The Green River Road', title: 'Why exhaustion mattered', body: "A great plan still needs an enemy who walks into it, and Tarleton did. By the modern reconstruction his men reached the Cowpens having slept less than four hours in 48 and gone hungry, after a five-hour march that began at two in the morning. Tarleton then attacked straight off that march, without resting his men or scouting the ground, because attacking straight off the march was how he had always won. Against a worse general it might have worked again. Against Morgan's three lines it meant that exhausted, disordered men chasing what they thought was a beaten enemy ran uphill into fresh regulars and a hidden reserve. The plan and the exhaustion finished the corps together." },
  },

  'the-reckoning': {
    eyebrow: 'Cowpens · The meaning',
    title: 'The quarter that was the answer',
    blocks: [
      { p: "As the British line collapsed, men in the American ranks began shouting \"Tarleton's quarter,\" the Waxhaws coming home, and for a moment the battle could have ended as a massacre, payback in kind for the men cut down trying to surrender the previous spring. It did not. American officers, Howard most prominently, physically stepped in to protect surrendering men, and quarter was given. Morgan wrote two days later, in his report to Greene, a line that the arithmetic of the battle bears out." },
      { p: "Not a man was killed, wounded or even insulted after he surrendered.", q: true },
      { p: "The cries were real and are well attested. The restraint is just as well attested: against roughly 600 to 830 prisoners taken alive, Morgan's army killed about 100 British, the proportions of a battle that ended in surrender, not slaughter. The man who had made the southern war a byword for no quarter had his own command spared at the moment it was helpless. The documented story is the discipline, not the bloodlust." },
      { p: "Tarleton himself got away with a remnant: a few dozen riders still with him, and the couple of hundred Legion cavalry who had already refused his last order and quit the field. As the fight broke up, Washington, riding ahead of his own troopers, closed with a knot of British officers, one of them believed to be Tarleton (Howard's own phrase, not a confident identification). In the family of accounts that grew up around the moment, Washington's saber broke at the hilt, a British cut was parried by his sergeant-major, and a teenage bugler too small to wield a sword shot another officer with a pistol and saved Washington's life; the officer taken for Tarleton fired a shot that wounded Washington's horse and got away. Tarleton's own memoir never mentions any of it, and his first documented wound came later, at Guilford Courthouse, so the duel stays a clause with \"believed to be Tarleton\" doing the work. Washington pursued about sixteen miles, lost his quarry when a local planter pressed as a guide led him astray, and gathered up roughly a hundred stragglers instead." },
      { p: "The numbers tell the rest. Tarleton's force of 1,050 to 1,150 men was roughly 80 to 90 percent destroyed or captured in about an hour: somewhere around 100 to 110 killed, 200-odd wounded, and 500 to 630 taken unwounded, along with both grasshopper guns, the colors of the 7th Fusiliers, sixty baggage wagons, and the Legion's baggage and music. American losses were light by any count, Morgan's report giving about 12 killed and 60 wounded, the modern reconstruction nearer 150 in all. As for Morgan's own strength, he reported that he \"fought only 800 men, two thirds of which were Militia,\" while the modern reconstruction runs near 1,900; the truth is somewhere in between, because his report undercounted the militia who had been arriving all night, and the contest over the number is itself part of the story." },
      { p: "Morgan did not wait for Cornwallis to react. He crossed the Broad the same afternoon and was camped beyond it within eight hours of the battle's end; Pickens took the unwounded prisoners north, out of Cornwallis's reach. The Old Wagoner had hit Cornwallis where it hurt most. The men he had destroyed were the light troops, the British Legion, the light infantry, the fast quarter of Cornwallis's field force and the quarter that made the rest of it fast. He could not screen, pursue, or move as he had the day before. Within days Cornwallis burned his own baggage train to turn his whole army into light infantry and set off after Greene, in what became a desperate chase northward. That chase, and the battle it ended in, belong to the next page." },
      { p: "John Marshall, who lived through the Revolution and later wrote its history, gave the battle its standing verdict: \"Seldom has a battle, in which greater numbers were not engaged, been so important in its consequences as that of Cowpens.\" The historian John Buchanan went further about the man, calling Morgan perhaps \"the only general in the American Revolution, on either side, to produce a significant original tactical thought.\" Greene paid the design the highest compliment a soldier can pay: he copied it. Eight weeks later, at Guilford Courthouse, he drew up his army in the same three lines, with the same two-volley order for the militia, and fought Cornwallis on Morgan's plan." },
      { pill: '/war-revolution/southern-turn', plabel: 'The southern war that followed: Greene, the chase, and the road to Yorktown' },
      { p: "Cowpens was Morgan's masterpiece, and it was also the last battle he ever fought. The sciatica and rheumatism that the winter campaign had aggravated finished his health within weeks; he guided the first leg of the retreat and then left the army on February 10, days before it reached the river it was racing for. Congress voted him a gold medal, with silver for Howard and Washington, though the medal would not reach him for nearly a decade. He had asked his militia for two volleys instead of miracles, scripted their flight as bait, and folded an army onto an anvil, and a battle that lasted under an hour has been studied ever since as a model of how to win." },
    ],
    meanwhile: { region: 'Guilford Courthouse, North Carolina', title: 'The battle that copied the battle', body: "The surest measure of Cowpens is that the best general in the southern war studied it and used it. Eight weeks after Morgan's victory, Nathanael Greene drew up his army at Guilford Courthouse in three lines, with his militia given the same two-volley order Morgan had given his, then licensed to fall back. It is the clearest sign that Cowpens was not a lucky day but a reproducible idea, a way of using citizen soldiers that worked because it asked them for what they could give. What happened when Greene tried it, and where the long chase that began at the Cowpens finally led, is the next page's story." },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={COWPENS_NARR}
    id={id}
    slug="cowpens"
    battleName="Cowpens"
    date="January 17, 1781"
    theatreId="rev-battles"
    battleId="rev-cowpens"
    theatreHref="/war-revolution/battles"
    accent="var(--rev-battles)"
    endHref="/war-revolution?theatre=rev-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
