'use client'

// Gaines' Mill — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

export const GAINES_MILL_NARR: Record<string, Narr> = {
  'lee-attacks': {
    eyebrow: 'Gaines’ Mill · Lee Takes the Offensive',
    title: 'Lee Takes the Offensive',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -78.3, lonMax: -76.5, latMin: 37, latMax: 38.2 },
        states: [
          { name: 'Virginia', tone: 'focus', label: 'VIRGINIA', labelLon: -77.8, labelLat: 38.1 },
          { name: 'Maryland' }, { name: 'West Virginia' }, { name: 'North Carolina' }, { name: 'Pennsylvania' },
        ],
        dots: [
          { name: 'Gaines\' Mill', date: 'Jun 27, 1862', lat: 37.57, lon: -77.29, heavy: true, anchor: 'start' },
          { name: 'Richmond', lat: 37.5407, lon: -77.436, color: '#8a8175', anchor: 'end' },
        ],
      } },





      { p: 'In the last days of June 1862, the Confederate capital could hear the United States Army coming. Major General George B. McClellan, commanding the Army of the Potomac, had spent the spring creeping up the Virginia Peninsula (the long neck of land between the James and York Rivers, southeast of Richmond), and by late May his men were close enough to see the church spires of Richmond, roughly 5 to 6 miles (8 to 10 km) off. He had well over 100,000 men; some counts put the army at 105,000 or more. The Confederacy had a capital about to fall.' },
      { fig: '/war-img/gaines-mill-sevendays.png', cap: 'The Seven Days: Lee strikes Porter’s corps isolated north of the Chickahominy while a thin line screens Richmond', credit: 'Stuff Happened map' },
      { p: 'The man who decided not to let it fall had only just taken the job. At the Battle of Seven Pines (also called Fair Oaks) on May 31 and June 1, the Confederate commander, General Joseph E. Johnston (South), was badly wounded, and President Jefferson Davis handed the army to General Robert E. Lee. Lee renamed it the Army of Northern Virginia and did the math: he could not win a siege against a bigger, better-supplied army parked outside his capital. Sitting still meant losing slowly. So he chose the opposite of sitting still. Within weeks of taking command, he attacked.' },
      { p: 'And the thing he was fighting to save was not just Richmond’s warehouses or its railroads. The fight for Richmond was, at bottom, a fight over a slaveholding republic: a country of roughly 4 million enslaved people whose forced labor was the South’s economy, and whose continued bondage was the reason the Confederate states had walked out of the Union in the first place. Take Richmond in the summer of 1862 and the rebellion might end before it became something larger. Save it, and slavery’s republic got to keep fighting. That was the prize on the table outside the city. Lee had been a general for less than a month, and was about to throw the largest army the South had ever fielded straight at the larger army in front of it to hold onto it.' },
      { h: 'The Seven Days | Mechanicsville and the plan to crush Porter', eyebrow: 'June 26' },
      { p: 'On June 26, Lee opened what history would call the Seven Days Battles, a week of near-continuous fighting from June 25 to July 1, with an assault at Beaver Dam Creek, near the village of Mechanicsville, just northeast of Richmond. It did not go well. The division of Major General A.P. Hill (South) charged across the creek and was shot to pieces for no ground gained, somewhere around 1,000 to 1,500 men down. As a tactic, Mechanicsville was a failure.' },
      { p: 'As psychology, it worked, on the wrong man. McClellan, watching the Confederates suddenly turn aggressive, began that very day to plan a “change of base”: army slang for picking up his whole supply line and shifting it somewhere safer, in his case from the York River side over to the James River to the south, where U.S. Navy gunboats could cover him. The man with the bigger army started planning his retreat the day the smaller army attacked him.' },
      { p: 'That plan hardened fast. In the pre-dawn hours of June 27, before a single shot was fired at Gaines’ Mill, McClellan had already decided to fall back to the James. He sent out orders to start the army’s supply trains south, and he gave Porter a specific, telling job: hold the north bank as a rearguard, then bring his corps back across the river over the Grapevine Bridge once the Confederate attack developed. Porter was not being asked to win the coming battle. He was being asked to buy time for a retreat his commander had already chosen. The fight at Gaines’ Mill, when it came, did not break McClellan’s nerve and trigger his withdrawal: the withdrawal was the plan, and the battle was the price of covering it.' },
      { p: 'Lee’s actual plan was sharper than Mechanicsville made it look. McClellan’s army was split awkwardly by the Chickahominy River, a slow, swampy stream that wandered east of Richmond. Most of McClellan’s force sat south of the river; one piece sat exposed on the north bank, his Fifth Corps (written “V Corps,” numbered units being just how the army named the big pieces of itself) under Brigadier General Fitz John Porter (North), a steady career officer McClellan trusted with his most vulnerable flank. (A corps was the army’s largest building block, on the order of 20,000 to 35,000 men.) Lee meant to leave only a thin screen of troops south of the river, under Major General John Magruder (South), who had already bluffed McClellan once on the Peninsula by marching the same men in circles to look like more, to fool McClellan’s main body, then throw the bulk of his army across the Chickahominy and destroy Porter’s isolated corps before McClellan figured out that the force in front of his capital was mostly theater. Crush Porter, threaten McClellan’s supply line, and the whole invasion might unravel.' },
      { p: 'The plan had one moving part that refused to move on schedule. To turn Porter’s right flank (the exposed northern end of his line, the side you hit to roll a position up from its edge) Lee was counting on Major General Thomas J. “Stonewall” Jackson, marching in from the Shenandoah Valley to the west, a long farming corridor about 100 miles (160 km) west of Richmond where Jackson had spent the spring running circles around Union armies. Jackson was the most feared marcher in either army. And he was late. He had left the day before reportedly six hours behind schedule, his men worn down from a brutal Valley campaign, slowed by burned bridges, mud, enemy skirmishers, and a supply train that kept failing. His tardiness was already bending Lee’s plan out of shape before Gaines’ Mill even began.' },
      { pill: '/war-civil-war/eastern/first-winchester', plabel: 'First Winchester: Jackson’s Valley campaign, the spring of running circles' },
    ],
    meanwhile: { region: 'Washington', title: 'McClellan sees an army that isn’t there', body: 'McClellan’s caution was not random. It was fed. His intelligence came largely from Allan Pinkerton’s detective agency, and Pinkerton’s estimates were wildly, catastrophically wrong: McClellan believed Lee commanded something like 180,000 to 200,000 men. Lee actually had about 92,000, possibly less than half what McClellan thought he faced. So the general with the bigger army spent the entire campaign certain he was outnumbered, and acted accordingly: defending, hedging, planning his retreat, feeding his subordinate Porter only a trickle of help. The phantom army in McClellan’s head shaped Gaines’ Mill as much as any real soldier on the field.' },
  },

  'boatswains-swamp': {
    eyebrow: 'Gaines’ Mill · The Line at Boatswain’s Swamp',
    title: 'The Line at Boatswain’s Swamp',
    blocks: [
      { p: 'After the bruising at Beaver Dam Creek, Brigadier General Fitz John Porter (North) pulled his V Corps back to ground he could actually defend, and he chose it well. His line ran behind Boatswain’s Swamp (also called Boatswain’s Creek), a boggy ravine that curved in a long semicircle, roughly 1.5 to 2 miles (2.5 to 3 km) end to end, around the plateau where a farmhouse called the Watt House stood, a few miles into the Virginia Peninsula northeast of Richmond. Any Confederate who wanted Porter had to cross open ground, slither down into the muck of the swamp, and then climb a steep hillside, about 50 feet (15 m) of rise, straight into massed gunfire.' },
      { fig: '/war-img/gaines-mill.png', cap: 'Porter’s tiered line behind Boatswain’s Swamp, assaulted all afternoon', credit: 'Stuff Happened map' },
      { p: 'And the gunfire was massed. Porter stacked his defense in three tiers: a first line down at the creek bottom with sharpshooters (expert marksmen with long-range rifles) firing from behind felled trees, a second line halfway up the slope, and a third line of rifle pits along the plateau’s crest. On top of the plateau he arrayed 96 cannon, with still more artillery batteries (groups of cannon) firing in support from across the Chickahominy to the south. Morell’s division held his southern (left) flank, on Turkey Hill; Sykes’s division held the northern (right) flank; McCall’s division waited in reserve along the crest. It was, in short, a wall, and Robert E. Lee was about to run his army into it.' },
      { p: 'Lee did not know the wall was there. Boatswain’s Swamp did not appear on Confederate maps at all. Lee’s whole scheme assumed his troops would come around and hit Porter’s flank; instead, because the swamp pushed Porter’s line out farther than anyone on the Confederate side realized, his men kept marching straight into the front of a fortified position that, on paper, should not have existed.' },
      { h: 'June 27 | Hours of charging uphill into the guns', eyebrow: 'The afternoon' },
      { p: 'What happened next was Lee’s army losing the same battle three different ways, an hour at a time, because every division went in alone instead of all of them landing together. First the plan, then the momentum, then the men who carried it.' },
      { p: 'Around noon, the division of Major General Daniel Harvey “D.H.” Hill (South), no relation to A.P. Hill, reached the crossroads of Old Cold Harbor to the north and went looking for the open end of Porter’s line, the flank Lee’s maps promised him. It was not there. Instead of curling around Porter’s edge, D.H. Hill’s men ran straight into the solid front of his line, the first hard evidence that the map was wrong, that Boatswain’s Swamp had pushed the Union position somewhere no Confederate chart had it. From that moment, every assault Lee threw forward was aimed at a wall nobody on his side had known was there.' },
      { p: 'Around 2:30 p.m., Major General A.P. Hill (South), knowing by now the ground was worse than planned, sent his roughly 12,000-man division (grandly nicknamed the Light Division, A.P. Hill’s own name for it: “light” meaning fast, not small; at 12,000 men it was anything but) straight at Boatswain’s Swamp in the first major assault of the day, rather than wait for the rest of the army to come up alongside. His brigades crossed the open ground, went down into the swamp, started up the hill, and were torn apart. In about two hours, A.P. Hill’s division lost more than 2,000 men and gained essentially nothing, and bought Lee nothing either, because no one was attacking with him.' },
      { p: 'Around 3:30 p.m., the division of Major General Richard S. Ewell (South) fed into the same fight, three brigades in ferocious, doomed charges. Ewell had his horse shot out from under him and kept directing the fight on foot, walking among his own soldiers as they died around him in rows, for ground they could not hold. A Union soldier later described the volume of fire by saying the air “was too full of lead for standing room.” The picture was accurate: men were charging uphill into a hailstorm, one division at a time, and dying for nothing each separate division could keep.' },
      { p: 'Porter felt the pressure mounting. Around 5 p.m. he wired McClellan that he was “pressed hard, very hard.” McClellan, directing the whole battle by telegraph from his headquarters south of the river, never once appeared on the field in person. He finally moved help across. A full division under Major General Henry Slocum (North), on loan from the VI Corps, crossed the Chickahominy and fed its brigades straight into Porter’s line, where it was chewed up almost as badly as the men it came to save. Behind Slocum, McClellan also ordered two brigades from the II Corps under Major General Edwin Sumner (North), the Irish Brigade and one other, but they had a long way to come and arrived roughly three hours later, effectively during the final collapse, far too late to matter.' },
      { p: 'The one blow that might have ended it early never came. Thomas J. “Stonewall” Jackson finally reached Old Cold Harbor and found, as one officer put it, the Yankees in line facing him rather than the open flank Lee had promised him. He had been led down the wrong road, costing an hour-long countermarch (turning the whole column around to retrace its steps) and then dogged by burned bridges, roadblocks, and sharpshooters. Then, through a tangle of miscommunication, he sat and waited for orders while the battle roared a short distance away and did nothing. His Confederate artillery chief, Colonel Edward Porter Alexander (South), said it flatly after the war: “Had Jackson attacked when he first arrived, or during A.P. Hill’s attack, we would have had an easy victory.” Instead, the South paid for Porter’s wall in full, one division at a time, all afternoon.' },
    ],
    meanwhile: { region: 'across the Chickahominy', title: 'The bluff that held the door shut', body: 'While Porter’s corps bled on the north bank, the rest of the war was being decided by an army that barely fought. South of the river stood the bulk of McClellan’s force, the two-thirds of his army he kept facing Richmond, held in place by Magruder’s (South) thin screen of perhaps 25,000 men, many of them green recruits, theatrically marching and shouting to look like far more. Had McClellan grasped how few men were actually in front of him, he could have walked into Richmond that afternoon while Lee had his back turned, gambling everything against Porter. He never tried. Convinced by Pinkerton’s phantom army that he was the one outnumbered, McClellan sat with the bigger force and watched, and Magruder’s bluff held the door to Richmond shut with almost nothing behind it.' },
  },

  'hoods-breakthrough': {
    eyebrow: 'Gaines’ Mill · Hood Breaks the Line',
    title: 'Hood Breaks the Line',
    blocks: [
      { p: 'For most of an afternoon, Robert E. Lee’s army had thrown itself at Porter’s (North) wall and bounced off, division by division, each one alone. Late in the day, with less than an hour of daylight left, Lee finally did the thing he had been failing to do all afternoon: he hit the whole line at once.' },
      { p: 'Around 7 p.m. he launched a general, coordinated assault across his entire front, roughly 32,000 men in about 16 brigades, going forward together. On the right of the attack, the division of Major General James Longstreet (South) pressed in, Brigadier General George Pickett’s (South) brigade among the units driving against Porter’s line; in the center and left, Whiting’s, A.P. Hill’s, and the rest surged forward at the same moment. It was the largest single assault Lee would order in the whole war, and likely the largest Confederate assault of the Civil War, period. (For scale: the famous Pickett’s Charge at Gettysburg a year later used about 12,500 men; Hood’s later attack at Franklin, about 20,000.) After a day of piecemeal failure, all of it landed at once.' },
      { pill: '/war-civil-war/eastern/gettysburg', plabel: 'Gettysburg: where Pickett’s Charge, half this size, became the more famous one' },
      { h: 'Dusk | The Texas Brigade goes through', eyebrow: 'Around 7 p.m.' },
      { p: 'Brigadier General John Bell Hood (South), leading the Texas Brigade in the division of Major General William Whiting (South), found the crack in the wall as part of that coordinated front. He took the 4th Texas (the regiment he had commanded before he was handed the brigade) plus companies of the 18th Georgia, and angled toward a spot across the swamp where the ground looked just slightly more forgiving. Then he did something that took iron discipline: he sent his men forward without firing a shot. That was nearly unheard of, because the trained reflex under fire was to stop, load, and shoot back; ordering men to swallow that reflex and just run meant taking hits without being able to answer. But it also meant not losing momentum, no stopping, no clotting up halfway. Just fixed bayonets, the Rebel Yell (the high, howling war cry Confederate troops loosed when they charged, meant to unnerve the men waiting for them), and a flat-out rush down into the creek and up the deadly hillside that had swallowed assault after assault all day.' },
      { fig: '/war-img/cmdr/hood.jpg', cap: 'Brigadier General John Bell Hood (South), whose Texas Brigade spearheaded the dusk breakthrough', credit: 'Period photograph · public domain' },
      { p: 'It cost them horribly on the way in. A 4th Texas private later described the fire pouring into them “with increasing fury, cutting down our ranks like wheat.” But the unfired rush carried them into and over Porter’s first line at the bottom of the ridge. And then the Union defense worked against itself: with their own retreating men streaming back in front of them, the Federal second and third lines could not shoot cleanly, and Hood’s Texans drove through all three tiers and onto the plateau, capturing 14 cannon at the crest. By the time the battle ended, the Confederates, fighting for the army that was defending slavery’s republic, had taken around 22 Union guns in all.' },
      { p: 'The Texans paid heavily for those guns. Hood’s and Law’s brigades together lost 1,018 men in the assault. The 4th Texas alone was cut roughly in half (regimental records put its losses near 250, though some accounts run far higher) and every one of its field-grade officers, the colonels and majors who led the regiment, became a casualty: its colonel killed, its lieutenant colonel mortally wounded, its major shot down. The wall came down, and the men who walked up that slope holding their fire walked into the same killing ground that had swallowed every charge before them; the difference this time was that enough of them lived to reach the top.' },
      { h: 'The collapse and the consequence | Porter retreats, McClellan quits Richmond', eyebrow: 'Night, June 27–28' },
      { p: 'Once the line broke, Porter’s V Corps came apart in the dusk, men scattering back across open fields toward the Chickahominy. Two whole Union regiments were surrounded and surrendered. A Union cavalry countercharge, about 250 troopers of the 1st and 5th U.S. Cavalry under Brigadier General Philip St. George Cooke (North), who happened to be the father-in-law of Confederate cavalryman J.E.B. Stuart (South), one of Lee’s most famous officers, was thrown in to buy time and was driven back with roughly a quarter of its men cut down.' },
      { p: 'But darkness now did for Porter what Porter’s wall had done all afternoon: it stopped an advance cold. With night coming on, the Confederates could not press the pursuit that might have destroyed the V Corps outright. Through the night of June 27 to 28, with Sykes’s Regulars (the professional U.S. Army troops, the steadiest men in Porter’s corps) covering the rear, Porter pulled his battered corps south across the narrow Chickahominy bridges, and Union engineers burned the bridges behind them.' },
      { p: 'The casualty count tells which kind of victory this was. The two sides together lost roughly 15,000 men. The Union total ran about 6,800 to 7,300, but a large share of that, somewhere around 2,800, were captured, swept up when the line collapsed. The Confederate total was heavier, around 8,000, and far bloodier in killed and wounded (roughly 1,483 killed and 6,402 wounded, against just over 100 captured). By the morning of June 28, Gaines’ Mill stood as the second-bloodiest battle in American history to that point, behind only Shiloh that April; nine Union regimental commanders were killed or mortally wounded, and the 9th Massachusetts (a regiment of roughly 900 Massachusetts volunteers) lost 206 men, more than any other Northern regiment on the field. Lee had won, and he had won by spending more men than his enemy to do it, a pattern that would shadow his generalship for the rest of the war.' },
      { pill: '/war-civil-war/western/shiloh', plabel: 'Shiloh: the only American battle bloodier than this one, three months earlier' },
      { p: 'And the retreat McClellan had already chosen before dawn now became permanent. More convinced than ever that he faced a vastly larger army, McClellan ordered his whole Army of the Potomac to “change base” (the army’s term for packing up and pulling out), abandoning the advance on Richmond and falling back southeast to Harrison’s Landing, a plantation on the James River about 20 miles (32 km) below Richmond where the navy’s gunboats could shell any Confederate who came near. The church spires he had come within a few miles of would stay Confederate. Lee had his first victory: costly, bloody, imperfectly run, and it worked. Gaines’ Mill saved Richmond for 1862 and handed the war in the East to the man who would carry it, against this same McClellan, across this same river country, three months later, at Antietam and the bloodiest single day in American history.' },
      { pill: '/war-civil-war/eastern/antietam', plabel: 'Antietam: Lee and McClellan meet again three months later, the bloodiest day' },
    ],
    meanwhile: { region: 'McClellan’s tent', title: 'The telegram too hot to send', body: 'Just after midnight, McClellan wired Washington his account of the day, ending with a line so insubordinate that the chief censor of the Military Telegraph Service quietly deleted it before it ever reached Secretary of War Edwin Stanton (North): “If I save this army now I tell you plainly that I owe no thanks to you or any other persons in Washington. You have done your best to sacrifice this army.” Stanton and Abraham Lincoln never saw those words; the country would not learn they had been cut until a telegrapher revealed it in 1907. The general who outnumbered Lee had lost his nerve and his campaign, and was already blaming everyone but himself.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={GAINES_MILL_NARR} id={id} slug="gaines-mill" battleName="Gaines' Mill" theatreId="east" battleId="e-gainesmill" />
}
