'use client'

// THEME section — The Emancipation Proclamation (Off the Battlefield, kind=theme).
// NOTE: 'use client' is REQUIRED — this page reads ACCENTS (a value exported from
// a 'use client' module); in a server component that import resolves to a client
// reference and ACCENTS.otbf is undefined, so the accent silently falls back to
// violet. Any war page that passes an ACCENTS color must be a client component.
// First non-battle section built through the war content pipeline (fact pack →
// author(Opus) → fact-check + storytelling critic(Sonnet) → revise). A theme is
// ONE arc-driven section (pressure → turning point → consequence), rendered by
// the shared <BattleSectionReader>; no stat block, no tactical map. Source +
// gate records: audits/war-pipeline/emancipation-*.md. Green accent.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: 'The war’s purpose changes',
    title: 'The Stroke of a Pen, the Slowest Liberation',
    blocks: [
      { p: `For thirteen months Abraham Lincoln had been waiting for a win. Then, on September 17, 1862, along a creek in Maryland called Antietam, he got one, barely. Confederate general Robert E. Lee was stopped cold and pulled his army back across the Potomac, leaving behind a single day of fighting that produced roughly 23,000 combined casualties, the bloodiest single day in American history. It was less a triumph than a survival. But it was enough. Five days later, Lincoln picked up a document he’d been carrying in his pocket for two months and turned it loose on the country.` },
      { p: `What he issued is one of the most famous pieces of paper in American history, and one of the most misunderstood. People remember it as the moment four million enslaved people walked free. It wasn’t. On the day Lincoln signed the final version, it freed almost no one he could actually reach. And yet it remade the war, the country, and the meaning of the whole bloody fight. A freedom document that didn’t immediately free people, and mattered enormously anyway: that paradox is worth sitting with.` },

      { h: 'The president who said one thing, and was already doing another', eyebrow: 'Pressure' },
      { fig: '/war-img/emancipation-contraband-rappahannock.jpg', cap: `August 1862: enslaved families ford the Rappahannock River in wagons and on horseback, fleeing toward Union lines as Confederate forces close in: the most famous photograph of the war's true first emancipators, the enslaved freeing themselves on their own two feet, more than a year before Lincoln drafted a word of the Proclamation.`, credit: `Timothy H. O'Sullivan (Gardner's Gallery) · stereograph, albumen · August 1862 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `By the summer of 1862, the question of slavery was no longer something the war could politely avoid. It kept walking into Union army camps on its own two feet, and it had been doing so since the war’s first spring, long before any politician was ready for it.` },
      { p: `Go back to May 23, 1861, more than a year before Lincoln drafted a word of the Proclamation, barely a month into the war. Three enslaved men named Frank Baker, Shepard Mallory, and James Townsend slipped away from the Confederate work gangs building gun batteries near Hampton, Virginia, took a small boat across the water in the dark, and rowed to Fort Monroe, the big Union-held fort guarding the mouth of the James River. They asked the fort’s commander for protection. That commander was Maj. Gen. Benjamin Butler, a Massachusetts lawyer-turned-general with a lawyer’s eye for a loophole.` },
      { p: `By the rules of the day, a federal law called the Fugitive Slave Act required officials to return escaped enslaved people to their owners. Butler refused. His reasoning was pure courtroom: Virginia had declared itself a foreign country, so it could hardly demand the protection of a United States law it had just walked out on; and these men had been put to work building Confederate fortifications, which made them enemy war material. An army at war seizes the enemy’s war material. So Butler declared the three men “contraband of war” (confiscated enemy property) and kept them. The word stuck. The people who freed themselves this way became “contrabands,” and Fort Monroe earned a new name: Freedom’s Fortress.` },
      { p: `What happened next is the part the textbooks tend to skip. The three men were not an exception; they were the leak that became a flood. Within days, eight more arrived at Fort Monroe. Within weeks, dozens; within months, hundreds; and as the war ground on, the enslaved walked, rowed, and ran to Union lines wherever those lines reached (whole families, sometimes whole plantations’ worth at once) until the army was housing them in sprawling contraband camps. By the end of the war roughly half a million people had freed themselves this way, voting against slavery with their feet faster than any law could keep up. The historian W.E.B. Du Bois would later call it a “general strike”: a vast, leaderless withdrawal of the South’s enslaved labor that gutted the Confederate war economy from the inside. This is the thing to hold onto before any of the famous documents arrive: the first emancipators of the Civil War were the enslaved themselves. Washington spent the next four years catching up to them.` },
      { p: `Congress, prodded by the contrabands, scrambled to write the law to match the reality. The First Confiscation Act (August 6, 1861) did little more than ratify Butler’s loophole: it let the Union seize enslaved people who had been used against it, exactly the case he’d already made at Fort Monroe. The Second Confiscation Act (July 17, 1862) went much further: enslaved people who escaped to Union lines, or were seized from rebel owners, “shall be forever free,” and the army was authorized to enlist African Americans against the rebellion. (That March, Congress had even barred the army from returning people who’d fled to its lines.) Step by step, the politicians were catching up to the people on the boats, and “this isn’t a war about slavery” was getting harder to say with a straight face.` },
      { p: `Lincoln had already made up his mind. On July 13, 1862, he quietly read a draft proclamation to just two men: Secretary of State William H. Seward (his chief diplomat) and Navy Secretary Gideon Welles (whose diary would become one of the great records of the era). On July 22 he laid it before the full cabinet. Edwin Stanton, the Secretary of War, wanted it out immediately. Treasury Secretary Salmon Chase was on board. But Seward raised a hand: not yet. The Union had been losing. Drop an emancipation order now, he warned, and the world would read it as a desperate gesture: “its last shriek of retreat.” Wait for a victory, Seward said, so it goes out from strength.` },
      { p: `So Lincoln waited. And here is where the most famous misunderstanding of his whole presidency was born.` },

      { h: 'The Greeley letter, read correctly' },
      { fig: '/war-img/emancipation-frederick-douglass.jpg', cap: `Frederick Douglass, who had freed himself from slavery and become the most powerful Black voice in America, spent 1861 and 1862 hammering Lincoln in print to stop fighting slavery with one hand tied: free the enslaved, and put muskets in their hands. The pressure on the president did not come from editors and Congress alone. It came from the people the war was about.`, credit: `Merrill & Crosby studio · photograph · 1860s · public domain (via Wikimedia Commons)` },
      { p: `In August 1862, Horace Greeley (editor of the New York Tribune, the loudest newspaper voice in the North) published a furious open letter to the president titled “The Prayer of Twenty Millions,” demanding Lincoln strike at slavery already. On August 22, Lincoln answered him in public, and produced the lines that still get quoted to “prove” he didn’t care about enslaved people:` },
      { p: `My paramount object in this struggle is to save the Union, and is not either to save or to destroy slavery. If I could save the Union without freeing any slave I would do it, and if I could save it by freeing all the slaves I would do it; and if I could save it by freeing some and leaving others alone I would also do that.`, q: true },
      { p: `Read cold, it sounds like a man weighing freedom on a scale of pure expedience. But context flips it. Lincoln had already privately decided to issue the proclamation; the draft was sitting in his desk, waiting only for Seward’s victory. The letter, most historians argue, wasn’t indifference but a performance for a nervous public, framing emancipation as the thing that would save the Union and keeping the jittery slaveholding states still loyal to the U.S. from bolting. He even tucked the truth into the closing line: “I intend no modification of my oft-expressed personal wish that all men every where could be free.” He was managing the country’s nerves while holding a freedom order in his hand.` },
      { p: `And Greeley was not the only one leaning on the president. All through 1861 and 1862, Frederick Douglass (the former enslaved man turned abolitionist, someone demanding slavery be abolished outright, and the most powerful Black voice in America) hammered the same case from his own newspaper: stop fighting slavery with one hand tied, free the enslaved, and put muskets in their hands. “Let the slaves and free colored people be called into service,” he wrote, “and formed into a liberating army.” Where Lincoln was managing a nervous white public, Douglass was telling that public the truth it didn’t want to hear yet: that the war could not be won, or deserved to be won, without making it a war for freedom. The pressure on Lincoln did not come from Congress and editors alone. It came from the people the war was about.` },

      { h: 'A covenant, a deadline, and a document with a hole in the middle', eyebrow: 'Turning point' },
      { p: `When the news came that Lee had been turned back at Antietam, Lincoln treated it as the sign he’d been promised. Welles recorded that the president felt he had “made a covenant with God”: if the army drove the enemy out of Maryland, he would issue the proclamation. The army had. So he did.` },
      { p: `On September 22, 1862, came the preliminary Emancipation Proclamation: an ultimatum with a clock on it. Any state still in rebellion on January 1, 1863, would have the enslaved people within it declared, in Lincoln’s own words, “thenceforward, and forever free.” The rebel states had a little over three months to lay down arms and rejoin the Union. None did. And so, on the afternoon of January 1, 1863, after standing through the traditional White House New Year’s reception, Lincoln signed the final version.` },
      { fig: '/war-img/emancipation-cabinet.jpg', cap: 'Lincoln reads the draft to his cabinet, summer 1862. Stanton seated at left, Welles bearded at center, Seward at front right.', credit: 'Francis B. Carpenter, “First Reading of the Emancipation Proclamation” (1864), Senate wing of the U.S. Capitol · public domain' },

      { h: 'What it actually said, and the hole at its center' },
      { fig: '/war-img/emancipation-proclamation-print.jpg', cap: `An ornately engraved 1864 reproduction of the full text of the Emancipation Proclamation, sold to a North that wanted the words on its wall. The fine print is the whole story: signed as a "war measure," it named ten rebel states and pointedly exempted the loyal slaveholding ones, so it freed enslaved people only where the Union army could not yet reach them.`, credit: `engraved by W. Roberts · printed reproduction of the Emancipation Proclamation · 1864 · public domain (via Wikimedia Commons)` },
      { p: `Lincoln did not free the enslaved as a moral emperor waving a wand. He freed them as a general, specifically as “Commander-in-Chief,” calling the act “a fit and necessary war measure for suppressing said rebellion.” That phrase, war measure, was the whole game. It was his legal justification, and it was also his cage. A president at war can seize an enemy’s resources. A president has no general power to abolish slavery by decree. So the proclamation could only reach the enemy’s territory, which is exactly where Lincoln’s pen could not yet reach anybody.` },
      { p: `Look at where it applied. It named ten states in rebellion: Arkansas, Texas, Louisiana, Mississippi, Alabama, Florida, Georgia, South Carolina, North Carolina, and Virginia. And then look at who it pointedly left out. The “border states” (the slaveholding states along the line between North and South: Missouri, Kentucky, Maryland, and Delaware) that had stayed in the Union were exempt; slavery stayed perfectly legal there. So was all of Tennessee, under Union military government. So were thirteen Union-occupied Louisiana parishes (Louisiana’s word for counties), New Orleans among them, and the Virginia counties breaking away to form West Virginia, plus the Norfolk area.` },
      { p: `In other words: the proclamation freed enslaved people only in the places the Union army didn’t yet control, and exempted the slaveholding places it did control. Hundreds of thousands of people across the border states and the occupied zones were left exactly where they were, still held in bondage. The document covered more than 3.5 million of the nearly 4 million enslaved in America, but “covered” is doing heavy lifting. On the day it was signed, the number actually walking free, in the few coastal corners the army already held, was perhaps twenty thousand. For everyone else, freedom now had a precondition: the United States Army had to physically arrive. Liberation would advance one mile at a time, at the speed of the columns. It was not a moment. It was a promise the army would have to keep with its boots.` },

      { h: 'Why it landed like thunder anyway' },
      { fig: '/war-img/emancipation-nast-print.jpg', cap: `Thomas Nast's "Emancipation," published in Harper's Weekly weeks after the Proclamation took effect: the horrors of slavery on the left, a hopeful free future on the right: a Black family at its own hearth, children walking to school, wages honestly paid. It is the visual argument for why people who understood slavery best celebrated a document that, on paper, had freed almost no one yet.`, credit: `Thomas Nast · "The emancipation of the negroes, January, 1863 — the past and the future," Harper's Weekly · 1863 · Library of Congress (via Wikimedia Commons) · public domain` },
      { p: `So why did anyone celebrate? Because the people who understood slavery best understood what had just changed.` },
      { p: `In Boston, at Tremont Temple, Frederick Douglass (the great abolitionist orator who had himself been enslaved) spent New Year’s night in an agony of waiting for the telegraph. “We were waiting and listening as for a bolt from the sky, which should rend the fetters of four millions of slaves,” he later wrote, “we were longing for the answer to the agonizing prayers of centuries.” When word finally came that Lincoln had signed, the hall erupted, and the rejoicing spilled into a nearby church that, by Douglass’s account, “did not break up till near the dawn of day.” Douglass grasped what the fine print couldn’t hide: the United States government had just, officially, put itself on the side of ending slavery. The war’s purpose had changed. There was no going back.` },

      { h: 'One signature, four ways the world tilted', eyebrow: 'Consequence' },
      { fig: '/war-img/emancipation-usct-colors.jpg', cap: `The 20th United States Colored Troops receive their regimental colors before a vast crowd in New York's Union Square, March 5, 1864. The Proclamation had authorized Black men to enlist; roughly 180,000 would serve, about one in ten of all Union manpower. Men who had been property a year earlier now wore the uniform and bled for the freedom of the rest.`, credit: `published in Harper's Weekly · wood engraving · 1864 · Library of Congress (via Wikimedia Commons) · public domain` },
      { p: `First, it changed what the war was for. Before, the official goal was simple: restore the Union. After January 1, 1863, the goal was to restore the Union and end slavery in the rebel states. You cannot overstate how big that is. Every mile the army advanced now carried freedom with it as a matter of national policy. The war and abolition had become the same campaign.` },
      { p: `Second, it put rifles in the hands of the formerly enslaved. The proclamation authorized Black men to enlist, and on May 22, 1863, General Order No. 143 created the Bureau of U.S. Colored Troops to organize them. Roughly 180,000 Black soldiers would serve in the Union army, about one in ten of all Union manpower, with some twenty thousand more in the Navy. And they did not just fill out the ranks. That July, the 54th Massachusetts, one of the first Black regiments, charged the sand walls of Fort Wagner in South Carolina at dusk and lost nearly half its men in a single assault, and the country read about it. Men who had been property a year earlier now wore the uniform and bled for the freedom of the rest.` },
      { p: `But these men were fighting two wars at once: one against the Confederacy, and one against the army that had recruited them. White privates were paid $13 a month plus a clothing allowance. Black soldiers were paid $10 a month, and then had $3 docked for clothing, leaving $7, barely half a white soldier’s wage, for the same risk and the same dying. The men of the 54th Massachusetts refused to take it. For more than a year they served without drawing a single dollar rather than accept unequal pay; some of their families went hungry at home while they made the point. Corporal James Henry Gooding of the 54th wrote directly to President Lincoln, in plain and unanswerable language, asking whether the men who had charged Fort Wagner were soldiers of the United States or something less. The protest worked: in 1864 Congress equalized the pay and made much of it retroactive, with Frederick Douglass among those pushing for it. The men who had to argue for the right to die for the country also had to argue, and win, the right to be paid the same for it.` },
      { p: `Third, it quietly killed the Confederacy’s last hope abroad. The South had been betting that Britain and France, starved of Southern cotton, would step in and recognize the Confederacy as a real country. But once Lincoln reframed the war as a war against slavery, recognizing the Confederacy meant openly siding with slavery, politically impossible in Britain, where abolitionism ran deep. After Antietam and the proclamation, British leaders dropped the mediation talk that had been drifting around in the fall of 1862; Britain never recognized the Confederacy. Even the cotton-mill workers of Manchester, England, thrown out of work by the loss of Southern cotton, backed the Union anyway. Lincoln, moved, praised their “sublime Christian heroism.” The South’s foreign lifeline went slack.` },
      { p: `And fourth, it pointed the way to making freedom permanent. Because the proclamation was only a war measure, everyone understood its weakness: it could be challenged, narrowed, or unwound once the war ended. To free people for good, the Constitution itself had to change. That recognition drove the push for the 13th Amendment, which abolished slavery nationwide, passing the Senate in April 1864, the House on January 31, 1865, and finally ratified (approved by the required three-quarters of the states) on December 6, 1865. The proclamation lit the road. The amendment paved it.` },

      { h: '“My whole soul is in it”' },
      { fig: '/war-img/emancipation-lincoln-1863.jpg', cap: `Abraham Lincoln, photographed by Alexander Gardner on November 8, 1863, the same season he was telling the artist Francis Carpenter that if his name ever went into history it would be for the Proclamation: "my whole soul is in it." He signed it slow and firm on New Year's Day, worried only that a hand stiff from holiday handshaking would be misread as a hand that trembled with doubt.`, credit: `Alexander Gardner · albumen photograph (Ostendorf O-77) · November 8, 1863 · public domain (via Wikimedia Commons)` },
      { p: `On signing day, Lincoln’s hand was a mess. Not from nerves, but from hours of holiday handshaking. He reportedly joked that he’d “been receiving calls and shaking hands since nine o’clock this morning, till my arm is stiff and numb,” and worried that “this signature is one that will be closely examined, and if they find my hand trembled they will say he had some compunctions.” So he steadied himself and signed slow and firm. “I never in my life felt more certain that I was doing right,” he reportedly said, “than I do in signing this paper.” And, the artist Francis Carpenter later remembered, he added that if his name ever went into history it would be for this act: “and my whole soul is in it.”` },
      { p: `He was right about the history. The Emancipation Proclamation freed shockingly few people on the day it was signed. But it changed what the war meant, who could fight it, who would help it from abroad, and where the whole story was heading. It was a beginning that read like an ending: a promise the army would spend two more years keeping, mile by mile, until a constitutional amendment made it forever.` },

      { h: 'Freedom at the speed of an army', eyebrow: 'The promise kept' },
      { fig: '/war-img/emancipation-freedpeople-group.jpg', cap: `A group of self-emancipated people ("contrabands") photographed on a Virginia farm in May 1862. These were the faces of the "general strike" against slavery: families who walked toward freedom from the war's first spring, by the hundreds of thousands, faster than any government could keep up. For many of them the Proclamation's promise would not be made real until a Union army physically arrived. In Texas, that was not until June 1865.`, credit: `James F. Gibson · albumen photograph · May 1862 · Library of Congress (via Wikimedia Commons) · public domain` },
      { p: `Because the proclamation freed people only where the army could reach, freedom did not arrive everywhere at once. It arrived the way the army arrived: a town at a time, a county at a time, often years after the ink had dried in Washington. The farther a place sat from the war, the longer its enslaved people waited for a freedom that, on paper, was already theirs.` },
      { p: `Nowhere waited longer than Texas. It was far from the fighting, full of enslavers who had fled there with the people they held precisely to keep them out of the army’s reach, and the Union had no force on the ground to enforce a thing. So slavery simply went on for two and a half years after the Proclamation took effect. Then, on June 19, 1865, Maj. Gen. Gordon Granger landed at Galveston with Union troops and read out General Order No. 3 (the army’s official announcement), informing the people of Texas that “all slaves are free.” For as many as a quarter-million people, that day in June was the day the Proclamation finally became real. They named the day for the date, Juneteenth, and have celebrated it ever since. It is, in a sense, the truer Emancipation Day: not the day a president signed a promise, but the day the last of the enslaved heard that the promise had come for them too.` },
      { p: `Even then, freedom arrived contested. Within months, the defeated Southern states began passing Black Codes (1865–66), laws designed to chain the formerly enslaved back to the plantation by other means: vagrancy statutes that could jail a Black man for being out of work, contracts that bound laborers to a single employer for a year, rules barring Black families from owning land or moving freely. Freedom had been won on the battlefield and was being clawed back in the statute books before the soldiers had even gone home.` },
      { p: `What finally shut the door on slavery was not the Proclamation at all, but the constitutional amendment it had pointed toward. The 13th Amendment, passed by the House on January 31, 1865, and ratified on December 6, 1865, abolished slavery everywhere in the United States, in every state, with no “war measure” asterisk and no army required to make it stick. That was the real ending: not a stroke of one man’s pen, but a law the whole country was bound to. The Emancipation Proclamation lit the road and freed people one mile at a time at the speed of marching columns. The enslaved had walked toward that freedom from the war’s first spring, by the hundreds of thousands, faster than any government could keep up. And the freedom they reached for in 1861, and that Galveston finally heard about in 1865, was made permanent, for everyone at last, by the amendment that closed the book.` },
    ],
    meanwhile: {
      region: 'the Eastern Theatre, five days earlier',
      title: 'Antietam',
      body: 'The bloodiest single day in American history was also the victory Lincoln had been waiting for. Lee’s retreat from Maryland gave him the moment of strength Seward had told him to find, and the preliminary proclamation followed within the week.',
    },
  },
}

export default function EmancipationThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="emancipation"
      battleName="The Emancipation Proclamation"
      theatreId="offfield"
      battleId="th-emancipation"
      theatreHref="/war-civil-war/off-the-battlefield"
      accent={ACCENTS.otbf}
      heroImage="/war-img/emancipation-hero-ls.jpg"
      heroPalette={['#3a342a', '#23201a', '#0a0806']}
      heroCredit={`"Watch Meeting — Dec. 31st 1862 — Waiting for the Hour" · after William Tolman Carlton, 1863 · Heard & Moseley carte-de-visite, Boston · Library of Congress (via Wikimedia Commons) · public domain`}
      endHref="/war-civil-war/off-the-battlefield"
      endKicker="Free at last"
      endLabel="Back to Off the Battlefield"
    />
  )
}
