// AUTHORED gated draft of the "Pre-Socratics" philosophy SCHOOL read (kind = TRADITION) — the
// "whole tradition across the centuries" deep read for the Pre-Socratics camp (school id `pre`),
// the analog of the shipped Platonism school read. Written ONLY from
// audits/philosophy-pipeline/presocratics-school-fact-ledger.md. PhiNarr shape is identical to
// platonism.ts and the thinker reads.
//
// Quote doctrine: every quoted fragment is VERIFIED PD wording from John Burnet, Early Greek
// Philosophy (3rd ed., 1920, PD), confirmed word-for-word against Wikisource on 2026-06-14, and
// cited by DK number in the fact ledger. PARAPHRASE / reported-doctrine items (Pythagoras "all
// things are number", Protagoras "man is the measure", Anaximander's proto-evolution) are framed
// as reported, never invented as fragments. Framing traps from the ledger are honored: "everything
// flows" (panta rhei) is named as a later summary, not a Heraclitus fragment; Zeno's "tortoise" is
// Simplicius' later dress on Aristotle's "slowest runner"; "Pre-Socratic" is a modern label of
// convenience; the biography (Thales' well, Pythagoras' golden thigh, Empedocles' leap, Democritus'
// self-blinding) is framed as tradition/legend, never asserted flat; Western-overclaim is guarded
// ("Western philosophy begins", not "philosophy begins"). Inline *italics*, **bold**, and
// [text](/internal-href) links to the four existing hubs (Thales, Pythagoras, Heraclitus,
// Parmenides) are rendered by the page; figure captions are gated content; alt text is presentational.

import type { PhiNarr } from '@/components/philosophy-reader'

export const PRESOCRATICS: PhiNarr = {
  "title": "The Pre-Socratics",
  "throughline": "The moment a handful of Greeks stopped explaining the world by gods and stories and started explaining it by impersonal natural principles and reasoned argument. That move is where Western philosophy and natural science both begin. The first questions they asked (what is everything really made of, and is change real or an illusion?) outlived every answer they gave, and the questions are the inheritance. This is the story of a group of thinkers who did not yet have a word for what they were doing, whose books are all lost, who survive only as quotations in the writings of later men, and who nonetheless invented the habit of mind that everything after them runs on.",
  "hero": {
    "fig": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Miletus_-_Ancient_Greek_theatre_01.jpg/1280px-Miletus_-_Ancient_Greek_theatre_01.jpg",
    "cap": "The great theatre of *Miletus*, the Ionian Greek city on the coast of Anatolia (modern Turkey). Miletus produced [Thales](/philosophy/thinker/thales), Anaximander, and Anaximenes, the first three people known to have explained the world by nature instead of the gods. The theatre is later than they are; the place is the birthplace. Photo: Bernard Gagnon, 2014 (CC BY-SA 3.0).",
    "alt": "Wide view of a large, well-preserved ancient Greek stone theatre with tiered seating curving around a flat stage area, set in an open landscape under a clear sky"
  },
  "hook": [
    "For most of human history every people that ever looked at the sky explained it the same way: with a story. The sun is a god driving a chariot. The storm is a god who is angry. The sea has a will, the harvest has a will, the world is a vast family of persons whose moods are the weather and the seasons and the luck of the year. In the Greek world that story had a canonical form in Hesiod's *Theogony*, written around 700 BC, which tells the cosmos as a genealogy of gods: first Chaos, then Earth, then the rest, born and married and warring down the generations. To explain a thing was to say which god was behind it and what that god wanted.",
    "Then, in a Greek trading city on the coast of what is now Turkey, sometime in the early sixth century BC, a man named [Thales](/philosophy/thinker/thales) said something different. He said the world is ultimately made of one underlying stuff, and the stuff is water, and the earth floats on it. No god enters the explanation. There is no chariot, no anger, no will. There is a material, a question about that material, and an argument about the answer. It sounds almost too small to matter. It is the hinge of Western intellectual history.",
    "The shift has a name. The old way was **mythos** (MOO-thoss), explanation by gods and stories. The new way was **logos** (LOH-goss), explanation by impersonal natural principles and reasoned argument, the kind of account another person can examine, doubt, and try to beat. The people who made this turn are grouped under a label coined long after they were dead: the **Pre-Socratics**, meaning the thinkers before Socrates. The label is a convenience and a little misleading, because some of them were Socrates' own contemporaries; they never thought of themselves as one school. What unites them is the move itself, the decision to treat the world as something that can be reasoned about rather than only worshipped.",
    "One difficulty belongs at the start. Not a single complete book by any of these thinkers survives. Everything that is known of them comes secondhand: short quotations (called **fragments**) preserved inside the writings of much later authors, and summaries (called **doxography**, the reports of others' opinions) written by people like Aristotle, his pupil Theophrastus, the commentator Simplicius a thousand years on, and the gossipy biographer Diogenes Laertius, who is the single largest source of the legends and the least reliable. Reading the Pre-Socratics means reading a reconstruction. Much of the biography is late invention. The genuine sentences are precious and few, and where a famous line cannot be pinned to a real fragment, that is said plainly. What survives is enough to watch the most important intellectual habit in the Western tradition being switched on for the first time."
  ],
  "brk": {
    "beforeLabel": "The world is a society of gods, and to explain a thing is to name the god behind it and read its will",
    "afterLabel": "The world is a natural order, and to explain a thing is to find the principle it works by and argue for it",
    "paragraphs": [
      "The Milesians did not necessarily deny the gods. What they did was stranger and more lasting: they removed the gods from the *explanation*. In the mythic mode, the cause of the storm is Zeus, and there is nothing further to investigate, because a person's will is not the kind of thing that has a further mechanism. In the new mode, the cause of the storm is air doing something that air does, and that *can* be investigated, because a natural process has further steps that can be traced, modeled, and disputed. Mythos gives an answer that closes the question. Logos gives an answer that opens it.",
      "The decisive feature of the new way is not that the first answers were correct. They mostly were not. Water is not the secret of everything; the earth does not float on it. The decisive feature is that the answers were the *kind of thing that could be wrong*, and known to be wrong by argument, so that the next person could disagree and propose better. That is exactly what happened. [Thales](/philosophy/thinker/thales) said water; his successor Anaximander said the underlying stuff cannot be any one familiar thing at all; Anaximander's successor Anaximenes said air, and explained *how* it turns into everything else. Three men in three generations in one city, each correcting the last with reasons. A tradition of criticism had begun, and a tradition of criticism is what science and philosophy actually are.",
      "That is the break, and the whole story is a sequence of moves made on the board it opened. The board is a single conviction: the world is a natural order with a hidden structure, and the human mind can reach that structure by reasoning rather than by revelation. Every Pre-Socratic plays on that board. They will disagree, ferociously, about what the hidden structure is (one stuff or many, changing or changeless, continuous or made of indivisible bits), and the deepest of those disagreements, between [Heraclitus](/philosophy/thinker/heraclitus) and [Parmenides](/philosophy/thinker/parmenides) over whether change is even real, will set the agenda for everything that follows, straight through Socrates, Plato, and Aristotle. What never reverts is the founding move. After the Milesians, to explain the world is to argue about it."
    ]
  },
  "chapters": [
    {
      "num": 1,
      "title": "The men of Miletus and the search for the one stuff",
      "epigraph": {
        "text": "\"And into that from which things take their rise they pass away once more, as is meet; for they make reparation and satisfaction to one another for their injustice according to the ordering of time.\"",
        "attribution": "— Anaximander, the one surviving fragment (DK 12 B1), trans. John Burnet (1920)"
      },
      "blocks": [
        {
          "p": "It begins in Miletus, a wealthy Greek port on the coast of Ionia (the central stretch of the Anatolian seaboard, in present-day Turkey), in the early sixth century BC. Ionia was the right place for it: rich from trade, in constant contact with the older civilizations of Egypt and Babylon and their accumulated astronomy and mathematics, politically restless, and far enough from the old religious centers of mainland Greece to think freely. Three men of this one city, across three generations, took the founding step, and the thing that links them is a single question. They were looking for the **archē** (AR-kay), a term Aristotle later used for what they sought: the first principle, the original and underlying stuff out of which everything is made and into which it all returns. One question, three answers, each arguing with the last."
        },
        {
          "p": "[Thales](/philosophy/thinker/thales) (active around 585 BC) gave the first answer: the archē is **water**. Everything is ultimately water in some form, and the earth itself rests on water like a log on a pond. The reasoning has to be reconstructed, because Thales wrote nothing that survives and the report comes from Aristotle two centuries later, given cautiously and partly as conjecture. The likeliest case is the plainest one: water is the substance that visibly takes every form, solid as ice, liquid as the sea, vapor as mist and cloud, and life everywhere depends on it, so it is a reasonable guess at the stuff behind all stuff. The guess is wrong. That is not the point. The point is that it is a guess about *nature*, defended by *observation*, with no god in it, and that had not been done before. The well-loved stories about Thales (that he predicted an eclipse, that he fell down a well while staring at the stars, that he cornered the olive-press market to prove a philosopher could get rich if he cared to) all come from much later writers and are best treated as the tradition they are, not as biography."
        },
        {
          "p": "His successor **Anaximander** (around 610 to 546 BC) made the first great correction, and it is a subtle, powerful one. If the underlying stuff were water, he reasoned, then water would have an unfair advantage over its opposites; a world whose ground was the cold and the wet could never have produced an equal measure of the hot and the dry. So the archē cannot be any one of the familiar opposites at all. It must be something more basic and indefinite, with no particular qualities of its own, out of which all the opposites separate off. He called it the **apeiron** (ah-PY-ron), the Boundless: limitless in extent, indefinite in kind, eternal, the neutral reservoir from which worlds emerge and back into which they dissolve. With Anaximander the explanation has left the realm of ordinary substances entirely and become genuinely abstract. He is also credited with the first map of the known world and with a startling guess that living things arose from moisture and that humans must have developed from creatures of a different kind, since a human infant could never have survived alone, a line of thought that points, faintly and across two and a half thousand years, toward the idea of evolution."
        },
        {
          "p": "Anaximander left behind what is very likely the oldest surviving sentence of Western philosophy, the line in this chapter's epigraph: that things pass back into the Boundless and \"make reparation and satisfaction to one another for their injustice according to the ordering of time.\" The image is of a cosmic balance kept by law. When the hot encroaches in summer it commits an injustice against the cold, and in winter it pays the penalty back; the opposites trade dominance forever under a fixed order, the \"ordering of time.\" It reaches the modern world only because the commentator Simplicius quoted it a thousand years later, quoting Theophrastus quoting Anaximander, which is exactly how fragile this inheritance is. Even the first sentence of the tradition survives only at three removes."
        },
        {
          "fig": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Anaximander_Mosaic.jpg",
          "cap": "A Roman floor mosaic from Trier, early third century AD, showing a seated figure with a sundial, identified as *Anaximander*. It is one of the very few ancient images of a Milesian, and like everything else about these men it reaches the present at a great distance: a Roman picture made some eight centuries after its subject lived.",
          "alt": "An ancient Roman mosaic showing a seated bearded man in a draped robe, gesturing toward an upright sundial",
          "portrait": true
        },
        {
          "p": "The third Milesian, **Anaximenes** (around 586 to 526 BC), pulled the abstraction back toward the concrete and, in doing so, supplied the piece the other two were missing: a mechanism. The archē, he said, is **air** (the breath, the unseen stuff all around). What made this more than a third guess in a list was his explanation of *how* air becomes everything else. Air turns into other things by thickening and thinning, by **condensation and rarefaction**. Thinned out, air becomes fire; thickened, it becomes wind, then cloud, then water, then earth, then stone. In Burnet's translation of the surviving line, \"When it is dilated so as to be rarer, it becomes fire; while winds, on the other hand, are condensed Air.\" This is the first time a Greek explained the *variety* of the world by a single physical process acting on a single substance, more or less or denser or thinner. It is, in embryo, the explanatory move all of physics would later make. With Anaximenes, Burnet wrote, the Milesian cosmology became consistent for the first time. Three men, one city, one question, and a method of correction-by-argument that has never been turned off since."
        }
      ]
    },
    {
      "num": 2,
      "title": "Pythagoras and the world made of number",
      "epigraph": {
        "text": "\"They supposed the elements of numbers to be the elements of all things.\"",
        "attribution": "— Aristotle on the Pythagoreans, *Metaphysics* A.5"
      },
      "blocks": [
        {
          "p": "While the Milesians were asking what stuff the world is made of, a very different answer was taking shape across the sea, in the Greek cities of southern Italy. Its source was [Pythagoras](/philosophy/thinker/pythagoras) (around 570 to 495 BC), born on the Ionian island of Samos, who emigrated around 530 BC to Croton in the Italian south and founded there not a school exactly but a brotherhood: a tight community bound by ritual, secrecy, dietary rules, and a shared way of life devoted to study. Almost nothing about Pythagoras can be known with confidence, and that is not a figure of speech. He wrote nothing. His followers attributed their own discoveries back to him on principle (\"the master said it himself\" was a way of settling arguments), and the surrounding biography is pure legend: that he had a golden thigh, that he remembered his past lives, that he forbade his followers to eat beans. All of it comes from writers centuries later and belongs to the cult that grew up around him, not to any reachable man."
        },
        {
          "p": "What can be recovered is the idea, and the idea is astonishing: that the deep structure of reality is not a *stuff* at all but **number**. Where the Milesians said the world is made of water or air, the Pythagoreans said the world is made of number and ratio; that the truth of a thing is its mathematical form. Aristotle, the source for this, put it bluntly: they \"supposed the elements of numbers to be the elements of all things.\" This is a wholly new kind of answer to the founding question. It moves the hidden structure of the world out of the realm of materials and into the realm of mathematics, and it is the first appearance of an idea that has never gone away, the idea that nature is written in the language of number."
        },
        {
          "p": "The conviction was not mysticism for its own sake; it rested on a real and stunning discovery. The Pythagoreans found that musical harmony is governed by whole-number ratios. Pluck a string, then stop it at half its length, and the note jumps exactly one octave; the ratio is 2 to 1. The perfect fifth is 3 to 2; the perfect fourth is 4 to 3. The concords the ear finds beautiful correspond precisely to simple ratios of small whole numbers. Here was something invisible and abstract (number) controlling something concrete and sensual (the sound of a plucked string), and controlling it exactly. If number ruled music, why not the cosmos? They extended the thought to the heavens, proposing that the planets in their orbits sound a vast inaudible music, the \"harmony of the spheres,\" each body humming the note its distance dictates. The universe, on this view, is a tuned instrument."
        },
        {
          "p": "Two cautions keep the picture honest. The famous \"Pythagorean theorem,\" the relation between the sides of a right triangle, was known to Babylonian mathematicians long before Pythagoras was born; attaching his name to it is a tradition, not a record of who found it first. And the number-creed met an enemy from inside its own mathematics. A Pythagorean named **Hippasus** is associated with the discovery of magnitudes that cannot be expressed as a ratio of whole numbers at all, the **irrationals** (the length of the diagonal of a square whose sides are one unit is the standard example; no fraction equals it exactly). For a brotherhood that had staked everything on reality being whole-number ratio, this was a scandal in the foundations, and the legend that Hippasus was drowned at sea for letting the secret out is the cult's own melodrama and should be read as legend. The irrationals were real, though, and they were the first crack in the dream of a world that is whole numbers all the way down, a crack the Greeks never fully closed."
        },
        {
          "p": "The Pythagorean contribution to the tradition is twofold and permanent. First, the specific claim that mathematics is the key to nature, which runs underground for centuries and surfaces with full force in Galileo, in Newton, and in every physicist since who has expected the world to obey an equation. Second, the conviction that the truest things are not the things the senses report but an abstract order behind them, graspable only by the intellect. That second idea would pass directly to a young Athenian named Plato, who studied the Pythagoreans closely and built it into the center of his philosophy. The men of Miletus had asked what the world is made of. Pythagoras answered with something that is not a material at all, and in doing so opened the possibility that the realest thing about reality is not in the world the eyes can see."
        }
      ]
    },
    {
      "num": 3,
      "title": "The great quarrel: everything flows against nothing changes",
      "epigraph": {
        "text": "\"This world, which is the same for all, no one of gods or men has made; but it was ever, is now, and ever shall be an ever-living Fire, with measures of it kindling, and measures going out.\"",
        "attribution": "— Heraclitus, fragment (DK 22 B30), trans. John Burnet (1920)"
      },
      "blocks": [
        {
          "p": "Out of the founding move came two thinkers who pushed reasoning to opposite extremes, and the collision between them is the single most consequential argument in early Greek thought. The question they split over is as basic as a question can be: is change real? One of them answered that change is the only thing that is real. The other answered that change is impossible, a flat illusion, and that reason can prove it. Every philosopher after them inherits the problem they opened, because both arguments are strong and they cannot both be right."
        },
        {
          "p": "[Heraclitus](/philosophy/thinker/heraclitus) of Ephesus (around 535 to 475 BC) took the first position. He wrote a single book, now lost, in deliberately riddling prose that earned him the nickname \"the Obscure,\" and he survives in some of the most quoted fragments in philosophy. His core perception is that reality is not a collection of stable things but a ceaseless process. The world is a fire, never the same from instant to instant: \"an ever-living Fire, with measures of it kindling, and measures going out,\" as the epigraph has it. His most famous image is the river: \"You cannot step twice into the same rivers; for fresh waters are ever flowing in upon you.\" The river keeps its name and its banks, but the water is never the water of a moment ago, so in the deepest sense it is never the same river. Everything that looks solid (a stone, a body, a city) is like that river, a stable-seeming pattern riding on constant flux. The bald slogan usually hung on Heraclitus, \"everything flows\" (in Greek *panta rhei*), is in fact a later summary by other writers and not a sentence he is recorded as writing; the genuine line is the river fragment, and the slogan is the textbook's shorthand for it."
        },
        {
          "p": "Heraclitus is widely misremembered as a prophet of pure chaos, and he is the reverse. The flux is not random; it is governed. The thing that governs it he called the **logos** (the same word that names reasoned explanation itself): a hidden rational principle, a measure or formula that holds the changing world in order. \"Though this Word is true evermore,\" his book opened, \"yet men are as unable to understand it when they hear it for the first time as before they have heard it at all.\" The order is real but hidden, and it consists in the tension of opposites, the way a bowstring or a lyre string is held taut and useful by pulling in two directions at once. \"The hidden attunement is better than the open,\" he wrote. Strife is not a flaw in the world but its engine: \"War is the father of all and the king of all.\" The picture is of a world in perpetual change, perpetually balanced, ruled by a logos most people are too asleep to notice. Change is everything, and change is lawful."
        },
        {
          "p": "Against this stood [Parmenides](/philosophy/thinker/parmenides) of Elea (around 515 to 450 BC), of a Greek colony in southern Italy, and he is the first philosopher to trust a chain of pure reasoning over the plain evidence of the eyes, even when the reasoning leads somewhere the eyes flatly deny. He wrote his philosophy as a poem in which a goddess reveals the truth, and the argument she delivers is austere and devastating. Start, Parmenides says, from the one thing that cannot be doubted: *it is*. Whatever is, is; and \"it is impossible for it not to be.\" Now consider its opposite, what-is-not, sheer nothing. Nothing cannot be thought, because to think is always to think of *something*; nothing cannot be spoken of, because to speak of it is to make it a something. What-is-not is therefore not even available to the mind. And from that single move the whole familiar world unravels."
        },
        {
          "p": "Follow the consequences, which Parmenides follows without flinching. Could what-is have come into being? Only out of what-is-not, out of nothing, and there is no such thing to come out of: \"How, then, can what is be going to be in the future? Or how could it come into being? If it came into being, it is not.\" So Being is **ungenerated**, never born. Could it perish? Only into nothing, which is unavailable, so Being is **imperishable**, it never dies. Could it change, become what it is not? To do that it would have to take on some what-is-not, which does not exist, so Being is **changeless**. Could it be divided, with gaps of empty nothing between its parts? There is no nothing to do the separating, so Being is **one**, a single undivided whole. Reason, pushed all the way, proves that reality is a single, eternal, motionless, indivisible Being, and that the world the senses report, full of many things coming to be, changing, and passing away, is simply false. The deepest claim of all is the quietest: \"for it is the same thing that can be thought and that can be.\" Whatever can be coherently thought is real, and whatever cannot be coherently thought (a true nothing, a real becoming) is not."
        },
        {
          "p": "Parmenides handed his argument down with a bodyguard. His pupil **Zeno of Elea** built a series of paradoxes designed to show that motion and plurality, the things common sense takes for granted, lead to absurdity, so that Parmenides' impossible-sounding conclusion is actually the *safer* bet. The best known is what Aristotle presents in the *Physics* (Z, 9. 239b14) as the Achilles paradox: Achilles will never overtake the tortoise, because before he reaches the place from which the tortoise started, the tortoise has moved ahead, and before he reaches that point the tortoise has moved again, through infinitely many such steps, so the gap is never closed. Zeno's paradoxes were a genuine intellectual weapon, and untangling them would occupy mathematicians into the modern age. The quarrel was now fully drawn. Heraclitus: all is flux, held by a hidden logos. Parmenides: change is impossible, and reason trumps the senses. Neither could simply be dismissed, and the next generation had no choice but to answer the harder of the two."
        }
      ]
    },
    {
      "num": 4,
      "title": "Saving the world from Parmenides",
      "epigraph": {
        "text": "\"At one time it grew to be one only out of many; at another, it divided up to be many instead of one... at one time all uniting in one through Love, at another each borne in different directions by the repulsion of Strife.\"",
        "attribution": "— Empedocles, fragment (DK 31 B17), trans. John Burnet (1920)"
      },
      "blocks": [
        {
          "p": "Parmenides had built a wall across the road. His logic seemed airtight: nothing comes from nothing, true being cannot perish, and so real change is impossible. But the world plainly does change; things are born and die, fire turns wood to ash, the seasons turn. The thinkers who came after him faced a precise and difficult task. They could not simply ignore the argument, because no one had refuted it. They had to find a way to grant Parmenides his logic and still save the appearances, still account for the changing world everyone lives in. The solution they converged on, in three different versions, was one of the most fertile ideas in the history of science: keep Parmenides' unchanging being, but make it *many*, and let what looks like change be nothing more than the rearrangement of permanent parts."
        },
        {
          "p": "**Empedocles** of Akragas (around 494 to 434 BC), in Sicily, gave the first version. There is not one unchanging being, he said, but four: the eternal, indestructible **roots** of everything, which later thinkers would call the four elements, fire, air, earth, and water. The roots themselves never come to be and never perish, exactly as Parmenides demanded. What we call birth and death is only the four roots mixing in new proportions and then separating again; bone is so much earth and fire and water blended in a fixed ratio, and when a creature dies nothing is destroyed, the roots merely part. Two forces drive the mixing and parting, and Empedocles named them **Love** (which draws the roots together) and **Strife** (which pulls them apart), the cosmos breathing slowly between unity and division forever: \"at one time all uniting in one through Love, at another each borne in different directions by the repulsion of Strife.\" Change is rescued without violating Parmenides, because at the level of the roots nothing ever really changes at all. (Empedocles also attracted the usual cloud of legend, including the tale that he leapt into the volcano Etna to prove he was a god; it is a story about him, not a fact about him.)"
        },
        {
          "p": "**Anaxagoras** of Clazomenae (around 500 to 428 BC), who brought philosophy to Athens for the first time, gave a stranger and more radical version. He kept Parmenides' rule that nothing truly comes to be, and pushed it to an extreme: there is \"a portion of everything in everything.\" Every scrap of matter contains some of every kind of stuff, however far it is divided, and a thing appears to be bread or bone or gold simply because that ingredient predominates in it. When bread becomes flesh, no new flesh is created; the flesh was already there in the bread, mixed in, and the body draws it out. \"All things were together,\" he wrote of the beginning, \"infinite both in number and in smallness; for the small too was infinite.\" His most important move comes next. To get from that original undifferentiated mixture to an ordered cosmos, something had to start the sorting, and Anaxagoras named that something **Nous** (rhymes with \"house\"), Mind. Mind is the one thing not mixed with everything else; it is \"infinite and self-ruled, and is mixed with nothing, but is alone itself by itself,\" the \"thinnest of all things and the purest,\" and it set the whole mixture spinning and separating into a world. This is the first time in the tradition that *mind* is named as the ordering principle of the cosmos, and it electrified the next generation. The young Socrates, by Plato's account, was thrilled to hear that Mind arranges all things, then bitterly disappointed to find that Anaxagoras, having introduced Mind, used it only to start the spin and then explained everything else mechanically, a complaint that would echo for centuries."
        },
        {
          "p": "The boldest answer of all came from **Leucippus** and his pupil **Democritus** of Abdera (around 460 to 370 BC), and it is the one that turned out, two thousand years later, to be closest to the truth. They granted Parmenides his unchanging being and his ban on coming-from-nothing, and then made two daring moves at once. First, being is not one but consists of countless tiny, solid, indivisible, unchanging bits, the **atoms** (from the Greek *atomos*, \"uncuttable\"), each one a little eternal Parmenidean sphere of pure being. Second, and this is the audacious part, they affirmed the very thing Parmenides had outlawed: the **void**, empty space, literally what-is-not, in which the atoms move. \"He called them what is,\" Burnet writes of the atoms, \"while they moved in the void which he called what is not.\" Parmenides had said nothing cannot exist; the atomists calmly replied that the nothing exists too, as the empty room the somethings need in order to move. Everything in the universe, on their view, is atoms and void: countless uncuttable particles, differing only in shape and size and arrangement, falling and colliding and hooking together in the emptiness, building up the whole visible world by their combinations and breaking it down again when they part."
        },
        {
          "p": "Two features of atomism mark it as a leap past everything before it. The world it describes is fully mechanical and runs on necessity, with no Mind and no Love and no Strife required; the one surviving line of Leucippus states it flatly: \"Naught happens for nothing, but everything from a ground and of necessity.\" And the atomists drew a distinction that modern science would make its own: the atoms have only shape, size, and motion, and the qualities we seem to perceive (color, taste, warmth, sound) are not really in the atoms but arise in us from their impact on our senses. The honey is not sweet in itself; there are only smooth atoms striking the tongue. Democritus, like the others, comes wrapped in legend (the \"laughing philosopher,\" the story that he blinded himself to think better, both from the unreliable Diogenes Laertius), and his atomism was a minority view in its own time, dismissed by Plato and qualified by Aristotle. But it never quite died. It would be revived by Epicurus a century later and carried into the Roman world, and when European science went looking, in the seventeenth century, for a picture of matter made of small moving particles in empty space, it found that two Greeks had sketched the idea before anyone had a microscope. The wall Parmenides built had been climbed, three different ways, and the third way pointed straight at the physics to come."
        }
      ]
    },
    {
      "num": 5,
      "title": "The turn to man, and the handoff to Socrates",
      "epigraph": {
        "text": "\"Man is the measure of all things: of the things that are, that they are, and of the things that are not, that they are not.\"",
        "attribution": "— Protagoras, as reported by Plato, *Theaetetus* 152a"
      },
      "blocks": [
        {
          "p": "By the second half of the fifth century BC the great cosmological questions had been argued to a kind of exhaustion. The thinkers had disagreed brilliantly and irreconcilably about what the world is made of and whether change is real, and a reasonable person might well conclude that these towering questions could not be settled at all. Out of that mood came a new kind of intellectual, and a new direction for thought. The center of gravity shifted, from Italy and Ionia to Athens, now the richest and most powerful Greek city and a democracy in which the ability to argue persuasively in the assembly and the law court was the path to influence. The thinkers who met that demand were the **Sophists**, traveling professional teachers who, for a fee, taught the skills of public life: rhetoric, argument, and *aretē* (a-reh-TAY), the excellence or effectiveness that lets a man succeed in the city."
        },
        {
          "p": "The Sophists turned philosophy away from the cosmos and toward the human world: language, law, custom, persuasion, and the question of how to live. The greatest of them, **Protagoras** of Abdera (around 490 to 420 BC), captured the new outlook in a single famous line, preserved by Plato: \"Man is the measure of all things.\" The claim is that there is no truth standing above human judgment; things are, for each person, as they appear to that person, so that what is hot or just or good is always hot-for-someone, just-for-someone, with no view from nowhere to overrule it. It is the ancient ancestor of relativism, and it provoked exactly the reaction that would shape the next chapter of philosophy. If everything is merely a matter of who is more persuasive, then truth collapses into rhetoric and justice into power, and a young Athenian named Socrates would spend his life insisting that it does not, that there are real answers about virtue and the good and that they can be reached by relentless questioning."
        },
        {
          "p": "That objection is where the Pre-Socratic age ends and classical philosophy begins. The thinkers in this story had asked one family of questions: what is the world ultimately made of, where did it come from, and is the change we see real? Socrates (470 to 399 BC) deliberately set those questions aside, by his own account having found the study of nature unsatisfying, and asked a different family entirely: what is justice, what is courage, what is the good, and how should a person live? The focus moved from the cosmos to the soul, from physics to ethics, from what is to what ought to be. But the tools Socrates and his heirs used were forged in the two centuries just described. Plato took Parmenides' conviction that the truest reality is changeless and graspable only by thought, married it to the Pythagorean faith in an abstract order behind the senses, and produced the theory of Forms. Aristotle took the Milesian project of explaining nature systematically and built it into the first comprehensive science. Neither could have done it without the men who first dared to treat the world as something to be reasoned about."
        },
        {
          "p": "What the Pre-Socratics handed forward, in the end, was not a set of correct answers; almost every specific answer they gave was eventually discarded or transformed. What they handed forward was the questions, and the way of asking them. Is reality one or many? Is change real, or only rearrangement? Is the world matter, or number, or something the senses cannot reach? Is true knowledge possible at all, or only persuasion? Those questions did not close when Socrates picked up his own. They were absorbed and carried, through Plato and Aristotle, through the long history that follows, into the physics and the metaphysics still argued today. Their books are lost, their lives are half legend, and they survive in scraps quoted by their critics. But the habit they invented, of looking at the world and demanding a reason rather than a story, never lapsed. Western philosophy and natural science both begin in the moment a man in Miletus looked at everything there is and said: it is made of water, and here is why."
        }
      ]
    }
  ]
}
