'use client'

// Antietam — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const ANTIETAM_NARR: Record<string, Narr> = {
  'lost-order': {
    eyebrow: 'Antietam · Lee invades the North',
    title: 'The Lost Order',
    blocks: [
      { p: 'In the late summer of 1862, the Civil War was going badly for the United States, and Robert E. Lee (South) decided to make it worse. For more than a year the fighting in the East had been a war fought on Southern soil, with Northern armies grinding into Virginia and getting thrown back out again. Lee had just broken one of those armies near Washington. Now, instead of waiting for the next blow, he did something audacious: he marched his Army of Northern Virginia north, across the Potomac River and into Maryland. It was his first invasion of the North.' },
      { fig: '/war-img/antietam-lost-order.jpg', cap: 'The rebel army crossing the fords of the Potomac for the invasion of Maryland — Lee’s columns moving north by moonlight, in a Harper’s Weekly engraving.', credit: 'Harper’s Weekly · public domain' },
      { p: 'The gamble was about more than ground. A Confederate victory on Northern soil might convince Britain or France to formally recognize the Confederacy as a country — to treat the South as a real nation rather than a rebellion. Recognition could mean trade, money, maybe even intervention. A loud win above the Potomac might also break Northern nerve in an election year. Lee was not just raiding Maryland. He was reaching for the things that win wars without being battles.' },
      { fig: '/war-img/antietam-campaign.png', cap: 'The Maryland Campaign: Lee crosses the Potomac and pushes north past Frederick, peeling off part of his army to take Harpers Ferry — the plan the lost order revealed.', credit: 'Stuff Happened map' },
      { h: 'The two armies', eyebrow: 'The odds' },
      { p: 'The man sent to stop him was Maj. Gen. George B. McClellan (North), commander of the Army of the Potomac. McClellan was a gifted organizer and a beloved leader of men, and he had one defining flaw that decided everything that followed: he would bring roughly 87,000 men toward this fight against Lee’s 38,000 — better than two to one — and spend the whole campaign convinced he was the one outnumbered. The bigger army, certain it was the smaller, was the central fact of the day.' },
      { p: 'To pull off an invasion with an army half the size of his enemy’s, Lee did the riskiest thing a general can do in front of a stronger foe: he split it into pieces, sending part of his force to capture the Union garrison at Harpers Ferry while the rest moved on. It was a bet that McClellan would be too slow and too cautious to catch the scattered halves before they reunited. Given the man he was facing, it was a reasonable bet.' },
      { h: 'The three cigars', eyebrow: 'September 13' },
      { p: 'Then the war handed McClellan a miracle. On September 13, near Frederick, Maryland, a Union soldier named Barton Mitchell of the 27th Indiana was resting in a field a Confederate unit had just left when he noticed something on the ground: three cigars, wrapped in a piece of paper. The cigars were a nice find. The paper was the war. It was a copy of Special Order 191 — Lee’s own campaign orders, laying out exactly how he had divided his army and where each piece was going.' },
      { p: 'Generals dream of this and never get it. McClellan now knew his enemy was split, scattered, and beatable in detail — destroy one piece before the others could rejoin. He is reported to have said it himself:' },
      { p: '“Here is a paper with which if I cannot whip Bobbie Lee I will be willing to go home.”', q: true },
      { p: 'He had the map to the other man’s army. Then he sat on it.', i: true },
      { p: 'True to form, McClellan waited roughly eighteen hours before he moved. It was enough time for Lee to learn the order had been lost and to start pulling his army back together along a low ridge near a town called Sharpsburg, behind a winding stream called Antietam Creek. The once-in-a-war chance was still a chance — McClellan still had the bigger army and the high ground of knowledge. But the margin had narrowed from “catch them scattered” to “catch them gathering.” On the morning of September 17, the two armies stood across Antietam Creek from each other, and the bloodiest day in American history began.' },
    ],
    meanwhile: { region: 'Washington', title: 'The president waits for a win', body: 'In Washington, Abraham Lincoln (North) had a document finished and locked in a drawer: a proclamation to free the slaves in the rebelling states. His cabinet had told him not to release it while the army was losing — it would read like a desperate cry, not a decision. He needed a victory first. He had been waiting all summer for one. Maryland was about to give him the closest thing he would get.' },
  },

  'cornfield': {
    eyebrow: 'Antietam · The morning',
    title: 'The Cornfield',
    blocks: [
      { p: 'The day did not happen all at once. Antietam was really three battles fought one after another, rolling from the north end of the line to the south across a single September day, as if neither army could manage to fight everywhere at the same time. The first one started at dawn, on the northern end, in a farmer’s cornfield.' },
      { p: 'Union Maj. Gen. Joseph Hooker (North) sent his I Corps smashing into the left of Lee’s line, straight through a field of standing corn owned by a farmer named Miller. The corn was tall and ripe, taller than a man, and it hid soldiers until they were close enough to kill each other in the face. Lines surged forward, were shot to pieces, fell back, were replaced, and surged again. Miller’s Cornfield changed hands, by some counts, roughly fifteen times in a few hours. Hooker wrote in his official report that the corn had been cut “as closely as could have been done with a knife, and the slain lay in rows precisely as they had stood in their ranks a few moments before.” The corn was cut down. So were the men standing in it.' },
      { fig: '/war-img/antietam-cornfield.png', cap: 'Dawn at the northern end: Hooker’s corps drives south into Miller’s Cornfield and the Dunker Church.', credit: 'Stuff Happened map' },
      { h: 'The Dunker Church', eyebrow: 'A pacifist chapel at the center of it' },
      { p: 'The fighting swirled around a small whitewashed building on the edge of the field: the Dunker Church. It belonged to the Dunkers, a German Baptist sect whose entire faith was built on plainness and pacifism — they believed Christians must never take up arms, never fight, never kill. Their modest little meetinghouse, raised by people who had renounced violence as a sin, became the bullet-scarred landmark of the worst single day of violence the country had ever seen. There is no way to make that irony gentle. The men of two armies bled out around the doorstep of a church whose congregation believed all of it was forbidden.' },
      { fig: '/war-img/antietam-dunker-church.jpg', cap: 'The Dunker Church after the battle, with the dead and a wrecked limber before it — a pacifist congregation’s plain meetinghouse, at the center of the bloodiest day.', credit: 'Alexander Gardner · Library of Congress · public domain' },
      { h: 'The West Woods', eyebrow: 'Twenty minutes' },
      { p: 'A little later, on that same northern end, the killing found a new low. A Union division under Maj. Gen. John Sedgwick (North) pushed into a stand of trees called the West Woods, marching in a tight formation right into a trap. Confederate troops were waiting on three sides. They opened fire into the packed Union ranks from front and flank at once, and the division came apart. In roughly twenty minutes, Sedgwick’s men took around 2,200 casualties. Not in a day. In about the length of a coffee break. A man getting out alive ran back through his own dead and dying — friends he had marched in with that morning sprawled across the leaves, the wounded grabbing at his legs as he passed — and the woods behind him so thick with bodies you could not cross them without stepping on someone. The northern third of the battlefield had become a place where a man could be alive and whole one moment and one of thousands of bodies the next, and the sun was barely up.' },
    ],
    meanwhile: { region: 'the Confederate left', title: 'Holding with nothing to spare', body: 'Lee (South) had no soldiers to waste and was spending them anyway. Outnumbered two to one across the whole field, he could only hold his crumbling left by stripping troops from other parts of his line and rushing them north, plugging gaps as fast as they tore open. It worked — the line bent and held — but it was the arithmetic of a man with no reserves, robbing one threatened spot to save another. He was committing his entire army. McClellan, with far more men, was about to do the opposite.' },
  },

  'bridge': {
    eyebrow: 'Antietam · Midday & afternoon',
    title: 'The Bloody Lane & the Bridge',
    blocks: [
      { p: 'By late morning the fighting slid south to the center of Lee’s line, where Confederate soldiers had taken cover in a worn-down farm lane. Years of wagon traffic had sunk the road below the level of the surrounding fields, turning an ordinary country path into a ready-made trench. Wave after wave of Union troops marched up the rising ground toward it and were shot down by the men sheltered in the sunken road. For hours the lane held.' },
      { p: 'Then it didn’t. Union soldiers worked around to a position where they could fire straight down the length of the road, and the trench that had protected the Confederates turned into a killing chute with no cover. Men fell in heaps along its length. When it was over the lane had a new name that it still carries: Bloody Lane. The Federals had finally punched a hole clean through the center of Lee’s army.' },
      { fig: '/war-img/antietam-sunken-road.png', cap: 'The center at midday: Union assaults swing around to fire down the length of the Sunken Road — “Bloody Lane” — and break through.', credit: 'Stuff Happened map' },
      { h: 'The reserves that never moved', eyebrow: 'The great missed chance' },
      { p: 'This was the moment. Lee’s center was broken open, his army split, his whole position one hard shove from collapse. McClellan (North) had an entire fresh corps in reserve — Maj. Gen. Fitz John Porter’s (North) V Corps — standing ready behind the lines, the men who could have driven through the gap and finished the Army of Northern Virginia for good. And McClellan, certain as always that Lee had hidden masses of men somewhere, refused to send them in. The hole closed. The chance passed. It was the great missed opportunity of the day, maybe of the war — the bigger army holding back the punch that could have ended its enemy.' },
      { h: 'Burnside’s Bridge', eyebrow: 'Afternoon' },
      { p: 'At the southern end of the field, a third battle had been grinding on. Maj. Gen. Ambrose Burnside (North) and his IX Corps spent much of the afternoon trying to cross a narrow stone bridge over Antietam Creek, defended by only a few hundred Georgia riflemen on the high bank above. The numbers tell the whole grim joke of it: thousands of men in blue, a few hundred in gray, hours of dying for a bridge they didn’t have to take. The Georgians, dug in on the heights, picked off anyone who set foot on the span — even though, as it turned out, the creek could be waded across at other spots not far away. Hours and lives went into forcing a bridge that didn’t have to be forced. It has been called Burnside’s Bridge ever since.' },
      { fig: '/war-img/antietam-bridge.png', cap: 'The afternoon at the southern end: Burnside forces the bridge and pushes toward Sharpsburg — until A. P. Hill’s division arrives from Harpers Ferry and strikes his flank.', credit: 'Stuff Happened map' },
      { fig: '/war-img/antietam-burnside-bridge.jpg', cap: 'Burnside’s Bridge over Antietam Creek, photographed soon after the battle. A few hundred Georgians on the far bank held a whole corps here for most of an afternoon.', credit: 'Alexander Gardner · Library of Congress · public domain' },
      { p: 'When Burnside’s men finally got across and reorganized, they pushed uphill toward Sharpsburg itself, into the rear of Lee’s exhausted, outnumbered army. And here Lee was finished. He had spent his whole army to hold the morning’s fights; he had nothing behind his right but tired men and empty road, no fresh brigade left to throw in, and Burnside’s blue mass climbing toward the town that anchored his entire line. One more push and the Army of Northern Virginia was done. The Confederate line was about to break for the last time.' },
      { p: 'And then, out of the south, came the dust of marching men.', i: true },
      { h: 'A. P. Hill’s arrival', eyebrow: 'The last roll of the dice' },
      { p: 'The men were Confederate Maj. Gen. A. P. Hill’s (South) “Light Division,” and they had no business being there yet. They had spent the day on the road, force-marching about seventeen miles from Harpers Ferry to reach the battlefield, some of them dressed in Union blue uniforms captured at the garrison they had just taken. They arrived at the worst possible moment for Burnside and the best possible moment for Lee, slammed into the Union flank, and drove Burnside’s corps back down the slope they had just climbed. The line held. The Confederate army, somehow, was still alive when the sun went down. The battle ended in the dark, with both armies right where they had nearly destroyed each other.' },
    ],
    meanwhile: { region: 'across the country', title: 'A number no one had ever seen', body: 'By nightfall on September 17, more Americans had been killed, wounded, or gone missing in this one day than on any single day in the nation’s history. The country did not yet know the figure. It would take days to count, and longer to believe.' },
  },

  'bloodiest': {
    eyebrow: 'Antietam · The cost & the meaning',
    title: 'The bloodiest day',
    blocks: [
      { p: 'Start with the cost, because the cost is the story. In one day — September 17, 1862 — the two armies suffered about 22,726 casualties, killed, wounded, and missing. It remains the bloodiest single day in American history, and nothing has come close in the more than a century and a half since. The Union counted roughly 12,410 of those, with 2,108 men killed; the Confederates about 10,316, with 1,547 killed. Put another way, around a quarter of every Union soldier engaged and nearly a third of every Confederate became a casualty in the space of one September day. These were not abstractions. They were the men who had been standing in Miller’s Cornfield at dawn and lying in it by breakfast, the 2,200 lost in the West Woods in twenty minutes, the dead heaped in the Bloody Lane until you could have walked its length without touching the ground.' },
      { h: 'The dead would not stay invisible', eyebrow: 'Brady’s exhibition' },
      { p: 'For the families up North, the war had always happened somewhere else, described in newspaper columns and casualty lists — names in small type, a war you read about. Antietam ended that. On September 18 and 19, two photographers named Alexander Gardner and James Gibson, working for the famous studio of Mathew Brady, walked the field before the dead were buried and photographed the bodies exactly as they had fallen. In October, Brady put the pictures on display in New York under the title “The Dead of Antietam.” It was the first time the American public had ever seen photographs of battlefield corpses.' },
      { fig: '/war-img/antietam-bloody-lane.jpg', cap: 'Confederate dead in the Sunken Road — “Bloody Lane” — from Gardner’s series. Photographs like these, shown in New York as “The Dead of Antietam,” were the first time the public saw the war’s corpses.', credit: 'Alexander Gardner · Library of Congress · public domain' },
      { p: 'People filed past the images in stunned silence. A war that had been words became, suddenly, faces and bodies. The New York Times put it plainly:' },
      { p: '“Mr. Brady has done something to bring home to us the terrible reality and earnestness of war. If he has not brought bodies and laid them in our door-yards and along the streets, he has done something very like it.”', q: true },
      { p: 'The dead in those frames were somebody’s son, and now everyone could see it.', i: true },
      { h: 'Lee slips away, McClellan stays put', eyebrow: 'September 18 and after' },
      { p: 'The morning after the slaughter came up over a field that had not moved an inch. The two armies were still there, what was left of them, standing in the same ground they had ruined the day before and looking at each other across it. The dead lay between them in the corn and the lane and the woods. Neither side attacked. Lee (South) held his line all day with his back to the Potomac and nothing behind it — no reserves anywhere in the world, his whole army spent — and simply waited, daring McClellan to come and finish what he had started. McClellan (North), who still had Porter’s untouched corps and thousands more men he had never sent in, did not come. He let the day pass. That night Lee quietly slipped his entire army back across the river into Virginia, and McClellan let him go without a fight.' },
      { p: 'It was, in the end, a strategic victory for the United States: Lee’s invasion of the North was turned back, and the Confederacy’s bid for the foreign recognition that might have saved it was broken. But it was a maddening, half-finished victory. Lee’s army — the thing McClellan had held the orders to destroy and the reserves to destroy it with — escaped intact to fight for nearly three more years. In November, his patience finally gone, Lincoln (North) relieved McClellan of his command.' },
      { fig: '/war-img/antietam-lincoln-mcclellan.jpg', cap: 'Lincoln visits McClellan in his tent at Antietam, October 1862 — two weeks after the battle, and a month before he relieved the general for letting Lee escape.', credit: 'Alexander Gardner · Library of Congress · public domain' },
      { p: 'The man who could organize an army better than anyone could never quite bring himself to spend it.', i: true },
      { h: 'What the day was for', eyebrow: 'Five days later' },
      { p: 'The deepest meaning of Antietam wasn’t decided on the field at all. It was decided in Washington, five days later. Lincoln had been waiting all summer for a victory — any victory — to give him the standing to act, and the turning-back of Lee’s invasion was close enough. On September 22, 1862, he issued the preliminary Emancipation Proclamation, putting the South on notice that the enslaved people in the rebelling states would be declared free.' },
      { p: 'In a stroke, it changed what the war was about. A fight to hold the Union back together became, openly and on the record, a fight to end slavery. And it slammed a door that had stood worryingly open: no European power could now step in on the side of the Confederacy without standing up, in front of the whole world, for slavery against a nation fighting to abolish it. Britain and France stayed out. The bloodiest day in American history had bought, at a price almost too large to write down, the moment the war became a war for freedom.' },
    ],
    meanwhile: { region: 'Richmond & London', title: 'A door swings shut', body: 'For the Confederacy, the worst loss at Antietam wasn’t the casualty count — it was the diplomacy. The recognition Lee had marched north to win moved out of reach the moment Lincoln tied the Union cause to emancipation. After September 1862, backing the South meant backing slavery in the eyes of the world, and no European government was willing to pay that price. The invasion that was meant to win the war abroad helped lose it there instead.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={ANTIETAM_NARR} id={id} slug="antietam" battleName="Antietam" />
}
