'use client'

// Antietam — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.
//
// VOICE PASS 2026-06-01 (dossier-retrofit strand 2): brought to the locked
// house-voice rules — no em-dashes; marquee names (Lee, Jackson, McClellan,
// Lincoln) carry no side-tag while every other side-affiliated person is tagged
// once on first mention per section; full rank spelled out on first appearance
// per section; meta-narrator / editorial asides removed (tell it plainly);
// South Mountain added as the missing campaign beat; cross-refs are pills
// (Second Bull Run, Emancipation). Facts web-verified. See audits/war-pipeline.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const ANTIETAM_NARR: Record<string, Narr> = {
  'lost-order': {
    eyebrow: 'Antietam · Lee invades the North',
    title: 'The Lost Order',
    blocks: [
      { locator: {
        eyebrow: 'Where and when · September 1862',
        caption: 'Sharpsburg sits in western Maryland, on Antietam Creek a few miles above the Potomac. Lee crossed into Maryland near Frederick, sent Jackson back across the river to take the Union garrison at Harpers Ferry, then pulled his scattered army together at Sharpsburg, a long day’s march north of Washington.',
        frame: { lonMin: -80.4, lonMax: -74.6, latMin: 37.1, latMax: 40.6 },
        states: [
          { name: 'Maryland', tone: 'focus', label: 'MARYLAND', labelLon: -76.5, labelLat: 38.7 },
          { name: 'Virginia' }, { name: 'Pennsylvania' }, { name: 'West Virginia' },
          { name: 'Delaware' }, { name: 'New Jersey' }, { name: 'Ohio' },
        ],
        dots: [
          { name: 'Sharpsburg', date: 'Sept 17, 1862', lat: 39.46, lon: -77.75, heavy: true, anchor: 'start' },
          { name: 'Frederick', lat: 39.41, lon: -77.41, color: '#8a8175', anchor: 'end' },
          { name: 'Harpers Ferry', lat: 39.32, lon: -77.74, color: '#8a8175', anchor: 'start' },
          { name: 'Washington', lat: 38.91, lon: -77.04, color: '#8a8175', anchor: 'end' },
        ],
      } },
      { p: 'In the late summer of 1862, the war in the East had been going badly for the United States, and Robert E. Lee set out to make it worse. For more than a year the fighting there had been waged on Southern soil, with Northern armies grinding into Virginia and getting thrown back out again. Lee had just broken one of those armies near Washington at the end of August. Now, instead of waiting for the next blow, he marched his Army of Northern Virginia north, across the Potomac River and into Maryland. It was his first invasion of the North.' },
      { pill: '/war-civil-war/eastern/second-bull-run', plabel: 'Second Bull Run: the victory that opened the road north' },
      { fig: '/war-img/antietam-lost-order.jpg', cap: 'The rebel army crossing the fords of the Potomac for the invasion of Maryland: Lee’s columns moving north by moonlight, in a Harper’s Weekly engraving.', credit: 'Harper’s Weekly · public domain' },
      { p: 'The gamble was about more than ground. A Confederate victory on Northern soil might convince Britain or France to recognize the Confederacy as a country, to treat the South as a real nation rather than a rebellion. Recognition could mean trade, money, perhaps even intervention. A loud win above the Potomac might also break Northern nerve in an election year. Lee was not merely raiding Maryland. He was reaching for the things that win wars without battles.' },
      { fig: '/war-img/antietam-campaign.png', cap: 'The Maryland Campaign: Lee crosses the Potomac and pushes north past Frederick, peeling off Jackson’s wing to take Harpers Ferry, while McClellan forces the passes of South Mountain behind him.', credit: 'Stuff Happened map' },
      { h: 'The two armies', eyebrow: 'The odds' },
      { p: 'The man sent to stop him was Major General George B. McClellan, commander of the Army of the Potomac. McClellan was a gifted organizer and a beloved leader of men, with one flaw that shaped everything that followed. He would bring roughly 87,000 men toward this fight against Lee’s 38,000, better than two to one, and spend the whole campaign convinced that he was the one outnumbered. The bigger army, certain it was the smaller, was the central fact of the day.' },
      { p: 'To invade with an army half the size of his enemy’s, Lee took the riskiest course open to a general in front of a stronger foe: he divided it. He sent part of his force under Major General Thomas “Stonewall” Jackson back across the Potomac to capture the Union garrison at Harpers Ferry, while the rest pushed on into Maryland. It was a bet that McClellan would be too slow and too cautious to catch the scattered halves before they reunited. Given the man he was facing, it was a reasonable bet.' },
      { h: 'The three cigars', eyebrow: 'September 13' },
      { p: 'Then McClellan got an extraordinary piece of luck. On September 13, near Frederick, Maryland, a Union soldier named Barton Mitchell of the 27th Indiana was resting in a field a Confederate unit had just left when he noticed three cigars on the ground, wrapped in a piece of paper. The paper mattered far more than the cigars. It was a copy of Special Order 191, Lee’s own campaign orders, laying out exactly how he had divided his army and where each piece was going.' },
      { p: 'McClellan now knew his enemy was split, scattered, and beatable in detail: he could destroy one piece before the others rejoined. He is reported to have said it himself:' },
      { p: '“Here is a paper with which if I cannot whip Bobbie Lee I will be willing to go home.”', q: true },
      { p: 'Then he waited. True to form, McClellan held still for about eighteen hours before he moved, time enough for Lee to learn the order had been lost.' },
      { p: 'When McClellan did move, the orders pointed him straight at Lee’s scattered pieces. On September 14 his army forced the gaps in South Mountain, the long ridge standing between the two armies, in a day of hard fighting that drove the Confederate defenders off the passes. It was a Union victory, but the delay bought Lee the hours he needed. Jackson finished his work to the south: on September 15 the Harpers Ferry garrison surrendered, more than 12,000 men laying down their arms, the largest surrender of United States troops in the war. Lee called the rest of his army together along a low ridge near a town called Sharpsburg, behind a winding stream called Antietam Creek. McClellan still had the bigger force and the advantage of knowing the plan, but the chance had narrowed from catching the Confederates scattered to catching them as they gathered. On the morning of September 17, the two armies stood across Antietam Creek from each other, and the bloodiest day in American history began.' },
    ],
    meanwhile: { region: 'Washington', title: 'The president waits for a win', body: 'In Washington, Abraham Lincoln had a document finished and locked in a drawer: a proclamation to free the enslaved people in the rebelling states. His cabinet had told him not to release it while the army was losing, since it would read like a desperate cry rather than a decision. He needed a victory first, and he had been waiting all summer for one. Maryland was about to give him the closest thing he would get.' },
  },

  'cornfield': {
    eyebrow: 'Antietam · The morning',
    title: 'The Cornfield',
    blocks: [
      { p: 'Antietam was really three battles fought one after another, rolling from the northern end of the line to the south across a single September day. The first began at dawn, on the northern end, in a farmer’s cornfield.' },
      { p: 'Major General Joseph Hooker (North) sent his I Corps (a corps being the army’s largest building block, on the order of ten to fifteen thousand men, made up of smaller divisions and brigades) smashing into the left of Lee’s line, the wing held by Major General Thomas “Stonewall” Jackson. They drove straight through a field of standing corn owned by a farmer named Miller. The corn was tall and ripe, taller than a man, and it hid soldiers until they were almost on top of one another. Lines surged forward, were shot to pieces, fell back, were replaced, and surged again. Miller’s Cornfield changed hands, by some counts, roughly fifteen times in a few hours. Hooker wrote in his official report that the corn had been cut “as closely as could have been done with a knife, and the slain lay in rows precisely as they had stood in their ranks a few moments before.”' },
      { p: 'For a while it was the Confederate left simply absorbing the blow and bleeding. Then the South hit back. Brigadier General John Bell Hood’s (South) division had been pulled out of the line just before dawn to cook the first hot breakfast the men had seen in days, and they were yanked off their half-cooked food and thrown straight into the Cornfield, hungry and furious. Hood’s counterattack drove the Union troops back out of the corn and shoved the morning’s tide the other way. It is much of why the field changed hands so many times instead of falling once and staying fallen. It also cost him nearly everything. Hood’s division was wrecked doing it, losing somewhere around sixty percent of its men in the corn. Asked afterward where his division had gotten to, Hood is supposed to have answered that it was dead on the field. Whether or not he said it in those exact words, it was very nearly the truth.' },
      { p: 'Senior officers were falling as fast as the men they led. Around mid-morning Hooker himself was shot through the foot and carried from the field, and with him went the one commander driving the whole northern attack; leadership of the I Corps passed on the spot to Brigadier General George Meade (North). The morning was not one corps but a relay of them. When Hooker’s drive stalled, a second wave came up behind it, the XII Corps under Major General Joseph K. F. Mansfield (North), feeding fresh men into the same killing ground. Mansfield, a white-bearded old soldier of long service, rode forward to position his troops and was almost immediately shot down; he died of the wound the next day. Two senior Union generals were down before noon, one carried off and one dying, and a third corps was still waiting its turn.' },
      { fig: '/war-img/antietam-cornfield.png', cap: 'Dawn at the northern end: Hooker’s corps drives south into Miller’s Cornfield and the Dunker Church.', credit: 'Stuff Happened map' },
      { h: 'The Dunker Church', eyebrow: 'A pacifist chapel at the center of it' },
      { p: 'The fighting swirled around a small whitewashed building on the edge of the field, the Dunker Church. It belonged to the Dunkers, a German Baptist sect whose faith was built on plainness and pacifism; they believed Christians must never take up arms, never fight, never kill. Their plain meetinghouse, raised by people who had renounced violence as a sin, became the bullet-scarred landmark of the worst single day of violence the country had yet seen. The men of two armies fought and died around the doorstep of a church whose congregation believed all of it forbidden.' },
      { fig: '/war-img/antietam-dunker-church.jpg', cap: 'The Dunker Church after the battle, with the dead and a wrecked limber before it: a pacifist congregation’s plain meetinghouse, at the center of the bloodiest day.', credit: 'Alexander Gardner · Library of Congress · public domain' },
      { h: 'The West Woods', eyebrow: 'Twenty minutes' },
      { p: 'A little later, on that same northern end, a Union division under Major General John Sedgwick (North) pushed into a stand of trees called the West Woods, marching in tight formation straight into a trap. Confederate troops were waiting on three sides. They opened fire into the packed Union ranks from the front and the flank (the exposed side of a formation) at once, and the division came apart. In roughly twenty minutes, Sedgwick’s men took around 2,200 casualties. A man getting out alive ran back through his own dead and dying, friends he had marched in with that morning sprawled across the leaves, the wounded grabbing at his legs as he passed, the woods behind him so thick with bodies a man could not cross without stepping on someone. By then the sun was barely up, and the northern third of the field was already covered with the dead.' },
      { fig: '/war-img/antietam-west-woods.png', cap: 'Sedgwick’s division pushes west out of the Cornfield into the West Woods and is caught by Confederate fire from three sides; around 2,200 men fall in about twenty minutes.', credit: 'Stuff Happened map' },
    ],
    meanwhile: { region: 'the Confederate left', title: 'Holding with nothing to spare', body: 'Lee had no soldiers to waste and was spending them anyway. Outnumbered two to one across the whole field, he could only hold his crumbling left by stripping troops from other parts of his line and rushing them north, plugging gaps as fast as they tore open. It worked, the line bent and held, but it was the arithmetic of a man with no reserves, robbing one threatened spot to save another. He was committing his entire army. McClellan, with far more men, was about to do the opposite.' },
  },

  'bridge': {
    eyebrow: 'Antietam · Midday & afternoon',
    title: 'The Bloody Lane & the Bridge',
    blocks: [
      { p: 'By late morning the fighting slid south to the center of Lee’s line, the wing commanded by Major General James Longstreet (South), where Confederate soldiers had taken cover in a worn-down farm lane. Years of wagon traffic had sunk the road below the level of the surrounding fields, turning an ordinary country path into a ready-made trench. Wave after wave of Union troops marched up the rising ground toward it and were shot down by the men sheltered in the sunken road. For hours the lane held.' },
      { p: 'One of those waves has a name. Among the Union brigades sent up the rising ground was the Irish Brigade, men recruited largely from Irish immigrant neighborhoods of New York and Boston, fighting under green regimental flags, led by Brigadier General Thomas Francis Meagher (North). Before they stepped off toward the lane, their chaplain, Father William Corby, rode the length of the line on horseback and gave the men general absolution, a Catholic priest’s blessing forgiving their sins all at once, the last rites of their faith granted in advance to soldiers about to walk into fire. Then they went forward. They walked into the worst of the sunken-road fire and were torn apart, losing on the order of 540 men in the attack, roughly three of every five who started up the slope. The green flags went down, were picked up, and went down again.' },
      { p: 'Then Union soldiers worked around to a spot where they could fire straight down the length of the road, and the trench that had protected the Confederates became a killing chute with no cover. Men fell in heaps along its length. When it was over, the lane had a new name that it still carries: Bloody Lane. The Federals had finally punched a hole clean through the center of Lee’s army.' },
      { fig: '/war-img/antietam-sunken-road.png', cap: 'The center at midday: Union assaults swing around to fire down the length of the Sunken Road, “Bloody Lane,” and break through.', credit: 'Stuff Happened map' },
      { h: 'The reserves that never moved', eyebrow: 'The great missed chance' },
      { p: 'This was the moment. Lee’s center was broken open, his army split, his whole position one hard shove from collapse. Major General George B. McClellan had an entire fresh corps in reserve, Major General Fitz John Porter’s (North) V Corps, standing ready behind the lines, the men who could have driven through the gap and finished the Army of Northern Virginia for good. McClellan, certain as always that Lee had hidden masses of men somewhere, refused to send them in. The hole closed. The chance passed. It was the great missed chance of the day, the bigger army holding back the blow that could have ended its enemy.' },
      { h: 'Burnside’s Bridge', eyebrow: 'Afternoon' },
      { p: 'At the southern end of the field, a third battle had been grinding on. Major General Ambrose Burnside (North) and his IX Corps spent much of the afternoon trying to cross a narrow stone bridge over Antietam Creek, defended by only a few hundred Georgia riflemen on the high bank above. The numbers were lopsided: thousands of men in blue against a few hundred in gray, hours of dying for a bridge they did not have to take, since the creek could be waded across at other spots not far away. The Georgians, dug in on the heights, picked off anyone who set foot on the span. It has been called Burnside’s Bridge ever since.' },
      { fig: '/war-img/antietam-bridge.png', cap: 'The afternoon at the southern end: Burnside forces the bridge and pushes toward Sharpsburg, until A. P. Hill’s division arrives from Harpers Ferry and strikes his flank.', credit: 'Stuff Happened map' },
      { fig: '/war-img/antietam-burnside-bridge.jpg', cap: 'Burnside’s Bridge over Antietam Creek, photographed soon after the battle. A few hundred Georgians on the far bank held a whole corps here for most of an afternoon.', credit: 'Alexander Gardner · Library of Congress · public domain' },
      { p: 'When Burnside’s men finally got across and reorganized, they pushed uphill toward Sharpsburg itself, into the rear of Lee’s exhausted, outnumbered army. Lee had spent his whole army to hold the morning’s fights. He had nothing behind his right but tired men and empty road, no fresh brigade left, while Burnside’s blue mass climbed toward the town that anchored his entire line. One more push might have finished the Army of Northern Virginia.' },
      { h: 'A. P. Hill’s arrival', eyebrow: 'The last roll of the dice' },
      { p: 'Then, out of the south, came the dust of marching men. They were Major General A. P. Hill’s (South) “Light Division,” and they had spent the day on the road, force-marching about 17 miles (27 km) from Harpers Ferry to reach the battlefield, some of them dressed in Union blue uniforms captured at the garrison they had just taken. They arrived at the worst possible moment for Burnside and the best for Lee, slammed into the exposed Union flank, and drove Burnside’s corps back down the slope they had just climbed. The line held. The Confederate army was still alive when the sun went down. The battle ended in the dark, with both armies right where they had nearly destroyed each other.' },
    ],
    meanwhile: { region: 'across the country', title: 'A number no one had ever seen', body: 'By nightfall on September 17, more Americans had been killed, wounded, or gone missing in this one day than on any single day in the nation’s history. The country did not yet know the figure. It would take days to count, and longer to believe.' },
  },

  'bloodiest': {
    eyebrow: 'Antietam · The cost & the meaning',
    title: 'The bloodiest day',
    blocks: [
      { p: 'In one day, September 17, 1862, the two armies suffered about 22,726 casualties: killed, wounded, and missing. It remains the bloodiest single day in American history, and nothing has come close in the more than a century and a half since. The Union counted roughly 12,410 of those, with 2,108 men killed; the Confederates about 10,316, with 1,547 killed. Around a quarter of every Union soldier engaged, and nearly a third of every Confederate, became a casualty in the space of one September day. Those numbers were the men who had stood in Miller’s Cornfield at dawn and lay in it by breakfast, the 2,200 lost in the West Woods in twenty minutes, the dead heaped in the Bloody Lane until a man could walk its length without touching the ground.' },
      { h: 'The dead would not stay invisible', eyebrow: 'Brady’s exhibition' },
      { p: 'For the families up North, the war had always happened somewhere else, described in newspaper columns and casualty lists, names in small type, a war you read about. Antietam ended that. On September 18 and 19, two photographers named Alexander Gardner and James Gibson, working for the famous studio of Mathew Brady, walked the field before the dead were buried and photographed the bodies exactly as they had fallen. In October, Brady put the pictures on display in New York under the title “The Dead of Antietam.” It was the first time the American public had ever seen photographs of battlefield corpses.' },
      { fig: '/war-img/antietam-bloody-lane.jpg', cap: 'Confederate dead in the Sunken Road, “Bloody Lane,” from Gardner’s series. Photographs like these, shown in New York as “The Dead of Antietam,” were the first time the public saw the war’s corpses.', credit: 'Alexander Gardner · Library of Congress · public domain' },
      { p: 'People filed past the photographs in silence. The New York Times put it plainly:' },
      { p: '“Mr. Brady has done something to bring home to us the terrible reality and earnestness of war. If he has not brought bodies and laid them in our door-yards and along the streets, he has done something very like it.”', q: true },
      { h: 'Lee slips away, McClellan stays put', eyebrow: 'September 18 and after' },
      { p: 'The morning after came up over a field that had not moved an inch. The two armies were still there, what was left of them, standing in the same ground they had ruined the day before and looking at each other across it. The dead lay between them in the corn and the lane and the woods. Neither side attacked. Lee held his line all day with his back to the Potomac and nothing behind it, his whole army spent, and waited, daring Major General George B. McClellan to come and finish what he had started. McClellan, who still had Porter’s untouched corps and thousands more men he had never sent in, did not come. He let the day pass. That night Lee quietly slipped his entire army back across the river into Virginia, and McClellan let him go without a fight.' },
      { p: 'It was, in the end, a strategic victory for the United States: Lee’s invasion of the North was turned back, and the Confederacy’s bid for the foreign recognition that might have saved it was broken. But it was a half-finished one. Lee’s army, the one McClellan had held both the orders and the reserves to destroy, escaped intact and fought for nearly three more years. And the cause that army carried, whatever the courage of the men in its ranks, was at bottom the preservation of slavery, the very thing the day’s outcome was about to start undoing. On November 7, with his patience finally gone, Lincoln relieved McClellan of his command.' },
      { fig: '/war-img/antietam-lincoln-mcclellan.jpg', cap: 'Lincoln visits McClellan in his tent at Antietam, October 1862: two weeks after the battle, and a month before he relieved the general for letting Lee escape.', credit: 'Alexander Gardner · Library of Congress · public domain' },
      { h: 'What the day was for', eyebrow: 'Five days later' },
      { p: 'The most important consequence of Antietam was not decided on the field. It was decided in Washington, five days later. Lincoln had been waiting all summer for a victory, any victory, to give him the standing to act, and the turning-back of Lee’s invasion was close enough. On September 22, 1862, he issued the preliminary Emancipation Proclamation, putting the South on notice that the enslaved people in the rebelling states would be declared free.' },
      { pill: '/war-civil-war/off-the-battlefield/emancipation', plabel: 'The Emancipation Proclamation: what Antietam made possible' },
      { p: 'In a stroke, it changed what the war was about. A fight to hold the Union together became, openly and on the record, a fight to end slavery. And it closed a door that had stood worryingly open: no European power could now step in on the side of the Confederacy without standing up, in front of the whole world, for slavery against a nation fighting to abolish it. Britain and France stayed out. The bloodiest day in American history had bought the moment the war became a war for freedom.' },
    ],
    meanwhile: { region: 'Richmond & London', title: 'A door swings shut', body: 'For the Confederacy, the worst loss at Antietam was not the casualty count. It was the diplomacy. The recognition Lee had marched north to win moved out of reach the moment Lincoln tied the Union cause to emancipation. After September 1862, backing the South meant backing slavery in the eyes of the world, and no European government was willing to pay that price. The invasion that was meant to win the war abroad helped lose it there instead.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={ANTIETAM_NARR} id={id} slug="antietam" battleName="Antietam" theatreId="east" battleId="e-antietam" />
}
