'use client'

// Wilson's Creek — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const WILSONS_CREEK_NARR: Record<string, Narr> = {
  'fight-for-missouri': {
    eyebrow: "Wilson's Creek · The border state",
    title: 'The Fight for Missouri',
    blocks: [
      { p: 'In the first summer of the Civil War, the fight that decided whether Missouri stayed in the United States was not fought by armies at all. It was fought in a St. Louis hotel, in the streets of that same city, and along the rivers and railroads that made Missouri worth fighting for in the first place. Missouri was a border state, a slaveholding state that had not joined the Confederacy and that Abraham Lincoln could not afford to let go. It sat on top of the Union like a keystone. Lose it, and the rebellion would push hundreds of miles north and put its hands on the Mississippi and Missouri rivers, the great water highways into the heart of the country. The man who refused to let that happen was a short, red-bearded, perpetually furious Regular Army officer named Brigadier General Nathaniel Lyon (North), and the way he refused was to start a war before anyone gave him permission to.' },
      { fig: '/war-img/cmdr/lyon.jpg', cap: 'Brig. Gen. Nathaniel Lyon (North), the fierce Union commander who seized the initiative in Missouri, and declared war on its secessionist government on his own authority.', credit: 'Period photograph · public domain' },
      { h: 'A keystone Lincoln could not lose', eyebrow: 'The border state' },
      { p: 'Missouri was a slave state that stayed in the Union, and it was the biggest prize of them all. It bordered the free states of Illinois and Iowa to the north, putting Confederate sympathizers within reach of the North\'s doorstep. More important than the borders were the rivers. The Missouri and the Mississippi ran through or past the state, and rivers in 1861 were how you moved armies and supplies in bulk; whoever held them held the ability to push troops deep into enemy country. Add the rail lines knitting the state together, and Missouri was a logistics jackpot. By the end of the war it would send roughly 40,000 men to the Confederacy and about 60,000 to the Union, a state split down the middle over whether to take Missouri into the Confederacy and keep slavery safe there, which is exactly why both sides fought so hard and so dirty to control it.' },
      { p: 'The Confederate States of America that the secessionists wanted to join was a government whose constitution explicitly protected slavery, and whose own vice president, Alexander Stephens, had declared just weeks earlier that slavery and the subordination of Black people were the literal "cornerstone" of the new nation. When Missouri\'s secessionist leaders fought to deliver the state to that confederacy, they were fighting to keep Missouri a slave state inside a slaveholders\' republic.' },
      { p: 'The trouble was the man in the governor\'s chair. Claiborne Fox Jackson (South) had Confederate sympathies and a problem: in March 1861, a Missouri state convention (a special elected body called to decide the question) had voted *against* secession (secession being a state\'s formal break from the United States altogether). The people of Missouri, formally, wanted to stay. Jackson did not let that stop him. He set about reorganizing the state militia and using it to menace the one thing the Union most needed to protect, the St. Louis Arsenal, a federal weapons depot (an arsenal being a government storehouse stuffed with guns, powder, and cannon) holding enough arms to outfit an army. Whoever grabbed the arsenal could arm Missouri. Jackson wanted it for the South. The Army had sent Lyon to St. Louis back in January for the express purpose of keeping it out of his hands.' },
      { h: 'St. Louis', eyebrow: 'Camp Jackson' },
      { p: 'In early May 1861, Lyon, at that point still only a captain, learned that pro-secession state militia were drilling at a camp outside St. Louis, a place they had named Camp Jackson after the governor. Worse, the camp had taken delivery of four cannon that Confederates had seized from the federal arsenal at Baton Rouge, Louisiana. To Lyon this was the South arming itself on Union soil. He is said to have scouted the camp personally while disguised as an old blind woman riding through it in a carriage, veiled and in skirts, taking a slow careful count of captured Confederate guns while the militiamen never gave him a second look. The sources hand the disguise story down with the caveat that it may be too good to be true. On May 10, 1861, he surrounded Camp Jackson with 6,500 troops and forced its 700-man garrison to surrender without a shot fired.' },
      { p: 'The shooting came afterward, and it came in the streets. As Lyon\'s men marched the captured militiamen back through St. Louis, hostile crowds gathered along the route, jeering and pressing in. A drunk man fired into the Union ranks and mortally wounded a soldier, and Lyon\'s troops opened fire on the crowd. When it was over, at least 28 civilians were dead and close to a hundred wounded, with more violence and six more deaths spilling into the next day.' },
      { p: 'The violence did exactly what Jackson needed it to do. Up to that morning, most Missourians had wanted no part of the war; they had voted, through their convention, to stay neutral. Lyon\'s armed seizure of the camp and the dead in the St. Louis streets handed the secessionists a grievance, and thousands of previously neutral Missourians (men who had opposed leaving the Union so long as nobody coerced the South or touched slavery) now had a reason to hate the federal army instead. Camp Jackson gave the Confederate cause in Missouri more recruits than a dozen speeches would have. A rattled legislature handed Governor Jackson near-dictatorial powers, and Jackson handed the reorganized Missouri State Guard, the South\'s homegrown Missouri army raised expressly to override the convention\'s vote and force the state into the Confederacy, to a veteran of the 1846 war with Mexico and former governor named Major General Sterling Price (South). The lines were now drawn, and they were drawn in blood.' },
      { h: 'A peace meeting in a hotel', eyebrow: 'The Planters\' House' },
      { p: 'A month later, on June 11, 1861, the two sides sat down to talk it out at the Planter\'s House Hotel in St. Louis. Governor Jackson and General Price came for the secessionist side; Lyon, now promoted to brigadier general, came with his political partner, the congressman Frank Blair Jr. (North). They talked for four or five hours. Jackson\'s offer was a kind of armed truce: both sides would disarm, and Missouri would stay neutral, taking no part in the war. Lyon would not have it. In Lyon\'s reading, accepting neutrality meant treating Missouri\'s government as an equal party negotiating with the United States over whether the two would be at war, and a state government that could bargain with the federal government as an equal had already won the very argument the South was making. That was the one thing Lyon would never grant.' },
      { p: 'So he ended the meeting by declaring war. The exact words he used have come down to us in two different versions, both written years later by men who took opposite sides, and no document from the day itself records what he actually said. One version, from a Confederate aide writing in 1886, has Lyon vowing he would rather see every man, woman, and child in Missouri "dead and buried" than concede the smallest point to the state, and finishing with the line history remembers: *"This means war."* A Union version from 1866 phrases it differently. The flourish is contested; the substance is not. Lyon stood up, told Jackson and Price they were now enemies, and sent them out the door.' },
      { p: 'And then he walked out of that hotel, a brigadier general not three weeks in the rank, having just declared, on no authority but his own, that his country was at war with the government of one of its own states. Washington had not decided it. Lincoln had not ordered it. Lyon had decided it, in a hotel parlor, and walked out into the street with the decision made. It was the decision of a man at the end of his rope who had decided to swing rather than fall. Jackson and Price took him at his word, and on their way out of the capital, Jackson\'s men burned the Osage River railroad bridge behind them.' },
      { p: '"Rather than concede to the state of Missouri the right to dictate to my government in any matter however unimportant, I would see you, and you, and you, and you, and you, and every man, woman, and child in the state dead and buried. This means war." As remembered by a Confederate aide writing in 1886; the exact wording is disputed, but the ultimatum was real.', q: true },
      { h: 'Run them into the corner', eyebrow: 'The chase' },
      { p: 'What followed was Lyon doing the thing he did best: moving fast and hitting hard. He loaded troops onto steamboats and ran them about 145 miles up the Missouri River to seize Jefferson City, the state capital, locking it down for the Union. Then he chased and scattered Jackson\'s forces at Boonville on June 17, running a sitting governor and his armed followers, the men who claimed to be the rightful government of Missouri, clean off the capital ground of the state they claimed to govern. He also sent a column under Colonel Franz Sigel (North) by rail to the railhead at Rolla to cut off the retreating secessionists, though Sigel ran into a larger force and got bloodied in a fighting retreat at Carthage on July 5, an early taste of what his impetuousness would cost him six weeks later. Through it all, Lyon kept pushing the secessionist government into the far southwestern corner of Missouri. By mid-July he had roughly 7,000 men gathered at Springfield, in the Ozark hill country, and he had effectively chased Missouri\'s rebel government out of Missouri proper.' },
      { fig: '/war-img/wilsons-creek-campaign.png', cap: "Lyon’s summer chase across Missouri: up the Missouri River through Jefferson City and Boonville, then southwest to Springfield; Sigel’s column came down through Carthage, while McCulloch’s Confederates marched up from Arkansas to Wilson’s Creek.", credit: 'Stuff Happened map' },
      { h: 'Attack, or admit you\'ve lost', eyebrow: 'End of the tether' },
      { p: 'Then the math caught up with him. While Lyon chased, the South gathered. Price\'s Missouri State Guard joined with about 5,000 Confederate and Arkansas troops marching up from northwestern Arkansas under Brigadier General Benjamin McCulloch (South), the first Confederate move onto Union ground west of the Mississippi. Combined, they became the Western Army, somewhere around 12,000 strong, and they planted themselves about 10 miles (16 km) southwest of Springfield along a creek called Wilson\'s Creek. Lyon now faced a force roughly twice his size. His supplies had dwindled to half and quarter rations. His short-term volunteers (men who had signed on for ninety days) were weeks from the end of their enlistments and entitled to go home. And his own superior, the general commanding the whole western region, John C. Frémont (North), refused to send him reinforcements and told him to retreat.' },
      { p: 'Retreat meant abandoning Springfield, and abandoning Springfield meant abandoning everything Lyon had spent the summer seizing, handing southwestern Missouri back to the men he\'d just chased out of it. Lyon would not do it. He decided instead to do the most aggressive thing a heavily outnumbered general can do: he would attack the bigger army first, to hurt it badly enough that he could withdraw in safety, or, if it broke, break it for good.' },
      { fig: '/war-img/wilsons-creek-plan.png', cap: "Lyon's gamble: outnumbered nearly two to one outside Springfield, he splits his army and sends his own column down the Wire Road while Sigel loops wide south, both striking the Confederate camp at dawn from opposite ends.", credit: 'Stuff Happened map' },
    ],
    meanwhile: { region: 'Missouri', title: 'A state with two governments forming', body: 'By the late summer of 1861, Missouri was tearing itself into two countries that happened to occupy the same ground. A Unionist provisional government held the capital and the legal machinery of the state; meanwhile Governor Jackson\'s secessionist faction, chased into the southwest and traveling with Price\'s army, claimed to be the real government of Missouri and was angling for admission into the Confederacy. What Price\'s State Guard was marching to do, what the battle along Wilson\'s Creek was for, was to flip a state that had already voted to stay, and to deliver it, slavery and all, into a confederacy built to protect slavery. The answer would shape four years of the ugliest fighting in the war.' },
  },

  'bloody-hill': {
    eyebrow: "Wilson's Creek · Dawn, August 10",
    title: 'Bloody Hill',
    blocks: [
      { p: 'Lyon\'s plan was the kind of plan you only make when you\'ve run out of safe ones. His army was already badly outnumbered, roughly 5,400 men against something like 12,000. The textbook answer to being outnumbered is to keep your force together, where its weight counts for the most. Lyon did the opposite. He split his already-tiny army in two and sent the halves on an all-night march to hit the sprawling Confederate camp from two directions at once at dawn. It was audacious, it was reckless, and for a few hours on the morning of August 10, 1861, it very nearly worked.' },
      { fig: '/war-img/wilsons-creek.png', cap: "Lyon's two-pronged dawn attack: his main column of ~4,200 driving from the northeast while Sigel looped south with ~1,100 to strike the Confederate camp from both ends at once, the gamble that opened the fight for Bloody Hill.", credit: 'Stuff Happened map' },
      { h: 'Split the small army in two', eyebrow: 'The plan' },
      { p: 'His own main column, about 4,200 men, would come down on the Confederate camp from the north at first light. At the same time, Col. Franz Sigel (North) would take a flanking column of roughly 1,100 to 1,200 men (a flank being the side of an enemy formation, the vulnerable spot away from where it\'s facing) and swing on a wide loop all the way around the Confederate position to strike it from the south. If both blows landed at once at dawn, the Confederates would be caught between two fires and unable to turn their full weight on either column. The plan was actually Sigel\'s idea, not Lyon\'s, and other officers objected to dividing a force this small in front of an enemy this large. Lyon took it anyway, partly because Sigel was a popular German-born officer whose standing made him politically awkward to overrule.' },
      { p: 'The whole gamble depended on surprise and on timing, both columns moving through the dark and hitting together. And it depended on a piece of luck nobody could have planned: the Confederates had drawn up their own surprise attack on the Union camp for the night of August 9 and called it off because of a light rain. Both armies, it turned out, had been planning to ambush each other on the very same night. Only one of them actually went.' },
      { h: 'Out of the dark', eyebrow: 'The surprise' },
      { p: 'Before dawn on August 10, Lyon\'s column came out of the dark and ran straight over the Confederate pickets and cavalry, who had no idea an army was on top of them. A quirk of the terrain (the steep creek valley seems to have swallowed the sound) kept McCulloch (South) and Price (South) from hearing the opening gunfire for as much as half an hour; the two generals were reportedly still at breakfast when word finally reached them. When their scouts did come in, they breathlessly reported the Federals were attacking with "twenty thousand men and 100 pieces of artillery," a wildly inflated number that briefly threw the Confederate command into confusion. Meanwhile Lyon drove the rebel cavalry back and pushed his men uphill onto a low, brush-covered plateau on the east bank of the creek, high ground that rose maybe a hundred feet above the valley floor and had no name yet. The soldiers who fought and died on it that morning would give it one: Bloody Hill. The artillery battery of Captain James Totten (North), a battery being a cluster of cannon worked as a single unit, unlimbered (unhooked the guns from their horse teams and set them up to fire) and opened on the camp below, setting tents ablaze and throwing Price\'s men into disarray. For a moment, the audacious plan looked like genius.' },
      { h: 'How Sigel\'s column came apart', eyebrow: 'The gray-uniform catastrophe' },
      { p: 'Down on the south end, Sigel\'s half of the plan opened even better than Lyon\'s. His guns caught the southern edge of the Confederate camp at the Sharp farm and shredded it; his artillery scattered the Southern cavalry and camp followers, sending hundreds of horsemen fleeing, and his men scooped up over a hundred prisoners in the first minutes. Sigel pushed up onto the Wire Road, the main road linking Springfield to Fort Smith, Arkansas, planting his column squarely across the Confederate line of supply. He believed the plan was working. He was so sure of it that he stopped being careful. He failed to post proper skirmishers (soldiers thrown out ahead of the main line to scout it and watch for an approaching enemy) out front to screen his line, and he made no attempt to link up with Lyon.' },
      { p: 'That carelessness met the worst possible enemy: the uniforms hadn\'t been sorted out yet. This was the rawest period of the war, before blue-for-Union and gray-for-Confederate was anything like universal, and regiments (a regiment being a fighting unit of roughly a thousand men) wore whatever their states had managed to dress them in. So when a body of gray-clad soldiers came marching toward Sigel\'s line, his men assumed they were friends, specifically the 1st Iowa Infantry, a Union regiment that happened to wear gray, and held their fire. They were not the 1st Iowa. They were the 3rd Louisiana Infantry (South), Confederate troops who also happened to be in gray, part of a counterattack McCulloch had organized once he grasped what Sigel had done. The Louisianans walked to within about 40 yards (37 m) of Sigel\'s trusting line and then let loose a single annihilating volley straight into it. Sigel\'s column shattered and ran. He lost five of his six cannon. The colonel himself escaped capture only by hiding in a cornfield and slipping back toward Springfield with a single orderly (a personal aide). One mistaken glance at a gray coat had erased half of Lyon\'s army from the battle.' },
      { fig: '/war-img/wilsons-creek-sigel.png', cap: "The gray-coat catastrophe at the Sharp farm: McCulloch's counterattack catches Sigel's flanking column, a single volley at forty yards shatters it, and the survivors flee down the Wire Road.", credit: 'Stuff Happened map' },
      { h: 'Wave after wave', eyebrow: 'The hill that earned its name' },
      { p: 'With Sigel routed and gone, the Confederates could turn their whole weight on Lyon alone on Bloody Hill, and they did, in three great surging assaults up the slope. Price organized his State Guard along the south face of the hill, and the battle became a brutal uphill grind: Missourians climbing into the muzzles of Lyon\'s line, formations three and four ranks deep firing while prone, kneeling, and standing all at once, the fighting closing to shotgun range and at one point to within twenty feet of the Union cannon. Price himself took a painful wound in the side during the fighting and stayed in the saddle. A Pulaski Arkansas battery had set up its cannon near the creek ford at first light and bought Price the time he needed to get organized, then traded blows with Totten\'s guns in a duel so thick with smoke that, as the Arkansas battery\'s commander, Captain William E. Woodruff Jr. (South), put it, his gunners could only aim by the enemy\'s muzzle-flashes.' },
      { p: '"The gunners of my pieces were obliged to give direction to their pieces by the flash." Capt. William E. Woodruff Jr., commanding the Pulaski Arkansas battery.', q: true },
      { p: 'For all their numbers, the Confederates could not break the hill. A Texas cavalry unit even tried a circuitous charge around to strike the Union position from behind, and it too was thrown back. And part of the reason the larger army kept failing was that its two halves never quite became one army. McCulloch held a Confederate commission; Price held only a Missouri State Guard commission and was, technically, an allied commander rather than a subordinate one. The two men had quarreled for a month before agreeing to fight together at all, and the friction never went away; McCulloch at times maneuvered his Confederate troops on his own rather than in lockstep with Price\'s Missourians.' },
      { p: 'Lyon had split his army on purpose and was outnumbered two to one; his enemy had twice his men and split itself by accident.', i: true },
    ],
    meanwhile: { region: 'the Confederate camp', title: 'A two-headed command', body: 'The Western Army that fought at Wilson\'s Creek was never really one army with one commander. It was Sterling Price\'s Missouri State Guard and Ben McCulloch\'s Confederate and Arkansas troops, lashed together by a late-July agreement that put McCulloch nominally on top while leaving Price\'s men formally outside his chain of command. The two generals had argued their way through the whole month before the battle and would argue their way through the fight itself, over tactics, over command, over who outranked whom. It was the original sin of the Confederate war west of the Mississippi: divided command between proud men who couldn\'t quite take orders from each other, a flaw that would haunt the rebel cause in this theater long after Wilson\'s Creek was over. And the thing Price was marching north to do once the shooting stopped was not some abstract "hold Missouri." It was to overturn the state\'s own democratic vote to stay in the Union and hand it to the Confederacy.' },
  },

  'death-of-lyon': {
    eyebrow: "Wilson's Creek · The cost & Missouri's fate",
    title: 'The Death of Lyon',
    blocks: [
      { p: 'By mid-morning on August 10, Brig. Gen. Nathaniel Lyon (North) had already given more to the battle than most men give in a war. He had been shot in the leg and grazed across the head, and his horse had been killed under him. One observer remembered him as masked in blood from his earlier wounds. He had ridden the whole length of his line all morning, in his old captain\'s coat rather than a general\'s uniform, rallying men who were fighting two-to-one odds on a hill that was filling up with the dead. And the Union center was starting to waver. So Lyon did the only thing he knew how to do. He got on another horse and rode to the front to lead a counterattack in person.' },
      { h: 'A general at the head of the charge', eyebrow: 'The first to fall' },
      { p: 'Sometime around half past nine or ten o\'clock in the morning, Lyon put himself at the head of a charge (the 2nd Kansas Infantry, with the 1st Iowa alongside by some accounts) aimed at the weakening Union center, and waved his men forward, still in that worn captain\'s coat. He is remembered to have called out as he went, "Come on, my brave boys, I will lead you! Forward!", words that appear on the marker at the site and have been repeated in account after account, though they come down to us as a remembered, reported line rather than anything written at the time. Moments later a bullet struck him in the chest, through the heart, and he died almost at once. Nathaniel Lyon became the first Union general to be killed in combat in the Civil War, dead on a Missouri hill in the war\'s first summer. His body was later carried to the farmhouse of a local family named Ray, just off the Wire Road, where it was laid out on the family bed, while in the rooms around it the same house was doing service as a field hospital for wounded Southern soldiers, the dead Union commander and the bleeding men he had been killing laid out under one roof.' },
      { p: 'The battle went on without him, the way battles do. The man who had started Missouri\'s war on his own authority was gone before lunch, and the soldiers still on Bloody Hill now belonged to someone else, facing a very different problem than the one Lyon had set out to solve.' },
      { fig: '/war-img/wilsons-creek-fall-of-lyon.jpg', cap: 'The death of General Lyon on Bloody Hill, the first Union general killed in the war, cut down leading a counterattack in his old captain\'s coat as the Union center wavered.', credit: 'Lithograph · public domain' },
      { h: 'Pulling the army out', eyebrow: 'The withdrawal' },
      { p: 'Command passed to Major Samuel D. Sturgis (North), and Sturgis inherited a wreck. His commanding general was dead, Sigel\'s column had been destroyed and scattered hours earlier, his men were exhausted, and they were running low on ammunition. He reorganized the line, beat back one more Confederate assault, and then made the only sane call available: he ordered a withdrawal. Around half past eleven that morning the Union army began pulling off Bloody Hill, and it did so in good order, falling back in formation, with the cavalry of Colonel Gordon Granger (North) covering the column\'s flank. They reached Springfield by about five that afternoon and, the next day, began the long retreat to Rolla, the railhead a hundred-odd miles to the east-northeast that was their supply base. The Confederates, for their part, did not chase. They were too spent and too low on ammunition to follow. As the Arkansas commander Brigadier General Nicholas Bartlett Pearce (South) put it, watching the blue column go: "We watched the retreating enemy through our field-glasses, and were glad to see him go."' },
      { p: '"We watched the retreating enemy through our field-glasses, and were glad to see him go." Brig. Gen. Nicholas Bartlett Pearce, on watching the Union army withdraw.', q: true },
      { fig: '/war-img/wilsons-creek-withdrawal.png', cap: "With Lyon dead, Major Sturgis pulls the Union army off Bloody Hill and retreats northeast through Springfield to the railhead at Rolla; the victors then split, Price marching north into Missouri and McCulloch taking his Confederates back to Arkansas.", credit: 'Stuff Happened map' },
      { h: 'A small battle\'s terrible rate', eyebrow: 'The cost' },
      { p: 'Count the bodies and the smallness of these armies is what hits you. The casualty figures vary across reputable sources by a couple hundred (the most commonly cited academic numbers put Union losses around 1,317 and Confederate around 1,222, while the American Battlefield Trust gives somewhat lower figures, roughly 1,235 Union and 1,095 Confederate), but the totals are not really the story. The story is the rate. Lyon lost something like a quarter of every man he brought to the field, roughly 24 to 25 percent. The Confederates, despite winning, lost about 12 percent of theirs. For armies this size, those are appalling numbers; Wilson\'s Creek ranked among the bloodiest battles in American history up to that point, measured by the share of men it chewed up. The 1st Kansas Infantry alone suffered one of the heaviest single-battle tolls of any Union regiment in the entire war. This was a small battle in a far corner of the country, and it bled like a great one.' },
      { h: 'An empty win', eyebrow: 'The victory they couldn\'t spend' },
      { p: 'The cruel irony at the center of Wilson\'s Creek is that the South won the battle and could do almost nothing with it. It was a clear tactical victory: they held the field, they killed the enemy commander, they drove the Union army off the hill and out of Springfield. But McCulloch refused to pursue, pleading exhaustion, empty cartridge boxes, and worry about his supply line back to Arkansas. And the moment the fighting stopped, the two-headed command that had hampered the battle finished the job of wrecking the campaign. Price wanted to march north toward the Missouri River and the heart of the state; McCulloch wanted to stay and hold the southwestern corner. They could not agree, so the coalition simply came apart: McCulloch took his Confederates back to Arkansas, and Price marched his Missourians north alone. Price\'s lone march did score one more triumph, the capture of the Union garrison at Lexington in September, but his new recruits had no logistics behind them and roughly two-thirds of them melted away when the Union pushed back. A battle won, and nothing won by it.' },
      { h: 'The Union holds, the guerrilla war begins', eyebrow: "Missouri's fate" },
      { p: 'And in the end, the great prize, Missouri itself, slipped through the Confederacy\'s fingers even in victory. The Unionist provisional government kept its grip on the capital and the legal machinery of the state, and Missouri never actually left the Union. But Wilson\'s Creek did not settle the question so much as split it in two. That October, secessionist Missouri legislators met at Neosho and voted to officially leave the United States, and on November 28, 1861, the Confederacy formally recognized Missouri as a Confederate state, giving the state two rival governments at once for the rest of the war, each claiming to be the real one.' },
      { p: 'And so a state with two governments and a population genuinely divided over which country Missouri belonged to became the center of the most vicious irregular fighting of the entire war. Bushwhackers and jayhawkers (homegrown partisan raiders, the bushwhackers fighting for the Confederacy and the jayhawkers for the Union) turned Missouri into a landscape of ambushes, burned farms, and neighbor murdering neighbor for years, well into Reconstruction (the years after the war when the federal government tried to rebuild the South). It was not a tidy, symmetrical feud. Both sides committed atrocities, but the pro-Confederate bushwhackers were fighting, specifically, to keep slavery in place, terrorizing Unionist families, free and enslaved Black Missourians, and Free State settlers to do it. Wilson\'s Creek was the opening shot of three and a half years of guerrilla war that would make Missouri the third most-fought-over state in the conflict. The organized Confederate threat in the region was finally broken at Pea Ridge, Arkansas, in March 1862, where McCulloch, the general who had refused to chase Lyon\'s beaten army off Bloody Hill, was himself killed, but the bushwhacking went on long after the armies left. The first major battle west of the Mississippi had earned its nickname, the Bull Run of the West, and it had previewed the whole character of the war west of the Mississippi to come: divided commands, victories no one could exploit, and a state set savagely against itself.' },
      { p: 'The monuments tend to leave out one thing about Lyon. The North made him a martyr, the first Union general to fall, the man credited with saving Missouri, and in the simplest accounting he did win the thing he died for: Missouri stayed in the Union. But historians have never fully agreed on the verdict. The same aggression that made Lyon effective at Camp Jackson also drove thousands of neutral Missourians into the secessionist camp and helped ignite the very guerrilla war that then tore the state apart for years. Some judge that Lyon saved Missouri; others that he made its war far nastier than it had to be. The honest answer is that he may have done both at once.' },
      { p: 'Lyon lost the battle, lost his life, and won the prize he\'d died for, and may have lit the fire that burned Missouri for years doing it.', i: true },
    ],
    meanwhile: { region: 'Missouri', title: 'The guerrilla war coming', body: 'The armies marched away from Wilson\'s Creek, but for Missouri the war was just changing shape into something worse. With a Unionist government in the capital and a secessionist government claiming the same state, and with families and whole counties split between the two, the fight dropped down to the level of the farm and the country road. Bands of bushwhackers and jayhawkers rode the back roads settling scores under cover of the war, and the regular armies could never fully stamp them out. The savage, merciless partisan fighting that defined Missouri for the rest of the war (and bred some of the country\'s most infamous outlaws in its aftermath) began here, in the bloody summer that Wilson\'s Creek opened.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={WILSONS_CREEK_NARR} id={id} slug="wilsons-creek" battleName="Wilson's Creek" theatreId="tmis" theatreHref="/war-civil-war/trans-mississippi" battleId="t-wilsonscreek" accent="#d97706" />
}
