'use client'

// Chancellorsville — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise → integrate. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const CHANCELLORSVILLE_NARR: Record<string, Narr> = {
  'the-plan': {
    eyebrow: 'Chancellorsville · Hooker’s great gamble',
    title: 'The Finest Army on the Planet',
    blocks: [
      { p: 'In the spring of 1863, the Army of the Potomac had a new commander, a fresh plan, and a swagger it had not earned in a long time. Major General Joseph Hooker (North) had taken over the largest army on the continent after a winter of disasters, rebuilt its morale, and now intended to do what none of his predecessors had managed: catch Robert E. Lee and his Army of Northern Virginia out in the open and crush them. He had the men to do it. By the best estimates Hooker fielded somewhere around 130,000 soldiers against Lee’s roughly 60,000, better than two to one, though exact engaged counts differ by source. Hooker is said to have called it the finest army on the planet, and on paper it was hard to argue.' },
      { p: 'The plan was genuinely excellent. Lee was dug in along the Rappahannock River (the broad east-west river line that the town of Fredericksburg sits on, where a Union army had been slaughtered head-on the previous December). Hooker had no intention of repeating that. Instead of hammering the front door, he would slip around the side, around the flank (the end of Lee’s line, where an army is weakest because it cannot easily turn to face a blow from the side). He sent three entire corps (a corps being one of the big self-contained chunks an army is built from, here anywhere from 10,000 to 30,000 men, several of which together make up the whole army) on a wide swing: cross both rivers far upstream to the west and come down behind Lee’s left, into the rear of his position. Meanwhile Major General John Sedgwick (North) would stay below Fredericksburg with the VI Corps and mount what soldiers call a demonstration, a loud, faked threat meant to look like the real attack, pinning Lee in place and convincing him the blow was still coming where it had come before.' },
      { pill: '/war-civil-war/eastern/fredericksburg', plabel: 'Fredericksburg: the head-on slaughter Hooker meant never to repeat' },
      { fig: '/war-img/chancellorsville-overview.png', cap: 'Hooker’s turning march: three corps swing far upstream and come down behind Lee at the Chancellorsville crossroads while Sedgwick demonstrates below Fredericksburg.', credit: 'Stuff Happened map' },
      { p: 'There was a third arm to the plan, and it mattered most by its absence. While the infantry swung around Lee’s flank, Hooker sent his entire cavalry corps, around 10,000 horsemen under Major General George Stoneman (North), on a deep raid far to the south, to get between Lee and the Confederate capital at Richmond and tear up the railroad at Gordonsville that fed Lee’s army. The idea was to panic Lee into retreating to protect his supply line, straight into Hooker’s waiting infantry. It went nowhere, and worse than nowhere: the raiders wrecked a little track, accomplished nothing that lasted, and meanwhile the army they had ridden away from was left with almost no cavalry of its own to scout and screen. An army without its horsemen is an army that cannot see. Hooker had sent away his eyes.' },
      { h: 'Lee Caught Between Two Fires', eyebrow: 'April 30' },
      { p: 'It worked, at first. By April 30 the flanking column had gathered at a place called Chancellorsville, not a town but a single large brick house at a road junction in the woods, owned by the Chancellor family. Hooker now had a powerful army planted squarely behind Lee’s position, with Sedgwick’s force still threatening the front. Lee was caught between two fires, enemies on two sides at once, outnumbered everywhere, on ground of Hooker’s choosing. In General Orders No. 47 on April 30, Hooker told the army that the enemy must now "ingloriously fly, or come out from behind his defences… where certain destruction awaits him." For about one day, the boast looked justified.' },
      { p: 'What Hooker had not reckoned with was the ground itself. The Chancellorsville crossroads sits in the middle of the Wilderness of Spotsylvania, a dense, tangled second-growth scrub forest grown up over abandoned charcoal and iron furnaces. It was the kind of country that swallows artillery (the heavy cannons that win battles in the open) and breaks up any large body of men trying to maneuver through it, the kind of country where you cannot see fifty yards and cannot bring your numbers to bear. Hooker’s two-to-one advantage was only an advantage in the open. In the Wilderness, the woods were about to do the work of an extra Confederate corps.' },
      { p: 'Hooker’s turning march was one of the best-conceived operations the Army of the Potomac ever attempted, and it set the table for the army’s most humiliating defeat, because it marched the bigger army into a forest that erased the very edge the plan was built to exploit.', i: true },
    ],
    meanwhile: { region: 'the war’s new stakes', title: 'The war had changed under their feet', body: 'The war this army was fighting had changed under its feet. Four months earlier, on January 1, 1863, the Emancipation Proclamation had taken effect, declaring enslaved people in the rebelling states free and binding the Union war effort, openly and on the record, to the destruction of slavery. The men marching toward Chancellorsville were no longer fighting only to hold the country together. They were fighting to end the thing the Confederacy had been built to protect. That was now the stake on the table, whatever any soldier in the ranks thought of it.' },
  },

  'lee-divides': {
    eyebrow: 'Chancellorsville · The audacity of the outnumbered',
    title: 'Splitting an Army That Was Already Too Small',
    blocks: [
      { p: 'Here is the situation Robert E. Lee woke up to on the first of May: a Union army of perhaps 130,000 men had gotten behind him, a second Union force was pressing his front at Fredericksburg, and his own army numbered around 60,000 all told. The textbook answer to being outnumbered two to one, with enemies on two sides, is to retreat and save the army. Lee did the opposite, twice, in a way that has been studied by soldiers ever since as either reckless or perfect, and possibly both.' },
      { p: 'The first thing that saved him was that Major General Joseph Hooker (North) flinched. On May 1, Union columns pushed east out of the Wilderness toward the open ground where their numbers and their guns would finally count. Lee’s lead elements, with Lieutenant General Thomas "Stonewall" Jackson driving them forward, met that advance and pushed back. The fighting was sharp but not decisive, and by every measure Hooker still held the advantage. Then Hooker ordered his men to stop and pull back into the Wilderness, surrendering the open ground he had marched all that way to reach. Major General Darius Couch (North), his senior subordinate, came away from that order shaken; he later wrote that he left Hooker’s presence "with the belief that my commanding general was a whipped man." The battle had been fought for one afternoon, and already the psychology had flipped: the bigger army was digging in to defend, and the smaller army was coming on.' },
      { p: 'With Hooker hunkered down, Lee did the first audacious thing. He split his army in front of a superior enemy. He left a small holding force of somewhere between 9,000 and 11,000 men under Major General Jubal Early (South) to watch Fredericksburg and hold off Sedgwick, and took everyone else west to deal with Hooker. That alone would have been bold. What he and Jackson decided to do next was, by the standards of military prudence, close to insane.' },
      { h: 'A Flank Hanging in the Air', eyebrow: 'The night of May 1' },
      { p: 'What made it possible was a piece of intelligence that arrived that night. Major General J.E.B. "Jeb" Stuart (South), Lee’s cavalry chief, rode in with a report from his scouts under Brigadier General Fitzhugh Lee (South), Robert E. Lee’s own nephew, who had ridden out along the Union line and found its far western end hanging open. Hooker’s right flank, out past the XI Corps, was unanchored: it leaned on no river, no hill, no obstacle of any kind, the soldier’s nightmare condition called being "in the air," a flank with nothing to lean on and nothing to stop an enemy from getting around the end of it. Lee and Jackson did not intuit the weak spot. Their cavalry found it for them, and handed them the whole battle.' },
      { p: 'That night, the two men sat on cracker boxes by a fire in the woods and worked out a plan to split the army again. If a force could march clear around the Union army through the concealing Wilderness and come in on that exposed flank from the side, it could roll the whole line up like a carpet. The catch was the size of the force required and the distance it would have to travel. Jackson proposed taking his entire Second Corps, around 28,000 to 30,000 men, on a march of roughly twelve miles around the Union army’s front.' },
      { p: 'The arithmetic is staggering. Lee was already outnumbered better than two to one. He had just peeled off a third of what remained to hold Fredericksburg. Now he proposed to send the larger part of what was left on a half-day march around the enemy, leaving himself with perhaps 14,000 men directly in front of Hooker’s 70,000-odd. If Hooker attacked the thin force in front of him during those hours, Lee’s army would simply cease to exist.', i: true },
      { p: 'The road existed because the country knew it and the army did not. Jackson’s mapmaker, Jedediah Hotchkiss (South), the topographer whose careful maps were one of the Confederacy’s quiet advantages, was shown a concealed route by Charles C. Wellford, the proprietor of an iron furnace called Catharine Furnace south of the crossroads, who knew the local roads the way only a man who hauls iron over them can. That hidden road, looping south and west out of sight of the Union lines, was the whole plan. Without it there is no flank march and no surprise. Lee bet his army on a furnace owner’s knowledge of his own back roads.' },
      { p: 'Lee chose, twice in two days, the single riskiest option available to a general: dividing his force in the face of a stronger enemy, the textbook recipe for being beaten in detail (destroyed one piece at a time). He got away with it twice in forty-eight hours, partly because his subordinates were good enough to execute it, and largely because the man across the field had already decided he was beaten.', i: true },
    ],
    meanwhile: { region: 'behind the audacity', title: 'What the brilliance was in service of', body: 'It is worth being plain about what this brilliant maneuver was in the service of. The Army of Northern Virginia existed to defend the Confederacy, and the Confederacy existed to preserve a society built on the enslavement of Black people. The army that marched those twelve miles through the Wilderness ran, at the front and behind it, on enslaved labor: cooks, teamsters, blacksmiths, hospital hands, and officers’ body servants, men held in bondage who shadowed the columns and dug the works. Lee’s generalship at Chancellorsville was extraordinary. The cause it served was the ownership of human beings, and the victory it won was, within two months, the springboard for an invasion of the free North.' },
  },

  'the-flank-march': {
    eyebrow: 'Chancellorsville · Dusk on the Orange Turnpike',
    title: 'Jackson Comes Out of the Woods',
    blocks: [
      { p: 'At around seven or eight in the morning on May 2, Lieutenant General Thomas "Stonewall" Jackson put his Second Corps on the road, and for most of the day the most dangerous column in the Confederacy more or less disappeared. Twenty-eight to thirty thousand men, with their guns and wagons, threaded south and then west along Wellford’s hidden road, past Catharine Furnace, through woods thick enough to hide an army from an enemy a few miles away. It was slow, exposed work. A march like that has no good answer if it is caught strung out on a forest track, and for hours it was strung out on a forest track. The one force that should have caught it, Union cavalry ranging ahead to scout the woods, was hundreds of miles south on Stoneman’s raid. Hooker had sent his eyes away, and now a Confederate army was crossing his front and almost no one was watching the ground.' },
      { p: 'It was very nearly caught anyway. Major General Daniel Sickles (North), whose III Corps held high ground at a place called Hazel Grove, spotted the column moving across his front and sent troops to probe at Catharine Furnace. For a moment the whole plan teetered. But the 23rd Georgia (South), thrown out as a rear guard, fought a delaying action that bought Jackson the time he needed, and the moment passed. Worse, Major General Joseph Hooker (North) read the moving column exactly backward. A long gray line trailing south and west out of his front looked, to a commander who had already convinced himself Lee was beaten, like a Confederate army in retreat. Hooker chose to believe Lee was running. Lee was not running. Lee was reaching around his neck.' },
      { fig: '/war-img/chancellorsville-flank.png', cap: 'Jackson’s twelve-mile loop south past Catharine Furnace, screened by the Wilderness, then north into the open western end of Howard’s XI Corps along the Orange Turnpike.', credit: 'Stuff Happened map' },
      { h: 'A Corps Facing the Wrong Way', eyebrow: 'Dusk, May 2' },
      { p: 'What was waiting at the end of that march was the XI Corps under Major General Oliver O. Howard (North), and it was waiting the wrong way. Howard’s men held the far western end of the Union line, the flank that hung in the air, and they were facing south, toward where the trouble was supposed to come from, with their right end open to the west and unprotected. They were not entrenched. As the long spring evening came on, around 5:30, they were cooking supper, stacking arms, settling in. They had been warned that something was moving out beyond their flank, and the warnings had been waved off up the chain as the nervousness of green troops (new soldiers who jump at shadows). Most of the corps was made up of German-American regiments, immigrant soldiers the rest of the army half-dismissed as the "Dutch," and no one with the authority to bend the line back and face west had taken their reports seriously.' },
      { p: 'The first thing many of them saw was the wildlife. According to accounts, deer and rabbits and turkeys came bolting out of the western woods ahead of the line, driven from cover by the advance of an army the men had been told was not there. Then the trees themselves seemed to come apart, and out of them came Jackson’s corps at a dead run, the high keening rebel yell carrying ahead of a battle line a mile wide, hitting the open end of Howard’s corps from exactly the direction no one was facing.', i: true },
      { p: 'The division of Brigadier General Robert Rodes (South) led the assault and, in the words that have followed it ever since, rolled completely over the XI Corps. A line of unentrenched men, facing the wrong way, with their suppers half-cooked, was simply overrun from the side, where almost no one could even turn a weapon to meet the enemy. The corps came apart. Some units, Major General Carl Schurz’s (North) division among them, managed a stand in the chaos and made the Confederates pay for ground. Most of it dissolved into a stampede back toward the Chancellorsville crossroads. In a matter of minutes the XI Corps lost around 2,500 men, killed, wounded, and captured, and the Union right ceased to exist as a fighting line.' },
      { p: 'Jackson’s men drove forward through the wreckage, pushing roughly a mile and a quarter toward Chancellorsville before the dark and their own disorder (the inevitable tangle of a victorious assault in thick woods at night) finally brought them to a halt. The flank march had worked exactly as drawn on the cracker box. Lee had now cut his army into three pieces in front of a force twice his size: Early at Fredericksburg, Lee’s own sliver in front of Hooker, and Jackson’s corps swinging in from the west. The gamble had paid the biggest dividend of the war.' },
      { p: 'Jackson’s flank attack is the single most famous maneuver of the Civil War. The twelve-mile march should never have gone undetected, and went undetected because the ground hid it, the Union cavalry was gone, and the Union commander misread what was left in plain sight. It shattered an entire Union corps in under an hour.', i: true },
    ],
    meanwhile: { region: 'the scapegoats', title: 'The "Flying Dutchmen"', body: 'In the weeks after, the broken XI Corps was nailed to the wall by the rest of the army and the Northern press, mocked as the "Flying Dutchmen" for breaking and running. The label stuck, and it was unfair. These were largely German-American immigrant regiments who had been strung out on an unanchored flank, told to face the wrong direction, and denied reinforcement after their own lookouts reported the enemy massing. They lost roughly 2,500 men in minutes because of where they were placed, not because of who they were. The army needed someone to blame for the rout, and the immigrants were the easiest target.' },
  },

  'jackson-falls': {
    eyebrow: 'Chancellorsville · The cost of the masterpiece',
    title: 'Shot by His Own Men',
    blocks: [
      { p: 'It was Jackson’s own aggression that killed him, and the manner of it is one of the cruelest accidents in American military history. With the XI Corps shattered and night fallen, Lieutenant General Thomas "Stonewall" Jackson was not satisfied. He wanted to push on in the dark, to get between the broken Union army and its escape routes across the river and finish the job before morning. So he rode forward of his own lines on the Orange Plank Road with his staff, scouting the ground ahead for a night attack, out past the point where his own jumpy soldiers expected anyone friendly to be.' },
      { p: 'In the black confusion of the woods, his own men opened fire on him. The 18th North Carolina (South) heard horsemen coming back toward their line in the dark, took them for Union cavalry, and let go a volley. Three balls struck Jackson, shattering his left arm. He was carried off the field under fire, and the next day, May 3, surgeons amputated the arm. Robert E. Lee, when word reached him of the amputation, is said to have answered that Jackson had lost his left arm but the army had lost its right arm.' },
      { p: 'With Jackson down, command of the Second Corps fell to the most unlikely man on the field. Major General J.E.B. "Jeb" Stuart (South), Lee’s flamboyant cavalry chief, the plumed-hat scout whose horsemen had spent the war riding rings around Union armies, had never in his life commanded infantry in a pitched battle. He took over Jackson’s corps overnight and renewed the assault at first light on May 3, and he did it well, which was not at all guaranteed.' },
      { h: 'A Hilltop and a Blunder', eyebrow: 'May 3, morning' },
      { fig: '/war-img/chancellorsville-collapse.png', cap: 'May 3: Stuart’s renewed assault from the west, Confederate guns massed on Hazel Grove, the Union line collapsing inward on the crossroads while Sedgwick storms Marye’s Heights and is stopped at Salem Church.', credit: 'Stuff Happened map' },
      { p: 'May 3 was decided by a hilltop and a blunder. Hazel Grove was commanding high open ground southwest of the crossroads, one of the few places in all that forest where cannons could see and be massed, and Sickles’s (North) men held it. On the morning of the third, Major General Joseph Hooker (North) ordered Major General Daniel Sickles (North) off it to tighten his line. It was a gift, and the Confederates took it instantly: Colonel E. Porter Alexander (South), Lee’s gifted young artillerist, rushed thirty-odd guns up onto Hazel Grove and pounded the Union position to pieces, and by half past nine the whole Union line around Chancellorsville was buckling inward.' },
      { p: 'In the middle of that collapse, the Union army effectively lost its commander. Around 9:15 that morning, at almost the same minute Alexander’s guns were taking Hazel Grove, Hooker was standing on the porch of the Chancellor house, leaning against one of its pillars, when a Confederate cannonball struck the pillar and knocked him senseless, very likely a concussion. At the exact moment one army was seizing the high ground and pressing its advantage, the other army’s commander was being carried off his own porch, dazed and incapacitated for over an hour. Even half-conscious, Hooker refused to hand command over to his senior subordinate, Major General Darius Couch (North). The 130,000-man army was paralyzed at the top while its line came apart.' },
      { p: 'Lee won the field on May 3, and paid for it with the one subordinate he could not replace.', i: true },
      { p: 'The price of the night before was Stonewall Jackson, the most aggressive corps commander Lee had, the engine of the whole flank attack, now lying in a shattered ruin in a borrowed bed while Stuart finished the work he had started.' },
    ],
    meanwhile: { region: 'the other end of the field', title: 'Sedgwick breaks through', body: 'While Chancellorsville burned, the second Union force finally moved. On May 3, Sedgwick’s (North) VI Corps stormed Marye’s Heights above Fredericksburg, the same stone wall and sunken road that had butchered the Union attackers the previous December, drove Jubal Early (South) off it in the Second Battle of Fredericksburg, and pushed west toward Lee’s rear. For a few hours there was a real chance to catch Lee between two fires after all. Then, a few miles on, at a country meetinghouse called Salem Church, Maj. Gen. Lafayette McLaws’s (South) division, detached by Lee to plug exactly this hole, stopped Sedgwick cold. The pincer closed on nothing.' },
  },

  'hooker-quits': {
    eyebrow: 'Chancellorsville · A victory too expensive to keep',
    title: 'The General Loses His Nerve',
    blocks: [
      { p: 'What broke at Chancellorsville, in the end, was not the Union army. It was Major General Joseph Hooker’s (North) will to use it. He still had tens of thousands of men who had barely fired a shot. He still outnumbered Lee. But after the porch and the concussion and the collapse of his line, the fight had gone out of the man at the top, and an army cannot be braver than the general commanding it.' },
      { p: 'Lee was now the one dividing his attention. With Hooker passive and pulled back into a tight defensive horseshoe near the river, Lee turned part of his army around, away from Hooker, to deal with Major General John Sedgwick’s (North) breakthrough in his rear. He was fighting in two directions at once and winning in both, against a combined force more than twice his size, because the larger force had stopped believing it could win. Major General Lafayette McLaws (South) and the returning Major General Jubal Early (South) hemmed Sedgwick in at Salem Church, and on the night of May 4 into the 5th Sedgwick gave it up and pulled his corps back north across the Rappahannock over pontoon bridges (temporary floating bridges thrown across the river) at Banks’ Ford.' },
      { p: 'That left only Hooker, dug in with his back to the river, and on the night of May 5 into May 6 he quit. With Sedgwick repulsed and his own nerve gone, Hooker recrossed the Rappahannock to the north bank and ended the campaign. He had brought roughly twice Lee’s numbers across the rivers and behind the Confederate army, and he carried them back across beaten by an enemy he had outnumbered the entire time. It is, fairly, called Lee’s masterpiece, his perfect battle, by the historians who have studied it. Outnumbered two to one, he had divided his army twice, out-thought and out-nerved a larger and better-positioned foe, and sent it packing.' },
      { h: 'The Bill Behind the Masterpiece', eyebrow: 'The cost & the meaning' },
      { p: 'But the word masterpiece hides the bill. The casualty lists tell a darker story underneath the brilliance.', i: true },
      { p: 'The two armies between them lost somewhere around 30,000 men in roughly six days of fighting in tangled woods that hid the dead and trapped the wounded. The horror of that ground had its own signature: brush fires, set off by shellfire and musketry in the dry second-growth scrub, swept through the thickets, and wounded men of both sides who could not crawl clear were burned where they lay. In raw numbers the North lost more, around 17,300 to the South’s roughly 13,000. But measure each loss against the army it came out of, and the brilliance curdles: out of Hooker’s roughly 130,000, the North’s dead and wounded were about one in eight; out of Lee’s roughly 60,000, the South’s were better than one in five. Lee bled a far heavier share of a far smaller army. It was a victory his army could not really afford to keep winning.' },
      { p: 'One of the 13,000 was Jackson. He had been carried roughly twenty-seven miles south to an outbuilding on the Chandler plantation near Guinea Station to recover away from the front. There the wound did not kill him; pneumonia did. On May 10, 1863, eight days after his own men shot him in the dark, Stonewall Jackson died, thirty-nine years old. His reported last words were that they should cross over the river and rest under the shade of the trees.' },
      { p: 'That death reorganized both armies and the war. Lee, with no one who could fill Jackson’s shoes, broke his two corps into three and handed two of them to men who had never carried that weight, and at Gettysburg, eight weeks later, the new commanders would hesitate on the first evening exactly where Jackson would have pressed. On the other side, the defeat finished Hooker. Within weeks Lee was marching north into the free states, into the teeth of the new emancipation policy; Hooker quarreled with Washington over reinforcements, offered his resignation in a temper, and Lincoln took it. On June 28, 1863, three days before Gettysburg, Major General George G. Meade (North) was woken in the dark and told he now commanded the Army of the Potomac.' },
      { pill: '/war-civil-war/eastern/gettysburg', plabel: 'Gettysburg: the invasion that Chancellorsville launched, two months later' },
      { p: 'Confederate victory: Lee’s tactical masterpiece in the Wilderness, won by sheer audacity, and the most expensive win of his career. A fifth of his army was gone, Stonewall Jackson was dead, and the reorganized command would falter two months later at Gettysburg. The perfect battle was the launching pad for the campaign that broke the Confederacy in the East.', i: true },
    ],
    meanwhile: { region: 'what the victory marched toward', title: 'The road to Gettysburg', body: 'Buoyed by Chancellorsville, Lee turned his army north within weeks for a second invasion of the United States, the Gettysburg campaign of June and July 1863. The army that crossed into Pennsylvania did so shadowed by an estimated 6,000 to 10,000 enslaved people, serving as cooks, teamsters, blacksmiths, and body servants, who kept the Confederate war machine running, and who on free soil were at risk of liberation. Some Confederate units, on that same march, seized free Black Pennsylvanians and sent them south into slavery. The masterpiece in the Wilderness was the launching pad for all of it, and it ended, two months later, at Gettysburg.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={CHANCELLORSVILLE_NARR} id={id} slug="chancellorsville" battleName="Chancellorsville" theatreId="east" battleId="e-chancellorsville" />
}
