'use client'

// Malvern Hill — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

export const MALVERN_HILL_NARR: Record<string, Narr> = {
  'the-retreat': {
    eyebrow: 'Malvern Hill · The Hill Above the James',
    title: 'The Hill Above the James',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -78.2, lonMax: -76.4, latMin: 36.8, latMax: 38 },
        states: [
          { name: 'Virginia', tone: 'focus', label: 'VIRGINIA', labelLon: -78, labelLat: 36.9 },
          { name: 'Maryland' },
          { name: 'North Carolina' },
          { name: 'West Virginia' },
          { name: 'Pennsylvania' },
        ],
        dots: [
          { name: 'Malvern Hill', date: 'Jul 1, 1862', lat: 37.36, lon: -77.19, heavy: true, anchor: 'start' },
          { name: 'Harrison\'s Landing', lat: 37.3, lon: -77.07, color: '#8a8175', anchor: 'start' },
          { name: 'Richmond', lat: 37.54, lon: -77.44, color: '#8a8175', anchor: 'end' },
        ],
      } },







      { p: 'By the morning of July 1, 1862, Colonel Henry J. Hunt (North) had built a wall of iron on a hilltop in Virginia, and the army that had been running all week had finally stopped. Up on the crest of Malvern Hill, gun stood above gun, rank behind rank, all of them looking down one long, bare, gently sloping field, and the army backing up the hill had decided that here, at last, it would turn around and fight. (Throughout this story, North = the Union, the United States fighting to hold the country together; South = the Confederacy, the breakaway slaveholding republic. Officers on a side carry a (North) or (South) tag the first time they appear in each section.)' },
      { p: 'To understand why everyone had come to this hill, you have to back up a week. For seven days, Robert E. Lee had been hitting George B. McClellan, and for seven days McClellan had spent every day backing away. The great Union army (the United States’ main fighting force in the East) had come up the Virginia Peninsula (the finger of land between the York and James rivers) to take the Confederate capital at Richmond, and now it was in full retreat, marching south toward the one thing that felt safe: the James River, where the United States Navy’s gunboats (river warships carrying heavy cannon) waited to cover them. The navy’s guns could pound any Confederate pursuit from the water, shielding the army’s rear. The army was running, and the thing it was running from was the survival of a slaveholding republic. Richmond was the capital of a new country founded to keep four million people enslaved, and an entire campaign had been built to capture it and end the rebellion in a stroke. Now that campaign was collapsing backward toward the river, and Lee smelled a chance to finish it for good.' },
      { fig: '/war-img/malvern-hill-retreat.png', cap: 'The Seven Days’ end: McClellan retreats from Richmond to the James, with Malvern Hill the last high ground before Harrison’s Landing.', credit: 'Stuff Happened map' },
      { h: 'The Seven Days’ end', eyebrow: 'The Hill Above the James' },
      { p: 'The fighting that brought everyone here was called the Seven Days Battles (June 25 to July 1, 1862), and it was Lee’s offensive: six engagements in a row, launched to drive McClellan away from Richmond and save the Confederate capital. Mechanicsville, Gaines’s Mill, Savage’s Station, Glendale, the names piled up, all of them clashes Lee forced that week, and after Gaines’s Mill on June 27, McClellan made his decision. He would not fight his way into Richmond. He would withdraw his whole army (officially the Army of the Potomac, the Union’s main eastern force) south across the Peninsula and put his back against the James, where the gunboats could shield him. Lee chased the whole way, swinging at the retreating column, trying to cut it apart before it reached the water. At Glendale, on June 30, he nearly did, and missed.' },
      { pill: '/war-civil-war/eastern/gaines-mill', plabel: 'Gaines’s Mill: the victory that decided McClellan to retreat' },
      { p: 'By July 1, the Union rearguard (the troops assigned to cover a retreat so the rest of the army can pull back safely) had backed up onto Malvern Hill, and for the first time in the whole week, the entire Army of the Potomac stood united on one field. It was a good place to make a stand. Malvern Hill is a broad, flat-topped plateau, only about 100 feet above the country around it, but its strength was never really its height. Its strength was what it let you see and shoot. The north face, the side the Confederates would have to come up, was open, gently sloping farm field, with almost no cover for hundreds of yards, in places more than a mile. Any attacker had to walk uphill across that bare ground in full view the entire way. The James River lay just 1 to 2.5 miles (1.6 to 4 km) to the south, securing the Union rear. Boggy creeks, ravines, and dense woods guarded the flanks (the exposed sides of the army’s line). It was, in plain terms, a natural fortress, and the men in blue knew it.' },
      { p: 'What turned a strong position into a death trap was Hunt, the man already standing on the crest with his guns, the army’s chief of artillery (the officer in charge of the cannon). Artillery in this war meant cannon grouped into batteries, a battery being a cluster of roughly six guns that worked and moved together. Hunt’s job that day was to mass those batteries (to concentrate them so their combined fire overlapped on the same ground): to gather them side by side and tier on tier along the crest, gun above gun, all looking down the open northern slope. There is real confusion in the records about exactly how many cannon he had, since different counts measure different things, the forward line versus the reserve versus every piece on and behind the hill, but the totals run up toward 250 guns altogether, stacked across the high ground. Hunt also wedged a battery of heavy 32-pounder howitzers (short, big-bored cannon that lob a heavy shell) onto the right flank. Behind the hill, in close support, sat the army’s Artillery Reserve (a dedicated pool of fresh gun batteries held back to roll forward and replace any that ran low on ammunition). Down on the James, three Union gunboats, including the USS Galena, added their fire from the river. Hunt had built a wall of iron on the high ground, and he aimed all of it at the empty field below.' },
      { p: 'Lee had spent a week trying to destroy this army on the run. Now it had stopped running and turned to face him from the best ground it had found yet.', i: true },
    ],
    meanwhile: { region: 'Richmond', title: 'The capital they were fighting over', body: 'About ten miles north sat Richmond, the prize and the reason for all of it. A month earlier, Union soldiers had been close enough to the city to hear its church bells; civilians had packed wagons, the government had readied trains to flee, and the fall of the Confederate capital had seemed near. Lee’s whole offensive was built to push that danger back across the Peninsula, and as McClellan’s army backed toward the James, the bells of Richmond fell quiet with relief. The capital of the slaveholding republic was no longer in immediate reach. The fight at Malvern Hill was the last act of the campaign meant to take it.' },
  },

  'it-was-murder': {
    eyebrow: 'Malvern Hill · It Was Not War',
    title: 'It Was Not War',
    blocks: [
      { p: 'Lee thought he could still destroy this army. He had been chasing it for a week, and at Glendale the day before he had come close to splitting it open. One more hard blow, he believed, and McClellan’s retreating force might break apart entirely. A retreating army that loses its rearguard or gets cut in half stops being an army and becomes a rout, every man running for himself. So on July 1, looking up at the worst piece of ground he could possibly attack, Lee decided to attack it anyway.' },
      { h: 'July 1', eyebrow: 'It Was Not War' },
      { p: 'Major General D.H. Hill (South), one of Lee’s division commanders (a division being a fighting force of roughly eight thousand men, the largest unit a single general usually led into battle), rode out to look at the hill before any of it began. He went forward that morning and studied the Union position with a soldier’s eye: the open fields running up to the crest, the cannon stacked tier on tier along the top, the bare ground a man would have to cross to reach them. He read it correctly. He told the others, in so many words, that if McClellan was up there in strength, the smart thing to do was to leave him alone. It was the right call. It was overridden.' },
      { p: 'The plan that overrode it was the problem before a single man stepped off. Lee meant to soften the Union position first with his own cannon: to plant Confederate batteries at separated spots, have them throw converging fire onto the Union guns (cannon aimed from several directions at one point, so the damage concentrates), and silence them. Only after the Union artillery was beaten down would the infantry go in. It was a sound idea on paper and a disaster in practice. The Confederate guns came into action one at a time instead of all together, never managed their crossfire, and Colonel Henry J. Hunt’s (North) massed batteries, firing first and firing from above, simply cut them to pieces. Of roughly forty-five Confederate guns brought to the field, only six or eight were ever firing at once on either flank; the rest sat useless while the few that engaged were smashed one by one. Hill called the whole Confederate artillery effort “most farcical.”' },
      { p: 'The plan for the infantry was worse. The orders, drafted by Lee’s staff, made the attack signal a yell: fifteen brigades (a brigade being a smaller unit of roughly 1,500 to 2,500 soldiers, the standard block of an attack; several brigades make a division) were supposed to charge the moment they heard one general’s men cheer, across miles of broken, wooded country. As a way to coordinate thousands of soldiers, it was hopeless, and it failed not with a clean signal but by accident, in stages. Around 3:30 in the afternoon, Brigadier General Lewis Armistead (South) saw Union skirmishers (scouts probing forward of the main line) creeping toward his guns and sent three regiments to shove them back. That was a small local push, not the signal, but garbled reports of it, plus a false report that the Union line was pulling out, convinced Lee to turn his discretionary attack loose. Just then Major General John B. Magruder (South), one of Lee’s generals assigned to lead the assault, finally arrived, hours late, because a bad map had mislabeled one of the key roads and sent him the wrong way. He saw the commotion and threw his own men forward around 5:30. And Hill’s soldiers, who had heard no yell for hours and had actually begun building bivouac shelters to sleep in, assuming there would be no battle that day, now heard the racket from Magruder’s sector, took that for the signal, and charged. The assault did not come as one great coordinated wave. It cascaded out of one misunderstanding stacked on another, brigade after brigade stepping off because the brigade beside it had, each one walking up that bare open slope alone into the teeth of the guns.' },
      { fig: '/war-img/malvern-hill.png', cap: 'Massed Union guns on the crest shatter Lee’s uphill assaults, broken short of the line.', credit: 'Stuff Happened map' },
      { p: 'A frontal assault (marching infantry straight at a strong, fortified position head-on) is the costliest attack in war even when it works. A frontal assault uphill, across open ground, against massed artillery (many batteries concentrated to fire on the same killing zone), delivered one fragment at a time with no support, is not really an attack at all. From mid-afternoon on, the Confederate brigades came on and were torn apart. The guns fired canister (tin cans packed with iron balls that turned a cannon into a giant shotgun), and at close range a single blast could scythe down most of a company at a stroke, dropping a line of men where it stood. The charges stalled well short of the crest and were driven back down. Then another brigade tried, and was driven back. Then another; one of them, Kershaw’s, broke and ran after being raked by fire from its own confused supports. Around twenty separate Confederate brigades charged at different moments across the afternoon and into the evening; some divisions lost a quarter or more of their strength, individual brigades close to half. Not one Confederate soldier reached the top of the hill. A large share of those losses came from the artillery: Hunt’s gunners fired hundreds of rounds per battery and broke charge after charge before it could ever close to musket range, though no one has a precise accounting of how many men the cannon killed versus the rifles. The result is certain: the open field below the crest filled up with the dead and wounded of an army that never got to grips with its enemy.' },
      { p: 'Hill led one of the largest of those charges himself, five brigades, more than eight thousand men, sent up through the killing ground in uncoordinated waves, and he watched them get shot down on the very slope he had warned everyone to leave alone. More than twenty years later, writing his own account of the battle, he gave the day its verdict:' },
      { p: 'It was not war, it was murder.', q: true },
      { p: 'He had seen it from the front: brigade after brigade walking up an open hill into massed guns that broke each one before it arrived.', i: true },
    ],
    meanwhile: { region: 'the killing ground', title: 'The man who tried to stop it', body: 'The Confederate general who coined the most famous line about Malvern Hill, that it was not war but murder, was the same man who that morning had ridden out, looked up the slope, and tried to talk everyone out of going up it. His warning was overruled in the planning. Through the long afternoon it came true brigade by brigade, in front of his own eyes, on the exact ground he had pointed at. He named the slaughter because he had spent the day watching the thing he predicted happen anyway.' },
  },

  'richmond-saved': {
    eyebrow: 'Malvern Hill · Richmond Saved',
    title: 'Richmond Saved',
    blocks: [
      { p: 'By dark on July 1, the field belonged to the North. Every Confederate charge had been broken; the dead and wounded covered the slope below the guns; Lee’s army had thrown itself at Malvern Hill and bounced off with thousands of casualties and nothing to show. By every measure of the battlefield, the United States had won, clearly, and at far lower cost than the enemy. And then the winning army got up in the dark and continued its retreat.' },
      { h: 'The aftermath', eyebrow: 'Richmond Saved' },
      { p: 'The count was lopsided in the North’s favor. Union losses came to roughly 3,000 men, killed, wounded, and missing. Confederate losses ran far higher, somewhere in the range of 5,300 to 5,650, the price of sending brigade after brigade up an open hill at massed cannon. Lee had lost nearly twice as many men as McClellan and gained not one foot of the crest. On the field, Malvern Hill was a one-sided Union tactical victory, a tactical victory being a win in the actual fight on the ground, as opposed to a strategic one, which is winning the larger goal the whole campaign was fought for. It was the kind of defensive win generals study for a century afterward.' },
      { p: 'The victorious commander was not even there to see it. McClellan had left the immediate battlefield before the main fighting, going aboard the gunboat USS Galena on the James River and riding off to inspect Harrison’s Landing, the spot downriver where he meant to plant the army. Command on the hill fell to Brigadier General Fitz John Porter (North), his V Corps commander; a corps was the largest building block of the army, several divisions together, the unit just below the whole army itself, and Porter’s V Corps ran perhaps fifteen thousand men. Porter ran the defense, lined up the infantry around Colonel Henry J. Hunt’s (North) guns, and won the battle. McClellan’s absence from the field of his own great victory became a thing his enemies never let him forget; years later, during his run for president in 1864, his critics were still mocking him for sitting on a gunboat while other men fought.' },
      { p: 'When McClellan’s orders came down, they stunned the men who had just won. The army would not turn and drive back toward Richmond. It would keep retreating, abandon the hill it had just defended so well, and march on through the night to Harrison’s Landing on the James. Some of his subordinates objected; they had just shattered Lee’s attacks and wanted to push the other way, back toward the Confederate capital. McClellan overruled them. Around eleven at night the army pulled off Malvern Hill and marched away in heavy rain, tearing down a bridge behind it, and reached Harrison’s Landing the next day under the protection of the gunboats. The Seven Days were over. Lee thought about chasing and let it go, citing the rain and his own exhausted, bled-white army; Thomas J. “Stonewall” Jackson, Lee’s most aggressive corps commander, reportedly wanted to pursue and was overruled in turn.' },
      { p: 'The battle left a lesson in iron that outlived everyone on the hill, and it was about the cannon. Hunt had shown what massed artillery could do: hold a dedicated reserve of fresh batteries behind the line, rotate them forward as the front guns burned through their ammunition, and pour converging fire across open ground so that no infantry charge could ever cross it. That became the template for how the Union handled its guns for the rest of the war. The Confederates had taught the opposite lesson by failing. Their practice of parceling batteries out to individual brigades meant that of some forty-five guns on the field, only six or eight were ever firing at once, so they could never mass enough metal to silence Hunt. Lee took the point. After the Seven Days he reorganized his artillery into battalion-sized units that could be gathered and aimed together instead of scattered brigade by brigade. Malvern Hill earned its place in the textbooks not just as a slaughter but as the day that changed how both armies thought about cannon.' },
      { p: 'The small story and the big story split apart here. McClellan had won the battle. But Lee had won the week. In one week of relentless fighting, six battles, the last of them a defeat, Lee had taken an army that started within sight of Richmond’s church steeples and shoved it all the way back across the Peninsula to cower under naval guns on the James, ten miles from where it began. The threat to the Confederate capital was gone. The Peninsula Campaign, the North’s grand effort to win the war by taking Richmond, was effectively finished; the Army of the Potomac would dig in at Harrison’s Landing and never resume the advance. By the tally of blood, Malvern Hill went to the North. By the tally of the map, who saved his capital and who got driven away from it, the whole campaign went, decisively, to the South. It would be roughly two years before Union forces came that close to Richmond again.' },
      { p: 'The consequences rolled outward from there. Lincoln began losing faith in McClellan, the general who kept winning ground and giving it back; a new Union army under Major General John Pope (North) was already forming for a fresh overland push. Lee, meanwhile, reorganized his victorious army and turned north. The war in the East was about to leave the Peninsula entirely and swing toward a new collision in northern Virginia, the campaign that would end at Second Bull Run that August, a major battle Lee would also win, driving the Union out of northern Virginia again.' },
      { pill: '/war-civil-war/eastern/second-bull-run', plabel: 'Second Bull Run: where Lee carried the war back to northern Virginia' },
      { fig: '/war-img/cmdr/dh-hill.jpg', cap: 'Major General D.H. Hill (South), who called the slaughter “not war, it was murder.”', credit: 'Period photograph · public domain' },
      { p: 'Our success has not been as great or complete as we should have desired.', q: true },
      { p: 'McClellan won the last battle and lost the campaign. He saved his army and surrendered the prize it had come for. Both halves were true at once, and the South would take that trade every time, though it bought that week of deliverance with thousands of its own dead piled on an open hill, and could not yet know it was only buying time.', i: true },
    ],
    meanwhile: { region: 'Richmond', title: 'The captain who saved a capital', body: 'In Richmond, no one was tallying the slope below Malvern Hill. They were tallying the map, and on the map, the enemy that had nearly taken the city was now ten miles away and going nowhere. The Confederate press lionized Lee, the general who in one week had turned near-disaster into deliverance; the Richmond Dispatch went so far as to declare that “no captain that ever lived could have planned or executed a better plan.” A month earlier the capital had been packing to flee. Now it was safe, and the man who had saved it was a hero, a tactical defeat at Malvern Hill swallowed whole inside a strategic triumph.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={MALVERN_HILL_NARR} id={id} slug="malvern-hill" battleName="Malvern Hill" theatreId="east" battleId="e-malvern" />
}
