'use client'

// The Battle of Brandywine (September 11, 1777), battle sections · American Revolution.
// Produced through the war content pipeline (audits/war-content-pipeline.md): fact
// pack → author → critic gates (fact-check + storytelling + newcomer-clarity +
// framing, parallel) → reconcile → revise. Data only; rendered by the shared
// <BattleSectionReader>. House voice: no em-dashes; American/British side-tags once
// on first mention per section. Legend control per the fact pack: Cheyney's ride is
// badged "in the traditional telling," Greene's 45-minute pace "by tradition,"
// "treat him as if he were his son" is Lafayette's own much-later recollection, and
// every American casualty figure is a range (no official return was ever issued).
// The Lafayette-wounded painting carries its mandatory staging caveat in the caption.
// Sources: audits/war-pipeline/rev-brandywine-final.md (+ rev-brandywine-factpack.md).

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const BRANDYWINE_NARR: Record<string, Narr> = {
  'a-wall-with-doors': {
    eyebrow: 'Brandywine · The sea move and the creek',
    title: 'A wall with a handful of doors',
    blocks: [
      { locator: {
        eyebrow: 'Where and when · September 11, 1777',
        caption: 'The Brandywine was a wall with a handful of doors: an army crossed at fords (the shallow places where men could wade), and Washington guarded every one he knew about, from Pyle\'s Ford below Chadds Ford up to Buffington\'s at the forks. Above the forks, Trimble\'s and Jefferis\'s fords stood open, and Cornwallis\'s column came through them onto Osborne\'s Hill, squarely behind the American right.',
        frame: { lonMin: -75.74, lonMax: -75.52, latMin: 39.82, latMax: 39.96 },
        states: [
          { name: 'Pennsylvania', tone: 'focus', label: 'PENNSYLVANIA', labelLon: -75.71, labelLat: 39.951, labelSize: 11 },
          { name: 'Delaware' },
        ],
        labels: [
          { text: 'BRANDYWINE CREEK', lon: -75.69, lat: 39.852, kind: 'water', size: 11 },
          { text: 'WEST BRANCH', lon: -75.728, lat: 39.937, kind: 'water', size: 10, anchor: 'start' },
          { text: 'EAST BRANCH', lon: -75.628, lat: 39.954, kind: 'water', size: 10 },
        ],
        dots: [
          { name: 'Chadds Ford', date: 'the American center; Washington\'s HQ', lat: 39.872, lon: -75.589, heavy: true, anchor: 'end', dateBelow: true },
          { name: 'Birmingham Meetinghouse', date: 'the afternoon fight', lat: 39.906, lon: -75.595, heavy: true, anchor: 'end', dy: -6, dateBelow: true },
          { name: 'Kennett Square', date: 'Howe\'s HQ; both columns\' start', lat: 39.844, lon: -75.711, color: '#8a8175', anchor: 'start', dateBelow: true },
          { name: 'Trimble\'s Ford', date: 'first crossing, unguarded', lat: 39.923, lon: -75.687, color: '#8a8175', anchor: 'start', dateBelow: true },
          { name: 'Jefferis\'s Ford', date: 'the unwatched defile', lat: 39.939, lon: -75.636, color: '#8a8175', anchor: 'start', dateBelow: true },
          { name: 'The forks', date: 'East/West Branch confluence', lat: 39.89, lon: -75.62, color: '#8a8175', anchor: 'end', dateBelow: true },
          { name: 'Osborne\'s Hill', date: 'Cornwallis deploys', lat: 39.925, lon: -75.595, color: '#8a8175', anchor: 'start', dateBelow: true },
          { name: 'Dilworth', date: 'the evening stand', lat: 39.899, lon: -75.567, color: '#8a8175', anchor: 'end', dy: 8, dateBelow: true },
        ],
      } },
      { p: 'In the summer of 1777 Britain had two armies in America and two plans that had remarkably little to do with each other. One army, under General John Burgoyne, was coming down from Canada toward Albany, New York. The other, the main army under General Sir William Howe (British), the commander in chief in America, was going after Philadelphia, the rebel capital and the largest city in America. Howe hoped that reaching for the capital would force George Washington (American), commander of the Continental Army (the rebels\' regular army, as opposed to part-time militia), into the decisive battle the British wanted. Howe had told his superiors in London he intended Pennsylvania; London approved, while hoping he could somehow still cooperate with Burgoyne; no order ever required him to go north. So when Howe went south, Burgoyne\'s army was on its own. Who deserves the blame for that, Howe, London\'s sloppy coordination, or Burgoyne\'s own overconfidence, is an argument historians have been having for two and a half centuries. The fact pattern is not argued: Howe sailed away, the northern army went unsupported, and that fall it surrendered at Saratoga.' },
      { pill: '/war-revolution/two-armies', plabel: '1777: two British armies, two separate wars' },
      { p: 'And he did sail, which was the strange part. Rather than march overland across New Jersey (where Washington had spent the spring sparring with him without ever offering battle), Howe put his army to sea. On July 23, 1777, a fleet of more than 260 ships carrying some 16,000 to 17,000 troops stood out from Sandy Hook, New York. The obvious route ran up the Delaware River, the water highway straight to Philadelphia, and the fleet duly reached the mouth of the Delaware around July 30. There it stopped. Admiral Richard Howe, the general\'s brother, and his captains judged the river approach too risky: the Americans had forts and underwater obstructions called chevaux-de-frise (rows of sunken, iron-tipped spikes designed to tear out a ship\'s hull) below Philadelphia, and no safe landing place within reach. So the fleet turned around and sailed the long way, down the coast and up Chesapeake Bay (the next great bay to the south) instead.' },
      { p: 'The voyage was brutal. All told the army spent about 34 days at sea, packed into transports in midsummer heat, through thunderstorms and contrary winds. Only about three weeks\' forage (animal feed) had been loaded, and hundreds of horses died or were dying when the fleet finally anchored; the dead ones went overboard. When the army landed at Head of Elk, at the top of the Chesapeake near present-day Elkton, Maryland, on August 25, 1777, it stood roughly 45 to 50 miles from Philadelphia. Six weeks after leaving New York, seasickness and dead horses included, it was barely closer to the capital than when it started.' },
      { p: 'Washington, who had been tracking the fleet\'s reported positions all summer, marched south to meet it. On September 3 his light troops (fast-moving soldiers used for scouting and skirmishing) under William Maxwell skirmished with the British and Hessian (German troops in British service) advance guard at Cooch\'s Bridge, Delaware, the only Revolutionary War battle fought in that state. The British pushed on northeast into Pennsylvania, and by September 10 Howe had his headquarters at Kennett Square, a crossroads town about seven miles west of a creek called the Brandywine. Washington had already pulled his army back behind that creek and dug in on the east bank. It was the last good defensive line in front of the capital: lose the Brandywine and there was nothing but open country between Howe and Philadelphia, 25 miles to the northeast.' },
      { p: 'The Brandywine had no bridges along this stretch in 1777. An army, with its guns and wagons, could only cross at fords, the shallow places where men could wade. That made the creek a wall with a handful of doors, and Washington\'s plan was simply to hold the doors. The main door was Chadds Ford, where the Great Road (the main highway from Kennett Square toward Philadelphia, also called the Nottingham Road) crossed the creek. Washington put his strength there: Nathanael Greene\'s division at the ford itself, Anthony Wayne\'s division and Maxwell\'s light infantry covering it, and his own headquarters at the Benjamin Ring house nearby. Downstream, where the banks ran steep and an attack seemed unlikely, about a thousand Pennsylvania militia under John Armstrong watched Pyle\'s Ford. Upstream the doors kept coming: Brinton\'s Ford, Jones\'s and Painter\'s Ford, Wistar\'s Ford, Buffington\'s Ford. John Sullivan\'s division held that right wing, with Hazen\'s brigade strung out at the farthest crossings. Buffington\'s Ford sat at the forks of the Brandywine, the spot where the creek splits into an East Branch and a West Branch, and Washington believed it was the last usable crossing. Above the forks, he thought, the wall had no more doors.' },
      { fig: '/war-img/rev-brandywine-faden-map.jpg', cap: 'William Faden\'s 1778 London map of the battle, the British version of the day: the creek line, the fords, and the long hook of the British flanking march (the wide swing around the end of the American line). The triumphant title ("in which the rebels were defeated") is the victor\'s.', credit: 'William Faden · engraved map · 1778 · Boston Public Library / Wikimedia Commons · public domain' },
      { p: 'It did. Only a few miles farther north, Trimble\'s Ford crossed the West Branch and Jefferis\'s Ford crossed the East Branch, and nobody was guarding either one. Washington\'s maps were poor, he had been in this stretch of country for only a few days, and the local intelligence he leaned on failed him. Howe had the opposite problem solved for him: this corner of Pennsylvania held plenty of Loyalists (Americans who sided with the king), and local Loyalist guides who knew every road and crossing rode with the British army. The same countryside was also Quaker country, one of the most thoroughly Quaker landscapes in America: Kennett, Birmingham, and the townships around them were communities of Friends (Quakers), pacifist by conviction, and the war was about to march straight across their farms and meetinghouses.' },
      { p: 'If this is starting to sound familiar, it should have sounded familiar to the Americans too. Thirteen months earlier, at Long Island, Howe had pinned Washington\'s front with a demonstration (a noisy fake attack meant only to hold the enemy\'s attention) and marched a massive column through an unguarded pass around the American flank. Now Washington was standing behind a wall with an open door at the far end of it, facing the same general. When the British vanguard (the column\'s leading troops) poured through the narrow defile (a tight pass with no room to deploy) at Jefferis\'s Ford the next day, the Hessian captain leading it, Johann Ewald, could hardly believe what he was looking at, and said so in his diary.' },
      { p: 'I do not understand why the pass has been left wide open for us where a hundred men could have held up either army the whole day.', q: true },
    ],
    meanwhile: { region: 'Philadelphia', title: 'Sprigs of green', body: 'On August 24, the day before Howe\'s army landed, Washington marched the Continental Army down Front and Chestnut Streets through Philadelphia on its way south, the men wearing sprigs of green in their hats, the capital turning out to look at the army that was going to defend it. The show was the point: the city, and Congress sitting in it, needed to see soldiers. A little over a month later the British army marched into the same city unopposed.' },
  },

  'uncertain-and-contradictory': {
    eyebrow: 'Brandywine · The battle',
    title: '"Uncertain and contradictory"',
    blocks: [
      { p: 'At about five in the morning on September 11, 1777, the British army split itself in two at Kennett Square, Pennsylvania, and ran the Long Island play again: pin the enemy\'s front with a noisy fake attack while the real force marches around the end of his line, the same trick that had won General Sir William Howe (British), the commander in chief in America, his biggest victory the year before. Seven miles east, George Washington (American), commander of the Continental Army (the rebels\' regular army), was dug in behind Brandywine Creek, a stream with no bridges along this stretch, crossable by an army only at fords (shallow wading places), covering the road to Philadelphia, 25 miles away. Howe sent Wilhelm von Knyphausen, a veteran lieutenant general of the Hessians (German troops in British service), straight down the Great Road toward the main crossing at Chadds Ford with about 6,800 men, artillery, and the baggage train. Knyphausen\'s orders were theater: make noise, look like the whole army.' },
      { p: 'Cornwallis, Howe\'s hard-driving subordinate, meanwhile swung north with Howe riding along and about 8,400 of the army\'s elite: grenadiers (the big assault infantry, the army\'s heaviest punch), light infantry (fast troops trained to fight loose and quick), the Guards (the king\'s own regiments), and jaeger riflemen (German huntsmen turned sharpshooters). Their route around the American right ran some fifteen to seventeen miles (Major John André of Howe\'s staff, who made the march, called it "a circuit of about fifteen miles"; the standard modern measure is about seventeen). A heavy morning fog covered the column\'s first hours.' },
      { p: 'Between about nine and ten thirty Knyphausen pushed Maxwell\'s American light infantry back across Chadds Ford in running skirmishes, deployed on the west bank, opened a bombardment, and then simply kept the show going for hours. The morning fight rolled right past Old Kennett Meetinghouse on the Great Road, where the local Quakers (the Society of Friends, pacifist by conviction) were holding their midweek meeting; September 11, 1777 fell on a Thursday, meeting day. They did not stop. As one of the Kennett Friends later wrote:' },
      { p: 'While there was much noise and confusion without, all was quiet and peaceful within.', q: true },
      { p: 'The middle of Washington\'s day was consumed by reports that cancelled each other out. Around eleven, word came from Lieutenant Colonel James Ross, skirmishing on the Great Valley Road, that a large British column, maybe 5,000 men with Howe himself along, was marching north toward the upper fords. Washington liked what he heard: a divided enemy could be beaten one half at a time. He began issuing orders for a counterattack across the creek against Knyphausen. Then, around one, Major Joseph Spear of the militia reported that he had ridden the upper roads all morning and seen nothing. That made Ross\'s column sound like a feint (a fake move) designed to bait Washington into crossing. He cancelled the attack and waited.' },
      { p: 'While headquarters weighed Spear\'s nothing, the column he had not found was nearing the end of its circuit. Cornwallis\'s men had been on the road since five in the morning, the fog covering their first hours. They had waded Trimble\'s Ford on the West Branch of the creek; now the vanguard (the column\'s leading troops) was filing through Jefferis\'s Ford on the East Branch and into the narrow defile beyond it, a tight pass with no room to deploy, the kind of ground where a hundred men could have held up an army all day. Nobody was there. The column walked through.' },
      { p: 'Only around two o\'clock, as the reports stacked up (a Major Eustace; Bland\'s light dragoons, scouts on horseback; the local squire Thomas Cheyney, who in the traditional telling rode in hot and was disbelieved until he offered his life on it) did the picture come clear: the British were not marching toward the upper fords. They were already across, and behind the army\'s right flank. Washington put it plainly in his report to Congress that night: the intelligence had been "uncertain and contradictory."' },
      { p: 'By two o\'clock Cornwallis\'s column stood on Osborne\'s Hill, high ground squarely behind Washington\'s right, and rested after nine or ten hours of marching. Fooled by the same man, with the same move, twice in thirteen months.' },
      { pill: '/war-revolution/battles/long-island', plabel: 'Long Island, 1776: the first time Howe marched around an open American flank' },
      { p: 'Washington now did the thing that saved his army: he wheeled his right wing, which had spent the day facing west across the creek, a quarter-turn to meet an attack coming from the north. The divisions of two more of his generals, Lord Stirling (William Alexander, a New Jersey general who went by his claimed Scottish title) and Adam Stephen, and then John Sullivan\'s, with Sullivan in overall command of all three, swung north to the high ground around Birmingham Friends Meetinghouse, about two and a half miles north of Chadds Ford. The meetinghouse itself was already part of the war: the American army had commandeered it the day before as a field hospital (a makeshift hospital set up close behind the lines), so the Birmingham Friends had held their Thursday meeting in a wheelwright shop in Sconnelltown nearby. Joseph Townsend, a young Quaker who was there, remembered decades later that "some disturbance was discovered near the house," and "the meeting accordingly closed"; the Friends walked out into the sight of Cornwallis\'s army deploying across the fields.' },
      { p: 'Between three thirty and four, Cornwallis attacked off Osborne\'s Hill in parade-ground order. Sullivan\'s own division, still marching to its place on the left, was caught mid-deployment; Deborre\'s brigade broke almost at once, and the division was driven off in disorder. Stirling\'s and Stephen\'s divisions held the hill around the meetinghouse. Imagine standing in Stirling\'s line. You have been marching since the news broke; the meetinghouse at your back is the field hospital your own army set up yesterday; and coming up the slope toward you, in step, with bayonets fixed, is the army that was supposed to be on the other side of the creek, in front of Chadds Ford. Your guns on the knoll fire over your head. The line holds, breaks, takes the ground back, and holds again, for the better part of two hours, through some of the most intense close fighting of the entire war. British grenadiers came on with the bayonet; the light infantry and the jaegers worked the flanks; and at last Stephen\'s line broke, and then Stirling\'s.' },
      { p: 'Into that collapse rode the Marquis de Lafayette (American service), a nineteen-year-old French volunteer aide in his first battle, a major general by honorary commission for all of six weeks. He threw himself into Stirling\'s breaking line to rally it and took a musket ball through the left calf. He stayed on the field until the blood filling his boot forced him out. Decades later Lafayette remembered Washington telling the surgeon to treat him as if he were his son; the line is his own much-later recollection, but the bond it describes was real for the rest of both men\'s lives.' },
      { fig: '/war-img/rev-brandywine-lafayette-wounded.jpg', cap: '"Lafayette wounded at the battle of Brandywine," a nineteenth-century history painting. Heroically staged long after the fact (the calm poses and the spotlight are the painter\'s), but the event is real: the nineteen-year-old marquis was shot through the left calf rallying the breaking line at Birmingham Meetinghouse (the hilltop meetinghouse where the afternoon fighting peaked), in his first battle.', credit: '19th-century history painting · Wikimedia Commons · public domain' },
      { p: 'Down at Chadds Ford, Knyphausen heard Cornwallis\'s guns and stopped pretending. Between four and five his column stormed across Chadds Ford for real and broke through the weakened line of Anthony Wayne\'s American division and Maxwell\'s light infantry; with the artillery horses shot, most of the American guns there had to be abandoned (of fourteen American pieces on the field, eleven were lost before the day ended). John Armstrong\'s Pennsylvania militia downstream, never engaged, withdrew. The American center and right were now both collapsing, and Washington fed in his last fresh formation: Nathanael Greene\'s division, pulled from the center, which covered roughly four miles at a run, by tradition in about 45 minutes. Greene\'s regiments opened their ranks to let the fugitives stream through, closed them again, and with Weedon\'s Virginia brigade made a stand south of the village of Dilworth that held the pursuit for nearly an hour at sunset, until dark stopped it.' },
      { p: 'The army retreated east toward Chester, on the Delaware River about 14 miles away, beaten but not broken. Lafayette, wounded leg and all, helped rally the column at the Chester bridge, and most of the army was in by midnight, stragglers through the morning.' },
    ],
    meanwhile: { region: 'Birmingham', title: 'One grave behind the wall', body: 'The Americans had fought from behind the stone wall of the Birmingham burying ground; when the fighting moved on, the meetinghouse that had been an American field hospital that morning filled with wounded British officers instead. Local Friends (Quakers), young Joseph Townsend among them, came to tend the wounded of both armies and help bury the dead. British and American soldiers were laid in a common grave inside the wall the battle had been fought over.' },
  },

  'masters-of-the-field': {
    eyebrow: 'Brandywine · What it meant',
    title: 'Masters of the field',
    blocks: [
      { locator: {
        eyebrow: 'The campaign · August–September 1777',
        caption: 'A six-week sea move put Howe\'s army ashore at Head of Elk on August 25, about 45 to 50 miles from Philadelphia, barely closer than it had been at New York. The road to the capital ran through the Brandywine. After the battle the beaten army rallied at Chester, Wayne\'s division was bayoneted in its camp near Paoli on the night of September 20, and Cornwallis marched into Philadelphia unopposed on September 26.',
        frame: { lonMin: -76.00, lonMax: -75.00, latMin: 39.50, latMax: 40.10 },
        states: [
          { name: 'Pennsylvania', tone: 'focus', label: 'PENNSYLVANIA', labelLon: -75.86, labelLat: 40.05, labelSize: 12 },
          { name: 'Maryland', label: 'MARYLAND', labelLon: -75.9, labelLat: 39.665, labelSize: 10 },
          { name: 'Delaware', label: 'DELAWARE', labelLon: -75.50, labelLat: 39.545, labelSize: 10 },
          { name: 'New Jersey', label: 'NEW JERSEY', labelLon: -75.22, labelLat: 39.56, labelSize: 10 },
        ],
        labels: [
          { text: 'DELAWARE RIVER', lon: -75.28, lat: 39.77, kind: 'water', size: 11 },
          { text: 'CHESAPEAKE BAY', lon: -75.97, lat: 39.53, kind: 'water', size: 11, anchor: 'start' },
        ],
        dots: [
          { name: 'Brandywine / Chadds Ford', date: 'Sept 11', lat: 39.872, lon: -75.589, heavy: true, anchor: 'end', dy: -6, dateBelow: true },
          { name: 'Philadelphia', date: 'falls Sept 26', lat: 39.953, lon: -75.164, heavy: true, anchor: 'end', dateBelow: true },
          { name: 'Head of Elk, Md.', date: 'the landing, Aug 25', lat: 39.608, lon: -75.830, color: '#8a8175', anchor: 'start', dy: 14, dateBelow: true },
          { name: 'Cooch\'s Bridge, Del.', date: 'Sept 3 skirmish', lat: 39.640, lon: -75.727, color: '#8a8175', anchor: 'start', dateBelow: true },
          { name: 'Kennett Square, Pa.', date: 'Howe\'s HQ, Sept 10', lat: 39.844, lon: -75.711, color: '#8a8175', anchor: 'end', dy: 16, dateBelow: true },
          { name: 'Chester, Pa.', date: 'the midnight rally point', lat: 39.847, lon: -75.373, color: '#8a8175', anchor: 'start', dateBelow: true },
          { name: 'Paoli', date: 'the night attack, Sept 20–21', lat: 40.030, lon: -75.518, color: '#8a8175', anchor: 'start', dateBelow: true },
        ],
      } },
      { p: 'At midnight on September 11, 1777, from the town of Chester on the Delaware River, where his beaten army was still walking in, George Washington (American), commander of the Continental Army, reported the day to John Hancock, the president of the Continental Congress (the assembly governing the rebelling colonies, sitting up the river in Philadelphia). "I am sorry to inform you," he wrote, "that in this days engagement we have been obliged to leave the enemy masters of the field." The missing apostrophe is his; the candor is too. And then, in the same letter, the sentence that turned out to matter more:' },
      { p: 'Notwithstanding the misfortune of the day, I am happy to find the troops in good spirits; and I hope another time we shall compensate for the losses now sustained.', q: true },
      { p: 'The counting afterward says a great deal about the day, including how hard it is to count. The British and their Hessians (the German troops serving with them) filed an official return of 587 casualties, call it around 580 to 600, and only about 40 of them were Hessians. American observers guessed British losses at 2,000, but they were guessing from a distance. On the American side there is no return at all. None was ever issued, and none survives, so every American figure is an estimate: roughly 200 to 300 killed, 500 to 750 wounded, and 350 to 400 captured, a total somewhere around 1,100 to 1,300. Nathanael Greene, the American division commander whose stand at Dilworth had covered the retreat, put his own army\'s loss at 1,200 to 1,300. Eleven of the army\'s fourteen guns on the field were gone.' },
      { p: 'What followed was two weeks of the war going Britain\'s way. On September 16 the armies met again near the White Horse Tavern and a torrential storm soaked every cartridge on the field, washing out the battle before it happened; it is remembered, a little wryly, as the Battle of the Clouds. Then came the night of September 20. Anthony Wayne (American), the Pennsylvania brigadier whose division had held Chadds Ford, was camped near Paoli Tavern, in his own home county, shadowing the British army. Major General Charles Grey (British) took a force against the camp at midnight with a piece of cold professional discipline: he ordered muskets unloaded and flints removed (the flint is the stone that sparks the gunpowder; no flint, no accidental shot to alarm the sentries), so that the attack would be made silently, with the bayonet alone. It earned him the name "No Flint Grey," and it worked completely. The modern count is about 53 Americans killed, with some 113 wounded and 71 captured; older accounts ran the dead as high as 150 or more. Many of the American dead had multiple bayonet or sword wounds, and American propaganda said men had been killed begging for quarter (the formal word for mercy and surrender). Americans called it, immediately and ever after, the Paoli Massacre. Strictly by the rules of eighteenth-century war it was a lawful night attack, devastating because it was disciplined; "massacre" was the American framing, and the multiple wounds and the dark made it easy to believe. Wayne, criticized afterward by a court of inquiry, demanded a full court-martial (a formal army trial) to judge his conduct, and on November 1, 1777 it found that he "did every duty that can be expected from an active, brave and vigilant officer" and did "acquit him with the highest honor."' },
      { fig: '/war-img/rev-brandywine-paoli.jpg', cap: 'The night attack at Paoli, painted by Xavier della Gatta in 1782: British general Charles Grey\'s men coming in with the bayonet by firelight, nine nights after Brandywine. Americans called it the Paoli Massacre; modern counts put the dead at about 53.', credit: 'Xavier della Gatta · oil painting · 1782 · Wikimedia Commons · public domain' },
      { p: 'Philadelphia had already begun emptying two days before Paoli. On September 18 and 19, on a warning from Alexander Hamilton (a young officer on Washington\'s staff) that the British could cross the Schuylkill River outside the city, Congress fled, first to Lancaster, Pennsylvania for a single day, then on to York, Pennsylvania, farther west. The city\'s bells went too, hauled away to Allentown and hidden under a church floor, among them the State House bell that Americans now call the Liberty Bell. On September 26, 1777, fifteen days after Brandywine, Lord Cornwallis, the British general whose flank march had won the battle, led a column of British and Hessian grenadiers into Philadelphia unopposed. The rebel capital, the largest city in America, had fallen.' },
      { p: 'The campaign of General Sir William Howe, the British commander in chief, had been executed about as well as any British operation of the war. The sea move put his army where Washington had to fight; the flank march at Brandywine was longer and bolder than the Long Island version and worked completely; he beat the main American army in the open field and took the enemy\'s capital, and his official casualty bill for the battle was about half his enemy\'s. As pure generalship, Brandywine was arguably Howe\'s masterpiece. And then there is everything the masterpiece did not buy. He did not pursue at nightfall, and the Continental Army got away intact, in decent order, with its morale surprisingly whole; Washington had it back on the attack within a month, falling on Howe\'s camp at Germantown on October 4. Capturing the capital paralyzed nothing, because the American government was not the kind that lived in a building: Congress simply kept governing from York. And the same autumn, the northern British army that Howe had sailed away from surrendered at Saratoga on October 17, the defeat remembered ever since as the war\'s true turning point. Howe had won a city. What Britain needed him to win was an army, and the army was still out there, in good spirits, promising to compensate another time.' },
    ],
    meanwhile: { region: 'Paris', title: '"Philadelphia has captured Howe"', body: 'When word reached Benjamin Franklin, the rebels\' envoy in Paris working to bring France into the war on America\'s side, that Howe had taken Philadelphia, Franklin is said to have replied that it was the other way around: Philadelphia had captured Howe. The wording varies with the teller, but the point of the joke was sound strategy. A British army settling into a captured city for the winter was a British army not destroying its enemy, and the enemy was still in the field.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={BRANDYWINE_NARR}
    id={id}
    slug="brandywine"
    battleName="Brandywine"
    date="September 11, 1777"
    theatreId="rev-battles"
    battleId="rev-brandywine"
    theatreHref="/war-revolution/battles"
    accent="var(--rev-battles)"
    endHref="/war-revolution?theatre=rev-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
