// GENERATED by scripts/_build-threads.mjs from audits/threads-pipeline/parties-final.md.
// Do NOT hand-edit — edit the gated -final.md and re-run the build script.

import type { Narr } from '@/components/mode/battle-reader'

export const NARR: Narr = {
  "eyebrow": "The Parties · the anchor",
  "title": "When the Parties Traded Sides",
  "blocks": [
    {
      "p": "If you have ever cracked open a book about the Civil War, you have probably tripped over the same strange fact. The party fighting to end slavery was the Republican Party. The party of the slaveholding South was the Democratic Party. Abraham Lincoln, the man who freed the slaves, was a Republican. The states that seceded (formally broke away from the United States) to keep slavery were run by Democrats. And if you know anything about American politics today, where the Republican and Democratic coalitions on race and the South sit roughly opposite to all of that, your first reaction is reasonable: wait, what?"
    },
    {
      "p": "The confusion is real, and the answer is genuinely surprising. Over a little more than a century, the two parties' regional and ideological coalitions came to look roughly inverted from where they started. The South that voted Democratic for a hundred years now votes mostly Republican. The Black voters who once belonged to the \"party of Lincoln\" now vote overwhelmingly Democratic."
    },
    {
      "p": "The parties did not flip overnight. There was no single day, no single law, no backroom handshake where everyone agreed to put new names on the same two ideas. The change was gradual, it took decades, and it had several different causes working at once. It is a real story with real machinery, and once you see the machinery it stops feeling like a magic trick."
    },
    {
      "p": "To follow it, you have to do one thing: stop tracking the party *names* and start tracking the *coalitions and ideas* underneath them. The names attach and detach from those underlying positions over time. The positions are the more stable thing. So we start at the beginning, with two ideas about what America should be."
    },
    {
      "h": "The two poles America has always argued about",
      "eyebrow": "1790s–1820s · the first parties"
    },
    {
      "p": "The original argument was about how much power the federal government should have, and it had two faces from the very start."
    },
    {
      "p": "On one side stood **Alexander Hamilton** (the first Secretary of the Treasury, who organized his followers into the Federalist Party around 1789 to 1791 to push his financial plan). Hamilton wanted a strong central government with broad powers, a national bank, federal money to take over the states' debts, protective tariffs (taxes on imported goods, meant to shelter American factories from foreign competition), and a country built on commerce and manufacturing. Call this the Hamiltonian pole: strong federal power, pro-business, pro-modernization."
    },
    {
      "p": "On the other side stood **Thomas Jefferson** and **James Madison**, who built the Democratic-Republican Party (also called the Jeffersonian Republicans) in 1792 to 1793. They wanted the opposite: limited federal power, a strict reading of the Constitution that allowed Washington only what it spelled out, states' rights (the idea that the states, not the federal government, should hold most governing power), low tariffs, and a republic of independent farmers rather than bankers and factory owners. They thought Hamilton's national bank was flatly unconstitutional. Call this the Jeffersonian pole: states' rights, agrarian, suspicious of central power."
    },
    {
      "p": "Hold onto those two poles, Hamiltonian and Jeffersonian, because they are the spine of this whole story. The party names sitting on top of them will change again and again. The poles stay put."
    },
    {
      "p": "The Federalists ran the country until 1800, when Jefferson won the presidency and the Jeffersonians took over for a generation. The Federalists never recovered, and the way they died matters. During the War of 1812, a group of New England Federalists gathered at the Hartford Convention (December 1814 into January 1815) to protest President Madison and the war. Bad timing. Almost as soon as they finished, news arrived of the Treaty of Ghent ending the war, and of Andrew Jackson's stunning victory at the Battle of New Orleans. Rumors that some at Hartford had floated New England seceding made the whole party look disloyal and regionally selfish at the exact moment the country felt victorious. That was the end of the Federalists as a national force. The stretch that followed, roughly 1815 to 1825, got the nickname the \"Era of Good Feelings\": one party, the Jeffersonians, with no real opposition, and James Monroe winning re-election in 1820 essentially unopposed."
    },
    {
      "h": "New names, same two poles",
      "eyebrow": "1830s–1850s · Jackson vs. the Whigs"
    },
    {
      "p": "One-party calm did not last. By around 1828 a new two-party fight had organized itself, and the names had changed while the poles had not."
    },
    {
      "p": "Out of the old Jeffersonians grew the **Democratic Party**, built around Andrew Jackson. This is the direct ancestor of today's Democratic Party, and at the time it was the party of the \"common man\" against entrenched elites. Jacksonian Democrats pushed to give the vote to white men who did not own land, distrusted concentrated economic power, and favored low tariffs and aggressive westward expansion. Their signature fight was against the Second Bank of the United States, a national bank Jackson vetoed and killed because he saw it as a tool of the rich. Notice the inheritance: anti-bank, states'-rights-leaning, agrarian and populist. The Jeffersonian pole, wearing a new name."
    },
    {
      "p": "Against them rose the **Whig Party** (1833 to 1854), assembled by the Kentucky senator **Henry Clay** out of everyone who hated what they called Jackson's \"executive tyranny.\" The Whigs wanted what Clay packaged into a program he called the **American System**: a national bank for a stable currency, a protective tariff to grow American manufacturing, and federal money for \"internal improvements\" (building the roads and canals that would knit the country together commercially). Strong federal hand, pro-commerce, pro-modernization. The Hamiltonian pole under yet another label."
    },
    {
      "p": "So the same two ideas were still fighting. They had just swapped the labels on their jerseys once already."
    },
    {
      "p": "The Whigs had one fatal weakness, and it was the weakness that would blow the whole system apart. They were a cross-sectional party, with a Northern wing and a Southern wing, held together by economics and not by any shared position on slavery. As long as national politics was mostly about banks and tariffs, that worked. The moment slavery moved to the center of everything, in the early 1850s, the Whigs could not hold their increasingly anti-slavery Northern wing and their pro-slavery Southern wing in the same room. The founders who might have held it together were gone: Henry Clay and the great Whig orator Daniel Webster both died in 1852."
    },
    {
      "h": "The crucible",
      "eyebrow": "1854–1860 · a new party is born"
    },
    {
      "p": "Then came the law that broke everything."
    },
    {
      "p": "In May 1854, Senator **Stephen A. Douglas** of Illinois, a Democrat, pushed through the **Kansas-Nebraska Act**. It organized the Kansas and Nebraska territories (western lands the U.S. held that had not yet become states, where the slave-or-free question was the central fight) under a principle called **popular sovereignty**, which meant letting the settlers of a territory vote slavery up or down for themselves. That sounds tidy until you see what it undid. For more than thirty years, the **Missouri Compromise of 1820** had drawn a line across the map (at latitude 36°30′) and barred slavery in the northern part of the Louisiana Purchase (the vast western territory the U.S. bought from France in 1803, which roughly doubled the size of the country). Popular sovereignty effectively erased that line. Slavery, which many Northerners had assumed was fenced in and slowly dying, was suddenly back on the table everywhere."
    },
    {
      "p": "The North erupted. Settlers for and against slavery poured into Kansas and started shooting each other, a guerrilla war that earned the grim nickname \"**Bleeding Kansas**.\" And the political map of the country came apart. The Kansas-Nebraska Act destroyed the Whig Party, split the Democrats, and gave birth to a brand-new party."
    },
    {
      "fig": "/thread-img/parties-magee-1856.jpg",
      "cap": "\"Forcing Slavery Down the Throat of a Freesoiler,\" J.L. Magee, 1856. The cartoon's free-soil rage at the Democratic slavery-expansion platform is exactly the anger that built the new Republican Party.",
      "credit": "Library of Congress, item 2008661578; public domain."
    },
    {
      "p": "That new party was the **Republican Party**, and it is worth being precise about who built it and what they actually wanted, because the popular shorthand gets it wrong. It was born at anti-slavery meetings across the North in 1854. The coalition that came together was a merger of leftovers: the Northern, anti-slavery wing of the dying Whigs, plus the small **Free Soil Party** (a movement to keep the western territories free of slavery so that ordinary farmers could settle them without competing against slave labor), plus anti-slavery Democrats who could not stomach Kansas-Nebraska. And here is the precise part. They united on one plank, and it was not the abolition of slavery (abolition being the total, immediate end of slavery everywhere, not merely stopping its spread). It was stopping the *expansion* of slavery into the new territories. The early Republicans were free-soilers, not founding abolitionists. When Lincoln ran in 1860, his platform pledged not to interfere with slavery in the states where it already existed. It only opposed letting slavery spread. That is a real distinction, and flattening it into \"the abolition party\" gets the 1860 Republicans wrong."
    },
    {
      "p": "While the Republicans were forming up, the Democrats were tearing apart. At their 1860 national convention in Charleston, South Carolina, the party deadlocked. Douglas led the voting but could not reach the two-thirds majority his party required to nominate, a rule that handed the Southern delegates a veto: as long as they held together, they could block him. After the convention rejected a hard pro-slavery platform plank, around fifty Southern delegates walked out. The party reconvened in Baltimore and simply split in two. The Northern Democrats nominated Douglas on popular sovereignty. The Southern Democrats nominated the sitting vice president, **John C. Breckinridge** of Kentucky, on a flatly pro-slavery, states'-rights platform. A fourth party, the Constitutional Union Party, nominated **John Bell** of Tennessee on a platform that amounted to \"save the Union and don't talk about slavery.\""
    },
    {
      "p": "With his opposition split three ways, Lincoln won. The 1860 results are a portrait of a country already cracking along its seams. Lincoln took 180 electoral votes (the state-by-state votes that actually decide the presidency, which is how a candidate can win the office without winning the most ballots nationwide). Breckinridge took 72, Bell 39, and Douglas, despite running second in the national popular vote, just 12. Lincoln won with roughly 40% of the popular vote, one of the lowest winning shares in American history, because he swept the North and the Pacific coast and won zero slave states. In much of the South he was not even printed on the ballot. Breckinridge took most of the South. Bell took the border states of Kentucky, Tennessee, and Virginia. Douglas, the national front-runner of his party, carried only Missouri outright, plus a split share of New Jersey."
    },
    {
      "fig": "/thread-img/parties-1860-map.png",
      "cap": "The 1860 electoral map. Lincoln's Republican red covers the North and Pacific coast; Breckinridge's Southern Democrats hold the slave states. The country is already split along the line it will fight over.",
      "credit": "Wikimedia Commons, public domain."
    },
    {
      "p": "So stand back and look at what each party actually *was* on the eve of the Civil War. The **Republicans** were the party of the North, of stopping slavery's spread, of Lincoln, and of the Hamiltonian pole: a strong federal government and aggressive economic modernization. During the war, the Republican Congress would pass the Homestead Act, the Pacific Railway Act, the National Banking Acts, and high protective tariffs, the most Hamiltonian program imaginable. The **Democrats** were the party of the South (every seceding state was run by Democrats) plus the Northern Democrats, who themselves split into \"War Democrats,\" who backed the fight, and \"**Copperheads**,\" anti-war \"Peace Democrats\" who wanted to negotiate an end to it. The Copperheads were strongest in the Midwest, in Ohio, Indiana, and Illinois, and they explicitly waved the banners of Jefferson and Jackson, attacking Lincoln's centralizing of power and his move toward emancipation (the freeing of the enslaved, which Lincoln formalized in his 1863 Emancipation Proclamation) as \"strangling the Constitution.\" In 1864 the Democrats nominated General **George B. McClellan** for president on a platform, written by the Copperhead wing, that called the war a failure and demanded peace talks. McClellan repudiated that peace plank, and after Union General **William T. Sherman** captured the Confederate city of Atlanta that September, signaling that the Union side was winning, the case that the war was hopeless collapsed. Lincoln won re-election decisively."
    },
    {
      "pill": "/war-civil-war",
      "plabel": "The war these parties fought"
    },
    {
      "h": "The mirror",
      "eyebrow": "1865–1877 · Reconstruction"
    },
    {
      "p": "Reconstruction was the federal effort to rebuild the country after the war. With the Confederacy defeated, the federal government placed the former rebel states under military control and required them to write new governments, with Black men allowed to vote, before they could rejoin the Union. It is also the era when the two parties held coalitions that are the mirror image of what they hold today, and the facts here are not subtle."
    },
    {
      "p": "The three constitutional amendments that ended slavery and tried to build a multiracial democracy were written and pushed through by **Republicans, over Democratic opposition**. The **13th Amendment** abolished slavery (passed by Congress in January 1865 and ratified in December 1865, after Lincoln's death). The **14th Amendment** established birthright citizenship, due process, and equal protection of the laws (ratified in 1868). The **15th Amendment** guaranteed the vote regardless of \"race, color, or previous condition of servitude\" (ratified in 1870)."
    },
    {
      "p": "When Black men in the South voted in large numbers for the first time, in 1867 under the Reconstruction Acts, they voted overwhelmingly Republican. The Republicans became, in the phrase that stuck, \"the party of Lincoln,\" the party of Black voters and Black civil rights. The first Black members of Congress, men like Hiram Revels and Joseph Rainey, both arriving in 1870, were Republicans."
    },
    {
      "fig": "/thread-img/parties-first-vote-1867.jpg",
      "cap": "\"The First Vote,\" drawn by Alfred R. Waud for Harper's Weekly, November 1867. Black men in the South cast their first ballots under the Reconstruction Acts, and they voted overwhelmingly Republican.",
      "credit": "Library of Congress, LCCN 2011648984; no known restrictions on publication."
    },
    {
      "p": "The Democrats, meanwhile, became the party of the white South. As Northern enthusiasm for occupying the South faded, white Southern Democrats who called themselves \"**Redeemers**\" set out to take back control of their state governments, and they did it in large part through violence and voter suppression. The Ku Klux Klan, a secret white-supremacist terror group founded by former Confederates to murder and intimidate Black voters and their allies, was the first wave, founded in 1865 or 1866. From around 1874, paramilitary groups like the White League and the Red Shirts followed, organizations historians have flatly described as the military arm of the Democratic Party. They murdered and terrorized Black voters and their white Republican allies to drive them from the polls."
    },
    {
      "fig": "/thread-img/parties-nast-1874.jpg",
      "cap": "\"The Union as It Was,\" Thomas Nast, Harper's Weekly, October 1874. The Klan and the White League shake hands over a Black family they have ruined. This is the violence that put the white-supremacist Democratic Redeemers back in power.",
      "credit": "Library of Congress, item 2001696840; no known restrictions."
    },
    {
      "p": "Reconstruction ended with the Compromise of 1877, the deal that settled the disputed 1876 presidential election. Republican leaders in Washington accepted the withdrawal of the last federal troops from the South, handing the region back to Democratic control, in exchange for the presidency for their candidate, Rutherford B. Hayes. It was a bargain that traded away federal enforcement of Black civil rights for the White House, and historians have judged it harshly. With Washington's protection gone, the Redeemer Democratic governments built **Jim Crow**: legalized racial segregation and the systematic stripping of the vote from Black citizens through poll taxes, literacy tests, and grandfather clauses (rules that let a white man skip the poll tax or literacy test if an ancestor had voted before the war, which nearly all Black men, whose grandfathers had been enslaved, could not). With Black voters stripped from the rolls, the only voters left in much of the region were white, voting as one bloc, so reliably Democratic in every election at every level that the white South earned its own name, the \"**Solid South**.\""
    },
    {
      "p": "So here is the inversion, stated plainly because it is the whole point. In this era the Republicans are the party of Black Americans, of the civil-rights amendments, and of federal power used to enforce them. The Democrats are the party of the white South, of \"states' rights\" invoked in this era as a shield for white supremacy, and of Jim Crow."
    },
    {
      "p": "Two things have to be said together here, and saying only one of them is how this history gets abused. The first thing is true: in the nineteenth century the Democrats were the party of slavery and then of Jim Crow, and the Republicans were the party of Lincoln and Black civil rights. The second thing is just as true: those coalitions did not stay put. They are the *starting line* of a long realignment that the rest of this story is about, not a description of the parties as they exist now. Anyone who quotes the first fact and hides the second is selling you the past as if it were the present. The mirror is the setup. The swap is the payoff."
    },
    {
      "h": "How the sides actually moved",
      "eyebrow": "the teaser · a realignment that took decades"
    },
    {
      "p": "So how did we get from there to here? Not in one election, and not for one reason. The coalitions moved over the better part of a century, pushed by two large engines working at different times."
    },
    {
      "p": "The first engine was economic. In the 1930s, **Franklin D. Roosevelt** and the New Deal (his sweeping government response to the Great Depression, the economic collapse of the 1930s that wiped out jobs and savings nationwide) assembled a new Democratic majority that held an almost impossible mix of people: the segregationist white Solid South alongside Northern city dwellers, immigrants, labor unions, and, for the first time, large numbers of Black voters in the North. Black voters in Northern cities began moving to the Democrats on bread-and-butter economics: in 1936 roughly three-quarters of them backed Roosevelt, a stunning break from their old loyalty to the party of Lincoln. That left one party holding both the white South *and* a growing bloc of Black voters, a contradiction that could not last forever."
    },
    {
      "p": "The second engine was race and civil rights, and it is what finally cracked that contradiction open, slowly, from the late 1940s onward. As the national Democratic Party moved toward supporting civil rights, the white South began moving away. But the timing is the part everyone gets wrong. The white South did not abandon the Democrats all at once. Southern voters started voting Republican for *president* first, beginning in the 1960s, while still electing Democrats to state and local offices and still calling themselves Democrats for decades afterward. The full migration, from solidly Democratic to solidly Republican, took something like thirty years and was not really complete until the 1990s. On the other side, Black voters became overwhelmingly Democratic, which they remain today. Anyone who tells you the parties \"switched overnight\" is skipping all of this."
    },
    {
      "p": "There is also an honest argument among historians that you should know is unsettled. Everyone agrees the white South moved from the Democrats to the Republicans. The disagreement is about *why*, and specifically about how much of it was about race and how much about money. One camp, which has the weight of recent quantitative research behind it, argues that the move was driven mainly by white backlash against the national Democrats' embrace of civil rights. Another serious camp, anchored by a Harvard University Press study that won the V.O. Key Award (political science's top prize for research on Southern politics), argues that the bigger driver was the postwar economic boom in the South, the growth of a Southern suburban middle and upper class that turned Republican on taxes and economics more than on race. Both factors were clearly in play. What scholars genuinely dispute is the *proportion*, and it would be dishonest to tell you the question is closed in either direction."
    },
    {
      "p": "You will sometimes hear this whole turn summed up by a line attributed to **Lyndon B. Johnson**, that on signing the civil-rights laws he sighed that the Democrats had \"lost the South for a generation.\" Treat that line with suspicion. There is no solid contemporary record of him saying it, the wording surfaces only decades later, and historians regard it as effectively apocryphal. It makes a tidy story precisely because the real story is messier than any one quote."
    },
    {
      "p": "That messier story, the full decades-long swap with its New Deal economics and its civil-rights ruptures and its arguing historians, is a chapter of its own. But the foundation underneath it is the part most people never learn, and now you have it. The Republicans began as the anti-slavery-expansion party of Lincoln and the North. The Democrats began as the party of the agrarian South. Both of those things are true, and neither of them describes the parties you know today, because the ground underneath the names moved."
    }
  ]
}
