// GENERATED by scripts/_build-fi-themes.mjs from audits/war-pipeline/fi-<slug>-final.md.
// Do NOT hand-edit — edit the gated -final.md and re-run the build script.
// The French and Indian War off-the-battlefield theme narratives, consumed by the
// dynamic off-the-battlefield/[theme] route through the shared <BattleSectionReader>.

import type { Narr } from '@/components/mode/battle-reader'

export const THEME_NARR: Record<string, Narr> = {
  "ohio-company": {
    "eyebrow": "How a real-estate deal lit a world war",
    "title": "The Ohio Country & the Ohio Company",
    "blocks": [
      {
        "p": "A world war began as a property scheme. Not over a throne, not over a religion, but over a stretch of rich river-bottom land west of the mountains that a handful of Virginia gentlemen meant to buy cheap and sell dear. They never lived there. The people who did live there, Shawnee and Delaware and Mingo and Wyandot families, had already moved once to get away from men exactly like these. The gentlemen formed a company, won a king's signature on hundreds of thousands of acres, and the rest of the continent's empires answered. By the time the shooting started, the deal had a name on it in two languages and a fort going up on the very spot the company's paperwork demanded."
      },
      {
        "p": "This is the story of how that happened, and of the people whose ground it was all along."
      },
      {
        "h": "The land everyone wanted and no empire held",
        "eyebrow": "The Ohio Country, 1748"
      },
      {
        "p": "The Ohio Country was a loosely drawn region west of the Appalachian Mountains and south of Lake Erie, the upper valley of the Ohio River. A trader's map from 1752 ran its rough edges from the Wabash River in the west to the Thirteen Colonies in the east, Lake Erie in the north, the Cumberland River in the south. To a tidewater planter in coastal Virginia it was the best unclaimed farmland on the continent. To France it was something more vital: the land bridge. New France ran in a long arc, from Canada and the St. Lawrence River in the north down through the Illinois Country to Louisiana and the mouth of the Mississippi in the south, and the Ohio valley was the hinge that held the two ends together. A wall of British farms planted across that valley would saw New France in half."
      },
      {
        "p": "So both empires drew the Ohio Country onto their maps in their own colors. Neither one lived there."
      },
      {
        "p": "The people who lived there were Native nations, and how they came to be there is the whole heart of this story. A century earlier, in the 1600s, the Iroquois Confederacy (the powerful alliance of Native nations based in what is now upstate New York, also called the Haudenosaunee or Six Nations) had swept through the Ohio Country in a long series of wars historians call the Beaver Wars, driving out or absorbing the peoples who had lived there and holding the emptied land afterward as a hunting ground. Then, from the 1720s on, Native nations moved back into it, and they moved there on purpose. They were getting away. They came west driven by pressure from encroaching European colonists, looking for distance, looking for room the colonists had not reached yet."
      },
      {
        "p": "The Shawnee, an Algonquian-speaking people, began returning to the Ohio Country in those decades. The Delaware (who call themselves the Lenape) had been pushed west out of their home valleys along the Delaware and Susquehanna Rivers, and by 1724 they had founded the village of Kittanning on the Allegheny River. The Mingo were Iroquois people, mostly Seneca and Cayuga, who had migrated south and west into the Ohio Country and lived there half-independent of the home Confederacy's councils back east. The Wyandot, the people also known as the Huron or Wendat, lived in the region too."
      },
      {
        "p": "Hold the shape of that in mind, because everything else turns on it. These were nations that had already fled colonial pressure once, settling new ground precisely because it was beyond the colonists' reach. And the venture at the center of this story existed for one purpose: to reach it."
      },
      {
        "h": "A syndicate of planters and a king's signature",
        "eyebrow": "The Ohio Company of Virginia, 1748–1749"
      },
      {
        "p": "In 1748 a group of Virginia gentlemen organized themselves into the Ohio Company of Virginia. The founders were Thomas Lee (British) and the brothers Lawrence and Augustine Washington (British), fronting the interest of a circle of Virginia, Maryland, and British investors in the Ohio Country. They were speculators, which is the polite name for people who buy land cheap on the bet that they can sell it dear later, and the Ohio was the bet of a lifetime."
      },
      {
        "p": "A speculator's syndicate could not simply walk west and claim a valley, though. It needed a grant from the Crown. So a petition went across the Atlantic to King George II, and on the 16th of March 1748/49 (a date written with both years because Britain still used the old-style calendar, whose year began in late March, so a winter date carried the year on either side of that turn) royal instructions came back to Sir William Gooch (British), the Governor of Virginia, directing him to make the grant to two named men: John Hanbury (British), a London merchant who had done the lobbying at court, and Thomas Lee."
      },
      {
        "p": "The numbers were enormous. The Crown granted 500,000 acres in the Ohio valley, the country lying between the Kanawha and the Monongahela Rivers, and it structured the grant in two parts. The Company got 200,000 acres up front, with a further 300,000 to follow if it met a condition. The condition is the load-bearing fact of this entire story, so read it slowly. To keep the land, the Company had to do two things. First, it had to seat one hundred settler families on the ground within seven years. Second, it had to build a fort, and pay to keep a garrison in it, at its own expense. In exchange, the land would be free of quitrent (the small annual feudal rent colonists owed the Crown) and free of tax for ten years. The Privy Council in London (the king's governing council) worked the paperwork through and the grant issued in mid-July 1749."
      },
      {
        "p": "Look at what that grant actually ordered. The Company's own charter required it to plant a hundred families and raise a fort on land where Shawnee, Delaware, Mingo, and Wyandot families were already living. The settlement condition and the dispossession are the same fact stated two ways. The Company existed to take that ground and sell it."
      },
      {
        "p": "The roster of investors reads like a roll call of the Virginia gentry, and a few names matter for what comes later. Thomas Lee organized it. Lawrence and Augustine Washington were in, and so was their younger half-brother, a teenage shareholder named George Washington. George Mason (British) joined and became the Company's treasurer in 1752. John Mercer (British) and his sons held shares, and other tidewater shareholders besides, along with the London merchant John Hanbury, who had steered the petition through the Privy Council. And one more investor matters more than any of them for the chain of events to come: Robert Dinwiddie (British), the man who would soon be Lieutenant Governor of Virginia, held shares in the Ohio Company too."
      },
      {
        "p": "By about 1750 the Company had put a foothold on the ground, a fortified storehouse at Wills Creek (near the present-day West Virginia and Maryland border), a forward base from which to push west."
      },
      {
        "h": "The land rush and the king of the traders",
        "eyebrow": "Rivals for the Ohio, 1749–1750"
      },
      {
        "p": "The Ohio Company was not alone. The Ohio was the prize of the age, and other speculators wanted it too. The Loyal Company of Virginia organized at about the same time, a rival syndicate whose investors included Dr. Thomas Walker (British), William Cabell (British), and Peter Jefferson (British), the father of Thomas Jefferson. The two companies were after the same kind of thing: huge tracts of western land, won cheap, sold dear."
      },
      {
        "p": "And the rivalry was not only between syndicates. Even on the British side the Ohio was contested ground. Virginia claimed it under its old sea-to-sea charter, a colonial grant that ran the colony's bounds clear across the continent; Pennsylvania claimed the same upper Ohio as a westward extension of its own charter. So the land race was never just Britain against France. It was Virginia's Ohio Company against Pennsylvania's traders, both reaching for the same Forks of the Ohio, and the Forks were the crux of the whole dispute."
      },
      {
        "p": "Then there was George Croghan (British), the Irish-born Pennsylvania trader the frontier called the king of the traders, the British Empire's chief man among the Ohio Indians. In August 1749 Croghan bought 200,000 acres from the Iroquois, with one telling exception written into the deed: two square miles at the Forks of the Ohio, reserved for a British fort. That little reservation tells you what everyone already understood. The Forks were the key to the whole country."
      },
      {
        "p": "Croghan's deed had a legal problem. Pennsylvania law barred private men from buying land directly from Native nations, which made his purchase invalid at home. Virginia practice was looser about such things, and so the king of the traders ended up working for Virginia's Ohio Company instead. By 1750 Croghan and the interpreter Andrew Montour (British) were guiding the Company's scout, Christopher Gist (British), on a tour through the Ohio Indian villages, scouting the land the Company meant to sell."
      },
      {
        "h": "Lead plates in the ground",
        "eyebrow": "France answers, 1749"
      },
      {
        "p": "France was watching all of this, and France answered first with ceremony and then with forts."
      },
      {
        "p": "In the summer of 1749 the governor of New France sent an officer named Pierre-Joseph Céloron de Blainville (French) down into the Ohio Country to reassert French ownership of the entire watershed and to drive British traders out of it. Céloron left Montreal on the 15th of June 1749 with a force of around 216 French Canadians and roughly 55 Native allies, somewhere near 270 men in all."
      },
      {
        "p": "His method was strange and formal. At the mouth of each major tributary of the Ohio, Céloron's men buried an inscribed lead plate in the ground, a slab of lead about 11 inches by 7.5 inches, and nailed the French royal arms to a tree nearby. The plates claimed the land for King Louis XV of France. The text on them announced \"the renewal of the possession we have taken of the said river Ohio and of all those which empty into it, and of all the lands on both sides as far as the sources.\" At least six of these markers went into the ground that summer, including one at the confluence with the Chadakoin on the 29th of July, one at the mouth of the Muskingum on the 15th of August, and one at the mouth of the Kanawha on the 18th of August."
      },
      {
        "p": "\"the renewal of the possession we have taken of the said river Ohio and of all those which empty into it, and of all the lands on both sides as far as the sources.\" — inscription on Céloron's lead plates, 1749",
        "q": true
      },
      {
        "p": "It changed nothing on the ground, and the way it failed is the point. When Céloron reached Logstown, a Native town on the Ohio, he found English traders doing business and ordered them out. Further down, near Lower Shawneetown around the 25th of August, he summoned the traders again and warned them to leave. They did not leave. Worse for France, Céloron's high-handed manner offended even the Iroquois traveling in his own party. Some of them peeled off and went home, and as they went they pulled the nailed French plates back down off the trees. The expedition returned to Montreal on the 10th of November 1749 having accomplished nothing durable. The British traders stayed. The Ohio nations were not won over. Céloron himself reported back that the nations of the Ohio were very badly disposed toward the French and devoted entirely to the English."
      },
      {
        "p": "The lead plates are easy to laugh at, but notice who is missing from the whole ceremony. France claimed the river and all the land on both sides of it as far as the sources, and at no point did anyone think to ask the Shawnee, the Delaware, the Mingo, or the Wyandot whose country it was. That silence is the same silence on the British paperwork. Two empires were trading away a land neither of them lived on."
      },
      {
        "h": "A chain of forts toward the Forks",
        "eyebrow": "France builds the wall, 1753–1754"
      },
      {
        "p": "Ceremony had not moved the Ohio nations or cleared the traders out, so France reached for stone and timber. In 1753 and 1754 the French built a chain of forts to wall the British out of the Ohio and run a line of control from Lake Erie down toward the Forks. There were four, and they shared a design: a rectangle of roughly 75 by 105 feet with a bastion (a projecting corner platform for guns) at each of the four corners."
      },
      {
        "p": "Fort Presque Isle came first, on the shore of Lake Erie at present-day Erie, Pennsylvania, with construction beginning on the 15th of May 1753. Next came Fort Le Boeuf, inland on French Creek at modern Waterford, Pennsylvania, begun on the 11th of July 1753. Fort Machault followed in August 1753, where French Creek meets the Allegheny at a place called Venango, present-day Franklin, Pennsylvania. The fourth and most important would come at the Forks of the Ohio itself, the fort that would be named Fort Duquesne."
      },
      {
        "p": "These forts were the last links in France's effort to connect Canada with the Illinois Country and Louisiana, the physical version of the land bridge. With them, France was no longer just claiming the Ohio. France was building the wall that would cut the British colonies off from the west for good. Virginia could not let that stand, and the man who would not let it stand was an Ohio Company shareholder."
      },
      {
        "h": "An ultimatum carried by a 21-year-old",
        "eyebrow": "Washington's mission to Fort Le Boeuf, 1753"
      },
      {
        "p": "By 1753 Robert Dinwiddie was Lieutenant Governor of Virginia, and the awkward truth at the center of what he did next is that he was also a shareholder in the Ohio Company. The official sending an imperial ultimatum to France over the Ohio Country had a private financial stake in who ended up owning it. The empire's interest and the Company's interest had become, in Dinwiddie's person, the same interest."
      },
      {
        "p": "The envoy Dinwiddie chose was George Washington, then 21 years old, a major in the Virginia militia and, like the men who sent him, a shareholder in the Company whose land this was about. Dinwiddie commissioned him on the 30th of October 1753, and Washington left Williamsburg the next day. He hired a Dutch-born interpreter named Jacob Van Braam (British) at Fredericksburg to handle the French, picked up the Ohio Company's scout and surveyor Christopher Gist at Wills Creek, and gathered four frontier traders to handle the baggage, along with Native escorts. His orders from Dinwiddie were to reach the French forces on the Ohio, present his credentials and deliver Dinwiddie's letter to the senior French officer, demand an answer, and along the way note everything he could about the French forts, their forces, and their intentions."
      },
      {
        "p": "The party reached Fort Le Boeuf on the evening of the 11th of December 1753, escorted by Tanaghrisson, the Mingo leader the British called the Half-King, and other chiefs. Washington met the fort's commandant the next day. That officer was Jacques Legardeur de Saint-Pierre (French), and his answer, written out and dated from the fort on French Creek on the 15th of December 1753, was a polite, total refusal."
      },
      {
        "p": "\"As to the summons you send me to retire, I do not think myself obliged to obey it.\" — Jacques Legardeur de Saint-Pierre, French commandant, 15 December 1753",
        "q": true
      },
      {
        "p": "Saint-Pierre added that his orders came from his commanding general and that he would carry them out with all the exactness and determination that could be expected from a good officer, and that he knew of nothing in the campaign that could be construed as an act of hostility or as contrary to the treaties between the two Crowns. Which was diplomatic French for: we are not leaving, and you cannot make us."
      },
      {
        "p": "Washington left Fort Le Boeuf on the 16th of December and made the hard winter trip back, reaching Williamsburg around the middle of January 1754. He handed Dinwiddie the refusal and, with it, the journal he had kept on the road. That journal was published in Williamsburg in 1754 as *The Journal of Major George Washington*, and it made the unknown 21-year-old a name on two continents. It also recorded something more important than his own adventures, which is the voice of the man who had escorted him to the fort."
      },
      {
        "h": "The land does not belong to either of you",
        "eyebrow": "Tanaghrisson, Logstown, and the Ohio nations' own claim"
      },
      {
        "p": "Here the Ohio nations step forward in their own right, because they were never the backdrop to this story. They were a third power inside it, playing the two empires against each other to hold their own ground."
      },
      {
        "p": "The man at the center is Tanaghrisson, also written Tanacharison, the leader the British called the Half-King. He was a Mingo, an Iroquois of Seneca background settled in the Ohio Country, and he first appears in the records at Logstown in 1747. Almost everything else about him is contested, and the contests matter. The French claimed he had been born a Catawba (a Carolina nation) and taken captive and adopted by the Seneca as a child, and some historians repeat that origin; others dispute it. His working identity, the one that counts here, was as a Mingo and Seneca spokesman in the Ohio. Even his famous title is disputed. The old reading is that the Iroquois Grand Council appointed him a deputy, a \"half king,\" to oversee the Ohio peoples on the Confederacy's behalf. Modern historians argue that \"Half King\" was largely a British invention, a convenient title hung on a man whose real authority over the resident Ohio nations was thinner than the British wanted to believe. Both readings can be held at once, and the gap between them is exactly the tension this story runs on."
      },
      {
        "p": "That tension was about who had the right to sell the Ohio. The Iroquois Confederacy claimed the whole country by right of conquest, won in the Beaver Wars a century before, and treated it as theirs to negotiate away to the British. But the people actually living on it, the four nations of the Ohio, did not accept that the Iroquois could sell their ground out from under them. The British, for their part, loved dealing through the Iroquois, and through the Half-King, precisely because it produced land cessions (formal handovers of land) that the resident nations had never agreed to. Buy the land from a council that did not live there, and you never had to ask the families who did."
      },
      {
        "p": "This came to a head at Logstown in June 1752. Logstown sat on the east bank of the Ohio about 14 miles below the Forks, near present-day Ambridge, Pennsylvania, and there Virginia's commissioners met the Six Nations. Virginia sent Joshua Fry (British), Lunsford Lomax (British), and James Patton (British); the Ohio Company sent Christopher Gist, William Trent (British), and William Beverley (British). Andrew Montour, who had guided Gist's 1750 tour, was the interpreter at the council, and he was treated as more than a translator: Tanaghrisson addressed him by his Indian name, Eghnisara, and spoke to him as a man with standing among them. The British came to get two things: a confirmation of the earlier 1744 Treaty of Lancaster, which the British read as ceding Native land beyond the Allegheny Mountains, and consent to a Company fort and Company settlements on the Ohio."
      },
      {
        "p": "They did not get the first thing. Tanaghrisson flatly denied that the Lancaster treaty had ever ceded any land beyond the Alleghenies, and the Six Nations would not confirm Virginia's ownership of the country the Company meant to sell. Under pressure he did give ground on the second thing: he consented to a British \"strong house,\" a fort, at the mouth of the Monongahela at the Forks, and promised the Iroquois would not trouble English settlements southeast of the Ohio. In fact he had been telling the Virginians as early as 1752 that they should build a strong house at the Forks. But he did not sign away the Ohio nations' country, and he was careful about exactly where the line fell."
      },
      {
        "p": "The clearest statement of what the Ohio nations actually wanted survives because Washington wrote it down. Tanaghrisson is the person Washington quotes more than anyone else in his 1753 journal, and in it he recorded the Half-King's own speech to the French commandant. It is filtered through a British envoy's ear and pen, which is worth remembering, but it is the genuine primary record, and it says plainly what no empire wanted to hear."
      },
      {
        "p": "\"Both you & the English are White. We live in a Country between; therefore the Land does not belong either to one or the other; but the GREAT BEING above allow'd it to be a Place of Residence for us.\" — Tanaghrisson (Mingo), recorded in Washington's Journal, 1753",
        "q": true
      },
      {
        "p": "He was just as direct about the difference between trade and conquest:"
      },
      {
        "p": "\"If you had come in a peaceable Manner like our Brethren the English, we shou'd not have been against your trading with us as they do, but to come, Fathers, & build great houses upon our Land, & to take it by Force, is what we cannot submit to.\" — Tanaghrisson (Mingo), recorded in Washington's Journal, 1753",
        "q": true
      },
      {
        "p": "And he threw France's own past friendship back in its face, calling the French the disturbers in this land, by coming and building their towns and taking it away unknown to the nations and by force. Read those words next to the lead plates and the royal grant. Two empires had each declared the Ohio theirs on paper. The man whose people lived on it told both of them, to their faces, that it belonged to neither."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/native-alliances",
        "plabel": "The Contest for Native Alliances"
      },
      {
        "h": "The town France burned to make a point",
        "eyebrow": "Pickawillany, 21 June 1752"
      },
      {
        "p": "The Ohio nations were not only refusing land cessions in council. One of them had already gone further, choosing British trade over its French master outright, and the same June that Tanaghrisson stood at Logstown, France answered that choice with fire. The place was Pickawillany, a Miami (Twightwee) trading town on the west bank of the Great Miami River, near present-day Piqua, Ohio. The Miami chief Memeskia had founded it in late 1747 after breaking with the French, and within a few years it had grown to roughly 400 families and become the largest center of British trade in the whole Ohio Country. Memeskia had walked away from the French because their fur monopoly meant worse goods at worse prices, and he turned instead to Pennsylvania traders, the same Pennsylvanians reaching west under Virginia's rival. The British called him \"Old Briton\" for it; the French called him \"La Demoiselle.\" His town undersold the French and pulled neighboring nations out of the French orbit, and France was watching that happen."
      },
      {
        "p": "On the 21st of June 1752, days after the Logstown council, France moved. Charles Michel de Langlade (French), a young Métis officer in the French interest, led about 240 Ottawa and Ojibwe warriors down from the Great Lakes against Pickawillany, striking in the morning while most of the Miami men were away hunting. They killed about 13 Miami and an English blacksmith, captured several Pennsylvania traders, looted the goods, and burned the town. Memeskia was killed, and the attackers, by the accounts that come down to us, reportedly boiled and ate him within sight of the survivors, a deliberate act meant to punish his friendship with the English. The surviving Miami abandoned Pickawillany and drifted back toward the French. Historians often call the raid one of the opening actions of the war, and the lesson it taught was plain on both sides: France would use force to keep the Ohio nations in line, and Britain could not protect even the most prominent Native partner it had courted. The Ohio nations were actors in this story, choosing for themselves, and Pickawillany was what it cost when one of them chose wrong in France's eyes."
      },
      {
        "h": "The race for the Forks",
        "eyebrow": "Fort Prince George becomes Fort Duquesne, 1754"
      },
      {
        "p": "It all came down to one point on the map. The Forks of the Ohio, where the Allegheny and the Monongahela join to form the Ohio, sits where downtown Pittsburgh stands today, and it commanded river movement in every direction. Whoever held the Forks held the valley. The Ohio Company's grant had specifically ordered it to build its fort here, and Washington, scouting the site on his 1753 trip, had seen exactly why."
      },
      {
        "p": "\"As I got down before the Canoe, I spent some Time in viewing the Rivers, & the Land in the Fork; which I think extremely well situated for a Fort, as it has the absolute Command of both Rivers.\" — George Washington, Journal, 1753",
        "q": true
      },
      {
        "p": "Virginia moved first, barely. On the 17th of February 1754 a Virginia work party under Captain William Trent, with Ensign Edward Ward (British) commanding on the spot, began throwing up a small fort at the Forks, called Fort Prince George, or simply Trent's Fort. It was a modest thing, and it did not last two months. A French force of 500 or more men under Claude-Pierre Pécaudy de Contrecoeur (French) arrived at the Forks on the 17th of April 1754 and demanded surrender, and Ensign Ward, badly outnumbered, gave up the position without a fight the next day."
      },
      {
        "p": "The French tore down the British work and built their own fort on the same ground, a far larger one, and named it Fort Duquesne for Ange Duquesne de Menneville, the Marquis Duquesne (French), governor-general of New France. Fort Duquesne became France's anchor on the upper Ohio. Within a year it would be the objective of a doomed British army marching west under Major General Edward Braddock, but that is another story."
      },
      {
        "p": "The shape of the thing should be clear now. The Ohio Company's charter ordered it to build a fort at the Forks. France built a fort on that exact spot first. The first shots of a world war would be fired over who owned that ground, and the ground was never empty: Shawnee, Delaware, Mingo, and Wyandot families were living on it the whole time. The real-estate venture and the war are not two stories. They are one."
      },
      {
        "h": "What was already being taken",
        "eyebrow": "The cost, before the war was even lit"
      },
      {
        "p": "It is worth saying plainly what this was, because the polite language of grants and treaties is built to hide it. The contest for the Ohio was a contest over Native land, and the people who lost it were the people who lived there."
      },
      {
        "p": "The Ohio nations had already moved west once to escape colonial encroachment, and the Ohio Company was chartered to follow them and take the new land too: settle a hundred families, sell the rest. Their own aim was never to choose a European master. It was to keep both empires at arm's length and hold their ground, which is exactly what Tanaghrisson said in words Washington wrote down. Their leverage was real but bounded. They could refuse a land cession, as they did at Logstown. They could expel a trader or admit one. They could tip the balance between France and Britain by leaning one way or the other. But Pickawillany had already shown what that leverage cost when it pushed too far, and by 1754 both empires were building forts on their country anyway, with or without consent. The leverage was running out. The dispossession that the rest of this war would bring down on the Ohio nations was already visible, already in motion, before the war was even fully lit."
      },
      {
        "p": "One more thing about the name. The colonists who fought this war called it the French and Indian War, naming it for the enemies they expected to face. The name centers their point of view and it flattens everyone else into one word. The Native nations were not one thing and not one side. They fought on all sides and, more than anything, for themselves, for the simple proposition that the land they lived on was a place of residence for them and not a deed to be signed away in Williamsburg or buried on a lead plate in Montreal's name."
      },
      {
        "p": "The land grab came first. The war came after. And the families on the ground at the Forks were about to pay for both."
      },
      {
        "p": "The first blood would be spilled within weeks, in two small fights along the same disputed ground. The opening shots came in a wet ravine where Washington's men and Tanaghrisson's fell on a French party."
      },
      {
        "pill": "/war-french-indian/ohio-spark/jumonville-glen",
        "plabel": "Jumonville Glen"
      },
      {
        "p": "A month later the French answered, and Washington made his stand behind a hasty stockade in a mountain meadow."
      },
      {
        "pill": "/war-french-indian/ohio-spark/fort-necessity",
        "plabel": "Fort Necessity"
      }
    ]
  },
  "native-alliances": {
    "eyebrow": "1754–1763 · who held the interior",
    "title": "The Contest for Native Alliances",
    "blocks": [
      {
        "p": "The British colonists who fought this war named it after the people they were most afraid of. King George's War, a generation earlier, had already used the monarch's name, so when fighting broke out again in 1754 the colonists called the new one the French and Indian War. The label is a point of view. It names the enemy from a British porch looking west: the French Empire, and the many Indigenous nations fighting alongside it. What the name quietly admits is that Native nations were not a sideshow to this war. They were the thing the war turned on."
      },
      {
        "p": "Look at a map of North America in 1754 and most of it is empty of colonial towns. The British colonies hugged the Atlantic coast. New France was a thin ribbon up the St. Lawrence River and a scatter of forts. Everything in between, the Great Lakes country and the Ohio Country (the upper Ohio River valley, roughly today's western Pennsylvania, eastern Ohio, and the panhandle of West Virginia), was Native homeland. No European army could march through that interior, let alone hold it, without Native nations who knew the ground, supplied the warriors, and decided whether a column of redcoats walked out of the forest or didn't. So both empires courted them. They courted them on very different terms, and that difference decided who won the opening battles, who lost the trust that won them, and what happened to the nations who had been doing the deciding all along."
      },
      {
        "h": "What France had built",
        "eyebrow": "a century of kinship"
      },
      {
        "p": "France's advantage was old. For a hundred years French traders had pushed deep into the interior to buy beaver pelts, and the men who did it (the voyageurs who paddled the canoe routes, and the coureurs de bois, the unlicensed \"runners of the woods\") did not stay behind fort walls. They lived in Native villages, learned the languages, married Native women, and raised children with a foot in both worlds. By the 1750s France's relationship with the interior nations was built out of kinship and need: France needed the fur, and the fur came through marriage and friendship, not conquest."
      },
      {
        "p": "That relationship ran through a wide circle of nations. The French called the Great Lakes interior the pays d'en haut, the \"upper country,\" and its peoples were France's deepest allies: the Ottawa (Odawa), the Ojibwe (also called Chippewa), the Potawatomi, the Huron-Wyandot, and others like the Mississauga and the Winnebago. Closer to the French heartland, strung along the St. Lawrence near Montreal, were the mission communities known as the Seven Nations of Canada: seven Catholic Native villages allied to New France. The most reliable of them was Kahnawake (\"near the rapids\"), a Mohawk town across the river from Montreal."
      },
      {
        "p": "The Kahnawake Mohawk carry an irony worth pausing on. Their ancestors were Mohawk who, after French raids on the Mohawk villages in New York in the 1660s, converted to Catholicism and resettled on the St. Lawrence. A century later their descendants were France's most dependable Native allies, which meant that when the war came, Mohawk would fight Mohawk: Kahnawake Mohawk for France, and the Mohawk of the New York valley for Britain. The nations were not blocs. They were communities making their own choices."
      },
      {
        "p": "Two things made the French alliances durable, and both are easy to misread. The first is gift-giving. Every year France handed out powder, lead shot, cloth, and goods to its allied nations. To European eyes that looked like bribery. It wasn't. In Native diplomacy, accepting a gift created a real obligation between the giver and the receiver, and the steady flow of gifts was the substance of the alliance, the thing that proved the relationship was alive. Stop the gifts and you didn't just save money; you broke the bond. The second was the Catholic missions. Jesuit priests had converted many of the St. Lawrence nations while largely leaving their languages and clan systems intact, which tied those communities to New France by faith as well as trade."
      },
      {
        "p": "Historians have a name for how this worked: the middle ground. The French governor played a role the Great Lakes nations called Onontio, a father figure, but a particular kind of father: one who gave gifts, settled quarrels between nations, and kept the peace that trade depended on, rather than one who gave orders. It was a relationship of mutual accommodation, a middle ground where neither side simply imposed its will. That is the model that made France's position in the interior so strong. Its collapse is where this story ends."
      },
      {
        "p": "\"We will not be like Father and Son, but like Brothers.\" — Iroquois leaders, 1692",
        "q": true
      },
      {
        "h": "What Britain had, and what it didn't",
        "eyebrow": "the Covenant Chain and the land it could not stop selling"
      },
      {
        "p": "Britain's great alliance was the Covenant Chain, a partnership between the British colonies (New York above all) and the Iroquois Confederacy, also called the Six Nations or Haudenosaunee: the Mohawk, Oneida, Onondaga, Cayuga, Seneca, and Tuscarora. It had grown out of old Dutch trade ties and been formalized after England took over the Dutch colony in 1664, and it was renewed at councils in Albany, where the two sides spoke of a silver chain that had to be polished now and then to keep it bright. The Iroquois were precise about what the chain meant. It linked equals. As their leaders had put it back in 1692, they would be brothers to the English, not sons."
      },
      {
        "p": "By the 1750s the chain was tarnishing fast, and the reason was land. British and especially Virginian land hunger pressed constantly westward, often through outright fraud, and the nations Britain most needed had the most reason to distrust it. The clearest example sat right in the Ohio Country, the very ground the war would be fought over."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/ohio-company",
        "plabel": "The Ohio Country & the Ohio Company"
      },
      {
        "p": "In 1749 a group of Virginia land speculators (investors who buy up land cheaply hoping to sell it later at a profit) called the Ohio Company of Virginia received a royal grant of 200,000 acres in the upper Ohio valley, with another 300,000 promised if they settled a hundred families within seven years. To the Ohio nations this was a paper claim on their homeland, and it was exactly the kind of thing that made the Ohio Delaware (also called the Lenape) and the Shawnee certain that the British wanted their country, not their friendship. France read the same threat and marched troops in to block it. The collision in the Ohio is where the war started, and the man who lit the fuse was neither French nor British."
      },
      {
        "h": "The Half King starts a war",
        "eyebrow": "28 May 1754 · Jumonville Glen"
      },
      {
        "p": "Tanaghrisson was a Mingo (Ohio Iroquois) leader the British called the Half King. The Iroquois Council had sent him to hold the Ohio Country for the Six Nations, to speak for the Ohio nations and keep them in line, but by the early 1750s that authority was slipping. The Ohio Delaware were going their own way; the Shawnee were drifting toward France. A leader without followers needed something to change the board, and Tanaghrisson decided what it would be. Historians such as Fred Anderson read his aim this way: he believed that a war between Britain and France would force the Ohio nations back under him, bound to a Britain that needed his warriors. So he set out to start one."
      },
      {
        "p": "In the spring of 1754 a young Virginia officer gave him his chance. Lieutenant Colonel George Washington, then twenty-two, had pushed into the Ohio Country with about forty Virginians. On 28 May 1754, in the woods of Fayette County, Pennsylvania, Tanaghrisson and about a dozen of his Mingo warriors guided Washington's men to a hollow where a small French detachment was camped, under Ensign Joseph Coulon de Jumonville. They surrounded it and attacked at dawn. About ten of the French were killed and roughly twenty-one captured in a matter of minutes."
      },
      {
        "p": "What happened next is the part the sources argue over. By the most-repeated account, the firing stopped with Jumonville wounded but alive, and Tanaghrisson walked up to him, said in French \"Thou art not yet dead, my father,\" and killed him with a hatchet. The \"father\" was deliberate: Jumonville was standing in for all of French power in the Ohio, and Tanaghrisson was answering it. But the details are disputed. Sources disagree on whether Jumonville died from a musket ball or a hatchet, and by whose hand, and the killing is reported as widely as it is contested, never as settled fact."
      },
      {
        "p": "The point that is not in dispute is whose plan this was. Washington did not stumble into the war and he did not engineer it alone; a Native leader put him in that hollow to serve a Native aim. It was the clearest case in the whole war of an Indigenous leader steering two empires toward a fight for reasons of his own. And it failed. The Ohio nations did not rally to him; the Shawnee had already turned to France, other Delaware bands with them, and Tanaghrisson had misjudged the ground he thought he commanded. He fell ill that summer and died of pneumonia on 4 October 1754, months before the war he had started spread across a continent."
      },
      {
        "h": "Sir William Johnson and the Mohawk",
        "eyebrow": "Britain's one indispensable man"
      },
      {
        "p": "The man Britain trusted to hold the Iroquois was Sir William Johnson (British), an Irish-born trader who had settled in New York's Mohawk Valley, learned the Mohawk language, and steeped himself in Iroquois custom. The Mohawk adopted him around 1742 as an honorary sachem (a civil leader) and gave him the name Warraghiyagey, \"a man who undertakes great things.\" In 1756 the Crown made him Superintendent of Indian Affairs for the Northern District, a post that reported straight to London over the heads of the colonial governments, with one job: revive the Covenant Chain and win the wary Iroquois to Britain. Johnson's closest link to the Six Nations was personal. His household partner was Molly Brant (Konwatsi'tsiaienni), a Mohawk clan mother whose standing among her people made her a power broker in her own right; she ran his household and her diplomacy and intelligence were central to his influence. Her younger brother Joseph Brant (Thayendanegea) was a boy in these years, about thirteen when he went with Johnson to his first battle in 1755; his fame would come later, in another war."
      },
      {
        "h": "The Iroquois play their own game",
        "eyebrow": "balancing two empires"
      },
      {
        "p": "It is tempting to file the Iroquois under \"Britain's allies\" and move on. They wouldn't have recognized the description. The Confederacy's strategy was its own: don't be conquered or dominated by either empire, and keep trade flowing from both. For most of the war that meant a careful neutrality, a refusal to commit fully to either side, because the leverage was in the not committing. A nation everyone needs and no one owns can play the empires against each other, and that is exactly what the Iroquois did."
      },
      {
        "p": "It was never a single bloc, and the clearest proof runs along the length of the Confederacy itself. The Mohawk in the east, and especially Johnson's valley Mohawk, leaned British through his diplomacy and family ties. The Seneca in the west leaned the other way: Seneca warriors fought against Braddock's army at the Monongahela in 1755 and joined the raids on the Virginia frontier that followed, even as the Confederacy as a whole tilted British or neutral. So the Six Nations could have a man at the Monongahela firing on the redcoats and a man in the Mohawk Valley marching with them in the same year, and both were Iroquois. Even the British-leaning Mohawk were aggrieved rather than loyal, and the plainest proof of that came from their leading orator."
      },
      {
        "h": "Hendrick at Albany",
        "eyebrow": "1754 · the chain declared broken"
      },
      {
        "p": "His name was Theyanoguin, known to the British as Hendrick, a Mohawk leader of the Bear Clan based at Canajoharie. (He is often confused with an older Mohawk of the same English name who had visited Queen Anne in London in 1710; they were two different men.) Hendrick was a Christian convert and the foremost Mohawk diplomat of his day, and he had run out of patience with the British."
      },
      {
        "p": "In 1753 he had stood before New York's governor and declared the Covenant Chain broken, citing roughly 800,000 acres of Mohawk land lost to fraudulent dealing. (That figure is the grievance Hendrick voiced rather than an audited survey, but the size of the anger is the point.) Then in June 1754, at a gathering of colonial delegates and Iroquois leaders in Albany called to shore up the alliance, he said it to their faces, in a speech that has outlived almost everything else said there."
      },
      {
        "p": "\"Brethren, you were desirous we should open our minds and our hearts to you; look at the French, they are men; they are fortifying everywhere; but, we are ashamed to say it, you are all like women, bare and open, without any fortifications.\" — Theyanoguin (Hendrick), Albany Congress, 1754",
        "q": true
      },
      {
        "p": "The contradiction in Hendrick is the contradiction in the whole British alliance. He thought Britain was negligent, grasping, and weak. He fought for it anyway, because the French expansion he watched fortifying \"everywhere\" threatened the Mohawk more. In 1755 he helped recruit Mohawk warriors for an expedition Johnson led toward the French at Crown Point, and rode out at the head of a Mohawk force himself, well into his sixties."
      },
      {
        "p": "It went badly. On the morning of September 8, 1755, near Lake George, Johnson sent a detachment south, around a thousand colonial troops and two hundred or so Mohawk under Hendrick, and a French force under Baron Dieskau (French) ambushed it in a ravine. Hendrick had objected to splitting the men in the first place. The saying remembered from him, passed down rather than written at the time, was that a small force was too few to fight and too many to die for nothing."
      },
      {
        "p": "\"If they are to fight, they are too few; if they are to die, they are too many.\" — Hendrick (Theyanoguin), on the eve of the Battle of Lake George, 1755",
        "q": true
      },
      {
        "p": "He was right. His horse was shot from under him in the ambush, and being old he could not get clear; he was killed there. And the warriors who killed Hendrick's Mohawk were themselves Mohawk, the Kahnawake fighting for France alongside Abenaki and Nipissing allies. Mohawk killed Mohawk in that ravine. There is no cleaner picture of what it meant to say these nations chose their own sides."
      },
      {
        "h": "How Native allies won France its early war",
        "eyebrow": "1755 · the Monongahela"
      },
      {
        "p": "A few weeks before Lake George, France's alliances had already delivered the war's most lopsided victory, and they had done nearly all of it themselves. In the summer of 1755 General Edward Braddock marched a British army toward Fort Duquesne, the French post at the forks of the Ohio (where Pittsburgh now stands). On July 9, about ten miles short of the fort near the Monongahela River, his column met a force that had come out to meet it."
      },
      {
        "pill": "/war-french-indian/disaster/monongahela",
        "plabel": "The Monongahela"
      },
      {
        "p": "That force was overwhelmingly Native. Of roughly nine hundred fighters, only around 250 were French troops and Canadian militia; the rest, somewhere near 640, were warriors from the Great Lakes nations (Ottawa, Ojibwe, Potawatomi, Huron) and the Ohio nations (Delaware, Shawnee, Mingo), with Abenaki as well. The French field commander was killed almost at once. After that the warriors carried the fight, firing from the cover of the trees into Braddock's tight European formations standing exposed in the open."
      },
      {
        "p": "It was a slaughter. Of Braddock's roughly 1,300 to 1,460 engaged, more than 900 were killed or wounded; the French and their allies lost only a few dozen. Braddock himself was mortally wounded and died four days later, on July 13. A young Virginia officer named George Washington helped organize the survivors' retreat. The lesson of the Monongahela is the lesson of the whole war in miniature: the empire that held the Native alliances held the interior, and in 1755 that empire was France."
      },
      {
        "h": "The Ohio nations' own war",
        "eyebrow": "1755–1758 · the frontier in flames"
      },
      {
        "p": "What the Monongahela opened, the Ohio Delaware and Shawnee carried on for years, and they carried it on for themselves. Beginning about October 1755, war parties of Ohio Delaware (Lenape) under leaders such as Shingas and Captain Jacobs, and Shawnee alongside them, fell on the Pennsylvania, Maryland, and Virginia backcountry. From late 1755 into 1758 they killed, captured, or drove off thousands of settlers, in a frontier war that emptied whole valleys. They cooperated with France and were France's most important allies in those years, but they were not fighting France's war. They were fighting the colonists who had taken their land, for the land itself."
      },
      {
        "p": "The colonies struck back where they could. On 8 September 1756 Lieutenant Colonel John Armstrong led about three hundred Pennsylvania provincials in a dawn raid that destroyed the Delaware town of Kittanning, the staging point for the raids, and killed Captain Jacobs in the burning. It was a mixed result at best. Armstrong took heavy losses, most of the townspeople escaped with their captives, and the raids only intensified that autumn. What the strike did was embolden a Pennsylvania peace faction, and that faction's road led to a council fire."
      },
      {
        "p": "The man who drove it there was Teedyuscung (Delaware), the Delaware spokesman who turned the grievance into talks. At Easton in 1756 he laid the land fraud out in the open and accused the Pennsylvania proprietors of forging the deed behind it. His complaints pulled in British negotiators, ran through a second Easton conference in 1757, and built toward the treaty in 1758 that became the way out of the war in the Ohio. The fighting did not end on a battlefield. It ended at the table Teedyuscung had insisted on."
      },
      {
        "h": "Easton: the Ohio nations change the war",
        "eyebrow": "1758 · a separate peace"
      },
      {
        "p": "The decisive blow to France in the interior was not struck by a British army. It was negotiated at a council. By 1758 the Ohio Delaware and Shawnee, the nations whose distrust of British land hunger had pushed them toward France in the first place, had reasons to reconsider. They had always fought for their own land, not for France, and Britain was now offering to talk about exactly that."
      },
      {
        "p": "In October 1758, at Easton, Pennsylvania, more than five hundred Native people gathered with the colonial governors of Pennsylvania and New Jersey. Representatives of around thirteen nations attended, the Ohio Delaware and Shawnee and three of the Iroquois nations among them, with Teedyuscung prominent in the talks. On October 26 they reached terms. Britain pledged to recognize the nations' rights to their Ohio hunting grounds and, crucially, to keep British settlers out of the lands west of the Appalachian Mountains after the war. Pennsylvania agreed to return lands it had taken in the Walking Purchase of 1737, the swindle in which the colony used a rigged day-and-a-half \"walk\" (the Lenape expected a man to cover perhaps forty miles of forest in that time, but Pennsylvania cleared a straight path in advance and hired runners who turned it into a seventy-mile sprint) to seize a tract about the size of Rhode Island from the Lenape. The Lenape were paid about 1,000 Spanish dollars, money that bought their remaining land claims in New Jersey specifically rather than undoing the older fraud. And Pennsylvania's governor agreed to deal with the Delaware directly, restoring their standing rather than treating them as junior partners of the Iroquois."
      },
      {
        "p": "The military effect was immediate. With the Ohio Delaware and Shawnee pulling away from France and pledging neutrality, the French garrison at Fort Duquesne lost the Native shield that had made it dangerous. As a British expedition under Brigadier General John Forbes (British) closed in that November, the French, now outnumbered and abandoned by their allies, blew up Fort Duquesne and left. The British took the site and built Fort Pitt, the seed of Pittsburgh."
      },
      {
        "p": "The Ohio nations were not given peace at Easton. They chose it, because it served their interest better than the French alliance now did: it promised their land back and got the Iroquois off their backs. In doing so they decided the war in the Ohio more surely than any battle had. The same promise to halt settlement at the mountains would echo five years later in the Crown's Royal Proclamation of 1763, and like most such promises to Native nations, it would not hold."
      },
      {
        "h": "The victory that cost France its allies",
        "eyebrow": "1757 · Fort William Henry"
      },
      {
        "p": "Between Braddock's defeat and Easton, France won again, and the winning is where it began to lose. In August 1757 the Marquis de Montcalm laid siege to Fort William Henry, a British fort at the south end of Lake George held by Lieutenant Colonel George Monro (British) with a garrison of around 2,300, many of them sick with smallpox. Montcalm's army of about 8,000 included some 3,000 French regulars (full-time professional soldiers), about 3,000 Canadian militia, and nearly 2,000 Native warriors drawn from both of France's alliance circles at once: the Great Lakes nations of the pays d'en haut and the St. Lawrence mission nations, the Abenaki among them."
      },
      {
        "pill": "/war-french-indian/disaster/fort-william-henry",
        "plabel": "Fort William Henry"
      },
      {
        "p": "Monro surrendered on August 8 on generous terms. His garrison would march out under French escort with the honors of war, keeping their muskets (though no ammunition) and a single symbolic cannon, on the promise not to fight again for eighteen months. It was an honorable European arrangement between two European armies, and that was precisely the problem."
      },
      {
        "p": "The warriors who made up a quarter of Montcalm's army had not come for honor. They had been promised the trophies of war: plunder, scalps, and captives, the recognized returns of a successful campaign, the thing that justified travelling hundreds of miles from the Great Lakes to fight someone else's siege. The surrender terms handed the war stores to the French army and let the British keep their personal effects, which left the warriors with nothing at all. From where they stood it looked like the French had made a private deal with the enemy at their allies' expense. As the historian Ian K. Steele put it, the terms bred \"resentment, as it appeared that the French were conspiring with their enemies, the British, against their friends, the Indians.\""
      },
      {
        "p": "So on the morning of August 9, as the British column marched for Fort Edward, warriors fell on it. They struck first at the sick and wounded left behind in the camp, then at the marching column, killing some, stripping others, and seizing women, children, servants, and enslaved people as the captives they had been denied. A Massachusetts officer in the column, Colonel Joseph Frye (British), watched it happen."
      },
      {
        "p": "\"...the savages still carrying away officers, privates, women and children, some of which later they kill'd & scalpt in the road.\" — Col. Joseph Frye, eyewitness, 1757",
        "q": true
      },
      {
        "p": "The episode became a legend, and the legend inflated it. Jonathan Carver's 1778 account claimed as many as 1,500 dead, a figure later echoed by the historian Benson Lossing, and James Fenimore Cooper's 1826 novel The Last of the Mohicans cemented the legend in the popular imagination. Modern scholarship puts the toll far lower, somewhere between about 69 and 184 British killed or missing, under eight percent of those who had surrendered, and forensic work on the dead has found that disease killed more of them than weapons did. Whether Montcalm could have stopped it is still argued: one tradition holds that his officers did what they could and were simply overwhelmed, another that he saw it coming and acted only once the worst was underway."
      },
      {
        "p": "What is not in doubt is the cost, and it ran in two directions. The garrison had been riddled with smallpox, and the Great Lakes warriors who carried captives and plunder back to their distant villages carried the disease home with them, sparking epidemics that devastated their own communities. They had been denied their due, then sickened for their trouble. France had won the battle and broken faith with the allies who won it. The western nations remembered. Many of them would not march for France again."
      },
      {
        "h": "Allies, not pawns",
        "eyebrow": "what the war was really about"
      },
      {
        "p": "Step back from the battles and a pattern is plain. At every turn the Native nations were acting on their own strategy, not anyone else's. The Ohio Delaware and Shawnee distrusted Britain over land, then made peace with Britain when peace protected that land. The Great Lakes nations fought brilliantly for France, then turned away when France cheated them. The Iroquois balanced between the empires to keep from being swallowed by either. Tanaghrisson, the Mingo headman the British called the Half King; Hendrick at Albany; Teedyuscung at Easton; each pursued a Native aim, not a French or British one."
      },
      {
        "p": "The protocols said as much, if anyone was listening. Gift-giving, the polished chain, brother and not son, Onontio the father who persuades rather than commands: every one of these assumed that Native nations were independent powers to be courted, not subjects to be owned. They were never \"Britain's Indians\" or \"France's Indians.\" They were nations deciding which empire's offer served them, and reserving the right to change their minds."
      },
      {
        "p": "The cost of being courted was nonetheless ruinous. Smallpox tore through the garrisons and then through the villages, carried home from Fort William Henry into the Great Lakes country. War and captivity emptied communities. And underneath all of it ran the slow catastrophe the whole war sat on top of: the steady loss of Native land. The Walking Purchase that defrauded the Delaware, the 800,000 acres of Mohawk country Hendrick said had been swindled away, the Ohio Company's 200,000-acre paper grant over Delaware and Shawnee homeland. The contest for Native alliances was, at bottom, a contest over Native land, and the people whose land it was would pay for the outcome no matter who won."
      },
      {
        "h": "Winning the war, losing the peace",
        "eyebrow": "1761–1763 · Amherst and the rupture"
      },
      {
        "p": "France lost. Quebec fell in 1759, Montreal in 1760, and the Treaty of Paris in 1763 handed New France to Britain. For the Native nations of the interior that defeat removed the one thing their whole strategy had depended on: a second empire to play against the first. With France gone, there was no one left to balance Britain with, and the leverage that had made these nations courted powers simply evaporated."
      },
      {
        "p": "Britain's commander in North America, Jeffery Amherst, drew the obvious conclusion and acted on it. To him the Native nations were no longer allies to be cultivated; they were conquered subjects, and subjects did not need to be paid for their loyalty. Beginning in early 1761 he ended the customary gift-giving, the very practice that, in Native eyes, was the alliance itself. He restricted the sale of gunpowder and ammunition to Native traders, which was not an inconvenience but a threat to hunting and the entire fur economy. And he made little secret of his contempt; Native people complained that the British treated them no better than slaves or dogs. Amherst thought he was cutting waste. He was severing every cord that had held the interior together."
      },
      {
        "p": "\"Could it not be contrived to send the Small Pox among those disaffected tribes of Indians? We must on this occasion use every stratagem in our power to reduce them.\" — Jeffery Amherst to Henry Bouquet, 1763",
        "q": true
      },
      {
        "p": "The explosion came within months. In May 1763 a broad coalition of nations, led by the Odawa war leader Pontiac (Obwandiyag) among others, rose against the British posts strung across the Great Lakes and the Ohio. The trigger was Amherst's policy and the news that France had signed their homeland over to Britain without so much as a word to them. During the siege of Fort Pitt that summer, British officers gave besieging Delaware two blankets and a handkerchief taken from the fort's smallpox hospital; one of the traders inside recorded it plainly in his journal. Amherst, separately, wrote to his subordinate Colonel Henry Bouquet (British) endorsing exactly that idea, that the smallpox should be spread among the nations by means of blankets."
      },
      {
        "p": "\"You will do well to try to inoculate the Indians by means of blankets, as well as to try every other method that can serve to extirpate this execrable race.\" — Jeffery Amherst to Henry Bouquet, 1763",
        "q": true
      },
      {
        "p": "To \"extirpate\" a people is to wipe them out, and Amherst meant it as he wrote it. Whether the blankets caused an outbreak is debated; the intent in his own hand is not."
      },
      {
        "p": "The thing that had made France's alliances work for a century was reciprocity: gifts, mediation, the treatment of nations as nations. Amherst threw all of it away as so much foolish expense, and the war that followed was the bill. The contest for Native alliances did not end when France surrendered in 1760. Britain won the war and then lost the peace, because it forgot why the alliances had ever mattered."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/pontiacs-war",
        "plabel": "Pontiac's War & the Aftermath for Native Nations"
      }
    ]
  },
  "albany-plan": {
    "eyebrow": "A meeting that mattered more after it failed",
    "title": "The Albany Congress & the Plan of Union",
    "blocks": [
      {
        "p": "In the summer of 1754 the British colonies in North America had a problem they could not solve one colony at a time. War had already started on the Ohio frontier, the land beyond the Appalachian Mountains where the colonies, France, and a half-dozen Native nations all claimed the same rivers. A young Virginia officer named Lieutenant Colonel George Washington had marched west that spring and stumbled into the opening shots of it: a deadly skirmish at a place called Jumonville Glen in May, and then, on July 3, a humiliating surrender at a hasty stockade he had named Fort Necessity. Those small, ugly fights in the woods were the first sparks of what would grow into a war fought on three continents."
      },
      {
        "p": "So when delegates from seven colonies gathered at Albany, New York, that June, the situation was urgent. But the meeting was not really their idea, and the thing it is remembered for was not the first thing on its agenda."
      },
      {
        "h": "Why London called the meeting",
        "eyebrow": "The order from across the ocean"
      },
      {
        "p": "The congress at Albany happened because the British government told the colonies to hold it. But the order itself was a reaction to something a Native leader had done the year before. In 1753 the Mohawk leader Theyanoguin, known to the English as Hendrick, led a delegation of 17 Mohawk leaders past Albany and straight to Governor George Clinton in New York City, where they declared the alliance between the Iroquois and the British broken and walked out."
      },
      {
        "p": "\"...the Covenant Chain is broken between you and us. So brother you are not to expect to hear of me any more, and Brother we desire to hear no more of you.\" — Theyanoguin (Hendrick), Mohawk, to Governor George Clinton, 1753",
        "q": true
      },
      {
        "p": "That alliance had a name: the Covenant Chain. It was the metaphor, and the working relationship, that linked the Iroquois (and through them other Native nations) to the British colonies, above all to New York. When word of Hendrick's walkout reached London, the Board of Trade, the body that oversaw colonial affairs, ordered the colonies to meet the Iroquois and repair the chain. That order became the Albany Congress, and it was specific about what mattered most. The first order of business, ahead of anything else, was to mend the fraying alliance with the Iroquois Confederacy, the powerful league of Native nations whose friendship the British could not win the coming war without."
      },
      {
        "p": "The anger behind Hendrick's break had a concrete cause: the Kayaderosseras Patent, a land grant in the Saratoga region that the Mohawk denounced as fraudulent. A deed for a few small farms had, on paper, ballooned into a claim of hundreds of thousands of acres of Mohawk land, and the Mohawk were still raising it at the 1754 congress. By 1754 the chain had gone badly rusty for reasons like this. There had been no formal treaty council at Albany in roughly three years, and that neglect had a cost. The Iroquois were drifting toward neutrality, or worse, toward France, whose agents were busy and attentive while the British were absent. London understood the arithmetic perfectly well: a frontier war could not be fought without Native allies, and the alliance was the precondition for everything else. The Board of Trade even specified that proper presents be furnished to the Native delegates, because gift-giving was not a courtesy in this diplomacy, it was the diplomacy."
      },
      {
        "p": "The reason the colonies met at all was that the Native nations were drifting away, and the empire needed them back."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/native-alliances",
        "plabel": "The Contest for Native Alliances"
      },
      {
        "h": "The colonies that came",
        "eyebrow": "Seven of them, and a long list of absences"
      },
      {
        "p": "Seven colonies sent delegates, twenty-one commissioners in all: New York, Pennsylvania, Maryland, and the four New England colonies (New Hampshire, Massachusetts, Rhode Island, and Connecticut). Virginia, New Jersey, and the southern colonies did not bother to come, even though the union plan that emerged would later set aside seats for them."
      },
      {
        "p": "The chairman was James DeLancey (British), the Lieutenant Governor of New York, meaning the deputy to the colony's royal governor. Among the commissioners were men whose names would echo later. Thomas Hutchinson (British) of Massachusetts, who would help draft the union plan and one day become the colony's royal governor and a hated symbol of Crown authority. Stephen Hopkins (British) of Rhode Island, who would live to sign the Declaration of Independence. William Johnson (British) of New York, the colonies' most important go-between with the Iroquois and later the Crown's Superintendent of Indian Affairs. And, from Pennsylvania, Benjamin Franklin, who arrived with an idea bigger than the meeting he had been sent to."
      },
      {
        "p": "They met daily, mostly in the city hall at Albany, from June 19 to July 11, 1754."
      },
      {
        "h": "The Iroquois come to the table",
        "eyebrow": "The first business, and the bluntest voice in the room"
      },
      {
        "p": "About 150 Iroquois delegates came to Albany. This was not a side event. By London's own instruction it was the main one."
      },
      {
        "p": "A word on who they were. The Iroquois Confederacy, who call themselves the Haudenosaunee (\"People of the Longhouse\"), were by 1754 a league of Six Nations: the Mohawk, Oneida, Onondaga, Cayuga, Seneca, and, since around 1722, the Tuscarora. Their central council fire, the seat of the confederacy's decision-making, burned at Onondaga in what is now central New York. They were not anyone's subjects. They were a power, and they negotiated like one, protecting their own land and their own interests and playing the British and French empires against each other as it suited them."
      },
      {
        "p": "The man who spoke for them at Albany was a Mohawk leader named Theyanoguin, born around 1692 and known to the English by his baptismal name, Hendrick, and often called King Hendrick. He was a sachem (a civil leader), a warrior, and an orator, and when he rose to address the commissioners around July 2, he did not soften anything."
      },
      {
        "p": "He started with the silence. The British had let the friendship fire go cold."
      },
      {
        "p": "\"Brethren, this is the ancient place of treaty where the fire of friendship always used to burn, and it is now three years since we have been called to any public treaty here.\" — Theyanoguin (Hendrick), as recorded at Albany, 1754",
        "q": true
      },
      {
        "p": "Then he made the neglect physical. As the proceedings record it, he took up a stick and threw it behind his back."
      },
      {
        "p": "\"the reason is, your neglecting us these three years past… You have thus thrown us behind your backs, and disregarded us; whereas the French are a subtle and vigilant people, ever using their utmost endeavours to seduce and bring our people over to them.\" — Theyanoguin (Hendrick), as recorded at Albany, 1754",
        "q": true
      },
      {
        "p": "And then he said the line that landed hardest, contrasting French energy on the frontier with British passivity. The French were building forts everywhere. The British sat exposed."
      },
      {
        "p": "\"Look at the French, they are men; they are fortifying every where; but, we are ashamed to say it, you are like women, bare and open, without any fortifications.\" — Theyanoguin (Hendrick), as recorded at Albany, 1754",
        "q": true
      },
      {
        "p": "It is worth being honest about how these words reach us. Hendrick spoke in Mohawk; what survives is the speech as written down by interpreters and clerks and printed in the congress proceedings. We have it as recorded, filtered through other men's pens, not as a recording. But the force of it is unmistakable, and so is the point underneath it. He was not pleading. He was telling a partner it had failed to hold up its end, and reminding it who needed whom."
      },
      {
        "p": "He also named the thing the whole war was actually about. The empires were fighting over ground that belonged to Native nations, and Native nations stood to lose either way."
      },
      {
        "p": "\"The Governor of Virginia and the Governor of Canada are both quarrelling about lands which belong to us, and such a quarrel as this may end in our destruction.\" — Theyanoguin (Hendrick), as recorded at Albany, 1754",
        "q": true
      },
      {
        "p": "In the end the two sides agreed to renew the Covenant Chain. The Iroquois accepted the renewed alliance, but on their own terms, and Hendrick made clear it would be kept where their authority lived."
      },
      {
        "p": "\"We will therefore take it to Onondaga, where our council-fire always burns, and keep it so securely that neither thunder nor lightning shall break it.\" — Theyanoguin (Hendrick), as recorded at Albany, 1754",
        "q": true
      },
      {
        "p": "The chain was brightened. But the grievance underneath it, settlers pushing onto Iroquois land, was not fixed. It was left unresolved, in the colonists' favor. The Iroquois went home only partly satisfied, with the alliance shored up and the land problem worse than before."
      },
      {
        "h": "The land taken in the next room",
        "eyebrow": "The cost the congress would rather not record"
      },
      {
        "p": "While one part of the congress was renewing a friendship, another part was quietly stealing land."
      },
      {
        "p": "On or around July 11, the very day the congress closed, agents of Connecticut's Susquehannah Company obtained from an Iroquois delegation a deed to the Wyoming Valley, a stretch of Susquehanna River country in what is now northeastern Pennsylvania, for about £2,000 (New York currency). The deal has been called fraudulent ever since, and for good reason. It was negotiated in secret, reportedly greased with liquor and bribes, and it sold land that the Mohawk signing it did not rightfully control."
      },
      {
        "p": "The people who actually lived in the Wyoming Valley were not in the room. They were the Delaware (who call themselves the Lenape), already shoved off their land once by the swindle known as the Walking Purchase of 1737, and the Shawnee. Neither nation was a party to this sale of their own home. Being sold out at Albany pushed the Delaware and the Shawnee toward the French, and that drift would come back as fire and blood along the Pennsylvania frontier within a few years."
      },
      {
        "p": "Pennsylvania, not to be outdone, ran its own grab at the same congress. Its Indian agent Conrad Weiser (British) secured a deed to unceded Iroquois land west of the Susquehanna, reaching toward the Ohio and Lake Erie, for a nominal sum and a promise of more. (\"Cede\" means to formally hand over territory; \"unceded\" land is land that was never given up.) The Connecticut and Pennsylvania claims overlapped, and that overlap would later explode into the Pennamite-Yankee Wars, settlers of the two colonies shooting at each other over the same valley starting in 1769."
      },
      {
        "p": "The same gathering that renewed the Covenant Chain also stripped land from Native nations who were not even present to object. Both things happened in the same town, in the same three weeks."
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/ohio-company",
        "plabel": "The Ohio Country & the Ohio Company"
      },
      {
        "h": "Franklin's bigger idea",
        "eyebrow": "A plan to make thirteen act like one"
      },
      {
        "p": "Benjamin Franklin had come to Albany carrying more than the agenda. He had been arguing for months that the colonies were dangerously, foolishly divided, each one negotiating its own Indian policy and minding its own defense while France acted as a single will."
      },
      {
        "p": "He had already made the case in print, and made it unforgettable. On May 9, 1754, weeks before the congress, his Pennsylvania Gazette ran a small woodcut he had drawn: a snake cut into eight pieces, each segment labeled for a colony or region, under the words \"JOIN, or DIE.\" It is widely regarded as the first American political cartoon. The image leaned on an old folk superstition that a snake chopped to pieces could come back to life if the parts were rejoined before sunset. The message was not subtle. Reunite, or die in pieces. The cartoon ran before the Albany delegates ever sat down. It was the argument for union, printed first; the plan was what Franklin carried to Albany next."
      },
      {
        "p": "At Albany the commissioners voted on June 24 to take up the question of union. A committee worked out a draft, with Thomas Hutchinson of Massachusetts among those shaping it, and submitted it on June 28. On July 10, one day before the congress broke up, it was adopted: the Albany Plan of Union."
      },
      {
        "p": "The plan tried to thread a hard needle. It proposed a single government over all the colonies for shared purposes, with two heads. At the top would sit a President-General, a single executive appointed and paid by the Crown, meaning the king chose him and the king's treasury supported him. Underneath would sit a Grand Council, a legislature whose members were chosen by the colonial assemblies, the elected bodies that governed each colony. So the colonies would elect the lawmakers, and the king would appoint the boss, whose consent was required for everything the council did. The council would meet each year at Philadelphia, and members would serve three-year terms."
      },
      {
        "p": "Seats were handed out by colony, forty-eight in all to start, with the bigger colonies getting more: Massachusetts and Virginia seven each, Pennsylvania six, Connecticut five, on down to two apiece for New Hampshire and Rhode Island. After three years the apportionment (the share-out of seats) would be adjusted to match what each colony actually paid in."
      },
      {
        "p": "And the powers were real. The union would handle common defense (raising and paying soldiers, building forts, fitting out armed ships). It would run Indian affairs, holding treaties, declaring war or making peace with Native nations, and regulating the trade. It would control the western lands, buying territory from Native nations on the Crown's behalf and managing new settlements. And to pay for all of it, the union could levy taxes and duties. The three things the plan most wanted to take out of thirteen quarreling hands and put into one were defense, Indian affairs, and western lands. The same things, in other words, that the colonies had just spent three weeks mishandling in person."
      },
      {
        "h": "Adopted, then refused by everyone",
        "eyebrow": "Too much power, and not enough, at the same time"
      },
      {
        "p": "The congress approved Franklin's plan. Then it was sent out to the colonial assemblies and to London, and there it died, rejected from both directions for exactly opposite reasons."
      },
      {
        "p": "The colonial assemblies turned it down because it took too much power away from them. Each colony's legislature guarded its own authority jealously, and a Grand Council that could tax them and command their defense looked like a thief of local control."
      },
      {
        "p": "London turned it down because it gave the colonies too much. To the Crown and the Board of Trade, a self-governing intercolonial council with its own taxing power and its own armies looked like too much unity and too much independence handed to provinces that were supposed to take orders. The British government preferred to run the war directly from home. The plan was never enacted."
      },
      {
        "p": "Franklin, looking back years later in his autobiography, saw the symmetry and thought it proved he had gotten the balance right."
      },
      {
        "p": "\"The Assemblies did not adopt it, as they all thought there was too much prerogative in it; and in England it was judg'd to have too much of the democratic.\" — Benjamin Franklin, Autobiography",
        "q": true
      },
      {
        "p": "\"The different and contrary reasons of dislike to my plan make me suspect that it was really the true medium; and I am still of opinion it would have been happy for both sides the water if it had been adopted.\" — Benjamin Franklin, Autobiography",
        "q": true
      },
      {
        "h": "What the failure rehearsed",
        "eyebrow": "The union that came back in anger"
      },
      {
        "p": "The name itself admits something. The British colonists called this the French and Indian War, naming it for the two enemies they expected to fight, the French and the Native nations allied with them. The name centers their point of view and hides a larger truth: Native nations were not one side's tool. They fought on all sides and, more than anything, for themselves, for their land and their sovereignty, playing the empires off each other for as long as they could. The Albany Congress is the proof in miniature. The Iroquois walked in as a power London needed and walked out with the alliance renewed but their land quietly slipping away. When the war finally ended, it would end as a catastrophe for the Native nations of the eastern woodlands, who lost the leverage of two competing empires and, with it, the ground itself."
      },
      {
        "p": "For the colonies, the failure had a different afterlife. The Albany Plan was the first serious proposal that they should join under a common government. It failed completely in 1754. Not one of the bodies that could have made it real said yes. And yet it did not vanish. It became a precedent, a thing that had been tried and remembered, and the idea of intercolonial union resurfaced when the colonies' quarrel was no longer with France but with Britain itself: at the Stamp Act Congress of 1765, and at the First Continental Congress of 1774. The union the colonies refused to build for defense in 1754 was the one they would build, in anger, about twenty years later."
      },
      {
        "p": "Franklin thought the refusal had cost more than a plan. In his autobiography he argued that a union strong enough to defend itself would have made the later quarrel unnecessary."
      },
      {
        "p": "\"The colonies, so united, would have been sufficiently strong to have defended themselves; there would then have been no need of troops from England; of course, the subsequent pretence for taxing America, and the bloody contest it occasioned, would have been avoided.\" — Benjamin Franklin, Autobiography",
        "q": true
      },
      {
        "pill": "/war-french-indian/off-the-battlefield/war-finance",
        "plabel": "War Finance & the Road to Taxation"
      }
    ]
  }
}
