'use client'

// Fort Necessity (1754), battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author (Opus) → five critic gates
// (fact-check + storytelling + comprehensiveness + clarity + fairness, Sonnet,
// parallel) → reconcile → revise. Data only; rendered by the shared
// <BattleSectionReader>. House voice: no em-dashes; British/French side-tags once on
// first mention per section; stakes named plainly (an imperial war that was, on the
// ground, a war over Native land). Sources: audits/war-pipeline/fi-fort-necessity-*.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const FORT_NECESSITY_NARR: Record<string, Narr> = {
  'a-fort-named-necessity': {
    eyebrow: 'Fort Necessity · Bracing for revenge',
    title: 'A fort named Necessity',
    blocks: [
      { fig: '/war-img/fi-necessity-tac1.jpg', cap: 'After the killing at Jumonville Glen, Washington fell back to Great Meadows and built Fort Necessity, a stockade in an open mountain meadow. A French revenge force came down from Fort Duquesne at the Forks of the Ohio.', credit: 'Stuff Happened map' },
      { p: 'It began with blood in a wet ravine. On May 28, 1754, a young Virginia officer named George Washington (British), then twenty-two, surprised a small French party in the woods of western Pennsylvania at a place called Jumonville Glen. The skirmish was over in minutes, but its ending was ugly: the French commander, an officer named Jumonville, lay dead among the wounded, killed by Tanaghrisson, the Mingo leader the British called the Half King, after the shooting had stopped. Roughly ten or twelve French were killed and some twenty-one taken prisoner. Whatever exactly had happened in that glen, one thing was certain. The French at Fort Duquesne, the timber stronghold they had just raised at the Forks of the Ohio (the junction of two rivers that is now Pittsburgh), would come for revenge.' },
      { pill: '/war-french-indian/battles/jumonville-glen', plabel: 'The skirmish that started it: Jumonville Glen, May 1754' },
      { fig: '/war-img/fi-new-france-map.jpg', cap: 'New France and the Ohio Country: the vast interior that France claimed from the St. Lawrence to the Gulf, and that Virginia and the Ohio nations both contested.', credit: 'Stuff Happened map' },
      { p: 'This was always a fight over the Ohio Country, the vast interior beyond the Allegheny Mountains, and the river road into it. Both Britain and France claimed the Forks; both wanted the land and the fur and trade that came with it. France had gotten there first and built Fort Duquesne. But the land was not theirs, and it was not empty. Living on it were Native nations, the Mingo (the Ohio Iroquois), the Lenape (also called Delaware), the Shawnee and others, each navigating between two empires to hold onto their own country and their own freedom to act. For a Mingo family at the Forks, the abstraction had a face: the bottomland where they planted their corn, the runs where they trapped beaver to trade for powder and cloth, the river path their relatives had traveled for generations. It had never stopped being their country, even as two distant crowns argued over who would get to keep settlers off it. Washington had a small Virginia force out near the Forks to contest the French claim, and now he had started a shooting war he was in no shape to finish.' },
      { p: 'He fell back to a wide, marshy clearing called Great Meadows and dug in. There, between roughly the last day of May and the first days of June, his men threw up a small round palisade of upright logs about seven feet high and only about fifty feet across, with a shed inside for ammunition and shallow entrenchments dug outside the walls. Washington named it, fittingly, Fort Necessity. It was not a fortress. It was a circle of logs in an open meadow, about as wide as a modern tennis court is long, big enough to hold powder and a knot of men, and not much more.' },
      { p: 'The ground was bad in a way that would matter terribly. The little fort sat in a low, boggy depression, and the meadow was ringed by wooded high ground. Washington misjudged the distance to those trees. He seems to have believed the tree line stood safely out of musket range; in fact the woods came down within musket range, the nearest trees under sixty yards off, close enough for men hidden among the trunks to fire down into the open fort and the trenches around it. He had built a target and stood his army in the middle of it.' },
      { p: 'Help and trouble arrived together. The rest of the Virginia Regiment reached Great Meadows on June 9, bringing his command up to around two hundred ninety-three officers and men, along with nine swivel guns (small cannon mounted to turn on a pivot). Washington had only just risen to command of them: his superior, Colonel Joshua Fry, had died on May 31 after a fall from his horse back at Wills Creek, leaving Washington in charge. He was widely called "Colonel" now, though his formal full commission as a colonel would not come until the following year; on the day of the battle he was, at most, a very young provincial officer carrying more responsibility than his rank.' },
      { p: 'Then came Captain James Mackay (British) with about a hundred regulars, full-time professional soldiers of an Independent Company sent up from South Carolina. They should have been a gift. Instead they brought a quarrel. Mackay held a royal commission, granted in the king\'s name, and by the rules of the day a king\'s commission outranked a colony\'s even when it came with fewer men, so he would not take orders from a provincial colonel whose authority stopped at Virginia\'s border. The two forces sat side by side under two separate commands, the regulars and the Virginians, with no single man clearly in charge of all of them. It was the same wound that ran through the whole war, the regulars and the colonials refusing to fit under one another, and it would cost both of them.' },
      { p: 'The Native allies, meanwhile, were leaving. Tanaghrisson had backed the British for his own reasons, not the crown\'s: he meant to use them as a lever to push the French off Native ground at the Forks, and he had done much to start the fighting at Jumonville Glen toward that end. But he had grown disillusioned with Washington, complaining that the young officer ignored his advice and, in words an interpreter recorded, "commanded the Indians as his Slaves," ordering them about as subordinates rather than treating them as partners. When the British proved useless to his purpose, he put the lever down. He looked at the cramped circle of logs sitting out in the open bog and was scornful, calling it "that little thing upon the meadow," and he withdrew. By the time the French came, the warriors had melted away. Washington would face the revenge expedition with essentially no Native support at all.' },
    ],
    meanwhile: { region: 'The Forks of the Ohio', title: 'Where the war was really fought', body: 'Fifty miles to the northwest stood Fort Duquesne, the prize at the center of everything. Both empires wanted the Forks for the land and the trade it commanded, and France had just seized it. Everything that happened in the meadow was an aftershock of that grab. The men dying around the little log fort were the leading edge of a collision that would widen into a war fought on several continents.' },
  },

  'the-day-it-rained': {
    eyebrow: 'Fort Necessity · The siege in the mud',
    title: 'The day it rained',
    blocks: [
      { p: 'The revenge had a name, and it was personal. The expedition that marched out of Fort Duquesne was led by Captain Louis Coulon de Villiers (French), the older half-brother of the Jumonville who had died in the glen, the two sharing a father. He came down toward Great Meadows at the head of a sizable force. The exact size is uncertain, with accounts ranging from around six hundred to as many as eight hundred French, Canadian militia, and Native warriors together. Whatever the precise count, it badly outnumbered Washington\'s roughly four hundred. The men in the little fort were about to be besieged by an army half again their size or more, led by a man who had come to avenge his brother.' },
      { p: 'The French appeared late in the morning of July 3, 1754, around eleven o\'clock. Washington briefly marched his men out and formed them up in the open, the way a European officer was trained to do, inviting the enemy to stand and trade volleys in the field. It was the wrong instinct for this ground: ranked-up volley fire was built for open European battlefields, not for a meadow walled in by trees that let an enemy shoot from cover and never offer a line to fire back at. The French declined. They took to the trees on the high ground instead, spreading out among the trunks at the edge of the woods, and from that cover they began to pour fire down into the meadow. Washington pulled his men back into the fort and its trenches, and the long day\'s killing settled into its grim shape: the defenders pinned in the open circle and the wet ditches around it, the attackers shooting down at them from the shelter of the tree line, hour after hour.' },
      { p: 'Then the sky opened. A heavy rain came down and did not stop, and it turned the battle into a misery the muskets alone could never have managed. The low ground around the fort flooded. The entrenchments the men were sheltering in filled with water and became, in one description, pools of slop and muddy water, leaving the defenders standing or crouching in the wet with nothing dry to hold. Worse, the rain got into the powder. Soaked cartridges would not fire; fouled and waterlogged muskets jammed and failed. The French and their allies, dry under the canopy of the woods, kept up their fire while the men in the meadow found their own weapons going dead in their hands.' },
      { p: 'The cost mounted through the afternoon. By evening something like a third of Washington\'s command had been killed or wounded, perhaps thirty-odd men dead and around seventy hurt out of the four hundred. The French, firing from cover in the trees, lost only a handful, something like three killed and under twenty wounded, the figures a stark measure of what the wooded high ground and the rain had done. Ammunition ran low. The powder that was left was wet. And as the situation came apart, discipline went with it. Many of the men broke into the fort\'s supply of rum and drank and got drunk, looking for warmth or courage or simple escape from the flooded, hopeless circle they were trapped in. By the time darkness fell the garrison was bleeding, soaked, low on dry powder, and partly drunk, with no relief coming and the woods all around still full of an enemy they could not reach.' },
      { p: 'Then, around eight in the evening, the firing from the trees paused, and the French called out an offer to talk. Villiers, it turned out, had problems of his own. He was running short of supplies and was not eager to lose men storming the trenches when he might get what he wanted another way. Under a white flag, he proposed terms. To the men standing in the flooded ditches of Fort Necessity, an offer to end the day was not nothing.' },
    ],
    meanwhile: { region: 'Fort Duquesne', title: 'A brother\'s errand', body: 'The French stated their purpose plainly. By their own account at the parley, they had come to avenge the murder of one of their officers, the Jumonville killed in the glen, and to keep the British from planting any settlement on land the French king claimed. For Villiers it was both a mission and a family matter. He had marched out to answer his half-brother\'s death, and now, with the rain on his side, he was about to collect.' },
  },

  'the-signature-in-the-rain': {
    eyebrow: 'Fort Necessity · The capitulation',
    title: 'The signature in the rain',
    blocks: [
      { p: 'Washington sent men out into the dark and the downpour to hear the French terms, and among them went his translator, Jacob Van Braam. This was the hinge on which the whole night turned. Van Braam was Dutch by birth; his native language was neither French nor English. He stood in the rain reading aloud a document written in French, rendering it as best he could into English for a commander who could not read it himself, by the light of a guttering candle, with wounded men around them and the powder ruined and no good choices left.' },
      { p: 'The Articles of Capitulation, the formal surrender document setting the terms on which the garrison would give up the fort, contained a buried trap. Twice the French text used the word l\'assassinat to describe Jumonville\'s death in the glen, that is, assassination, murder. Van Braam, with no exact word for it in his own tongue and reading under impossible conditions, rendered it neutrally, as something closer to "the death" or "the killing of" Jumonville. So when Washington signed the articles late that night, in the rain, by candlelight, he was unknowingly putting his name to a document that appeared to confess that he had assassinated a French officer. He did not understand that he had done so. He later insisted the translation had been faulty and that he never would have signed such a thing had he grasped what it said.' },
      { p: 'The mechanism is genuinely murky, and worth holding loosely. Eighteenth-century military French was slippery on that word; in the soldier\'s usage, an "assassin" could mean simply a man who attacks suddenly and without warning, which is not quite the same as a murderer in cold blood. Van Braam, with no Dutch cognate to lean on, may have caught the softer sense, or none of it. What is not murky is what France did with the signature. The capitulation became a propaganda coup. Here, in Washington\'s own hand, was a written admission that the English had murdered Jumonville, and the French crown made the most of it across Europe.' },
      { p: 'The terms themselves were, by the standards of the day, not harsh. The garrison was granted the honors of war: the men could march out the next morning with their colors flying and their drums beating, keeping their muskets and their baggage, treated as soldiers rather than captives. The articles even granted them one swivel gun to take away, a gesture the French wording cast as proof of friendly treatment. In practice it did not hold. The French kept all nine of the swivel guns; Villiers wrote in his own journal that they obliged the British to leave their cannon, nine pieces in all. And there was a smaller betrayal that landed harder for being personal: the one gun the terms had promised, the proof they would be treated as friends, was taken with the rest. Then came the price in men. Two officers, Van Braam and Captain Robert Stobo, were handed over as hostages, held by the French as security that the British would keep the agreement.' },
      { p: 'with Drums beating, and one Swivel Gun, being willing thereby to convince them, that we treat them as Friends', q: true },
      { p: 'So on the morning of July 4, 1754, the survivors marched out of the little fort and started the long, sodden road back toward Wills Creek and Virginia. The men who could not agree which of them was in charge had, in the end, both put their names to the surrender: Washington and Captain Mackay each signed the articles. The date is a strange one to sit with: George Washington surrendered an army on the night of July 3 and marched it out in defeat on July 4, exactly twenty-two years to the day before the document that would make his country. As the column withdrew, Native warriors and French troops fell on the abandoned baggage and looted it. Behind them, the French burned Fort Necessity to the ground and marched back to Fort Duquesne. It was the only time in his entire career that Washington would surrender an army.' },
      { fig: '/war-img/fi-washington-1772.jpg', cap: 'George Washington, painted by Charles Willson Peale in 1772 in the uniform of his French and Indian War service. Fort Necessity was the only army he ever surrendered.', credit: 'Charles Willson Peale, 1772 · public domain' },
      { p: 'The wreck of it was not all his fault, and his own colony seemed to know it. Despite the defeat, the Virginia House of Burgesses gave him a formal vote of thanks; much of the blame was laid on poor supply and the failure of the other colonies to send help. But the defeat had consequences that ran far past one young officer\'s record. It did not just beat the British; it evicted them from the interior altogether. The Forks, the rivers, the roads into the Ohio Country were all French now, and they stayed that way for four more years. It also forced London to answer with something far larger than a provincial regiment. The next year the British sent regulars, a full expedition under Major General Edward Braddock, to march on Fort Duquesne and take the Forks by main force. That campaign would end in catastrophe on the banks of the Monongahela.' },
      { pill: '/war-french-indian/battles/monongahela', plabel: 'What the defeat set in motion: Braddock\'s disaster, 1755' },
      { p: 'And the people with the oldest claim to the ground got nothing they had fought for. The nations of the Ohio Country had tried to navigate between the two empires to hold their land, and the contest only tightened the vise. Tanaghrisson, who had helped light the whole fire at Jumonville Glen and then turned away in scorn from "that little thing upon the meadow," did not live to see how the war would go. Disillusioned with the British he had backed, he died of pneumonia on October 4, 1754, only three months after the meadow. The empires would go on fighting over his country for years, even as two crowns bled over who would get to keep settlers off it.' },
      { pill: '/war-french-indian/off-the-battlefield/ohio-company', plabel: 'The land both empires wanted: the Ohio Country' },
    ],
    meanwhile: { region: 'The Ohio Country', title: 'Caught in the middle', body: 'The Mingo, the Lenape, the Shawnee and their neighbors were not bystanders to this war but its real subject. Both empires wanted their land and the trade that ran through it, and every fort and every skirmish narrowed the room the nations had to maneuver. Tanaghrisson\'s arc from kingmaker at Jumonville Glen to a disillusioned man dead within months is the war in miniature: Native leaders trying to steer between Britain and France, and finding that whoever won, the prize was their own ground.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={FORT_NECESSITY_NARR}
    id={id}
    slug="fort-necessity"
    battleName="Fort Necessity"
    theatreId="fi-battles"
    battleId="fi-fort-necessity"
    theatreHref="/war-french-indian/battles"
    accent="var(--fi-battles)"
    endHref="/war-french-indian?theatre=fi-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
