'use client'

// THEME section — Lincoln's Rise & the Election of 1860 (Off the Battlefield, kind=theme). Built through
// the war content pipeline (fact pack → author(Opus) → five gates [fact-check +
// storytelling + comprehensiveness + clarity + Lost Cause/framing] → revise → images).
// Source + gate records: audits/war-pipeline/lincolns-rise-*.md. Green accent; no stat
// block, no map. 'use client' is REQUIRED (reads ACCENTS from a client module).
// GENERATED from lincolns-rise-final.md by scripts/_build-war-themes.mjs — do not hand-edit
// the prose here; edit the final.md and rebuild.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: `The outsider the South would not abide`,
    title: `The Man Nobody Saw Coming`,
    blocks: [
      { p: `There is a tidy way to tell the story of Abraham Lincoln's rise, and it goes like this: a wise, melancholy giant of a man, marked for greatness from his log-cabin birth, was lifted by destiny to the office that would let him save the Union. It makes for a fine statue. It is also almost the exact opposite of how it felt at the time. In 1858, Lincoln was a country lawyer from Illinois who had served one undistinguished term in Congress (the national lawmaking body in Washington) nearly a decade earlier and then gone home. That year he ran for the United States Senate and lost. Two years after that, he was president of the United States.` },
      { p: `That is the genuinely strange thing: not a destined hero but an underestimated outsider, a man the smart money kept counting out, who rode the country's slavery crisis from a defeat to the highest office in the land in barely twenty-four months. And the final twist is the darkest one. His victory was lawful, peaceful, and decisive. He won by the rules, without firing a shot or breaking a statute. And it was that very lawful election, more than any speech or raid or court ruling before it, that finally cracked the Union in half. Behind all of it, every convention deal, every debate, every vote count, were the roughly four million people held in slavery in the United States in 1860, whose future was the actual subject of every argument in this story.` },
      { h: `A prairie lawyer reenters the ring`, eyebrow: `Pressure` },
      { p: `To understand why nobody saw Lincoln coming, you have to start with how thoroughly ordinary his résumé looked.` },
      { p: `He was born on February 12, 1809, in a one-room log cabin on a Kentucky farm, and his formal schooling, added all together, came to less than a year. Everything else he knew, he taught himself. He read his way into the law the hard way, working through William Blackstone's *Commentaries on the Laws of England* (the standard four-volume English legal treatise that generations of American lawyers learned from) with no law school, no professor, and no mentor looking over his shoulder. He served four terms in the Illinois state legislature (the body of elected representatives that makes the laws for the state, separate from the national Congress), then a single term in the U.S. House of Representatives, from 1847 to 1849, as a member of the Whig Party.` },
      { p: `A word on how that national Congress is built, because it matters for everything ahead. Congress has two chambers. The House of Representatives hands out seats by population, so big states get more of them; the Senate gives every state exactly two, no matter how large or small. The House is the louder, more crowded room; the Senate is the smaller, more prestigious one, and a Senate seat was the bigger prize. Lincoln had served one term in the House. The seat he was now chasing was in the Senate. (As for the Whigs, broadly the pro-business party of the era, set against the Democrats, the party of Andrew Jackson and, increasingly, of the slaveholding South.) Lincoln had promised back home to serve only one House term, and he kept the promise.` },
      { p: `He did not spend that one term making friends. With the Mexican-American War on, Lincoln stood up and challenged President James Polk (Democrat) to identify the exact "spot" on American soil where, as Polk claimed, American blood had first been shed to start the war, the clear implication being that the blood had actually been spilled on Mexican ground and the war was a land grab dressed up as self-defense. The "Spot Resolutions" were principled and politically poisonous. Lincoln went home in 1849, turned down a government post out in the Oregon Territory because it would have wrecked his Illinois career, and went back to being a very good railroad and circuit lawyer (riding from town to town to argue cases). As far as the country was concerned, that was the end of him.` },
      { p: `What pulled him back was not ambition but an act of Congress, and it pulled hard. In 1854, Senator Stephen Douglas of Illinois pushed through the Kansas-Nebraska Act, which threw open western territory to the possibility of slavery by letting the settlers there vote it up or down. To Lincoln this was a moral catastrophe, and it did something to him that a good legal career never had: it pulled him off the comfortable path of being the best railroad lawyer in central Illinois and put him back on the stump (out making political speeches), because he could not watch slavery's reach widen and stay quiet. On October 16, 1854, he delivered a long, careful speech against the act at Peoria, Illinois, and historians generally treat that day as the moment Lincoln returned to political life for good. His old Whig Party was already dying around him. Its two aging leaders, Henry Clay and Daniel Webster, the men who for a generation had held the party together, both died in 1852, and the party came apart in the years after, most of its Northern members drifting into a brand-new organization built around stopping slavery's spread westward: the Republican Party (the ancestor of today's party in name, but a frankly Northern, antislavery party at its founding, and a very different creature from the modern one). By 1856 Lincoln was a Republican.` },
      { p: `Two nicknames trailed him, and both are worth a word of caution, because the legend tends to harden them into more than the record supports. "Honest Abe" was real enough as a reputation, attached to his straight dealing as a young store clerk and surveyor and his plain integrity as a lawyer, but no one can point to the moment it was coined or who coined it, so it is best understood as a reputation he grew into rather than a slogan someone minted for him. "The Rail-Splitter" has a sharper origin. At the Illinois Republican convention in Decatur in May 1860, a supporter arranged for Lincoln's cousin to march into the hall carrying two fence rails, placarded as rails the candidate himself had split as a young man. Lincoln, characteristically, refused to swear they were the actual rails, allowing only that he had "mauled many and many better ones since he had grown to manhood." It didn't matter. The image, the self-made frontiersman who'd swung an axe with his own hands, was campaign gold, and it stuck.` },
      { fig: '/war-img/lincolns-rise-lincoln-1858-byers.jpg', cap: `Lincoln in 1858, the year of the Senate race, photographed in Beardstown, Illinois, months before the debates with Douglas made him a national name. Lean, unglamorous, and still beardless.`, credit: `Abraham Byers · ambrotype · May 7, 1858 · Library of Congress · public domain` },
      { h: `The Little Giant and the house divided`, eyebrow: `Pressure` },
      { fig: '/war-img/lincolns-rise-douglas-anthony-1860.jpg', cap: `Stephen A. Douglas, senator from Illinois, photographed in 1860. His "popular sovereignty" doctrine (let the settlers vote on slavery) was the big idea Lincoln spent the debates dismantling.`, credit: `E. Anthony · carte de visite · 1860 · Library of Congress · public domain` },
      { p: `The man standing between Lincoln and the Senate in 1858 was the most formidable Democrat in the country.` },
      { p: `Stephen Arnold Douglas (Democrat) was a senator from Illinois, one of the state's two members of that prestigious upper chamber, and almost everything about him was the opposite of Lincoln. Where Lincoln was tall and plain-spoken, Douglas was tiny, barely five feet four, and so forceful, quick, and dominating on the Senate floor that people called him "the Little Giant," the joke being that his physical size and his political size had nothing to do with each other. He had been in the Senate since 1847, and he was the author of the very Kansas-Nebraska Act that had pulled Lincoln back into the fight. His big idea was "popular sovereignty," the principle that the people living in a territory should decide for themselves whether to allow slavery, rather than having Congress decide for them. Douglas thought this was the most democratic solution imaginable. Lincoln thought it was a moral dodge that let slavery creep wherever it could win a local vote.` },
      { p: `It helps to know that the Democratic Party Douglas belonged to was a coalition under enormous strain. Its Northern members mostly cared about economic growth, cheap western land, and settlers running their own affairs; its Southern members increasingly cared, above all else, about protecting and expanding slavery. One party, two wings, pulling in opposite directions. Douglas, the most prominent Northern Democrat alive, was about to feel the strain personally. He came into 1858 wounded inside his own party. He had broken openly with the Democratic president, James Buchanan, over Kansas: Buchanan wanted to admit Kansas as a slave state under a pro-slavery constitution that most Kansas settlers plainly rejected, and Douglas, true to popular sovereignty, refused to go along with forcing it on them. That fight put him crosswise with the Southern wing of his own party, a crack that would matter enormously two years later.` },
      { p: `Illinois Republicans nominated Lincoln for Douglas's Senate seat on June 16, 1858, at a convention, a large meeting of party representatives who have the power to officially choose who the party will back. That same evening Lincoln gave the speech that announced what kind of candidate he meant to be. Before about a thousand convention delegates (the representatives the party members had sent to do the choosing) in Springfield, he reached for a line from the Gospel of Mark and turned it into a prophecy:` },
      { p: `"'A house divided against itself cannot stand.' I believe this government cannot endure, permanently half slave and half free. I do not expect the Union to be dissolved — I do not expect the house to fall — but I do expect it will cease to be divided. It will become all one thing, or all the other. Either the opponents of slavery will arrest the further spread of it, and place it where the public mind shall rest in the belief that it is in the course of ultimate extinction; or its advocates will push it forward, till it shall become alike lawful in all the States, old as well as new — North as well as South."`, q: true },
      { p: `It is a remarkable thing for a candidate to say out loud. He was not promising compromise; he was telling his audience that the long national truce over slavery was a fiction, that the country was going to become one thing or the other, and that pretending otherwise was a waste of breath. Notice what he was actually after, underneath the prophecy: not the immediate freeing of the four million people already enslaved in the South, but a halt to slavery's *spread*, so that it might be set "in the course of ultimate extinction" somewhere down the road. Some of his own allies privately winced and thought it too radical, too likely to scare moderate voters. Lincoln declined to soften it. He had said what he believed.` },
      { h: `Seven afternoons that built a national name`, eyebrow: `Pressure` },
      { p: `Then came the part that made him famous, even as it failed to make him a senator.` },
      { p: `Picture a raw wooden platform thrown up in an open field at the edge of a prairie town, Ottawa, Illinois, on a hot afternoon in late August, and a crowd of twelve thousand people pressing in around it, more than twice the population of the town itself. They had come on foot, on horseback, in wagons and on excursion trains, raising dust and noise, vendors working the edges, brass bands blaring, and they stood for hours in the heat to watch two men talk. There were no microphones, no screens, no moderator to keep order; a man's voice and the wind were the whole technology. This is what a political debate looked like in 1858, and across the late summer and fall of that year Lincoln and Douglas did it seven times, all over Illinois: Ottawa, Freeport, Jonesboro, Charleston, Galesburg, Quincy, Alton, from August 21 to October 15.` },
      { p: `The format was punishing. Each debate ran about three hours in the open air. One man opened for a full hour, the other answered for an hour and a half, and then the first man came back for a half-hour rejoinder. As the incumbent (the man already holding the seat), Douglas got to open four of the seven. The crowds were enormous by the standards of a frontier state, twelve thousand at Ottawa, fifteen thousand at Freeport, somewhere around sixteen to eighteen thousand at Galesburg, people pouring in from neighboring states for the debates held near the borders. Two men argued one question for twenty-one hours in front of tens of thousands of people who stood in fields to hear it.` },
      { p: `The question, underneath all the maneuvering, was always the same: should slavery be allowed to spread into the western territories? Lincoln pressed that popular sovereignty was a moral sham, a polite name for letting slavery go anywhere it could organize a majority. Douglas pressed that it was simply democracy, the settlers deciding their own affairs.` },
      { p: `It is worth being honest about exactly what kind of antislavery man Lincoln was, because the whole drama ahead turns on the South reacting to him as something far more dangerous than he was. Douglas hammered Lincoln before the racially anxious crowds of southern Illinois as a secret champion of racial equality, and at the fourth debate, at Charleston on September 18, Lincoln answered the charge by drawing his own limits in the bluntest terms:` },
      { p: `"I am not, nor ever have been, in favor of bringing about in any way the social and political equality of the white and black races, that I am not nor ever have been in favor of making voters or jurors of negroes, nor of qualifying them to hold office, nor to intermarry with white people."`, q: true },
      { p: `There is no softening that, and no reason to. This is Lincoln in his own mouth, under pressure, and it marks the outer edge of his position: he was against the *spread* of slavery into the territories, not for abolishing it where it already stood and not, in 1858, for the political and social equality of Black Americans. Hold that fact next to what the South would soon do, and the proportions of the story come clear. The man the slaveholding states would treat as a mortal threat had just told a crowd, plainly, how limited his program was.` },
      { p: `The single most consequential moment came at the second debate, in Freeport, on August 27. Lincoln laid a trap. He asked Douglas whether the people of a territory could, by any lawful means, keep slavery out before they became a state. It was a brutal question, because the Supreme Court had just ruled, in the *Dred Scott* decision of 1857, that Congress could not bar slavery from the territories at all. If Douglas said yes, the territories could still keep slavery out, he would be contradicting the Supreme Court and infuriating the South. If he said no, he would be abandoning popular sovereignty, the one idea his whole career rested on, and infuriating his own Northern voters.` },
      { p: `Douglas wriggled out with an answer that became known as the Freeport Doctrine. Slavery, he argued, could not actually survive anywhere unless local laws actively protected it, the slave codes and police regulations that made owning a human being enforceable in practice. So even if the Supreme Court said a territory could not formally ban slavery, the people could still kill it simply by refusing to pass those supporting laws, what he called "unfriendly legislation." No local protection, no slavery, Court or no Court.` },
      { p: `It was clever enough to win Douglas the immediate exchange. It also, over the next two years, helped destroy him. Stand in a Southern delegate's boots for a moment and hear what Douglas had just said out loud, in front of fifteen thousand people: that the Supreme Court's guarantee of slavery in the territories was worthless paper unless local legislatures chose to honor it; the protection of slavery in the West depended on the goodwill of free-soil settlers who would never grant it. The South did not want goodwill. They wanted a federal slave code, a national law protecting slavery in every territory no matter how the locals voted. Douglas refused to give them one, and the man who alone might have held the Democratic Party together had just told the South it could not trust him. That refusal, born in a debate in Freeport, would split the Democratic Party down the middle in 1860, and the split is what handed the presidency to Lincoln. But that is getting ahead of the story.` },
      { h: `Losing his way to the top`, eyebrow: `Turning point` },
      { p: `Lincoln lost.` },
      { p: `Here the mechanism matters, because Lincoln lost in a way that wasn't quite a defeat. In 1858, U.S. senators were not elected by the voters directly; they were chosen by the state legislature. (Direct popular election of senators didn't arrive until the Seventeenth Amendment in 1913.) So the 1858 contest was really a fight over which party would control the Illinois legislature, and that body would then pick the senator. When the votes were counted, Republican legislative candidates statewide actually outpolled the Democrats by a few thousand votes. But the legislative districts had been drawn in a way that favored the Democrats, so even with fewer votes statewide they won more seats. On January 5, 1859, the Illinois General Assembly met and re-elected Douglas to the Senate, 54 to 46. Lincoln had won more votes and lost the seat.` },
      { p: `And yet. The debates had been printed in newspapers and reprinted across the country, and they had introduced a sharp, formidable Lincoln to a national audience that had never heard of him. He gathered up the debate transcripts, edited them himself, and had them published as a book in 1860. It sold tens of thousands of copies, the exact figure disputed across sources, but enough to function as a campaign document carrying Lincoln's argument into Republican homes far beyond Illinois. He had lost the Senate seat and won something more useful: a reputation. The man who had been finished in 1849 was, suddenly, somebody the Republican Party had to reckon with.` },
      { h: `The night they took him seriously`, eyebrow: `Turning point` },
      { p: `Reckoning came on a snowy night in New York City.` },
      { p: `On February 27, 1860, Lincoln spoke at the Cooper Union (a free college in Manhattan; the talk was held in its Great Hall) to an audience of about fifteen hundred. This was enemy intellectual territory, the heart of the Eastern Republican establishment that regarded prairie politicians as provincial curiosities, and Lincoln knew the stakes. He had prepared for months, burying himself in founding-era records back in Springfield to build a single, lawyerly, devastating argument.` },
      { p: `The argument went after the Southern claim that the Founding Fathers had never meant for the federal government to control slavery in the territories. Lincoln took the thirty-nine men who signed the Constitution and went through them one by one, showing from the historical record how they had actually voted and acted on the question. His tally: a clear majority of the framers had, in their own careers, treated the federal government as having the power to restrict slavery's spread. Far from violating the Founders' design, restricting slavery in the territories *was* the Founders' design. It was not a sermon; it was a brief, the kind of patient, evidence-stacked case a good lawyer builds, and it dismantled the opposition's history in front of the most demanding audience in the country. He closed on a line that has outlived everything around it:` },
      { p: `"Neither let us be slandered from our duty by false accusations against us, nor frightened from it by menaces of destruction to the Government nor of dungeons to ourselves. LET US HAVE FAITH THAT RIGHT MAKES MIGHT, AND IN THAT FAITH, LET US, TO THE END, DARE TO DO OUR DUTY AS WE UNDERSTAND IT."`, q: true },
      { p: `The room came apart. The editor Horace Greeley, whose *New-York Tribune* was the most widely read Republican newspaper in the country, called it "one of the most happiest and most convincing political arguments ever made in this City" and judged that no man had ever made such an impression on a first appearance before a New York audience. Several New York papers printed the speech in full, and others reprinted it in Chicago, Detroit, and Albany. New England Republicans, suddenly curious, invited him north, and Lincoln went on a tear, speaking in eleven cities in twelve days. The historian Harold Holzer, who wrote the standard book on the speech, calls Cooper Union the event that turned Lincoln from a regional figure into a national phenomenon, and that is about right.` },
      { p: `That same afternoon, before the speech, the photographer Mathew Brady made a now-famous portrait of Lincoln, the one that softened his gangly frame into something statesmanlike. Lincoln is often quoted as crediting "Brady and the Cooper Institute" with making him president. It's a good line, but it surfaces secondhand and can't be firmly verified, so it's best treated as something he may have said rather than something he certainly did. What is certain is the effect. After Cooper Union, the East stopped laughing.` },
      { fig: '/war-img/lincolns-rise-hero-cooper-union-brady.jpg', cap: `Lincoln photographed by Mathew Brady the afternoon of February 27, 1860, before he delivered the Cooper Union address. The image spread across Republican newspapers nationwide within days.`, credit: `Mathew B. Brady · photograph · February 27, 1860 · Library of Congress · public domain` },
      { h: `The dark horse in the Wigwam`, eyebrow: `Turning point` },
      { fig: '/war-img/lincolns-rise-wigwam-convention-1860.jpg', cap: `The Republican National Convention, Chicago, May 1860. The Wigwam, a vast temporary wooden hall built for the occasion. Lincoln stayed home in Springfield; his managers worked the floor through the night.`, credit: `Library of Congress Prints & Photographs Division · wood engraving · 1860 · public domain` },
      { fig: '/war-img/lincolns-rise-wide-awake-certificate-1860.jpg', cap: `A Wide-Awake Club membership certificate, 1860. Lincoln and Hamlin preside from the upper corners; uniformed members with torches march below. The Wide-Awakes were the Republican youth movement that electrified the Northern campaign.`, credit: `Library of Congress Prints & Photographs Division · lithograph · 1860 · public domain` },
      { p: `When the Republicans gathered to pick their presidential nominee, the single candidate the party would run in the general election, in May 1860, Lincoln was not the favorite. He was barely in the conversation.` },
      { p: `They met in Chicago, in a vast temporary wooden hall thrown up specifically for the convention and nicknamed "the Wigwam," big enough to pack in something like ten thousand people. The obvious choice was Senator William H. Seward of New York, a former governor and the most nationally prominent Republican alive. But Seward carried baggage. He had a reputation as a radical (he had spoken of a "higher law" than the Constitution and of an "irrepressible conflict" over slavery, phrases that thrilled antislavery zealots and alarmed everyone trying to win a general election), he had alienated nativist voters (those who wanted to restrict immigration and limit the rights of the foreign-born) and German immigrant voters alike, and he had made personal enemies, including the same Horace Greeley who had cheered Lincoln at Cooper Union. Seward faced several other serious contenders too, governors, senators, and a former congressman from Ohio, Missouri, and Pennsylvania, but none of them was the real obstacle.` },
      { p: `Lincoln's path ran straight through Seward's weaknesses. He was a moderate, opposed to slavery's spread but not calling for its immediate abolition where it already existed, which made him far less frightening to the cautious voters of the lower North whom Republicans needed to flip. He was the favorite son of Illinois, a critical swing state. And he had a shrewd campaign team that understood the math: nobody was likely to win on the first ballot, so the goal was to be everybody's acceptable second choice. Lincoln's managers worked the delegates through the night, cut deals, and (in a detail that says something about nineteenth-century conventions) reportedly printed up counterfeit tickets to pack the Wigwam's galleries with roaring Lincoln supporters. Lincoln himself never showed up; he stayed home in Springfield and waited.` },
      { p: `The balloting bore the strategy out. On the first ballot Seward led with 173½ votes to Lincoln's 102. On the second, Lincoln surged to a near-tie, and the hall began to understand what was happening before the tally was finished: delegations that had been parked with favorite sons started shifting, the anti-Seward men sensing they finally had a candidate who could win. On the third ballot they broke decisively Lincoln's way, and he took 350 of the 466 votes, well past the majority he needed. The most famous Republican in America had been beaten by a one-term former congressman from the prairie whose chief asset was that almost nobody disliked him. The convention added Senator Hannibal Hamlin of Maine as his running mate, the candidate for vice president, who would serve alongside him if they won, and the dark horse was now a nominee.` },
      { h: `Four men, one ballot, no center`, eyebrow: `Turning point` },
      { fig: '/war-img/lincolns-rise-political-quadrille-1860.jpg', cap: `"The Political Quadrille," 1860: all four presidential candidates dancing to Dred Scott's fiddle. The four-way race handed Lincoln the presidency on less than 40 percent of the popular vote.`, credit: `Popular Graphic Arts / Library of Congress · lithograph · 1860 · public domain` },
      { p: `Here is the part a newcomer has to slow down for, because it is the whole machinery of how a man could become president with about forty percent of the vote and not a single Southern state. The election of 1860 was not Lincoln against one opponent. It was a four-way wreck, and the wreck was mostly the Democrats' own doing.` },
      { p: `The Democratic Party was the only truly national party left (the Republicans were a frankly Northern party with no real voters in the South, so the Democrats alone still had supporters in both halves of the country). And that national party tore itself apart over exactly the issue the Freeport debate had exposed. The Democrats first met in Charleston, South Carolina, in the spring of 1860. Douglas was the front-runner, but Southern delegates (the representatives each state sent to vote at the convention) demanded a party platform, the official list of positions the party commits to running on, that explicitly endorsed the *Dred Scott* decision and promised a federal slave code protecting slavery in every territory, the ironclad guarantee Douglas had refused to give. Northern delegates wouldn't accept it. Fifty-one Southern delegates walked out, whole delegations from the Deep South marching off the floor, and the convention broke up without naming anyone. The party reconvened weeks later in Baltimore, and the Southerners walked out *again*. What was left of the convention nominated Stephen Douglas as the Northern Democratic candidate. The Southerners who had bolted held their own convention and nominated their own man, the sitting Vice President of the United States, John C. Breckinridge of Kentucky (Democrat), on a platform of full federal protection for slavery everywhere.` },
      { p: `So the Democrats now had two candidates, one for the North and one for the South, splitting the only party that could plausibly have beaten Lincoln. And there was a fourth man in the race: John Bell of Tennessee, running for the brand-new Constitutional Union Party, a refuge for old Whigs and others who wanted to dodge the slavery question entirely and simply stand for "the Constitution, the Union, and the laws." It is worth being clear-eyed about what that dodge meant: in 1860, to say nothing about slavery's expansion was to leave the institution exactly as it was, protected and intact. Silence was its own kind of answer, and a comfortable one for anyone who wanted no interference with slavery. Bell's pitch was aimed at the nervous border states, the slaveholding states wedged between North and South that had not seceded and feared, correctly, that this whole argument was about to blow the country apart.` },
      { p: `Now here is how the pieces fell. In the North, Lincoln faced mainly Douglas. In the South, the fight was between Breckinridge and Bell, and Lincoln was not even a factor, because in ten Southern states the Republican Party hadn't organized at all and Lincoln's name did not appear on the ballot. You could not have voted for him in Alabama or Georgia or Texas if you had wanted to. The country was holding two different elections at once, and Lincoln was running in only one of them.` },
      { p: `And the Republicans were not running on slavery alone, which is the piece that made their Northern coalition durable. Their 1860 platform offered the free-labor North a whole economic program: a homestead act to hand free western land to settlers, a protective tariff to shield Northern manufacturers and workers, and federal aid for a transcontinental railroad to the Pacific. Those planks pulled in Midwestern farmers, German immigrants, and Eastern workingmen who cared as much about land and wages as about slavery. It was a broad Northern coalition that happened to be flatly incompatible with the Southern slaveholding interest, which is exactly why the South's sense that it was being shut out of the country's future was not paranoia. The numbers, the territory, and the economic momentum were all tilting North.` },
      { p: `That is the mechanism, and it runs on a rule a newcomer has to understand: the Electoral College. The president is not chosen by a single national vote count. Each state runs its own popular vote and is assigned a number of electoral votes, allotted roughly by population. And in almost every state it is winner-take-all: the candidate who wins that state, even by a single vote, collects *all* of its electoral votes, and second place gets nothing. Fifty-one percent and ninety percent pay exactly the same. So a candidate who wins a big Northern state like New York by a hair pockets every one of its electoral votes; a candidate who runs second everywhere collects almost none, because second place is worth zero.` },
      { p: `Now the geography does its work. The Northern states held the larger share of the population, and therefore of the electoral votes. With Lincoln's opposition in the North divided between Douglas and the others, Lincoln only had to come in first, not win a majority, to take each Northern state whole. And here is the cruelty of the split for the Democrats: together, Douglas and Breckinridge held a clear majority of the national popular vote, but they were running as two men, not one. In the Northern states that decided the election, neither Douglas nor Breckinridge alone could out-poll Lincoln; the anti-Lincoln vote was divided between them, so Lincoln finished first in state after state and swept all their electoral votes, while his rivals split the leftovers and collected almost nothing. If a single Democrat had carried all of Douglas's and Breckinridge's votes, that candidate might have beaten Lincoln outright in several Northern states and changed the whole result. Two candidates couldn't. That is how a four-way race with about forty percent of the vote produced a decisive, lopsided win.` },
      { fig: '/war-img/lincolns-rise-national-game-1860.jpg', cap: `"The National Game. Three Outs and One Run," Currier & Ives, September 1860. Lincoln's bat is labeled "Equal Rights and Free Territory." The other three struck out.`, credit: `Currier & Ives (attr. Louis Maurer) · lithograph · September 1860 · Library of Congress · public domain` },
      { h: `A clear majority, a divided country`, eyebrow: `Consequence` },
      { fig: '/war-img/lincolns-rise-electoral-map-1860.png', cap: `The 1860 electoral map. Lincoln swept the free North and won 180 electoral votes (well past the 152 needed) without a single electoral vote from any slave state.`, credit: `ElectoralCollege1860 · Wikimedia Commons · public domain` },
      { p: `On November 6, 1860, Americans voted in numbers never seen before, better than eight in ten eligible voters turned out, the highest share in the nation's history to that point. They were voting as if they understood that this one mattered.` },
      { p: `The popular vote tells the story of a fractured country. Lincoln won roughly 1.86 to 1.87 million votes, just under forty percent of the national total. The remaining sixty percent was scattered across his three rivals, with Douglas a distant second. (The exact popular-vote totals from 1860 are genuinely disputed; nineteenth-century counts were ragged, and different authorities give meaningfully different numbers, especially for Douglas, whose share is often put around 1.38 million, or roughly 29 percent, in the most-cited modern tabulation. The point that survives every version is that Lincoln won well under half the popular vote.)` },
      { p: `The electoral vote tells the other half of the story, and there the result was not close at all. Lincoln carried 180 electoral votes, sweeping nearly the entire free North, when he needed only 152 to win. Breckinridge, the Southern Democrat, took the Deep South. Bell took three border states. And Douglas, who finished *second* in the popular vote nationwide, won almost nothing in the electoral count, carrying only Missouri and a sliver of New Jersey. That is the winner-take-all rule at its most merciless: Douglas had broad, shallow support spread thin across the whole country, and broad-but-thin wins no states outright, so it converts into almost no electoral votes at all. Coming in a strong second everywhere is worth nearly nothing in a system that pays only first place.` },
      { p: `Now hold the two numbers side by side, because the gap between them is the whole tragedy. Lincoln had won a clean, undisputed majority of the electoral votes, a decisive and entirely lawful victory. And he had done it without a single electoral vote from any slave state, the first time a winning presidential ticket had ever been built purely on the North, with no Southerner and no Southern support anywhere on it. To the slaveholding South, this was the nightmare made real. A man who was not even on most of their ballots, who had won barely a third of the votes that had actually been cast and not one of theirs, was now going to be their president.` },
      { p: `And it is worth naming exactly what the South believed it was losing, because the loss was not abstract. For a generation, the South's grip on national power had been the grip of the slaveholding interest on federal policy, the machinery that had delivered the Fugitive Slave Act, the *Dred Scott* ruling, a friendly Supreme Court, and a steady Southern hand on the cabinet and the foreign service, all of it keeping slavery protected, expanded, and constitutionally entrenched. Lincoln's election, even before he had taken a single action, signaled that this machinery was breaking down: a president had won the highest office in the land while running explicitly on halting slavery's spread, and he had done it without needing the South at all. By the ordinary rules of the republic, his election was as legitimate as any in the country's history. The South's own newspapers and politicians nonetheless reached for the language of violation, South Carolina's legislature calling the result a hostile act, and treated a lawful constitutional election as if it were a coup. It was not a coup. It was a count. But to a section that had run the federal government's slavery policy for decades and just lost the means to keep running it, a lawful forty-percent victory, achieved without breaking a single rule, landed like a revolution. That is the engine of everything that came next.` },
      { fig: '/war-img/lincolns-rise-buchanan-1860.jpg', cap: `President James Buchanan in 1860, the lame-duck commander in chief who declared secession illegal and then spent four months doing nothing to stop it.`, credit: `Meade Brothers · photograph · 1860 · public domain` },
      { h: `Secession winter`, eyebrow: `Consequence` },
      { fig: '/war-img/lincolns-rise-charleston-mercury-1860.jpg', cap: `The Charleston Mercury "Extra," December 20, 1860: the day South Carolina voted 169 to 0 to dissolve its bond to the United States. They printed the headline the same afternoon.`, credit: `Charleston Mercury · broadside · December 20, 1860 · public domain` },
      { p: `The earthquake came fast. Lincoln had won an election, not yet taken an office, and the country began coming apart anyway.` },
      { p: `First, the word itself, because it is the central act of everything that follows: **secession** is the act of a state formally declaring that it is leaving the United States altogether, dissolving its bond to the nation as if the union of state and country could simply be cut. That is what now began, state by state.` },
      { p: `South Carolina went first. On December 20, 1860, barely six weeks after the election and months before Lincoln could so much as take the oath, a special state convention, an elected body assembled for the single purpose of deciding the question, voted, 169 to nothing, to dissolve South Carolina's bond to the United States. The declaration the state issued a few days later did not bother to disguise the reason. It named the "increasing hostility" of the free states to slavery and the election of a president "whose opinions and purposes are hostile to slavery." They were seceding, in their own words, because Lincoln had been lawfully elected and because they would not live under a government that might one day limit slavery.` },
      { p: `Then the Deep South went in a rush, and the rush is the thing to feel. Mississippi left on January 9, 1861, Florida on the 10th, Alabama on the 11th, Georgia on the 19th, Louisiana on the 26th, Texas on February 1; for stretches of that winter, a state walking out of the United States every few days. The North woke up to a new departure on its breakfast table again and again, until a thing that was supposed to be unthinkable began to feel almost routine, a tide going out. Seven states had declared themselves gone, and every one of them did it before Lincoln had any power to do anything about it, because he was not yet president.` },
      { p: `That was the cruelest mechanism of the whole winter: the calendar. Lincoln had been elected in November, but under the rules then in force he would not be inaugurated until March 4, 1861, leaving nearly four months in which the man the country had just chosen had no authority whatsoever, and the man still holding the office had no intention of using his. The president for those four months was James Buchanan (Democrat), a lame duck (an officeholder already voted out or on his way out, still technically in power but politically spent). Buchanan's response to the gravest crisis in the nation's history was to split the difference into paralysis. Secession, he declared, was unconstitutional and illegal; no state had the right to leave. But, he also declared, the federal government had no power to stop a state from leaving; the sword, he said, had not been placed in the government's hand to hold the Union together by force. Illegal but unstoppable: it was the perfect formula for doing nothing, and Buchanan did nothing, watching from the White House as Southern authorities seized federal forts, arsenals, and customs houses across the South. Northerners watched too, reading each day's dispatches, and what they were watching was the federal government being looted in plain sight by men its own president had just declared to be acting illegally, while that president stood aside.` },
      { p: `There was one brief, telling exception. In early January, Buchanan authorized a single, half-hearted move: he sent an unarmed civilian merchant steamer, the *Star of the West*, chosen precisely so it would look less like a warship, to slip supplies to the U.S. soldiers still holding Fort Sumter (a U.S. Army fort on an island in Charleston Harbor, now ringed by a South Carolina that had just left the Union, its small garrison effectively surrounded). On January 9, 1861, as the ship tried to enter the harbor, South Carolina shore batteries opened fire on it. The ship took a few hits, did an about-face, and steamed back to New York with its supplies undelivered. It is sometimes called the first time Southern guns fired on the United States flag. It did not start the war (the standoff at Sumter would simmer on into the spring), but it showed exactly how far Buchanan's policy of hand-wringing had gotten him: federal soldiers fired upon, the resupply turned back, and the president doing essentially nothing in response.` },
      { p: `Washington's last real hope for peace was a bargain, and the bargain died in Lincoln's lap. In December, Senator John Crittenden of Kentucky, a veteran deal-maker who had spent a long career trying to hold the Union together by compromise, proposed a sweeping set of constitutional amendments that would, among other things, revive the old line dividing free from slave territory (the boundary the Missouri Compromise had drawn a generation earlier) and extend it clear to the Pacific, guaranteeing slavery federal protection south of it, in lands "now held, or hereafter acquired," and forever barring Congress from abolishing slavery in the slave states. This was the kind of grand compromise that had patched the Union together before. And this is where the long American habit of papering over slavery finally ran out of paper: the era of compromise, Clay, Webster, the Missouri line, forty years of buying the Union a few more decades each time, was over, and it died on this proposal, because the proposal ran into Lincoln. From Springfield, the president-elect quietly but flatly instructed Republican leaders in Congress to give no ground on the central point. "Entertain no proposition for a compromise in regard to the extension of slavery," he wrote to Congressman William Kellogg on December 11, 1860; the moment they did, he warned, they would "lose us everything we gained by the election." He would not bargain away the one thing his whole campaign had stood for, the containment of slavery, the promise to stop its spread west, even to buy peace. With Republicans holding firm at his direction, the Senate rejected the Crittenden Compromise on January 16, 1861, every one of the votes against it cast by a Republican, and it failed again when a last-ditch peace conference and a final Senate effort took it up early the following March. The compromises were finished.` },
      { p: `So picture where things stand as the winter grinds toward March. Seven states have walked out, federal property is being seized, shots have been fired on a federal ship, and the last compromise is dead. And picture the man at the center of it: Abraham Lincoln, still in Springfield, not yet president, sitting in the quiet of his law office or his temporary headquarters while the telegraph brings him the news of another state gone, another fort seized, the Union he has just been elected to lead coming apart a piece at a time. He says little in public and commits to nothing in detail, partly by temperament, partly by hard calculation: any reassurance he offers the South will fracture the coalition that just elected him, and any threat he makes will speed the breakup. So he waits. The underestimated outsider who rose from a lost Senate race to the presidency in twenty-four months has won a country that is already, in fact if not yet in full, dissolving beneath him, and he cannot lift a finger to stop it until he takes the oath on March 4.` },
    ],
    meanwhile: {
      region: `Montgomery, Alabama`,
      title: `Two Governments`,
      body: `While Lincoln waits powerless in Springfield, the seven seceded states are already gathering in Montgomery to build a government, write a constitution, and choose a president of their own, and to name, out loud, exactly what the new nation is for.`,
    },
  },
}

export default function LincolnsRiseThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="lincolns-rise"
      battleName="Lincoln's Rise & the Election of 1860"
      theatreId="offfield"
      battleId="th-lincoln1860"
      theatreHref="/war-civil-war/off-the-battlefield"
      accent={ACCENTS.otbf}
      heroImage="/war-img/lincolns-rise-hero-cooper-union-brady.jpg"
      heroPalette={["#2b2218","#3a3026","#0c0a07"]}
      heroCredit={`Mathew B. Brady · February 27, 1860 · Library of Congress · public domain`}
      heroFocus="center 20%"
      heroScale={1}
      endHref="/war-civil-war/off-the-battlefield"
      endKicker={`The outsider wins`}
      endLabel={`Back to Off the Battlefield`}
    />
  )
}
