'use client'

// Battle of the Wilderness — battle sections. Produced through the war content
// pipeline (audits/war-content-pipeline.md): fact pack → author → fact-check +
// storytelling critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const WILDERNESS_NARR: Record<string, Narr> = {
  'the-thicket': {
    eyebrow: 'Wilderness · May 4',
    title: 'The woods Lee picked on purpose',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -78.5, lonMax: -76.7, latMin: 37.7, latMax: 38.9 },
        states: [
          { name: 'Virginia', tone: 'focus', label: 'VIRGINIA', labelLon: -78.2, labelLat: 37.9 },
          { name: 'Maryland' }, { name: 'West Virginia' }, { name: 'North Carolina' }, { name: 'Tennessee' },
        ],
        dots: [
          { name: 'Wilderness', date: 'May 5–7, 1864', lat: 38.32, lon: -77.73, heavy: true, anchor: 'end' },
          { name: 'Germanna Ford', lat: 38.408, lon: -77.747, color: '#8a8175', anchor: 'middle', dy: -16 },
          { name: 'Spotsylvania Court House', lat: 38.195, lon: -77.588, color: '#8a8175', anchor: 'start' },
          { name: 'Fredericksburg', lat: 38.3032, lon: -77.4605, color: '#8a8175', anchor: 'start' },
        ],
      } },







      { h: 'Why a general would choose to fight in a place nobody could see', eyebrow: 'May 4' },
      { p: 'One thing to fix in your head first, because the rest of the story leans on it. By 1864 the United States had split in two and was three years into a civil war. Eleven southern states had seceded (broken away) and formed their own country, the Confederacy (called here “the South”), and they were fighting the states that stayed loyal to the old United States, the Union (“the North”). Officers in this story are tagged with the side they fought for: (North) for the Union, (South) for the Confederacy.' },
      { p: 'The Wilderness was not a place you would pick for a battle. It was a place you would pick to get lost in. A few miles west of Fredericksburg, Virginia, in Spotsylvania and Orange counties, the land went bad in a particular way: a dense, second-growth thicket of scrub oak, pine, and tangled underbrush so thick that a man could not see more than a few yards in any direction. Whole armies would disappear into it. The National Park Service has a phrase for what the fighting there became, “bushwhacking on a grand scale,” isolated little knife-fights between small clumps of men who could not find the rest of their own army, all of them “confused by the bewildering forest.”' },
      { fig: '/war-img/wilderness-overview.png', cap: 'The Wilderness, a few miles west of Fredericksburg: two parallel east-west roads, the Orange Turnpike (north) and the Orange Plank Road (south), crossed by the north-south Brock Road, with the Rapidan and Germanna Ford to the northeast and Spotsylvania Court House to the southeast.', credit: 'Map: Stuff Happened' },
      { p: 'So why fight there? Because one man wanted exactly that. In early May 1864, Lieutenant General Ulysses S. Grant, newly made general-in-chief of all the United States armies, the top soldier in the country, had brought a very large army across the Rapidan (the river marking the northern edge of this country) and pushed it into the woods. His plan was to march through the thicket fast and out into open ground on the far side, where his numbers could tell. And his numbers were enormous: well over 100,000 men, against the roughly 60,000 to 66,000 that General Robert E. Lee had in his Army of Northern Virginia. Grant had nearly twice Lee’s strength.' },
      { p: 'Lee’s answer was to refuse Grant the open ground. He struck inside the thicket, while the Union army was still strung out crossing it, before it could clear the trees. In the open, Grant’s extra men and his roughly 316 cannon would have crushed him. But in the Wilderness, cannon could not be aimed (there was nothing to aim at but leaves) and a battle line dissolved into the brush the moment it moved. The terrain erased the difference between a big army and a small one. Lee chose to fight blind, because blind was the only way the math worked.' },
      { p: 'There was an extra ghost in these particular woods. Just one year earlier, on nearly this same ground, Lee had won the masterpiece of his career at Chancellorsville, and it was there that his great lieutenant, Thomas “Stonewall” Jackson, had been shot by his own men in the dark. The Wilderness was about to echo that story almost exactly.' },
      { pill: '/war-civil-war/eastern/chancellorsville', plabel: 'Chancellorsville: the victory a year before, on the same ground' },
    ],
    meanwhile: { region: 'the Overland Campaign', title: 'The new kind of war Grant brought', body: 'Every Union general before Grant had fought Lee the same way: take a beating, then fall back across the river to refit and lick wounds. Grant intended to do the opposite. His whole campaign, later called the Overland Campaign, the drive on the Confederate capital at Richmond, was built on never letting go. He meant to fight Lee continuously, day after bloody day, and grind his army into the ground. The target was not a city or a road. The target was Lee’s army itself. That single change in intent is what made the Wilderness the opening move of the end, and not just one more inconclusive bloodletting in Virginia.' },
  },

  'the-two-roads': {
    eyebrow: 'Wilderness · May 5',
    title: 'First contact in the brush',
    blocks: [
      { h: 'Two parallel roads, a crossroads, and a day with no winner', eyebrow: 'May 5' },
      { p: 'To understand this battle you only need two roads and the crossing between them. Both ran roughly east-west through the thicket, out toward Orange Court House in the west, where Lee was coming from, and toward Fredericksburg in the east. They ran about 2 miles (3 km) apart, with the dense woods filling the gap between. The northern one was the Orange Turnpike. The southern one was the Orange Plank Road (a “plank road” being just that, a road surfaced with wooden planks). And cutting across both of them, running north-south, was the Brock Road, the road the Union army needed if it wanted to keep marching south, toward a little place called Spotsylvania Court House. Where the Plank Road met the Brock Road was the single most important spot on the field. Hold that crossroads and your army stayed in one connected piece; lose it and Lee could split the Union force in two.' },
      { p: 'On the morning of May 5, the northern road went first. Down the Orange Turnpike came the corps of Lieutenant General Richard S. Ewell (South), a corps being one of the big building-block chunks an army is divided into, ten or twenty thousand men under one general. (A corps splits into divisions, divisions into brigades, brigades into regiments, biggest to smallest; every unit named below is one of those nesting pieces.) Ewell ran straight into the V Corps of Major General Gouverneur K. Warren (North) near Saunders Field, one of the few open clearings in the whole tangle. Major General George G. Meade (North), who commanded the Army of the Potomac (the main Union army in Virginia) on the ground while Grant rode along setting the strategy, ordered an attack across that dreadful terrain. Ewell’s men, dug into hasty earthworks (dirt barricades thrown up fast), threw it back. Out in the brush the attack fell apart on its own: gaps tore open between regiments, whole companies lost any sense of which way was forward, and men squeezed off shots into their own comrades, never seeing them as anything but a shape in the leaves. The fighting see-sawed all day with nobody able to land a decisive blow.' },
      { p: 'Two miles south, the Plank Road told a similar story with higher stakes. Down it came the corps of Lieutenant General Ambrose Powell (“A.P.”) Hill (South), aiming for that all-important crossroads. Union cavalry (mounted scouts) spotted him coming, and the division of Brigadier General George W. Getty (North) raced to grab the Plank Road and Brock Road crossing before Hill could take it. Around 4:15 in the afternoon Getty attacked, with the big II Corps of Major General Winfield S. Hancock (North) arriving to pile in alongside him. What followed was brutal, close-range fighting in brush so thick the enemy was often just a muzzle flash a few feet away. It ran into the night with no decision. Brigadier General Alexander Hays (North) was killed here, shot mid-sentence while he was addressing the 63rd Pennsylvania, one of his own regiments.' },
      { p: 'When the firing finally guttered out on May 5, neither side had won anything you could point to. It had been a confused, bloody draw. But it had left A.P. Hill’s corps badly tangled, poorly placed and disorganized along the Plank Road, having fought all afternoon and never sorted itself out. That mess would matter at dawn.' },
    ],
  },

  'longstreet-attacks': {
    eyebrow: 'Wilderness · May 6',
    title: 'The day of the great attacks',
    blocks: [
      { h: 'Hill nearly breaks, Longstreet saves him, and the woods repeat a year-old horror', eyebrow: 'May 6' },
      { p: 'The second day opened with the Union nearly winning the whole thing before breakfast. Around five in the morning, Major General Winfield S. Hancock (North) and Brigadier General George W. Getty (North) attacked straight down the Plank Road and slammed into the exhausted, disorganized corps of Lieutenant General Ambrose Powell (“A.P.”) Hill (South) from the night before. Hill’s line came apart. His men fell back in confusion, and for a few minutes Lee’s entire right wing, the southern end of his line along the Plank Road, teetered on the edge of total collapse.' },
      { p: 'What held it together first was a single open field and twelve guns. At the Widow Tapp farm, a small clearing just behind Hill’s crumbling line, twelve Confederate cannon under one artillery colonel stood out in the open and fired canister (a can packed with musket balls that turns a cannon into a giant shotgun) straight down the Plank Road, buying minutes against Hancock’s advance.' },
      { p: 'And then, around six in the morning, the rescue arrived. The First Corps of Lieutenant General James Longstreet (South), Lee’s most trusted lieutenant, the man he called his “Old War Horse,” came up at the end of a hard night march; his corps had started the battle some 10 miles (16 km) away. At the head of the column was the Texas Brigade. Lee, seeing his line saved at the last instant, rode forward to lead the counterattack in person, waving his hat and shouting that the Texans always carried any position they were sent against. His own soldiers would not have it. They refused to advance until he went back to safety, some grabbing the reins of his horse, Traveller, and Longstreet talked him into a safer spot behind the line. (This is the famous “Lee to the rear” episode, the traditional name for the moment; the soldiers halting his horse is the verified part.) The counterattack then went in: two of Longstreet’s divisions drove the Union line back through the woods. The Texas Brigade was wrecked doing it, by one account only about 250 of some 800 men coming through unhurt. Brigadier General James S. Wadsworth (North) was mortally wounded as the Confederate advance pushed his command back. Between the two roads, the IX Corps of Major General Ambrose E. Burnside (North), reporting straight to Grant rather than to Meade, fed in piecemeal through the same blinding woods, too slowly to tip the morning.' },
      { fig: '/war-img/wilderness-may6.png', cap: 'May 6: Hancock’s dawn assault breaks A.P. Hill on the Plank Road before Longstreet’s First Corps arrives; the unfinished railroad bed south of the road lets four Confederate brigades curl around Hancock’s exposed left flank.', credit: 'Map: Stuff Happened' },
      { p: 'Then Lee’s army found the door nobody had thought to lock. Around ten in the morning, Lee’s chief engineer, Major General Martin L. Smith (South), came back from scouting the brush with a report that changed the day. South of the Plank Road, hidden in the trees, ran an unfinished railroad bed, a long graded cut where a railroad had been started and never built. It was open. It was unguarded. And it pointed like an arrow straight around the flank of Hancock’s line. (A flank is the exposed end of a battle line, the side rather than the front; get around a flank and you can fire down the whole length of the enemy’s line instead of butting into the front of it.) Hancock’s men were facing west, braced for the next blow to come at their front, and this graded ditch led to the one place they were not looking, their open southern end.' },
      { p: 'Around eleven, a staff officer led four brigades quietly up that hidden railroad bed, formed them in the trees, and turned them loose into Hancock’s unguarded left. The surprise was total. An order meant to guard that flank had miscarried somewhere in the chain, so there was nothing waiting. The Union line came apart from the end, collapsing sideways, one unit folding into the next, the whole formation peeling up the way a strong wind lifts the corner of a tarp. Hancock fell back to his log breastworks (chest-high barricades of piled timber) along the Brock Road, and later said the attack had rolled up his line, in his own words, like a wet blanket.' },
      { p: 'Then the woods reached for their year-old echo. Riding forward on the Plank Road to press the broken Union army, Longstreet (South) was shot by his own men. In the smoke and brush, one of his own regiments had become separated from the rest; when it came back toward the road, its own side mistook it for Federals, and two bodies of Confederate troops fired on each other, catching Longstreet’s mounted party in the crossfire. A bullet tore through his throat and into his shoulder. He survived, but he was out of the war for roughly five or six months. In the same volley, Brigadier General Micah Jenkins (South) was struck in the forehead and mortally wounded; he lingered for hours and died without ever regaining his senses. It had happened in the same woods, in the middle of a successful flank attack, almost exactly a year after Thomas “Stonewall” Jackson had been shot down by his own men at Chancellorsville nearby: both corps commanders, both cut down by friendly fire on the brink of victory, in this same tangle of trees. With Longstreet down, the great Confederate attack lost its grip and stalled.' },
      { p: 'The day still had two blows left. In the late afternoon Lee threw a renewed assault at Hancock’s Brock Road breastworks; a fire broke out in the log works and for one moment Confederate flags went up on the barricade itself, but the works held, and a Union counterattack drove the breach back out within about an hour. Then, as evening came on, the northern road flared one last time: around 5:30 p.m. Brigadier General John B. Gordon (South) struck the far Union right, a flank that had been left hanging in the air. Out of the dusk his attack crumpled the Union line and swept up two captured generals, and for a few minutes it threatened to roll the whole northern end of the army into ruin. But darkness and the woods did to Gordon what they had done to everyone all day: they swallowed his momentum, and the Union line re-formed in the dark before a crumpled flank could become a rout.' },
    ],
    meanwhile: { region: 'between the lines', title: 'The woods on fire', body: 'The defining horror of the Wilderness was the fire. Muzzle flashes and bursting shells set the dry leaves and underbrush ablaze, and the fires spread through the woods between the lines, into the no-man’s-land where the wounded lay. Men too badly hurt to crawl away were burned to death where they had fallen, and they were men of both sides. At Saunders Field, soldiers fought hand-to-hand at the guns while the field caught fire around them and the wounded burned. The National Park Service describes fires blazing through the forest, hot acrid smoke rolling up, searing the wounded trapped between the lines, “a fitting conclusion to a grisly engagement.” Nobody planned it, and neither side could stop it.' },
  },

  'the-turn': {
    eyebrow: 'Wilderness · May 7',
    title: 'The night Grant turned south',
    blocks: [
      { h: 'The first time a Union army did not flinch', eyebrow: 'May 7' },
      { p: 'By the morning of May 7 the two armies sat in their trenches, glaring at each other across the smoking woods. Tactically, the Wilderness had been a draw with a Confederate edge: Lee had stopped a far larger army on ground he had chosen, and he had done it while losing only about half as many men. The arithmetic was lopsided. The Union had lost somewhere around 17,500 to 18,000 men, killed, wounded, and missing. Lee’s loss is genuinely uncertain in the records, somewhere in the range of roughly 11,000, with some accounts running as low as about 8,000. Either way, Grant had lost close to twice what Lee had. By every rule of the previous three years, this was a defeat, and the next move was a retreat back across the Rapidan.' },
      { p: 'Grant did not retreat.', i: true },
      { p: 'He judged Lee’s earthworks too strong to storm head-on, so he chose to maneuver instead, and the direction he chose is the hinge of the entire war in the East. Rather than recross the river to safety, he ordered the pontoon bridges (the army’s portable floating bridges) at Germanna Ford, the Rapidan crossing the army had entered through, taken up, the unmistakable sign that he was not going back, and pointed the army southeast, around Lee’s right flank, toward Spotsylvania Court House about 10 miles (16 km) away. The point was to stay between Lee and Richmond and force the next fight on his own terms. It was the first time the Army of the Potomac had stayed on the offensive after an opening battle with Lee in Virginia.' },
      { fig: '/war-img/wilderness-the-turn.png', cap: 'The night of May 7: rather than recross the Rapidan at Germanna Ford to the northeast, Grant orders the bridges taken up and marches southeast, around Lee’s right, toward Spotsylvania Court House, staying between Lee and Richmond.', credit: 'Map: Stuff Happened' },
      { p: 'The soldiers felt it before they understood it. On the night of May 7 the exhausted army filed out of its trenches and marched, and at a certain fork in the road the men found the column turning south, toward the enemy, instead of north toward the river and home. As the realization rolled down the ranks that they were advancing and not retreating, the army broke into cheering, and on the dark road they sang. After three years of bleeding Lee and falling back, the Army of the Potomac finally had a commander who would not turn around. Lee read Grant exactly: he guessed Grant would make for Spotsylvania Court House, and he got there first and dug in, which opened the next battle.' },
      { pill: '/war-civil-war/eastern/spotsylvania', plabel: 'Spotsylvania Court House: where the race south led next' },
    ],
  },

  'what-it-was-for': {
    eyebrow: 'Wilderness · The meaning',
    title: 'The men marching back across their own bondage',
    blocks: [
      { h: 'What the relentlessness was for', eyebrow: 'The meaning' },
      { p: 'The Confederacy fought to preserve and extend slavery. Eleven states had broken away from the United States rather than accept any limit on the enslavement of Black people, and Lee’s Army of Northern Virginia was the military shield of that slaveholding republic, the thing standing between four million enslaved people and their freedom. Grant’s new way of war, the refusal to ever let Lee rest, was aimed at destroying that shield. He could trade about 18,000 of his men for about 10,000 of Lee’s and keep marching south because the Union was no longer fighting to win a battle and go home. It was fighting to break the slaveholders’ army for good and end the institution it protected.' },
      { p: 'The most literal proof of that was in the line of march. The army that pushed into the Wilderness contained an all-Black division of United States Colored Troops, formerly enslaved and free Black men in Union uniform, part of Burnside’s (North) IX Corps, the first Black combat division to march with the Army of the Potomac, which had paraded past President Abraham Lincoln in Washington on its way to the front. One of its regiments, the 23rd USCT, had been recruited from the free men and ex-slaves of Stafford, Spotsylvania, Orange, Culpeper, and Caroline counties and the city of Fredericksburg, which is to say, from the very ground this battle was being fought on. Men who had been somebody’s legal property in these neighborhoods, in Spotsylvania and Orange, were now carrying Union rifles back across the land of their own bondage.' },
      { pill: '/war-civil-war/off-the-battlefield/usct', plabel: 'United States Colored Troops: the Black soldiers in Grant’s column' },
      { p: 'During the Wilderness itself, that division was guarding the army’s wagon trains, not standing in the main battle line. But the point would land just days later, a few miles south, as the campaign moved on toward Spotsylvania: the 23rd USCT would become the first Black troops to fight Robert E. Lee’s Army of Northern Virginia in directed combat, turning their rifles, for the first time, on the army that existed to keep them enslaved. The men with the most literal stake in the outcome of the entire war were the ones marching back through the woods where they had once been owned.' },
      { p: 'On the map, the Wilderness opened the Overland Campaign, the continuous six-week grind (Wilderness, then Spotsylvania, then North Anna, then Cold Harbor, then the long siege of Petersburg) that pinned Lee’s army down and never let it recover the initiative again. It proved Grant’s strategy worked: the Confederacy could not replace the men it lost, and the Union could, so the very disproportion that looked like a Union defeat was, by Grant’s cold arithmetic, a step toward Confederate collapse. It gutted Lee’s high command, costing him Longstreet for the campaign’s critical phase in a friendly-fire wound that mirrored Jackson’s a year before. And the cheering on the night march was the moment the Union army stopped expecting to lose to Lee. Under all of it ran the fact the railroad junctions and casualty tables can hide: the thicket was the object, and slavery was the reason.' },
    ],
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={WILDERNESS_NARR} id={id} slug="wilderness" battleName="the Wilderness" theatreId="east" battleId="e-wilderness" accent="#7c3aed" />
}
