'use client'

// THEME section — Medicine & Disease (Off the Battlefield, kind=theme). Built through
// the war content pipeline (fact pack → author(Opus) → five gates [fact-check +
// storytelling + comprehensiveness + clarity + Lost Cause/framing] → revise → images).
// Source + gate records: audits/war-pipeline/medicine-*.md. Green accent; no stat
// block, no map. 'use client' is REQUIRED (reads ACCENTS from a client module).
// GENERATED from medicine-final.md by scripts/_build-war-themes.mjs — do not hand-edit
// the prose here; edit the final.md and rebuild.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: `The war's quietest killer`,
    title: `The Killer Was Never the Bullet`,
    blocks: [
      { p: `Here is the thing almost everybody gets wrong about the Civil War, and it's worth getting right before anything else, because it changes the whole shape of the story. Picture the war and you picture the killing: the Minié ball, the bayonet, the cannon, the surgeon's saw working in a bloody tent while a boy bites down on a bullet to keep from screaming. Hold that image, because almost none of it is how the dying actually happened.` },
      { p: `The great killer of the Civil War was not the bullet. It was disease. Roughly two soldiers died of sickness for every one killed in battle; about two-thirds of all the war's military deaths came from illness, not combat. A country boy was far more likely to die of diarrhea in a crowded camp than of anything an enemy did to him. The men knew it, dimly, and hated it; there is no glory in dysentery (a gut disease we'll come to). But the arithmetic is brutal and clear: for every man shot dead on a field, roughly two more wasted away in a tent or a hospital cot, killed by something nobody at the time could even see.` },
      { p: `And there is a second, bitter irony stacked on top of the first. When those men *were* wounded, and when they did go under the surgeon's saw, they were almost always given anesthesia (drugs that put them to sleep so they felt nothing). The medicine of the day was good enough to spare a man the pain of having his leg cut off. It was not good enough to keep the wound from killing him three days later. They had figured out how to stop the pain. They had not figured out what causes infection. That gap (pain control without infection control) is the cruelest fact in Civil War medicine, and it killed tens of thousands of men who survived their operations only to die of the dirt on the surgeon's hands.` },
      { p: `The men and women who tried to fix it deserve to be seen, because what they built mid-war, while the bodies piled up, is the ancestor of every ambulance that has come for anyone since. The cost was real, and it deserves to be felt.` },
      { h: `The boy who died of a children's disease`, eyebrow: `Pressure` },
      { p: `Start with the camps, because that is where most of the dying happened, and it started before the shooting did.` },
      { p: `When the war began, both sides did the same thing: they pulled hundreds of thousands of men off farms and out of villages and threw them together into enormous camps. For a lot of these recruits, this was the first crowd they had ever stood in. Many had "seldom been far from home." They came from isolated farms in the hill country and the backwoods, and that isolation, which had kept them safe their whole lives, was about to get a great many of them killed, because it meant they had never been exposed to the ordinary contagious diseases that a city child shrugs off by age six.` },
      { p: `Here is the mechanism, because it is the saddest one in the whole story. Diseases like measles, mumps, chickenpox, and whooping cough (a violent, suffocating cough that can rack a body for weeks) are what we now call childhood diseases (common contagious illnesses most people catch young, after which the body is immune for life). A boy raised in a town had usually caught them, survived them, and become immune. A boy raised alone on a remote farm had not. So when you packed tens of thousands of those never-exposed country boys into a single camp, you had assembled the perfect kindling for an epidemic. The childhood diseases "came first"; they swept through the ranks before the armies ever met in a serious battle. And measles in particular tore through the camps and killed. Not because measles is ordinarily a great killer, but because grown men catching it for the first time, exhausted, badly fed, and crowded together, sickened hard, and the pneumonia and other complications that followed finished many of them off.` },
      { p: `Put one real face to it, because the records hand us one. Newton Robert Scott was a farm boy from Albia, Iowa, a private (and company clerk) in the 36th Iowa Infantry, and the letters he sent home are a plain witness to how this war actually killed: he wrote of sickness, not Confederates, as the thing emptying the ranks around him, of sick and disabled men "Dieing Every Day" in the Union camps. Scott himself lived. He came home, married Hannah, the girl he'd been writing to, and died an old man in 1925. Thousands of the men he wrote about did not. A young man left his family, marched off to fight for a cause, and died in a tent of a disease that the children back home survived every winter. He never saw the enemy. That is not the exception in this war. That is closer to the rule.` },
      { p: `Why did the camps breed death like this? Because nobody understood the cause. This is the single fact underneath the entire disease catastrophe, and it is important to be fair about it: the doctors were not lazy or stupid by the standards of their own time. They simply did not know what we know. **Germ theory** (the understanding that tiny living microbes, invisible to the naked eye, are what cause infection and contagious disease) had not yet been accepted. Doctors "did not understand germs and did little to prevent infection," because in their picture of the world there was nothing to prevent. They could not fight an enemy they did not know existed.` },
      { p: `So the camps were filthy in ways that look insane to us and looked normal to them. Men dug latrines (the open trench pits used as toilets) too close to the streams they drank from. Water was contaminated. Food was bad. Waste, exposure, and bad hygiene piled up, and into that filth the epidemics came. It was not carelessness exactly. It was ignorance, total and tragic, of the link between dirt and death.` },
      { h: `What was actually killing them`, eyebrow: `Pressure` },
      { p: `If you could go down the rolls of the dead and sort them by cause, here is roughly the order you would find. The number-one killer is one most people have never thought about.` },
      { p: `It was not a dramatic disease. It was diarrhea. **Dysentery** and chronic diarrhea (severe, persistent illness of the gut, with bloody or watery stools, caused by eating and drinking food and water fouled by human waste) were the deadliest category of the entire war. Something on the order of 57,000 deaths were recorded directly to dysentery and diarrhea. And the misery was nearly universal: the Union army reported that more than 995 of every 1,000 men eventually came down with some form of chronic diarrhea or dysentery at some point in the war. Read that again: better than 99 of every 100 men. Almost nobody escaped it. The cause was the same contaminated water and food the camps were swimming in, and since nobody understood that disease passes from human waste into the mouth through dirty water, nobody could stop the cycle. The most ordinary-sounding killer in the whole war (the runs) was the one most likely to get a soldier. In the plainest terms, the war's biggest killer was men drinking each other's filth.` },
      { p: `Behind dysentery came the named fevers and lung diseases. **Typhoid fever** (a bacterial disease spread, like dysentery, through water and food fouled by human waste, producing weeks of high fever) was among the very deadliest; at the time doctors often couldn't tell it apart from other "continued fevers" (their catch-all label for any long-running fever they couldn't identify), lumping different illnesses together because they had no test to distinguish them. **Pneumonia** and respiratory disease (infection deep in the lungs) was a particular killer of two groups: men weakened in freezing winter camps, and the wounded, who often survived their injuries only to be carried off by an infection in the chest. Typhoid and pneumonia together killed well over fifty thousand Union men alone.` },
      { p: `Then there is **malaria** (a disease spread by mosquitoes, marked by recurring waves of fever and chills), which makes a useful contrast, because it shows that "common" and "deadly" are not the same thing. Malaria was everywhere: over 1.3 million cases were recorded, an astonishing number. But it killed comparatively few, something more than 10,000, because there was an actual treatment for it: **quinine** (a bitter drug, made from the bark of the South American cinchona tree, that genuinely worked against malaria). A soldier could catch malaria, shake and sweat through it, take his quinine, and live. He often could not do the same with dysentery. Malaria was the ubiquitous disease men mostly survived; dysentery was the ordinary-sounding one that killed and killed. (Quinine, and the desperate Southern shortage of it, comes back later in this story.)` },
      { p: `And then there are the named horrors that round out the list. **Measles**, already met, the children's disease that became a mass killer of grown country boys. **Smallpox** (a terrifying, disfiguring viral disease), which was feared everywhere; a vaccine for it actually existed, but it was applied unevenly and sometimes badly: the period practice of vaccinating arm-to-arm, taking material from one person's vaccination sore to inoculate the next, could accidentally pass along other infections. Behind those moved a background of yellow fever, tuberculosis, cholera, and scurvy (the disease of vitamin-starved diets). The point is not the catalog. The point is that a soldier in this war walked through a forest of invisible deaths every single day.` },
      { p: `And the forest was not equally deadly to every soldier who walked it. When the Union began enlisting Black men into the **United States Colored Troops** (the USCT, the federal regiments of Black soldiers, most of them recently freed or escaped from slavery), those men died of disease at a staggering rate: roughly 148 of every 1,000 USCT soldiers died of sickness, against about 88 of every 1,000 white Union troops. Some of that gap was where they were sent; Black regiments were disproportionately handed garrison duty in malaria-soaked Southern lowlands and the worst camps. But much of it was deliberate neglect. USCT units were chronically short of doctors; many served their entire enlistment without a surgeon ever assigned to them, because the army offered Black-regiment medical posts no path to promotion and few trained men would take them. The sick were funneled into segregated, under-supplied hospitals. Those disease numbers are usually quoted as one figure for "the soldier." They were never racially even. The men the country was least willing to spend its medicine on died of disease at nearly twice the rate of the men beside whom they fought.` },
      { h: `The soft lead ball that shattered bone`, eyebrow: `Pressure` },
      { p: `Now to the wounds. When the bullet *did* find a man, what it did to him was uniquely terrible, and it explains the surgery that followed.` },
      { p: `The dominant projectile of the war was the **Minié ball** (named for its French co-inventor; Americans said "MIN-ee," though the French original is closer to "min-YAY"), and despite the name it was not a ball at all. It was a cone-shaped bullet of soft lead, roughly .58 of an inch across, fired from a rifled musket (a gun with spiral grooves cut inside the barrel that spin the bullet for far better range and accuracy than the old smoothbore muskets, which were plain-barreled, no grooves, and wildly less accurate). That combination, a soft slug fired with real force and accuracy, made for a wound unlike what earlier wars had produced. When the soft lead hit a man, it flattened and tumbled inside him instead of punching cleanly through. Where it struck bone, it did not crack the bone; it shattered it completely, splintering it into fragments and driving those fragments out into the surrounding muscle, and it tore a large, ragged exit wound on its way out. Over the course of the war, more than 476,000 soldiers were wounded by bullets, shrapnel, or blades.` },
      { p: `A man shot in the arm or the leg, then, very often did not have a broken bone. He had a destroyed one: bone smashed into splinters, the limb hanging by ruined muscle. And here we have to clear away another myth, the one that paints Civil War surgeons as butchers who hacked off limbs out of haste or ignorance. That picture is wrong, and it's worth understanding why, because the truth is harder and sadder.` },
      { p: `**Amputation** (surgically cutting off a damaged limb) was the standard response to a shattered limb, and given the medicine of the day, it was the *rational* one. Think about what the surgeon did not have. He had no antibiotics to fight infection, no X-rays to see inside the limb, no way to pin or plate a shattered bone back together. A bone smashed into splinters could not be rebuilt; it simply was not within the power of 1862 medicine to repair it. And a mangled limb left on the body would, in that pre-antiseptic world, almost certainly turn gangrenous (start rotting, the flesh dying around the wound), and the spreading infection would kill the man. So amputation was not butchery. It was, as one modern account puts it, "one of the quickest, most effective ways for surgeons to treat as many patients as possible in a short amount of time," and the military manuals laid out exactly when to do it: when a limb was carried off, when the major blood vessels and nerves were badly torn, when the soft tissue was too lacerated to save. Roughly three of every four operations performed in the entire war were amputations. (How many in total is genuinely uncertain; reputable sources put it anywhere from about 30,000 to about 60,000, a real two-fold disagreement, so the honest answer is "tens of thousands.")` },
      { p: `Timing decided who lived. A "primary" amputation, done within about the first 48 hours after the wound, gave the man markedly better odds than an "intermediary" one done days later, by which time infection had usually already set in. And the closer the cut was to the body, the worse the odds, because of blood loss; a leg taken off at the hip was far deadlier than one taken below the knee. Even so, about three of every four men who went under the saw survived the operation itself. The operation was not, usually, what killed them. We'll come to what did.` },
      { h: `They had the anesthesia. They didn't have the soap.`, eyebrow: `Turning point` },
      { fig: '/war-img/medicine-amputation-anesthesia.jpg', cap: `The myth says the soldier was awake, biting a bullet. The photograph says otherwise: an amputation staged for the camera outside a Gettysburg hospital tent in July 1863, with an officer at the head of the table holding a cloth of chloroform over the patient's face. They had solved the pain. They had not yet solved the dirt on the surgeon's hands.`, credit: `attributed to Charles J. & Isaac G. Tyson · albumen photograph · 1863 · U.S. National Archives and Records Administration (via Wikimedia Commons) · public domain` },
      { p: `The popular picture of Civil War surgery is the man held down on a table, fully awake, a leather strap or a bullet clenched in his teeth, screaming while the surgeon cuts. It is in every movie. It is almost entirely false. Anesthesia (drugs that render a patient unconscious and unable to feel pain) was widely available throughout the war, and it was *used*: in the large majority of surgeries, by the best modern estimate around 95% of them. This was not some rare luxury. Union records document anesthesia being given tens of thousands of times. The standard experience of a soldier facing the saw was not to feel it. He was put to sleep first.` },
      { p: `The drug of choice was **chloroform** (a sweet-smelling liquid whose vapor, breathed in, quickly puts a person to sleep), preferred in the field because it worked fast, you needed less of it, and it carried no fire risk. The alternative was **ether** (another inhaled anesthetic, gentler on the heart but dangerously flammable), favored in the fixed hospitals far from the front but feared in field tents lit by open flame. The records show the drugs were used overwhelmingly (chloroform most of the time, ether mostly in the safer fixed hospitals), and, the part that should surprise you most, they were *safe* in these men's hands. With no monitors and no modern training, surgeons were putting soldiers to sleep and bringing them back with deaths from the anesthesia itself counted in the dozens out of tens of thousands of administrations. Anesthesia was one of the genuine quiet successes of Civil War medicine.` },
      { p: `So where did the "bite the bullet" myth come from, if the men were asleep? This is the best part of the whole busting, so stay with it. Under light anesthesia (not deeply under, just enough) patients still moaned, thrashed, grimaced, and twitched. To an onlooker who had no idea what anesthesia was or did, a man making those sounds and motions looked exactly like a man awake and in agony. Observers assumed the soldiers were conscious and suffering, and the story spread. Add a later layer of folklore, and the odd discovery of bullets found on old battlefields with teeth marks in them (chewed, it turns out, by foraging pigs, not bitten by suffering soldiers), and the legend hardened into fact. When a modern researcher went back through the actual primary record (the diaries of soldiers, surgeons, and nurses, plus the medical manuals), the review "failed to turn up any contemporary references to biting the bullet, especially during surgery." Nobody who was there wrote it down, because it did not happen.` },
      { p: `They had solved pain. What they had not solved (what they did not even know was a problem) was dirt. **Antisepsis** (the practice of killing germs to keep a wound from getting infected, by cleaning the hands, the instruments, and the dressings) did not yet exist in American surgery. The methods that would eventually save the wounded (the carbolic-acid technique of **Joseph Lister**, the British surgeon who, in the years just after the war, would prove that washing wounds and instruments with carbolic acid killed the invisible germs causing infection) were only being worked out in Europe in the mid-to-late 1860s, and were not in use in America during the war. So the Civil War surgeon, who had genuinely good anesthesia, operated with unwashed hands and unwashed instruments. He went from one patient to the next without cleaning his tools or his hands. He used the same sponges, rinsed in a bucket of water, on man after man after man. To him this was not negligence; it was simply how surgery was done, because the thing that made it deadly was invisible and unimagined.` },
      { p: `The clearest emblem of that ignorance is a phrase: "laudable pus." Surgeons of the era believed that thick, creamy white pus welling up in a wound was a *good* sign, proof the wound was healing properly. They called it laudable, praiseworthy. In reality that pus was the visible sign of a raging infection. The doctors were watching the thing that was killing their patient and reading it as recovery. You could hardly invent a better summary of pre-germ-theory medicine: the warning light was on, and they thought it meant the engine was fine.` },
      { p: `Among the wounded, **infection** (gangrene, the rotting and dying of flesh around a wound, and pyemia, a condition in which bacteria from the infected wound get into the blood and spread the infection through the whole body, shutting the organs down) was the most common cause of death. Not the bullet. Not the saw. The dirt. A soldier could survive the shot, survive the agonizing journey to the rear, survive an amputation he never felt because they put him gently to sleep for it, and then die days later of an infection introduced by the very hands that saved him. They had the anesthesia. They didn't have the soap. That sentence is the whole tragedy of Civil War surgery.` },
      { h: `After the saw: a nation of empty sleeves`, eyebrow: `Consequence` },
      { fig: '/war-img/medicine-empty-sleeves.jpg', cap: `Maimed soldiers (empty sleeves pinned across their coats, men on crutches and missing legs) gathered outside a relief office in Washington in April 1865. Roughly 70,000 men came home from this war missing a limb, and what the country built to replace those limbs founded the American prosthetics industry.`, credit: `unattributed (Brady studio) · albumen photograph (glass-negative) · 1865 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `The men who survived all of that (the shot, the saw, the infection) came home missing arms and legs, by the tens of thousands. Roughly 70,000 soldiers lost a limb in the war. And what the country did next turned out to be the direct, practical consequence of the amputation story: it built an industry to replace what the surgeons had cut off.` },
      { p: `In 1862 the federal government launched what came to be called the "Great Civil War Benefaction," a promise to supply an artificial limb, or the money for one, to every Union amputee. A maimed veteran could choose from officially approved designs, and Washington paid the fixed price: $75 for an artificial leg, $50 for an arm, travel to be fitted included. The demand was enormous, and it pulled inventors into the field by the dozen. The Patent Office, which had issued just 34 prosthetic-limb patents in the sixteen years before the war, issued 133 in the years 1861 to 1873. The war essentially founded the American prosthetics industry, and some of those firms (one started by a Confederate amputee named James Hanger, who lost his leg in the war's very first land action and spent the rest of his life building better ones) outlived the century.` },
      { p: `But the benefaction had a hard edge written into it, and it is part of the war's cause, not separable from it. Confederate veterans were cut out of the federal program entirely. "Because they had engaged in rebellion," in the plain language of the rule, they were not eligible for a dollar of it. A man who had lost his leg fighting to keep other men enslaved got no limb from the government he had tried to destroy. Some former Confederate states, scraping together their own ruined budgets, set up programs of their own to fit their veterans. The empty sleeve, pinned across a coat, became one of the most common sights in postwar America, North and South; but who paid to fill it depended on which side a man had bled for, and why.` },
      { h: `The man who got the wounded off the field`, eyebrow: `Turning point` },
      { fig: '/war-img/medicine-letterman.jpg', cap: `Jonathan Letterman (seated, second from left), the army surgeon history calls the "Father of Battlefield Medicine," photographed with his medical staff at Warrenton, Virginia, in November 1862, months after he had rebuilt the Army of the Potomac's collapsed medical service from scratch.`, credit: `Alexander Gardner · albumen photograph (glass-negative) · 1862 · Library of Congress, Prints & Photographs Division · public domain` },
      { fig: '/war-img/medicine-ambulance-corps.jpg', cap: `A Zouave ambulance crew demonstrates lifting a wounded man into a horse-drawn ambulance, the kind of trained, medically-controlled stretcher work that did not exist until Letterman invented the Ambulance Corps in August 1862. Getting the wounded off the field had finally become somebody's actual job.`, credit: `unattributed (Brady studio) · albumen photograph (glass-negative) · c. 1862–1865 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `The war did not just kill on an industrial scale. In the middle of itself, it forced a revolution in how the wounded were saved, and that revolution had a name.` },
      { p: `Early in the war the system for handling the wounded was, frankly, no system at all. The job of carrying men off the field belonged to the Quartermaster Corps (the army branch that handled supplies and transport), and it was handled by civilian teamsters (hired wagon drivers) who were often drunk, often cowardly, and under no real obligation to risk anything. After a battle, wounded men could lie on the field for days, untended, dying slowly within sound of an army that simply had no organized way to come get them. It was a scandal and a horror, and it took two reformers to fix it.` },
      { p: `The first was the man at the top. **William Alexander Hammond** was appointed the eleventh Surgeon General of the U.S. Army on April 25, 1862; Lincoln chose him on the recommendation of the Sanitary Commission (more on that body shortly). Hammond was young, energetic, and reform-minded, and he took a sleepy, outdated Medical Bureau and shook it awake. He set sanitation and ventilation standards for hospitals, borrowing from the work of the British nursing reformer Florence Nightingale, and sent inspectors to enforce them. He set minimum age and skill requirements for army surgeons, so the job stopped going to anyone with a saw. He pushed a new, healthier hospital design. He founded the Army Medical Museum to study the war's wounds, and he launched the vast project that would eventually become the war's great medical record (the last beat of this story). He was, in short, medically ahead of his time: so far ahead that when he banned calomel (a mercury-based drug used to purge the gut, which was useless and toxic) from the army's supply list in 1863, he enraged the conservative old doctors who'd prescribed it for decades. That kind of friction, plus a personal feud with the powerful Secretary of War Edwin Stanton, got Hammond court-martialed and dismissed in 1864 on what were essentially political grounds. He was exonerated years later, in 1879, and restored to the rolls, and went on to become a pioneering American neurologist. But his most important act was backing the second reformer, the one who actually went to the field.` },
      { p: `That man was **Jonathan Letterman**, a major and army surgeon, and history remembers him by a grand title he genuinely earned: the "Father of Battlefield Medicine." In June 1862, Hammond made him Medical Director of the Army of the Potomac (the Union's principal eastern army) and handed him a collapsed medical service to rebuild. What Letterman built in the months that followed is, with very little exaggeration, the foundation of all modern emergency medicine.` },
      { p: `His first move, in August 1862, was to create the army's first organized **Ambulance Corps**: a dedicated, trained body of stretcher-bearers and wagon drivers placed under the control of the *medical* department, not the quartermasters. That sounds like a dull administrative shuffle. It was a revolution. For the first time, getting wounded men off the field was somebody's actual job, done by trained people who answered to doctors, instead of an afterthought left to whichever teamster hadn't run off.` },
      { p: `His second move was the architecture of the system itself, the thing now called the Letterman Plan: a three-tier chain of evacuation, each tier doing a different job, moving every wounded man back along it from the chaos of the firing line to the calm of a rear hospital.` },
      { p: `1. First, the **field dressing station**, right at or near the firing line: immediate first aid, a tourniquet, stop the bleeding, get the man moving back. 2. Next, the **field hospital**, just behind the lines: the place for emergency surgery and amputation. 3. Finally, the **general hospital**, far to the rear: the large, permanent place for long-term recovery.` },
      { p: `Built into that chain was **triage** (sorting incoming wounded by how badly they're hurt, so the scarce surgeons spend their time where it does the most good). Tiered evacuation plus triage is the direct ancestor of how every military and emergency-medicine system on earth handles mass casualties today: the ambulance that comes for a car-crash victim is running, in its bones, on Jonathan Letterman's plan.` },
      { p: `Did it work? The first full test came on the worst possible day. On September 17, 1862, at the Battle of Antietam (the bloodiest single day in all of American history, with something like 23,000 casualties), Letterman's brand-new system was thrown into the deep end. It cleared *all* the wounded from that vast, ruined field within about 24 hours. For an army that had recently been leaving men to rot for days, this was a near-miracle, and it was the proof that the system worked. It was proven again at Fredericksburg and at Gettysburg, and in March 1864 an Act of Congress made the Letterman system the official model for the entire U.S. Army. A scandal at the start of the war had become, by its middle, the template the modern world still uses.` },
      { h: `Cities of the sick`, eyebrow: `Consequence` },
      { fig: '/war-img/medicine-chimborazo.jpg', cap: `Chimborazo Hospital sprawling across its hill in Richmond in April 1865, roughly 90 long, low wards spread over nearly 150 buildings, one of the largest military hospitals in the world. It admitted nearly 78,000 patients, and the labor that kept it running was done in large part by enslaved people hired out by their owners.`, credit: `unattributed · albumen print on card mount · photographed 1865 (printed 1880s) · Library of Congress, Prints & Photographs Division · public domain` },
      { fig: '/war-img/medicine-armory-square-ward.jpg', cap: `A ward at Armory Square Hospital in Washington, the long, high-ceilinged, well-ventilated "pavilion" design that the Union built by the dozen. Beds line both walls under flags and greenery; the spacing and the open air were meant to carry off "bad airs." The theory was wrong, but the clean, airy practice happened to work, and these hospitals kept death rates surprisingly low.`, credit: `unattributed · albumen print · photographed 1862–1865 (printed 1880s) · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `The end of that evacuation chain (the third tier, the place men were carried to for the long haul of recovery) became something the country had never seen: hospitals on a scale closer to small cities.` },
      { p: `In the South stood **Chimborazo Hospital** in Richmond, Virginia (named for the hill it sat on), the largest and most famous hospital of the Confederacy and one of the largest military hospitals in the entire world at the time. Its roughly 90 hospital wards held up to about 4,000 patients at a time, with overflow tents pushing total occupancy as high as 8,000 in the most crowded stretches, all of it spread across a sprawling campus of nearly 150 buildings on Chimborazo Hill. Over the course of the war it admitted nearly 78,000 patients; somewhere between about 6,500 and 8,000 of them died there. It was run under the Confederate hospital system, and its chief matron for one of its divisions (the woman who ran the diet and the nursing and the day-to-day care of thousands of men) was Phoebe Pember, whom we are about to meet.` },
      { p: `But the arduous, ceaseless physical labor that kept Chimborazo running (the cooking, the laundry, the hauling of water and supplies, the emptying and cleaning and lifting, and a great deal of the hands-on nursing) was done in large part by enslaved people. In 1864 alone, Chimborazo's medical superintendent reported using 256 enslaved men and women to care for the patients. The Confederate hospitals hired them from their owners under detailed contracts; the wage for the work went to the slaveholder, not to the person who did it. The largest hospital in the Confederacy, in other words, ran on the labor of the very people the Confederacy existed to keep in bondage, and the standard histories of these great wards tend to name the white matron and pass over the enslaved hundreds who did the lifting. They should not be passed over.` },
      { p: `In the North stood **Satterlee General Hospital** in West Philadelphia, the largest Union Army hospital, running from 1862 to 1865 on a roughly 16-acre site. With 34 wards plus hundreds of overflow tents, it reached about 4,500 beds, spiking whenever a great battle (Bull Run, Gettysburg) flooded the rear with wounded. It was staffed in part by the **Daughters of Charity** (an order of Catholic nuns who took up nursing).` },
      { p: `These vast places had a particular look, and the look was itself an innovation: the "pavilion" design, with long, well-ventilated wards spaced deliberately apart so that fresh air could move through and, the thinking went, carry off the bad airs that caused disease. They had the wrong theory (it was germs, not bad air), but the practice of fresh air and space and cleanliness, pushed by Hammond and the Sanitary Commission, happened to work, and these hospitals achieved surprisingly low death rates for their era. Again and again in this war, people did the right thing for reasons that turned out to be wrong, and men lived because of it.` },
      { h: `The amateurs who organized the war's mercy`, eyebrow: `Consequence` },
      { fig: '/war-img/medicine-sanitary-commission.jpg', cap: `Workers of the United States Sanitary Commission outside the Home Lodge in Washington in June 1863. The Commission (run by volunteers, bankrolled by public "Sanitary Fairs," and famously managed day-to-day by Central Park designer Frederick Law Olmsted) inspected the filthy camps, supplied what the army lacked, and helped seed modern public health almost by accident.`, credit: `unattributed (Brady studio) · albumen photograph (glass-negative) · 1863 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `Behind the official army medical system stood a sprawling civilian effort, and the largest piece of it was an organization invented for the war out of nothing: the **United States Sanitary Commission**.` },
      { p: `It was created by federal legislation on June 18, 1861, as a private relief agency to support sick and wounded Union soldiers, and the names running it tell you how much earnest civilian energy poured into the war effort. Its president was Henry Whitney Bellows, a Unitarian minister. Its executive secretary, the man who actually ran the thing day to day, was Frederick Law Olmsted: yes, the same Frederick Law Olmsted who designed New York's Central Park, the most famous landscape architect in American history. The man who had bent rivers and moved hills to lay out the nation's grandest park now spent his war counting the distance from a regiment's latrines to its drinking water, riding from muddy camp to muddy camp with an inspector's notebook, and pushing the findings onto the desks of the War Department.` },
      { p: `That was, in fact, the first of the three things the Commission did. It inspected the camps (checking where the latrines were dug, whether the water was clean, how the tents were ventilated, what the men were eating) and reported the deficiencies straight to the War Department. (By late October 1861 it had already collected detailed inspection reports from more than 400 regimental camps.) It supplied the things the army was short of: bandages, food, clothing, medicine. And it raised money, famously through "Sanitary Fairs," big public fundraising events. Over the war it gathered an estimated $25 million in cash and goods and mobilized thousands of volunteers, most of them women. As an unintended bonus, all that systematic collecting of camp data and medical statistics helped seed the methods of modern public health and medical research. The amateurs, in trying to keep soldiers from dying of filth, accidentally helped invent a discipline.` },
      { h: `The women who walked into the wards`, eyebrow: `Consequence` },
      { fig: '/war-img/medicine-susie-king-taylor.jpg', cap: `Susie King Taylor, born into slavery near Savannah and freed at fourteen, served four years and three months with the 33rd United States Colored Troops as laundress, teacher, and nurse, walking straight into a smallpox outbreak because she'd been vaccinated and the soldiers hadn't. She was never paid a dollar, and she became the only Black woman to publish a memoir of her Civil War service.`, credit: `unattributed · photograph reproduced as the frontispiece of *Reminiscences of My Life in Camp* · 1902 · Library of Congress, Prints & Photographs Division · public domain` },
      { fig: '/war-img/medicine-clara-barton.jpg', cap: `Clara Barton, the "Angel of the Battlefield," who carried nursing care and supplies directly into the danger at Antietam and Fredericksburg, and who wasn't a trained nurse at all, but a former teacher and Patent Office clerk running a relief operation she built by sheer will. In 1881 she founded the American Red Cross. This is the wartime portrait she chose as the one she wished to be remembered by.`, credit: `Mathew Brady studio (later print) · photograph · Civil War era (print c. 1890–1910) · Library of Congress, Prints & Photographs Division · public domain` },
      { fig: '/war-img/medicine-dorothea-dix.jpg', cap: `Dorothea Dix, appointed Superintendent of Army Nurses in June 1861, the first woman ever to hold so senior a federally appointed post. She got the job because decades of reorganizing the nation's asylums had taught her, better than almost anyone alive, how to build an institution from nothing. She vetted the Union's nurses with a famously stern hand, preferring plain, older, sober women.`, credit: `unattributed · photograph (b&w copy negative) · mid-19th century · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `And then there is the change that outlasted every hospital and every reform: the women.` },
      { p: `Before the Civil War, nursing in America was largely a male job, or menial work, not something a respectable woman did. The war shattered that, because it produced more broken men than any existing system could tend, and women stepped into the gap by the thousands; estimates run from a few thousand formally appointed Union nurses to many times that number serving in military hospitals in some capacity, North and South. Whatever the exact count, it was a genuine social transformation: the war pulled an entire category of women out of the parlor and into the hospital ward, and it legitimized women in hospital medicine in a way that did not reverse when the guns fell silent. A handful of them became famous, and each is worth knowing.` },
      { p: `**Dorothea Dix** was appointed Superintendent of Army Nurses in June 1861, the first woman ever to hold so senior a federally appointed post. The job went to her for a concrete reason: she came to it having spent decades campaigning for the humane treatment of the mentally ill, reorganizing asylums state by state across the country, which meant she already knew, better than almost anyone alive, how to build an institution from nothing. She organized and vetted the Union's female nurses with a stern, particular hand; she notoriously preferred to hire plain, older, sober women, the better to keep her nursing corps respectable and above gossip.` },
      { p: `**Clara Barton** earned a nickname that has stuck for a century and a half: the "Angel of the Battlefield." She earned it by doing something most people did not dare: bringing nursing care and supplies directly to the front, into the noise and danger, notably at Antietam and Fredericksburg, often working entirely outside the official system. She was not a trained nurse at all. She had been a teacher and a clerk at the U.S. Patent Office, and she built her own supply-and-relief operation essentially by force of will. Her war work was the seed of something larger: in 1881 she founded the American Red Cross and led it as president for 23 years.` },
      { p: `**Walt Whitman** (the poet, the author of *Leaves of Grass*) came to Washington in December 1862 for an intensely personal reason: he had seen his brother George's name on the casualty list from Fredericksburg and went to find him. He found the sick and wounded so badly cared for that he stayed, and spent much of the war as a hospital volunteer. Not a nurse; he did the human work around the edges of medicine: he wrote letters home for men who couldn't, brought them small gifts and treats, read to them, and sat with the dying so they would not be alone. He visited tens of thousands of soldiers. The war poetry he produced out of all this, the collection *Drum-Taps*, published in May 1865, came directly from those wards. Whitman said it was put together "by fits and starts, on the field, in the hospitals as I worked with the soldier boys."` },
      { p: `And there is a caregiver the histories of this war left out for far too long: **Susie King Taylor**. Born into slavery near Savannah, Georgia, in 1848, she was taught to read in secret as a child (a crime where she lived) and freed herself at fourteen by reaching a Union gunboat. She attached herself to the **33rd United States Colored Troops** (the regiment of freedmen first raised as the 1st South Carolina Volunteers), enrolled officially as a laundress, and over four years and three months became far more: she taught the soldiers of the regiment to read in camp, and she nursed their sick and wounded through the war's worst, including a smallpox outbreak she walked straight into because she had been vaccinated and they had not. During that work in the South Carolina Sea Islands she met and worked alongside Clara Barton herself. She was never paid a dollar for any of it. Decades later she wrote it all down, becoming the only Black woman to publish a memoir of her Civil War service, the direct counterpart to Barton, doing the same dangerous front-line work and very nearly written out of the same story.` },
      { p: `The South had its own remarkable women. **Phoebe Yates Pember** took the post of chief matron of a division of Chimborazo Hospital in November 1862, one of the first women in such a role in the South, and she took it over the open resistance of the male staff who did not want a woman running anything. She ran the food, the comfort, and the nursing for thousands of men (her division alone cared for over 15,000 over its life; labor she directed but, as we've seen, did not perform alone), and she later wrote a sharp, unsentimental, very readable memoir of it all, *A Southern Woman's Story*.` },
      { p: `And then there is the single most extraordinary case, **Sally Louisa Tompkins**. She ran a small private hospital in Richmond, the Robertson Hospital. When the Confederate government ordered all military hospitals placed under military command (which would have shut down a private operation like hers), President Jefferson Davis solved the problem by commissioning her a captain of cavalry on September 9, 1861. Cavalry was simply the available commission slot; nobody expected her on a horse. The rank existed only to make her hospital officially military so it could keep running under her. That made Sally Tompkins the only woman formally commissioned as an officer in the Confederate Army. She accepted the rank and declined the pay. And she earned the commission with results no one else in the war could match: over four years her Robertson Hospital treated 1,334 patients and lost only 73 of them, the lowest death rate of any military hospital on either side of the war. She got that result by insisting, fiercely, on cleanliness and good food. She had no idea about germs; nobody did. She simply ran a clean hospital and fed her men well, and they lived: the right practice, decades ahead of the theory that would explain why it worked.` },
      { h: `Improvising a medical service under blockade`, eyebrow: `Consequence` },
      { p: `The Confederate side fought this entire medical war desperately short of the drugs its doctors needed most, and it is worth being clear about why, because the shortage was not bad luck. It was the medical cost of the Union blockade, and the blockade was the Union's lawful answer to secession, which the Confederacy had chosen to defend slavery. The men who improvised under these conditions deserve sympathy as individuals; the government that put them there had chosen this war to keep four million people in bondage, and the empty medicine shelf was one of the bills that choice ran up.` },
      { p: `Building the South's medical service essentially from scratch fell to **Samuel Preston Moore**, the Confederate Surgeon General, a South Carolina–born former U.S. Army surgeon whom Jefferson Davis tapped to create a Confederate Medical Department where none had existed. Moore organized the Southern hospital system (Chimborazo among them), enforced standards by a relentless stream of correspondence, and pushed hard for medical self-sufficiency, because self-sufficiency was the only option the South had.` },
      { p: `The blockade (the Northern naval cordon choking off Southern ports) caused crippling shortages of the drugs the South's doctors needed most. Quinine for malaria, morphine and opium (the main drugs for dulling and killing pain, in surgery and out of it), chloroform and ether for surgery: all of it ran short. The medicines that made Northern medicine humane were precisely the ones the South couldn't get.` },
      { p: `So the South smuggled and improvised. Blockade-runners carried quinine and morphine through the Northern cordon for enormous profit, and the smuggling produced details almost too vivid to believe: Union searchers found quinine concealed inside the hollowed-out heads of children's dolls, and stuffed inside the carcasses of slaughtered animals. When smuggling fell short, Moore's medical laboratories manufactured chloroform and ether domestically, and his chemists experimented with native-plant substitutes (barks of dogwood, willow, and other trees) to stand in for scarce quinine. The substitutes mostly didn't work very well. But it tells you everything about the Confederate medical predicament that its doctors were boiling tree bark and hoping, while their counterparts in the North reached for a bottle.` },
      { fig: '/war-img/medicine-embalming.jpg', cap: `Dr. Richard Burr, an embalming surgeon with the Army of the James, demonstrating his trade over a dead soldier. Before the war, embalming was rare in America; the need to ship sons home recognizable, over long distances, created a brand-new commercial industry almost overnight, one that got its biggest advertisement when Lincoln's embalmed body toured the country by funeral train in 1865.`, credit: `unattributed (Brady studio) · albumen photograph (glass-negative) · c. 1860–1865 · Library of Congress, Prints & Photographs Division · public domain` },
      { h: `What the war wrote down`, eyebrow: `Consequence` },
      { p: `Two things outlived the war's medicine and carried it into the country's future: a new industry, and a book.` },
      { p: `The first was **embalming** (treating a dead body with chemicals to preserve it from decay). Before the war it was rare in America; afterward it was mainstream, and the war is the reason. The need was wrenchingly practical: families wanted their dead sons (the farm boys and the freedmen, the men who'd died of measles in a tent and the men who'd died under the saw) shipped home over long distances, and they wanted them recognizable, not decomposed, when the coffin was opened. That demand created a brand-new commercial industry overnight. Its most famous practitioner, later called the "father of modern embalming," was Dr. Thomas Holmes, who claimed to have personally embalmed over 4,000 soldiers and officers during the war. A figure some believe he inflated, so it's best taken as his own boast rather than a hard number. The whole young industry got a final, enormous advertisement in April 1865, when the embalmed body of the assassinated President Lincoln toured the country by funeral train, viewed by enormous crowds.` },
      { p: `The second legacy was the war's attempt to learn from its own carnage. The project Surgeon General Hammond had launched, and which was completed under a later Surgeon General, Joseph K. Barnes (Hammond's successor at the head of the army's medical department), became *The Medical and Surgical History of the War of the Rebellion*, a monumental six-volume government work issued between 1870 and 1888, documenting tens of thousands of the war's disease and surgical cases in painstaking detail. It was a landmark of military medical record-keeping and a founding text of modern military medicine: the war's hardest, grimmest lessons, finally written down so that the next war's doctors might not have to learn them again from scratch. The men of the Civil War died largely in ignorance of what was killing them. The book was the start of the answer: the moment the country stopped just burying its medical disasters and began, at last, to study them.` },
    ],
    meanwhile: {
      region: `behind the lines`,
      title: `The Home Front`,
      body: `The same war that filled the hospitals emptied the farms and the shops. Back home, two societies were mobilizing everything they had, and the burden fell hardest on the people with the least.`,
    },
  },
}

export default function MedicineThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="medicine"
      battleName="Medicine & Disease"
      theatreId="offfield"
      battleId="th-medicine"
      theatreHref="/war-civil-war/off-the-battlefield"
      accent={ACCENTS.otbf}
      heroImage="/war-img/medicine-hero-field-hospital.jpg"
      heroPalette={["#2a2826","#1a1917","#080808"]}
      heroCredit={`James F. Gibson · albumen photograph (glass-negative) · 1862 · Library of Congress, Prints & Photographs Division · public domain`}
      heroFocus="center 50%"
      heroScale={1.06}
      endHref="/war-civil-war/off-the-battlefield"
      endKicker={`Two died of sickness for every one shot`}
      endLabel={`Back to Off the Battlefield`}
    />
  )
}
