'use client'

// Stones River — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const STONES_RIVER_NARR: Record<string, Narr> = {
  'the-armies-face-off': {
    eyebrow: 'Stones River · Two mirror-image plans',
    title: 'The Year Turns at Murfreesboro',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -87.5, lonMax: -85.7, latMin: 35.3, latMax: 36.7 },
        states: [
          { name: 'Tennessee', tone: 'focus', label: 'TENNESSEE', labelLon: -86.2, labelLat: 36.5 },
          { name: 'Kentucky' }, { name: 'Alabama' }, { name: 'Georgia' }, { name: 'Virginia' },
        ],
        dots: [
          { name: 'Stones River', date: 'Dec 31, 1862–Jan 2, 1863', lat: 35.848, lon: -86.432, heavy: true, anchor: 'middle', dy: 24 },
          { name: 'Nashville', lat: 36.166, lon: -86.782, color: '#8a8175', anchor: 'middle', dy: -16 },
        ],
      } },



      { p: 'In the second winter of America’s Civil War, the North against the slaveholding South and going on two years now, the fighting did not pause for Christmas. In the last week of 1862 the South had real reason for cheer: two weeks earlier, on December 13, a Union army had walked into a slaughter at Fredericksburg, Virginia, and the North was reeling. The Union badly needed a win, and it needed one in the West, the Civil War’s other great battleground, the long valleys of the Tennessee and the Cumberland rivers, where control of the rivers and the railroads meant control of the interior. So the day after Christmas, the Union’s Army of the Cumberland (Civil War armies were usually named after rivers, not states) marched out of Nashville, Tennessee, heading southeast down the Nashville Pike (a turnpike, a paved toll road) toward the town of Murfreesboro, about 30 miles (48 km) away, where a Confederate army was wintering.' },
      { pill: '/war-civil-war/eastern/fredericksburg', plabel: 'Fredericksburg: the slaughter that left the North desperate for a win' },
      { p: 'These two armies were marching toward each other to settle a question the Confederacy itself had never been shy about. It was a country barely two years old, founded for one overriding reason: to protect and preserve the enslavement of four million Black people. The South had built its economy and its social order on slavery and seceded rather than see it limited. And on the very morning these two armies would pause to bury their dead, that question would stop being abstract: the Emancipation Proclamation took legal effect on January 1, 1863, in the middle of this battle. Stones River would be the first major battle fought under it.' },
      { p: 'The Union commander was Major General William S. Rosecrans (North), a devout, fast-talking engineer of a man who had spent weeks stockpiling supplies in Nashville before he would budge. His Confederate counterpart was General Braxton Bragg (South), commander of the Army of Tennessee, a harsh disciplinarian whose own generals could barely stand him. Bragg had just come off a failed invasion of Kentucky that fall and had pulled back to Murfreesboro to recover. Now he turned to face Rosecrans on the open, rolling farmland west of the town, ground broken up by dense thickets of eastern red cedar growing over flat sheets of bare limestone, the "cedar brakes," gloomy tangles that would choke and hide whole brigades.' },
      { p: 'A brief word on how an army was built, since the rest of this story runs on it: an army split into a few corps, each corps into two or three divisions, each division into a handful of brigades, each brigade a few thousand men down to a thousand or so. The men running them ranked, top to bottom, full General, Lieutenant General, Major General, Brigadier General, then Colonel and Captain, each commanding roughly the unit his rank fit. Rosecrans had also split his army into three pieces by position: a right wing, a center, and a left wing, the three thirds of his battle line. Stones River, a shallow stream, ran roughly south-to-north through the field.', i: true },
      { fig: '/war-img/stones-river-overview.png', cap: 'The night of December 30: the two armies bed down astride Stones River west of Murfreesboro while Wheeler’s cavalry rides clear around the Union rear to wreck the supply line back to Nashville.', credit: 'Stuff Happened map' },
      { h: 'The Same Plan, Twice', eyebrow: 'Two mirror-image plans' },
      { p: 'Each general made the same plan. Both Rosecrans and Bragg decided to attack the other army’s right flank at dawn, mirror images of each other, each intending to swing wide around the enemy’s exposed end (the flank being the end, the unanchored side, of a battle line) and roll it up. Whoever struck first would have his blow land before the other’s was ready. It came down to the clock.' },
      { h: 'Wheeler Rides the Rear', eyebrow: 'Hold the pike and you hold the battle' },
      { p: 'There was one Confederate piece already in motion before either plan could fire. In the days the Union army spent grinding the 30 miles down from Nashville, Bragg’s cavalry chief, Brigadier General Joseph Wheeler (South), took some two thousand horsemen and rode them completely around Rosecrans’s marching army, a full circuit, front to rear, in about forty-eight hours. At midday on December 30 his troopers fell on a lightly guarded supply train (a supply train being a convoy of wagons hauling food and ammunition, not a railroad train) near the village of LaVergne, behind the Union line. They carried off or burned close to a million dollars’ worth of supplies and captured and paroled some eight hundred men. By the early hours of December 31, Wheeler rode back in on Bragg’s flank having torn up the Union rear and left Bragg believing he could strangle Rosecrans’s supply line and force him to retreat without a real fight. That single road back to Nashville, the pike, was the Union army’s one open artery, and the Confederates had just shown how exposed it was. Hold the pike and you held the battle.' },
      { p: '"Home! Sweet Home!"', q: true },
      { p: 'The song that bands of both armies are said to have struck up together on the night of December 30; soldiers on both sides reportedly joined in.', i: true },
      { p: 'The night before the battle, the two armies camped close enough to hear each other. Regimental bands began a kind of contest across the dark, one side’s "Yankee Doodle" answered by the other’s "Dixie." Then, by most accounts, one band started up Home! Sweet Home!, and bands and men on both sides joined in together: thousands of soldiers who would be trying to kill each other at first light, singing the same song about home across the cold ground between them.' },
      { h: 'Who Hits First', eyebrow: 'Outcome · the setup' },
      { p: 'Two armies, two identical plans, one open question: who hits first.', i: true },
      { p: 'By the night of December 30, 1862, roughly 76,000 men were bedded down within earshot of each other west of Murfreesboro, and both commanders intended to attack the enemy’s right wing at dawn. Bragg’s men had less ground to cover and woke earlier. That single fact, who landed the first punch, would shape the next three days.' },
    ],
    meanwhile: { region: 'Fredericksburg & Washington', title: 'The win the North was desperate for', body: 'Two weeks before Stones River, the Union had marched into one of the war’s worst defeats at Fredericksburg, Virginia, throwing wave after wave of men against an unbreakable Confederate position and losing thousands for nothing. The North’s morale was at low ebb, and the war’s purpose was about to change in writing: Lincoln had announced that on January 1 he would proclaim the enslaved in the rebelling states free. A second straight disaster, this time in the West, would have been a political gift to the Confederacy at the worst possible moment. The men marching out of Nashville did not know it, but a great deal more than a Tennessee railroad town was riding on what happened next.' },
  },

  'the-dawn-blow': {
    eyebrow: 'Stones River · December 31, before breakfast',
    title: 'The Confederate Jackknife',
    blocks: [
      { p: 'Bragg (South) struck first. At about six o’clock on the morning of December 31, before most of the Union right wing had finished breakfast, the Confederate attack came howling out of the cedars: some ten thousand men under Lieutenant General William J. Hardee (South), one of the army’s best tacticians, coming on in a great wave with more divisions filling in close behind. The Union soldiers on that flank, the men of Major General Alexander M. McCook (North), were quite literally caught at their cook fires, rifles stacked, coffee on.' },
      { p: 'The problem for the Union was geography as much as surprise. McCook’s right flank was not anchored on anything; it simply hung in the air, out past a creek called Overall, with nothing solid to brace against. So when the Confederate wave hit and then wheeled, there was nothing to stop it from curling around the open end. The whole Union right began to fold backward, hinging in place, "like a jackknife" closing: the line bent back on itself and driven roughly three miles, all the way to the Nashville Pike and the railroad beside it. By mid-morning the Union army’s entire right half had been knocked loose and was reeling toward the rear.' },
      { fig: '/war-img/stones-river.png', cap: 'Dawn, December 31: Hardee’s attack out of the cedars wheels the Union right back three miles like a closing jackknife, until Sheridan’s stand in the Slaughter Pen and the Round Forest near the pike bend the line into an L that will not break.', credit: 'Stuff Happened map' },
      { h: 'The Slaughter Pen', eyebrow: 'Sheridan’s four-hour stand' },
      { p: 'What kept it from becoming a rout (a total, panicked collapse) was a holding action in the cedars so brutal the soldiers named the place for it. The division of Brigadier General Philip H. Sheridan (North), a short, ferocious officer near the start of a career that would make him famous, dug in among the cedar brakes and refused to break. For roughly four hours Sheridan’s men stood and bled in a sector that earned the name the Slaughter Pen, the eastern red cedars splintering overhead and the limestone underfoot slick where men had fallen, the Confederates coming on through the gloom in wave after wave and Sheridan’s line firing into them at a few dozen yards until the cedars in front were carpeted. The cost was staggering: all three of Sheridan’s brigade commanders were killed, and more than a third of his division went down. But the four hours they bought were the four hours the rest of the army needed to form a new line. Around eleven o’clock, his ammunition gone, Sheridan finally pulled back.' },
      { p: 'The morning had its private horror, too. Riding near the front, Rosecrans’s chief of staff (the officer who runs an army’s headquarters), Lieutenant Colonel Julius P. Garesché (North), was killed at the general’s side, decapitated by a cannonball as the two rode together. Rosecrans (North), spattered with the blood of his own friend, rode on and kept the army in hand, galloping the lines, plugging gaps, holding the thing together by force of will.' },
      { p: '"The enemy has yielded his strong position and is falling back."', q: true },
      { p: 'The substance of Bragg’s telegram to Richmond the night of December 31, reporting that he had won.', i: true },
      { h: 'The Knockout That Never Landed', eyebrow: 'Friction in Bragg’s army' },
      { p: 'The Confederates did not land the knockout, and part of the reason was friction inside Bragg’s own army. False reports of Union troops moving up another road, tangled with the bad blood between Bragg and one of his generals (a feud the next section will return to), pulled an entire fresh division away from the main blow at the decisive moment. Bragg had bent the Union line nearly double, but he could not snap it. As the short December day ended, he believed he had won, and wired Richmond to say so.' },
      { p: 'He was wrong, and he found out that night across the lines. In the Union camp, some of Rosecrans’s officers urged him to retreat, since the army had been mauled and the right wing wrecked. Rosecrans refused, backed firmly by his two other wing commanders: Major General George H. Thomas (North), who held the center, and the man who held the left, Major General Thomas L. Crittenden (North). (Two Thomases, confusingly: Thomas the center general, Crittenden the left.) He would stay and fight it out.' },
      { h: 'A Battle the South Failed to Finish', eyebrow: 'Outcome · day one (December 31)' },
      { p: 'A near-disaster for the Union, and a battle the South failed to finish.', i: true },
      { p: 'Bragg’s dawn surprise folded the Union right back three miles and very nearly destroyed Rosecrans’s army before breakfast. But Sheridan’s stand in the Slaughter Pen and the anchor near the Nashville Pike kept the line from collapsing, and Confederate friction kept Bragg from landing the killing blow. The South held the field at dusk and thought it had won. The Union army was still alive.' },
    ],
    meanwhile: { region: 'The Round Forest', title: 'Hell’s Half Acre', body: 'While the right wing was being driven back, the hinge that saved the day held in a four-acre copse of rocky cedar near the pike and railroad, a salient (a bulge in the line jutting toward the enemy) that the soldiers came to call "Hell’s Half Acre." The brigade of Colonel William B. Hazen (North) anchored it, and through the afternoon the Confederate corps of Lieutenant General Leonidas Polk (South) threw as many as four separate attacks at the position. Each one was broken. Hazen’s brigade was the one piece of the original Union line that never gave ground, and as long as the Round Forest held, the Confederates could not turn the corner and roll up what was left. It was the most savage close-range fighting of the day, and it was the pivot the whole battle turned on.' },
  },

  'the-new-years-pause': {
    eyebrow: 'Stones River · January 1',
    title: 'The Day Nobody Moved',
    blocks: [
      { p: 'The men woke on New Year’s morning into the strangest day of the battle: a day on which almost nothing happened, and everything changed. There was no dawn attack this time. The two armies lay exhausted in the cedar brakes, a few hundred yards apart, and mostly stared at each other across ground still full of the unburied and the not-yet-dead: the wounded of December 31 still out where they had fallen, calling in the cold through the night, burying parties working between the lines. The soldiers stamping their feet in the freezing cedars that morning had no way of knowing that the entire reason they were lying there had, that very dawn, been rewritten a thousand miles away.' },
      { h: 'A War’s Whole Meaning, Changed Overhead', eyebrow: 'The Proclamation takes effect' },
      { p: 'This was the morning the Emancipation Proclamation took effect. A war the Confederacy had started to defend slavery now had, in writing and for the first time, the destruction of slavery as its declared purpose, and it opened, by the accident of the calendar, in the lull of this freezing battle. None of the men in the cedar brakes knew it yet. They were, from that morning forward, fighting the first major battle of a war waged explicitly to end slavery, and not one of them on the field could have told you so. The war’s whole meaning had changed overhead while the men who were dying for it shivered, oblivious, among their own dead.' },
      { pill: '/war-civil-war/off-the-battlefield/emancipation', plabel: 'The Emancipation Proclamation: what took effect over the battlefield' },
      { h: 'The Field Shifts Quietly', eyebrow: 'A division crosses the river' },
      { p: 'The armies did not sit perfectly still. Before dawn, Rosecrans (North) ordered a division across to the east bank of Stones River to seize a low hill, high ground that would make a fine platform for artillery and let the Union fire down the length of the Confederate line if it held. The crossing went off quietly, and by light the Union had men and the makings of a gun line on the far bank. The Confederate cavalry under Brigadier General Joseph Wheeler (South) kept up the work it had done all week, ranging behind the Union army to harry the supply wagons creeping down the Nashville Pike, but this time Rosecrans got resupplied through the night anyway. By the end of the day, the shape of the field had quietly shifted. Bragg had expected to wake up and find the enemy gone, beaten and retreating up the pike. Instead the Union army was still there: dug in, fed, and now sitting on a hill across the river that Bragg did not like one bit.' },
      { h: 'The Tide Turns Without a Shot', eyebrow: 'Outcome · day two (January 1)' },
      { p: 'A pause that turned the tide without a shot.', i: true },
      { p: 'The quiet of New Year’s Day worked entirely in the Union’s favor. Rosecrans used it to hold his ground, resupply, and plant a division on commanding high ground east of the river. Bragg, who had wired Richmond that he had won, instead found the enemy he thought was beaten still in front of him and freshly entrenched. And the men who held that line did it without knowing they were now holding it for emancipation: the day’s quiet was also the day the war’s purpose changed under them.' },
    ],
    meanwhile: { region: 'Washington, D.C.', title: 'The stroke of the pen', body: 'A thousand miles from the cedar brakes, Lincoln spent the morning of January 1 shaking hundreds of hands at the traditional White House New Year’s reception until his arm ached, then went upstairs and signed the Emancipation Proclamation. It declared the enslaved in the rebelling states "forever free" and, for the first time, authorized Black men to enlist and fight in the Union army. It freed no one instantly, since it applied to the very Confederate territory the Union did not yet control, but it changed what the war was for, turning every advancing Union army into an army of liberation. It also raised the stakes of every battle then underway, the one in the Tennessee cedars included. A Union army shattered at Murfreesboro in the first days of January would have made the Proclamation look like the desperate gesture of a losing side. The men holding the line near the Nashville Pike were, without knowing it, holding up the document too.' },
  },

  'breckinridges-charge': {
    eyebrow: 'Stones River · January 2, four o’clock',
    title: 'The Charge at McFadden’s Ford',
    blocks: [
      { p: 'The hill across the river was the problem. From the high ground the Union had seized on January 1, Federal guns could rake the right of Bragg’s line. So on the afternoon of January 2, Bragg (South) decided it had to be taken back, and he handed the job to the division of Major General John C. Breckinridge (South), a former Vice President of the United States, now a Confederate general, and a man who had spent the previous day feuding with Bragg over the army’s handling. Bragg ordered him to cross the open ground and storm the Union division on the hill east of the river.' },
      { p: 'Breckinridge looked at the ground and saw a death trap. The Union held the high east-bank hill, yes, but across the river, on the west bank, the rising ground was perfect for massing artillery, and any attack on the hill would have to go forward with the enemy’s guns looking straight down its flank from across the water. He protested the order as suicidal. Bragg overruled him. At about four o’clock, Breckinridge attacked anyway.' },
      { p: 'Breckinridge protested the order, telling Bragg the attack would be a slaughter.', i: true },
      { fig: '/war-img/stones-river-day2.png', cap: 'Four o’clock, January 2: Breckinridge’s charge crosses toward the Union-held hill on the east bank, only to be torn apart at McFadden’s Ford by Mendenhall’s roughly fifty massed Union guns firing across the river from the west bank.', credit: 'Stuff Happened map' },
      { h: 'Into the Massed Guns', eyebrow: 'McFadden’s Ford' },
      { p: 'For a few minutes it looked like he might be wrong. The charge hit hard and drove the Union defenders back, down off the hill and across McFadden’s Ford, a shallow crossing on Stones River. And that was exactly the disaster Breckinridge had feared, because the moment his men surged across the open low ground by the ford, they came under the eye of the gun line the Union had spent the day building on the west bank. Captain John C. Mendenhall (North) had massed roughly fifty cannon there, wheel to wheel. As Breckinridge’s men crowded into the open by the river, all of it opened at once.' },
      { p: 'It was over in under an hour. The massed guns shredded the Confederate assault where it stood, the shells tearing through ranks packed into open ground with the river at their backs. More than 1,800 Confederates fell in roughly sixty minutes, better than a third of the five thousand men who made the charge. The Kentucky soldiers of Brigadier General Roger W. Hanson (South), the famous "Orphan Brigade," Kentuckians who could not go home because their state stayed in the Union, were nearly destroyed, and Hanson himself was mortally wounded. As the broken survivors fell back through the smoke, a Union counterattack drove them the rest of the way. The whole ferocious gamble had lasted less than an hour and accomplished nothing but the gutting of one of Bragg’s best divisions.' },
      { h: 'A Self-Inflicted Catastrophe', eyebrow: 'Outcome · day three (January 2)' },
      { p: 'A self-inflicted catastrophe for the South.', i: true },
      { p: 'Bragg ordered a frontal assault that his own commander on the ground called suicidal, and it was. Breckinridge’s charge briefly drove the Union back across McFadden’s Ford, then ran straight into roughly fifty massed Union guns on the far bank and was annihilated in under an hour, losing more than 1,800 men and gutting the Orphan Brigade. The attack gained nothing and bled the Army of Tennessee at the exact moment it could least afford it.' },
    ],
    meanwhile: { region: 'The Orphan Brigade', title: 'The men who couldn’t go home', body: 'The Kentuckians shattered at McFadden’s Ford carried a name that told their whole tragedy: the Orphan Brigade. Kentucky had not seceded; it stayed in the Union, and so these men had left their state to fight for the Confederacy and could not return to it, soldiers without a home to go back to. At Stones River, ordered into a charge their own division commander had begged to call off, they were cut down by the hundreds in a few minutes of cannon fire, their commander Hanson mortally wounded leading them. Of all the units wrecked in Breckinridge’s doomed assault, none lost more, and none had less to gain, cut down not for any ground taken but to satisfy an order Bragg would not take back. They were orphaned twice over by the end of January 2.' },
  },

  'the-cost-and-the-meaning': {
    eyebrow: 'Stones River · The cost & the meaning',
    title: 'A Hard-Earned Victory',
    blocks: [
      { p: 'Bragg (South) had thought he won on December 31. Two days later he knew he hadn’t. His army was bled white, Breckinridge’s charge had cost him a division for nothing, Rosecrans was being reinforced and resupplied while the Confederates could not be, and a cold winter rain was swelling Stones River behind him, threatening to trap his army on the wrong side of a rising stream. With perhaps twenty thousand men still fit to fight and the situation worsening by the hour, Bragg withdrew on the night of January 3, falling back about 36 miles (58 km) south toward Tullahoma, Tennessee. Rosecrans (North) occupied Murfreesboro on January 5. He did not pursue, a choice he would be second-guessed for, but he had won. The army that retreats off the field is the army that lost, and that army was Bragg’s.' },
      { h: 'The Number Is the Whole Story', eyebrow: 'The cost' },
      { p: 'In three days of fighting, the two armies suffered somewhere between 24,600 and 25,600 casualties combined (killed, wounded, and missing) out of roughly 76,000 men engaged. The Confederates lost about 11,700; the Union lost between roughly 12,900 and 13,900, the uncertainty hanging on a thousand-man discrepancy in how the missing were counted. Either way, it was a third of everyone on the field.' },
      { p: 'It is the rate, not the raw total, that stands out. As a percentage of the men engaged, Stones River produced one of the very highest casualty rates of any major battle of the entire Civil War, by some reckonings bloodier than Shiloh or Antietam, by others second only to Gettysburg. The exact ranking depends on how the casualties are counted, but proportionally this small, half-forgotten battle in the Tennessee cedars was among the bloodiest the country ever fought.' },
      { h: 'The Win That Backstopped Emancipation', eyebrow: 'The meaning' },
      { p: 'And it mattered far out of proportion to its fame, for one reason above all: it took effect in the same breath as the Emancipation Proclamation. Stones River was the first major Union victory of the new era, the first won under a war aim that now openly included the end of slavery. Coming days after the Fredericksburg disaster, at the precise moment the Proclamation became law, a Union defeat here would have been a catastrophe of timing, undercutting the new policy politically the very week it took effect. Instead the North got a win. It steadied morale at the turn of the year, secured Middle Tennessee and Nashville as a forward base, and helped discourage Britain and France from formally recognizing the Confederacy as a nation, a step that would have lent the South legitimacy and possibly aid, and one a fresh Union defeat might have nudged along. Above all it put hard military weight behind a piece of paper that had just redefined what the war was for. Had Rosecrans retreated up the Nashville Pike, the story of emancipation would have opened on a defeat.' },
      { p: 'Lincoln understood exactly what he had been handed, and said so months later, in a letter to Rosecrans, in words that have lasted:' },
      { p: '"I can never forget, whilst I remember anything, that about the end of last year, and beginning of this, you gave us a hard earned victory which, had there been a defeat instead, the nation could scarcely have lived over."', q: true },
      { p: 'Abraham Lincoln to Major General William S. Rosecrans, letter of August 31, 1863.', i: true },
      { p: 'The road from Murfreesboro ran on south. Bragg dug in around Tullahoma, setting up Rosecrans’s campaign there later in 1863 and the long, grinding road toward Chattanooga and Chickamauga. But the meaning of Stones River was already fixed by January 5. It was a costly, close-run, strategically decisive Union win, bought at one of the highest casualty rates of the war, that gave the North a victory it desperately needed at the exact moment the war became, explicitly and in law, a war to end slavery.' },
      { pill: '/war-civil-war/western/chickamauga', plabel: 'Chickamauga: where the road south from Murfreesboro led' },
      { h: 'A Win That Backstopped Emancipation', eyebrow: 'Outcome · the battle' },
      { p: 'A costly Union strategic victory that backstopped emancipation.', i: true },
      { p: 'Tactically it was nearly a draw: both armies were savaged, and the killing was as concentrated as any battle of the war. But Bragg retreated and Rosecrans held the field, securing Middle Tennessee and handing Lincoln a desperately needed win days after Fredericksburg. Its deepest significance is timing: it was the first major Union victory of the Emancipation Proclamation era, put military muscle behind the new war aim at the moment it took legal effect, and helped ensure the story of emancipation did not open on a defeat.' },
    ],
    meanwhile: { region: 'Tullahoma & the road south', title: 'What came next', body: 'Bragg’s beaten army did not go far. It fell back only to Tullahoma, dug in, and waited, and Stones River settled into a strange quiet that lasted nearly half a year. The battle had not destroyed the Army of Tennessee; it had only mauled it and pushed it south. But it had pried the door to the deeper Confederacy a little further open. The next act would be Rosecrans’s Tullahoma Campaign in the summer of 1863, then the drive on Chattanooga and the bloodletting at Chickamauga. The river by Murfreesboro was one more hinge in the long Union effort to crack the western Confederacy open, and the first such hinge to turn under the banner of emancipation.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={STONES_RIVER_NARR} id={id} slug="stones-river" battleName="Stones River" theatreId="west" theatreHref="/war-civil-war/western" battleId="w-stonesriver" accent="#1d4ed8" />
}
