'use client'

// THEME section — The Limited War Ends (Off the Battlefield, kind=theme). Built through
// the war content pipeline (fact pack → author(Opus) → five gates [fact-check +
// storytelling + comprehensiveness + clarity + Lost Cause/framing] → revise → images).
// Source + gate records: audits/war-pipeline/the-limited-war-ends-*.md. Green accent; no stat
// block, no map. 'use client' is REQUIRED (reads ACCENTS from a client module).
// GENERATED from the-limited-war-ends-final.md by scripts/_build-war-themes.mjs — do not hand-edit
// the prose here; edit the final.md and rebuild.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS, WAR_ACCENT } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: `The year the short war died`,
    title: `The Limited War Ends`,
    blocks: [
      { p: `When 1862 opened, both sides still half-believed the war could be small. It would be fought between armies, on battlefields, by gentlemen’s rules, and it would leave the social order of the South, slavery included, more or less alone. The North’s aim was narrow and stated plainly: restore the Union, put the seceded states back where they belonged, and change as little else as possible along the way. The Confederacy’s aim was narrower still: survive, outlast Northern patience, and keep the world it had seceded to protect.` },
      { p: `That world rested on slavery. The eleven states had broken away to keep roughly four million people in bondage, and the armies the Confederacy raised in 1862 were raised to defend exactly that. The Union began the year fighting only to put the country back together. It would end the year fighting, by its own declared purpose, to take that property and that institution apart.` },
      { p: `This is the second chapter of the military story. It does not re-tell the battles blow by blow; it links down to those. What it carries is the year’s strategic shape, and that shape is a single hard turn: from the limited, hopeful war of 1861 to the long war of destruction that 1862’s casualties made undeniable. Two enormous numbers, Shiloh in April and Antietam in September, did most of the turning.` },
      { fig: '/war-img/the-limited-war-ends-fig1-battlefield-dead.jpg', cap: `Alexander Gardner photographed Confederate dead gathered for burial at Antietam in September 1862. When Brady put Gardner’s Antietam photographs on show in New York that October, the crowds who lined up to see them had their first real glimpse of what the war looked like.`, credit: `Alexander Gardner · September 1862 · Library of Congress Prints & Photographs Division (cwpb.01094) · public domain` },
      { h: `The plan, and the man who wouldn’t move`, eyebrow: `A magnificent army at rest` },
      { p: `The Union had a strategy by the start of 1862, even if the public still hated it. Winfield Scott, the aging general who had run the army at the war’s start, had proposed strangling the Confederacy rather than smashing it in one battle: blockade the coast, take the Mississippi River, and cut the South in two. The press had mocked it as the “Anaconda Plan,” after the snake that suffocates its prey. By 1862 Scott was gone, but his shape of the war was quietly becoming the real one.` },
      { p: `Carrying it out in the East was another matter, and the problem had a name. After the rout at First Bull Run in July 1861, command of the main Eastern army had passed to Major General George B. McClellan, and McClellan had done one thing superbly: he had built it. He drilled the green volunteers into the formidable Army of the Potomac, the great Union army of the East, and his men adored him for it. What he would not do was fight with it.` },
      { p: `McClellan was cautious to a fault. From the start he consistently overestimated the enemy in front of him, often by a factor of two, while underestimating his own strength by the same margin. His intelligence chief, Allan Pinkerton, fed him inflated counts of Confederate troops, but the habit was McClellan’s own, and it produced a general forever waiting for more men, more guns, more time before he dared to move.` },
      { p: `Lincoln’s patience wore through. He diagnosed McClellan with “a case of the slows,” and his exasperation hardened into an order. On January 27, 1862, he issued General War Order No. 1, directing all Union land and naval forces to begin a general advance by February 22, Washington’s birthday. The order worked in the West, where the generals moved. In the East, McClellan still did not.` },
      { fig: '/war-img/the-limited-war-ends-fig5-mcclellan.jpg', cap: `Major General George B. McClellan in 1862. He drilled the Army of the Potomac into the finest force the country had ever fielded, then spent the year finding reasons not to use it.`, credit: `Mathew B. Brady · 1862 · Library of Congress Prints & Photographs Division, Brady-Handy Collection (LC-BH82-1334) · public domain` },
      { p: `The Confederacy, for its part, had settled on a strategy that suited its weakness. It did not need to conquer the North; it needed only to survive. So it fought defensively to protect its territory and outlast Northern will, striking offensively when an opening appeared. A draw was a Confederate victory. That logic, defend and endure, then hit hard when the chance came, would shape everything Robert E. Lee did once he took the field.` },
      { h: `The West cracks first`, eyebrow: `The rivers as roads` },
      { p: `While the East sat, the West moved, and the key to the West was geographic. The Confederate heartland was laced with rivers, and the rivers ran the wrong way for the South: north to south, straight into the interior, which made them natural invasion roads for a Northern army that controlled them. Two in particular, the Tennessee and the Cumberland, pointed like spears into Tennessee and beyond. Each was guarded by a fort, Fort Henry on the Tennessee and Fort Donelson on the Cumberland.` },
      { p: `In February the Union took them both. Brigadier General Ulysses S. Grant, working with the ironclad gunboats of Flag Officer Andrew H. Foote (North) (a Flag Officer was a senior naval rank of the day, roughly an admiral commanding a fleet), seized Fort Henry on February 6 (Foote’s armored gunboats, warships sheathed in iron plate, did most of the work before the infantry even arrived). Grant then marched the dozen miles overland to Fort Donelson and, after several days’ fighting, forced the larger prize.` },
      { p: `When the Confederate commander at Donelson asked for terms, Grant’s reply became famous: no terms except unconditional and immediate surrender would be accepted, and he proposed to move at once. The garrison gave up, and Grant did not just win ground, he bagged an entire army, with something over twelve thousand men marched off into captivity. The North, hungry for a hero, rechristened his initials: U. S. Grant was now “Unconditional Surrender” Grant, and he was promoted to major general.` },
      { pill: '/war-civil-war/western/fort-donelson', plabel: `Fort Donelson` },
      { p: `The strategic payoff was enormous and immediate. These were the first significant Union victories of the war, and they unhinged the whole Confederate defensive line in the West. Kentucky and much of Tennessee fell into Union hands, including Nashville, the first Confederate state capital to be lost. In two weeks, while McClellan studied maps in Virginia, the Western door had been kicked open.` },
      { fig: '/war-img/the-limited-war-ends-fig2-river-gunboats.jpg', cap: `Alexander Simplot’s wood engraving for Harper’s Weekly shows Foote’s ironclad gunboats hammering the water batteries at Fort Donelson. The iron armor shrugged off Confederate shot that would have sunk any wooden warship.`, credit: `Alexander Simplot · Harper’s Weekly, March 15, 1862 · Missouri History Museum · public domain` },
      { p: `The far edges of the map settled soon after. In Arkansas in early March, three weeks after the river forts fell, a Union army won at Pea Ridge on March 7–8 and secured Missouri for the Union for good, locking down the border state whose loyalty had hung in doubt since the first summer.` },
      { pill: '/war-civil-war/trans-mississippi/pea-ridge', plabel: `Pea Ridge` },
      { p: `Farther west still, in the New Mexico Territory, a Confederate column had been driving up the Rio Grande to seize the Southwest and its mineral wealth. At Glorieta Pass in late March a Union force destroyed the Confederate supply train, and the whole invasion collapsed for want of food and ammunition; the Confederate bid for the Southwest was finished.` },
      { pill: '/war-civil-war/trans-mississippi/glorieta-pass', plabel: `Glorieta Pass` },
      { h: `Shiloh, and the cost made visible`, eyebrow: `The short war dies` },
      { p: `Grant pushed south up the Tennessee River, and at a country meeting-house called Shiloh the war showed its true face. On the morning of April 6, 1862, a Confederate army under General Albert Sidney Johnston (South) attacked Grant’s camps by surprise and nearly drove them into the river. Reinforced overnight, the Union counterattacked the next day and won the field. Johnston himself was shot in the leg leading the assault and bled to death from a severed artery, the highest-ranking soldier killed in combat on either side in the entire war; command passed to General P. G. T. Beauregard (South).` },
      { pill: '/war-civil-war/western/shiloh', plabel: `Shiloh` },
      { p: `The field was won. The number was the thing that changed the country. Roughly twenty-four thousand men were killed, wounded, or missing in those two days, split close to evenly between the armies. That single battle’s casualties, as people then reckoned it, exceeded the combined casualties of every previous American war, the Revolution, the War of 1812, and the war with Mexico, added together. Nothing in the nation’s memory had prepared anyone for it. The earlier battles that had so shocked people, Bull Run, Donelson, Pea Ridge, looked small beside it.` },
      { p: `Shiloh broke the short-war illusion on both sides at once, and it broke it most clearly in the mind of the general who had just won. Grant later wrote that until Shiloh he had believed the rebellion might collapse suddenly if one decisive victory could be won. After Shiloh he abandoned that hope. He gave up, in his own words, all idea of saving the Union except by complete conquest. A Union general had looked at the cost in April 1862 and concluded that this enemy would have to be destroyed, not bargained with. That conclusion is the whole chapter in one man’s sentence.` },
      { h: `The East stalemates, and Lee takes the offensive`, eyebrow: `The drive on Richmond fails` },
      { p: `McClellan did finally move that spring, and he moved with characteristic grandeur. Rather than march overland, he shipped the entire Army of the Potomac down the Chesapeake to Fort Monroe, at the tip of the Virginia Peninsula, and began creeping up it toward Richmond, the Confederate capital, meaning to take the city in one vast turning maneuver. It was the Peninsula Campaign, and at first it nearly worked. McClellan pushed to within about seven miles (11 km) of Richmond, close enough that the campaign to win the war in a single stroke seemed within reach.` },
      { p: `Then the cautious habit returned. Confronted by Confederate fieldworks, McClellan stopped to lay a formal siege of Yorktown (a siege is the slow business of surrounding and starving out a fortified position rather than storming it) instead of attacking, and the Confederates simply slipped away before his big guns could open. He had traded a month for a battle he never fought.` },
      { p: `McClellan’s caution had help. While he crept up the Peninsula, he kept demanding the large reinforcements waiting near Washington, and a single Confederate diversion kept freezing them in place. Off to the west, in the Shenandoah Valley, Major General Thomas J. “Stonewall” Jackson ran a lightning campaign against scattered Union forces, and at First Winchester on May 25 he routed the Federals and drove them out of the lower Valley. The raids so alarmed Washington for its own safety that Lincoln held back the reinforcements McClellan wanted, exactly the result Jackson’s diversion was meant to produce.` },
      { pill: '/war-civil-war/eastern/first-winchester', plabel: `First Winchester` },
      { p: `The campaign was decided by an accident of war. On May 31, at the Battle of Seven Pines just outside Richmond, the Confederate commander, General Joseph E. Johnston (South), was wounded by a shell fragment. The next day, June 1, 1862, Robert E. Lee took command of the army he would rename the Army of Northern Virginia. It was the single most consequential change of command in the Eastern war, and Lee made his intentions plain within weeks.` },
      { p: `Where McClellan dawdled, Lee attacked. In the last week of June, in a running series of battles known as the Seven Days, Lee hurled his army at the Federals to drive them away from Richmond. At Gaines’s Mill on June 27 he won his first victory, an assault that broke McClellan’s nerve and turned the whole campaign; from that moment McClellan thought only of retreat.` },
      { pill: '/war-civil-war/eastern/gaines-mill', plabel: `Gaines' Mill` },
      { p: `The Seven Days ended at Malvern Hill on July 1 in a grim paradox. There the Union held the high ground and slaughtered the Confederate assaults with massed artillery (Lee’s men were cut down attacking a position they could not take), so the Federals won the field outright. And McClellan kept retreating anyway, all the way back to the James River. He had won the battle and abandoned the campaign in the same afternoon.` },
      { pill: '/war-civil-war/eastern/malvern-hill', plabel: `Malvern Hill` },
      { p: `The Seven Days cost Lee more men than they cost his enemy, around twenty thousand against the Union’s roughly sixteen thousand. He had won the campaign by bleeding, and he had done it with the smaller army, a trade the South could less afford every time it made it. But the strategic result was undeniable: the great Union drive on Richmond was dead, the capital was safe, and Lee had seized the initiative he would not let go.` },
      { p: `He used it at once. With Richmond secure, Lee turned north against a fresh Union army gathering in northern Virginia under Major General John Pope (North), a boastful officer who had reportedly announced that his headquarters would be in the saddle. At Second Bull Run, on the same ground as the war’s first big battle, Lee split his army in the face of the enemy, sent Jackson to strike Pope’s supply line and then hold, and on August 30 unleashed Lieutenant General James Longstreet (South) and some twenty-five thousand men in the largest simultaneous assault of the war, crushing Pope’s flank and routing him back toward Washington.` },
      { pill: '/war-civil-war/eastern/second-bull-run', plabel: `Second Bull Run` },
      { p: `In a single summer the Eastern map had flipped. The Union had begun the season seven miles from Richmond; it ended the season with its armies thrown back on the defenses of Washington, Virginia cleared of major Union forces, and the road north open for the first time. Lee’s confidence stood at its peak, and he meant to use it on Northern soil.` },
      { fig: '/war-img/the-limited-war-ends-fig3-robert-e-lee.jpg', cap: `Robert E. Lee around 1862, about the time he took command of what he would call the Army of Northern Virginia. Within weeks of this portrait he launched the Seven Days and drove the Union army back from Richmond.`, credit: `Unknown photographer · c. 1862 · National Park Service · public domain` },
      { h: `Antietam: the bloodiest day, and the turn`, eyebrow: `The invasion stopped` },
      { p: `Riding the momentum of Second Bull Run, Lee crossed the Potomac in September on his first invasion of the North, into the slaveholding border state of Maryland. The aims were several: feed his army off Northern farms, pull the fighting out of war-ravaged Virginia, draw Maryland toward the Confederacy, and, with a victory won on Northern ground, push Britain and France toward recognizing the Confederate government and pressure Lincoln before the fall elections. The diplomacy of that gamble belongs to its own story.` },
      { p: `The invasion ran into one of the strangest pieces of luck in the war. Two Union soldiers found a copy of Lee’s campaign orders, Special Order 191, wrapped around three cigars in an abandoned field. The paper revealed that Lee had split his army into widely separated columns, a windfall that told McClellan exactly how to destroy his enemy piece by piece. And McClellan, true to himself, waited the better part of a day before acting on it, long enough for Lee to pull his scattered army back together. That delay was the last word on a general who was handed everything and still moved slow.` },
      { p: `On September 17, near Sharpsburg, the two armies met along Antietam Creek in the bloodiest single day in American history. Somewhere around twenty-three thousand men fell killed, wounded, or missing in the daylight hours of that one day, more Americans than on any other day before or since. Tactically the battle was close to a draw; neither side broke the other. But strategically it was a Union victory, because Lee’s invasion was finished. He withdrew back across the Potomac into Virginia, and the first attempt to carry the war into the North had failed.` },
      { pill: '/war-civil-war/eastern/antietam', plabel: `Antietam` },
      { p: `McClellan then declined to pursue the beaten enemy for over a month, pleading shortages of supplies and equipment despite repeated orders to move. Lincoln had seen enough. On November 5, 1862, he relieved McClellan of command, and the magnificent army-builder who would not fight passed out of the war’s central story.` },
      { fig: '/war-img/the-limited-war-ends-fig4-antietam-dead.jpg', cap: `Confederate dead along a fence on the Hagerstown road at Antietam, September 1862. This photograph, and the dozen others Gardner made that week, was the first time most Americans saw the war’s dead in the field.`, credit: `Alexander Gardner · September 1862 · Library of Congress Prints & Photographs Division (cwpb.01097) · public domain` },
      { h: `What the war was now for`, eyebrow: `A new purpose` },
      { p: `Antietam mattered for more than the men it cost, because Lincoln had been waiting for exactly this. For weeks he had carried a document he dared not release. His secretary of state, William Seward (North), had warned him not to issue it from a position of defeat; coming after a string of Union losses, Seward said, it would read like a last shriek on the retreat, the desperate gesture of a government about to lose. Lincoln needed a battlefield victory first. Antietam, for all its horror, gave him one.` },
      { p: `Five days later, on September 22, 1862, Lincoln issued the preliminary Emancipation Proclamation, warning that on January 1, 1863, the enslaved people in any state still in rebellion would be declared free. He would issue the final proclamation on that New Year’s Day, just past the edge of this chapter’s year. Its terms were carefully bounded: it reached the roughly three and a half million people held in the rebelling states, but not the loyal border states or the areas already under Union control, and for the army its most important clause authorized, for the first time, the enlistment of Black men in the Union ranks.` },
      { fig: '/war-img/the-limited-war-ends-fig6-emancipation-reading.jpg', cap: `An engraving after Francis Carpenter’s painting of Lincoln reading the first draft of the Emancipation Proclamation to his cabinet, July 22, 1862. Seward, seated at far left, urged him to hold it until a battlefield victory gave it credibility.`, credit: `F. B. Carpenter (painter), A. H. Ritchie (engraver) · published 1866 · U.S. Senate Art & History Collection · public domain` },
      { pill: '/war-civil-war/off-the-battlefield/emancipation', plabel: `Emancipation` },
      { p: `Antietam closed a second door at the same time. Since 1861 the South had banked on cotton, expecting that Britain and France, starved of the raw material their mills depended on, would have to recognize the Confederacy and break the blockade to get it. That bet had already been failing; Europe had a cotton surplus, and no government wanted to back a rebellion it judged might lose. A victory on Northern soil was meant to settle the doubt and pull the European powers in. Instead Lee was thrown back, and once the war became openly a war against slavery, no British or French government could side with the slaveholders without its own public revolting. The Confederacy never got the recognition it had counted on.` },
      { pill: '/war-civil-war/off-the-battlefield/cotton-diplomacy', plabel: `Britain, France & Cotton` },
      { p: `This is the turn the whole year had been building toward. The war had begun as a struggle to restore the Union and nothing more. With the Proclamation it became, by the North’s own declaration, a war to end slavery, the institution the South had seceded to protect. A draw would no longer return the country to what it had been. As the Union armies advanced after January 1863, they advanced as armies of liberation, freeing the enslaved as they came. The military story and the moral one had become a single story, and the hinge between them was the strategic check at Antietam. Without that victory, the Proclamation waits, and the war stays small.` },
      { h: `The river war and a brutal close`, eyebrow: `The vise tightens` },
      { p: `The Eastern battles dominated the newspapers, but 1862 was also the year the naval and river war advanced the old Anaconda strategy further than any land campaign. It began in March, in the water off Virginia, where the Confederate ironclad CSS Virginia (CSS for Confederate States Ship; an ironclad is a warship clad in iron armor, all but impervious to the cannon of the day) destroyed two wooden Union warships in an afternoon and proved every wooden navy in the world obsolete. The next morning the Union’s own ironclad, the USS Monitor (USS for United States Ship), with its revolving gun turret, fought the Virginia to a standstill in the first battle between ironclad ships in history. Naval war had changed overnight.` },
      { pill: '/war-civil-war/off-the-battlefield/ironclads', plabel: `Ironclads & the Blockade` },
      { p: `The bigger blow came at the mouth of the Mississippi. In late April, Flag Officer David G. Farragut (North) ran his fleet past Forts Jackson and St. Philip in the dark and seized New Orleans, the Confederacy’s largest city and greatest port, almost without a land fight; Major General Benjamin Butler (North) then occupied it. The South had lost its commercial capital and the southern end of its great river in a single stroke.` },
      { pill: '/war-civil-war/naval/forts-jackson', plabel: `Forts Jackson` },
      { p: `Upriver, the Union pried the Mississippi open from the north as well. At Island Number Ten, a Confederate fortress commanding a bend of the river, Pope and Foote took the position by digging a bypass canal and running gunboats past the batteries in a thunderstorm; several thousand defenders surrendered, and the upper Mississippi lay open to the Union navy.` },
      { pill: '/war-civil-war/trans-mississippi/island-number-ten', plabel: `Island Number Ten` },
      { p: `Put the year’s river victories together and the picture is the Anaconda Plan, once mocked as too slow, closing into a vise. New Orleans pressed up from the south; Island Number Ten and Forts Henry and Donelson pressed down from the north. By the end of 1862 the Confederacy held only the middle stretch of its own river. The last lock, the fortress at Vicksburg, was the next year’s work.` },
      { p: `The Western land war held the gains the spring had won, but the Confederacy fought back for them all fall in a string of counter-offensives. In early October the two armies grappled at Corinth, the northern Mississippi rail junction the Union had taken after Shiloh, and the Union held it against a hard Confederate assault, keeping a key rail crossing of the Western theater in Northern hands. The bigger Confederate gamble that month was an invasion of Kentucky, the border state Lincoln could least afford to lose, where General Braxton Bragg (South) marched an army north to draw the state into the Confederacy. He got as far as Perryville on October 8 and fought a confused, bloody collision with the Union army; but finding few Kentuckians willing to enlist and unable to feed his army off a hostile countryside, Bragg turned back and gave up the state rather than be beaten on the field.` },
      { pill: '/war-civil-war/western/corinth', plabel: `Corinth` },
      { pill: '/war-civil-war/western/perryville', plabel: `Perryville` },
      { p: `He tried once more at the year’s very end. At Stones River, near Murfreesboro, Tennessee, Bragg attacked on December 31 and again on January 2; the fighting was among the deadliest of the war by the share of men engaged. It was bloody and inconclusive on the field, but Bragg withdrew afterward and the Union kept middle Tennessee, so the strategic gain was the North’s.` },
      { pill: '/war-civil-war/western/stones-river', plabel: `Stones River` },
      { p: `The year on land ended in futility. McClellan’s replacement, Major General Ambrose Burnside (North), marched on Lee at Fredericksburg and, in December, threw his army in repeated frontal assaults uphill against Confederate troops entrenched behind a stone wall along a sunken road. Wave after wave was cut down in the open before it could reach the wall; no Union attack broke the line. The losses ran close to two to one against the attacker, the most futile slaughter the Union had yet suffered, and the defeat sank Northern morale to its lowest point of the war. Watching the carnage from the heights above, Lee said:` },
      { p: `“It is well that war is so terrible, or we should grow too fond of it.”`, q: true },
      { pill: '/war-civil-war/eastern/fredericksburg', plabel: `Fredericksburg` },
      { h: `The machine under strain`, eyebrow: `The hard war begins` },
      { p: `Step back from the battles and a system comes into view, straining. Early Union policy had aimed at a limited, conciliatory war; McClellan himself had argued it should be a war against armed forces, not against the population. The bloodshed of 1862 destroyed that idea. By year’s end the North was turning toward what would come to be called hard war: striking not only at Confederate armies but at the resources, the property, and above all the slave labor that sustained them. Congress had pointed the way in July with the Second Confiscation Act, which authorized the seizure of rebel property and freed the enslaved people of disloyal owners who came under Union control. The hard-war turn and the emancipation turn were the same turn: the North was learning to make war on the thing the war was about.` },
      { p: `The casualty numbers were not box scores; they were a manpower system beginning to crack. Shiloh near twenty-four thousand, the Seven Days some thirty-six thousand between the armies, Antietam around twenty-three thousand in a day, Fredericksburg near eighteen thousand. The Confederacy’s offensive victories cost it as many men as the Union lost or more, and Lee’s army was the smaller one. Every bloody triumph spent something the South could not replace.` },
      { p: `The strain reached past the armies into the homes that supplied them. Filling the ranks after 1862’s losses meant reaching deeper into the population on both sides, toward conscription and the resentments it bred, while the war was paid for with new taxes and, in the North, paper money issued to cover bills no peacetime budget had imagined. In the South, blockaded and stripped of its farm labor and railroads by the fighting, ordinary goods grew scarce and prices climbed out of reach. The civilians who stayed home were fighting a second war over food, money, and manpower, and it bore on the armies as directly as any battle did.` },
      { pill: '/war-civil-war/off-the-battlefield/home-front', plabel: `The Home Front` },
      { p: `The scale also overwhelmed the systems built to absorb it. A medical and supply apparatus designed for a small peacetime army now faced tens of thousands of wounded from a single day’s fighting, Shiloh alone left some seventeen thousand, Antietam as many again. Disease killed more men than the bullets did. What was killing them at this rate was a war fought with new tools on old habits. The rifle that could kill at a quarter-mile, the railroad that moved armies by the trainload, the telegraph that tied it all together, had outrun the tactics, and the casualties were the price of the gap.` },
      { pill: '/war-civil-war/off-the-battlefield/medicine', plabel: `Medicine & Disease` },
      { pill: '/war-civil-war/off-the-battlefield/new-way-of-war', plabel: `The New Way of War` },
      { p: `So 1862 closed with the last illusions gone. The short war was dead, killed by Shiloh’s number and confirmed by Antietam’s. The limited war was dead, replaced by a war that now openly reached for the South’s slaves and its sustenance. And the war’s purpose had changed under everyone’s feet: a fight begun to restore the Union had become, by the North’s own word, a war to end slavery. Both sides now understood what kind of war they were in. It would be long, it would be total, and it would be fought to the destruction of one side or the other.` },
    ],
    meanwhile: {
      region: `the war at large, 1863`,
      title: `The Turning`,
      body: `With emancipation now a war aim and Black men entering the Union ranks, 1863 became the year the long war turned. Two victories in the same week of July, Vicksburg in the West and Gettysburg in the East, split the Confederacy along its river and ended Lee’s last invasion of the North. The chapter argues the war was really won in the West, even as the East got the headlines.`,
    },
  },
}

export default function TheLimitedWarEndsThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="the-limited-war-ends"
      battleName="The Limited War Ends"
      theatreId="howfought"
      battleId="mil-1862"
      theatreHref="/war-civil-war/how-the-war-was-fought"
      accent={WAR_ACCENT}
      heroImage="/war-img/the-limited-war-ends-hero.jpg"
      heroPalette={["#3d3c1e","#4a5048","#8aadad"]}
      heroCredit={`Kurz & Allison · “Battle of Antietam,” chromolithograph, c. 1888 · Library of Congress Prints & Photographs Division (pga.01841) · public domain`}
      heroFocus="center 42%"
      heroScale={1.05}
      endHref="/war-civil-war/how-the-war-was-fought"
      endKicker={`Now a war on slavery`}
      endLabel={`Back to the Military Story`}
    />
  )
}
