'use client'

// The Battle of Germantown (October 4, 1777), battle sections · American Revolution.
// Produced through the war content pipeline (audits/war-content-pipeline.md): fact
// pack → author → critic gates (fact-check + storytelling + newcomer-clarity +
// framing, parallel) → reconcile → revise. Data only; rendered by the shared
// <BattleSectionReader>. House voice: no em-dashes (the one in Wayne's "Glorious
// day" letter is the quotation's own); American/British side-tags once on first
// mention per section. Legend control per the fact pack: the Stephen court-martial
// verdict is rendered narrower than the "drunk during the battle" legend; the
// Vergennes "fought at all" quotation is debunked in place (Trevelyan's prose, not
// Vergennes's); the captured figure is honest only as a range (~400–440). The two
// painted-later history paintings (Chew House, Paoli) carry their mandatory
// painted-after-the-fact caveats in the captions. The four column routes of
// Locator 1 render as faint road labels (the locator block draws no route lines).
// Sources: audits/war-pipeline/rev-germantown-final.md (+ rev-germantown-factpack.md).

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const GERMANTOWN_NARR: Record<string, Narr> = {
  'white-paper-in-their-hats': {
    eyebrow: 'Germantown · The audacity',
    title: 'White paper in their hats',
    blocks: [
      { fig: '/war-img/rev-germantown-tac1.jpg', cap: 'Four columns, four roads, one village. Sullivan and Wayne came straight down the Germantown Road through Mount Airy with Washington behind them; Greene\'s larger column swung in from the northeast on the Limekiln Road; militia columns took the Ridge Road and the Old York Road on the far flanks. Everything was supposed to converge on the market square at five in the morning. In the fog, the columns could not see each other, Stephen\'s division drifted toward the gunfire at the Chew House and into the back of Wayne\'s, and the plan came apart short of the square.', credit: 'Stuff Happened map' },
      { p: 'By the end of September 1777, the American war effort in Pennsylvania looked like a thing in collapse. General Sir William Howe (British), the commander in chief in America, had landed his army at the head of Chesapeake Bay in late August and marched on Philadelphia, the rebel capital and the largest city in America. On September 11 he beat George Washington (American), commander of the Continental Army (the rebels\' regular army, as opposed to part-time militia), at Brandywine Creek. On the night of September 20 a British force surprised the division of Anthony Wayne (American) in its camp near Paoli and bayoneted it in the dark, an attack Americans immediately called a massacre. And on September 26 the British marched into Philadelphia itself, unopposed. The Continental Congress (the assembly governing the rebelling colonies) fled, first to Lancaster, Pennsylvania, then on to York. American morale sagged, and desertion was a real problem.' },
      { pill: '/war-revolution/battles/brandywine', plabel: 'Brandywine: the defeat that opened the road to Philadelphia' },
      { fig: '/war-img/rev-germantown-paoli.jpg', cap: 'The midnight bayonet attack at Paoli, two weeks before Germantown, painted by Xavier della Gatta in 1782. The division being bayoneted by firelight was Anthony Wayne\'s (American). At Germantown, Wayne\'s men got their hands on the same light infantry, and British officers remembered hearing what they shouted about it.', credit: 'Xavier della Gatta · oil painting · 1782 · Wikimedia Commons · public domain' },
      { p: 'So what does a beaten army do? Here is what this one did. Eight days after losing its capital, it attacked.' },
      { p: 'It could even attack with reason, because Howe had handed Washington an opening. The British army did not concentrate inside Philadelphia. Howe posted his main field force, roughly 8,000 to 9,000 men, in a camp strung across Germantown, a village about 5 to 6 miles northwest of the city on the Germantown Road (today it is a neighborhood of Philadelphia). Lord Cornwallis (one of Howe\'s generals) and several battalions garrisoned Philadelphia proper, other detachments were off escorting supplies up from Chester and operating against Billingsport (a rebel fort on the Delaware River below the city), and every detachment made the Germantown camp a little thinner. And Howe, the man who had won at Long Island, Brandywine, and now held the capital, was confident to the point of carelessness: he built no entrenchments or redoubts (small dirt forts) at Germantown at all. He did not believe the beaten Americans would attack.' },
      { p: 'Washington knew most of this. At the end of September, intercepted intelligence and deserters told him Howe had detached troops, cutting the camp at Germantown down to that 8,000 to 9,000. His own army, reinforced by Maryland and New Jersey militia and by troops sent down from the Hudson, was back up to about 11,000 men: roughly 8,000 Continentals and 3,000 militia. On September 28 a council of war (a formal meeting of the senior generals) voted to move closer and watch. Then came news of further British detachments, and Washington committed: a dawn surprise attack on the main camp of the army that had just taken his capital.' },
      { p: 'If the shape of the idea sounds familiar, it should. The winter before, after losing New York, Washington had marched at night and fallen on a sleeping garrison at Trenton, in New Jersey, at dawn. That was the pattern that made him: lose the set-piece battle, keep the army alive, then strike the moment the enemy relaxed. Germantown was Trenton again, scaled up. And the scaling is exactly where the trouble lived. Trenton used 2,400 men in two coordinated columns against an outpost. Germantown asked 11,000 men, including 3,000 part-time militia, to march 14 to 16 miles overnight on four separate roads and hit a 9,000-man veteran army simultaneously at five in the morning, with no way for the columns to signal one another in the dark. Every piece of it had to go right at once, in the dark, on a clock, with no way to know when a piece had gone wrong.' },
      { p: 'The four columns looked like this. A column here meant a separate marching body of troops, each taking its own road. Down the Germantown Road itself, the spine of the attack, came the main blow: the divisions (the army\'s big building blocks, a few thousand men each) of John Sullivan (American), the New Hampshire general whose flank had been turned (the British had marched around the end of his line and hit it from the side) at Brandywine three weeks before, and of Anthony Wayne, whose men had been bayoneted at Paoli two weeks before and had not forgotten it, with Washington himself and the reserve (troops held back from the first clash, to be thrown in wherever they were needed) following. On the left, by the Limekiln Road, came the largest column of all, about two-thirds of the Continental infantry, under Nathanael Greene (American), Washington\'s most trusted subordinate, with the division of Adam Stephen (American), a Virginia major general with an old, prickly rivalry with Washington. On the far right, Pennsylvania militia under John Armstrong would demonstrate (make a threatening show, without pressing a real attack) along the Schuylkill River against the Hessian troops (German soldiers in British service) anchoring the British left. On the far left, Maryland and New Jersey militia under Smallwood and Forman would swing by the Old York Road against the British right and rear. The point of splitting the army four ways was to hit the strung-out British camp everywhere at once, front, both flanks, and rear, so that no part of it could form a line or come to another part\'s rescue, with everything converging on the market square at the center of the village. Four roads, four columns, one village, one clock.' },
      { fig: '/war-img/rev-germantown-loc-map.jpg', cap: 'A British manuscript map of the battle drawn at the time, from the Library of Congress. The period title gives away whose map it is: "where the rebels were repulsed." The long straight spine running through the middle of the sheet is the Germantown Road, the route of Washington\'s main column.', credit: 'period British manuscript map (attributed to John Montrésor, Howe\'s chief engineer, per the Library of Congress) · 1777 · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'The orders, issued on October 3, called for all four columns to attack precisely at five o\'clock with charged bayonets (the long blade fixed to the muzzle of the musket, a silent weapon for an attack meant to start before the enemy could shoot). And they contained one detail that tells you everything about what this plan was asking: each soldier was to put a piece of white paper in his hat, so that in the dark, at bayonet range, Americans could tell each other from the enemy. An army was marching all night to fight at first light, and it knew it might not recognize itself when it got there.' },
      { p: 'The army left its camps around Methacton Hill, in Worcester Township about 14 to 16 miles northwest of Germantown, after dusk on October 3 and marched all night. The columns ran late. Dawn found them short of their start lines. And with the dawn came something nobody had planned for: a dense ground fog, settling over the whole field, about to swallow four converging columns that already could not talk to each other. A week later, Washington described in a letter exactly what it did.' },
      { p: 'Unfortunately, the day was overcast by a dark & heavy fog, which prevented our Columns from discovering each Others movements, and from improving the advantage', q: true },
    ],
    meanwhile: { region: 'Philadelphia', title: 'The conquered capital', body: 'Eight days into the British occupation, the capture of Philadelphia had changed less than London might have hoped. Congress had not surrendered; it had simply moved, first to Lancaster and then on to York. And the army that was supposed to be broken was not in winter quarters or in pieces. It was on the roads north of the city, marching through the night toward the conquerors\' camp with white paper in its hats.' },
  },

  'a-castle-in-the-rear': {
    eyebrow: 'Germantown · The fog',
    title: 'A castle in the rear',
    blocks: [
      { p: 'A little after five in the morning on October 4, 1777, the head of the main American column came down the Germantown Road out of the dark and struck the British picket (a small forward guard posted to give the alarm) at Mount Airy, northwest of the village of Germantown. The picket\'s two cannon fired the alarm, and the battle was on. This was the column of John Sullivan (American): his own division and that of Anthony Wayne (American), the general whose men had been bayoneted at Paoli, with George Washington (American), the commander in chief, following close behind with the reserve. It was the spearpoint of an 11,000-man, four-column dawn attack on the camp of General Sir William Howe (British), whose army had taken the rebel capital of Philadelphia, 5 to 6 miles down this road, eight days before.' },
      { p: 'Posted forward were the 2nd Light Infantry battalion (light infantry: fast, aggressive troops used for skirmishing and shock work) and the 40th Regiment of Foot (an ordinary infantry regiment). The light infantry were the very corps that had bayoneted Wayne\'s division at Paoli two weeks earlier, and Wayne\'s men knew it. After a sharp fight the light infantry broke and ran back through their own camp, and Wayne\'s men went after them with the bayonet. British officers remembered cries of "At the bloodhounds" as the Americans came on.' },
      { p: 'Howe himself rode up toward the firing believing it was a raiding party, and found his elite light infantry streaming back at him.' },
      { p: 'For shame, light infantry! I never saw you retreat before.', q: true },
      { p: 'Then American grapeshot (a cannon round that sprays a cloud of iron balls) came rattling through the trees around him, and Howe understood. It was Washington\'s whole army.' },
      { p: 'For about an hour, the unthinkable was happening. Sullivan\'s column rolled some two miles down the Germantown Road into the village, overrunning the light-infantry camp as it went. And then the fog closed in for good. The dense ground fog that had come with dawn thickened as black-powder smoke poured into it, until men could see only a few dozen yards. The plan depended on four columns striking together; now they could not see one another at all. Units drifted off their roads, officers could not tell friend from enemy, and the white paper in the men\'s hats was little use in a fog that hid the hats. Washington told Congress the next day: "The Morning was extremely foggy, which prevented our improving the advantages we gained so well, as we should otherwise have done."' },
      { p: 'And in the middle of the rolling advance, a stone house filled up with redcoats (British soldiers, for their uniform coats). As the 40th Foot fell back through the village, its commander, Lieutenant Colonel Thomas Musgrave (British), threw about 120 men, six depleted companies (the small subunits of a regiment, these were down to about twenty men each), into "Cliveden," Chief Justice Benjamin Chew\'s new stone country house: walls about two feet thick, doors barred, ground-floor shutters closed, muskets at the upper windows. The American advance flowed around and past it, leaving a fortified island of British infantry behind the moving American front. Musgrave\'s stand was a superb piece of soldiering, decided in minutes under a collapsing line, and it changed the battle.' },
      { p: 'Washington and his staff, coming up with the reserve, now had a decision to make, and they made the most argued-over one of the day. Some of the staff, Timothy Pickering among them (and by several accounts Alexander Hamilton, another of Washington\'s staff officers), argued the obvious: leave a regiment to mask the house (pen the garrison in and ignore it) and push everything else on into the village where the battle was being won. Henry Knox, the army\'s chief of artillery, argued the doctrine: it was, as Pickering remembered him insisting decades later, contrary to all military rule to leave a castle in one\'s rear (the fear being that a fortified enemy left behind your line can sally out against your back, or cut your only road home if the attack goes wrong). Washington sided with Knox. The army stopped to take the castle.' },
      { p: 'It could not be taken. Knox\'s 3- and 6-pounder field guns (light cannon, named for the weight of ball they threw) simply bounced off the stone. So the infantry went in. Imagine being one of them: you cross ground you can see only a few dozen yards of, toward a house you mostly hear, every ground-floor window shuttered, every door barred, muskets working steadily from the upper floor. The cannonballs that were supposed to open the wall for you have bounced off it. You reach a door that will not give, and the men who reached it before you are lying at the step. Maxwell\'s New Jersey brigade went in like this and was thrown back with slaughter; rushes at the doors and windows failed; attempts to set the house alight failed. Lieutenant Colonel William Smith of Virginia, sent forward under a flag of truce (a party the rules of war said you did not shoot at) to demand the garrison\'s surrender, was shot down and died of the wound. John Laurens of Washington\'s staff was wounded; one French volunteer, the Chevalier de Mauduit du Plessis, actually reached the house. Roughly an hour was consumed. The reserve was sucked in piece by piece. More than 50 Americans died at the Chew House, over a third of all the Americans killed in the entire battle, in front of a building defended by about 120 men.' },
      { fig: '/war-img/rev-germantown-chew-house.jpg', cap: 'The attack on the Chew House, painted by Edward Lamson Henry about a century after the battle: a history painting, imagined long after the fact, but the scene it stages is real. About 120 British soldiers barricaded in a stone mansion swallowed the American reserve in bloody, futile assaults while the battle moved on without it.', credit: 'Edward Lamson Henry · oil painting · 1878 · Art Institute of Chicago / Wikimedia Commons · public domain' },
      { p: 'The cannonade at the house did something worse than kill the reserve: it confused everyone else. In fog, sound was the only map, and the heaviest firing on the field was now behind the American advance. It is widely credited with pulling wandering units toward it, and with convincing men at the front that they were being cut off.' },
      { p: 'One of the wandering units was a whole division. Adam Stephen (American), a Virginia major general marching with the left-hand column, drifted off the Limekiln Road in the fog, by most accounts toward the gunfire at the Chew House, and his division blundered into the rear-left of Wayne\'s. Each took the other for British. The two American formations opened fire on each other, and both broke. Wayne\'s men, at that moment deep in the village and winning, fell back through the fog, and the center of the attack began to come apart. Exactly what happened, and whose fault it was, would be argued at a court-martial within weeks.' },
      { p: 'On the far left, Nathanael Greene (American), commanding the army\'s largest column, had finally arrived, about three-quarters of an hour late behind a guide who lost the way in the dark, and his attack near Luken\'s Mill hit hard. Colonel Walter Stewart claimed a trophy in the first rush: "I engaged the 5th and 38th; both ran lustily, and I took a little flush redoubt, with three pieces of cannon from them." Colonel George Mathews\'s 9th Virginia drove deepest of any unit on the field, clean into the British camp, taking prisoners, until the British closed in around it (Lord Cornwallis\'s reinforcements, up from Philadelphia, among them) and captured the regiment entire, Mathews included.' },
      { p: 'It was not enough. Sullivan\'s men, who had been fighting longest, were running out of ammunition. The Wayne–Stephen wreck was spreading panic through the center. The militia columns on the far flanks had barely gotten into action. And the British, rallied by Howe, were counterattacking from both wings, the brigades on the left led by Charles Grey, the same "No Flint" Grey of the Paoli bayonets. Roughly three hours after the first shots at Mount Airy, around half past eight in the morning, Washington ordered a general retreat. Greene pulled his divisions out and covered the army with his guns. The battle that had been nearly won dissolved back up the roads it had come down.' },
    ],
    meanwhile: { region: 'Cliveden', title: 'The arithmetic of a stone house', body: 'About 120 British soldiers held the Chew House for the rest of the battle. More than 50 Americans died in front of it, over a third of the American dead of the whole day, and the hour the reserve spent failing to take it was the hour the attack everywhere else came apart. Henry Knox, the American artillery chief, had warned against leaving a castle in the army\'s rear. The harder lesson was what it cost to stop and besiege one.' },
  },

  'a-glorious-day': {
    eyebrow: 'Germantown · What it meant',
    title: '"A Glorious day"',
    blocks: [
      { fig: '/war-img/rev-germantown-tac2.jpg', cap: 'The campaign in one frame: Howe landed at the head of the Chesapeake in August, beat Washington at Brandywine, bayoneted Wayne\'s division at Paoli, and took Philadelphia on September 26. Washington circled to the hills northwest of the city, and on the night of October 3 his army marched 14 to 16 miles from Methacton Hill to attack the British camp at Germantown at dawn, the same lose-then-lunge instinct that had produced Trenton the winter before. The army wintered at Valley Forge.', credit: 'Stuff Happened map' },
      { p: 'The retreat was long but it was not a rout. The army of George Washington (American), the Continental Army that had attacked the British camp at Germantown at dawn and seen the attack come apart in the fog, fell back up the same roads it had marched down in the night, with Anthony Wayne\'s guns and Nathanael Greene\'s rear guard turning to check the pursuit. Many of the men marched 20 miles and more that day, on top of the 14 to 16 they had marched the night before. The British followed for about 9 miles and gave up; General Sir William Howe (British), true to form, had won his battle and declined to chase the beaten army to destruction. During the withdrawal a cannonball struck Brigadier General Francis Nash of North Carolina, who died of the wound four days later. The British had lost a senior officer of their own: Brigadier General James Agnew was killed.' },
      { p: 'The count, when it finally ran, was about twice as ugly on the side that attacked. American losses: roughly 152 killed and 521 wounded, around 650 to 675 in all, plus somewhere between 400 and 440 captured or missing, including the entire 9th Virginia regiment, taken in a body at the deepest point of the advance. Call it about 1,100 men. British losses: about 70 killed, 448 wounded, and 14 missing, a total around 520 to 535, of whom only about two dozen were Hessians (the German troops in British service). The Americans had lost roughly twice what they inflicted, and more than 50 of their dead had fallen in front of one stone house.' },
      { p: 'The collision of the two American divisions, the moment they fired into each other in the fog, went to a court-martial within weeks, and the man on trial was Adam Stephen, the Virginia major general who had been Washington\'s own second-in-command back in the 1750s, and whose division had drifted off its road and into the back of Wayne\'s. The court (a formal army trial, with John Sullivan, a fellow division commander in the battle, presiding) found him guilty of "unofficerlike behavior, in the retreat from Germantown, owing to inattention, or want of judgement; and that he has been frequently intoxicated since in the service," and sentenced him to dismissal; the sentence was approved on November 20, 1777, and Stephen was cashiered, the only major general of the Continental Army dismissed by court-martial in the whole war. The popular version of the story says he was drunk during the battle and caused the friendly fire. The verdict itself is narrower than that: unofficerlike behavior in the retreat, and frequent intoxication "since in the service." Witnesses testified to his drinking and his erratic conduct, and the legend compressed it all into one bottle on one morning. What is certain is what followed: Stephen was gone, and his division went to a young French volunteer, the Marquis de Lafayette: a quiet hinge in one of the war\'s great careers. Twenty years with Washington, ending in a cashiering ordered under the same man.' },
      { p: 'Here is the strange part, the thing that makes Germantown more than a lost battle: the army did not feel beaten. They had marched all night, surprised the conquerors of their capital, and watched the famous British light infantry run through its own camp. Most of the men blamed the fog, the stone house, and accident, not the enemy, and certainly not themselves. Washington, reporting to Congress the day after, allowed that "it may be said the day was rather unfortunate than injurious." Wayne, whose division had been winning the battle when its own side shot into it, wrote home that "Fortune smiled on our arms. The enemy were broke, dispersed, and flying in all quarters." Then he summed up the whole morning in a sentence that has no business coming out of a defeat.' },
      { p: 'Upon the whole it was a Glorious day — Our men are in the Spirits — and I am confident we shall give them a total defeat the next Action.', q: true },
      { p: 'And then there is the famous claim about France, which is wrong in a delicious way. The story goes that the Comte de Vergennes, the French foreign minister, was so impressed that Washington dared attack at all that Germantown helped persuade France to join the war, and a long, eloquent quotation usually travels with the story: that the battle\'s failure "was of small importance when weighed against the fact that it had been fought at all." Here is the catch: Vergennes never said it. The eloquent passage is the prose of Sir George Otto Trevelyan, a British historian writing more than a century later, and it has been pasted into articles under Vergennes\'s name ever since. The nineteenth-century historians themselves claimed something more modest. Trevelyan judged the battle "of great and enduring service to the American cause"; John Fiske wrote in 1891 that the French court "is said to have been influenced almost as much by the battle of Germantown as by the surrender of Burgoyne," hedge and all. What Germantown actually bought was an impression: a beaten, year-old army that assaulted Howe\'s veterans three weeks after losing its capital was an army that was not going to quit. Saratoga made the alliance. Thirteen days after Germantown, on October 17, the British army of General Burgoyne surrendered at Saratoga, and the French treaties followed that winter, signed February 6, 1778. Germantown helped make Saratoga believable.' },
      { pill: '/war-revolution/two-armies', plabel: '1777: the year of two British armies, and the surrender that bought an alliance' },
      { p: 'The British took their own legend out of the morning. The defense of the Chew House made Thomas Musgrave, the British lieutenant colonel who had held the house with about 120 men, famous, and Sir George Osborn, later colonel of the 40th Regiment, struck a medal honoring the regiment\'s stand at Cliveden, among the earliest valor medals in the British Army\'s history. And the house itself outlasted everyone. Cliveden still stands at 6401 Germantown Avenue in Philadelphia, a National Historic Landmark since 1961, owned by the National Trust for Historic Preservation and run as a museum; the Chew family lived in it for seven generations, until 1972. The battle is still on the building. The doors carry the damage from that October morning, the marble statues in the yard are still chipped where the fire caught them, and every year, on the grounds, the battle is fought again in reenactment.' },
      { fig: '/war-img/rev-germantown-cliveden.jpg', cap: 'Cliveden, at 6401 Germantown Avenue in Philadelphia: the stone house that swallowed the American reserve, now a National Historic Landmark and a museum. The Chew family lived here for seven generations, until 1972, and a reenactment of the battle is staged on the grounds every year.', credit: 'Bmzuckerman · Wikimedia Commons · CC BY 4.0' },
      { fig: '/war-img/rev-germantown-cliveden-doors.jpg', cap: 'Cliveden\'s doors, photographed for the Historic American Buildings Survey in 1967, still carrying the damage from October 4, 1777. The battle is nearly 250 years old; the scars are original.', credit: 'Cortlandt V.D. Hubbard · Historic American Buildings Survey · 1967 · Library of Congress · public domain' },
    ],
    meanwhile: { region: 'Valley Forge', title: 'Where the paradox went', body: 'Howe pulled his Germantown camp back into the Philadelphia lines within weeks, probed Washington\'s army at Whitemarsh in December without result, and settled into the captured capital for the winter. Washington\'s army went into winter quarters at Valley Forge on December 19. The gloom and desertion that had followed Brandywine never collapsed into dissolution, and the army that starved and drilled through that famous winter was the same one that had marched all night to attack its conquerors at Germantown, still insisting it had nearly won.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={GERMANTOWN_NARR}
    id={id}
    slug="germantown"
    battleName="Germantown"
    date="October 4, 1777"
    theatreId="rev-battles"
    battleId="rev-germantown"
    theatreHref="/war-revolution/battles"
    accent="var(--rev-battles)"
    endHref="/war-revolution?theatre=rev-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
