'use client'

// The Battle of Guilford Courthouse (March 15, 1781), battle sections ·
// American Revolution, southern campaign. The pyrrhic victory: the Race to the
// Dan, the three-line stand, and the win that emptied Cornwallis's army and
// sent it toward Yorktown. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → critic gates
// (fact-check + storytelling + newcomer-clarity + framing, parallel) →
// reconcile → revise. Data only; rendered by the shared <BattleSectionReader>.
// House voice: no em-dashes in prose; side-tags combatants only, once on first
// mention per section; inline-define every term. HANDLE-WITH-CARE framings per
// the fact pack: the grapeshot scene written with the cannonade as fact and the
// deliberate-order narrative explicitly as Henry Lee's later memoir account, the
// debate named (never "Cornwallis cold-bloodedly ordered his guns to fire on
// his own men"); the Fox quote attributed to Charles James Fox in the Commons
// AND flagged as a conscious echo of Plutarch's Pyrrhus; the British loss "about
// a quarter of the army"; Webster MORTALLY WOUNDED, died ~two weeks later, never
// "killed at Guilford"; the "lost my scabbard" line via a sergeant's secondhand
// account; the ~1,000 missing militia explained as dispersal not casualties;
// Tarleton's wound "at least two fingers"; tradition-layer quotes (the
// "three rounds" instruction, Webster's and Lee's battle cries) framed as what
// men remembered, not flat fact. No map/locator blocks (per the brief).
// Sources: audits/war-pipeline/rev-guilford-factpack.md.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const GUILFORD_NARR: Record<string, Narr> = {
  'race-to-the-dan': {
    eyebrow: 'Guilford Courthouse · The chase',
    title: 'The race to the Dan',
    blocks: [
      { p: 'On January 17, 1781, at a cow pasture in the South Carolina backcountry called the Cowpens, Daniel Morgan (American) had destroyed the fastest, sharpest quarter of the British southern army in under an hour. Banastre Tarleton (British), the young cavalry commander who had been the terror of the Carolinas, lost something like four men in five. When Lord Cornwallis (British), the British general charged with conquering the South, got the news the next day, he had already lost a fifth of his strength at one stroke and had nothing to show for it.' },
      { p: 'What Cornwallis did next tells you everything about the kind of soldier he was, and why the year would end the way it did. He decided to chase. Morgan was withdrawing north with his prisoners and his exhausted men, and somewhere behind Morgan was Nathanael Greene (American), the new American commander in the South, a Rhode Island Quaker and former blacksmith whom Washington trusted above any of his generals. Greene had taken over a wrecked army in December, barely 1,500 fit men, and had done the thing the manuals forbid: he had split it in the face of a stronger enemy, sending Morgan off with one wing precisely so Cornwallis would have to divide his own attention. Cowpens was the reward for that gamble. Now Greene meant to reunite his two wings and run.' },
      { p: 'Cornwallis resolved to catch him by matching his speed, and to do that he burned his own army light. At Ramsour\'s Mill, in late January, he put the torch to his baggage train, the wagons that carried the tents, the spare clothing, the rum, every comfort an eighteenth-century army hauled with it, keeping back only what carried medicine, salt, ammunition, and the sick. His whole force would now march and fight as light infantry, sleeping in the open in a Carolina winter, living on what the country gave them. Charles O\'Hara (British), who commanded Cornwallis\'s elite Brigade of Guards, wrote down what that felt like from the inside.' },
      { p: 'In this situation, without Baggage, necessaries, or Provisions of any sort, for Officer or Soldier, in the most barren inhospitable unhealthy part of North America, opposed to the most savage, inveterate perfidious cruel enemy, with zeal and with Bayonets only, it was resolved to follow Greene\'s army to the end of the World.', q: true },
      { p: 'What followed was the Race to the Dan, a 240-mile footrace across the muddy piedmont of the Carolinas through the back half of a wet winter. Greene reunited with Morgan\'s column and fell back steadily to the northeast, putting one swollen river after another between himself and the British. Light Horse Harry Lee (American), who commanded a fast mixed corps of cavalry and infantry called Lee\'s Legion, screened the rear, fighting Tarleton\'s troopers in daily skirmishes to buy the main body time. Greene\'s council of war, meeting on the road, voted to keep running rather than turn and fight at a disadvantage; the whole point of the army was that it could not be replaced, and Greene meant to keep it in being. He had long since told Washington, in substance, that his strategy was to fight, lose, recover, and fight again, and that a beaten army that survives is worth more than a brilliant stand that ends it.' },
      { p: 'The race ended at the water. On February 14, 1781, Greene\'s last troops crossed the Dan River into Virginia, and they took the boats across with them, leaving Cornwallis on the south bank with a flooded river he could not pass and no way to bridge it. The British had marched their hearts out, burned everything they owned, and arrived at the riverbank to watch the enemy disappear. Cornwallis fell back to Hillsborough, North Carolina, issued a proclamation calling the loyal subjects of the king to rise, and waited for the Loyalist masses London had promised him. They did not come, not in numbers that mattered.' },
      { p: 'And then Greene did the unexpected thing again. Resupplied and reinforced across the river, his army now swollen to roughly 4,400 men with fresh Virginia militia (part-time citizen soldiers) and Continentals (the full-time paid regulars of the Continental Army), he recrossed the Dan on February 22 and came back south, shadowing Cornwallis through the piedmont, skirmishing, never quite offering battle. By the middle of March the two armies were within a few miles of each other. Cornwallis was now down to somewhere between 1,900 and 2,100 men fit to fight, far fewer than he had brought into the Carolinas, the cumulative bill of Cowpens and the chase. Greene, outnumbering him better than two to one, decided the moment had finally come to stand. He chose the ground at a crossroads settlement called Guilford Court House, and he built it on the same blueprint Morgan had used at Cowpens.' },
      { pill: '/war-revolution/battles/cowpens', plabel: 'Cowpens: the three-line trap that built the Guilford plan' },
    ],
    meanwhile: { region: 'The Carolina piedmont', title: 'The cost of the chase', body: 'The Race to the Dan looks on a map like a draw: Cornwallis chased, Greene escaped, nobody fought a battle. But a winter march of 240 miles with no tents and little food is its own kind of casualty list. The British arrived at Guilford lean, hard, and dangerous, but also worn thin, with no reserve of strength to spend, while every river crossing and burned wagon had narrowed the difference between the two armies. By the time Cornwallis finally got the battle he wanted, the chase had already taken from him the one thing a pyrrhic victory cannot spare: the margin to bleed.' },
  },

  'the-three-lines': {
    eyebrow: 'Guilford Courthouse · The battle',
    title: 'Through the three lines',
    blocks: [
      { p: 'Nathanael Greene (American) drew up his army the way Daniel Morgan had drawn up his at Cowpens, in three lines set one behind another, so that an attacker would have to fight the same battle three times. He knew his militia would not stand against British regulars in the open, so he did not ask them to. He asked them to fire a few times and leave, and he put his irreplaceable Continentals in the back, fresh, where the British would reach them only after two earlier fights had thinned and tired them.' },
      { p: 'The first line was about 1,000 North Carolina militia, posted behind a split-rail fence at the edge of an open field, with riflemen, Lee\'s Legion, and William Washington\'s dragoons (mounted soldiers) guarding the flanks and two small cannon in the center. A rail fence at the edge of a field is a shooting position, not a place to die; the men had a fence to steady their muskets and open ground in front to shoot across. Greene rode the line before the fighting, and the men remembered him telling them to give three rounds and then they could fall back. That was the difference from Camden, the disaster the August before, where militia had been thrown into the open with no plan and no permission to leave, and had simply run. Here the running was scripted, and the regulars stood behind to catch the battle when the militia let it through.' },
      { p: 'The British came on about half past one in the afternoon, after a hard, cold approach march and a pre-dawn brush at New Garden Meeting House in which Tarleton (British) had taken a musket ball through his right hand, mangling it and costing him at least two fingers. The British deployed from column into line about 550 yards from the fence and walked forward across the open ground: James Webster (British) on the right with the 23rd and 33rd Foot, jägers (German marksmen serving as skirmishers), and light infantry, and O\'Hara (British) coming on with the Guards, the elite household infantry that was the best of Cornwallis\'s army, on the left. The North Carolina militia behind the fence got off their volleys, two ragged sheets of fire that staggered the advancing line, and then most of them did exactly what they had been told and a little more: they fell back, and a good many kept going, drifting off the field toward home rather than to the rally point. On the flanks the riflemen and Lee\'s troops held longer, killing officers, and Lee\'s men on the left cut off the Hessian Regiment von Bose (German soldiers in British service) and pulled it into a separate, wandering fight off in the woods.' },
      { p: 'The second line was about 1,200 Virginia militia under Brigadier Generals Robert Lawson and Edward Stevens, posted some 350 yards back in thick timber. The woods broke the neat British line into knots of men fighting tree to tree, which was exactly the point. Stevens\'s Virginians, some of them Cowpens veterans, held longer and hit harder than the North Carolinians had; the fighting here was close and bitter, and the British took officer-heavy losses pushing through it. But in the end the Virginians too gave way, some of them falling back through the third line, and the British, blown and bloodied, pressed on into the clearing where the courthouse stood.' },
      { p: 'The third line was the army Greene could not afford to lose: about 1,400 Continentals, Isaac Huger\'s Virginia brigade and Otho Holland Williams (American)\'s veteran Maryland brigade, drawn up in the open ground with two more guns. And here the battle nearly turned all the way over. The 2nd Battalion of Foot Guards, O\'Hara\'s elite, the best infantry on the field, came through the smoke and into a gap and threw a regiment of raw Maryland troops back in disorder. But the 1st Maryland, hard veterans of Camden and Cowpens, wheeled and met them, stopped them, and then charged them with the bayonet, and William Washington (American) brought his dragoons in twice through the Guards\' rear, sabering as they went. For a few minutes the elite of Cornwallis\'s army was being destroyed in the clearing, Guards and Marylanders and horsemen all tangled together in a single heaving mass of friend and foe.' },
      { p: 'It is at this moment that the most argued-over incident of the battle takes place, and it has to be told carefully, because the way it is usually told is not quite the way it can be proved. What is not in doubt is that the British guns, three or four pieces under Lieutenant John Macleod (British), fired grapeshot, clusters of small iron balls packed into a charge that turn a cannon into an enormous shotgun, straight into that swirling melee, and that the grape killed Cornwallis\'s own men along with the Americans, but broke up the assault and saved the Guards. What is in doubt is the cold-blooded version: the famous scene in which Cornwallis personally orders the guns to fire into the mass knowing it will hit his own troops, O\'Hara lying wounded beside the guns and begging him to stop, and Cornwallis answering that he has no choice. That scene comes from the memoir Light Horse Harry Lee published about thirty years after the battle, and battlefield historians treat it as embellished, a dramatic shaping of events by a man who was not standing at the guns. The honest account is the narrow one: the guns fired into the crisis, the grape hit both sides, and it worked. Whether it was a deliberate decision to sacrifice his own men, or simply artillery firing on a mass as the British infantry fell back, is the part nobody can settle.' },
      { p: 'However it happened, the grape did its work. The American attack broke up, the Guards got clear, and Greene, looking at a battle he was winning in the clearing but could lose in an hour if it went wrong, made the choice he had made all winter: he saved the army. Around the middle of the afternoon he ordered a withdrawal to Reedy Fork Creek, and the Continentals pulled back in good order, taking their wounded and most of their guns. Tarleton charged the retreating American flank to hurry it along, but his hand was ruined and his Legion was a shadow of the corps Cowpens had wrecked; there was no devastating pursuit of the kind he had once been famous for. Greene\'s army marched off the field beaten but intact. Cornwallis was left holding the courthouse, the clearing, and the dead.' },
    ],
    meanwhile: { region: 'The clearing at the courthouse', title: 'The price of the Guards', body: 'The fight in the third line is where the battle was won on paper and lost in fact. The two battalions of Foot Guards, the elite of Cornwallis\'s whole force, lost something close to 56% of their men and nearly all their officers in the few terrible minutes around the guns. An army can hold a field with troops like that and still be finished, because troops like that cannot be replaced in the middle of a hostile continent. The grapeshot saved the Guards as a body of men on March 15. It could not give Cornwallis back the army the Guards had been.' },
  },

  'another-such-victory': {
    eyebrow: 'Guilford Courthouse · The meaning',
    title: 'Another such victory',
    blocks: [
      { p: 'By the rules of the eighteenth century, the side left holding the field had won, and Cornwallis (British) was left holding the field. He fired a victory salute, sent off a dispatch claiming the day, and by the strict letter of it he was right. But a soldier counts the morning after, and the morning after was grim. His official return showed about 93 killed, 413 wounded, and 26 missing, roughly 532 men, about a quarter of everyone he had brought to the fight, and historians who have gone through the pension records think even that may undercount the real total by fifteen or twenty percent. James Webster (British), his finest subordinate, was dying of a shattered leg. O\'Hara (British) was badly wounded. The Guards were wrecked. And the most damning fact of all was the simplest: Cornwallis could not pursue. The army that wins a battle is supposed to chase the army that loses it, and he was too weak even to do that. Nathanael Greene (American) marched away unmolested, and within days was looking for his next fight.' },
      { p: 'Set the British loss of about a quarter of the army against Greene\'s, and the shape of the day becomes clear. Greene\'s return showed about 79 killed and some 185 wounded, plus around a thousand "missing," but that missing column is misleading, and it is the kind of detail the honest version has to explain. Most of those thousand were the North Carolina militia of the first line, who had fired their volleys and melted away toward home rather than to the rally point. They were not killed and they were not captured; they were simply gone, more or less as the plan had allowed for, just gone farther than intended. Strip them out and Greene\'s effective loss was something like six percent of his force, against the British quarter. The winner had bled roughly four times as hard as the loser. That sentence is the whole battle.' },
      { p: 'Cornwallis could not stay. He limped his wounded to Ramsey\'s Mill on the Deep River, rested nearly two weeks, and then marched the remnant southeast to Wilmington on the North Carolina coast to refit and resupply by sea, because he could no longer feed his army off a country that hated him. And then he made the decision that turned a battlefield victory into a strategic ruin. In late April, against the advice of his commander in chief, Sir Henry Clinton in New York, who wanted him back in South Carolina, Cornwallis marched north out of the Carolinas altogether, into Virginia. His reasoning had a logic to it: the Carolinas could never be held, he argued, as long as Greene could always slip across the border into Virginia to refit and come back; cut the supply at its Virginia root and the whole South would fall. So he marched away from the war he had been sent to win, toward a war nobody had ordered, on a road whose end he could not see. It ran to a small tobacco port called Yorktown, and to a surrender there in October, with a French fleet across the bay and Washington and Rochambeau across the neck.' },
      { p: 'Behind him, Greene did exactly what Cornwallis\'s march made possible. With the main British field army gone north, Greene turned south and went after the chain of British posts that held the interior of South Carolina and Georgia, reducing them one by one. He lost most of the battles he fought doing it, the spring and summer fights at Hobkirk\'s Hill, at the fortified post of Ninety Six, and at Eutaw Springs, and won the campaign anyway, because each fight cost the British a garrison they could not replace and gained Greene ground he could. By the end of 1781 the king\'s men in the whole South held nothing but Savannah and Charleston, and within another year they had given those up too. Guilford was the hinge. The day Cornwallis won the field was the day he lost the South.' },
      { p: 'They understood this in London faster than Cornwallis did in the field. When the news of the victory reached Parliament, Charles James Fox, the great Whig orator who led the opposition to the war, rose in the House of Commons and pronounced the verdict that has stuck to the battle ever since. He was not coining a fresh phrase; he was reaching back across two thousand years to Plutarch and the ancient Greek king Pyrrhus of Epirus, who beat the Romans twice at a cost so ruinous that he is supposed to have said one more such victory would leave him with no army at all, the origin of the words "pyrrhic victory." Fox aimed the old line straight at Guilford Courthouse.' },
      { p: 'Another such victory would ruin the British army.', q: true },
      { p: 'It was the exact truth, and Fox knew his classics well enough to know it had been the truth once before. Cornwallis had won the kind of victory that an army does not survive. He had marched 240 miles in a winter, burned everything he owned, and beaten an enemy twice his size, and at the end of it all he had emptied his army into the Carolina mud for a courthouse he could not keep and a province he had to abandon. The road from the Cowpens, through the Race to the Dan, through the three bloody lines at Guilford, led him at last to a tobacco field where he would hand over his sword. Greene lost the battle and won the war in the South. Fox had it right the first time.' },
      { pill: '/war-revolution/battles/cowpens', plabel: 'Cowpens, the disaster that started the chase to Guilford' },
    ],
    meanwhile: { region: 'The House of Commons, London', title: 'A verdict two thousand years old', body: 'Fox\'s line was an act of erudition as much as opposition. Pyrrhus of Epirus beat the Romans at Heraclea and Asculum around 280 BC, each time at a cost in his best men that he could not make good, until the wins themselves bled him out of the war. Plutarch preserved the king\'s rueful remark, and Fox, reading the casualty returns from Guilford, recognized the same arithmetic at work and said so. It is why the phrase "pyrrhic victory" and the Battle of Guilford Courthouse are taught in the same breath: an ancient king and a Cornwallis, two centuries and an ocean apart, each ruined by the act of winning.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={GUILFORD_NARR}
    id={id}
    slug="guilford"
    battleName="Guilford Courthouse"
    date="March 15, 1781"
    theatreId="rev-battles"
    battleId="rev-guilford"
    theatreHref="/war-revolution/battles"
    accent="var(--rev-battles)"
    endHref="/war-revolution?theatre=rev-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
