'use client'

// THEME section — The War Within the North (Off the Battlefield, kind=theme). Built through
// the war content pipeline (fact pack → author(Opus) → five gates [fact-check +
// storytelling + comprehensiveness + clarity + Lost Cause/framing] → revise → images).
// Source + gate records: audits/war-pipeline/war-within-north-*.md. Green accent; no stat
// block, no map. 'use client' is REQUIRED (reads ACCENTS from a client module).
// GENERATED from war-within-north-final.md by scripts/_build-war-themes.mjs — do not hand-edit
// the prose here; edit the final.md and rebuild.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: `The other war the North was fighting`,
    title: `The War Within the North`,
    blocks: [
      { p: `Here is something that almost never happens in human history, and the United States did it in November 1864, in the fourth bloody year of a war that had already killed hundreds of thousands of its own people: it held a regularly scheduled presidential election, on time, with a real opposition party, an anti-administration press, and an incumbent who fully expected to lose. Wars are usually the excuse to *cancel* elections: suspend the rules, declare an emergency, and let the man in charge stay in charge until the danger passes. The danger had rarely been greater than it was for Abraham Lincoln in 1864. And the election went ahead anyway.` },
      { p: `The road there ran through some of the ugliest constitutional questions the country has ever faced. To fight the war, Lincoln's government did things that would be scandals in peacetime and were scandals to a great many people at the time: it locked up thousands of civilians without trial, tried at least one congressman before a panel of army officers instead of a jury, banished him into enemy territory for giving a speech, and shut down a major newspaper. There was, in other words, a second war going on the whole time. Not North against South, but North against itself, fought with ballots and arrests and pamphlets instead of bullets, over a single hard question: how much liberty can a free country suspend in order to save itself, before there is no free country left to save?` },
      { p: `There are no clean heroes in it. The case against Lincoln's clampdown was real, and the case for it was also real, and the honest verdict is that the country did genuinely dangerous things to itself and somehow came out the other side still a democracy.` },
      { h: `The snake that called itself Liberty`, eyebrow: `Pressure` },
      { p: `Start with the opposition, because Lincoln's hardest political problem was never the Confederate army. It was the millions of Northerners who wanted him to stop fighting it.` },
      { p: `Not every Northerner supported the war. A large faction of the Democratic Party (the party of Andrew Jackson, the president of the 1820s–30s who built it as the champion of ordinary white voters, and in this era the main rival to Lincoln's Republicans) opposed the war and wanted it ended by negotiation rather than by victory. They were called the **Peace Democrats**, and they were the political heart of Northern dissent. They said they were loyal to the Union; what they were against was the *war* to restore it. They demanded an immediate cease-fire and a negotiated settlement with the Confederacy. They opposed the draft. They especially opposed emancipation, the freeing of enslaved people, which they blamed on abolitionists (the activists pressing for slavery's end) and which they insisted had hijacked a war for the Union into a war for Black freedom that white Northerners were now being made to die for. Their slogan, coined by their leading spokesman in May 1862 and endorsed by fifteen Democratic congressmen, packed the whole program into a single line:` },
      { p: `"To maintain the Constitution as it is, and to restore the Union as it was."`, q: true },
      { p: `Read it carefully, because it is doing quiet work. "The Union as it was" meant the *prewar* Union, the Union *with slavery still in it*. "The Constitution as it is" meant: stop Lincoln's war measures, the arrests and the emancipation and the suspensions, all of which the Peace Democrats considered illegal. It was a demand to rewind the country to 1860 and pretend the whole catastrophe had never started.` },
      { p: `And here we have to be plain about something the slogan was built to hide. The Copperhead opposition to emancipation was not, at bottom, a constitutional scruple. It was a racial one. Historians are unambiguous on this: the movement was deeply racist even by the standards of its own time. Many of its followers feared that freed Black workers would flood north and compete for their jobs, and they opposed any Black political presence in their states at all. Vallandigham himself, the man who would become its national face, had voted against repealing Ohio's "Black Laws," the statutes that stripped Black Ohioans of basic civil rights. So when you read what comes next, hold this underneath it: the "liberty" the Copperheads kept invoking was, for a great many of them, the liberty of white Northerners not to share their country's future with Black people.` },
      { p: `They had a nickname, and it is one of the better stories in American political naming, because it got flipped on its head. Republicans coined "**Copperhead**" as an insult, after the eastern copperhead, a venomous snake that, unlike a rattlesnake, strikes without warning, with no rattle to announce it. The point of the slur was exactly that: these were hidden, treacherous enemies, not out on the battlefield in gray uniforms but at home, smiling, striking from inside the Union itself. The *New York Tribune* is usually credited with first hurling the word at the Peace Democrats in the summer of 1861, though the exact date the snake-slur stuck is the kind of detail secondary sources repeat more confidently than the record can quite support. What is solid, and wonderful, is what the Peace Democrats did with the insult. Instead of rejecting it, they *embraced* it and reinterpreted the "copper head" not as the snake but as the head of **Liberty**. The large copper one-cent coin of the day carried an image of Liberty's head, so Copperheads cut that Liberty head out of their pennies and pinned it to their lapels as a badge, recasting themselves as the true defenders of liberty and the Constitution against a despotic administration. The slur meant to brand them traitors; they wore it to brand themselves patriots. Both meanings are real, and you should hold both while remembering, from the paragraph above, exactly whose liberty those penny-badges were chiefly protecting.` },
      { p: `Their strength had a map, and the map matters. The Copperheads were strongest in the lower Midwest, the band of states just north of the Ohio River, especially Ohio, Indiana, and Illinois, then often called the "Old Northwest" (the contemporary term for what is now the upper Midwest). There was a concrete reason for it. Many families in that region had Southern roots and ran their commerce *down* the Ohio and Mississippi river systems toward the South, not east toward the manufacturing centers tied to the Republican North. Their livelihoods and their kinfolk both pointed the wrong way for the war. When the river trade was cut by the fighting and their sons were called up to fight people they thought of as cousins and customers, the Copperhead message landed hard: end this, restore the old Union, leave us alone.` },
      { h: `King Lincoln's most dangerous critic`, eyebrow: `Pressure` },
      { fig: '/war-img/war-within-north-vallandigham.jpg', cap: `Clement L. Vallandigham of Ohio — the Copperheads' fearless mouthpiece, the man who called the president "King Lincoln" and all but dared the government to arrest him. A lame-duck congressman with no power left to lose, he turned out to be right that arresting him was a trap: it handed the peace movement a martyr the administration spent the next year trying not to make.`, credit: `Brady-Handy studio · photograph · between 1855 and 1865 · Library of Congress, Prints & Photographs Division (via Wikimedia Commons) · public domain` },
      { p: `The Copperhead movement had a face, and it belonged to a lame-duck congressman (one still in office but already voted out, so politically powerless) from Ohio who all but dared the government to arrest him. He turned out to be right that arresting him was a trap.` },
      { p: `**Clement L. Vallandigham** (Peace Democrat), pronounced "val-AN-dig-ham," was born in 1820 in New Lisbon, Ohio, and served in the U.S. House of Representatives (the larger, population-based chamber of Congress) from 1858 until early 1863, when he lost his seat after his district was redrawn. He was the acknowledged leader of the Copperhead faction and its most fearless mouthpiece. His central charge was blunt and incendiary: that the war had been quietly converted from a war for the Union into a war to free enslaved people, and that it was being prosecuted at the cost of white Northerners' liberties by an administration that had become a despotism. He had a name for that despotism. He called the president "**King Lincoln**."` },
      { p: `In a speech on the floor of the House (the chamber where members of Congress debate and vote) on January 14, 1863, two weeks after the Emancipation Proclamation, Lincoln's order freeing enslaved people in the rebelling states, took effect, Vallandigham reduced his whole indictment to a single line that he is reliably recorded as having spoken:` },
      { p: `"War for the Union was abandoned; war for the negro openly begun, and with stronger battalions than before."`, q: true },
      { p: `He demanded an armistice (a halt to the fighting) and a negotiated peace. This was protected political speech by any peacetime standard: a congressman attacking the president's war from the floor of Congress is about as core as free speech gets. But the country was not at peace, and a Union general was about to decide that some speech, in some places, was a weapon.` },
      { h: `Arrested in the night, tried by soldiers, banished to the enemy`, eyebrow: `Turning point` },
      { fig: '/war-img/war-within-north-burnside.jpg', cap: `Major General Ambrose Burnside, commander of the Department of the Ohio, whose General Order No. 38 announced that an army general could put civilians on trial for political speech. It was Burnside's soldiers who broke down Vallandigham's door at twenty minutes to three in the morning — and Burnside again, weeks later, who shut down the *Chicago Times*, only to have Lincoln overrule him both times.`, credit: `Brady-Handy studio · photograph · c. 1865 · Library of Congress, Prints & Photographs Division (via Wikimedia Commons) · public domain` },
      { p: `What turned Vallandigham from a loud nuisance into a national crisis was a single military order and the army's decision to enforce it against a civilian politician.` },
      { p: `On April 13, 1863, **Ambrose Burnside**, a major general commanding the military district covering the Copperhead heartland, formally the **Department of the Ohio**, issued **General Order No. 38**. (A "general order" is a standing command issued to everyone under a commander's authority, with the force of military law inside his district.) The order declared, in substance, that expressing sympathy for the enemy would not be tolerated in the department, and that people who committed "treason, expressed or implied" could be tried by **military commission**, a court made up of army officers rather than a civilian judge and jury. Crucially, it reached past soldiers to civilians, and past actions to *words*. (The precise wording of the order is paraphrased differently across sources; the substance, sympathy for the enemy forbidden, military-commission trials authorized, issued by Burnside in April 1863, is firm.) It was, in effect, an army general announcing that he could put civilians on trial for political speech.` },
      { p: `Vallandigham treated the order as a gauntlet thrown down, and he picked it up. At a Democratic rally in Mount Vernon, Ohio, on May 1, 1863, he denounced the war and the administration and openly defied Order No. 38, telling the crowd, in the gist of it, that the war's real purpose was to free Black Americans while enslaving white ones under King Lincoln, a white-supremacist inversion of reality that equated wartime conscription and the suspension of a few legal protections with chattel slavery itself, while treating the actual bondage of some four million Black people as the natural order being disturbed. Union officers in plain clothes stood in the audience taking notes. (No fully reliable word-for-word transcript of the Mount Vernon speech survives. It was an outdoor stump speech, and the army's note-takers and Vallandigham's own account differ, so it is described here in paraphrase, not quoted.)` },
      { p: `Burnside's response was not subtle, and it played out in the dark. At roughly twenty minutes to three on the morning of May 5, 1863, about a hundred and fifty Union soldiers came through the sleeping streets of Dayton, Ohio, and surrounded a single private house. They pounded on the door; when no one opened it, they broke it down and went up the stairs. The man they had come for was no soldier and no spy. He was a former congressman, asleep in his own bed, and they pulled him out of it. By the time the sun came up, Clement Vallandigham was on his way under guard to Cincinnati, and he had become the most famous political prisoner in the country. He had also, by walking into Order No. 38 with his eyes open, arranged the whole thing on purpose.` },
      { p: `In Cincinnati, on May 6 and 7, he was tried, not before a civilian court but before a military commission, on the charge of publicly expressing sympathy for those in arms against the government with the object of weakening the government's effort to suppress the rebellion. The trial produced its own small drama. Vallandigham stood before the panel of army officers and refused to recognize that they had any right to judge him at all: he was a civilian, the civilian courts in Ohio were open and doing business, and a citizen could not lawfully be hauled before a military tribunal while the regular courts sat down the street. He declined to enter a plea. The officers convicted him anyway and sentenced him to confinement for the rest of the war.` },
      { p: `There was one more door for Vallandigham to try, and he tried it: he carried his case to the Supreme Court of the United States, arguing that the military commission had no lawful power over a civilian. In February 1864 the Court answered, and dodged. In a unanimous ruling (*Ex parte Vallandigham*), the justices held that they had no jurisdiction to review the proceedings of a military commission at all, and so refused to decide the constitutional question his case raised. The country's highest court had looked at the practice of trying civilians before army officers and declined to say whether it was legal. That question would have to wait until after the war, which is exactly why, when the Court finally did rule on the merits in *Ex parte Milligan* (1866, below), it mattered so much.` },
      { p: `But before any of that, Lincoln stepped in, and the move he made was as shrewd as it was strange. He understood immediately that locking Vallandigham in a fort would hand the Copperheads a *martyr*, a living symbol of the despotism they were warning about. So on May 19, 1863, Lincoln reduced (commuted) the sentence: instead of prison, Vallandigham would be sent through the Union lines and deposited **inside the Confederacy**. The leader of the Northern peace movement was, in effect, deported to the country he was accused of sympathizing with. He was delivered under guard to Confederate lines in Tennessee in late May.` },
      { p: `And then the punishment turned into a farce, which tells you a great deal about who Vallandigham actually was. The Confederacy did not want him either. He was an anti-war Northerner, not a secessionist, an embarrassment to the people he was supposed to be in league with. He was briefly held at Wilmington, North Carolina, then slipped out on a blockade-runner (a ship that ran past the Union Navy ships blockading Southern ports) to Bermuda, sailed on to Canada, and first came ashore near Niagara Falls, taking rooms at the Clifton House on the Canadian side. Only later did he relocate to Windsor, Ontario, directly across the river from Detroit. He was a man banished from his own country by his own government and unwelcome in the enemy's, running out the war on foreign soil within sight of home.` },
      { p: `From across that border, he ran for governor of Ohio. While he was being expelled into the Confederacy, the Ohio Democratic convention had nominated him for governor *in absentia* (in his absence) on June 11, 1863, by a lopsided vote of 411 to 11. So through the summer and fall of 1863 the Copperhead leader campaigned for the governorship of a state he was legally forbidden to enter, from Canadian soil. On October 13, 1863, Ohio's voters answered. They crushed him. The War Democrat John Brough (a Democrat who supported prosecuting the war, running on the pro-Union ticket) beat Vallandigham by a wide margin, roughly 288,000 to 187,000, about a 100,000-vote margin, with the soldiers voting in the field going overwhelmingly against him. The result was read across the country as a referendum, and the verdict was unmistakable: even in the Copperhead heartland, even with their most famous man on the ballot, the voters rejected the peace platform. For Lincoln's administration in the dark autumn of 1863, it was an enormous relief.` },
      { p: `Vallandigham was not done. He slipped back across the Canadian border into Ohio in June 1864, under heavy disguise, and Lincoln, having learned the lesson, simply ignored him rather than make him a martyr a second time. He would surface again, with consequences, at the Democratic convention of 1864. (As an aside that has nothing to do with the war but is too remarkable to omit: Vallandigham died in 1871, as a defense lawyer, while demonstrating to a jury how a shooting victim could have accidentally killed himself, and accidentally killed himself with a pistol he believed was unloaded, winning the case and his client's acquittal at the cost of his own life.)` },
      { h: `"Must I shoot a simple-minded soldier boy?"`, eyebrow: `Pressure` },
      { fig: '/war-img/war-within-north-lincoln-1863.jpg', cap: `The "King Lincoln" his critics raged against: Abraham Lincoln photographed in November 1863, the same year he answered the Copperheads in the Corning letter with the line that has outlived the whole episode — "Must I shoot a simple-minded soldier boy who deserts, while I must not touch a hair of a wiley agitator who induces him to desert?" The misspelling is his own.`, credit: `Alexander Gardner · collodion print · 8 November 1863 · (via Wikimedia Commons) · public domain` },
      { p: `The Vallandigham arrest forced Lincoln to do something presidents usually avoid: explain himself, in public and in detail, on the most dangerous question of the war.` },
      { p: `Picture the oddity of the scene first. The president of the United States, in the middle of a civil war, sat down to write a long, careful public letter (not to a general or a foreign minister, but to a railroad executive in Albany), knowing every word would be reprinted in newspapers across the country. After the arrest, a group of New York Democrats led by the railroad magnate Erastus Corning had sent Lincoln a set of formal resolutions denouncing the arrest as unconstitutional. Lincoln answered them on June 12, 1863, in that public letter addressed to "Hon. Erastus Corning & others," the **Corning letter**, which became one of his most important public defenses of wartime presidential power. His argument cut to the bone. Vallandigham, he insisted, had not been arrested for *criticizing* the administration but for *materially damaging the army*: for working, with real effect, to keep men from enlisting and to persuade soldiers to desert:` },
      { p: `"Mr. Vallandigham avows his hostility to the war on the part of the Union; and his arrest was made because he was laboring, with some effect, to prevent the raising of troops, to encourage desertions from the army, and to leave the rebellion without an adequate military force to suppress it."`, q: true },
      { p: `Then came the line that has outlived the whole episode, the moral hinge of his entire case:` },
      { p: `"Must I shoot a simple-minded soldier boy who deserts, while I must not touch a hair of a wiley agitator who induces him to desert?"`, q: true },
      { p: `(The misspellings, "wiley" and elsewhere "contemptable," are Lincoln's own, preserved here as he wrote them.) To silence the agitator and save the boy, he concluded, was "not only constitutional, but, withal, a great mercy."` },
      { p: `This deserves to be stated fairly from both sides, because it has never really been settled. Lincoln's case: in an actual rebellion, speech that recruits desertion and obstructs enlistment is not mere opinion. It is a weapon aimed at the army's survival, and the Constitution itself contemplates suspending its normal protections "when in cases of rebellion or invasion the public safety may require it." The critics' case, then and ever since: a recent member of Congress was dragged from his bed by soldiers in the middle of the night, tried before a panel of army officers rather than a jury for the content of a political speech, and banished from his own country for dissent. A government that can do that to a congressman can do it to anyone, which is precisely the kind of power a free republic is supposed to deny itself. Both of those are strong arguments. The war never resolved which one was right. Neither, really, has the country since.` },
      { h: `The Great Writ and the Chief Justice who said no`, eyebrow: `Pressure` },
      { fig: '/war-img/war-within-north-taney.jpg', cap: `Roger B. Taney, Chief Justice of the United States and author of the despised *Dred Scott* decision — the man who, in the war's first weeks, told the president flatly that suspending habeas corpus was Congress's power, not his, and ordered the prisoner released. Lincoln simply ignored him. The Chief Justice had said no, and there was no machinery on earth to make the president obey.`, credit: `Brady-Handy studio · photograph · between 1855 and 1860 · Library of Congress, Prints & Photographs Division (via Wikimedia Commons) · public domain` },
      { p: `Underneath the Vallandigham drama lay the deeper machinery that made it possible. The legal fight over that machinery started in the war's very first weeks, with the Chief Justice of the United States ruling flatly against the president, and the president ignoring him.` },
      { p: `The machinery has a name worth pausing on. **Habeas corpus**, Latin for "you shall have the body," is the legal right that lets anyone the government has jailed demand to be brought before a judge and shown a lawful reason for being held. It is the basic protection against simply being locked up and left there: no charge, no trial, no end date. It is old enough and important enough that lawyers call it "the Great Writ." (A **writ** is just a formal written order from a court.) To *suspend* habeas corpus is to switch that protection off, to let the government arrest people and hold them indefinitely without bringing them before any judge at all.` },
      { p: `Lincoln suspended it, and he did so early and on his own authority. Within weeks of the war's first shots, with Washington nearly cut off from the North and the slave state of Maryland (which wrapped around the capital on three sides) seething with secessionist feeling, Lincoln on April 27, 1861, authorized the army to suspend habeas corpus along the military line between Philadelphia and Washington, so it could arrest and hold suspected saboteurs and secessionists without going through the civil courts. The problem was constitutional and immediate. The clause permitting suspension sits in **Article I of the Constitution**, the article that lays out the powers of *Congress*, which is exactly why this mattered: if the power to suspend habeas lives in Congress's article, then arguably only Congress, not the president acting alone, could switch the protection off. Lincoln did it anyway. Congress did not formally authorize the suspension until the Habeas Corpus Act of March 3, 1863, nearly two years later.` },
      { p: `The challenge came almost at once, and from the very top of the judiciary. A Maryland secessionist militia officer named John Merryman was arrested by the army and held at Fort McHenry in Baltimore. His case reached **Roger B. Taney**, the Chief Justice of the United States and the author of the notorious *Dred Scott* decision of 1857, the Supreme Court's most infamous ruling, which had declared that Black Americans were not citizens and had no rights the government was bound to respect, and which had made Taney a reviled figure across the North. In that era, justices also rode "circuit," presiding over lower federal courts in their region; it was in that lower-court role, not as the full Supreme Court, that Taney issued an opinion in late May 1861, ***Ex parte Merryman*** (the Latin label simply means the case was brought by one side alone, without the other party present), holding that the president had **no** power to suspend habeas corpus, that the power belonged to Congress alone, and ordering Merryman released.` },
      { p: `Lincoln ignored the order. And it is worth sitting with how extraordinary that was. The Chief Justice of the United States had just told the president, in writing, that what he was doing was unlawful, and the president declined to obey. Merryman stayed locked in Fort McHenry. There was no machinery to make the president comply: no sheriff who could arrest him, no court that could physically pry open the army's prison and walk Merryman out. The Constitution had run straight into one of its own gaps, the place where a determined executive and a defiant court simply face each other with nothing in between. Lincoln did not answer Taney directly; instead he laid out his reasoning to Congress in a special message on July 4, 1861, and posed the question that has framed the debate ever since:` },
      { p: `"Are all the laws but one to go unexecuted, and the government itself go to pieces, lest that one be violated?"`, q: true },
      { p: `The "one law" was habeas corpus. Lincoln's point was that if honoring that single protection meant letting the entire government collapse, and with it every *other* law, then a rigid insistence on that one law was not principle but suicide. It is a genuinely powerful argument. It is also, his critics noted, exactly the argument every strongman in history has reached for: the emergency is too grave for the ordinary rules. That both of those can be true at once is the whole uncomfortable point.` },
      { h: `More than thirteen thousand, and the trouble with that number`, eyebrow: `Pressure` },
      { p: `So how big did the clampdown actually get? This is where the story is most often told badly. It is worth getting right, because the most-repeated statistic about it is also the least reliable.` },
      { p: `For generations, the figure cited for civilians arrested by military authority during the war was around 13,000 to 14,000, and one suspiciously precise number, 13,535, got passed from book to book as if it had been carefully counted. It had not. The historian **Mark E. Neely Jr.**, in his Pulitzer Prize–winning *The Fate of Liberty: Abraham Lincoln and Civil Liberties* (1991), the leading modern study of the subject, went looking for the basis of that famous number and found it to be, in his words, unverifiable and erroneous. Digging through the surviving records, he documented at least about 14,000 arrests and concluded the true total was *higher*, and ultimately unknowable, because many arrest records were simply lost.` },
      { p: `But Neely found something more important than a bigger number. He found that the *composition* of those arrests has been badly misunderstood. A great many of the people arrested were not Northern political dissenters at all. They were blockade-runners, Confederate deserters, smugglers, and civilians in the border regions and the occupied South, people swept up by an army operating in a war zone, not editors and orators jailed for their opinions. So the honest way to state it is this: **more than 13,000 civilians were arrested by military authority, and by the leading modern study likely more**, but it would be wrong to imagine all or even most of them as political prisoners locked up for criticizing Lincoln. The clampdown on dissent was real. It was not as vast, or as purely about silencing opponents, as the round number makes it sound.` },
      { p: `There is one more piece of the civil-liberties record, and it cuts in Lincoln's favor. In June 1863, Burnside, the same general who had arrested Vallandigham, issued an order suppressing the *Chicago Times*, a Democratic newspaper, for what he called repeated disloyal and incendiary sentiments. And the suppression itself became a scene. Federal troops marched into the *Times* offices in the dark hours, occupied the building, and shut down the presses so the morning edition would not print. When Chicago woke to the news that the army had seized a major daily, the city did not stay quiet: thousands of people poured into the streets that very evening in protest, the kind of crowd that makes a government nervous about what it has just started. The Illinois legislature formally objected, and even some Republicans were alarmed at the precedent of soldiers shutting down a newspaper. And Lincoln *reversed it.* On June 4, 1863, he directed his Secretary of War, Edwin Stanton, to revoke Burnside's order, and the *Times* reopened. This is the crucial corrective to the villain version of the story. The same administration that arrested Vallandigham also pulled its own general back from his most aggressive suppression, twice in fact, since Lincoln had also overruled Burnside's instinct to imprison Vallandigham in favor of banishment. The record on civil liberties under Lincoln is genuinely mixed, not uniformly authoritarian, and the honest account has to hold the suppressions and the reversals in the same hand.` },
      { h: `The secret army that mostly wasn't`, eyebrow: `Pressure` },
      { p: `Then there were the secret societies. Here the danger ran in the other direction, because the threat was real enough to be frightening and exaggerated enough to become a campaign weapon.` },
      { p: `Running beneath the open Copperhead politics was a shadowy chain of secret fraternal and paramilitary orders, forever renaming themselves. The **Knights of the Golden Circle**, founded in the 1850s around a pro-slavery scheme to ring the Caribbean with new slave territory, became, by the war, a label for Copperhead secret organizing in the Midwest. Around late 1863 it was reorganized as the **Order of American Knights**, and in 1864 it became the **Order of the Sons of Liberty**, with none other than Clement Vallandigham named its "supreme commander." (Savor the absurdity for a second: a man already running for governor from a hotel in Canada was now also, on paper, the supreme commander of a secret army he could not legally cross the border to command.) There was talk of a "Northwest Conspiracy": an alleged 1864 plot, encouraged by Confederate agents operating out of Canada with Confederate money, to spark an uprising in the Old Northwest, break Confederate prisoners out of Northern prisoner-of-war camps (POW camps), arm them, and pull the lower Midwest out of the war.` },
      { p: `Now the hard part, which is telling real from inflated. Membership in these orders was claimed in the tens of thousands, and there *were* real plotters and real Confederate money behind some of the scheming. But historians stress an enormous gap between the perceived threat and the actual one. In most places only a small minority was radical enough to genuinely discourage enlistment, resist the draft, or shelter deserters, and the grand armed uprising never materialized. And there was a powerful incentive to make the menace sound bigger than it was: Republicans heading into the 1864 election had every reason to paint the entire Democratic Party as a nest of treasonous Sons of Liberty. The 1864 treason trials in Indianapolis furnished exactly that kind of campaign material. The fair conclusion is that the secret societies were neither the vast hidden army Republicans warned of nor pure fantasy. There was a real conspiratorial fringe, swimming in a much larger pool of ordinary war-weary Democrats who were getting tarred with the fringe's brush for political effect.` },
      { p: `The episode has a coda that lands after the war is over, and it is the closest thing this whole tangle ever got to a verdict. In 1864 a man named **Lambdin P. Milligan**, an alleged leader of the order in Indiana, was arrested for a plot to free Confederate prisoners and raise an insurrection, convicted by a military commission, and sentenced to death. After the war, in ***Ex parte Milligan*** (1866), the Supreme Court overturned the conviction. The Court held, in an opinion by Justice David Davis, a Supreme Court justice Lincoln himself had appointed, that civilians cannot be tried by military commissions in places where the regular civil courts are open and functioning. Indiana's courts had been open the whole time, so trying Milligan before army officers had been unconstitutional. That ruling came down in 1866, after the war and after Lincoln himself was dead. During the war the Court had *ducked* this very question, refusing in *Ex parte Vallandigham* even to look at a military commission's work. In *Milligan*, with the emergency over, it finally looked. That is the judgment history rendered, in cold peacetime, on the wartime practice of trying civilians by military commission, the same practice used on Vallandigham. The Court said: not like this, not where the courts are open.` },
      { h: `The president who expected to lose`, eyebrow: `Pressure` },
      { fig: '/war-img/war-within-north-union-banner.jpg', cap: `The pairing *was* the message. The 1864 National Union banner sets a Republican president, Abraham Lincoln, beside a Southern War Democrat, Andrew Johnson of Tennessee — the lone senator from a seceding state who refused to leave the Union. Lincoln ran not as a Republican at all but under this broadened "Union" label, a man building the widest possible alliance because he privately believed he would need every last vote.`, credit: `Currier & Ives · hand-colored lithograph · 1864 · Library of Congress, Prints & Photographs Division (via Wikimedia Commons) · public domain` },
      { p: `By August 1864, all of that pressure (the Copperheads, the war-weariness, the civil-liberties backlash) had settled into a single private conviction in Abraham Lincoln's own mind: he was going to be voted out of office.` },
      { p: `He had reason to think it. The war looked stalled and ghastly. Ulysses Grant, Lincoln's commanding general, was bogged down in the siege of Petersburg in Virginia (a grinding standoff at the Confederate rail hub south of Richmond that had dragged on for months with no end in sight) after the staggering casualties of the Overland Campaign that spring, Grant's brutal march south through Virginia that had bled the army white for ground it could not seem to hold. William Sherman was stalled outside Atlanta. The killing was enormous and the end was nowhere in sight, the Northern public was exhausted, and they blamed the man at the top.` },
      { p: `What Lincoln did with that gloom is one of the most extraordinary documents in American political history, and the way he did it is stranger than the document itself. On August 23, 1864, he wrote out a few sentences on a single sheet of paper. Then he folded it, pasted it shut, carried it into that day's cabinet meeting, and asked each of his secretaries (Seward, Stanton, Welles, and the rest) to sign their names across the blank *outside* of the sealed paper. They did it. Every one of them put his signature to a document he had not read and was not allowed to read, with no idea what he was endorsing. Lincoln said nothing about what was inside. Only after he had won the election, at the cabinet meeting of November 11, 1864, did he break the seal and let them see what they had signed. This is what history calls the "**blind memorandum**," and what it said was this:` },
      { p: `"This morning, as for some days past, it seems exceedingly probable that this Administration will not be re-elected. Then it will be my duty to so co-operate with the President elect, as to save the Union between the election and the inauguration; as he will have secured his election on such ground that he can not possibly save it afterwards."`, q: true },
      { p: `Read what the sitting president was committing to. He was saying he expected to lose, and he was pledging in advance to *cooperate fully with the man who beat him*, to spend the months between the election and the handover working to save the Union for his successor, even though he believed that successor would be running on a platform that made saving it impossible. He sealed that pledge in an envelope, in August, when the news was at its worst, and made his own cabinet witness it blind. That quiet, private decision (to accept defeat in advance and hand over power lawfully if the country chose someone else) is one of the load-bearing beams under American democracy, and it was made at the very moment Lincoln was most certain he had lost.` },
      { p: `Everything else he did that autumn was the public response to that private despair: a man who expected to lose, working to win anyway. His own coalition was fracturing on both flanks, and he had to hold it together. On his left, the **Radical Republicans**, the wing of his own party that wanted to be far harder on the South and far faster on Black rights and considered Lincoln too cautious on both, ran a third-party challenge. They nominated **John C. Frémont**, the explorer and 1856 Republican nominee, on a "Radical Democracy" ticket in late May 1864, threatening to split the anti-Confederate vote. (Frémont would withdraw in September, deciding that dividing the Union vote was too dangerous, and clear Lincoln's left flank just as the war news turned.)` },
      { p: `To shore up his right, Lincoln did some rebranding of his own. To pull in War Democrats and border-state Unionists (the slave states that had stayed in the Union: Kentucky, Maryland, Missouri, and Delaware) whose loyalties Lincoln could not afford to lose and who would never vote "Republican," he ran for reelection not as a Republican at all but under a broadened banner: the **National Union ticket**, a temporary coalition label meant to signal that this was a cross-party, save-the-country alliance rather than a partisan Republican campaign. At the National Union Convention in Baltimore on June 7 and 8, 1864, the coalition made a striking choice. It dropped Lincoln's sitting vice president, Hannibal Hamlin of Maine (his first-term running mate), and replaced him with **Andrew Johnson** of Tennessee, a Democrat and the only senator from a seceding Southern state who had refused to leave the Union with it. (When their states seceded, most Southern senators resigned and went home; Johnson was the lone exception.) A Republican president and a Southern War Democrat on one ticket: the pairing itself was the message, that this was a Union coalition, not a party. It was the work of a man building the broadest possible alliance because he privately believed he needed every last vote and feared it still would not be enough.` },
      { h: `A war hero on a peace platform`, eyebrow: `Turning point` },
      { fig: '/war-img/war-within-north-mcclellan.jpg', cap: `George B. McClellan — "Little Mac," the former commander of the Army of the Potomac and a genuine favorite of the troops before Lincoln relieved him for chronic slowness. In 1864 the Democrats nominated this *War* Democrat to run on a *peace* platform that called the war a failure, a ticket at war with itself. McClellan publicly repudiated his own platform's peace plank; it was a hard contradiction to sell to voters.`, credit: `Frank Leslie's Illustrated Newspaper · wood engraving (after a photograph) · 1861 · (via Wikimedia Commons) · public domain` },
      { p: `The Democrats, scenting a winnable election against an unpopular wartime president, gathered in Chicago at the end of August 1864 and promptly nominated themselves into a contradiction they could not escape.` },
      { p: `The convention met from August 29 to 31. Its platform (the official statement of what the party stood for) contained a peace plank (a single specific position within that larger platform) that was, in effect, a Copperhead document, written by Vallandigham himself, who had slipped back from exile and was now a force on the convention floor. The plank's decisive clause declared the war a failure outright:` },
      { p: `"...after four years of failure to restore the Union by the experiment of war... justice, humanity, liberty, and the public welfare demand that immediate efforts be made for a cessation of hostilities..."`, q: true },
      { p: `The Democrats had, on paper, committed themselves to declaring the war a failure and seeking an immediate cease-fire. And then they nominated, to run on that platform, a man who did not believe a word of it: **George B. McClellan**, Democrat and former Union general. "Little Mac" had commanded the Army of the Potomac (the Union's main army in the Eastern theater, the force charged with taking Richmond and ending the war in the East), and had been a genuine popular favorite among the troops before Lincoln relieved him for chronic slowness. His running mate was George H. Pendleton of Ohio, a peace man. The contradiction was glaring and fatal: McClellan was a *War* Democrat, a man who wanted to keep fighting until the Union was restored, running on a platform that called the war a failure and demanded it stop. McClellan tried to resolve it the only way he could, by publicly rejecting (repudiating) his own platform: in his acceptance letter he refused the peace plank, insisting the Union must be preserved and that he could not tell the soldiers who had bled that their sacrifices had been in vain. [VERIFY exact wording of McClellan's acceptance letter before any verbatim quotation.] The result was a ticket at war with itself, a peace platform topped by a war candidate, which is a hard thing to sell to voters trying to decide one clear question.` },
      { h: `Atlanta, the soldier vote, and 212 to 21`, eyebrow: `Turning point` },
      { fig: '/war-img/war-within-north-soldiers-voting.jpg', cap: `The most remarkable vote of the whole election. Pennsylvania soldiers of the Army of the James line up outside their tents to cast ballots in November 1864 — the army that could have ended Lincoln's power simply by voting him out instead chose, overwhelmingly, to keep the man sending it into battle. 1864 was the first U.S. election with widespread field voting, and the men with the most reason to be sick of the war re-elected the man waging it.`, credit: `William Waud · wood engraving, *Harper's Weekly* · 1864 · Library of Congress, Prints & Photographs Division (via Wikimedia Commons) · public domain` },
      { p: `And then, within days of the Democrats adopting a platform that declared the war a failure, the war stopped looking like a failure.` },
      { p: `On September 2, 1864, Sherman captured **Atlanta**. The timing could hardly have been crueler for the Democrats: they had bet their whole campaign on the proposition that the war could not be won, and almost the moment the ink dried on that bet, one of the Confederacy's great cities fell. And Atlanta was not just any city. It was a rail and manufacturing hub of the Confederacy, and its fall was the first hard proof that Sherman's long grind through Georgia was actually working, the first real sign that the war might be won before the country bled out entirely. The peace plank did not just become outdated; it became embarrassing. Atlanta's capture, followed that fall by the victories of Philip Sheridan in Virginia's Shenandoah Valley, transformed Northern morale and Lincoln's prospects nearly overnight. The argument that the war was hopeless collapsed the instant the war started visibly being won.` },
      { p: `Then came the most remarkable vote of the whole election: the soldiers'. Think about who was casting it. The army that was doing the fighting and the dying, the army that could have ended Lincoln's power simply by voting him out, got to decide whether the man sending it into battle should keep doing so. And it voted, overwhelmingly, to *keep him*. The men with the most reason on earth to be sick of the war re-elected the man waging it; no speech McClellan could have made would have hit as hard as that verdict coming out of the camps. Only then do the mechanics matter: the election of 1864 was the first in American history with widespread absentee and field voting, with roughly nineteen or twenty Northern states (sources differ, putting the count anywhere from about nineteen to twenty-five depending on what kind of provision is counted) passing laws that let soldiers cast ballots from camp or by proxy (a stand-in voting on their behalf), where before the war only Wisconsin had allowed it. Of about 40,247 army votes that were tallied separately, Lincoln took 30,503 to McClellan's 9,201, roughly three-quarters of the field vote. (The exact soldier-vote share is reported various ways across sources, since some states counted soldiers separately and others folded their ballots into the home totals; the documented separately-counted figure is 30,503 of 40,247, about 78 percent.)` },
      { p: `The general result, on November 8, 1864, was decisive. One note before the numbers, because they only make sense with it: an American president is not chosen by the raw nationwide popular vote but by **electoral votes**. Each state is assigned a block of them roughly according to its size, and whoever wins a state normally takes *all* of that state's electoral votes. That is why a fairly close popular split can turn into a lopsided electoral result: winning a state by a single vote still sweeps its whole block. Lincoln won most of the states, so a popular margin of about 55 to 45 became a 212-to-21 landslide in the count that actually decides the presidency.` },
      { p: `| | Lincoln (National Union) | McClellan (Democrat) | |---|---|---| | **Electoral votes** | **212** | **21** | | **Popular votes** | **2,218,388** | **1,812,807** | | **Popular share** | **about 55%** | **about 45%** |` },
      { p: `McClellan carried only three states, Kentucky, Delaware, and New Jersey, for 21 electoral votes against Lincoln's 212. Turnout ran near 74 percent of eligible voters, an astonishing figure for a country at war with itself. And the milestones stacked up: Lincoln was the first president reelected since Andrew Jackson in 1832, the first Northern president ever reelected, and the winner of the first wartime presidential election since 1812. The republic had looked its incumbent in the eye in the middle of a civil war and chosen to keep him. The sealed envelope Lincoln had pressed on his cabinet back in the worst of August, the one that began "it seems exceedingly probable that this Administration will not be re-elected," turned out to be the private record of a defeat that never came.` },
      { h: `What the ballot box proved`, eyebrow: `Consequence` },
      { p: `Step back from the vote counts, because the deepest fact about the election of 1864 is not who won. It is that it happened at all.` },
      { p: `In the middle of the bloodiest war in its history, a republic held a free, contested, regularly scheduled presidential election. There was a real opposition party. There was a peace platform openly calling the war a failure. There were anti-administration newspapers. There was an incumbent who fully expected to be thrown out, who had quietly pledged in a sealed envelope to accept the result and hand over power, and who held the election *on schedule* when postponing it under emergency powers would have been the easiest thing in the world to justify. The army voted and went back to its camps. The losing side conceded. Lincoln himself, the day after the result was clear, framed what had just been tested: whether a government of the people could sustain a great national election in the middle of a great civil war, and whether such a government was strong enough to maintain its own existence without being too strong for the liberties of its people. [VERIFY exact wording from the *Collected Works*, Response to a Serenade, November 10, 1864, before any verbatim quotation.] That question had now been answered in the affirmative, narrowly, and at a cost, but answered.` },
      { p: `And the cost matters. The same North that held that election had also suspended habeas corpus, arrested more than thirteen thousand civilians by military authority, tried civilians before panels of army officers, banished a congressman into the enemy's country for a speech, and shut down a major newspaper. Those things really happened, and the case against them was not paranoid. But the same government also reversed its own worst suppression when the *Chicago Times* was shut down, pulled its general back from imprisoning Vallandigham, and ultimately submitted the whole military-commission practice to the cold judgment of the Supreme Court, which curbed it in *Milligan*. So the honest verdict is a paradox, and the right move is to sit with it rather than resolve it cheaply. The war tested whether a democracy could survive both fierce internal dissent *and* a wartime election without hardening into a dictatorship. It did genuine damage to its own liberties in the testing. And it passed, narrowly, imperfectly, and without ever quite settling the argument about how close it came.` },
    ],
    meanwhile: {
      region: `Ford's Theatre, Washington`,
      title: `Lincoln Assassinated`,
      body: `The ballot box saved the presidency — the country re-elected its war president and the Union held. Five days after the surrender at Appomattox, a single bullet did what the election could not.`,
    },
  },
}

export default function WarWithinNorthThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="war-within-north"
      battleName="The War Within the North"
      theatreId="offfield"
      battleId="th-northwithin"
      theatreHref="/war-civil-war/off-the-battlefield"
      accent={ACCENTS.otbf}
      heroImage="/war-img/war-within-north-true-issue.jpg"
      heroPalette={["#22272e","#161a1f","#080a0c"]}
      heroCredit={`Currier & Ives · hand-colored lithograph · 1864 · Library of Congress, Prints & Photographs Division · public domain`}
      heroFocus="center 50%"
      heroScale={1}
      endHref="/war-civil-war/off-the-battlefield"
      endKicker={`The ballot held`}
      endLabel={`Back to Off the Battlefield`}
    />
  )
}
