'use client'

// THEME section — The Reckoning (Off the Battlefield, kind=theme). Built through
// the war content pipeline (fact pack → author(Opus) → five gates [fact-check +
// storytelling + comprehensiveness + clarity + Lost Cause/framing] → revise → images).
// Source + gate records: audits/war-pipeline/reckoning-*.md. Green accent; no stat
// block, no map. 'use client' is REQUIRED (reads ACCENTS from a client module).
// GENERATED from reckoning-final.md by scripts/_build-war-themes.mjs — do not hand-edit
// the prose here; edit the final.md and rebuild.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: `What it cost, what it changed, what it didn't`,
    title: `The Reckoning`,
    blocks: [
      { p: `This is where the road ends, and it ends in a graveyard.` },
      { p: `Every section of this arc has been about the war off the battlefield — the freedom seekers who freed themselves, the women who walked into the wards, the killers that were never the bullet. This last one is about what all of it cost, what it actually changed, and the one enormous thing it left undone. Because the honest truth about the Civil War is that it answered two of the great questions Americans had been fighting over for ninety years and walked away from the third — and the third was the one that mattered most to the four million people the war set free.` },
      { p: `So hold two facts side by side, because the whole section lives in the space between them. The war ended slavery and saved the Union. That is real, and it was bought with a pile of corpses larger than any other in American history. And the war did *not* secure the freedom it had won for the people it freed — the country wrote that freedom into the Constitution and then, within a decade, abandoned the will to enforce it. The guns went silent in 1865. The reckoning they were supposed to settle did not. It was deferred, not resolved, and the bill came due again only in the next century.` },
      { p: `Let's count the cost first. Then let's be honest about what got bought with it.` },
      { h: `The arithmetic of the dead`, eyebrow: `The cost` },
      { fig: '/war-img/reckoning-cold-harbor-bones.jpg', cap: `A year after the battle, Black laborers gather the skeletal remains of the soldiers who fell at Cold Harbor, Virginia, and load them onto a stretcher for reburial — the bodies had simply been left where they dropped. It is the truest possible picture of the war's arithmetic: three quarters of a million dead, and the men sent to pick up the bones were the same people the war had freed.`, credit: `John Reekie · albumen photograph (glass negative) · 1865 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `Start with the number, because the number is the thing.` },
      { p: `For more than a century the standard count of the Civil War's military dead was about **620,000** — conventionally split into roughly 360,000 on the Union side and a little over a quarter-million Confederate. Everyone always knew that number was soft. The Confederate figure in particular rested on incomplete battle reports and a crude guess at how many men had died of disease, and disease, as the Medicine section laid out, was the war's real executioner: roughly two of every three deaths came from sickness, not combat, men wasting away of dysentery in a tent rather than falling to anything an enemy did.` },
      { p: `Then, in December 2011, a demographic historian named **J. David Hacker** redid the math from the bottom up. Instead of adding up battle reports, he used newly digitized U.S. census records from 1850 through 1880 to count the *missing* — comparing how many young men should have been alive after the war, if the country had simply gone on aging normally, against how many actually were. The gap, the shortfall of men who should have been there and weren't, came to about **750,000**, with a plausible range running from **650,000 all the way to 850,000**. That is roughly 20 percent higher than the old figure, and it captures the uncounted: the disease deaths nobody tallied, the men who crawled home and died later, the toll that the battle reports never saw. It is an estimate of a range, not a hard count — nobody will ever know the exact number — but it is the best one we have, and **James McPherson**, the Pulitzer-winning historian of the war, called the new figure plausible and said he had long been convinced the old count was too low.` },
      { p: `So call it **about 750,000 dead, and possibly as many as 850,000.** Sit with that for a second, because the comparisons are staggering. The United States in 1860 held about 31 million people, which means the war killed something close to **one in every fifty Americans alive** — a share that, in a modern United States, would run into the millions of dead. And here is the comparison people reach for, told carefully, because the careful version is the true one: more American soldiers died in the Civil War than in every other American war from the Revolution through the Korean War *combined* — the War of 1812, the Mexican War, the Spanish-American War, both World Wars, Korea, all of them added together. (Only when you fold in Vietnam and the wars after it does the combined total of the others catch up, and even then the Civil War remains the single deadliest war in American history, and it isn't close.)` },
      { p: `And the dead are only the dead. Another **roughly 476,000 men were wounded** — shot, shelled, cut — and of those, an estimated **60,000 lost an arm or a leg** to the surgeon's saw. Three of every four operations performed during the war were amputations, and the men who survived them filled the postwar country with empty sleeves and pinned-up trouser legs; by one common account a state like Mississippi sank a fifth of its entire postwar budget into artificial limbs. Behind them stood the widows and the orphans, fatherless households in the hundreds of thousands, North and South.` },
      { p: `One group paid more than any other, in proportion to its numbers, and it has to be named here. Of the roughly **180,000 Black men of the United States Colored Troops** — the federal regiments of Black soldiers, most of them recently escaped or freed from slavery — **more than 36,000 died, about one in five**, a death rate around a third higher than that of white Union troops, and most of it from disease, in the worse camps and worse care that the war handed Black soldiers as a matter of course. And beyond the soldiers entirely were the freedpeople in the wartime "contraband" camps. The name itself is a window into how strange the law was: when enslaved people fled to Union lines, the army didn't quite know what to call them, so early in the war a Union general reasoned that since the Confederacy treated enslaved people as property, any property that crossed into Union hands could be seized like captured enemy goods — "contraband of war." It was a legal dodge that kept the army from having to return them, and the label stuck. These were the makeshift settlements that sprang up wherever the enslaved reached those lines, and the people in them died of disease, exposure, and starvation in numbers that nobody ever properly counted. Tens of thousands, at least, uncounted then and uncountable now. They were the freest people in the South and among the most likely to die, and history did not even keep their score.` },
      { h: `The end nobody filmed`, eyebrow: `The cost` },
      { p: `The war did not end at Appomattox — not really, not all of it. Appomattox, where Lee surrendered his army to Grant on April 9, 1865, is the moment everyone remembers and the one this arc hands to the battle layer to tell. But the Confederacy came apart over the following seven months, in a string of surrenders and one undignified capture that happened off the battlefield, in the ordinary business of a country ceasing to exist.` },
      { p: `The biggest surrender of the entire war wasn't Appomattox at all. It came seventeen days later, at a small farmhouse called **Bennett Place** near Durham Station, North Carolina, where on **April 26, 1865** the Confederate general **Joseph E. Johnston** gave up to **William T. Sherman** — and handed over not just one army but every Confederate soldier still under arms across the Carolinas, Georgia, and Florida, some **89,000 men**. Johnston did it in direct defiance of his own president, Jefferson Davis, who had ordered the armies to scatter and fight on as guerrillas. Johnston refused. He thought a guerrilla war would only get more men killed for a cause that was already lost, and he surrendered them instead.` },
      { p: `Davis himself, the president of a country that was evaporating around him, was on the run. Union cavalry caught him near **Irwinville, Georgia, on May 10, 1865**. (You may have heard he was caught fleeing in women's clothing — a story that got drawn into a hundred mocking cartoons at the time. It's a myth; let it go.) He was locked up at Fort Monroe in Virginia, briefly clapped in leg-irons, indicted for treason — and then never actually put on trial. The federal government, wary of what a treason trial might or might not establish about the legality of secession, quietly let it drop, and released him on bail in 1867.` },
      { p: `The land war flickered out in the far west, where **Edmund Kirby Smith**, commanding the Confederate forces beyond the Mississippi River, agreed to surrender on May 26 and signed the formal terms at Galveston, Texas, on **June 2, 1865**. And then, strangest of all, there was a Confederate warship that didn't get the news. The commerce raider **CSS *Shenandoah*** had spent the war hunting Union whaling ships, and it was still out doing it in the Pacific and the Bering Sea, burning American whalers, *months* after the Confederacy no longer existed. When its captain finally learned the war was over, he couldn't stomach surrendering to the United States — so he sailed the ship clear around the world and gave it up to **British authorities at Liverpool, England, on November 6, 1865**, seven months after Appomattox. The last Confederate flag came down not in the South, not in America at all, but in an English harbor, lowered by men who had no country left to fight for.` },
      { h: `A ruined land`, eyebrow: `The cost` },
      { fig: '/war-img/reckoning-richmond-ruins-2.jpg', cap: `More of Richmond's commercial heart, burned out in the same April 1865 fire — block after block of roofless walls and rubble. This is the wreckage the four million freedpeople were turned loose into: a region that would stay poor for the better part of a century, with nothing of their own to start from.`, credit: `unattributed (LOC Civil War collection) · albumen photograph (glass negative) · 1865 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `Then there was the wreckage the war left on the ground, almost all of it in the South.` },
      { p: `The cities had burned. **Richmond**, the Confederate capital, went up on April 2–3, 1865, when its own retreating defenders torched the tobacco warehouses and military stores and the fire spread out of control through the commercial downtown — the "Burnt District," the photographs of which became the visual shorthand for the whole South's defeat: gutted brick shells, a city's center reduced to chimneys. **Atlanta** had burned the previous November as Sherman left it for the sea. **Columbia, South Carolina**, burned on the night of February 17, 1865, as Sherman's army moved in — and historians still genuinely argue over who started it, retreating Confederates firing their own cotton or Union troops running wild, but the heart of the city was gutted either way.` },
      { p: `The countryside was wrecked in a quieter, more total way. Fences torn down, fields trampled and overgrown, barns empty, livestock gone — one often-cited illustration has South Carolina counting close to a million hogs before the war and only a fraction of that after, the kind of figure that, however rough, tells you a whole agricultural world had simply been eaten or scattered.` },
      { p: `But the single largest economic blow to the South wasn't a burned city. It was emancipation. This is an ugly truth that has to be stated plainly: under slavery, enslaved human beings were the South's biggest form of *capital* — the planters' wealth on paper was measured in people, and the roughly four million enslaved men, women, and children were collectively "worth," in the cold accounting of 1860, around **$3 billion**, more than all the region's land combined. When the war freed them, that entire paper fortune evaporated overnight. To the slaveholders it was the largest destruction of property in American history. To the people themselves it was the most basic kind of liberation, because they were never property — they were people, and now the law would finally have to agree. Both of those sentences describe the same event. Which one you lead with tells you which side of the war you were on.` },
      { p: `What's harder to convey is the dollar cost of the whole catastrophe, and the honest answer is that the numbers get slippery fast. The *direct* wartime spending of both sides — guns, food, wages, ships — ran to well over **$6.7 billion** in 1860s money, with the Union spending far more than the Confederacy. Some modern attempts to bundle in everything else and adjust for inflation run into the *trillions* of today's dollars, but those are rough advocacy-group estimates, so take them as a loose gesture at the scale rather than a real number. The firmer point is the long shadow: the eleven ex-Confederate states stayed poor for roughly a *century*, their land values depressed, their planters in debt, their economy reorganized not toward recovery but around sharecropping and tenant farming. The war didn't just defeat the South. It impoverished it for three generations — and the four million people it had just freed were turned loose into exactly that wreckage, with nothing of their own.` },
      { h: `Four million free — and then what?`, eyebrow: `What changed` },
      { p: `Now the other side of the ledger. For all the death and ruin, the war bought something, and it bought it permanently: it killed slavery.` },
      { p: `The Emancipation Proclamation of 1863 — covered in an earlier section — had been a *war measure*. It rested on the president's wartime powers, it freed enslaved people only in the rebelling states, and it left slavery legally untouched in the loyal border states. The moment the war ended, its legal footing would get shaky. To kill slavery for good, everywhere, forever, the country needed to change the Constitution itself. And it did.` },
      { p: `The **13th Amendment** is the one that finally did it. Its language is blunt and short: *"Neither slavery nor involuntary servitude, except as a punishment for crime whereof the party shall have been duly convicted, shall exist within the United States."* It passed the House on **January 31, 1865**, by a vote of 119 to 56, squeaking just past the two-thirds it needed, and it was ratified — approved by the required three-quarters of the states — on **December 6, 1865**. With that, the legal ownership of one human being by another, which had existed on American soil since before there was an America, was over. About **four million people** were free.` },
      { p: `And here is where the whole rest of the section turns, so read it slowly: **legal freedom is not the same as real freedom**, and the 13th Amendment, for all its world-changing power, answered almost none of the questions that came next. Were these four million people now *citizens*? Could they vote? Could they own land, sign contracts, testify in court against a white man, keep the wages they earned, move where they pleased? The amendment said none of that. It abolished the *owning* of people and stopped there. And notice the exact words of the one exception it did carry: slavery was abolished *"except as a punishment for crime."* That clause was not an accident, and the South would later pry it wide open — arrest Black men by the thousands on flimsy charges, convict them, and then put them back into forced, unpaid labor as prisoners. We'll get to how that machinery worked, because it is one of the darkest things the country built on the ruins of this amendment. For now, hold the point: the 13th Amendment opened the question of what Black freedom would actually mean in America. It did not answer it. The next twelve years were the country's attempt to — and then its decision not to.` },
      { h: `Reconstruction: the experiment`, eyebrow: `What changed` },
      { fig: '/war-img/reckoning-freedmens-bureau.jpg', cap: `A lone Freedmen's Bureau agent stands in the gap between an armed crowd of white planters on one side and freedpeople on the other — Alfred Waud's 1868 engraving of exactly the job the Bureau was given and never adequately funded to do: standing between freedpeople and the men who would otherwise cheat or attack them.`, credit: `Alfred R. Waud · wood engraving, *Harper's Weekly* (July 25, 1868) · 1868 · Library of Congress, Prints & Photographs Division (via Wikimedia Commons) · public domain` },
      { p: `The name for that attempt is **Reconstruction** — the roughly twelve-year period after the war, from about 1865 to 1877, when the country tried to figure out how to put the defeated South back together and what to do about the four million people it had just freed. It is one of the most misremembered chapters in American history, buried for a century under a mountain of lies we'll get to. So here is what actually happened, told straight.` },
      { p: `Start with what freedom looked like on the first morning, before any of the policy. For the freedpeople, one of the very first acts of being free was the search. Slavery had sold husbands away from wives, children away from mothers, scattered families across states and decades for profit — and now, suddenly, people could go looking. They walked the roads. They placed thousands of heartbreaking advertisements in Black newspapers — *information wanted* of a mother last seen on an auction block in 1849, of a son sold to a trader bound for Mississippi twenty years ago — paying for the ink with money they barely had, addressing strangers across a thousand miles in the hope that someone, somewhere, had seen a face they remembered. Most of those searches failed. That is what was at stake in Reconstruction: not an abstraction about citizenship but four million people trying to reassemble the lives that had been torn apart, and a country that had to decide whether it would help them or not.` },
      { p: `The fight over that decision began as a collision between two men's visions, and the men were the president and the Congress.` },
      { p: `The president was **Andrew Johnson**, a Tennessee Unionist and former war Democrat — a Democrat who had broken with his party to back fighting the war to hold the Union together — who had been Lincoln's second-term vice president and became president when Lincoln was murdered five days after Appomattox. Johnson wanted Reconstruction fast, lenient, and white. He handed out pardons to ex-Confederates generously, let the Southern states reorganize their governments under the same white men who had run them before the war, and flatly opposed using federal power to protect the freedpeople. Against him stood the **Radical Republicans** in Congress — men like Thaddeus Stevens in the House and Charles Sumner in the Senate — who wanted something far more ambitious: real civil and political rights for the freedpeople, federal muscle to enforce them, and a genuine remaking of the slaveholding order that had started the war in the first place.` },
      { p: `The white South showed its hand almost immediately, and it shocked the North into Congress's arms. The reorganized Southern legislatures of 1865 and 1866 passed a wave of laws called the **Black Codes** — statutes designed to rebuild slavery in everything but name. Vagrancy laws let authorities arrest any Black person who couldn't prove employment and then force them into labor contracts. Other codes barred freedpeople from many trades, restricted what property they could own and whether they could testify in court, and bound Black children to white "apprenticeships" that looked an awful lot like the thing that had just been abolished. The message was unmistakable: the South intended to nullify emancipation on the ground, whatever the Constitution said. The North got the message, and the fury it produced pushed Reconstruction out of Johnson's hands and into Congress's, where it got much harder and much more serious.` },
      { p: `Meanwhile, there was an actual federal agency trying to make freedom real on the ground. Congress had created the **Freedmen's Bureau** — formally the Bureau of Refugees, Freedmen, and Abandoned Lands — in **March 1865**, and the most human work it did was help with exactly that searching: it tried to reunite families that slavery had sold apart, formalized the marriages that slavery had refused to recognize so that couples who'd been together for decades could finally be married in the eyes of the law, and stood between freedpeople and the white employers who would otherwise cheat them. It also handed out food and medical care, set up courts, and, most lastingly, **built schools** across the South — the seedbed of Black education and of several of the historically Black colleges that still exist. It was always too small and too poorly funded for the size of the job, and Johnson fought it the whole way, vetoing its 1866 extension before Congress overrode him. And the one thing freedpeople wanted most — land of their own, the famous promise of "forty acres and a mule" that came out of one of Sherman's wartime orders — was mostly taken back, as Johnson returned confiscated plantations to the pardoned men who used to own them. The promise was made and then broken. That broken promise shaped everything that followed.` },
      { h: `The Constitution rewritten`, eyebrow: `What changed` },
      { fig: '/war-img/reckoning-first-vote.jpg', cap: `Black men line up to cast their first ballots — a tradesman with tools still in his pocket at the head of the queue — in Alfred Waud's cover for *Harper's Weekly*, November 1867. The 15th Amendment would make this a constitutional right in 1870. It is the thing the next thirty years of poll taxes and "understanding clauses" were built to take back.`, credit: `Alfred R. Waud · wood engraving, *Harper's Weekly* (Nov. 16, 1867) · 1867 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `Then Congress did the most lasting thing of the whole era: it wrote the answers to the 13th Amendment's unanswered questions directly into the Constitution.` },
      { p: `First came the **14th Amendment**, ratified on **July 9, 1868**, and it is the most consequential addition to the Constitution since the Bill of Rights. It made anyone "born or naturalized in the United States" a citizen — which at a stroke made the four million freedpeople citizens and overturned the infamous *Dred Scott* decision, the Supreme Court's 1857 ruling that had declared Black people could never be citizens at all. And it guaranteed every person the **equal protection of the laws** and **due process** against the states. Those two phrases sound like dry legalese, but they are where the next century and a half of American rights law would actually live: nearly every great civil-rights case that followed — desegregation, voting rights, and far beyond — was argued out of the equal-protection promise written here. Citizenship: settled, on paper.` },
      { p: `Then came the **15th Amendment**, ratified on **February 3, 1870**, which barred denying any man the vote "on account of race, color, or previous condition of servitude." Black men could vote. The ballot — the thing Frederick Douglass had been demanding, the thing that turns a freed person into a citizen with power — was now a constitutional right. But notice the gap, because the South certainly did: the amendment forbade denying the vote because of *race*. It said nothing about literacy tests, poll taxes, or "understanding" requirements — devices that were race-neutral on their face and would later be aimed, with surgical precision, at exactly the men the amendment was supposed to protect. The door was bolted against the obvious attack and left wide open to the clever one.` },
      { fig: '/war-img/reckoning-hiram-revels.jpg', cap: `Hiram Rhodes Revels of Mississippi, sworn in February 1870 as the first Black United States Senator — and the symbolism was almost too sharp to bear: he took a Senate seat from the very state whose secession Jefferson Davis had led, while Davis sat in a federal prison. Born free in North Carolina, a minister and educator, he is the face of the brief window when Black men governed.`, credit: `Brady-Handy studio · photograph (wet-collodion glass negative) · c. 1870 · Library of Congress, Prints & Photographs Division · public domain` },
      { h: `When Black men held office`, eyebrow: `What changed` },
      { fig: '/war-img/reckoning-black-congressmen.jpg', cap: `The 1872 Currier & Ives print "The First Colored Senator and Representatives" — Senator Revels and six Black congressmen of the 41st and 42nd Congresses. This is the part the Lost Cause later worked hardest to erase: about two thousand Black men held public office during Reconstruction, sixteen of them in Congress, men who had been property a few years earlier now writing the law.`, credit: `Currier & Ives · hand-colored lithograph · 1872 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `And for one brief, remarkable window, the promise was real. Black men voted across the South by the hundreds of thousands, and — this is the part the lies later worked hardest to erase — they *held office*.` },
      { p: `The historian **Eric Foner**, whose *Reconstruction: America's Unfinished Revolution* is the standard authority on all of this, documents **about 2,000 African Americans holding public office** during Reconstruction, everything from local sheriffs and justices of the peace up to the United States Congress. **Sixteen Black men served in Congress during the 1870s** — fourteen in the House, two in the Senate. In South Carolina, for a time, the state legislature had a Black *majority*. This was not chaos and it was not a joke, whatever the Lost Cause would later claim. It was a working democracy: men who had been the property of other men a few years earlier now sat in legislatures writing the laws.` },
      { p: `Put names to it. **Hiram Rhodes Revels** of Mississippi became the **first Black United States Senator**, sworn in on February 25, 1870 — and the symbolism was almost too sharp to bear. He represented Mississippi, the very state whose secession had been led by Jefferson Davis, who now sat in a federal prison while a Black man took a Senate seat from Davis's own state. (The story that Revels literally inherited Davis's old seat is a myth — that seat went to a white Union general; Revels filled a different Mississippi vacancy — but the deeper irony, a formerly disenfranchised people sending one of their own to the Senate from the cradle of the Confederacy, was entirely real, and the gallery packed in to watch it.) A few years later **Blanche Kelso Bruce**, also of Mississippi and born enslaved, became the first Black senator to serve a *full* term, from 1875 to 1881. After Bruce's term ended, the country would not send another Black man to the Senate until **Edward Brooke of Massachusetts in 1967** — eighty-six years later. That gap is not an accident of history. It is the measure of what was about to be taken away.` },
      { h: `Impeaching a president`, eyebrow: `What changed` },
      { p: `Before the counter-revolution comes the man who left the door open for it, because the same Andrew Johnson who fought Reconstruction at every turn nearly got himself thrown out of office for it — and the country, for the first time in its history, put a president on trial.` },
      { p: `The feud between Johnson and the Radical Republicans got so poisonous that in 1867 Congress passed a law, the **Tenure of Office Act**, specifically to box him in — it said he couldn't fire certain officials without the Senate's consent. The target was the Secretary of War, **Edwin Stanton**, the Radicals' ally who controlled the army that was enforcing Reconstruction in the South. When Johnson fired Stanton anyway, the House **impeached him on February 24, 1868** — formally charged him with offenses to be tried by the Senate — the first time in American history a president had been impeached. The Senate trial ran for weeks, and it ended on May 16, 1868, in **acquittal by a single vote**: 35 senators voted to convict, 19 to acquit, exactly one short of the two-thirds required to remove him, after seven Republicans crossed party lines. Johnson kept his office but lost his power, finishing his term a broken figure. It would be well over a century before the country impeached another president.` },
      { p: `That single vote mattered more than it looks. Johnson stayed, the federal commitment to protecting the freedpeople stayed weak at the top — and into that weakness, the violence came.` },
      { h: `The counter-revolution`, eyebrow: `What changed` },
      { fig: '/war-img/reckoning-visit-of-the-ku-klux.jpg', cap: `A hooded Klansman levels a rifle into a Black family's home while another holds the door — Frank Bellew's engraving for *Harper's Weekly*, February 1872. This is what "the counter-revolution" actually meant: not an argument but a years-long campaign of assassination, whipping, and arson aimed at making it too deadly for Black men to vote or hold office.`, credit: `Frank Bellew · wood engraving, *Harper's Weekly* (Feb. 24, 1872) · 1872 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `Because almost as soon as Reconstruction began, white Southerners began trying to destroy it — not with arguments but with murder.` },
      { p: `This is the part of the story that gets sanded down the most, so it needs to be said flatly: the overthrow of Reconstruction was a campaign of organized terrorism. The **Ku Klux Klan**, founded in Pulaski, Tennessee, in late 1865, and the wave of successor groups that came after it — the White League, the Red Shirts — waged a years-long war of assassination, whipping, arson, and election-day massacre against Black voters, against the Black men who held office, and against the white Republicans who worked with them. The goal was simple and explicit: make it too deadly for Black men to vote or govern, and take the South back.` },
      { p: `For a while the federal government fought back. Congress passed the **Enforcement Acts** of 1870 and 1871, and President Ulysses S. Grant used them to prosecute the Klan aggressively, breaking the first incarnation of it. But the terror just changed its name and kept going. The White League in Louisiana and the Red Shirts in Mississippi and the Carolinas were as openly violent as the Klan had ever been — they marched in daylight, drilled like a militia, and murdered in the open — but they were political clubs, not a secret society, and that made them far harder to prosecute. And the terror produced atrocities that ought to be as famous as any battle of the war.` },
      { p: `The worst was the **Colfax Massacre**, on **Easter Sunday, April 13, 1873**, in Colfax, Louisiana. After a disputed local election, a white mob of ex-Confederates and Klansmen and White League men overwhelmed a group of Black freedmen and a Black militia defending the parish courthouse — and then murdered them, many *after* they had surrendered. Somewhere **between roughly 60 and 150 Black men were killed**; the exact number will never be known because the bodies were dumped in the Red River or buried in mass graves. Eric Foner calls it the worst single act of racial violence in the entire Reconstruction era.` },
      { p: `And then the courts finished what the mob started. When the federal government tried to prosecute the Colfax killers, the case went up to the Supreme Court, which in ***United States v. Cruikshank*** (1876) threw the convictions out — ruling that the federal Enforcement Acts could reach violence committed by *states*, but not violence committed by private individuals, like a mob. In other words: when a white mob massacred Black citizens, the federal government had no power to punish them; that was a matter for the state, and the state was run by the same people who'd been in the mob. With that ruling the legal shield over Black Southerners was, for all practical purposes, taken away. The terrorists had effectively won a Supreme Court ruling that the federal government couldn't stop them.` },
      { h: `How it ended: a bargain in a back room`, eyebrow: `The unfinished reckoning` },
      { p: `And then, in 1877, the North simply gave up. Not in a battle. In a deal.` },
      { p: `The presidential election of **1876** pitted the Republican **Rutherford B. Hayes** against the Democrat **Samuel Tilden**, and it was a mess. Here you have to know one thing about how America picks a president, because the whole crisis turns on it: the winner isn't whoever gets the most votes nationwide. Each state is assigned a block of "electoral votes," and a candidate has to stack up a majority of *those* to win — so it is entirely possible to lead the national popular vote and still lose the presidency, if the electoral math breaks the other way. That is exactly what was poised to happen. Tilden won the popular vote by about a quarter-million and led the electoral count too — but 20 electoral votes, from Florida, Louisiana, South Carolina, and Oregon, were disputed amid fraud and intimidation in a South where federal troops were still keeping a fragile order. Whoever got those 20 would be president. To break the deadlock, Congress set up a special 15-member **Electoral Commission**, and on a string of party-line votes it awarded **all 20 disputed votes to Hayes**, handing him the presidency by a single electoral vote, 185 to 184 — even as Tilden kept his lead in the popular count.` },
      { p: `It went down quietly because of a bargain — the **Compromise of 1877**. Southern Democrats agreed to accept Hayes as president, and in exchange the Republicans agreed to pull the **last federal troops out of the South**. Hayes withdrew them after taking office in 1877, and that was the end. With the soldiers gone, there was nothing left to protect Black voters or Black officeholders or the Reconstruction governments, and the white Democrats — who called themselves "Redeemers," as if they were rescuing the South — took back control of every Southern state, one after another. The experiment was over. The North had decided that ending it was worth a presidency, and the four million freedpeople were the price.` },
      { h: `The long night`, eyebrow: `The unfinished reckoning` },
      { fig: '/war-img/reckoning-picking-cotton.jpg', cap: `Black men and women picking cotton near Savannah, Georgia, in the decades after the war. Denied the land they'd been promised, most freedpeople ended up farming a white owner's fields for a rigged share of the crop — a system, sharecropping, engineered so the harvest never quite covered the debt and the family could never legally leave. Formally free, designed to function as bondage.`, credit: `Launey & Goebel · albumen print on card mount · c. 1867–1890 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `What came after Reconstruction is the part the war was supposed to prevent, and didn't. It lasted the better part of a century, and it was not abstract. It happened to people with names, on porches and in cotton rows and at the ends of ropes.` },
      { p: `Freed from any federal check, the Southern states moved fast — within a few years of the troops leaving, one legislature after another began rewriting its laws — to methodically strip Black men of the vote they'd just been guaranteed. They couldn't do it by race directly, so they did it through the side door the 15th Amendment had left open: poll taxes a sharecropper could never spare the cash for, literacy tests no one was meant to pass, "understanding clauses" that let a white registrar wave a white man through and fail a Black schoolteacher on the same page, "grandfather clauses" that exempted anyone whose grandfather had voted — which, for the formerly enslaved, meant no one. Race-neutral on paper, devastating in fact. Within a generation, Black political power in the South was nearly erased.` },
      { p: `Underneath the disenfranchisement sat the economy the freedpeople had been left with: **sharecropping**. Denied the land they'd been promised, most ended up farming a white owner's land for a share of the crop — and the share was rigged. The owner kept the books, sold them seed and tools and food on credit at his own prices, and somehow the harvest never quite covered the debt, so the family owed more at the end of the year than the start and couldn't legally leave until it was paid. It was not accidental poverty. It was a system engineered to keep Black families tied to the same plantations their parents had been enslaved on — formally free, designed to function as bondage.` },
      { p: `And then there was the loophole, finally pried all the way open. Remember the 13th Amendment's one exception — slavery abolished *"except as a punishment for crime."* The Southern states turned that clause into a machine. They wrote vagrancy laws that made it a crime for a Black man to be without a job, "pig laws" that turned the theft of a farm animal worth a couple of dollars into years in prison, laws against walking beside a railroad or speaking loudly near a white woman. Then they arrested Black men under those laws by the thousands, convicted them in trials that lasted minutes, and — this is the part — *leased* the prisoners out: to coal mines, to turpentine camps, to railroads and plantations, who paid the state for their labor and gave the men themselves nothing. It was called **convict leasing**, and it was, in the exact and accurate phrase, slavery by another name. The men were chained, starved, worked until many of them died, and replaced — because unlike a slave, a leased convict cost nothing to replace. As many as 200,000 Black Americans were funneled into it, and it ran in some states well into the *1930s and '40s* — three-quarters of a century after a constitutional amendment supposedly ended slavery forever.` },
      { p: `And over the whole of it hung the rope. **Lynching** was not a stray act of mob fury; it was a system, the enforcement arm of the entire racial order. The Equal Justice Initiative has documented roughly **4,000 racial-terror lynchings** of Black Americans across the South between 1877 and 1950 — more than two a week, every week, for seventy years — Black men and women dragged from jails and homes and murdered in public, often before crowds, for trying to vote, for owning land a white man wanted, for an alleged offense never tried in any court, or for nothing at all. The point was terror: to remind every Black Southerner what the cost of stepping out of line could be. And the federal government, the same government that had freed these people, would not stop it. More than 200 anti-lynching bills were introduced in Congress over the following decades; Southern senators filibustered every one to death. The most fearless chronicler of all this was a Black journalist named **Ida B. Wells**, who in the 1890s investigated lynching after lynching, published the names and the lies behind them, and forced a country that wanted to look away to see what it was doing — and was driven out of the South under threat of her own life for the trouble.` },
      { p: `The Supreme Court put the final seal on it. In **Plessy v. Ferguson** (1896), the Court considered a Louisiana law segregating train cars and ruled it perfectly constitutional, inventing the doctrine of **"separate but equal"** — the legal fiction that segregation was fine as long as the separate facilities were equal, which they never, ever were. That doctrine gave **Jim Crow** — the dense web of segregation laws, named after a blackface minstrel character, that walled the races apart in schools and streetcars and restaurants and waiting rooms and water fountains across nearly all of Southern life — the full blessing of the Constitution, and held for **58 years**, until *Brown v. Board of Education* finally overturned it in 1954. Only one justice dissented in *Plessy*, John Marshall Harlan, who wrote that "our Constitution is color-blind" — a lone voice, decades too early, and entirely overruled.` },
      { h: `What the war settled, and what it didn't`, eyebrow: `The unfinished reckoning` },
      { p: `So here, at the end, is the accounting. The cleanest way to say it is this: **the war settled two questions and reopened a third.**` },
      { p: `The first thing it settled, permanently, is that the **Union is one nation and cannot be broken**. Secession was put to the ultimate test — could a state simply leave? — and the answer came back, written in 750,000 graves, as *no*. No state has seriously tried since. The plural country, "these United States," became a singular one, "the United States," and stayed that way. That is settled, and it is enormous.` },
      { p: `The second thing it settled is that **chattel slavery is dead** — the legal owning of human beings, gone from American soil forever, four million people freed and never to be owned again. That is settled too, and it is the thing the war is rightly remembered for.` },
      { p: `But the third question — **what Black freedom would actually mean, whether Black Americans would be equal citizens in fact and not just in law** — that one the war did not settle. It came *closer* than people remember: the Constitution now promised citizenship in the 14th Amendment and the vote in the 15th, real promises. But a promise is only as good as the will to keep it, and in 1877 the country put down that will and walked away. For nearly a century afterward, the answer to whether Black Americans were truly free was given in disenfranchisement, in sharecropping, in convict chains, in segregation, and in lynching. The war ended slavery. The fight over what would replace it was lost — lost on purpose, in a back-room deal — and it would have to be fought all over again in the civil rights movement of the twentieth century, a struggle some historians call the "Second Reconstruction." Don't reach for comfort here. The honest word is not *progress*. It is *deferred*.` },
      { h: `The lie that won`, eyebrow: `The unfinished reckoning` },
      { fig: '/war-img/reckoning-confederate-monument.jpg', cap: `The unveiling of the Confederate Memorial at Arlington, June 4, 1914 — a crowd packed in around the draped bronze nearly half a century after Appomattox. The dates tell on the whole project: the great wave of Confederate monuments went up not in the grief-stricken years right after the war but in the early 1900s, exactly as the South was locking Jim Crow into law. They went up to assert, in bronze and granite, who was still in charge.`, credit: `National Photo Company · photograph (glass negative) · 1914 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `And then comes the final irony, the one this entire arc has been built to confront. The South lost the war on the battlefield — and then won the argument over what the war had *meant*, for the better part of a century.` },
      { p: `The mythology has a name: the **Lost Cause**. In the decades after Appomattox, ex-Confederates and their descendants constructed an elaborate, comforting, and almost entirely false story about the war. In that story, the Confederacy had fought nobly for "**states' rights**," not for slavery. Secession had been constitutional and honorable. The enslaved had been content, even loyal, "faithful" servants who didn't really want freedom. And Reconstruction had been a tragedy — not a democratic experiment murdered in its cradle, but an outrage of corrupt Northern "carpetbaggers" and unfit Black officeholders inflicted on a noble, prostrate South.` },
      { p: `The ideological core of all that is a lie, and the people who made the war said so themselves. The South's own secession declarations named the protection of slavery as the cause, in plain words, and the Confederacy's vice president had stood up before the war and announced that slavery and white supremacy were the literal cornerstone of the new nation. The "states' rights" the Confederacy actually fought for was the right to own people. The documents were right there. (None of this means the men in the ranks lacked courage — many of them fought and died bravely; the lie isn't about their valor, it's about the cause they were spent on.) The myth simply painted over the cause.` },
      { p: `What made the Lost Cause so powerful wasn't that anyone believed it spontaneously — it was *organized*. The chief engine was the **United Daughters of the Confederacy**, founded in 1894, which spent decades raising monuments, lobbying legislatures, running essay contests for schoolchildren, and — most effectively — working to control what the history textbooks said, shaping how generations of American children, North and South, learned about the war. And the monuments themselves tell on the whole project if you just look at the dates. The great wave of Confederate monument-building came not in the grief-stricken years right after the war, but in the *early 1900s* — exactly as the Southern states were locking Jim Crow and disenfranchisement into law — and then again during the civil rights backlash of the 1950s and '60s. Those statues were never really about mourning the dead. They went up to assert, in bronze and granite, who was still in charge.` },
      { p: `That is the final irony, and it is the reason this whole arc exists. The side that lost the war wrote the history of it. For a hundred years, in much of the country, the Lost Cause *was* the history of the Civil War — taught in schools, carved in stone, accepted as fact. The war's actual truth — that it was fought over slavery, that it ended slavery, that the people freed by it were betrayed within a decade — was buried almost before the graves were dug. And digging it back out is itself part of the reckoning the country still owes.` },
      { h: `The debt still owed`, eyebrow: `The unfinished reckoning` },
      { fig: '/war-img/reckoning-frederick-douglass.jpg', cap: `Frederick Douglass, around 1870 — born enslaved, the great voice of his people, and the man who never once mistook charity for justice. Before the war was even won he had stood up in Boston and told the country exactly what the freedpeople needed from it: "not benevolence, not pity, not sympathy, but simply justice." That was the whole question of the reckoning, and in 1877 the country answered it by looking away.`, credit: `unattributed · albumen print · 1870 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `Lincoln saw the whole weight of it before the war was even over. In his Second Inaugural Address, on March 4, 1865, with the end finally in sight, he refused to let anyone pretend the bloodshed was random or cheap. The war, he said, was God's judgment on the whole country for the sin of slavery, and the bill might run to the last drop:` },
      { p: `"Yet, if God wills that it continue until all the wealth piled by the bondsman's two hundred and fifty years of unrequited toil shall be sunk, and until every drop of blood drawn with the lash shall be paid by another drawn with the sword, as was said three thousand years ago, so still it must be said 'the judgments of the Lord are true and righteous altogether.'"`, q: true },
      { p: `And then, in the same breath, he reached for grace — the most famous lines he ever spoke:` },
      { p: `"With malice toward none, with charity for all, with firmness in the right as God gives us to see the right, let us strive on to finish the work we are in, to bind up the nation's wounds, to care for him who shall have borne the battle and for his widow and his orphan, to do all which may achieve and cherish a just and lasting peace among ourselves and with all nations."`, q: true },
      { p: `Six weeks later he was dead, and the work of binding up the nation's wounds fell to smaller men who, in the end, chose not to finish it.` },
      { p: `Even the man who *won* the war refused to gloat over it, or to pretend the cause he'd beaten had been an honorable one. Ulysses S. Grant, writing years later in his memoirs about the moment of Lee's surrender, put down what he had actually felt — and it was not triumph:` },
      { p: `"I felt like anything rather than rejoicing at the downfall of a foe who had fought so long and valiantly, and had suffered so much for a cause, though that cause was, I believe, one of the worst for which a people ever fought, and one for which there was the least excuse."`, q: true },
      { p: `But the truest last word belongs to the man who had the most to win and the most to lose, and who never once mistook charity for justice. Frederick Douglass — born enslaved, the great voice of his people — had stood up in Boston back in January 1865, before the war was even won, and told the country exactly what the freedpeople needed from it, and exactly what they didn't:` },
      { p: `"What I ask for the Negro is not benevolence, not pity, not sympathy, but simply justice."`, q: true },
      { p: `That was the whole question of the reckoning, in one sentence. Not charity. Justice. And it is the question the country answered, in 1877, by looking away.` },
    ],
    meanwhile: {
      region: `the firing line`,
      title: `The battles themselves`,
      body: `These were the threads off the firing line — the causes, the society, the technology, the aftermath. The battles that ran alongside them, from Bull Run to Appomattox, are their own four theatres, waiting whenever you are.`,
    },
  },
}

export default function ReckoningThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="reckoning"
      battleName="The Reckoning"
      theatreId="offfield"
      battleId="th-reckoning"
      theatreHref="/war-civil-war/off-the-battlefield"
      accent={ACCENTS.green}
      heroImage="/war-img/reckoning-hero-richmond-ruins.jpg"
      heroPalette={["#2a2724","#1a1816","#080808"]}
      heroCredit={`unattributed (LOC Civil War collection) · albumen photograph (glass negative) · 1865 · Library of Congress, Prints & Photographs Division · public domain`}
      heroFocus="center 45%"
      heroScale={1.05}
      endHref="/war-civil-war/off-the-battlefield"
      endKicker={`A reckoning deferred, not resolved`}
      endLabel={`Back to Off the Battlefield`}
    />
  )
}
