'use client'

// The Battle of the Crater — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise → integrate. Data only; rendered by the shared <BattleSectionReader>.
//
// VOICE PASS 2026-06-01 (dossier-retrofit): brought to the locked house-voice
// rules — no reader-facing em-dashes; marquee names (Lee, Grant) carry no
// side-tag while every other side-affiliated person is tagged once on first
// mention per section; full rank spelled out on first appearance per section;
// meta-narrator / editorial asides removed (tell it plainly); bold removed;
// cross-refs are pills (USCT, Emancipation). Facts web-verified.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const CRATER_NARR: Record<string, Narr> = {
  'the-mine': {
    eyebrow: 'The Crater · Petersburg',
    title: 'A Tunnel Under the War',
    blocks: [
      { h: 'How a stalled siege drove men underground', eyebrow: 'Petersburg, summer 1864' },
      { p: 'By the summer of 1864 the war in Virginia had stopped moving. Lieutenant General Ulysses S. Grant, general-in-chief of the Union armies, had spent the spring grinding south toward Richmond, the Confederate capital. His army and General Robert E. Lee’s Army of Northern Virginia had finally locked together at Petersburg, a rail hub about 25 miles (40 km) south of Richmond. Petersburg fed the capital: take its railroads and Richmond starves. So the armies dug in around it, and what had been a war of marches became a siege, a long investment of a fortified place, both sides burrowing into the earth. In spots the two sets of trenches sat only about 100 yards apart, a strip of churned no-man’s-land between them. Frontal assaults had already failed bloodily that June, and by the end of the month the stalemate had hardened with no obvious way through it.' },
      { p: 'The way under it came up from the ranks. Facing the Union line at one point was a Confederate strongpoint, a salient (an angle in the works that juts out toward the enemy), held by Confederate guns and infantry. Men of the 48th Pennsylvania Infantry (North), a regiment thick with former coal miners from Schuylkill County, looked across that gap and thought what coal miners think: they could dig under it. Their commander, Lieutenant Colonel Henry Pleasants (North), had been a civil and mining engineer in civilian life. He championed the idea, designed it, and drove it.' },
      { p: 'The plan was simple to say and brutal to execute. A mine, in siege warfare, is a tunnel dug under an enemy position and packed with explosives; the gallery is the tunnel itself. Pleasants’s men would dig a gallery west from behind their own line, run it under no-man’s-land, and stop it directly beneath the Confederate salient, more than 50 feet below the enemy battery. There they would branch left and right and pack the dead-end chambers with gunpowder. Blow the salient skyward, and Lee’s line opens like a torn seam.' },
      { fig: '/war-img/crater-overview.png', cap: 'The siege lines at Petersburg: the Union front on the east, the 48th Pennsylvania’s gallery running west under no-man’s-land to Elliott’s Salient, with Cemetery Hill and the Jerusalem Plank Road behind.', credit: 'Map: Stuff Happened' },
      { p: 'Between June 25 and July 17, 1864, the 48th Pennsylvania hand-dug a main gallery about 511 feet long, with a perpendicular “T” gallery of roughly 75 feet running left and right at the far end, under the Confederate works. They did it with improvised tools and one clever trick. A tunnel that long needs fresh air, but a ventilation shaft breaking the surface would have told the Confederates exactly what was happening. So Pleasants rigged a canvas partition and a wooden duct, and kept a fire burning at the tunnel mouth. The fire drew stale air out, which pulled fresh air in along the duct, a furnace-powered bellows with nothing showing above ground. Then they packed the chambers with 320 kegs of black powder, about 8,000 pounds (four tons), and tamped it tight so the blast would punch up, not back out the tunnel. The powder went in around July 27 and 28, and the mine sat loaded and waiting.' },
    ],
    meanwhile: { region: 'Elliott’s Salient', title: 'What was sitting on top of it', body: 'Directly above the powder, in the Confederate salient, slept the 18th and 22nd South Carolina (South), of Brigadier General Stephen Elliott Jr.’s (South) brigade, sharing the ground with a battery of guns. The place is remembered as “Elliott’s Salient.” The Confederates were not blind to the danger. They suspected the Federals were digging and sank their own listening shafts to find the tunnel, but Pleasants had run his gallery deeper than they probed, and they never struck it. The men holding the salient knew a mine might be coming and could not find it, and slept that night a few feet of dirt above four tons of powder.' },
  },

  'pulled-from-the-lead': {
    eyebrow: 'The Crater · The night before',
    title: 'The Division Trained, Then Taken Out',
    blocks: [
      { h: 'The trained division, pulled the day before', eyebrow: 'The night before' },
      { p: 'The lead in the assault was decided by drawing straws. The one division that had spent two weeks rehearsing this exact attack was pulled out of it the day before, and the lead going in first was handed by lot, a literal straw, to the least prepared unit on the field. Who was pulled, and why, is the thread the rest of the battle runs along.' },
      { p: 'The Union army at Petersburg now included United States Colored Troops, the USCT: regiments of Black soldiers, many of them formerly enslaved, fighting in Union blue against the slave republic that had once owned them. The Confederacy had been built to preserve slavery. Eleven states broke away rather than accept any limit on the enslavement of Black people, and raised their armies to defend it. So when Black men, many of them lately somebody’s legal property, stood in the Union line at Petersburg, the war’s cause was in the ranks, carrying a rifle.' },
      { pill: '/war-civil-war/off-the-battlefield/usct', plabel: 'The USCT: Black soldiers in the Union army' },
      { p: 'It was that division, the trained one, that Major General Ambrose E. Burnside (North), commander of the Union IX Corps, meant to send in first. A word on how those armies were built, because the next two sections lean on it: a Civil War army nested in tiers. A corps was the largest field formation (tens of thousands of men), a corps held two or three divisions (several thousand men each), a division held brigades, and a brigade held the individual regiments. Burnside’s IX Corps, the corps whose sector this was and whose plan the mine assault was, held four such divisions. For about two weeks, two miles behind the line and out of Confederate sight, one of them, Brigadier General Edward Ferrero’s (North) 4th Division of USCT, roughly 4,300 men, drilled the assault specifically. The plan they learned was the right one: when the salient blew, one brigade would peel left and one right to widen the breach sideways, while the rest rushed around the hole, not into it, and drove for the high ground behind, called Cemetery Hill, and the Jerusalem Plank Road just past it, the road into Petersburg. That high ground was the key. A force on Cemetery Hill would be behind Lee’s whole line and astride the road into the city, and taking Petersburg starves Richmond. They were the one unit on the field prepared for this exact attack.' },
      { p: 'The day before the assault, they were pulled out of the lead.' },
      { p: 'Major General George G. Meade (North), who commanded the Army of the Potomac and stood between Grant above him and Burnside’s corps below, ordered Burnside not to lead with the Black division. Burnside protested. Grant, over them both, backed Meade. The reason was not that the USCT were untrained; they were the only trained ones. The reason was optics. The fear was that if the Black soldiers led the charge and the assault failed and they were slaughtered, the army would be accused of having thrown Black men away. Grant later explained the calculation to Congress in his own words: if the Black troops led and were killed, it would then be said that the army had been shoving these people ahead to get killed because it did not care anything about them.' },
      { p: 'The lives of the Black soldiers were weighed as a problem of political perception, a calculation no white division on that field had to survive, made by the same army that had put them in uniform. They were taken out of the lead not because the plan was bad but because their deaths would look bad. So the lead went instead to the three white divisions, who drew lots, that straw, for it. The straw fell to Brigadier General James H. Ledlie’s (North) 1st Division: untrained for this attack, and led by a man already known to have shirked under fire earlier that June. The unit that knew the plan would stand in reserve. The unit that drew it by chance would go in cold.' },
    ],
    meanwhile: { region: 'the bombproof', title: 'The man chosen by the straw', body: 'Ledlie (North) would not lead his division when the moment came. He would not even be near it. The general who drew the right to go in first spent the battle well behind the lines, in a bombproof (a covered, shellproof dugout) and, by multiple accounts, drinking. So did Ferrero (North), the commander of the division that had been pulled. The two generals most responsible for the men in front sat out the disaster together, sharing rum, while those men died.' },
  },

  'the-pit': {
    eyebrow: 'The Crater · Dawn, July 30',
    title: 'The Hole the Assault Drowned In',
    blocks: [
      { h: 'A perfect breach, thrown away by the hour', eyebrow: 'Dawn, July 30' },
      { p: 'The fuse failed. At the appointed hour before dawn, the fuse was lit and the army waited for the explosion that did not come. The fire had died somewhere in the tunnel. Two volunteers, Lieutenant Jacob Douty (North) and Sergeant Harry Reese (North), crawled into the loaded mine, found the dead spot, relit it by hand, then crawled back out. Around 4:44 a.m. the four tons of powder went off.' },
      { p: 'The blast tore the salient out of the earth. It threw dirt, guns, and men hundreds of feet into the air and killed roughly 300 Confederates of the 18th and 22nd South Carolina (South) where they slept. When the dirt rained back down it left a pit, the Crater, about 170 feet long, 100 to 120 feet wide, and at least 30 feet deep. Lee’s line was simply gone for that stretch. For the first critical minutes the surviving Confederates on either side of the hole were too stunned to do much of anything. For about fifteen minutes there was almost no fire, and the gap stood wide open. This was the moment the whole scheme had been built for: a clear path through the breach to Cemetery Hill behind it, the high ground that, once taken, would put the Union army astride the road into Petersburg and behind Lee’s entire line.' },
      { fig: '/war-img/crater-the-assault.png', cap: 'The assault: Ledlie’s division pours into the crater instead of around it, the following waves pile in behind, and Mahone’s Confederate brigades seal the gap and ring the pit.', credit: 'Map: Stuff Happened' },
      { p: 'The Union threw it away. Ledlie’s (North) untrained division hesitated about ten minutes before going forward at all. Then, because no one had prepared the footbridges and ramps an assault needs to get a mass of men quickly up and over their own high-walled fortifications, they had to climb down into and back out of their own trenches to start the advance, bleeding away time and order in front of an open door. Then came the decisive blunder. Instead of going around the crater, as the sidelined USCT had been trained to do, Ledlie’s men poured into it, treating the pit as cover. It was a trap. A 30-foot hole with steep, crumbling walls is easy to fall into and nearly impossible to climb out of or fight from. The men packed the bottom, milling, while the following divisions piled in behind them and made it worse. The general who might have grabbed the attack and shoved it forward was a mile back in his bombproof.' },
      { p: 'Within about an hour the Confederates had their feet back under them. Brigadier General William Mahone (South) brought up infantry brigades, sealed the gap, and ringed the crater. His men, and those of Major General Bushrod Johnson (South), poured rifle fire down into the packed mass, and Confederate artillery dropped shells straight down into the pit. Contemporaries called it a turkey shoot. Mahone’s men got so close they hurled bayoneted muskets like spears down into the crowd below. What had been a breakthrough at 4:44 was, by mid-morning, a slaughter pen with the Union army at the bottom of it.' },
    ],
    meanwhile: { region: 'Grant’s headquarters', title: 'Grant’s own verdict', body: 'Writing afterward to Major General Henry W. Halleck (North), his chief of staff, Grant called it the saddest affair he had witnessed in the war, and added that such an opportunity for carrying fortifications he had never seen, and did not expect ever to have again. The mine had worked perfectly. Everything built on top of it had failed.' },
  },

  'the-massacre': {
    eyebrow: 'The Crater · The crater rim',
    title: 'Murdered After Surrender',
    blocks: [
      { h: 'Murdered after surrender', eyebrow: 'The crater rim' },
      { p: 'It was about then, late and into the collapsing attack, that the Black division was finally fed in, exactly the disaster they had trained to avoid. The USCT fought hard and took the heaviest losses of any Union division on the field, somewhere around 1,300 to 1,380 men, the worst-mauled command of the day. But the casualty count alone does not carry what happened to them. When the line broke, surrendering and wounded Black soldiers were murdered.' },
      { p: 'At the crater rim, Confederates were heard shouting a command that sorted the captured by race: take the white man prisoner, and kill the Black one. Black men who tried to surrender were shot or bayoneted on the spot, or marched to the rear and executed after capture, while white prisoners standing beside them were taken alive. Surrender was offered to white soldiers and refused to Black ones, for no reason but that they were Black. These were men, many of them formerly enslaved, being killed for trying to surrender to the army that had claimed to own them.' },
      { p: 'This is not a Northern accusation. It is confirmed by the Confederates who were there. The Confederate artillery general Edward Porter Alexander (South) admitted afterward that some of the Black prisoners were shot by others, and that there was a great deal of unnecessary killing of them. A Confederate private, William Cowan McClellan of the 9th Alabama (South), described captured Black soldiers as the worst-looking set you ever saw, bayoneted and clubbed with musket butts, and wrote that all of them would have been killed but for Mahone, with one man in his own brigade having killed several. And a Confederate colonel, William Pegram (South), wrote home that the killings had a splendid effect on his men. A general admitting it, a private describing it, a colonel approving of it: the murders were not the work of a few rogue soldiers. They were widespread, witnessed, and on the Confederate side, in at least one officer’s telling, celebrated.' },
      { p: 'Mahone (South) himself appears to have tried to stop it. Multiple accounts have him pleading with his men to spare prisoners, and the private McClellan credited him with saving lives. That does not soften the verdict. The killing was general enough that a general had to beg to slow it, and even then at least one prisoner was reportedly murdered afterward anyway, while Pegram called the whole business a good thing.' },
      { p: 'The statistics leave a fingerprint of it. Across the war, Union soldiers tended to be wounded roughly five times for every one killed. In Ferrero’s (North) Black division at the Crater, the ratio was closer to two wounded for every one killed: far too many dead relative to wounded, the pattern you would expect when men are killed outright rather than allowed to fall wounded or to surrender. The eyewitnesses prove the massacre. The numbers agree with them.' },
    ],
    meanwhile: { region: 'the pit', title: 'The whole war in one pit', body: 'Black men who had been held as property fought at the Crater for their own freedom. They were trained to lead the assault, then pulled because their deaths were judged politically inconvenient, then spent into the disaster anyway, then murdered after surrender for the color of their skin. The Confederacy was built to keep them enslaved, and at the Crater the same racial logic that built it reached down into the hole and executed them for raising their hands. The war was fought over slavery, and this battlefield is one of its plainest proofs.' },
  },

  'what-it-meant': {
    eyebrow: 'The Crater · The reckoning',
    title: 'A Breakthrough Thrown Into a Hole',
    blocks: [
      { h: 'What was lost, and who answered for it', eyebrow: 'The reckoning' },
      { p: 'The Crater was a Confederate victory. Lee held the line. The Union mine had blown a clean breach in his works at dawn, nearly undefended for the crucial first quarter-hour, and the Union army turned that opening into one of its own worst disasters of the war.' },
      { p: 'The cost was lopsided. The Union lost about 3,800 men: 504 killed, 1,881 wounded, and 1,413 captured or missing. The Confederates lost about 1,500: 361 killed, 727 wounded, 403 captured or missing. The Union lost roughly two and a half times what the Confederates did, the price of an assault that piled into a death-pit instead of driving through it. Of the Union loss, the single heaviest share fell on the Black division that had been the right unit for the job all along.' },
      { p: 'The breakthrough was real and it was wasted. Cemetery Hill and the road into Petersburg behind it had been there for the taking in the first fifteen minutes, and with them the chance to get behind Lee’s line and into the city that fed Richmond. Instead the siege ground on for eight more months, and Petersburg did not fall until April 1865. The Crater moved nothing on the map.' },
      { p: 'A court of inquiry followed, and it spread the blame across the men who had failed the soldiers. It censured Burnside (North), Ledlie (North), Ferrero (North), and others. Burnside was relieved of his corps command within weeks, succeeded by Major General John G. Parke (North), and never held a field command again. Ledlie, drunk in a bombproof while his division died in the pit, was finished and resigned his commission early in 1865. Later, a Joint Committee of Congress shifted blame onto Meade (North) for reversing the plan and pulling the trained division from the lead, and partly let Burnside off.' },
      { p: 'One man came out of it praised. Lieutenant Colonel Henry Pleasants (North), the engineer of the mine, had no part in the failed assault. He was brevetted brigadier general, cited explicitly for the tunnel his coal miners had dug. The dig was a triumph of the ranks, ordinary men solving an impossible engineering problem with improvised tools and a furnace for a fan. The assault was a failure of the generals above them, and a moral catastrophe besides: the one trained division pulled from the lead to manage how its deaths would look, then spent anyway, then murdered after surrender. The mine remains one of the most remarkable feats of the war. What was built on top of it remains one of its worst.' },
    ],
    meanwhile: { region: 'memory', title: 'Why it still matters', body: 'What is left, once the generalship and the engineering are set aside, is the documented, cross-confirmed massacre of Black soldiers trying to surrender, a defining episode in the history of the United States Colored Troops. Men who had been held as property fought back, in uniform, in sight of the men who had owned them, and were killed for trying to give up. That, and not the hole in the ground, is what the Crater is remembered for.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={CRATER_NARR} id={id} slug="crater" battleName="The Crater" theatreId="east" theatreHref="/war-civil-war/eastern" battleId="e-crater" accent="#7c3aed" />
}
