'use client'

// THEME section — The Road to War (Off the Battlefield, kind=theme). Built through
// the war content pipeline (fact pack → author(Opus) → five gates [fact-check +
// storytelling + comprehensiveness + clarity + Lost Cause/framing] → revise → images).
// Source + gate records: audits/war-pipeline/road-to-war-*.md. Green accent; no stat
// block, no map. 'use client' is REQUIRED (reads ACCENTS from a client module).
// GENERATED from road-to-war-final.md by scripts/_build-war-themes.mjs — do not hand-edit
// the prose here; edit the final.md and rebuild.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: `How the peace came apart, deal by deal`,
    title: `The Half-Continent That Broke the Peace`,
    blocks: [
      { p: `There is a tidy way to tell the road to the Civil War, and it goes like this: the country had a long-running argument about slavery, wise old statesmen kept patching it up with compromises, and then one day the patches stopped holding and the shooting started. That version is not wrong, exactly. But it misses the engine underneath it: the thing that made every patch a temporary one. The argument was never really about whether slavery was right or wrong, not in the halls of Congress (the two-chamber lawmaking body of the U.S. government). It was about *territory*: whether slavery would be allowed to spread into the enormous, half-empty West the United States kept acquiring. And the moment the country won a war and seized half of a continent, that question stopped being theoretical and became the only question that mattered.` },
      { p: `The story of the people slavery claimed to own, the abolitionists Black and white who refused to let the nation look away, is told in "The Freedom Struggle." What follows here is the machinery: the deals, the votes, the parties (a political party being a coalition of people organized around shared beliefs who run candidates for office together), the territories, and the slow, grinding discovery that the American political system, for all its cleverness, had been built with a flaw it could not legislate around. Each of its great compromises bought time. None of them bought peace. And the men who made them (Henry Clay of Kentucky, the Senate's master deal-maker; Daniel Webster of Massachusetts, the North's great orator; John C. Calhoun of South Carolina, the South's foremost theorist; Stephen Douglas of Illinois, the brilliant young tactician who would outlive the other three) would mostly be dead before they could see how completely their handiwork failed.` },
      { p: `The flaw was simple to state and impossible to fix. Slavery was a question on which the country was split not by *party* but by *region*. And a republic can survive parties disagreeing; that is what parties are for. It cannot easily survive its two halves wanting opposite things and each half being strong enough to block the other. Watch, over the next fifteen years, for the moment the votes stop falling along party lines and start falling along the line between North and South. That moment is the alarm bell. It rings more than once, each time louder, and everything after it is the country failing to wake up in time.` },
      { fig: '/war-img/road-to-war-fig1-missouri-compromise-map.jpg', cap: `The deal that held for thirty-four years, drawn on a ruler and a map. The 36°30′ line split the West into two futures, until someone tore it up.`, credit: `McConnell Map Co. · 1919 · public domain` },
      { h: `The Old Peace and the New Problem`, eyebrow: `Pressure` },
      { p: `To understand why the new territory was such a catastrophe, you have to understand the peace it broke: a deal struck back in 1820, when most of the men in this story were young or unborn.` },
      { p: `In 1819 the territory of Missouri applied to join the Union as a slave state (a state where slavery was legal), and it set off a panic in Washington. The reason was arithmetic. The United States Senate gives every state two senators regardless of size, which means the balance of power in the Senate depends entirely on how many states fall on each side of a question. In 1819 the country had exactly eleven free states (where slavery was illegal) and eleven slave states: a perfect tie, twenty-two senators a side. Admit Missouri as a slave state and the South would have a permanent edge in the chamber that had to approve every law, every treaty, every appointment. The free North would not stand for it.` },
      { p: `The fix was a bargain that came to be called the **Missouri Compromise**, passed by Congress in March 1820 and signed by President James Monroe. It had three moving parts, and it was genuinely clever. Missouri came in as a slave state. At the same time **Maine** (until then the northern chunk of Massachusetts) was carved off and admitted as a free state, so the Senate tie held at twelve and twelve. And then came the part that mattered most for the future: a senator from Illinois named Jesse Thomas proposed drawing a line straight across the rest of the country. The line ran along the parallel of latitude **36°30′ north**, roughly along Missouri's southern border. Everything in the remaining western territory *north* of that line would be forever free soil. Everything *south* of it would be open to slavery. The whole vexed question of slavery in the West had been answered with a ruler and a map.` },
      { p: `It held for thirty-four years. A generation of Americans grew up regarding the 36°30′ line as something close to scripture: a permanent, settled, almost sacred boundary that had taken the most dangerous question in the republic and filed it away. That is precisely why tearing it up, when the day came, would feel to the North like a betrayal rather than a policy.` },
      { p: `But even at the moment of its making, sharp observers were uneasy. The aging Thomas Jefferson, writing in 1820, said the controversy had come to him "like a fire bell in the night," and had "awakened and filled me with terror." What worried Jefferson was not the deal itself but what it revealed. The country could now be divided, cleanly, on a map, into two hostile halves. A line drawn to keep the peace was also a line that told everyone exactly which side they were on.` },
      { p: `For three decades, nobody had to test it, because there was no new land to fight over.` },
      { h: `A Continent Falls Into the Argument`, eyebrow: `Pressure` },
      { p: `Then the United States went to war with Mexico, and won. The **Mexican–American War** ran from 1846 to 1848, and it was a war the United States had started (American troops marched into disputed borderland and Mexico fought back) to acquire territory, much of it land that might become slave country. A great many Northerners suspected exactly that, and opposed the war as a Southern scheme to grab new ground for slavery. Hold onto that suspicion, because it is the whole reason the next thing happened the way it did.` },
      { p: `When the war ended the map of North America had been redrawn in America's favor on a scale that is hard to overstate. By the **Treaty of Guadalupe Hidalgo** (signed February 2, 1848, in a town outside Mexico City), Mexico ceded to the United States roughly **525,000 square miles** of land. The United States woke up one morning owning about a third more continent than it had the night before. Out of this single transfer would eventually come California, Nevada, Utah, and most of the modern Southwest. The United States paid Mexico $15 million and assumed several million more in debts, which gave the whole thing the thin courtesy of a purchase rather than a seizure. The Senate ratified the treaty 38 to 14 in March 1848.` },
      { p: `And in an instant the question that had been sleeping since 1820 sat up. Half a continent of new territory, none of it yet organized, all of it now demanding the same answer: slave or free?` },
      { p: `Here is the thing to notice, though, because it is the political earthquake of the whole era, and it had already happened, two years *before* the war even ended.` },
      { p: `In August 1846, a few months into the fighting, a freshman congressman from Pennsylvania named **David Wilmot** (a Democrat, the party of Andrew Jackson, then the dominant party in the country) attached a short rider (an add-on provision tacked onto an unrelated bill) to a routine war-spending measure. It proposed that in any territory the United States might take from Mexico, "neither slavery nor involuntary servitude shall ever exist." This was the **Wilmot Proviso**, and on its face it was unremarkable: an antislavery Northerner proposing to keep slavery out of land the country didn't even own yet. What made it a thunderclap was *how the vote broke*.` },
      { p: `The Proviso passed the House of Representatives, 83 to 64. But it did not pass along the usual lines, with Democrats on one side and the rival Whig Party (the main opposition party of the era, more friendly to business and federal projects) on the other. It passed with Northern Democrats *and* Northern Whigs voting yes, and Southern Democrats *and* Southern Whigs voting no. For the first time since the Missouri crisis a quarter-century earlier, a major vote in Congress had broken cleanly along the line between North and South, with party loyalty simply evaporating in the face of slavery. Then it went to the Senate, where the South, holding its hard-won parity, killed it. They tried again in 1847; the House passed it again, 115 to 106, and the Senate killed it again.` },
      { p: `The Wilmot Proviso never became law. It almost didn't matter that it didn't. What it proved was the dangerous thing. It proved that on the question of slavery in the territories, an American politician's *region* now predicted his vote better than his *party* did. A country whose politics divide by region instead of by party is a country with a fault line running straight through it. The Proviso was the first ring of the alarm bell. The peace of 1820 was about to be tested by a problem it was never built to hold.` },
      { h: `The Last Great Bargain`, eyebrow: `Turning point` },
      { fig: '/war-img/road-to-war-fig2-henry-clay-brady.jpg', cap: `Henry Clay, photographed by Mathew Brady a month before he rose to propose the Compromise of 1850, his last and greatest gamble. Seventy-two years old, already "the Great Compromiser," and running out of time.`, credit: `Mathew Brady · 1849 · Beinecke Rare Book & Manuscript Library, Yale University · public domain` },
      { p: `What the crisis needed was a deal, and what it got was the last and greatest performance of the men who had spent their careers making them. The debate over what came to be called the **Compromise of 1850** was the final act of a generation of giants, and you can read the whole tragedy of the era in the fact that all three of its leading men were dead or dying as they spoke.` },
      { p: `The immediate trigger was California. By 1849 the Gold Rush (set off when gold was discovered in California the year before, drawing a flood of fortune-hunters west) had jammed something like a hundred thousand settlers into it, and it wanted in, as a free state. That alone would shatter the Senate balance, which by then stood at a knife's-edge fifteen free states to fifteen slave. Admit California free and the South's parity, the thing it had guarded since 1820, was gone. Meanwhile Texas was claiming a vast stretch of land to its west, the new Southwest needed governments, and the slave trade was still being run, in open auctions, in the shadow of the Capitol. Every one of these was a fuse.` },
      { p: `Into this stepped **Henry Clay** of Kentucky, a Whig, seventy-two years old and already known as "the Great Compromiser" for having brokered the great deals of 1820 and 1833 (the latter a bargain that had defused an earlier crisis over tariffs). In January 1850 he rose and proposed to settle *everything at once*: an eight-part package, an "omnibus" bill, that gave each side something and asked each side to swallow something. California free; the Southwest organized without a slavery ban; Texas paid off to drop its land claims; a tougher law for catching escaped slaves to satisfy the South; the slave *trade* (though not slavery itself) banished from the nation's capital to satisfy the North. It was the work of a master, and it was, at first, a complete failure. Bundled together, the package gave every faction enough to hate that no majority could be built for the whole thing. On July 31, 1850, Clay's grand omnibus collapsed on the Senate floor.` },
      { p: `Before it failed, though, the Senate heard from the dying.` },
      { fig: '/war-img/road-to-war-fig3-senate-1850-rothermel.jpg', cap: `The last act of a generation: Henry Clay on the Senate floor, 1850, with John C. Calhoun and Daniel Webster in the chamber. Three men who between them had run the Senate for thirty years: one dying, one about to become a traitor to his region, and one who thought a railroad could fix everything.`, credit: `Peter F. Rothermel (artist) · Robert Whitechurch (engraver) · c. 1855 · public domain` },
      { p: `**John C. Calhoun** of South Carolina (the South's foremost theorist, a former vice president, the man who had spent thirty years building the intellectual case for slavery and states' rights) was so wasted by tuberculosis that he could not deliver his own speech. So on March 4, 1850, he sat in the chamber, gaunt and wrapped against the cold, while Senator James Mason of Virginia, a Democrat and a Calhoun ally, read his words aloud for him. Picture the stagecraft of it: a dying man's ultimatum to the nation, delivered by another man's voice, in the very room where every deal of the past thirty years had been struck, to an audience that understood he would not live to hear the country's answer. The words were uncompromising. The North, Calhoun warned, must stop agitating against slavery, must return every escaped slave, must restore the South's lost balance in the government, must guarantee the South's rights by constitutional amendment. Otherwise the Union would end in "disunion, anarchy, and civil war." He refused to support Clay's compromise; he thought it merely delayed the reckoning. He died less than a month later, on March 31, 1850, his last reported words said to have been a lament for "the South, the poor South."` },
      { p: `Three days after Calhoun's speech, on March 7, 1850, **Daniel Webster** of Massachusetts rose to answer him. Webster was the North's great voice, a Whig, the most celebrated orator in the country, and his Northern admirers packed the galleries expecting him to thunder against the slaveholders as he always had. Instead he said this:` },
      { p: `I wish to speak to-day, not as a Massachusetts man, nor as a Northern man, but as an American, and a member of the Senate of the United States. … I speak to-day for the preservation of the Union. Hear me for my cause.`, q: true },
      { p: `And then he urged his fellow Northerners to *accept* Clay's compromise, including its harsh new fugitive-slave law (a federal law that would force Northern states to help slave-catchers seize and return escaped enslaved people to the South), for the sake of holding the country together. He even argued, with a kind of geographical optimism, that slavery would never take root in the arid Southwest anyway, so a legal ban there was a fight not worth having.` },
      { p: `The North never forgave him. To antislavery Northerners, Webster's "Seventh of March" speech was a betrayal: the great champion selling out to the slaveholders for the sake of peace. The poet John Greenleaf Whittier wrote "Ichabod," a poem mourning him as a fallen man; others called him Lucifer cast down from heaven. The Massachusetts antislavery forces took their revenge by helping send the fierce abolitionist Charles Sumner (an abolitionist being someone who wanted slavery ended entirely, not merely kept from spreading) to the Senate in Webster's place. (Remember Sumner; in a few years he would bleed on the Senate floor for the cause Webster had just abandoned.) Webster had tried to save the Union and had instead made himself the most hated man in his own region. He had asked the North to swallow a law that would make free citizens into slave-catchers, and a great many of them concluded (not unreasonably) that this was a price the peace was not worth paying. It was a preview of the whole era's cruelty: in this fight, the middle was the most dangerous place to stand, in part because the only deals available there required the North to become complicit in slavery itself.` },
      { p: `Clay's all-at-once approach was dead. What saved the compromise was a younger man with a colder, smarter strategy. **Stephen A. Douglas** of Illinois (a Northern Democrat, short, pugnacious, brilliant, nicknamed "the Little Giant") took Clay's failed omnibus, broke it into **five separate bills**, and ran each one through Congress on its own. It was a tactical masterstroke. Instead of asking one majority to swallow the whole package, he assembled a *different* majority for each piece: Northerners and a few Southerners to pass the free-state and antislavery bits, Southerners and a few Northerners to pass the proslavery bits. No single coalition had to love all of it. It helped that President Zachary Taylor, who had opposed the deal, died suddenly in July 1850, and his successor Millard Fillmore threw the White House's weight behind it. By September 1850, all five bills had passed.` },
      { p: `So here is what the **Compromise of 1850** actually traded. California entered free, and the old Senate balance (sixteen free states now to fifteen slave) was broken for good. The territories of Utah and New Mexico were organized under a new principle that would soon become the most dangerous idea in American politics: **popular sovereignty**, meaning the settlers of a territory would vote for themselves on whether to allow slavery, rather than Congress deciding for them. Texas surrendered its disputed land claims in exchange for the federal government assuming roughly $10 million of its debts. The slave *trade* (the public buying and selling of human beings) was banned in Washington, D.C., though slavery itself stayed legal there. And, the South's prize, a savage new **Fugitive Slave Act** was passed, putting federal power behind the recapture of escaped slaves and compelling Northern citizens to assist.` },
      { p: `The country exhaled. Politicians on both sides called it a "final settlement," and most Americans wanted desperately to believe them. But notice what had really happened. The compromise had not *answered* the territorial question. On the most important new land, it had simply handed the question to the settlers and walked away. Popular sovereignty sounded like democracy. It was in fact a time bomb with a delayed fuse, and worse than a tactical dodge, it was a moral one: it treated the question of whether human beings could be owned as a matter to be settled by local preference, like whether to build a road. It guaranteed that the fight over slavery, instead of being settled in Congress, would now be fought out on the ground in the territories themselves, settler by settler and ballot by ballot. That was another way of saying it was an open invitation to whoever could flood a territory with the most bodies and the most guns. It would take four years for someone to light it.` },
      { p: `And not everyone in the South had been willing to wait even that long. While Clay and Webster bargained, delegates from nine slave states had gathered in June 1850 at the **Nashville Convention**, the first time the South organized, in one room, to weigh leaving the Union if its demands on the territories were refused. The radicals who called it hoped for a secession movement. They did not get one: moderates took control, and when Congress passed the Compromise, most of the South accepted it as a fair-enough outcome and the convention fizzled. (A rump second session that autumn, smaller and angrier, denounced the deal and affirmed a state's right to secede, but almost nobody was listening.) Nashville settled nothing, and that is exactly why it matters: it showed that as early as 1850, secession was no longer just a threat muttered by individuals. It was something the South could convene to consider, and would convene again, when the conditions were riper.` },
      { fig: '/war-img/road-to-war-fig4-calhoun-brady.jpg', cap: `John C. Calhoun, photographed by Mathew Brady in 1849, one year before he sat wrapped in his coat in the Senate chamber, too ill to speak his own ultimatum. He died March 31, 1850, his final architecture of ideas outlasting him by a decade.`, credit: `Mathew Brady · 1849 · Sotheby's · public domain` },
      { h: `The Match on the Powder`, eyebrow: `Turning point` },
      { fig: '/war-img/road-to-war-fig6-douglas-vannerson.jpg', cap: `Stephen A. Douglas, "the Little Giant," photographed in 1859. He saved the Union in 1850 by splitting Clay's omnibus into five manageable bills. He nearly broke it in 1854 by erasing the Missouri Compromise line to build a railroad. Not a villain of this story, but something more interesting: a man whose ambition outran his conscience.`, credit: `Julian Vannerson · 1859 · Library of Congress · public domain` },
      { p: `The man who lit the territorial fuse was the same man who had saved the Union in 1850: Stephen Douglas. And he did it, by most accounts, not out of malice toward the North but out of ambition and a railroad.` },
      { p: `By 1854 Douglas wanted to organize the great unsettled territory west of Iowa and Missouri (the country that would become Kansas and Nebraska) partly because he dreamed of a transcontinental railroad running west from Chicago, his home city, and you cannot lay track through land that has no government. The problem was that all of this territory lay *north* of the 36°30′ line. Under the Missouri Compromise it was free soil, settled law, untouchable. Southern senators, whose votes Douglas needed, would not organize new free territory for nothing.` },
      { p: `So Douglas gave them what they wanted, and in doing so he detonated the country. His **Kansas–Nebraska Act**, introduced in January 1854, organized both territories under **popular sovereignty** (let the settlers decide) and, to make that mean anything, it declared the Missouri Compromise line "inoperative." In a single clause, the sacred boundary of 1820, the wall that had kept slavery out of the northern West for thirty-four years, was simply erased. President Franklin Pierce, a Northern Democrat sympathetic to the South, declared backing the bill "a test of Democratic orthodoxy" and signed it into law on May 30, 1854, after it passed the Senate 37 to 14 and squeaked through the House 113 to 100.` },
      { p: `Douglas badly misjudged what he had done. He seems genuinely to have thought he was clearing a procedural hurdle for a railroad. What the North heard was that the slave power (the term Northerners increasingly used for the political machine of wealthy slaveholders they believed controlled the federal government) had reached up, torn down a thirty-four-year-old guarantee, and thrown open to slavery land that had been promised to freedom before most living Americans were born. The reaction was not disappointment. It was fury: the sense of a contract broken, a sacred line defiled. Newspapers across the North denounced the act as a plot. And in the rage that followed, the American party system, which had organized the country's politics for a generation, came apart.` },
      { h: `The Parties Shatter`, eyebrow: `Consequence` },
      { p: `The collapse of the party system was more dangerous than any single deal. The institutions that had been containing the fight were coming apart.` },
      { p: `The Whig Party was the first to die. It had always been a national party, with a Northern wing and a Southern wing, and slavery had been straining the seams for years. The Kansas–Nebraska Act finished it. Southern Whigs could not stay in a party whose Northern half was in open revolt against the slave power; Northern Whigs could not stomach a party whose Southern half wanted slavery spread into the territories. The thing simply tore down the middle along the now-familiar line, and by 1856 the Whig Party had effectively ceased to exist. One of the two great parties that had governed the country had been killed by the slavery question. A party is a machine for *forging* national majorities across regions, the one device the country had for making a Mississippian and a Vermonter want the same man for president. The country had just lost one of only two it owned.` },
      { p: `Into the wreckage rushed two new movements, and the contrast between them is the contrast between a dead end and a fuse.` },
      { p: `The dead end was the **American Party**, better known as the **Know-Nothings**, so called because the movement began as a secret society whose members, when asked about it, were instructed to say they "knew nothing." Their cause was not slavery but immigration: they were nativists (people who wanted to protect what they saw as native-born American culture from newcomers), hostile above all to the Irish and German Catholics pouring into American cities. For a moment in 1854 they surged and looked like the replacement for the Whigs. But nativism could not organize a country that was busy tearing itself apart over something else, and the Know-Nothings split along the same North–South line as everyone else and collapsed.` },
      { p: `The fuse was the **Republican Party**, born out of the rage at Kansas–Nebraska: antislavery activists gathering in 1854 in towns like Ripon, Wisconsin, and Jackson, Michigan, to build a new party around a single organizing idea: *no further expansion of slavery into the territories*. Two things about it are easy to get wrong, and both matter. First, this is not the Republican Party of today; it is its ancestor in name and lineage, but it was a frankly sectional, antislavery, Northern party of the 1850s, and you should not read the present back into it. Second, the early Republicans were *not* abolitionists. Most of them did not propose to end slavery where it already existed; that would have been wildly unpopular even in the North, and constitutionally fraught. They proposed only to stop its *spread*. That careful distinction (against expansion, not against slavery itself) was exactly what let the new party gather former Whigs, ex-Free Soilers (the small antislavery-expansion party already in the field), disgusted Northern Democrats, and stray Know-Nothings into one broad Northern coalition.` },
      { p: `In 1856, only two years old, the Republican Party ran its first candidate for president (the explorer John C. Frémont) and very nearly won. Frémont lost to the Democrat James Buchanan. But he carried eleven Northern states, and the arithmetic of that was terrifying: a party could now win the presidency on Northern votes *alone*, without a single electoral vote from the South, without even appearing on most Southern ballots. The country had produced a major party that one entire region could elect and the other entire region despised, and there was nothing the South could do at the polls to stop it, because the votes simply weren't in the South to be had. The fault line of 1846 now had a political army standing on each side of it. All it would take to break the Union was for the Northern army to win one election. The alarm bell was no longer ringing in a single vote. It was a party.` },
      { p: `But first, the territories Douglas had thrown open would show the country exactly what "let the settlers decide" meant in practice. It meant blood.` },
      { h: `Bleeding Kansas`, eyebrow: `Consequence` },
      { fig: '/war-img/road-to-war-fig7-border-ruffians-kansas.jpg', cap: `"Border ruffians" from Missouri cross into Kansas to vote, and to make sure the other side doesn't. Popular sovereignty, in practice, meant whoever brought more guns to the polling place.`, credit: `Scribner, Armstrong & Co. (illustrator) · 1880 · public domain` },
      { p: `Popular sovereignty rested on a quaint assumption: that the settlers of a territory would calmly hold an election and abide by the result. In Kansas, both sides understood immediately that whoever showed up to vote would decide whether the territory entered the Union slave or free, and so both sides set out to flood Kansas with the right kind of settler, or to fake it. The result was not an election. It was a small civil war, four years before the big one, and the country took to calling it **Bleeding Kansas**.` },
      { p: `The mechanism worked exactly as a time bomb should. From neighboring Missouri, a slave state, thousands of armed proslavery men (called "border ruffians" by the free-state press) rode across the line on election days to cast fraudulent ballots and intimidate free-state voters. The proslavery faction, fortified by this fraud, set up a government at the town of **Lecompton**. The antislavery free-state settlers, refusing to recognize it, set up a rival government of their own at **Topeka**, with its own constitution barring slavery. So Kansas now had two governments, each claiming to be the legitimate one, each armed, neither willing to yield. President Pierce backed the proslavery side and declared the free-state government illegitimate. The federal machinery designed to keep order had instead picked a team.` },
      { p: `The violence that followed has no tidy body count, and you should be suspicious of anyone who gives you one. The careful estimates run to *more than fifty* killed in the political fighting, with broader tallies ranging higher and the precise number genuinely contested. But two episodes in the spring of 1856 stand for the whole, and they happened almost back to back.` },
      { p: `On **May 21, 1856**, a proslavery posse, hundreds strong and stiffened with Missouri border ruffians, descended on **Lawrence**, the free-state stronghold. They burned the free-state hotel, smashed the presses of two antislavery newspapers, and ransacked homes and shops. The "Sack of Lawrence" killed no one outright, but as a piece of news it was an atrocity, and the Northern press reported it as exactly that: proof that the slave power would burn a free town to the ground to get its way.` },
      { p: `Three days later came the answer, and it was worse. A grim, fanatical antislavery settler named **John Brown**, a man who believed himself the instrument of a wrathful God, led a band of seven men, including four of his own sons, to a settlement along **Pottawatomie Creek**. In the night of May 24–25, 1856, they dragged five proslavery settlers from their homes and hacked them to death with broadswords. The **Pottawatomie Massacre** was not a battle and not self-defense; it was a calculated, terrifying act of retributive murder, and it announced that the antislavery side had produced a man willing to kill in cold blood for the cause. (Brown would have said, and his defenders did say, that the slave system itself killed in cold blood every day; but that argument, whatever its force as moral philosophy, does not change what happened on Pottawatomie Creek.)` },
      { p: `Brown was never tried for it.` },
      { p: `He simply vanished back into the fighting, and the territory spiraled into raid and reprisal. This was what popular sovereignty had delivered. The idea had been to take the slavery question out of Congress's hands and let local democracy settle it. What it actually did was turn the question over to whoever was willing to bring more guns.` },
      { p: `But Kansas was not done teaching the country its lesson, and the next chapter of it would ring the alarm bell again, this time inside the Democratic Party itself. By 1857 the proslavery government at Lecompton had drafted a state constitution (the **Lecompton Constitution**) designed to bring Kansas into the Union as a slave state, and it had done so through a rigged process that never gave the territory's free-state majority a fair vote. The new president, **James Buchanan** (a Northern Democrat from Pennsylvania, but one so reliably sympathetic to the South that his enemies called men like him "doughfaces") endorsed it. He pressed Congress to admit Kansas as a slave state under a constitution most Kansans plainly did not want.` },
      { p: `This was a bridge too far even for the man who had started the whole mess. Stephen Douglas, the author of popular sovereignty, broke with his own party's president over it: publicly, bitterly, on the floor of the Senate. Douglas was no antislavery man; what he could not abide was that Lecompton made a fraud of the very principle he had staked his career on. If "let the settlers decide" meant anything, it could not mean ramming a slave constitution down a free-state majority's throat. And so the Democratic Party, the last truly national party left standing, split in two over Kansas: a Buchanan wing and a Douglas wing, Southern and Northern, glaring at each other across the same seam that had already swallowed the Whigs. In the House of Representatives the vote tells the story. Kansas statehood under Lecompton was blocked, 120 to 112, with Northern anti-Lecompton Democrats crossing the aisle to vote alongside Republicans. There was the alarm bell again, ringing now inside the governing party. When the question was finally sent back to Kansas itself in August 1858, the territory's voters rejected the slave constitution by something close to six to one. Kansas would eventually enter the Union, in 1861, as a free state.` },
      { p: `It was a total defeat for the slave power in Kansas. But the lasting damage was to the Democrats. The Buchanan–Douglas break was the first crack in the one institution still holding the country together, and it would widen, two years later, into the fracture that handed the presidency to a Republican and the South its excuse to leave. The seam that had opened in every other institution had now opened inside the last party that spanned it.` },
      { p: `And almost on cue, the violence of the territory climbed the steps of the Capitol and walked onto the floor of the United States Senate.` },
      { h: `The Caning`, eyebrow: `Consequence` },
      { fig: '/war-img/road-to-war-fig5-southern-chivalry-caning.jpg', cap: `"Southern Chivalry — Argument versus Clubs," 1856. Preston Brooks beats Senator Charles Sumner senseless at his Senate desk while Lawrence Keitt waves a pistol to keep anyone from interfering. Half the country sent Brooks commemorative canes. The other half sent Sumner back to the Senate as a martyr.`, credit: `After John L. Magee (lithographer) · 1856 · public domain` },
      { p: `If you want a single image for how far gone American politics already was by 1856, here it is: a congressman beating a senator nearly to death with a cane, on the Senate floor, while a colleague waved a pistol to keep anyone from intervening. Half the country cheered.` },
      { p: `It began with a speech. On May 19 and 20, 1856, the very days Kansas was boiling over, **Charles Sumner** of Massachusetts, the fierce antislavery Republican who had taken Daniel Webster's old Senate seat, delivered a two-day oration he called "The Crime Against Kansas." It was a blistering attack on the proslavery cause, and Sumner did not keep it abstract. He singled out **Andrew Butler**, an elderly proslavery senator from South Carolina, for personal ridicule, mocking him with an extended and deliberately filthy metaphor: Butler, Sumner said, had taken a mistress, "the harlot, Slavery" (a harlot being a prostitute), ugly to the world but ever lovely to him. It was a calculated insult, in an era that took insults to a gentleman's honor with deadly seriousness.` },
      { p: `Butler was not in the chamber to hear it, but his cousin was paying attention. **Preston Brooks**, a proslavery Democratic congressman from South Carolina, decided that Sumner's words demanded an answer, and that Sumner, an antislavery agitator, was beneath the dignity of a duel (a formal armed fight between social equals, the gentleman's way of settling a question of honor) and deserved instead the kind of beating a Southern gentleman administered to a social inferior. It is worth naming plainly what that "honor" was doing, because the genteel language hides it. In the antebellum South, the honor code was a machine for justifying violence against everyone it placed outside its protection: enslaved people, free Black people, social inferiors of every kind. Brooks's reasoning was not the quirk of one hot-headed man. It was honor-culture logic doing the work that argument no longer could: it classified a political opponent as someone beneath the rules of civil debate, and so made beating him on the Senate floor not a crime but a duty.` },
      { p: `On May 22, 1856, after the Senate had adjourned, Brooks walked up to Sumner at his desk, where Sumner sat writing, hemmed in and unable to rise. Brooks raised a heavy gutta-percha cane (a hard rubber walking stick) and began to beat him about the head. He struck more than thirty times, until the cane snapped, and then he kept beating Sumner with the broken stub. A fellow South Carolina congressman, Lawrence Keitt, brandished a pistol to hold off the senators who tried to come to Sumner's aid. Sumner, blinded by his own blood, finally wrenched his desk from its bolts and collapsed.` },
      { p: `The injuries nearly killed him. Sumner suffered what we would now recognize as a traumatic brain injury, and he could not return to his Senate seat until **1859**, more than three years later. Massachusetts pointedly refused to replace him. It left his desk empty, session after session, as a silent rebuke: an absence on the Senate floor that said more than any speech.` },
      { p: `But it was the *reaction* that revealed how irreparable the country had become. In the North, the attack on Sumner was an outrage, fresh proof (alongside the burning of Lawrence) that the slave power answered argument with violence; "Bleeding Sumner" and "Bleeding Kansas" became twin rallying cries that drove recruits into the young Republican Party. In the South, Preston Brooks became a *hero*. The Richmond Enquirer praised the caning as "good in conception, better in execution." Admirers across the South mailed Brooks dozens of new canes to replace the one he'd broken, some of them inscribed "Hit him again." When the House voted on whether to expel Brooks, the motion fell short of the required two-thirds; Brooks resigned anyway, went home, and was promptly and triumphantly re-elected. A District of Columbia court fined him $300 and sent him home. No prison, no real punishment, a chorus of applause.` },
      { p: `That is the part that should stop you. The two halves of the country did not merely disagree about Sumner's beating. They had opposite *moral reactions* to the same event: one side saw a martyr, the other saw a hero, and there is no compromise to be brokered between people who cannot even agree on whether a beating was a crime. Members of Congress began carrying weapons onto the floor. The Senate had become another front in Bleeding Kansas.` },
      { h: `The Court Tries to End the Argument`, eyebrow: `Turning point` },
      { fig: '/war-img/road-to-war-fig8-dred-scott-1857.jpg', cap: `Dred Scott, photographed around 1857. The Supreme Court ruled he had no right to sue, no right to be free, and no claim to citizenship the law was bound to respect. He was freed eighteen months later anyway, by a private man's signature. He died of tuberculosis on September 17, 1858.`, credit: `Photographer uncredited · c. 1857 · public domain` },
      { p: `If Congress could no longer settle the territorial question without bloodshed, perhaps the one branch of government still above the fray could. In 1857 the Supreme Court of the United States tried to settle the whole thing forever, with a single sweeping decision. It did not settle it. It poured gasoline on it.` },
      { p: `The case was **Dred Scott v. Sandford**, and the man at its center was an enslaved man named **Dred Scott**, who had been taken by his owner from the slave state of Missouri to live for years in free territory (Illinois and the Wisconsin Territory, where the Missouri Compromise banned slavery) and then back to Missouri. Scott sued for his freedom on the commonsense ground that living on free soil had made him free. The case climbed through the courts for a decade and reached the Supreme Court in 1857. The country waited, hoping the justices might find some narrow ruling that lowered the temperature.` },
      { p: `What it got, on **March 6, 1857**, was the opposite: a 7-to-2 decision, written by Chief Justice **Roger B. Taney** of Maryland (a Southern Democrat and former slaveholder) that went as far as it possibly could in the slave power's direction. Taney's majority opinion did three devastating things.` },
      { p: `First, it ruled that Black Americans, whether enslaved or free, were not and could never be citizens of the United States, and therefore had no right even to sue in a federal court. By that logic, Scott's case should never have been heard at all. Taney grounded this in a notorious passage describing what he claimed was the universal view of Black people at the nation's founding: that they had been regarded as "so far inferior, that they had no rights which the white man was bound to respect." It is crucial to be precise about that line, because it is often misquoted as Taney's own opinion of Black people. Taney was claiming to *describe* the attitude of the founding generation. But he was not offering it as mere history; he was deploying it as the legal foundation of his ruling that Black Americans had no claim to citizenship. The framing was historical; the effect was a holding, written into the law of the land in 1857.` },
      { p: `Second, and this is where the decision became a political earthquake rather than merely a moral one, Taney ruled that **Congress had no constitutional power to ban slavery from any federal territory**. His reasoning ran through the Fifth Amendment to the Constitution, which says the government may not take a person's property "without due process of law" (that is, without a fair legal proceeding). Enslaved people, Taney held, were property; so a law that barred a man from bringing his slaves into a territory stripped him of his property by simple act of Congress, and was therefore unconstitutional. This struck down the Missouri Compromise outright, declaring that the 36°30′ line had been illegal all along, and it was only the second time in the nation's history that the Court had struck down an act of Congress.` },
      { p: `Third, the logic ran straight through popular sovereignty as well. If Congress itself could not ban slavery from a territory, then neither could a territorial legislature created by Congress. At a stroke, this gutted *both* of the era's competing answers to the territorial question. It destroyed the **Republican Party's** entire platform; the party existed to bar slavery from the territories through Congress, and the Court had just declared that power unconstitutional. And it destroyed **Stephen Douglas's** popular sovereignty; the settlers couldn't ban slavery either. Taney had reached for a ruling that gave the South everything and, he hoped, ended the argument.` },
      { p: `It ended nothing. The North did not accept it. Republicans flatly refused to treat the decision as legitimate, denouncing it as the slave power's capture of the last branch of government it didn't yet control. Far from quieting the antislavery movement, *Dred Scott* swelled it, driving Northern moderates (including former Know-Nothings with nowhere else to go) into the Republican ranks. The decision meant to close the question instead handed the Republicans their most powerful argument: that the slave power now ran the Congress (Kansas–Nebraska), silenced its critics with violence (the caning), and owned the Supreme Court (Dred Scott). Three exhibits, one conspiracy.` },
      { p: `And what of Dred Scott himself, the man whose name the whole country now knew, whose freedom the highest court in the land had treated as an abstract constitutional theorem? The decision did not even keep him enslaved for long. Within weeks his owners transferred him to a man named Taylor Blow, a son of the family that had first owned Scott as a boy, and on May 26, 1857, Blow walked into a St. Louis courthouse and set Dred and his wife Harriet free. Scott had spent a decade in the courts to win what a stranger's signature granted in an afternoon. He lived barely sixteen months a free man, working as a hotel porter, before tuberculosis killed him on September 17, 1858. Harriet outlived him by eighteen years; she lived to see the war come, and to see the Thirteenth Amendment do for four million people what the Supreme Court had told her husband the Constitution forbade.` },
      { h: `The Architecture of the Quarrel`, eyebrow: `Pressure` },
      { p: `Underneath the events (the deals, the votes, the beatings, the rulings) ran a set of *ideas*, hardening on both sides, that turned ordinary political disputes into something neither side could compromise. By the late 1850s, each region had built a complete worldview in which the other was not a rival but a mortal threat. Those worldviews are why the country could no longer be talked down.` },
      { p: `The South's intellectual architecture had largely been built by one man: **John C. Calhoun**, dead since 1850 but more present than ever. Decades earlier, during a fight over tariffs, Calhoun had developed the doctrine of **nullification**: the claim that an individual state had the right to declare a federal law unconstitutional and refuse to obey it within its borders. He paired it with a theory he called the **concurrent majority**: the idea that a simple national majority must not be allowed to rule over a determined minority's vital interests, and that the minority (by which Calhoun meant the slaveholding South) must have the power to block any law that threatened it. Dress it up however you like, this was a constitutional doctrine engineered to one purpose: to give the slaveholding minority a permanent veto over the antislavery majority, so as to protect what was, concretely, the power to compel millions of human beings into unpaid labor for life. "States' rights" was the language. The protection of slavery was the substance.` },
      { p: `Calhoun had done one more thing, and it was the most consequential of all. In a Senate speech back in 1837, he had abandoned the South's old defensive crouch (the apologetic line that slavery was a "necessary evil" inherited from the past) and replaced it with something far more militant: slavery, he declared, was "a positive good," beneficial to master and slave alike, a superior way of organizing society. That reframing, from grudging apology to proud advocacy, defined the Southern mind for the next generation. You do not compromise away a positive good. You defend it, and you spread it.` },
      { p: `By the 1850s the men carrying Calhoun's logic to its conclusion had a name: the **fire-eaters**. They were not a formal party but a loose network of Southern radicals who had moved past defending slavery where it existed to demanding its expansion and, increasingly, **secession** (a state formally withdrawing from the United States to become an independent nation, or to join a new one). **Robert Barnwell Rhett** of South Carolina, nicknamed "the Father of Secession," used his family's *Charleston Mercury* newspaper to call for the South to leave the Union as early as 1850; it was Rhett's circle that had convened the Nashville Convention. **William Lowndes Yancey** of Alabama, the faction's most electric orator, wrote in 1858 of his plan to "fire the Southern heart" and "precipitate the cotton states into a revolution." (A third, **Edmund Ruffin** of Virginia, an agricultural reformer turned fanatic, agitated for disunion for years; he would get to fire one of the first shots at Fort Sumter and, after the Confederacy's defeat, would take his own life, putting his rifle in his mouth, rather than live under the flag he hated.)` },
      { p: `The fire-eaters were a minority even in the South in the 1850s, dismissed by many of their own neighbors as cranks. That is true, but it is the kind of truth that misleads if you stop there. They were cranks whose goal the Southern majority would, in the end, adopt. When the crisis finally ripened, when a purely Northern party won the White House, the respectable, moderate, Union-loving Southern majority did not restrain the fire-eaters. It followed them out of the Union. The men dismissed as cranks in 1850 turned out to be the vanguard, not the fringe.` },
      { p: `The North, meanwhile, had built its own worldview around a phrase Northerners increasingly used: the **Slave Power**. This was the conviction that a small oligarchy of wealthy slaveholders, a few hundred thousand planters (the great landowners who ran the plantations where enslaved people were worked), had quietly seized control of the federal government and was using it to protect and extend slavery against the wishes of the free majority. The charge was not pure paranoia; it had real evidence behind it. Through the Three-Fifths Compromise (the constitutional rule that counted three out of every five enslaved people toward a state's population for purposes of representation, despite those people having no rights at all) the South enjoyed extra seats in the House and extra votes for president, representation built on people it held in bondage. Southerners had held the presidency and dominated the Supreme Court for most of the nation's history. And now the Fugitive Slave Act was forcing free Northerners to become slave-catchers. To the rising Republicans, Kansas–Nebraska, the caning of Sumner, and Dred Scott were not three separate events but three moves by a single hidden hand: the Slave Power seizing Congress, then silencing dissent, then capturing the courts.` },
      { p: `Each side, in other words, had come to see the other as a conspiracy against liberty itself. But the two charges were not mirror images, however neatly the symmetry reads. The South called any limit on its power to hold human beings in bondage an attack on its liberty. The North called the Slave Power's reach a conspiracy against the liberty of free men. Both sides cried "conspiracy." Only one of the two was defending the liberty to own people, and the symmetry of grievance does not make the grievances equal.` },
      { p: `And running beneath all of it was a third idea, an economic one, that gave the South its dangerous confidence: **King Cotton**. The Southern cotton economy had grown so vast that Southerners had convinced themselves the world could not do without it. When a financial crisis, the Panic of 1857, wracked the industrial North while the agrarian South rode it out comparatively unscathed, the conviction hardened into swagger. In 1858 Senator **James Henry Hammond** of South Carolina put it to the Senate in words that became the slogan of Southern self-assurance: no nation, he declared, would dare make war on cotton, because cotton was indispensable to the looms of Britain and the wealth of the world. "Cotton is king," Hammond said, and the South believed it. It believed that its great cash crop made it not the weaker half of the country but the stronger, and that if it ever came to a break, Britain and the markets of Europe would be forced to take the South's side. It was a catastrophic miscalculation, as the war would prove. But in 1858 it was an article of faith, and it removed from the Southern mind the last practical reason for caution. A region that believes it holds the world's economy hostage does not fear a fight.` },
      { p: `So by the late 1850s the country had assembled every ingredient of a catastrophe: two regions, each convinced the other was conspiring against its freedom; a Southern intelligentsia that called slavery a positive good and a Southern radical fringe openly plotting to leave; a Northern political party that one whole region could elect and the other whole region could not abide; the last national party cracking in two over Kansas; and a system of compromises that had visibly, repeatedly, broken. All that was missing was a spark wild enough to make both sides believe, at last, that the other meant to destroy it. In the autumn of 1859, the grim antislavery zealot who had murdered five men in Kansas supplied it.` },
      { h: `The Spark at Harpers Ferry`, eyebrow: `Turning point` },
      { fig: '/war-img/road-to-war-fig9-john-brown-1859.jpg', cap: `John Brown, May 1859, six months before Harpers Ferry. He believed himself the instrument of a wrathful God. Looking at this photograph, it is difficult to argue he didn't believe it absolutely.`, credit: `Martin M. Lawrence (photographer) · May 1859 · Library of Congress · public domain` },
      { p: `**John Brown** had not been idle since Pottawatomie. The same fanatical certainty that had led him to hack five proslavery settlers to death in the Kansas night had, by 1859, grown into a far grander and stranger plan: he would seize a federal arsenal (a government weapons storehouse holding thousands of rifles and muskets), arm the enslaved people of the surrounding countryside, and ignite a slave uprising that would roll across the South and tear slavery up by the roots. It was, depending on how you look at it, an act of pure moral conviction or an act of suicidal delusion. It was almost certainly both.` },
      { p: `On the night of **October 16, 1859**, Brown led a band of twenty-one men besides himself (sixteen white, five Black) into **Harpers Ferry, Virginia** (today West Virginia), where the federal armory and arsenal held thousands of weapons. They seized the armory in the dark and took hostages, and then Brown waited for the enslaved population to rise and rally to him. They did not. Almost no one knew the raid was happening, and the few who might have joined had no way to. Instead, by morning the local militia and townspeople had Brown's men pinned down inside the armory's engine house, and word was racing to Washington.` },
      { p: `The federal government's response is one of history's grim little ironies. The officer dispatched to crush the raid was a U.S. Army colonel named **Robert E. Lee**, the same Robert E. Lee who, eighteen months later, would resign that army to command the armies of the slaveholding Confederacy. Lee arrived at Harpers Ferry late on October 17 with a force of U.S. Marines. His aide, sent forward under a flag of truce to demand Brown's surrender, was a young cavalry lieutenant named **J.E.B. Stuart**, who would also, soon enough, ride for the Confederacy. Brown refused to surrender. On the morning of October 18, Lee ordered the Marines to storm the engine house. It took only minutes. Brown was beaten down and captured; ten of his men, including two of his sons, were killed in the raid. A handful of his raiders escaped; the rest were taken.` },
      { fig: '/war-img/road-to-war-fig10-harpers-ferry-marines.jpg', cap: `U.S. Marines storming John Brown's engine house at Harpers Ferry, October 18, 1859, from a sketch made on the spot. The officer commanding the Marines was Colonel Robert E. Lee; his aide carrying the surrender demand was Lieutenant J.E.B. Stuart. Both would be in Confederate uniform eighteen months later.`, credit: `Frank Leslie's Illustrated Newspaper · October 29, 1859 · public domain` },
      { p: `The raid itself was a military fiasco, over almost before it began. But the *trial* turned John Brown into something the South would have given anything to prevent. Virginia charged him with treason against the state, murder, and inciting slaves to rebel. The proceedings were swift. The jury deliberated less than an hour before convicting him on all counts, and the outcome was never in doubt. But Brown, in the weeks between his sentencing and his death, conducted himself with a serene, unbreakable composure that unsettled everyone who watched, and he used the courtroom and his cell as a pulpit, issuing letters and statements that read less like a condemned criminal's than a prophet's. On the morning he was hanged, **December 2, 1859**, at Charlestown, Virginia, he handed his jailer a final written note. It read:` },
      { p: `I John Brown am now quite certain that the crimes of this guilty land will never be purged away but with blood.`, q: true },
      { p: `It would prove one of the most accurate prophecies in American history.` },
      { p: `And then came the reaction. It was a split screen so stark that it told the country it had already, in spirit, divided in two. It was not that North and South disagreed about John Brown. It was that one half of the country mourned as a martyr the man the other half saw as a murderer come to cut its throat in the night.` },
      { p: `In the South, John Brown confirmed the deepest, most primal fear of every slaveholding community: that the North was not merely hostile to slavery in the abstract but was prepared to send armed men south to put weapons in the hands of the enslaved and turn the countryside into a scene of massacre. It did not matter that Brown was a fringe figure most Northerners had never heard of and many abolitionists disowned. What mattered was what came next. Because in the North, large numbers of people (including respectable, law-abiding people who condemned the raid itself as criminal madness) treated Brown's *death* as a martyrdom. Church bells tolled. Flags flew at half-staff in Northern towns on the day he hanged. The great writers of New England, Ralph Waldo Emerson and Henry David Thoreau (two of the most celebrated thinkers in the country), praised his moral courage and likened him to a saint. To Southern eyes, this was the mask coming off. The South had told itself the North wanted to incite slave rebellion and race war, and here was the North ringing its bells for a man who had tried to do exactly that. The Richmond Enquirer declared that the raid and its aftermath had advanced the cause of disunion more than any event since the founding of the government.` },
      { p: `That was the thing no compromise could touch. Once a people have arrived at opposite verdicts not just on a policy but on whether a man was a saint or a devil, there is no longer a middle in which a deal can be made. The bonds of affection and trust that hold a country together had not been strained. They had snapped.` },
      { p: `By the end of 1859, every compromise had failed. The Missouri line was gone, ruled illegal by the Supreme Court. The Compromise of 1850's popular sovereignty had bled Kansas and then been gutted by Dred Scott. The party system that had channeled the conflict had shattered: the Whigs dead, the Democrats split down the middle over Lecompton, and in their place a Northern party the South would never accept and a Southern radicalism openly courting secession. The Senate floor had seen a beating, a federal arsenal had seen a raid, and a hanged zealot's prophecy of blood hung over everything. The machinery of compromise had been built to contain a disagreement. It turned out the country did not have a disagreement. It had two incompatible nations sharing one government, and a question between them (would the country be slave or free) that could no longer be deferred, divided, or dodged again.` },
      { p: `All that remained was an election to make the rupture official.` },
    ],
    meanwhile: {
      region: `the election of 1860`,
      title: `Lincoln's Rise & the Election of 1860`,
      body: `With the Whigs dead and the Democrats splitting along the same North–South seam that had broken everything else, the election of 1860 became a referendum on whether the Union could hold at all. The story turns to the prairie lawyer the Republicans nominated, the four-way race that broke the back of the old politics, and the night the Deep South began, at last, to leave.`,
    },
  },
}

export default function RoadToWarThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="road-to-war"
      battleName="The Road to War"
      theatreId="offfield"
      battleId="th-road"
      theatreHref="/war-civil-war/off-the-battlefield"
      accent={ACCENTS.otbf}
      heroImage="/war-img/road-to-war-hero-reynolds-map.jpg"
      heroPalette={["#5b3a1c","#2c3a24","#0f0c06"]}
      heroCredit={`William C. Reynolds & J. C. Jones · 1856 · Library of Congress Geography & Map Division · public domain`}
      endHref="/war-civil-war/off-the-battlefield"
      endKicker={`The peace is gone`}
      endLabel={`Back to Off the Battlefield`}
    />
  )
}
