'use client'

// Vicksburg Campaign & Siege — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → 5 critic gates → reconcile.
// Data only; rendered by the shared <BattleSectionReader>. 6 sections (campaign + siege).

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const VICKSBURG_NARR: Record<string, Narr> = {
  'the-key': {
    eyebrow: 'Vicksburg · The fortress on the bluffs',
    title: 'The Key to the War',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -91.5, lonMax: -89.6, latMin: 31.7, latMax: 32.9 },
        states: [
          { name: 'Mississippi', tone: 'focus', label: 'MISSISSIPPI', labelLon: -91, labelLat: 31.8 },
          { name: 'Louisiana' }, { name: 'Arkansas' }, { name: 'Tennessee' }, { name: 'Alabama' },
        ],
        dots: [
          { name: 'Vicksburg · May 18 – Jul 4, 1863', lat: 32.352, lon: -90.878, heavy: true, anchor: 'middle', dy: -30 },
          { name: 'Jackson, MS', lat: 32.299, lon: -90.184, color: '#8a8175', anchor: 'start' },
        ],
      } },




      { p: 'In the spring of 1863 the Mississippi River was the spine of a continent, and the Confederacy was sitting on the one vertebra that mattered. Trace the river south from where it leaves Union hands and you eventually run up under a bluff town in western Mississippi where the channel doubles back on itself in a tight hairpin bend. The town sat on high ground on the east bank, and its guns looked straight down on the water below: heavy cannon dug into the bluff in clusters called batteries. Any boat coming downriver had to pass directly under those batteries, slowly, in plain sight. That town was Vicksburg, and together with Port Hudson, Louisiana, downstream, it held the last Confederate-controlled stretch of the Mississippi. As long as Vicksburg stood, the river was closed.' },
      { p: 'That mattered for reasons both blunt and strategic. The Mississippi was how the farms of the Northwest (Ohio, Illinois, Iowa) got their grain and pork to market, and the Confederacy had corked the bottle. It was also the seam of the rebellion itself. East of the river lay the heart of the Confederacy; west of it lay Texas, Arkansas, and most of Louisiana, the so-called Trans-Mississippi, which funneled cattle, men, and supplies eastward across the water. Take Vicksburg and you opened the river to Union traffic and sawed the Confederacy clean in two. Abraham Lincoln understood this exactly. He is supposed to have told his cabinet that Vicksburg was the key, that the war could never be brought to a close until that key was in the Union’s pocket, and whether or not those were the precise words, the idea was his, and it was correct.' },
      { fig: '/war-img/vicksburg-overview.png', cap: 'Why Vicksburg was the key: its bluff batteries command the hairpin bend, and the last Confederate-held reach of the river runs down to Port Hudson.', credit: 'Stuff Happened map' },
      { p: 'The man sent to turn the key was Major General Ulysses S. Grant, commanding the Army of the Tennessee. Grant was the Union’s hardest-driving western general, the victor of Forts Henry and Donelson the year before, and by the end of 1862 he had a problem that no amount of hard driving had yet solved. Vicksburg could not simply be marched up to and attacked. North of the city lay a maze of swamp, bayou, and flooded bottomland; the bluffs themselves were a natural fortress; and the river batteries made a direct naval passage suicidal.' },
      { pill: '/war-civil-war/western/fort-donelson', plabel: 'Fort Donelson: where Grant earned his “Unconditional Surrender” name' },
      { p: 'He had already learned that the hard way. Late in 1862 he had tried the obvious thing, marching an army of 40,000 straight down the railroad through central Mississippi toward the city. It ended in December when Confederate cavalry under Major General Earl Van Dorn (South) swept in behind him and burned his entire supply base at Holly Springs, destroying something like a million and a half dollars in food and ammunition in a single morning. With his pantry in ashes and his supply line cut, Grant had no choice but to turn around and march back. The same week, his lieutenant William T. Sherman tried the other obvious thing, storming the bluffs just north of Vicksburg at Chickasaw Bayou, and was thrown back bloody. So by the new year both straightforward roads to Vicksburg, the overland march and the frontal assault, were closed. The double failure taught Grant that a long supply line was a noose, a lesson he would cash in, spectacularly, the following spring.' },
      { p: 'The country he was trying to break in half was a country that existed for one reason. The Confederate states had seceded barely two years earlier to protect and extend the enslavement of four million Black people, on whose forced labor the cotton economy of the lower Mississippi Valley, Vicksburg’s own valley, was built. The river plantations Grant’s army would soon march past were worked by enslaved people, and the war to open the river was, underneath everything, a war against the slaveholding republic those plantations sustained. Every mile Grant advanced down this valley, the institution the South had seceded to protect began dissolving behind him.' },
    ],
    meanwhile: { region: 'the East', title: 'The river the headlines ignored', body: 'Far to the northeast, the war in Virginia had stalled into a grinding deadlock around the Confederate capital at Richmond, and the headlines that winter were eastern headlines. But the men who thought longest about how to actually win the war kept coming back to the river. Whatever happened in Virginia, a Confederacy cut off from Texas beef and split down its own midline could not last. Vicksburg was the quiet hinge on which the whole map turned, even while the country’s attention pointed somewhere else.' },
  },

  'the-failed-approaches': {
    eyebrow: 'Vicksburg · The winter of mud',
    title: 'Canals, Bayous, and a Drowning Army',
    blocks: [
      { p: 'The overland road and the frontal assault were dead. So for four months over the winter of 1862 and 1863, Grant tried to get at Vicksburg through the water, and for four months the water beat him. It made for a miserable, mud-caked, disease-ridden season that nearly cost him his command. Each scheme had the same logic: if the army couldn’t pass the batteries on the river, maybe it could go around them through the tangle of swamps and side-channels that laced the bottomland north and west of the city.' },
      { h: 'A Literal Ditch', eyebrow: 'The canal schemes' },
      { p: 'The first attempt was a literal ditch. Across De Soto Point, the low, swampy peninsula on the Louisiana side, inside the hairpin bend opposite the city, Grant’s men dug a canal, hoping to cut a new channel that would let the boats skip the bend and the guns entirely. The river refused to cooperate; the cut wouldn’t take the current, and Grant’s Canal was abandoned around March 1863. Upstream they tried Lake Providence, a scheme to open a long looping bayou route through Louisiana to rejoin the river far below Vicksburg, a project so unpromising that the campaign’s own historians later nicknamed it the "Lake Providence Boondoggle." It too was given up in late March.' },
      { h: 'Lost in the Flooded Forest', eyebrow: 'The bayou expeditions' },
      { p: 'The army went deeper into the swamp after that. The Yazoo Pass Expedition blew a hole in a levee near Moon Lake and sent boats winding down a chain of smaller rivers to try to land troops on dry, high ground above the city; they were stopped cold by a fort the Confederates threw up out of cotton bales, Fort Pemberton, sitting squarely in the only navigable channel. Then came the strangest of all. In the Steele’s Bayou Expedition, Rear Admiral David Dixon Porter (North), who commanded the river fleet of gunboats and ironclads, pushed his warships up a twisting bayou through the Yazoo delta to slip around Fort Pemberton from behind. The Confederates simply felled trees into the narrow water ahead of the boats and behind them, and Porter’s ironclad fleet found itself boxed in and lost in a flooded forest, warships stuck among the trees and nearly captured, until Sherman marched infantry through chest-deep swamp to hack them loose. It is the rare moment in the war when the navy had to be rescued, on foot, from the woods.' },
      { p: 'Every one of these had now failed. From a distance, and the Northern press was watching from a distance, it looked like Grant was finished: bogged in the mud, his army sick and dying of camp fever in the flooded lowlands, the man himself drinking. The whiskey stories were rumor and political knife-work, the kind of charge that trailed Grant his whole career; treat them as a press attack of the moment, not fact.', i: true },
      { p: 'What the press could not see was that the failures had taught Grant there was no way through the water from the north. If he wanted Vicksburg, he would have to do something far more dangerous.' },
    ],
    meanwhile: { region: 'inside the fortress', title: 'A winter of free repulses', body: 'For Lieutenant General John C. Pemberton (South), the Confederate commander charged with holding Vicksburg, the winter looked like one repulse after another handed to him for free. Every Union scheme had broken against the swamps and his guns without his army having to fight much for it. The river still belonged to the Confederacy. The bluffs were as strong as ever. It was easy, that winter, for the defenders to believe that the geography itself was on their side, that Vicksburg could not be taken, only failed against. The spring would test that belief to destruction.' },
  },

  'the-gamble': {
    eyebrow: 'Vicksburg · The spring run',
    title: 'Past the Guns and Loose in Mississippi',
    blocks: [
      { p: 'What Grant decided to do in April 1863 was the kind of plan that gets a general either remembered or relieved. If he couldn’t get above or around Vicksburg, he would get below it: march his army down the Louisiana side of the river, past the city out of range of its guns, then cross the Mississippi back to the eastern bank somewhere south of the fortress and come at it overland from the rear, the one direction the swamps didn’t protect. The trouble was the fleet. The army could walk down the west bank, but it needed Porter’s (North) gunboats and transports on the same side of the river to ferry it across, and the only way to get them downstream was to run them straight past the Vicksburg batteries.' },
      { h: 'Running the Batteries', eyebrow: 'The night of April 16' },
      { p: 'On the night of April 16, 1863, Porter did exactly that. He took a fleet of gunboats and transports downriver in the dark, hugging the far bank, and for two and a half hours the Vicksburg guns lit up the night and hammered them as they passed. Most of the fleet got through; only a single transport was lost. A second run followed on April 22. It put Porter’s boats below the city, exactly where Grant needed them.' },
      { p: 'To keep Pemberton’s (South) eyes anywhere but the crossing point, Grant ran two deceptions. He sent Sherman to feint, or fake, an attack up at Haynes’ Bluff, north of the city, where the Confederates still expected the blow to fall. And he turned loose a cavalry raid under Colonel Benjamin Grierson (North) that slashed roughly 600 miles straight down the length of Mississippi, tearing up railroads and pulling Confederate forces into a frantic, fruitless chase across the whole state. While Pemberton looked north and east at phantom threats, Grant moved south.' },
      { h: 'The Largest Landing Before D-Day', eyebrow: 'Grand Gulf and Bruinsburg' },
      { p: 'The crossing itself nearly went wrong. Grant’s first choice was Grand Gulf, a Confederate strongpoint on the east bank, and on April 29 he sent Porter’s ironclads to pound its bluff batteries into silence so the army could land there. After five hours of bombardment the guns were still firing and the ironclads were battered, so Grant changed the plan on the spot: he marched the army a little farther downstream and crossed where nobody was waiting, at Bruinsburg, on April 30.' },
      { p: 'Ferrying the army across to Bruinsburg was, at the time, the largest amphibious operation, the largest ship-to-shore landing of troops, in American history, a record it would hold until the D-Day invasion of Normandy in 1944. Because Grand Gulf had pushed it to an undefended stretch of shore, the whole thing went across unopposed: by the next morning some 24,000 men had stepped onto dry Mississippi soil with the fortress behind them and the interior of the state open ahead.' },
      { fig: '/war-img/vicksburg-campaign.png', cap: 'The spring gamble: run the batteries, cross at Bruinsburg, then drive inland through five battles, east to Jackson, then back west through Champion Hill to bottle Pemberton in Vicksburg.', credit: 'Stuff Happened map' },
      { h: 'Cut Loose from the Base', eyebrow: 'Living off the country' },
      { p: 'Then Grant did the thing the burning of Holly Springs had taught him. Rather than tie his army to a vulnerable supply line back to the river, the kind of line Van Dorn (South) had cut so easily that winter, he largely cut himself loose from his base and lived off the country, the army carrying what it could and stripping the rest from the Mississippi plantations as it marched: corn cribs, smokehouses, livestock, the stored wealth of the slaveholding valley feeding the army sent to break it. Freed from the supply tether, he drove inland fast, and over the next eighteen days he fought five battles.' },
      { p: 'He landed and won at Port Gibson on May 1, securing the beachhead. He beat back a Confederate brigade, several thousand men, at Raymond on May 12. Then, instead of turning straight for Vicksburg, he wheeled inland to the northeast and on May 14 stormed into Jackson, the Mississippi state capital, scattering a small relief force gathering there under General Joseph E. Johnston (South) and wrecking the city’s railroads and war factories so they could not be used against him. Only then did he turn back west toward Vicksburg, Jackson lying inland to the east and Vicksburg on the river to the west, deliberately keeping his own army planted between Johnston’s relief force to the east and Pemberton’s garrison to the west so the two could never join hands.' },
      { h: 'The Ridge That Decided It', eyebrow: 'Champion Hill, May 16' },
      { p: 'On May 16 the campaign turned on a single ridge. About twenty miles east of Vicksburg, on a wooded hill called Champion Hill, Pemberton finally came out to fight, and the result decided everything. It was the hardest day of the campaign. Grant’s columns came at the high ground through ravines and cornfields; the crest changed hands as the lines surged up and back across it, and for a few hours in the middle of the day the issue was genuinely in doubt: Pemberton had the position and the moment to wreck a piece of Grant’s army if he moved fast. He didn’t. Grant’s men carried the hill, broke the Confederate line, and turned a battle into a rout. The cost to the Confederacy was permanent: Pemberton was thrown back toward the city, and an entire Confederate division of several thousand men under Major General William W. Loring (South) was cut off in the collapse and never made it back inside Vicksburg at all, wandering off east to join Johnston instead.' },
      { pill: '/war-civil-war/western/champion-hill', plabel: 'Champion Hill: the ridge that decided the campaign' },
      { p: 'Grant later wrote that the day left him "assured of our position between Johnston and Pemberton, without a possibility of a junction of their forces."', q: true },
      { p: 'Grant, Personal Memoirs', i: true },
      { p: 'From Champion Hill the two Confederate armies could never combine, and Vicksburg’s garrison was on its own. The next day, May 17, Pemberton’s rearguard tried to hold the crossing of the Big Black River just east of the city and was routed, the survivors streaming back over the bridges and into the Vicksburg fortifications. The gamble had worked. In eighteen days Grant had crossed a major river, cut his own supply line, won five battles, taken a state capital, and driven the enemy’s whole field army inside its walls.' },
    ],
    meanwhile: { region: 'outside the city', title: 'Johnston, helpless', body: 'While Grant tightened his grip, Johnston was supposed to be assembling the army that would rescue Vicksburg. He never could. He started with only a few thousand men, was scattered out of Jackson before he could concentrate, and spent the rest of the campaign gathering a relief force that was always too small and always too late. From the eastern edge of the action he could see the trap closing on Pemberton and could do almost nothing about it. The relief that the defenders inside the city kept waiting for, all through what came next, was a relief that was never going to break through.' },
  },

  'the-siege': {
    eyebrow: 'Vicksburg · Forty-seven days',
    title: 'The Caves, the Trenches, and the Mule Meat',
    blocks: [
      { p: 'Grant did not want a siege. He wanted to take the city by storm and be done with it, and on May 19 and again on May 22 he tried. The defenders waited behind a nine-mile arc of dug-in dirt forts, earth-and-log strongpoints with sloped, angled walls, the kind of fortification engineers in this era built by the dozen and gave names like the Stockade Redan and the Third Louisiana Redan (a redan is simply an arrowhead-shaped earthwork fort, its point aimed out at the attacker). The first assault, on May 19, threw Grant’s men at the Stockade Redan and was thrown back with about a thousand Union casualties against perhaps seventy Confederate. The second, on May 22, was bigger and worse: a broad assault across a three-mile front at ten in the morning that failed bloodily, costing roughly 3,200 Union men against fewer than five hundred Confederate. Part of that slaughter came when Major General John A. McClernand (North), one of Grant’s corps commanders (a corps was one of the army’s three big wings, tens of thousands of men under a single general), overstated a breakthrough on his front and drew reinforcements into a position that didn’t exist, feeding more men into the killing ground. It helped get McClernand relieved of his command weeks later.' },
      { h: 'A Regular Siege', eyebrow: 'The army digs in' },
      { p: 'Two failed assaults in three days settled it. Grant would not bleed his army against those works again.' },
      { p: '"I now determined upon a regular siege, to ‘out-camp the enemy,’ as it were, and to incur no more losses."', q: true },
      { p: 'Grant, Personal Memoirs', i: true },
      { p: 'So the army dug. Union engineers ran some fifteen miles of approach trenches zigzagging toward the Confederate works, brought up around 220 guns, and settled in to strangle the city while Porter’s (North) fleet shelled it from the river. For forty-seven days, from May 18 to July 4, the lines tightened and the bombardment never really stopped.' },
      { fig: '/war-img/vicksburg-siege.png', cap: 'The 47-day siege: Grant’s blue lines invest the city on the landward (east) side while Porter’s fleet shells from the river, sealing the Confederate works.', credit: 'Stuff Happened map' },
      { h: 'Underground', eyebrow: 'The cave city' },
      { p: 'Inside the perimeter were not only Pemberton’s (South) soldiers but more than three thousand civilians, and to understand the siege you have to go where they went, which was underground. Into the soft yellow clay of the Vicksburg hillsides (loess, a clay so fine and firm you can carve a room into it with a spade) the residents dug something like five hundred caves. They called them bombproofs. Some were single rooms; some were big enough to hold several families, with furniture carried down from the houses above, carpets on the dirt floors, candles in niches scooped out of the walls. People moved their whole lives into the hills and learned to live by the rhythm of the shelling, timing every dash above ground, for water, for air, for cooking, to the gaps between bombardments, dropping back into the earth when the guns opened again.' },
      { p: 'One of those cave-dwellers was Mary Webster Loughborough, who had come to Vicksburg with her husband, a Confederate officer, and her small child, and found herself trapped in the city when the siege closed around it. She wrote it down. Her diary became a book, My Cave Life in Vicksburg (1864), one of the few civilian eyewitness accounts of what the siege felt like from the inside of one of those holes in the ground. She described lying awake in the dark as the shells came down, the ground shaking, never sure the cave would hold:' },
      { p: '"I shall never forget my extreme fear during the night, and my utter hopelessness of ever seeing the morning light."', q: true },
      { p: 'Mary Loughborough, My Cave Life in Vicksburg', i: true },
      { p: 'It is one of the campaign’s stranger facts that the caves worked: despite roughly 22,000 shells fired into the town over the siege, fewer than a dozen civilians were killed.' },
      { h: 'Starved by Degrees', eyebrow: 'The food runs out' },
      { p: 'What finally broke Vicksburg was not the shelling but hunger. The food ran out by degrees. The beef went first. Then the garrison and the townspeople began killing and eating their mules and horses; then dogs went into the pot; then, in the public meat market, rats appeared for sale, reportedly around $3.50 apiece, close to two weeks’ pay for a private, and people bought them. Bread was baked from ground dried peas and cornmeal, a heavy, sour loaf that turned the stomach. By the end, one account records, "shoe leather became a last resort of sustenance for many adults." Disease did what the diet started: by late June, scurvy, malaria, dysentery, and chronic diarrhea had put half the garrison sick or in the hospital. Meanwhile Grant’s army, fed and resupplied by the open river behind it, only grew, swelling toward 70,000 men as reinforcements came down to guard against Johnston. Pemberton’s army did the opposite. It shrank, starved, and sickened, with no relief coming. One army grew while the other wasted away, and that gap was the whole arithmetic of the siege.' },
      { p: 'There was still some fighting. The Union engineers tunneled a mine under the Third Louisiana Redan, packed it with explosives, and blew it up on June 25, opening a smoking crater the storming party rushed but could not hold; a second mine went off July 1. But by then the explosions were almost beside the point. The city was being starved to death.' },
    ],
    meanwhile: { region: 'the country', title: 'Waiting on the river', body: 'Beyond the lines, the whole war seemed to pause over Vicksburg. Lincoln had called it the key, and for forty-seven days the North watched to see whether Grant could finally turn it. The siege coincided with the Confederacy’s great gamble in the East, General Robert E. Lee’s invasion of Pennsylvania, and as June turned to July the two crises came to a head together: one army dug into the bluffs over the Mississippi, another marching north toward a Pennsylvania town called Gettysburg. The country did not yet know that both would break the same week.' },
  },

  'emancipation-made-real': {
    eyebrow: 'Vicksburg · Freedom along the river',
    title: 'The Cause Made Flesh',
    blocks: [
      { p: 'The war was fought over slavery, the Confederacy had seceded to protect it, and on this campaign, more than almost anywhere else, the abstraction turned into something you could watch happen on the ground. As the Army of the Tennessee pushed through the Mississippi Valley, slavery dissolved in front of it. The institution the South went to war to preserve came apart, plantation by plantation, in the army’s path.' },
      { p: 'It did not come apart because Grant freed people, exactly. It came apart because enslaved people freed themselves. Historians of the valley stress the point: the enslaved men and women here, as the Mississippi Encyclopedia puts it, "more often already had taken steps to secure their own emancipation," young men slipping away in small groups toward Union lines, families walking off the plantations toward the soldiers, rather than waiting to be liberated. Thousands self-emancipated as the army advanced, until the surrender itself ended slavery in the city: "July 4, 1863: Slavery Ends in Vicksburg" is the actual title the National Park Service gives the day. The campaign that split the Confederacy also split open slavery along the river, and the people doing the splitting were, in large part, the enslaved themselves.' },
      { pill: '/war-civil-war/off-the-battlefield/freedom-struggle', plabel: 'The freedom struggle: the enslaved who freed themselves' },
      { h: 'A Lifeline and a Hard Place', eyebrow: 'The contraband camps' },
      { p: 'The army had to figure out what to do with the tide of people coming to it, and the answer was both a lifeline and a hard place. Grant established refugee camps, "contraband" camps in the awkward legal language of the time, the word the Union used for enslaved people who reached its lines, across the Mississippi Valley, sheltering thousands of freedpeople. Conditions in them were often brutal: families who had walked to freedom found themselves crowded into camps where measles and smallpox tore through the tents, where Union soldiers’ contempt and outright violence followed them, and where many were put back to labor, for wages now, but on the same leased plantations, under overseers, picking the same cotton. Freedom, on the ground, often looked like survival under guard. But the camps were also where free Black life along the river began to organize itself, and they were a recruiting ground. A senior Union officer, Adjutant General Lorenzo Thomas, came down the valley specifically to enlist freedmen into the army; the men who joined from the Mississippi Valley numbered in the tens of thousands, enough to raise dozens of new Black regiments, on the order of seventy of them by the end of the war. The men the South had owned were now being handed rifles to fight the South.' },
      { h: 'The Answer at Milliken’s Bend', eyebrow: 'June 7, 1863' },
      { p: 'Whether those men would fight was a question a lot of people, North and South, claimed to know the answer to. On June 7, 1863, while the siege ground on, a Confederate force struck a Union supply depot on the Louisiana bank at Milliken’s Bend, about fifteen miles above Vicksburg. The depot was held largely by the African Brigade, four regiments of newly recruited, formerly enslaved men, days into uniform, barely trained and poorly armed, stiffened by the white 23rd Iowa. At dawn a Texas brigade of roughly 1,500 under Brigadier General Henry McCulloch (South) came at them. What followed was some of the most savage hand-to-hand fighting of the entire war: bayonets and clubbed muskets across the levee and the cotton-bale barricades, men killing each other at arm’s length. Union gunboats on the river, the Choctaw and the Lexington, finally broke the attack with their heavy guns.' },
      { p: 'Union casualties at Milliken’s Bend ran to somewhere between roughly 490 and 650 (the figure is genuinely disputed across sources, with the Park Service citing around 652 and others closer to 492) against perhaps 185 Confederate. The 9th Louisiana, the formerly enslaved regiment at the center of it, lost something on the order of 68 percent of its strength, the greatest proportional loss of any Black regiment in the war; its dead were the most any single Union regiment lost on any one day of the whole Vicksburg campaign. They had stood, and fought hand-to-hand, and held until the gunboats came. Milliken’s Bend, together with the fights at Port Hudson and Fort Wagner that summer, shattered the claim that Black men would not or could not fight. The Secretary of War, Edwin Stanton, said the formerly enslaved soldier had "proved his manhood" in these battles.' },
      { pill: '/war-civil-war/off-the-battlefield/usct', plabel: 'United States Colored Troops: the men the South had owned' },
      { h: 'Lincoln Draws the Line', eyebrow: 'The river and the men who freed it' },
      { p: 'And it was Lincoln who tied it all together, the river and the men who freed themselves to open it. In a public letter dated August 26, 1863, to James C. Conkling, written just after the victory, Lincoln bound the unblocked Mississippi directly to the Black soldiers who had helped win it. On the river, he wrote that the Father of Waters again went unvexed to the sea. On the soldiers, in the same letter, he was just as plain. They had to be fighting for freedom, he reasoned, because that was the only motive strong enough:' },
      { p: '"If they stake their lives for us, they must be prompted by the strongest motive, even the promise of freedom. And the promise being made, must be kept."', q: true },
      { p: 'Lincoln, letter to James C. Conkling, August 26, 1863', i: true },
      { p: 'And he looked ahead to how they would be remembered: "there will be some black men who can remember that, with silent tongue, and clenched teeth, and steady eye, and well-poised bayonet, they have helped mankind on to this great consummation." The man in the White House had drawn the line himself, from the opened river straight back to the cause: slavery, and the people ending it.' },
    ],
    meanwhile: { region: 'the North', title: 'The argument that wouldn’t die quietly', body: 'For two years, North and South had argued bitterly over whether to make Black men soldiers, and a loud chorus had insisted they would break and run at the first fire. Milliken’s Bend, fought by men who had been enslaved weeks earlier, was an answer written in blood on a Louisiana levee, and it carried far beyond the riverbank. Recruiters used it, the War Department cited it, and Lincoln folded it into his case to a skeptical Northern public. The fighting on the Mississippi that summer didn’t just open a river. It helped settle, for good, the question of who got to be a soldier in the war to end slavery.' },
  },

  'the-surrender': {
    eyebrow: 'Vicksburg · The Fourth of July',
    title: 'The Father of Waters Goes Unvexed',
    blocks: [
      { p: 'By the start of July 1863, Pemberton (South) was out of road. His garrison was starving, half of it sick, the relief from Johnston (South) was not coming and he knew it, and the Union lines were practically on top of his works. On July 3 he sent out a flag of truce, carried by Major General John S. Bowen (South), his best division commander, and opened negotiations with Grant. Grant, true to the nickname he had earned at Fort Donelson, first demanded unconditional surrender. Then he reconsidered the arithmetic. Shipping nearly thirty thousand prisoners north up the river would tie up his boats and his men for weeks. So he offered terms instead: parole. The garrison would lay down its arms and sign an oath not to fight again until they were formally exchanged, traded back, prisoner for prisoner, in a swap between the two sides, and then go home.' },
      { pill: '/war-civil-war/western/fort-donelson', plabel: 'Fort Donelson: where “Unconditional Surrender” Grant got his name' },
      { h: 'Independence Day', eyebrow: 'The city gives up' },
      { p: 'On July 4, 1863, Independence Day, Vicksburg surrendered. About 29,495 Confederate soldiers marched out, stacked their arms, and signed their paroles, many of them gaunt from weeks of mule meat and pea bread. Grant’s army took the city, the garrison, around 172 cannon, and tens of thousands of small arms.' },
      { p: 'There is a long-told story that Pemberton, who was Northern-born, a Pennsylvanian who had cast his lot with the South, deliberately chose the Fourth of July, betting that Union pride in the date would win his men softer terms. The exact words put in his mouth aren’t reliable, but that he banked on the date is reasonably well attested through Grant’s memoirs.', i: true },
      { p: 'Whatever the calculation, the date carved itself into local memory: by reputation, Vicksburg did not officially celebrate the Fourth of July again for something like 81 years, until the end of the Second World War.' },
      { h: 'The Map Redrawn', eyebrow: 'The river opens end to end' },
      { p: 'The numbers around the surrender tell the story of how the siege ended without another grand battle, but only one of them really matters. The siege itself cost the Union roughly 4,800 men; the full campaign back to the spring landings cost something over 10,000 on each side in killed and wounded. But the figure that changed the war was the surrender: nearly 30,000 men taken out of it at a stroke, an entire field army gone in a single afternoon.' },
      { p: 'What it changed was the map of the war. Five days after Vicksburg fell, Port Hudson, Louisiana, the last Confederate post downstream, gave up too, there being no longer any point in holding it, and with that the Union controlled the entire Mississippi River, end to end. Texas, Arkansas, and most of Louisiana, the whole Trans-Mississippi, were now cut off from the rest of the Confederacy, severed from the beef and men they had been sending east. The river that had been closed was open, and Northwestern grain could float to the sea again. This was the moment Lincoln captured in the Conkling letter with the line that has outlived almost everything else about the campaign:' },
      { pill: '/war-civil-war/trans-mississippi/port-hudson', plabel: 'Port Hudson: the last river post, fallen five days later' },
      { p: '"The Father of Waters again goes unvexed to the sea."', q: true },
      { p: 'Lincoln, letter to James C. Conkling, August 26, 1863', i: true },
      { h: 'The Twin Turning Point', eyebrow: 'The week the South lost the war' },
      { p: 'And it did not happen alone. Vicksburg surrendered on July 4, the day after the Confederate army was thrown back for the last time at Gettysburg, in Pennsylvania, hundreds of miles away. The two together, the great eastern invasion turned back and the great western fortress fallen in the same 48 hours, are conventionally counted as the military turning point of the entire Civil War, the week the Confederacy lost the initiative for good and never got it back. For Grant, the campaign made his name; the boldness of it, the river crossing, the army cut loose and living off the land, the wedge driven between two enemy armies, put him on the road to general-in-chief of all the Union armies within the year. The key was in the pocket at last.' },
      { pill: '/war-civil-war/eastern/gettysburg', plabel: 'Gettysburg: the other half of the turning point' },
    ],
    meanwhile: { region: 'Gettysburg', title: 'The day after, in Pennsylvania', body: 'Seven hundred miles to the northeast, the other half of the turning point had just finished. On July 3, Lee’s last great assault was shattered on a Pennsylvania ridge, and on July 4 his beaten army began the long retreat back toward Virginia, the same day Pemberton’s men were stacking their arms on the bluffs over the Mississippi. The North got both pieces of news almost together, and the meaning was unmistakable: the Confederacy had reached for victory in the East and gambled on survival in the West, and in a single week it had lost at both. After that July, the war’s outcome was no longer really in doubt. Only its length was.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={VICKSBURG_NARR} id={id} slug="vicksburg" battleName="Vicksburg" theatreId="west" theatreHref="/war-civil-war/western" battleId="w-vicksburg" accent="#1d4ed8" />
}
