'use client'

// Lookout Mountain — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const LOOKOUT_MOUNTAIN_NARR: Record<string, Narr> = {
  'the-army-under-the-mountain': {
    eyebrow: 'Lookout Mountain · The trap and the plan',
    title: 'The Army Under the Mountain',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -86.2, lonMax: -84.4, latMin: 34.4, latMax: 35.6 },
        states: [
          { name: 'Tennessee', tone: 'focus', label: 'TENNESSEE', labelLon: -84.9, labelLat: 34.5 },
          { name: 'Georgia' }, { name: 'Alabama' }, { name: 'North Carolina' }, { name: 'Virginia' },
        ],
        dots: [
          { name: 'Lookout Mountain', date: 'Nov 24, 1863', lat: 35.009, lon: -85.342, heavy: true, anchor: 'middle', dy: 24 },
          { name: 'Brown\'s Ferry', lat: 35.06, lon: -85.398, color: '#8a8175', anchor: 'end' },
          { name: 'Missionary Ridge', lat: 35.033, lon: -85.246, color: '#8a8175', anchor: 'start' },
        ],
      } },



      { p: 'By November 1863, the Union Army of the Cumberland had spent the better part of two months living at the bottom of a trap. Two months earlier, at the Battle of Chickamauga, a Confederate army had beaten that Union force in the worst Federal defeat of the western war and driven it back into the city of Chattanooga, Tennessee, then followed it to the gates and sat down on the heights all around. To the east rose Missionary Ridge; to the southwest loomed Lookout Mountain, a long, steep wall of rock standing some 1,200 feet above the river. From those crests the Confederate Army of Tennessee, under General Braxton Bragg (South), looked straight down on the trapped Federals, on the river that fed them, and on the rail lines that were supposed to keep them alive. They had not so much defeated the Union army as caged it. That cage had a name. It was a siege: an army pinned inside its own lines by an enemy that rings it, cuts its supplies, and waits for it to starve or surrender.' },
      { pill: '/war-civil-war/western/chickamauga', plabel: 'Chickamauga: the defeat that drove the army into the trap' },
      { p: 'Caging it was the point, because of what Chattanooga was. Chattanooga was the great rail gateway to the Deep South, the junction through which an army could drive into Georgia, toward Atlanta and the plantation belt beyond. The Confederacy had broken away from the United States and gone to war for one overriding reason: to protect and extend the enslavement of four million Black people, the system its economy and its social order were built on. By the late autumn of 1863, with the Emancipation Proclamation in force since the first of that year, the Union’s war aim openly included slavery’s destruction. Bragg’s men held these mountains to keep the door to the slaveholding heartland shut. The Federals in the valley below were there to kick it open. The fight that was about to happen on the cliffs above them was, underneath the fog and the romance, a fight for the road into the slave South.' },
      { pill: '/war-civil-war/off-the-battlefield/emancipation', plabel: 'The Emancipation Proclamation: what the war had become by 1863' },
      { p: 'Through October the trapped army had nearly starved. With the Confederates commanding the river and the good roads, supplies had to come in over a long, broken mountain track, and the horses died by the thousands while the men went hungry. Then, in late October, the situation reversed. Major General Ulysses S. Grant, the Union’s rising star in the West, fresh from splitting the Confederacy at Vicksburg, arrived to take overall command on October 23 and almost at once forced open a new supply route, the “Cracker Line,” seizing a river crossing at Brown’s Ferry on October 27. Food and ammunition flowed again. The army that had been slowly strangled was fed, rested, and reinforced, and Grant began planning not to escape the trap but to smash it, to lift the siege by breaking the ring of heights that held it shut.' },
      { pill: '/war-civil-war/western/vicksburg', plabel: 'Vicksburg: the victory that made Grant the West’s rising star' },
      { p: 'The plan was a three-day breakout, not a single battle. Grant meant to crack the ring of heights around the city one piece at a time: Orchard Knob, a low rise out in front of Missionary Ridge, on November 23; Lookout Mountain, the western wall, on November 24; and Missionary Ridge itself, the long eastern crest where Bragg’s main strength sat, on November 25. Lookout Mountain was the middle day. It was never meant to be the decisive blow. It was meant to clear the western peak and set the stage.', i: true },
      { h: 'Hooker Gets the Mountain', eyebrow: 'The assignment' },
      { p: 'The job of taking Lookout Mountain fell to Major General Joseph “Fighting Joe” Hooker (North). Hooker carried a dented reputation: it was he who had commanded the Union army to defeat at Chancellorsville in the spring, and he had been shipped west with two corps to get him out of the way as much as anything. A corps was the army’s largest building block, tens of thousands of men under one general; it broke down into divisions, each division into brigades, each brigade into regiments. The steep mountain was, in part, Hooker’s chance to redeem the year. Grant never meant it to be much of a fight. Grant, prodded by Major General George Thomas (North), ordered Hooker only to demonstrate against the mountain, to threaten it, and take its point only “if his demonstration should develop its practicability.” It was a hedge, not an attack order. Hooker ignored the subtlety. At three o’clock on the morning of November 24 he told Geary to cross Lookout Creek and assault the mountain outright. The fight got big because the man told to feint chose to swing. He commanded an ad-hoc force of roughly 10,000 men, about three divisions, scraped together from three different corps.' },
      { pill: '/war-civil-war/eastern/chancellorsville', plabel: 'Chancellorsville: the defeat that dented Hooker’s name' },
      { p: 'The force was a patchwork. Brigadier General John W. Geary (North) led the column from the XII Corps that would make the main ascent. Brigadier General Peter J. Osterhaus (North), a German-born “Forty-Eighter,” one of the émigrés who fled the failed European revolutions of 1848, brought a division of the XV Corps that had been stranded on the wrong side of the river when the pontoon bridge tore apart, and was simply attached to Hooker for the day. Brigadier General Charles Cruft (North) brought the third piece, drawn from the IV Corps. Three corps, three commanders, one mountain.' },
      { fig: '/war-img/lookout-mountain-overview.png', cap: 'The trap before the climb: Lookout Mountain looms over besieged Chattanooga from the southwest, the Tennessee River wrapping its base at Moccasin Bend.', credit: 'Stuff Happened map' },
      { p: 'Against them, the mountain was held by far fewer men than its grim silhouette suggested, and fewer still than it should have been. The Confederate field commander on Lookout Mountain was Major General Carter L. Stevenson (South), responsible for the whole long northern face with too few troops to cover it. Worse for the defense, Bragg had recently thinned the garrison, pulling a division off the mountain in the days before the attack, on the apparent assumption that the cliffs themselves were defense enough. On paper there were perhaps 8,700 Confederates on Lookout Mountain. At the point where the blow would actually land, on the western and northern slope, there were only a few thousand, by one account around 3,000 men in three brigades, the rest scattered along the ridge and the summit where they could never be brought to bear.' },
      { p: 'The forward defenders, the men who would take the first blow, belonged to the Mississippi brigade of Brigadier General Edward C. Walthall (South). They were about to learn what it meant to hold a mile of cliff-face with too few rifles, sent there to keep shut the door into the country the Confederacy had gone to war to keep enslaved, and left too few to do it by their own commander’s miscalculation. The romance of “the Battle Above the Clouds,” a name not yet coined that morning, rested on a plain and brutal military fact: a steep, supposedly impregnable height, held by far too few men, climbed by a larger force that simply walked up it.' },
    ],
    meanwhile: { region: 'Orchard Knob', title: 'Day one, already done', body: 'The day before Hooker started up the mountain, the breakout had already begun on the far side of the valley. On November 23, Grant pushed the men of the Army of the Cumberland, the same army humiliated at Chickamauga, out of their lines toward Missionary Ridge in what was billed as a reconnaissance (a scouting probe to test the enemy), and they took a low forward hill called Orchard Knob in a brisk, near-bloodless rush, then dug in and held it under Bragg’s nose. It gave Grant a forward observation post looking straight at the ridge, and it gave a beaten army its first taste of going forward instead of back. Lookout Mountain was day two of three. The men climbing the cliffs on November 24 did so knowing the machine was already in motion, and that the real reckoning waited on the eastern ridge the morning after.' },
  },

  'into-the-fog': {
    eyebrow: 'Lookout Mountain · The climb',
    title: 'Across the Creek and Into the Cloud',
    blocks: [
      { p: 'Hooker’s men started up before most of the valley was awake. Around eight o’clock on the morning of November 24, his force began crossing Lookout Creek, the stream running along the western foot of the mountain between Lookout and neighboring Raccoon Mountain. Days of rain had swollen the creek, so it had to be bridged and forded under fire, no small thing with the enemy somewhere on the slope above. Geary’s (North) column swung wide to the south and got across near a place called Wauhatchie, putting his men on the steep western flank of the mountain where the defenders were thinnest. A low band of cloud already clung to the slope, and for once the weather worked for the attackers: it helped screen the crossing from the Confederate pickets (the forward lookouts posted ahead of the main line) watching from above.' },
      { p: 'Then came the climb, and the climb was the real enemy. Geary’s men hauled themselves up the steep western face toward the base of the palisade, the vertical rock cliff-line that crowns Lookout Mountain near its summit, a wall of stone no infantry could storm. The fight was never going to be for the top. The palisade saw to that. The fight would be for the slope and for the narrow shelf of ground below the cliffs. So when Geary’s column reached the base of that rock wall, it did not try to scale it. It wheeled, turning to its left, north and east, and began sweeping across the mountain’s north face, rolling along the slope toward Chattanooga and rolling up the thin Confederate picket line from the flank as it went. To hit a line from the flank is to come at it from the side or the end rather than head-on, where a few defenders cannot face the blow without their whole position unhinging. That is the difference that decided this battle: the mountain was being turned, levered off its position by a blow to its side, not stormed, charged straight up the front into the defenders’ rifles.' },
      { p: 'For Walthall’s (South) outnumbered Mississippians, strung along that mile of slope, it was an impossible morning. Hit from the flank by a force several times their size, they could do little but fight a delaying action, falling back from one rocky position to the next, trading boulders and ground for time, never able to plant themselves long enough to make a real stand. Somewhere on that same ground, climbing from the Union side, a sergeant major of the 96th Illinois (North) hauled himself hand-over-hand up wet rock he could barely see, men slipping and going down all around him in a fog that closed to a few dozen yards, and decided, then or later, that he was on “undoubtedly the roughest battle field of the war.” The cost that day was paid less in casualty lists than in exhaustion and falls.' },
      { p: 'The picture in the popular memory, a heroic charge up a sheer mountain into the teeth of the enemy, is not quite what happened. What happened was a hard, miserable climb and then a long flanking sweep across a slope, against defenders too few and too spread out to hold it. The bravery was real. The ground was genuinely brutal. But the mountain was being turned, not stormed.', i: true },
      { h: 'The Stand at the Cravens House', eyebrow: 'The hinge of the fight' },
      { p: 'The Confederates made their one real stand at the Cravens House, and everything that mattered that day happened there. The Cravens place was a farmhouse on a small flat shelf of ground, a bench, a level ledge cut into the mountainside about two-thirds of the way up the northern slope, below the palisade. It was the strongest position on the mountain, the place the Confederates had built their best works (dug-in trenches and log-and-earth defenses), and it was the natural choke point, the one stretch where the slope leveled enough for men to dig in and stand. As Geary’s sweep rolled toward it through the late morning, the fight tightened down to this one patch of cleared ground in the fog.' },
      { p: 'The bench broke open under a crossfire the defenders could not answer. While Colonel David Ireland’s (North) New Yorkers pressed the front of the Cravens line straight on, Colonel George A. Cobham Jr.’s (North) Pennsylvanians worked onto the higher ground above and poured fire down into the defenders from the flank. Caught between the frontal push and the plunging fire from above, the Confederates at the Cravens House had no good answer. Around one in the afternoon, Brigadier General John C. Moore (South) led an Alabama brigade in a counterattack to throw the Federals back off the bench, and ran straight into that same crossfire, which stopped him cold. The attempt to hold the Cravens House by hitting back had failed.' },
      { fig: '/war-img/lookout-mountain.png', cap: 'The climb and the sweep: Hooker’s columns cross Lookout Creek at the southwest base, climb to the foot of the palisade, then wheel east across the north face to the Cravens House bench above Moccasin Bend.', credit: 'Stuff Happened map' },
      { p: 'And then the fog, which had screened the climb, turned and wrecked the defense. Through the early afternoon the cloud-band thickened on the slope, and by about two o’clock it had closed in so densely that the Confederate command could no longer see to fight. Reinforcing brigades brought down from the summit, under officers named Brown and Pettus, could not be coordinated in the murk; men could not see who was where, or which way the enemy was, or where the line had broken. Outnumbered, out-positioned, and now blind, the defenders were driven off the Cravens bench and back eastward around the shoulder of the mountain. The fighting sputtered out in fog and the coming dark, ammunition running low on both sides, the line dissolving as much into surrender as into retreat. The mountain, for all practical purposes, had been taken, and it had cost remarkably little.' },
    ],
    meanwhile: { region: 'The Cravens House', title: 'The captured, not the killed', body: 'The human weight of Lookout Mountain was not a body count but a column of prisoners. As Walthall’s thin line was flanked and folded in the fog, the men at the broken end of it had nowhere to go but into Union hands: cut off in ones and twos and whole knots at a time, rounded up in a mist where you could not see far enough to run. By the end of the day the Confederates had lost something over 1,250 men, and roughly 1,064 of them were captured or missing, not dead. The defense did not so much die on the mountain as dissolve off the side of it. For a fight remembered as one of the war’s grand spectacles, the dominant human story is a quiet one: hundreds of exhausted, fog-blind men laying down their rifles because the line behind them was already gone.' },
  },

  'the-battle-above-the-clouds': {
    eyebrow: 'Lookout Mountain · The legend and the deflation',
    title: 'The Battle Above the Clouds',
    blocks: [
      { p: 'While the fight crawled across the slope, an army watched it from below and could not quite see it. Down in the valley around Chattanooga, tens of thousands of Union soldiers and officers stood looking up at Lookout Mountain all afternoon. But the cloud-band that had thickened across the slope hid the combat itself. They could see the bare summit standing clear above the cloud; they could hear the rattle and boom of the unseen battle muffled inside it; they simply could not see the men. A whole army stood riveted, watching a mountain smoke and rumble with a fight it could not lay eyes on.' },
      { p: 'The legend got its name in real time. Watching from the captured hill at Orchard Knob, the Union quartermaster general, Brigadier General Montgomery C. Meigs (North), the officer who ran the whole army’s supply, reached for a phrase to describe the thing in the cloud and called it “the Battle Above the Clouds,” and the name stuck before the gun smoke had cleared. The name was fastened onto a fight the namer could only half see, and it would outlive almost every hard fact about the day.' },
      { p: 'The hard facts are stubbornly modest. The Union lost on the order of 671 men, by the most-cited reckoning 89 killed, 471 wounded, and 111 captured or missing, though some accounts put the killed nearer 81 and the total nearer 629. The Confederates lost something over 1,250, of whom the great majority, around 1,064, were prisoners rather than dead. Fewer than two thousand men, all told, became casualties on that mountain. For comparison, the Battle of Chickamauga two months earlier, on the ground these same armies had just left, had cost something like 34,000. The Battle Above the Clouds, measured in blood, was one of the cheaper days of the war.' },
      { pill: '/war-civil-war/western/chickamauga', plabel: 'Chickamauga: the 34,000-casualty fight these armies had just left' },
      { p: 'Geary himself, who had led the climb, wrote home to his wife in the full flush of pride that he had “stormed what was considered the … inaccessible heights of Lookout Mountain,” a feat he was sure would “be celebrated until time shall be no more.” The heights were considered inaccessible, and his men had gone up them. But the largest figure in the campaign saw the day very differently, and said so without mercy.' },
      { fig: '/war-img/cmdr/hooker.jpg', cap: 'Major General Joseph “Fighting Joe” Hooker (North), who turned a feint into the climb that took the mountain.', credit: 'Period photograph · public domain' },
      { p: 'Grant thought the whole thing was overrated. He had not even wanted it fought as a battle, and when he came to write his memoirs years later he flattened the legend in a single famous passage:' },
      { p: '“The battle of Lookout Mountain is one of the romances of the war. There was no such battle and no action even worthy to be called the battle on Lookout Mountain. It is all poetry.”', q: true },
      { p: 'Grant, Personal Memoirs', i: true },
      { p: 'Both things are true at once. The romance is real: the cloud, the unseen battle, the watching army, the name coined on the spot, the flag at dawn still to come. And the deflation is real too: a hard climb, a modest fight, an outnumbered enemy who mostly surrendered, a summit walked up to rather than fought for. It was a genuine Union victory on a genuinely brutal piece of ground, wearing a name several sizes too big for it.', i: true },
    ],
    meanwhile: { region: 'Chattanooga', title: 'The audience makes the myth', body: 'Lookout Mountain became legend partly because it had the largest audience of any fight in the campaign. A battle fought out of sight in a Georgia thicket is just another bad day; a battle fought on a mountain wall, in a cloud, above the upturned faces of an entire army, is a spectacle. The thousands of Union soldiers in the Chattanooga valley were the engine of the myth as much as its witnesses. They watched a peak smoke all afternoon, told and retold what they had seen and not seen, and turned a flanking action into “the Battle Above the Clouds” before the official reports were even written. Grant could call it poetry; he could not call it forgotten. The watching army made sure of that.' },
  },

  'the-flag-at-dawn': {
    eyebrow: 'Lookout Mountain · The empty summit and the hand-off',
    title: 'The Flag at Dawn',
    blocks: [
      { p: 'The mountain was won, in the end, by being abandoned. Through the night of November 24, Bragg (South) made the calculation that decided the whole campaign: he could not hold everything, and what he needed to hold was Missionary Ridge, the long eastern crest where his main army and the climactic fight would be. So he ordered the Lookout Mountain force withdrawn in the darkness, pulling the survivors and the reinforcements alike down off the mountain by the Summertown road, which had stayed open, and east across the valley to the ridge. The night handed the retreat a strange gift: a brilliant full moon, riding high over the mountain, slid into the blackness of a total lunar eclipse in the small hours, the very hours Bragg’s men were filing off the summit. Veterans on both sides would remember it for the rest of their lives. The Confederates, slipping away into a reddened dark, read it as an omen of doom; the Federals below read the same red moon as a sign of the enemy’s ruin. The summit that the country was already turning into a legend was given up under an eclipse, without a shot. By dawn, there was no Confederate army left on Lookout Mountain at all.' },
      { p: 'The most famous image of the battle is, on close inspection, the gentlest. At first light on November 25, a patrol from the 8th Kentucky Infantry (North) climbed to the point of Lookout Mountain, the mountain’s northern tip, the prow that overlooks the river, and found it empty. They walked up the last of the mountain unopposed, climbed to the highest rock, and raised the United States flag on the summit, where the whole army in the valley below could see it. A great cheer rolled up from the thousands who had spent the previous day staring at the cloud. It is one of the indelible pictures of the war: the Stars and Stripes on the point of Lookout Mountain at dawn, a flag raised on a height nobody had fought for, planted by men who had walked, not stormed, to the top. It looked like a conquest. It was a quiet morning walk up an emptied mountain to plant a flag for an audience. The image outran the action, exactly as the name had.' },
      { h: 'On to Missionary Ridge', eyebrow: 'Day three' },
      { p: 'With Lookout Mountain cleared, the campaign turned to its real climax, and Hooker (North) turned with it. His orders for November 25 were to come down off the mountain, push across Lookout Valley, and strike the southern end of Bragg’s line on Missionary Ridge while the rest of Grant’s army hit it head-on. That was the decisive day, the day the siege of Chattanooga would truly be broken. Hooker, as it happened, was delayed crossing the valley and arrived late; the ridge was carried in a famous, half-ordered charge by the Army of the Cumberland, the same men beaten at Chickamauga, surging up the slope on their own momentum. Lookout Mountain cleared the western board and set the table. Missionary Ridge is its own battle.' },
      { pill: '/war-civil-war/western/missionary-ridge', plabel: 'Missionary Ridge: the decisive day this one set up' },
      { p: 'What Lookout Mountain actually bought was less than its legend, but not nothing. Tactically it was a clean, low-cost Union win: Hooker’s force took the western height and over a thousand prisoners for under 700 losses of their own. Strategically it was one piece of lifting the siege, not the decisive blow; it cleared the western peak and the river-and-rail approaches and freed Hooker to swing against the ridge the next day. Some historians, noting that Hooker’s delay kept his men from playing much part at Missionary Ridge, go so far as to call it effectively a drawn battle whose real payoff was the cleared board and the morale jolt, a defensible reading. What is not in doubt is the larger meaning.' },
      { p: 'The larger meaning is the door. Lifting the siege of Chattanooga opened the rail gateway to the Deep South, and through that gateway, in 1864, would march William T. Sherman’s army on the road to Atlanta and, beyond it, the March to the Sea, the campaign that drove a blade through the heart of the slaveholding South and helped break the system the whole war was fought over. So this small fight on a foggy mountain, the one Grant called all poetry, was one of the hinges of that door. The flag the 8th Kentucky planted at dawn flew over an emptied summit. But the valley it overlooked was now the open road into the country the Confederacy had gone to war to keep enslaved. The poetry was overrated. The door it helped open was not.' },
    ],
    meanwhile: { region: 'Missionary Ridge', title: 'The fight Grant actually cared about', body: 'Even as the 8th Kentucky’s flag went up on Lookout Mountain at dawn, Grant’s attention was already four miles east, on the long crest of Missionary Ridge, where Bragg’s whole army had now concentrated and where the campaign would actually be decided. Lookout Mountain had cleared the western wall and looked spectacular doing it; Missionary Ridge was the eastern wall, taller, longer, and crowded with the men Bragg had pulled off the mountain overnight to defend it. November 25 would bring the breakout’s climax there, a frontal assault that, almost by accident, became one of the most astonishing charges of the war. Lookout Mountain’s flag-raising was the curtain-raiser. The decisive fight was on the other ridge, and it belonged to the army that Chickamauga had humiliated, climbing to take its revenge.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={LOOKOUT_MOUNTAIN_NARR} id={id} slug="lookout-mountain" battleName="Lookout Mountain" theatreId="west" theatreHref="/war-civil-war/western" battleId="w-lookout" accent="#1d4ed8" />
}
