// Opus AUTHOR draft of Aristotle's *Nicomachean Ethics* WORK read (Step 2 of
// audits/philosophy-content-pipeline.md, kind = WORK). Written ONLY from
// audits/philosophy-pipeline/nicomachean-work-fact-pack.md (+ cross-ref
// src/app/philosophy/thinker/_reads/aristotle.ts, which it must not contradict).
// This is the work-level deep read below the ARISTOTLE thinker read; the five critic
// gates + the structural gates run against THIS file before it ships. PhiNarr shape
// is identical to republic.ts / symposium.ts; the reader at /philosophy/work/
// nicomachean (route TBD) renders it.
//
// Quote doctrine: every quoted line is W. D. Ross's UNREVISED 1925 public-domain
// translation (MIT Internet Classics Archive), never the 1980/1998 revised Ross and
// never a modern in-copyright translation (Irwin, Crisp, Rowe, Bartlett-Collins,
// Sachs are blacklisted). Ross's exact wordings are honored, including "happiness"
// for eudaimonia (always glossed as flourishing, with the feeling-trap warning),
// "the proud man" for the great-souled man, and "one swallow does not make a summer."
// PARAPHRASE-ONLY items (the Greek transliterations, the geometric/arithmetic
// proportion labels, the "bloom of youth" simile, the exact final sentence) never
// appear inside quotation marks. The Durant line "We are what we repeatedly do…"
// appears ONLY as a debunk, never attributed to Aristotle. Where a figure image is
// referenced it carries a [VERIFY] note for the media gate rather than asserting a URL.

import type { PhiNarr } from '@/components/philosophy-reader'

export const NICOMACHEAN: PhiNarr = {
  "title": "Aristotle's Nicomachean Ethics",
  "throughline": "One question runs the whole course and refuses to let go: what is the good life, what a human being is ultimately *for*, and how a person actually becomes good? Aristotle's answer is not a rule and not a feeling. The good is *flourishing*: living and acting excellently across a whole life. It is reached by training one's character through habit until doing right becomes second nature, by developing the practical judgment that knows what a situation calls for, and, at the very top, in a verdict that startles, by contemplation, the activity of the most god-like part of us. This is not a polished book. It is a set of lecture notes from Aristotle's own school, his working thoughts on how to live, written down for students who already had a decent upbringing and now wanted to know *why*.",
  "hero": {
    "fig": "https://upload.wikimedia.org/wikipedia/commons/7/75/Spangenberg_-_Schule_des_Aristoteles.jpg",
    "cap": "Gustav Spangenberg, *The School of Aristotle* (1880s). Aristotle walks and teaches among his students in the colonnade of the Lyceum, the setting these lecture notes come from. The Ethics is a course on how to live well, addressed to people already trying to.",
    "alt": "A 19th-century painting of Aristotle teaching a group of students gathered along a columned walkway in ancient Athens"
  },
  "hook": [
    "Most books about how to live prescribe what to do. Aristotle's *Nicomachean Ethics* does something stranger and more useful: it asks what a good life even *is*, refuses every easy answer, and then argues that being good is less like knowing the right rules and more like learning an instrument. No one becomes a good person by reading about goodness, any more than a violinist is made by reading about violins. A person becomes good by *doing* good things, over and over, until they become who they are. That is the spine of the whole work, and almost everything famous in it (the golden mean, the function argument, weakness of will, the three kinds of friendship, the contemplative life) is a move inside that one argument, not a detachable highlight.",
    "First, the title, because it sounds like a doctrine and isn't. \"Nicomachean\" is just a family name. The work is almost certainly named for a Nicomachus close to Aristotle, most likely his son (to whom it may have been dedicated, or who may have edited and published it after his death), though his father was also named Nicomachus and a few traditions point there instead. Either way, the title says nothing about the contents; it is a name, not a theme. The book itself, in Greek, is the *Ēthika Nikomacheia*, and \"ethics\" comes from *ēthos*, the word for character, because the heart of the work is the virtues of character: what they are, and how they are built.",
    "Second, what kind of thing this actually is. Aristotle (384–322 BCE) wrote elegant, published books for a general audience, and those are all *lost*. What survived are the opposite: his in-house working texts, the lecture notes and research drafts he used at his school, the Lyceum, in Athens. The *Ethics* is one of these. It was compiled and reworked over his teaching years, the 340s to 320s BCE, never smoothed for publication. So when a passage feels abrupt or compressed, like an outline awaiting its final revision, that is exactly what it is, and far from being a flaw, it is a window onto one of the most systematic minds in history thinking on paper about the oldest question there is. Aristotle even names who the book is *not* for: not the young, and not anyone who lives by their passions, because studying ethics is not for admiring a theory but for *becoming good*, and that, he says, takes more than listening."
  ],
  "brk": {
    "beforeLabel": "To be good is to *know* the good; grasp it, and good conduct follows automatically",
    "afterLabel": "To be good is to *do* good, repeatedly, until it becomes one's character, guided by judgment",
    "paragraphs": [
      "Two big traditions hung over Aristotle when he sat down to think about ethics. The first was his own teacher's. Plato, and the Socrates of Plato's dialogues, had argued that virtue is a kind of *knowledge*: know the Good (the perfect, changeless Form of it, grasped by reason) and one will *be* good, because no one who truly sees what is best would choose worse. On this view, to do wrong is just to be ignorant, so (in the famous Socratic line) no one does wrong willingly. The second tradition was ordinary Greek ethics, which handed down lists of admirable traits (courage, justice, piety) without any unifying account of *why* they are good or *how* a person actually comes to have them. So two questions sat open: what really makes a life go well? And if knowing the good isn't enough, how do people become good, and why do they so often fail, doing the very thing they know is wrong?",
      "Aristotle's break is to build the first systematic, this-worldly ethics, grounded in human nature rather than in a Form off in another realm, and to weld four moves into one structure. He *defines the good functionally*: a thing's good lies in doing its characteristic job well, and the human good is the soul's rational activity, done excellently, over a complete life. He *separates becoming-good from knowing*: good character comes not from being lectured but from *habit*, from practicing the acts until the disposition sticks, \"we become just by doing just acts.\" He gives virtue a *precise shape*: a trained disposition to hit the *mean*, the well-aimed response between too much and too little, calibrated not by a rule but by practical wisdom. And he takes *failure* seriously: weakness of will, which Socrates had said was impossible, Aristotle insists is real, and explains how it happens. He crowns the whole thing with a startling claim, that the highest happiness is contemplation, the activity of the divine spark in us, and then hands the inquiry off to politics, because no one actually becomes good without good laws and a good upbringing.",
      "The concrete claim to hold is this. Before Aristotle, to be good was to *know* the good; a person climbed to a truth and it transformed them. After Aristotle, to be good is to *do* good, repeatedly, until doing it is simply who one is, under the guidance of a judgment that has to be developed, not a formula to be applied. Ethics stops being a branch of metaphysics, a knowledge of perfect originals, and becomes a practical science of becoming good: grounded in function and habit, calibrated by wisdom, honest about how people actually fail. That is what makes the *Ethics* a break rather than a long essay on the virtues."
    ]
  },
  "chapters": [
    {
      "num": 1,
      "title": "What everything aims at: the good and the function argument",
      "epigraph": {
        "text": "\"Every art and every inquiry, and similarly every action and pursuit, is thought to aim at some good; and for this reason the good has rightly been declared to be that at which all things aim.\"",
        "attribution": "— Aristotle, *Nicomachean Ethics* I.1, trans. W. D. Ross"
      },
      "blocks": [
        {
          "p": "The work opens with its master claim, in the very first sentence: every action and pursuit aims at some good. People do things *for* something. And the things they do them for are themselves usually done for something further: take the medicine to get healthy, get healthy to keep working, work to live. Goods line up in chains of means and ends. But Aristotle argues the chains cannot run on forever. If each thing were only ever wanted for the sake of the next, with nothing ever wanted for *itself*, the wanting would be empty, pointed at nothing. So there must be some highest good, something wanted for its own sake and not as a means to anything beyond it. That highest good is what a human life is ultimately for."
        },
        {
          "p": "What is it? Here Aristotle notes a famous agreement-that-isn't. Almost everyone gives the highest good the same *name*. In Ross's translation: \"Verbally there is very general agreement; for both the general run of men and people of superior refinement say that it is happiness, and identify living well and doing well with being happy.\" The Greek word is eudaimonia (yoo-dy-MOH-nee-ah), and there is a translation trap right at the threshold that wrecks the whole theory. Ross renders it \"happiness\" (that is the standard English word, and we'll keep quoting it), but \"happiness\" is dangerously misleading, because in modern usage it means a *feeling*: a pleasant mood, a good day. That is not what Aristotle means. Eudaimonia is an objective, whole-life assessment of whether a person is *living and acting excellently*, flourishing, the way a healthy plant in full bloom is flourishing. Even Ross's gloss carries the right sense: \"living well and doing well.\" It is about what one *does* across a lifetime, not what one feels on a Tuesday. A cheerful fool is not flourishing; a person living with great excellence through real hardship is."
        },
        {
          "p": "Everyone agrees on the *name*, then, and disagrees wildly about what it actually is. Some say the good is pleasure, and Aristotle dismisses that as the life of a grazing animal, fit for cattle, not for a creature that can reason. Some say honor, but honor depends on the people who give it, not on the person honored, so it is too flimsy and external to be the thing a whole life is *for*. Some say wealth, but wealth is plainly just a means: money is wanted in order to get something else with it, so it can't be the final good. Naming pleasure, honor, and wealth and setting each aside, Aristotle needs a method that doesn't just poll opinions. He finds one in a single, slightly startling argument that is the engine of Book I."
        },
        {
          "p": "It is called the function argument, from the Greek *ergon*, a thing's characteristic work or job (we'll use \"function\"). Aristotle's reasoning: for anything that has a distinctive job, being a *good* one means doing that job *well*. A good flute-player plays well; a good eye sees well; the goodness of the thing just *is* the excellent performance of its function. So, he asks, what is the characteristic function of a *human being*? Not nourishment and growth, which plants do. Not sensation and movement, which animals do. The distinctively human thing, the activity that humans and only humans do, is the activity of a soul that follows reason. Put it together and the conclusion follows, in Ross's words: \"if this is the case, human good turns out to be activity of soul in accordance with virtue, and if there are more than one virtue, in accordance with the best and most complete.\""
        },
        {
          "p": "That sentence is the foundation of everything that follows. The human good is not a *feeling* and not a *prize at the end*; it is an *activity*, the soul's rational activity, exercised *well*. \"Virtue\" here translates the Greek *aretē* (uh-REH-tay), and it means *excellence*, doing-the-function-well, not niceness or moral piety; a good flute-player has the aretē of flute-playing. So a good human, like a good flute-player, is one who performs the characteristic human activity excellently. And the flourishing life is the *living* of that excellent activity, not a reward collected for having lived it. The activity itself, done well, *is* the good."
        },
        {
          "p": "Two hard, un-cozy points close out Book I, and Aristotle does not soften either. The first is scope: flourishing is a verdict on a *whole* life, not a good stretch of one. \"For one swallow does not make a summer, nor does one day; and so too one day, or a short time, does not make a man blessed and happy.\" A single fine afternoon, even a fine year, doesn't make a person eudaimōn, any more than one early swallow means the season has turned. The second is vulnerability: flourishing also needs some external goods (friends, a measure of wealth, health, decent luck) as the conditions that let a person *exercise* virtue at all, and that means it is not fully secure. Great misfortune can damage a flourishing life. This is a tougher, more honest picture than \"happiness is a state of mind,\" and it sets up the whole rest of the work. Aristotle ends Book I by splitting virtue into two kinds, virtues of *character* (the moral ones) and virtues of *intellect* (the thinking ones), which becomes the agenda for everything to come."
        }
      ]
    },
    {
      "num": 2,
      "title": "How character is built: habit and the doctrine of the mean",
      "epigraph": {
        "text": "\"we become just by doing just acts, temperate by doing temperate acts, brave by doing brave acts.\"",
        "attribution": "— Aristotle, *Nicomachean Ethics* II.1, trans. W. D. Ross"
      },
      "blocks": [
        {
          "p": "If the good life is excellent rational activity, the practical question is the rest of the work's whole engine: how does a person *get* the virtues of character that this excellent activity requires? Aristotle's answer is the most important, and most misquoted, idea in the book. Moral virtue, he says, comes neither from nature nor from being taught. It comes from *habit*. \"none of the moral virtues arises in us by nature; for nothing that exists by nature can form a habit contrary to its nature.\" A stone, dropped a thousand times, never learns to fall upward; its nature is fixed. If virtue came pre-installed by nature, practice couldn't change it; if it came by teaching, hearing the lesson would be enough. Neither fits. Instead virtue is something we *acquire by practicing it*."
        },
        {
          "p": "Aristotle points at the very word to make the case. In Ross's translation: \"moral virtue comes about as a result of habit, whence also its name (ethike) is one that is formed by a slight variation from the word ethos (habit).\" The Greek for character-virtue, *ēthikē* (the root of our \"ethics\"), is a near-cousin of *ethos*, the word for habit. The name itself signals that good character is a thing done until it sticks. And then the line that states the whole method: \"we become just by doing just acts, temperate by doing temperate acts, brave by doing brave acts.\" No one reasons their way into bravery and then acts bravely; a person acts bravely, in small ways and then larger ones, until bravery is simply the kind of person they have become. Moral education is therefore *training*, not lecturing, which is exactly why Aristotle said children and people ruled by passion aren't ready for this study. The point is to act well, and acting well is a built habit."
        },
        {
          "p": "The single most-quoted line attributed to this book was never in it. It turns up on posters and in graduation speeches: *\"We are what we repeatedly do. Excellence, then, is not an act but a habit.\"* It is stamped \"Aristotle\" everywhere. Aristotle never wrote it. It appears nowhere in his work. The sentence is Will Durant's, from his 1926 popular book *The Story of Philosophy*, where Durant was *summarizing* Aristotle's ethics in his own words and added that neat two-sentence capstone of his own. Over the decades the capstone got snipped loose from Durant's paragraph and re-stamped with Aristotle's name. In fairness, it's a *good* summary; even leading Aristotle scholars grant it captures the idea succinctly. But it is Durant's bumper sticker, not Aristotle's text, and the real text is more careful and more interesting: not \"excellence is a habit\" full stop, but the specific claim that we *become* just, temperate, and brave by *doing* just, temperate, and brave acts. The becoming is what the claim is about."
        },
        {
          "p": "So if virtue isn't a feeling and isn't an inborn capacity, *what is it*? Aristotle works by elimination. It can't be a passion (passions come and go, and we aren't praised or blamed for merely feeling fear), and it can't be a mere capacity (we all have the *capacity* for fear without that making us anything), until, in his words, \"all that remains is that they should be states of character.\" The Greek is *hexis* (HEK-sis), and \"habit\" undersells it: a hexis is not a mindless rut like nail-biting but an *active, settled state*, a trained and stable readiness to respond well, held on purpose, the way a musician holds a trained command of the instrument. Virtue is a hexis, a cultivated disposition of character, built by repeated practice, that reliably inclines a person to respond rightly."
        },
        {
          "p": "Now the doctrine of the mean, the part of the book most often half-remembered and mangled. Here is Aristotle's actual definition, the headline of Book II, in Ross's translation: \"Virtue, then, is a state of character concerned with choice, lying in a mean, i.e. the mean relative to us, this being determined by a rational principle, and by that principle by which the man of practical wisdom would determine it.\" Each virtue of character sits *between* two vices, one of having too much of some feeling or action, one of having too little. Take courage. Too *little* steadiness in the face of danger, fleeing what one shouldn't, is cowardice. Too *much* confidence, charging at everything and fearing nothing one ought to fear, is rashness. Courage is the well-aimed disposition in between: standing firm against the right things, in the right way, at the right time. Generosity works the same way, sitting between stinginess and wild extravagance. The virtue is the mean; the two vices are the overshoot and the undershoot."
        },
        {
          "p": "But Aristotle builds three guards into his own definition that the lazy \"everything in moderation\" version throws away, and getting these wrong is the number-one way this book is misread. *First:* the mean is \"relative to us,\" not an arithmetic midpoint. The right amount of fear for a trained soldier facing a known enemy is not the right amount for a frightened child; the mean is fitted to the person and the situation, never computed as the average of two extremes. *Second:* what does the fitting is \"the man of practical wisdom,\" the cultivated judgment that reads a particular situation and finds the response *in* it. Aristotle's ethics cannot be reduced to a rule precisely because the whole thing depends on a judgment that has to be developed (Chapter 5 is where he names it). *Third*, and most damaging to the cliché: the mean does not apply to everything. Some actions, Aristotle says flatly, have no virtuous middle amount at all. \"some have names that already imply badness, e.g. spite, shamelessness, envy, and in the case of actions adultery, theft, murder… It is not possible, then, ever to be right with regard to them; one must always be wrong.\" There is no \"right amount\" of murder; there is no committing adultery \"in moderation.\" \"Everything in moderation\" is a caricature. Aristotle's real claim is sharper and harder: train the kind of judgment that reliably hits whatever response a situation genuinely calls for, which is often a mean, and is sometimes no amount at all."
        }
      ]
    },
    {
      "num": 3,
      "title": "When it's up to us: choice and responsibility",
      "epigraph": {
        "text": "\"virtue also is in our own power, and so too vice. For where it is in our power to act it is also in our power not to act, and vice versa.\"",
        "attribution": "— Aristotle, *Nicomachean Ethics* III.5, trans. W. D. Ross"
      },
      "blocks": [
        {
          "p": "Before he catalogues the particular virtues, Aristotle stops to settle a question the whole moral enterprise rests on: *when is a person actually responsible* for what they do? Praise, blame, reward, punishment, and moral training all assume that some acts are genuinely up to us and others aren't. So he draws the line. An action is voluntary when, in Ross's words, \"the moving principle is in the agent himself,\" when it comes from the person, who knows what they are doing, with no one forcing their hand. An action is involuntary in two cases: when it's done under *compulsion*, where the source of the action is outside the agent (a stronger person drags them, a storm blows their ship off course), or when it's done through *ignorance* of the relevant particulars (not knowing the cup held poison) and would be regretted once it came to light. Those acts aren't really the agent's own, and we don't hold a person to them the same way."
        },
        {
          "p": "Inside the voluntary sits a narrower and more important thing: choice, in Greek *prohairesis* (pro-HY-reh-sis). Not every voluntary act is chosen in this fuller sense. A choice is a voluntary act arrived at by *deliberation*, by thinking it through beforehand. And Aristotle makes a sharp observation about what deliberation is actually about: \"We deliberate not about ends but about means. For a doctor does not deliberate whether he shall heal, nor an orator whether he shall persuade.\" The doctor doesn't sit weighing whether to cure the patient; that's the settled end, the goal he already has. What he deliberates is *how*: which treatment, in what order. We take our ends as given and reason about the path to them. Choice, then, is deliberate desire for the things in our power, the place where reasoning and wanting meet and become action."
        },
        {
          "p": "The payoff is the hinge the whole ethics rests on, and it is more demanding than it first sounds. Because acting well is built by habit, and the habit is built by voluntary acts, our *characters themselves* end up being something we're responsible for. \"virtue also is in our own power, and so too vice. For where it is in our power to act it is also in our power not to act, and vice versa.\" The unjust person became unjust by doing unjust things, freely, one at a time, until injustice set into a fixed disposition, and at the start, each of those acts was up to him. A hardened character can't be reformed overnight, any more than a sick man can become well by simply wishing it; but the man made himself sick by living carelessly when living otherwise was open to him. This is the ground of moral education and of holding people to account: we are, over time, the authors of the very dispositions we then act from."
        },
        {
          "p": "With responsibility settled, Aristotle turns to the particular virtues, starting with two. Courage (*andreia*, an-DRAY-uh) is a mean concerning fear and confidence, but he notes it's \"more with the things that inspire fear\"; facing down what we dread is the harder, more characteristic half. And he locates true courage in a specific and demanding place: \"He will be called brave who is fearless in face of a noble death, and of all emergencies that involve death; and the emergencies of war are in the highest degree of this kind.\" The model case is the soldier standing firm in battle, where what's at stake is death faced for a noble end. Temperance (*sōphrosynē*, so-fro-SOO-nay) is the other early virtue, and Aristotle narrows it carefully: \"Temperance must be concerned with bodily pleasures, but not all even of these.\" It isn't self-denial across the board, and it isn't about pleasures like music or beautiful sights; it's specifically the right relation to the bodily appetites of touch and taste (food, drink, sex), neither enslaved to them nor (the rare and barely-human extreme) numb to them entirely."
        }
      ]
    },
    {
      "num": 4,
      "title": "The catalogue of character: generosity, anger, and the great-souled man",
      "epigraph": {
        "text": "\"A slow step is thought proper to the proud man, a deep voice, and a level utterance.\"",
        "attribution": "— Aristotle, *Nicomachean Ethics* IV.3, trans. W. D. Ross"
      },
      "blocks": [
        {
          "p": "Book IV walks through the rest of the virtues of character, each one a trained mean between a too-much and a too-little, and the catalogue is worth seeing because it shows how concrete and worldly Aristotle's ethics is: it's about money, anger, conversation, public spending, and self-regard, not abstractions. Start with money on the ordinary scale. Liberality (generosity) is the mean about giving and taking wealth, sitting between *prodigality* (giving wildly, with no sense) and *meanness* (giving too little and grasping too much). The generous person gives the right amounts to the right people at the right times, and gives gladly. Scale it up and there is magnificence, generosity on the grand scale, which Aristotle defines as \"a fitting expenditure involving largeness of scale\": the great public gift, the temple offering, done in good taste, between vulgar showing-off and stingy pettiness."
        },
        {
          "p": "Then anger, which gets one of the cleanest illustrations of how the mean works. The virtue here is good temper, and Aristotle's description shows that the mean is a *calibration*, not a suppression: \"The man who is angry at the right things and with the right people, and, further, as he ought, when he ought, and as long as he ought, is praised.\" Good temper is not the absence of anger, since being unable to get angry at genuine wrongs is its own deficiency; it's anger *aimed correctly*. The excess is the hot-tempered person who flares at everything; the virtue is getting angry at what actually warrants it, and only that. Even being good company turns out to have a shape, and Aristotle gives it three social virtues, each a mean between two ways of getting it wrong. Friendliness is the right way to be pleasant in company, between fawning agreeableness and sour quarrelsomeness. Truthfulness is the mean between boastful self-inflation and the false modesty that undersells itself. And wit sits between the buffoon who'll say anything for a laugh and the humorless bore who can't take a joke at all."
        },
        {
          "p": "And then the strangest entry in the catalogue, which Aristotle treats as a kind of crown of the virtues and which reads very oddly to modern eyes: greatness of soul, in Greek *megalopsychia* (meg-a-lo-PSOO-kee-uh), magnanimity. Ross translates it as \"the proud man,\" and that's the first hurdle, because to us \"pride\" sounds like a vice. Aristotle means something specific and, in his terms, admirable: the man who correctly judges himself worthy of great things and *is* worthy of them. The vice on one side is *vanity*, claiming more than one is worth; the vice on the other is *undue humility*, claiming less than one is worth, selling oneself short. The great-souled man is the one whose high estimate of himself is *accurate*. His chief concern is honor, which Aristotle calls the greatest of the external goods, and he wants honor only from good people and only for genuine merit."
        },
        {
          "p": "The portrait deserves to be given straight, in Aristotle's own register; sanding it down would misrepresent him. The great-souled man moves and speaks a certain way: \"A slow step is thought proper to the proud man, a deep voice, and a level utterance.\" He is glad to do good for others but ashamed to *receive* help, because receiving puts him in the inferior position. He would rather own beautiful and useless things than useful ones, since usefulness suggests need. He doesn't fuss, doesn't marvel at much, doesn't bear grudges, and isn't given to gossip. To a modern reader this can sound less like a saint than like an aloof aristocrat, and the distance is real: this is an ideal rooted in an aristocratic Greek world that prized self-sufficiency and earned honor, and it can read as cold or even snobbish. But it isn't vanity, in Aristotle's scheme, and it isn't \"healthy self-esteem\" in ours either. It's the virtue of *sizing oneself up correctly* when the truth is that one is, in fact, excellent, a possibility egalitarian instincts resist."
        }
      ]
    },
    {
      "num": 5,
      "title": "Justice, and the wisdom that calibrates",
      "epigraph": {
        "text": "\"a true and reasoned state of capacity to act with regard to the things that are good or bad for man.\"",
        "attribution": "— Aristotle, on practical wisdom, *Nicomachean Ethics* VI.5, trans. W. D. Ross"
      },
      "blocks": [
        {
          "p": "Aristotle gives justice a whole Book to itself (Book V, the longest treatment he gives any single virtue) because it's the most complex, and because the one word does two very different jobs. In one sense, *justice* means the whole of virtue *as exercised toward other people*: lawful, decent conduct in the community, every virtue turned outward. In this broad sense, he says, \"in justice is every virtue comprehended\"; justice is \"complete virtue, but not absolutely, but in relation to our neighbour.\" That's universal justice: being a thoroughly good person in one's dealings with others. But there's a narrower sense too, justice as *fairness*, one specific virtue about how goods and burdens get divided up, and it's this particular justice that Aristotle dissects."
        },
        {
          "p": "Particular justice splits in two, and the split still organizes how we think about fairness. One kind, in Ross's words, is \"manifested in distributions of honour or money or the other things that fall to be divided\": this is distributive justice, the fair sharing-out of goods among members of a community. The other \"plays a rectifying part in transactions between man and man\": this is corrective justice, the restoring of balance when one person has wronged another, whether in a voluntary dealing like a sale gone bad or an involuntary one like theft or assault. The first asks how to *divide fairly*; the second asks how to *set right* an imbalance that's already happened."
        },
        {
          "p": "The two work by different mathematics, and Aristotle's core idea is that justice is a kind of *equality*: \"the unjust is unequal, just is equal, as all men suppose it to be,\" and \"The just, then, is a species of the proportionate.\" Distributive justice works by *proportion to merit*: shares are sized to what each person deserves, so equals get equal shares and unequals get proportionally different ones. Corrective justice ignores merit entirely; when a court rights a wrong, it treats the parties as simply equal and just cancels the gain against the loss, restoring the balance that the wrong upset. (The standard names for these two patterns are *geometric* proportion for distribution and *arithmetic* proportion for correction; that's the right reading of Aristotle's argument, stated here in ordinary terms.) And Book V closes on a deep, humane point, equity, *epieikeia* (eh-pee-AY-kay-uh): because laws are written in general terms, they sometimes fit a particular case badly, and the equitable person *corrects* the letter of the law to honor what the law was actually for. \"the equitable, though it is better than one kind of justice, yet is just\": better than the rigid letter, and still genuinely just. It's Aristotle's answer to the rule-bound legalist: sometimes doing right means going past the wording."
        },
        {
          "p": "Books II through V handled the virtues of *character*. Now, in Book VI, Aristotle turns to the part of us that does the *thinking*, because there's an unfinished promise from way back in the definition of the mean. The mean, he'd said, is fixed \"by a rational principle… by which the man of practical wisdom would determine it.\" Book VI is finally where he says *which* rational state that is. He lists five ways the mind reaches truth (art, the know-how of making things; scientific knowledge, demonstrating what must necessarily be so; practical wisdom; philosophic wisdom; and intuitive reason, the grasp of first principles), and two of them carry the weight of the whole ethics."
        },
        {
          "p": "The first is practical wisdom, in Greek *phronesis* (fro-NEE-sis). Aristotle defines it as \"a true and reasoned state of capacity to act with regard to the things that are good or bad for man.\" The definition is about *acting*, not just knowing, and it's about *human* goods, what's good or bad *for us*, which is exactly the excellence that hits the mean in a real situation. Phronesis is the calibrating judgment from Chapter 2, finally named. It can't be reduced to a formula, because situations don't come labeled; it's the cultivated capacity to see what *this* moment actually calls for. His example is the statesman: \"We think Pericles and men like him have practical wisdom, viz. because they can see what is good for themselves and what is good for men in general.\" And here Aristotle ties his whole ethics into a knot that can't be undone: no one can be truly good without practical wisdom, and no one can have practical wisdom without good character. Good character supplies the right ends to aim at; practical wisdom finds the way to hit them. Neither works alone."
        },
        {
          "p": "The second is philosophic wisdom, in Greek *sophia* (so-FEE-uh), and this one points past human affairs entirely. Where practical wisdom is about what's good *for us*, sophia is knowledge of the highest, eternal, unchanging things, the truths that couldn't be otherwise. Aristotle defines it as a combination of two of the five states: \"Wisdom must be intuitive reason combined with scientific knowledge—scientific knowledge of the highest objects which has received as it were its proper completion.\" It is the most finished form of knowing: grasping first principles *and* demonstrating from them, aimed at the loftiest objects there are. Sophia is the seed of the work's final, startling verdict. When Aristotle decides, in Book X, which activity is the very highest happiness, it won't be the practical wisdom of the active citizen. It will be the contemplation that sophia makes possible."
        }
      ]
    },
    {
      "num": 6,
      "title": "Why we fail: weakness of will",
      "epigraph": {
        "text": "\"The incontinent man, knowing that what he does is bad, does it as a result of passion, while the continent man, knowing that his appetites are bad, refuses on account of his rational principle to follow them.\"",
        "attribution": "— Aristotle, *Nicomachean Ethics* VII.1–3, trans. W. D. Ross"
      },
      "blocks": [
        {
          "p": "Most ethical theories before Aristotle had little to say about the most ordinary moral experience there is: knowing perfectly well what one should do, and doing the opposite anyway. The late-night snack resolved to be skipped, the angry text sent in the certainty of regret. The Greek name for it is akrasia (uh-KRAY-zee-uh), usually translated *incontinence* or weakness of will, and Aristotle gives it a long, careful treatment in Book VII, a measure of how seriously he takes the way people actually live. He sets it against its opposite. \"The incontinent man, knowing that what he does is bad, does it as a result of passion, while the continent man, knowing that his appetites are bad, refuses on account of his rational principle to follow them.\" Both feel the bad pull; the difference is who wins. The weak-willed person knows better and yields; the self-controlled person knows better and holds the line."
        },
        {
          "p": "This sounds like plain common sense, but it walks straight into a famous puzzle set by Aristotle's philosophical grandfather. Socrates had denied that weakness of will is even *possible*. His position: \"no one, he said, when he judges acts against what he judges best.\" For Socrates, to truly *know* the good is already to do it (virtue is knowledge), so what looks like weakness must really be *ignorance*: the person who does wrong didn't actually, fully know it was wrong in the moment. Wrongdoing is always a kind of mistake, never a knowing surrender. It's an elegant theory. It's also, Aristotle says bluntly, false to what we can all see: \"this view plainly contradicts the observed facts.\" People manifestly *do* act against what they know. Any theory that has to deny the obvious has gone wrong somewhere."
        },
        {
          "p": "But Aristotle doesn't just wave Socrates off; he diagnoses *what's right* in the Socratic picture and where it breaks. His resolution hinges on the difference between *having* knowledge and *actively using* it. The weak-willed person, he argues, genuinely has the relevant knowledge (\"this kind of thing is bad for me\") but in the heat of the moment is \"not exercising it,\" the way someone asleep, or drunk, or in a rage has knowledge that isn't currently switched on. Appetite drags him toward the particular tempting thing right in front of him, while his general knowledge sits there unused, like a fact he could recite but isn't bringing to bear. So Socrates is *partly* right: fully active, fully present knowledge really can't be overridden, and if the truth were vividly live in the mind at that instant, there would be no yielding. But Socrates was *wrong* that knowledge is always like that. We can possess knowledge we fail, in the moment, to use. That's what weakness of will is: not ignorance, and not knowledge defeated head-on, but knowledge gone quiet while appetite shouts."
        },
        {
          "p": "It's a genuine advance, and worth seeing as one rather than as \"Aristotle disagreed with Socrates.\" Aristotle takes the everyday fact of weakness seriously where Socrates had explained it away, and he dissolves the puzzle without either denying that people fail or pretending failure is just confusion. Pleasure belongs to the same discussion, because the appetites that overpower the weak-willed person are appetites for pleasure, so Book VII opens Aristotle's account of it, against thinkers who'd called all pleasure bad. His view is balanced: pleasure is, in a way, a good, and some pleasures are genuinely worth choosing; it's only bodily pleasures pursued to *excess* that are the problem. He'll come back to pleasure for the full account in the final book, where it turns out to matter for what the best life actually feels like."
        }
      ]
    },
    {
      "num": 7,
      "title": "The friend as another self",
      "epigraph": {
        "text": "\"without friends no one would choose to live, though he had all other goods.\"",
        "attribution": "— Aristotle, *Nicomachean Ethics* VIII.1, trans. W. D. Ross"
      },
      "blocks": [
        {
          "p": "Aristotle gives friendship *two whole books* (VIII and IX, the single longest stretch of the *Ethics*), and the sheer length is the point: for Aristotle, friendship isn't a pleasant extra on top of the good life, it's close to the heart of it. The Greek word is *philia* (fih-LEE-uh), and it's broader than our \"friendship,\" covering the bonds between family, between fellow-citizens, between any people joined by mutual goodwill. He opens by ranking it near the top of human goods: friendship \"is a virtue or implies virtue, and is besides most necessary with a view to living,\" and then the line that says it plainest: \"without friends no one would choose to live, though he had all other goods.\" Give a person everything else and take away friends, Aristotle thinks, and they would not choose that life. We are not built to flourish alone."
        },
        {
          "p": "The structural core is the three kinds of friendship, sorted by what one actually loves the other person *for*. \"There are therefore three kinds of friendship, equal in number to the things that are lovable,\" and the three lovable things are the *useful*, the *pleasant*, and the *good*. A friendship of utility is built on benefit: business partners, useful contacts, allies. The two value each other for what each gets out of the relationship, and Aristotle notes these dissolve the moment the usefulness ends. A friendship of pleasure is built on enjoyment: the people who are fun to be around, common (he says) among the young, who live by their feelings, and these fade when the fun does, when tastes change and the pleasure runs out. Both are real friendships, but both are, in his phrase, \"easily dissolved,\" because what's loved isn't really the *person*; it's the benefit or the pleasure they happen to provide."
        },
        {
          "p": "Then the real thing, the kind the other two are only shadows of: perfect friendship. \"Perfect friendship is the friendship of men who are good, and alike in virtue.\" Here the friend is loved *for who they are*, for their character, and wished well for their own sake, not for any benefit. And because it's grounded in their goodness rather than in shifting benefits or pleasures, it lasts: \"their friendship lasts as long as they are good—and goodness is an enduring thing.\" This kind is rare, slow to form, and possible only between good people, because only good people have the stable character that can anchor it. It's also, Aristotle notes, the kind possible with only a few people: deep friendship takes time and shared life, and simply can't be sustained toward many at once."
        },
        {
          "p": "Book IX deepens it into something almost metaphysical with a single phrase: a true friend, Aristotle says, is *\"another self.\"* The good person relates to a true friend the way they relate, rightly, to themselves: wishing them good for their own sake, sharing their joys and griefs as their own, wanting to spend their life with them. This even reshapes the loaded idea of *self-love*: the good person *should* be a lover of self, Aristotle argues, but in the right way, not the grasping self-love that hoards money and pleasure, but the kind that assigns oneself the noblest actions. Loving a good friend turns out to be an extension of loving the good in oneself. And it answers a hard question he raises directly: does the supremely happy, self-sufficient person even *need* friends? Yes: \"the supremely happy man will need friends of this sort, since his purpose is to contemplate worthy actions and actions that are his own, and the actions of a good man who is his friend have both these qualities.\" We see our own good lives more fully by sharing them; even the happiest person flourishes more with a friend than without."
        }
      ]
    },
    {
      "num": 8,
      "title": "The highest happiness: the contemplative life",
      "epigraph": {
        "text": "\"Happiness, therefore, must be some form of contemplation.\"",
        "attribution": "— Aristotle, *Nicomachean Ethics* X.8, trans. W. D. Ross"
      },
      "blocks": [
        {
          "p": "The final book is a two-part climax, and it begins by going back to pleasure for the full account it had postponed. Some thinkers said pleasure *is* the good; others said pleasure is simply bad. Aristotle threads between them with a careful idea: pleasure is neither the good itself nor an evil; it *\"completes the activity.\"* Pleasure isn't a separate thing to be chased; it supervenes *on* good activity, crowning it, the way (in his image) the bloom of health crowns those in the flower of youth. Do an activity well, and a proper pleasure naturally comes with it and completes it. Which means the best pleasures are the ones that come with the best activities. So the question \"what is the most pleasant life?\" collapses into the question that's run the whole work: *what is the best activity?* And that sets up the verdict the entire *Ethics* has been climbing toward."
        },
        {
          "p": "The answer lands like a surprise even though Book VI prepared it: the highest happiness is contemplation, in Greek *theoria* (thay-oh-REE-uh), the activity of philosophic wisdom, the mind engaged in understanding the highest, eternal truths for their own sake. Why this, above the active life of the virtuous citizen exercising courage and justice and practical wisdom? Aristotle stacks up reasons. Contemplation is the activity of the *best thing in us*, reason, our highest faculty. Its objects are the highest and most knowable things there are. It's the most *continuous* activity we can sustain; thinking can go on for longer than almost anything else. It's the most *self-sufficient*: the just person needs other people to be just toward, but the wise person can contemplate alone. And it alone is loved purely for itself: \"this activity alone would seem to be loved for its own sake; for nothing arises from it apart from the contemplating.\" Every other good activity aims at some result beyond it; contemplation aims at nothing but more of itself."
        },
        {
          "p": "Such a life, he admits, is almost *too high* for a human being; we live it not insofar as we're human but insofar as something divine is in us. And rather than back away from that, he leans in: \"But we must not follow those who advise us, being men, to think of human things, and, being mortal, of mortal things, but must, so far as we can, make ourselves immortal, and strain every nerve to live in accordance with the best thing in us.\" Don't settle for merely human horizons, he says; reach, as far as a mortal can, toward the divine activity of pure understanding, and live by the highest part of yourself. From all of which the conclusion follows: \"Happiness, therefore, must be some form of contemplation.\""
        },
        {
          "p": "This verdict creates a real tension, and Aristotle himself doesn't fully resolve it. For nine books he built a rich, engaged, practical picture of the good life: the trained virtues of character, justice in the community, the deep necessity of friends, the active citizen using practical wisdom in the thick of human affairs. And then Book X seems to crown a *solitary*, almost god-like, theoretical activity above all of it, calling the life of moral virtue happy only \"in a secondary degree\": \"in a secondary degree the life in accordance with the other kind of virtue is happy.\" Scholars have argued ever since over how to take this: whether contemplation is meant to be the *best part* of a full, virtuous, engaged life, or the *one thing* that happiness really comes down to, with everything else demoted. It's a genuine puzzle, and the honest reading holds both halves: Aristotle does crown contemplation, *and* he never tells us to abandon the virtues or the friends, since contemplation needs a stable character and external goods to be livable at all. The tension is in the text, not a reader's mistake."
        },
        {
          "p": "And then the *Ethics* ends by refusing to end; it opens a door instead. Knowing what the good life is, Aristotle points out, is not the same as becoming able to live it, and most people will never be argued into virtue; they need to be *shaped* into it, from childhood, by good habits and good laws. Which means the study of ethics is incomplete on its own. To actually produce good people, the question becomes how a community raises and governs them: what laws, what upbringing, what kind of city. So the inquiry has to turn toward constitutions and legislation, to complete what Aristotle calls the philosophy of human nature. The book closes mid-stride, handing off directly to his *Politics*. It's a fitting last move for the most down-to-earth of the great ethical works: the question of how to be good was never really separable from the question of how to live *together*. A person becomes good inside a good community, or not at all."
        }
      ]
    }
  ]
}
