'use client'

// THEME section — Fort Pillow & the Guerrilla War (Off the Battlefield, kind=theme). Built through
// the war content pipeline (fact pack → author(Opus) → five gates [fact-check +
// storytelling + comprehensiveness + clarity + Lost Cause/framing] → revise → images).
// Source + gate records: audits/war-pipeline/guerrilla-war-*.md. Green accent; no stat
// block, no map. 'use client' is REQUIRED (reads ACCENTS from a client module).
// GENERATED from guerrilla-war-final.md by scripts/_build-war-themes.mjs — do not hand-edit
// the prose here; edit the final.md and rebuild.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: `The war with no front line`,
    title: `Fort Pillow & the Guerrilla War`,
    blocks: [
      { p: `There is a clean version of the Civil War, and you already know it: two great armies in matching uniforms, lined up across a field, fighting by rules both sides mostly honored, taking prisoners when a man threw down his musket. That war was real. But it was not the whole war, and at the edges of it there was another war entirely: dirtier, more personal, and a great deal more savage, fought by men in no uniform at all, where the line between a soldier and a murderer could vanish completely, and where the most ordinary act of war (laying down your arms to surrender) could get you killed where you knelt.` },
      { p: `Two wars ran in parallel. One was the **guerrilla war** (irregular fighting carried on by small bands or lone gunmen rather than organized armies, relying on ambush, raid, and terror instead of pitched battle), which raged hardest in the border country: Missouri, Kansas, Kentucky, Tennessee, and the mountains of what became West Virginia, where Union and Confederate sympathizers were not separated by a battle line but lived on the same roads, and simply started killing each other. The other was **no quarter** (the old battlefield term for refusing to let a beaten enemy surrender and live; killing the men who lay down their arms instead of taking them prisoner), turned most often and most deliberately against Black soldiers, and burned into the nation's memory at a bluff above the Mississippi River called Fort Pillow.` },
      { p: `The ugliness ran both ways. Confederate guerrillas committed the war's most infamous massacres, but the Union's reprisals could be collective and merciless too. Start with what this kind of war actually *was*, because the words for it (bushwhacker, jayhawker, partisan ranger) are not interchangeable, and the differences are the whole story.` },
      { h: `A war with no uniforms and no rules`, eyebrow: `Pressure` },
      { p: `Historians sort the war's irregular fighting into three rough kinds, and each kind was judged very differently for it.` },
      { p: `The first kind was the **bushwhackers**: the mass, decentralized guerrilla violence of the border states, where most fighters wore no uniform, held no formal military commission, and answered to no chain of command. A bushwhacker was, in plain terms, a man with a gun and a grievance who ambushed his enemies from the brush ("bushwhack" meant exactly that: to attack from hiding) and then melted back into the civilian population he came from. The Missouri guerrillas, William Quantrill, "Bloody Bill" Anderson, the young James brothers, were bushwhackers. They were the purest form of the war-with-no-rules.` },
      { p: `The second kind was **partisan warfare**: smaller bands that were *organized*, that operated under some real conventional-army control to raid behind enemy lines, and that the Confederacy tried, for a while, to make legitimate. The men who did this best were the **partisan rangers** (irregulars who, unlike the bushwhackers, wore the uniform, held commissions, and reported up a chain of command), and their type case was John Mosby. A partisan ranger and a bushwhacker might do similar things (raid, ambush, hit and run) but one did it as a recognized soldier and the other did it as an armed civilian, and that difference decided whether the enemy treated you as a prisoner or hanged you as a criminal.` },
      { p: `The third kind barely belongs among irregulars at all, but it matters for one specific reason: **raiding warfare**, the deep cavalry raids run by *regular* Confederate generals against railroads, supply depots, and bridges. (**Cavalry** means soldiers who fight mounted, on horseback.) Nathan Bedford Forrest and John Hunt Morgan were raiding generals. It is crucial to understand, because the man at the center of Fort Pillow was not a bushwhacker. He was a commissioned major general of the regular Confederate army. The massacre was not committed by outlaws in the woods. It was committed by uniformed soldiers under a general's command, which is exactly what makes it so hard to explain away.` },
      { p: `Now the two sides of the border war, because they had their own names. On the Confederate side were the bushwhackers. On the Union side were the **jayhawkers**: pro-Union irregulars, a term born in the pre-war "Bleeding Kansas" troubles, who raided across the line into Missouri, burning slaveholders' farms and plantations. Their leaders were men like Charles "Doc" Jennison and James Montgomery, and behind them, politically, stood Kansas Senator James H. Lane; a related Union irregular band on the Kansas side went by the **"Red Legs"** (a distinct pro-Union Kansas raiding band, said to be named for the red-leather leggings some wore, notorious for especially savage raids into Missouri, not simply another word for jayhawkers). Bushwhackers and jayhawkers were mirror images: each was an un-uniformed band convinced it was defending its homes against the savages on the other side, and each gave the other all the proof it needed.` },
      { p: `Two pieces of paper tried to bring order to this, and it is worth knowing both. The first was the Confederacy's attempt to harness the irregulars: the **Partisan Ranger Act**, passed by the Confederate Congress on April 21, 1862, which let the South recruit irregulars into formal service and gave sanctioned partisan units a legal standing. It did not last. The regular-army officers came to hate it, Robert E. Lee (the South's top general) among the loudest, because they saw partisan bands as undisciplined, plunder-prone, and corrosive of the regular army's order, drawing good men away into freelance war. So the Confederate Congress **repealed it on February 17, 1864**, less than two years on. Only two partisan commands were exempted and allowed to keep operating: Mosby's Rangers and McNeill's Rangers. The South had tried to legitimize the irregular war and then, deciding it did more harm than good, mostly took the legitimacy back.` },
      { p: `The second piece of paper was the Union's, and it cut the other way. On April 24, 1863, Lincoln issued **General Orders No. 100**: the **Lieber Code**, written by Francis Lieber (a German-born lawyer and veteran of the Napoleonic wars, then teaching in New York), 157 articles laying out the laws of land warfare for the U.S. Army. Much of it was humane and forward-looking. But one thing in it was lethal: it denied **prisoner-of-war** protection (the status, under the rules both sides were meant to honor, that kept a captured enemy soldier alive and decently treated) to guerrillas. A captured bushwhacker, the Code reasoned, was not a lawful soldier at all. He wore no uniform, answered to no chain of command, and could not himself take prisoners, and so he was an "armed prowler," not a protected combatant. In plain effect, the law made a captured guerrilla legally killable. A lawyer in New York, writing rules for a civilized army, had drafted the paper that licensed the no-quarter spiral on the border, and the men in the Missouri brush would do the rest.` },
      { p: `So why here? Why did this kind of war erupt in Missouri and Kansas and Kentucky and the Virginia and Tennessee mountains, and not in the heart of Georgia or the cotton South? Because these were the places where loyalty was mixed at the level of the neighborhood. There was no front line because the two sides were not on two sides of anything: they were the family down the road, the men at the next farm. Conventional armies marched through and marched on, but daily control of the back roads belonged to whoever held the local woods that night. And Missouri's case was the worst of all, because Missouri did not have to invent its hatreds in 1861. It inherited them, fully formed, from the decade before.` },
      { h: `Fort Pillow: surrender by the color of your skin`, eyebrow: `Turning point` },
      { fig: '/war-img/guerrilla-war-forrest.jpg', cap: `Major General Nathan Bedford Forrest — a Memphis slave trader before the war, a commissioned Confederate cavalry general during it. The man who commanded at Fort Pillow was no outlaw in the brush; he was regular army, which is exactly what makes the killing there so hard to explain away. A witness from his own command said Forrest gave the order to shoot the surrendering men down; Forrest denied it; the question has never closed. What is not in question is what he became after the war.`, credit: `Unidentified photographer · photograph · before 1877 · Wikimedia Commons · public domain` },
      { p: `On the afternoon of April 12, 1864, on a bluff above the Mississippi River in Lauderdale County, Tennessee, about 40 miles (64 km) north of Memphis, the irregular war's defining cruelty was committed by a regular army, in broad daylight, and the nation got its emblem of what no quarter against Black men looked like. The place was **Fort Pillow.**` },
      { p: `Set the scene. The fort sat on high ground over the river and was held by a Union **garrison** (the body of troops stationed to defend a fixed position) of roughly 600 men, and that garrison's makeup is the whole story of the day. About half of it was Black: a battalion of the 6th U.S. Colored Heavy Artillery and a section of the 2nd U.S. Colored Light Artillery, men of the **United States Colored Troops** (the federal regiments of Black soldiers, most of them recently escaped or freed from slavery). The other half was white: the 13th (West) Tennessee Cavalry, Unionist Tennesseans, many of them former Confederates who had switched sides, which made them, in the eyes of the attackers, traitors. So the men inside the fort were, to the Confederates closing in around it, the two most hated kinds of enemy the war produced: armed Black men, and white Southerners who had turned their coats. Command of the garrison fell first to Major Lionel F. Booth, and when a sharpshooter killed Booth early in the fighting, it passed to Major William F. Bradford, who led the white Tennessee battalion.` },
      { p: `The Confederate force surrounding them, roughly 1,500 to 2,500 cavalry (sources vary), was commanded by Major General **Nathan Bedford Forrest**, one of the war's most feared cavalry raiders, a self-made Memphis slave trader and planter before the war who had risen to general on raw fighting ability. By mid-afternoon Forrest's men had taken the high ground around the fort, and the garrison was effectively trapped with the river at its back. At about 3:30 in the afternoon Forrest sent in a demand for surrender, giving Bradford 20 minutes to answer. The demand, as it comes down to us, promised that the garrison would be **treated as prisoners of war**, but warned that if the offer was refused, Forrest "cannot be responsible for the fate of your command." [VERIFY exact wording against the *Official Records* before quoting verbatim.] That phrase (*cannot be responsible*) would sit at the center of everything argued afterward. Bradford refused. The Confederates stormed the fort.` },
      { p: `The attackers overran the works quickly, and what happened next is the reason the word "Fort Pillow" still carries weight a century and a half later. The fort sat with its back to a bluff and the Mississippi below it; there was nowhere for the garrison to run. When the resistance broke, men threw down their muskets and raised their hands on open ground above the water, and the killing did not stop. By the testimony of the survivors, men who tried to surrender were shot and bayoneted anyway (Black soldiers above all), some on the slope down to the river, some in the water itself, and some accounts have men burned or buried alive. Survivors said the Confederates came on shouting "No quarter! No quarter!" Major Bradford himself appears to have been killed *after* he surrendered.` },
      { p: `Now the numbers, because at Fort Pillow the numbers are not background: they are the proof. Of the roughly 600 defenders, close to 300 were killed. That alone is a staggering share of a garrison; battles did not usually kill half the losing side. But the damning figure is how those deaths split by race. About 70 percent of the white defenders survived the day. Only about 35 percent of the Black defenders did, half the survival rate of the men fighting beside them. Put it another way: of the Black soldiers, only around one in five was taken prisoner; of the white soldiers, around three in five. And set against the Union's nearly 300 dead, Forrest lost about 14 men killed. An assault that overruns a fort and kills nearly 300 defenders while losing 14 of its own has not fought a battle in the ordinary sense. A battle that kills two-thirds of one race of defenders and a third of the other has selected its dead by skin. The asymmetry *is* the massacre. You do not need a confession to read it; the arithmetic confesses for everyone.` },
      { p: `The North read it immediately. The **Joint Committee on the Conduct of the War** (Congress's standing oversight committee, run by hard-line Republicans) sent investigators almost at once, led by Senator Benjamin Wade of Ohio and Representative Daniel Gooch of Massachusetts. They interviewed survivors and witnesses and, in a report published in May 1864, branded the event a massacre: "a massacre without parallel." Be clear-eyed about that report, though, the way the honest histories are: Wade and Gooch were partisans with a political stake, and their framing was wartime propaganda as much as forensics, written to inflame the North as well as to record the truth. The committee's *rhetoric* should be read as a political document. But the committee's *core finding* does not depend on its rhetoric at all, because the casualty figures (gathered independently, confirmed by the killing's own arithmetic) establish the massacre on their own. A propagandist can exaggerate a true thing. The true thing here was a massacre.` },
      { p: `One witness matters more than the whole committee, because of who he was. Among Forrest's own troopers was a Confederate sergeant named Achilles V. Clark, of the 20th Tennessee Cavalry, who two days after the fight sat down and wrote home to his sisters. This is not a Northern propagandist describing the enemy. This is a Confederate describing what his own side did, and his letter is the single hardest piece of evidence in the whole affair, so it has to be quoted in full, not in the comfortable half:` },
      { p: `"The slaughter was awful. Words cannot describe the scene. The poor deluded negroes would run up to our men, fall upon their knees and with uplifted hands scream for mercy but they were ordered to their feet and then shot down. I with several others tried to stop the butchery and at one time had partially succeeded but Gen. Forrest ordered them shot down like dogs and the carnage continued."`, q: true },
      { p: `That last sentence is the most explosive line in the entire Fort Pillow record, and earlier tellings of this story have a habit of quoting Clark up to "shot down" and stopping. A Confederate soldier on the field, writing privately to his own family days afterward, said in plain words that Forrest gave the order. You cannot cite Clark as your best evidence and then bury his most damning sentence.` },
      { p: `So did Forrest order it? Clark's letter says he did. But a single eyewitness, even one as unimpeachable in motive as Clark, is not the same as a settled fact, and historians have argued the question for 150 years and still divide. Forrest's defenders point out that Clark was one man on a chaotic field, that no written order survives, that Forrest always denied directing a massacre, and that the killing may have been his men's rage breaking loose after a refused surrender: fury at armed Black soldiers and turncoat white Tennesseans boiling over without a directive. His critics answer that an eyewitness from his *own* command, with no reason to lie to his sisters, named him giving the kill order, and that Forrest was on the field, in command, and did little visible to stop it. The honest reading: an eyewitness Confederate soldier attributed the order to Forrest; Forrest denied ordering a massacre; and historians remain split on his *personal* premeditation. What is *not* split, and never has been, is that a massacre occurred. The casualty asymmetry settles that beyond argument, and the evidence leaves Forrest's premeditation exactly where it has always sat: alleged by a witness on his own side, denied by the man himself, and unproven to the standard history demands.` },
      { p: `Forrest's own words afterward are fair to weigh on that question. In his official report he wrote that "the river was dyed with the blood of the slaughtered for two hundred yards," and added a sentence that tells you how he understood the day:` },
      { p: `"It is hoped that these facts will demonstrate to the Northern people that negro soldiers cannot cope with Southerners."`, q: true },
      { p: `(The lowercase spelling is the period original, reproduced as written, not an editorial choice.) That line does not prove a premeditated order. But it shows a commander who understood the slaughter of Black soldiers as a *demonstration*: a message to the North about what arming Black men would cost them, and who was content to send that message in his own dispatch. Ulysses S. Grant, recalling Forrest's report years later in his memoirs, noted that Forrest had quoted the "river was dyed" line himself and then "subsequently … made a report in which he left out the part which shocks humanity to read." Even Forrest, it seems, came to understand what he had set down.` },
      { p: `For the men of the USCT, Fort Pillow became something beyond an atrocity: it became a battle cry, **"Remember Fort Pillow!"**, screamed by Black regiments for the rest of the war as a vow to give no quarter to an enemy that had given none. The man who commanded at Fort Pillow did not vanish into history when the war ended. He became the first national face of the terror that followed it.` },
      { h: `The general becomes the Grand Wizard`, eyebrow: `Consequence` },
      { p: `First, what the thing actually was, because the name has been worn smooth by a century of use. The **Ku Klux Klan** was a white-supremacist terror organization, a secret society that used beatings, arson, whippings, and murder to terrorize freedpeople and their white allies, drive Black Southerners away from the polls, and strangle Black freedom in its cradle. It is sometimes said to have begun almost as a fraternity, a circle of bored ex-soldiers, before it curdled into something else; but what it curdled into, and what made it matter, was organized racial terror. It was founded by six Confederate veterans in Pulaski, Tennessee, in 1866 (some accounts date the very first meeting to December 24, 1865, but 1866 is the year the thing took shape). **Nathan Bedford Forrest joined in the fall of 1866, and in the spring of 1867 he was elected its first Grand Wizard** (its supreme national leader) at a gathering traditionally placed at the Maxwell House Hotel in Nashville.` },
      { p: `Under Forrest's tenure the Klan used violence and the threat of it to break Black political participation across the postwar South, terrorizing freedpeople and their white allies away from the polls, with the campaign sharpest around the 1868 elections. How tightly Forrest actually controlled the scattered local "dens" is debated (the Klan was always more a franchise of local terror than a disciplined army taking orders from one man) but he was its first national figurehead, and that is not in dispute. In 1869, expressing disgust at the Klan's uncontrolled violence and lack of discipline, Forrest issued a letter ordering it dissolved and its costumes destroyed, and withdrew from it. Sit for a second with that last detail: a general whose troopers had murdered surrendering prisoners on a riverbank, and who may have ordered it, now recoiling years later at *other* men's uncontrolled violence. (Late in life he made some public gestures of conciliation toward Black audiences; the record there is contested, and it would be dishonest to inflate them into a change of heart.)` },
      { p: `The man who commanded the army that committed the war's emblematic racial massacre became, within three years of Appomattox (where Robert E. Lee surrendered to Grant in April 1865, effectively ending the war), the first Grand Wizard of the nation's first organized engine of racial terror. The premeditation question at Fort Pillow stays open: the evidence genuinely does not close it. The Klan role does not stay open; it is simply a fact. Whatever Forrest did or did not order on that bluff in 1864, the war's worst day for Black soldiers and the postwar's first face of racial terror were the same man, and the line runs from a Tennessee riverbank to a Nashville hotel.` },
      { h: `Bleeding Kansas never stopped bleeding`, eyebrow: `Pressure` },
      { fig: '/war-img/guerrilla-war-quantrill.jpg', cap: `William Clarke Quantrill — an Ohio-born schoolteacher before the border remade him into the most infamous bushwhacker of the Missouri–Kansas war. By the war's start he had traded the schoolhouse for horse theft and then for a band of un-uniformed pro-Confederate guerrillas accountable to no one but himself. Cole Younger, "Bloody Bill" Anderson, and the teenage James brothers all rode under him.`, credit: `Kansas Historical Society · photograph · between 1861 and 1865 · Wikimedia Commons · public domain` },
      { p: `In the border country of Missouri and Kansas, the irregular war reached its purest and ugliest form, because there it had been going since before the war even started.` },
      { p: `The Missouri–Kansas guerrilla war did not begin in 1861. It inherited, fully loaded, the hatreds of **"Bleeding Kansas"** (the years of pre-war violence, roughly 1854 to 1859, over the one question that drove everything: whether Kansas would enter the Union as a slave state or a free one). By the time the war proper began, the Kansas–Missouri line already had armed free-state "jayhawkers" on one side and pro-slavery **"border ruffians"** (pro-slavery Missourians who crossed into Kansas to raid, intimidate, and stuff ballot boxes for the slave-state cause) on the other, men who had been raiding and killing each other for years. The war did not create them. It just handed them flags and told them it was now official. And underneath the personal scores, the thing the Missouri side was defending was never abstract: it was a slaveholding society, and the reason Lawrence was the obvious target was that Lawrence was the headquarters of the people trying to keep slavery out of Kansas.` },
      { p: `Into that ready-made hatred stepped the man who became its most infamous figure. **William Clarke Quantrill** was born in Canal Dover, Ohio, in 1837, and there was nothing in his beginnings to mark him. He was a schoolteacher in Ohio and Illinois, a literate young man from a free state with no obvious stake in Southern slavery. Then he drifted west to Kansas in 1857, and the border remade him. By 1860, living near Lawrence, he had slid out of the schoolhouse and into theft, charged with stealing horses, mixing with both sides of the border feud and trusted by neither, until he came down hard on the pro-slavery side. When the war came he formed his own band of pro-Confederate guerrillas, **Quantrill's Raiders**, and raided Union-leaning towns and farms across the border country. The schoolteacher had become a man who organized other men to kill, and the border, which had taught him that, would be where he proved it. Over time his band drew in some names the country would not forget: Cole Younger, William T. "Bloody Bill" Anderson, and a pair of farm boys named Frank and Jesse James, the men who would become America's most famous outlaws. Quantrill's Raiders were bushwhackers in the fullest sense: un-uniformed, uncommissioned, accountable to no one but Quantrill, and increasingly to nothing but their own appetite for revenge.` },
      { p: `That appetite found its target in a town named Lawrence.` },
      { h: `The Lawrence Massacre`, eyebrow: `Turning point` },
      { fig: '/war-img/guerrilla-war-lawrence-ruins.jpg', cap: `The ruins of Lawrence, Kansas, sketched by a correspondent in the weeks after Quantrill's raiders rode in at dawn on August 21, 1863 and murdered somewhere between 150 and 190 men and boys — nearly all of them unarmed civilians, many shot on their own doorsteps in front of their families. About a quarter of the town was burned. The raiders lost exactly one man.`, credit: `Unsigned correspondent's sketch · wood engraving · 1863 · *Harper's Weekly* (via Library of Congress / Wikimedia Commons, LCCN 2003663009) · public domain` },
      { p: `Before dawn on August 21, 1863, Lawrence, Kansas, was as quiet as any prairie town at the end of summer: a few hundred frame houses and brick storefronts along the Kansas River, the people asleep, a company of Black recruits and a clutch of young white enlistees camped near the edge of town, not one of them expecting that the worst raid of the border war was already riding toward them in the dark. Lawrence was the obvious target and had been for years. It was the abolitionist heart of the territory, the base from which the jayhawkers launched their raids into Missouri, and the symbol of everything the bushwhackers hated. Missourians had old scores to settle there, among them the 1861 sacking of Osceola, Missouri, by jayhawkers associated with Senator James H. Lane, a raid that had burned a Missouri town and that Quantrill's men had not forgotten.` },
      { p: `And then, eight days before the raid, came the spark that turned an old grudge into a slaughter. Union authorities in Kansas City had been jailing the female relatives of known bushwhackers, holding them in a building as a way to pressure the men. On **August 13, 1863, that building collapsed**, killing four of the young women inside. One of the dead was about fifteen years old: Josephine Anderson, a sister of "Bloody Bill" Anderson. The bushwhackers were certain the collapse had been deliberate, a murder dressed up as an accident. Whether it was or not, the effect was the same: it lit a rage in Anderson and the others that had somewhere, now, to go.` },
      { p: `At dawn on **August 21, 1863**, Quantrill led roughly 400 to 450 raiders into Lawrence. What followed was not a battle; there was almost no one to fight. They moved through the town and murdered **somewhere between about 150 and 190 men and boys** (sources put the toll across that range), nearly all of them unarmed civilians, dragged from homes and shot in front of their wives and children, some on their own doorsteps before they were fully awake. Among the dead were eighteen of twenty-three young army recruits camped at the edge of town who had not yet even been **mustered into service** (officially sworn in and enrolled as soldiers): boys killed before they were soldiers, never given the chance to fire the muskets they had come to learn. The raiders burned about a quarter of the town and destroyed nearly every business, doing as much as $2 million in damage in 1863 money. Senator Lane, the man whose name the Missourians most wanted, escaped by fleeing through a cornfield in his nightshirt. The raiders lost exactly one man.` },
      { p: `When the riders left, around mid-morning, they left a town of widows. Women walked the smoking streets turning over the bodies of husbands and sons; nearly every household that had lost a man had lost him in front of the others. A few hundred armed men had ridden into a sleeping town at sunrise and, in a few hours, murdered well over a hundred unarmed neighbors and burned the place to its foundations. There was no military objective in it that any rule of war would recognize. It was terror as the point, not as a side effect, and it set the standard the rest of the border war would try to match.` },
      { h: `"Bloody Bill" Anderson and Centralia`, eyebrow: `Pressure` },
      { fig: '/war-img/guerrilla-war-bloody-bill-anderson.jpg', cap: `William T. "Bloody Bill" Anderson, photographed in the early 1860s — alive, and worth saying so, since the image usually attached to his name is the one taken after a Union ambush killed him in October 1864. He scalped and mutilated the men he killed and reportedly kept a knotted cord that tallied them; at his death it is said to have held some fifty-four knots. At Centralia, his band stripped and shot 22 unarmed Union soldiers pulled off a train, then rode down and killed about 123 more men the same afternoon.`, credit: `Unknown photographer · photograph · early 1860s · Wikimedia Commons · public domain` },
      { p: `If Quantrill was the border war's most famous bushwhacker, **William T. "Bloody Bill" Anderson** (born around 1840) became its most pitiless. He rode with Quantrill's Raiders from early 1863, including at Lawrence, but the two men split late that year, after a falling-out in Texas, and Anderson went on to lead his own band. He earned the name. He was known to scalp and mutilate the men he killed, and he reportedly kept a knotted cord that tallied his victims. By the time he died, the cord is said to have held some 54 knots.` },
      { p: `Anderson's emblem was a railroad stop called Centralia, Missouri, and the day there, **September 27, 1864**, shows the border war at its most merciless. That morning Anderson's band, about 80 men, stopped a North Missouri Railroad train carrying around 125 passengers. Pulled off it were 23 unarmed Union soldiers: men on **furlough** (authorized leave from duty), heading home to Missouri and Iowa after the Atlanta campaign, soldiers who had survived a hard summer in Georgia and thought the worst was behind them. Anderson's men ordered them to strip (that last humiliation before the killing) and shot them down, 22 of the men pulled off the train murdered on the spot, sparing only one, Sergeant Thomas Goodman, kept as a hostage. The bodies were mutilated and scalped, and the train and depot were set ablaze.` },
      { p: `That was the morning. In the afternoon a Union officer, Major A.V.E. Johnston, pursued Anderson with about 147 mounted infantry. Anderson's guerrillas, mounted and each carrying multiple revolvers, were built for exactly this kind of close, fast, mounted killing. They closed on Johnston's foot soldiers, who had dismounted to fire, and rode them down before most could reload, killing around 123 of the 147 almost where they stood. Counting the men murdered at the depot that morning, the single day cost roughly 150 Union dead against a handful of guerrillas. And riding with Anderson that day were two young brothers, Frank and Jesse James. By the account Frank James later gave, it was Jesse (still a teenager) who fired the shot that killed Major Johnston. (That is a family attribution, not an established fact, and it is fair to mark it as such.)` },
      { p: `Anderson did not outlive the year. He was killed in a Union ambush near Albany, Missouri, on October 26, 1864, shot in the head. The cord and the legend went with him.` },
      { h: `The army empties four counties`, eyebrow: `Consequence` },
      { fig: '/war-img/guerrilla-war-order-no-11.jpg', cap: `George Caleb Bingham's *Martial Law*, better known as *Order No. 11* — a Missouri Unionist's furious protest against his own side, showing families turned out of their homes at gunpoint under the Union order that emptied four counties. General Order No. 11 expelled roughly 25,000 people in fifteen days and left a burned-over "Burnt District" of standing chimneys. A massacre and a military order are not the same thing, but they are the two ends of the same collapse.`, credit: `George Caleb Bingham · engraving/print after his painting · 1872 · Wikimedia Commons · public domain` },
      { p: `Here is where the border war proves its deepest point: that it had erased the line between soldier and civilian on *both* sides, and that the Union's answer to bushwhacker terror was a reprisal against an entire civilian population.` },
      { p: `Four days after Lawrence, with the North howling for an answer to Quantrill, the Union commander of the border district acted. **General Thomas Ewing Jr.** issued **General Order No. 11 on August 25, 1863.** Its logic was cold and simple: the bushwhackers survived because the rural population fed them, hid them, and warned them, so you drained the bushwhackers by draining the population. The order commanded *all persons* living in four Missouri counties (Jackson, Cass, Bates, and the northern part of Vernon) to abandon their homes within 15 days. Those who could prove their loyalty to a Union post were allowed to relocate to a handful of designated towns; everyone else simply had to get out.` },
      { p: `The result was a forced exodus of roughly 25,000 people (estimates run from about 20,000 up to 25,000). Cass County, which had held around 10,000 residents in 1860, was down to a few hundred by late 1863. The Union army, and the jayhawkers riding in its wake, burned much of what was left behind, and the emptied, charred region earned a name that stuck: the **"Burnt District."** For months afterward a traveler could ride a full day through that country and pass nothing but blackened chimneys standing over abandoned fields. "Jennison's tombstones," people called the lone chimneys, after the jayhawker whose men had done much of the burning. Only about a third of the people driven out ever came back.` },
      { p: `At Lawrence, Confederate guerrillas murdered civilians wholesale. At Order No. 11, the Union army expelled civilians wholesale. One was a massacre and the other was a military order, and they are not morally identical, but they are the two ends of the same collapse, the same erasing of the line between the man who carries a gun and the family that does not. Atrocity bred reprisal bred more bushwhacking; the cycle fed itself. That is the truest thing to say about the border war: the story is not any single villain. The story is the cycle, and how it consumed everyone inside it.` },
      { p: `The painter George Caleb Bingham, a Missouri Unionist who watched the expulsion, was so horrified that he painted it as a protest: his canvas *Martial Law*, better known as *Order No. 11*, showing families turned out of their homes at gunpoint. A Union man made the Union's most enduring indictment of what the Union army did. That, too, is the border war: even the people on the "right" side could not always stomach what their side had become.` },
      { h: `The Gray Ghost: how it could have been fought`, eyebrow: `Turning point` },
      { fig: '/war-img/guerrilla-war-mosby.jpg', cap: `John Singleton Mosby, "the Gray Ghost," who fought the same hit-and-run war as the Missouri bushwhackers and still kept it inside the rules — his men wore Confederate uniforms, answered to a chain of command, and took prisoners alive. In November 1864, after a cycle of tit-for-tat executions began in the Shenandoah Valley, Mosby wrote to the enemy general and proposed both sides go back to treating captives as prisoners of war. It was the rare moment in this whole story when someone deliberately stopped the killing.`, credit: `Mathew B. Brady · photograph · between 1860 and 1865 · Wikimedia Commons (Brady-Handy Collection) · public domain` },
      { p: `A man could fight behind enemy lines, raid and ambush and vanish, and still keep his war inside the rules. That man was **John Singleton Mosby**.` },
      { p: `Mosby commanded the 43rd Battalion of Virginia Cavalry (**Mosby's Rangers**), one of the two partisan commands the Confederacy exempted when it repealed the Partisan Ranger Act in 1864. He operated in the rolling farm country of Northern Virginia, in Loudoun, Fauquier, and Prince William counties, a region so completely his that Union forces gave up calling it anything but **"Mosby's Confederacy."** His method was the partisan's: lightning raids on Union outposts, supply lines, and **pickets** (the small guard posts set at the outer edge of a camp to watch for an approaching enemy), struck out of nowhere and gone before a response could form, his men dissolving back into the local farms between strikes. Around 1,900 men served under him over the war, which earned him a nickname that fit the way he fought: **"the Gray Ghost."**` },
      { p: `His men **wore Confederate uniforms, operated under official authority, and took prisoners.** That is the line between a partisan ranger and a bushwhacker, drawn in the clearest possible terms. Quantrill's men murdered captives; Mosby's men captured them and kept them alive. Mosby fought the irregular war as a soldier inside the laws of war, which is precisely why his name is honored where Quantrill's and Anderson's are bywords for slaughter. It was a choice. He made the other one.` },
      { p: `In the fall of 1864, in the **Shenandoah Valley** (the rich farm corridor running through western Virginia that fed the Confederate army, and which Union forces were then burning to ruin), Union troops under the command of Philip Sheridan and George Custer executed six of Mosby's captured men at Front Royal, Virginia, with a seventh Ranger captured separately and executed soon after, in early October, treating them as guerrillas rather than prisoners of war. Mosby answered in kind, as the logic of no quarter demanded: on November 6, 1864, he ordered seven Union prisoners chosen by lottery to be hanged in retaliation, to match the seven of his own men killed. But even here the spiral broke. In the event only about three were actually executed; some escaped, and at least one was spared. And then, on November 11, Mosby **wrote to General Sheridan** and proposed that both sides go back to treating captives as prisoners of war. Sheridan agreed. The tit-for-tat executions stopped.` },
      { p: `That letter is the moral hinge of the whole episode. At Fort Pillow and Lawrence and Centralia, the no-quarter logic ran until it ran out of victims. In the Shenandoah, a commander on one side simply decided to halt it, and the commander on the other side let him. It could be done. Almost no one chose to do it, but Mosby did, and it is why he ends the war a different kind of figure than the men of the Missouri brush.` },
      { p: `His afterlife sealed the contrast, though it is worth being precise about its limits. After the war Mosby became a Republican, befriended and supported Ulysses S. Grant (the general who had beaten him) and held federal posts, including U.S. consul to Hong Kong. On the things that matter most: war crimes, and joining the organized racial terror of the Klan, he is the inverse of Forrest. But his reconciliation with Grant was personal and pragmatic, not an ideological repudiation of the Confederacy. Mosby remained, for the rest of his long life, a proud and vocal defender of Confederate veterans and their honor. He is the moral opposite of Forrest on conduct and on the Klan, not a man who recanted the cause. The contrast holds: the Confederate irregular who fought within the rules and reconciled with the nation, against the Confederate general who presided over a massacre and then founded the Klan. Between those two men lies the entire moral spectrum of this war's edges.` },
      { h: `The thin reckoning`, eyebrow: `Consequence` },
      { fig: '/war-img/guerrilla-war-champ-ferguson.jpg', cap: `Samuel "Champ" Ferguson, seated in Union custody in 1865 before his trial. A backwoods guerrilla who claimed to have killed over a hundred men in the settling of neighborhood scores, he took part in murdering wounded Union soldiers — including Black troopers — in their hospital beds after Saltville. He was hanged on October 20, 1865, one of the very few Confederates ever executed for war crimes. Nathan Bedford Forrest, who commanded an army that killed surrendering men by the hundreds, was never charged, and died in his bed.`, credit: `Federal government photographer · photograph · 1865 · Wikimedia Commons · public domain` },
      { p: `So who was ever punished for any of this? Almost no one. The few who were make their own bleak point.` },
      { p: `The Cumberland Plateau, the rough border country between Tennessee and Kentucky, had its own bushwhacker, and he became one of the only men the war's reckoning actually reached. **Samuel "Champ" Ferguson** waged a pro-Confederate guerrilla war that was, even by border standards, intensely personal: much of it the settling of neighborhood scores, the hunting down of specific local men. He claimed to have killed over a hundred Union soldiers and pro-Union civilians. His worst act tied him directly into the no-quarter throughline of this section: after the First Battle of Saltville in Virginia, in October 1864, Ferguson's band took part in murdering wounded Union soldiers in their hospital beds, including wounded Black troopers of the 5th U.S. Colored Cavalry, killed where they lay.` },
      { p: `Ferguson was caught, tried, and convicted in 1865, and hanged on October 20 of that year. At his trial he was unrepentant to the last:` },
      { p: `"I am yet and will die a Rebel… I killed a good many men, of course, but I never killed a man who I did not know was seeking my life."`, q: true },
      { p: `Ferguson is usually named, alongside one other man, as one of the only two Confederates executed for war crimes after the Civil War. The other was **Henry Wirz**, the commandant of the Andersonville prison camp, hanged on November 10, 1865. The "only two" line needs one honest caveat, though: some sources add a third name, the Kentucky guerrilla Henry C. Magruder (also tried and executed in Kentucky in 1865), so the careful way to say it is that Ferguson and Wirz are the two men *usually* named, among the very few ever held to that account.` },
      { p: `Champ Ferguson, a backwoods guerrilla, was hunted down and hanged for killing wounded men. Nathan Bedford Forrest, who commanded the army that killed surrendering men by the hundreds along a color line and may well have ordered it, was never charged with anything. He died in his bed in 1877. A war that produced Fort Pillow and Lawrence and Centralia and Saltville, that killed surrendering men by the hundreds and murdered civilians by the score, hanged a handful of men for it: a guerrilla, a prison commandant, perhaps one more, and let the general walk free. The atrocity was vast and the accounting was thin, late, and partial. That gap, between what was done and what was answered for, is its own fact about how this war ended.` },
      { h: `A pattern, not a single day`, eyebrow: `Consequence` },
      { fig: '/war-img/guerrilla-war-jesse-james.jpg', cap: `Jesse James, about sixteen, photographed in 1864 as a Missouri bushwhacker riding with "Bloody Bill" Anderson — years before the outlaw legend. Frank and Jesse James carried the bushwhacker's habits — the raid, the ambush, the grievance against Union authority — straight out of the war and into a seventeen-year outlaw career, a legend half folk hero and half Lost Cause myth. The border's hatreds simply refused to demobilize.`, credit: `Taylor Copying Co., St. Louis · photograph · 1864 · Wikimedia Commons · public domain` },
      { p: `It would be a mistake to leave Fort Pillow standing alone, as if it were a single dreadful aberration. It was the emblem of a pattern, and the pattern had a paper trail running up the Confederate chain of command. On May 1, 1863, nearly a year before Fort Pillow, the Confederate Congress passed a retaliatory measure declaring that captured Black Union soldiers would not be treated as prisoners of war at all: they were to be turned over to the state authorities and, in effect, re-enslaved, while the white officers who led them could be put to death for "inciting servile insurrection." Six weeks later, on June 13, 1863, the Confederate commander of the Trans-Mississippi (the theater west of the Mississippi River), General Edmund Kirby Smith, wrote to a subordinate approving the idea of giving "no quarter to armed negroes and their officers": about as close to a written command-level authorization for massacre as the historical record holds. The Union answered the policy in kind: on July 30, 1863, Lincoln issued his **Order of Retaliation**, threatening to execute a Confederate prisoner for every Union soldier murdered and to put one at hard labor for every one sold back into slavery. (That Union counter-threat helped collapse the prisoner-exchange system between the armies, which swelled the death camps on both sides.) So when Forrest's troops shouted "No quarter" at Fort Pillow, they were not improvising a private cruelty. They were acting inside a policy their own government had written down.` },
      { p: `Fort Pillow was not the only place it was carried out. Six days later, at Poison Spring, Arkansas, on April 18, 1864, Confederate troops massacred and mutilated Black soldiers of the 1st Kansas Colored Infantry. Of roughly 300 Union casualties that day, the majority were from that single Black regiment, and the survivors raised their own vow: in the Trans-Mississippi, the Black battle cry became "Remember Poison Springs!" At Saltville that October, wounded Black cavalrymen were murdered after the battle, with estimates of the dead ranging from a handful to as many as roughly 45 or 50, the precise toll disputed to this day. And at the Crater outside Petersburg in July 1864, surrendering USCT soldiers were murdered after a failed assault. Put together, Fort Pillow, Poison Spring, Saltville, and the Crater make a single grim point: the killing of Black soldiers trying to surrender was not one terrible afternoon in Tennessee. It was Confederate practice, authorized at the top and carried out in more than one theater in the same year: a policy with a body count, of which Fort Pillow was only the most infamous instance.` },
      { p: `The guerrilla war erased the line between soldier and civilian: Lawrence and Order No. 11 are the matched proof. The no-quarter war erased the line between combat and murder: Fort Pillow and Poison Spring are the proof of that. And both wars outlived the surrender. Quantrill himself was ambushed in Kentucky in the spring of 1865, shot and paralyzed and dead within weeks. He had survived the whole war only for the war to kill him anyway, after the main armies had already laid down their arms. Frank and Jesse James carried the bushwhacker ethos (the raid, the ambush, the grievance against Union authority) straight out of the war and into a seventeen-year career as outlaws, the most famous in American history. Their legend was burnished, then and after, by the same Confederate-sympathizer mythology that romanticized the bushwhacker cause and shaped the whole border's memory of the war, so that "most famous outlaws" was always half folk hero and half Lost Cause. The border's hatreds simply refused to demobilize. And Forrest, the emblem of the war's worst day for Black soldiers, put on the first Grand Wizard's robes and carried the war's racial terror directly into the peace.` },
      { p: `A regular general's troops slaughtering surrendering men along a color line, and un-commissioned neighbors murdering each other in the Missouri brush, are not two stories but one: the story of what happens when the line erases, between soldier and civilian, between combat and murder, between a war with rules and a war with none. The men who would not let Black soldiers surrender, and the men who murdered their neighbors at dawn, did not lay down those habits at Appomattox. They carried them into Reconstruction (the postwar years, 1865–1877, when the federal government tried to rebuild the South and protect the rights of the freedpeople), into the Klan, into the outlaw legend, into the long racial terror that followed the war it supposedly ended. The honorable exception, Mosby, only sharpens the point by standing nearly alone. The war's edges were where its rules ran out, and where you can already see, before the guns even fall silent, the shape of the violence that the peace would inherit.` },
    ],
    meanwhile: {
      region: `the Northern home front`,
      title: `The War Within the North`,
      body: `While the war turned savage at its edges, the North was fighting a quieter war with itself — over dissent, over civil liberties, and over whether a democracy could hold a free presidential election in the middle of a civil war without tearing itself apart.`,
    },
  },
}

export default function GuerrillaWarThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="guerrilla-war"
      battleName="Fort Pillow & the Guerrilla War"
      theatreId="offfield"
      battleId="th-atrocity"
      theatreHref="/war-civil-war/off-the-battlefield"
      accent={ACCENTS.otbf}
      heroImage="/war-img/guerrilla-war-fort-pillow-massacre.jpg"
      heroPalette={["#2e211c","#1e1714","#0a0706"]}
      heroCredit={`Unsigned · wood engraving · 1864 · *Harper's Weekly* (Apr 30, 1864), via Wikimedia Commons · public domain`}
      heroFocus="center 45%"
      heroScale={1.06}
      endHref="/war-civil-war/off-the-battlefield"
      endKicker={`The war at its ugliest`}
      endLabel={`Back to Off the Battlefield`}
    />
  )
}
