'use client'

// The Battles of Saratoga (September 19 & October 7, 1777, surrender October 17),
// battle sections · American Revolution. The flagship XL battle: two battles in
// the same woods eighteen days apart, plus the surrender, told as one squeeze.
// Produced through the war content pipeline (audits/war-content-pipeline.md):
// fact pack → author → critic gates (fact-check + storytelling + newcomer-clarity
// + framing, parallel) → reconcile → revise. Data only; rendered by the shared
// <BattleSectionReader>. House voice: no em-dashes; side-tags once on first
// mention per section. Legend control per the fact pack: Arnold is NOT staged on
// the field Sept 19 (Luzader named); the Oct 7 ride is told at evidence level;
// McCrea's killer is genuinely unknown; Murphy and the surrender dialogue ride
// "tradition" / "by the famous account"; the turkey call is "the story goes";
// "begin the game" is "is supposed to have said"; the Franklin doorstep is "the
// story goes" + paraphrase. The apocrypha blacklist is untouched. The final's
// locator arrows are not renderable in the locator block contract; the movement
// lines live in the captions instead (Ticonderoga precedent). The tactical
// locator serves BOTH battle sections per the final (Sections 1–2); the
// strategic campaign-collapse frame opens Section 3, with the Clinton-raid inset
// note folded into its caption (the locator block draws no inset panel).
// Sources: audits/war-pipeline/rev-saratoga-final.md (+ rev-saratoga-factpack.md).

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import type { Block } from '@/components/mode/battle-reader'

// Locator 1 · tactical: the two battles. Opens Sections 1 AND 2 per the final
// ("a tactical frame serving both battles"); each section page stands alone.
const TACTICAL_LOCATOR: Block = {
  locator: {
    eyebrow: 'The ground · Sept 19 & Oct 7, 1777',
    caption: 'Both battles were fought in the forest clearings northwest of the American line, and the line is the reason why. Kościuszko\'s entrenchments on Bemis Heights commanded the defile where the Albany road squeezed between the bluff and the Hudson; Burgoyne could not go through it, so twice he tried to swing west around the American left, into the woods where Morgan\'s riflemen were waiting.',
    frame: { lonMin: -73.70, lonMax: -73.56, latMin: 42.96, latMax: 43.04 },
    states: [
      { name: 'New York', tone: 'focus', label: 'NEW YORK', labelLon: -73.69, labelLat: 43.036, labelSize: 11 },
    ],
    labels: [
      { text: 'HUDSON RIVER', lon: -73.578, lat: 42.985, kind: 'water', size: 10, anchor: 'middle' },
      { text: 'RIVER ROAD TO ALBANY', lon: -73.617, lat: 42.963, kind: 'faint', size: 10, anchor: 'middle' },
    ],
    dots: [
      { name: 'Bemis Heights', date: 'the American line; the Neilson farm', lat: 42.987, lon: -73.642, heavy: true, anchor: 'end', dy: -8, dateBelow: true },
      { name: 'The river defile', date: 'the road Burgoyne could not force', lat: 42.975, lon: -73.628, color: '#8a8175', anchor: 'start', dy: 8, dateBelow: true },
      { name: 'Freeman\'s Farm', date: 'the Sept 19 clearing', lat: 43.003, lon: -73.633, heavy: true, anchor: 'start', dy: 12, dateBelow: true },
      { name: 'Balcarres Redoubt', date: 'the fortified farm, after Sept 19', lat: 43.004, lon: -73.635, color: '#8a8175', anchor: 'end', dy: 23, dateBelow: true },
      { name: 'Breymann Redoubt', date: 'stormed at dusk Oct 7', lat: 43.0084, lon: -73.6394, heavy: true, anchor: 'end', dy: -14, dateBelow: true },
      { name: 'Barber\'s wheat field', date: 'the Oct 7 opening', lat: 42.997, lon: -73.645, color: '#8a8175', anchor: 'end', dy: 6, dateBelow: true },
      { name: 'Great Redoubt', date: 'Fraser\'s burial; the river bluff', lat: 43.012, lon: -73.612, anchor: 'start', dy: 10, dateBelow: true },
      { name: 'Sword\'s House', date: 'Burgoyne\'s camp, Sept 17–19', lat: 43.02, lon: -73.61, anchor: 'start', dy: -8, dateBelow: true },
    ],
  },
}

// Locator 2 · strategic: the campaign collapses (Section 3). Clinton's too-late
// Highlands raid is an inset NOTE folded into the caption per the final (never
// extend the main frame toward the Highlands).
const STRATEGIC_LOCATOR: Block = {
  locator: {
    eyebrow: 'The campaign collapses · July–October 1777',
    caption: 'The whole campaign ran down this map and died ten miles short of where it stalled. Ticonderoga fell in July; Bennington and Stanwix broke the army\'s reach in August; the crossing in September made Albany the only way out. After October 7 the army retreated north to Saratoga, and the militia closed the circle around it. Off the frame to the south, Clinton\'s raid, Oct 3–16: ~3,000 men stormed the Highlands forts and burned Kingston, still about 50 miles short of Albany. A raid, not a rescue; nothing he did could have arrived in time.',
    frame: { lonMin: -75.6, lonMax: -73.0, latMin: 42.55, latMax: 43.95 },
    states: [
      { name: 'New York', tone: 'focus', label: 'NEW YORK', labelLon: -75.48, labelLat: 43.88, labelSize: 12 },
      { name: 'Vermont', label: 'VERMONT', labelLon: -73.08, labelLat: 43.66, labelSize: 11 },
      { name: 'Massachusetts', tone: 'faint' },
    ],
    lakes: [
      { name: 'Lake Champlain', label: 'LAKE CHAMPLAIN', labelLon: -73.34, labelLat: 43.88, labelSize: 10, labelAnchor: 'start' },
      { name: 'Lake George', label: 'LAKE GEORGE', labelLon: -73.73, labelLat: 43.55, labelSize: 9, labelAnchor: 'end' },
    ],
    labels: [
      { text: 'HUDSON RIVER', lon: -73.53, lat: 43.04, kind: 'water', size: 10, anchor: 'start' },
    ],
    dots: [
      { name: 'Fort Ticonderoga', date: 'the July triumph; abandoned by Britain in November', lat: 43.842, lon: -73.387, anchor: 'end', dateBelow: true },
      { name: 'Fort Edward', date: 'Jane McCrea, July 27; Stark seals the north in October', lat: 43.267, lon: -73.581, anchor: 'end', dateBelow: true },
      { name: 'Bennington battlefield', date: 'Walloomsac, NY; the Aug 16 bleeding', lat: 42.936, lon: -73.305, anchor: 'end', dy: 6, dateBelow: true },
      { name: 'Fort Stanwix', date: 'the failed western prong, siege abandoned Aug 22', lat: 43.211, lon: -75.455, anchor: 'start', dateBelow: true },
      { name: 'The Hudson crossing', date: 'bridge of boats, Sept 13–15; no going back', lat: 43.11, lon: -73.58, color: '#8a8175', anchor: 'start', dy: -10, dateBelow: true },
      { name: 'Saratoga / Schuylerville', date: 'the trap closes; the Fort Hardy surrender meadow, Oct 17', lat: 43.101, lon: -73.581, heavy: true, anchor: 'end', dy: 8, dateBelow: true },
      { name: 'Bemis Heights / the battlefield', lat: 42.987, lon: -73.642, heavy: true, anchor: 'end', dy: -6 },
      { name: 'Stillwater', lat: 42.967, lon: -73.683, color: '#8a8175', anchor: 'start', dy: 10 },
      { name: 'Albany', date: 'the goal he never reached', lat: 42.652, lon: -73.757, anchor: 'start', dy: 4, dateBelow: true },
    ],
  },
}

const SARATOGA_NARR: Record<string, Narr> = {
  'the-squeeze': {
    eyebrow: 'Saratoga · The squeeze',
    title: 'No going back',
    blocks: [
      TACTICAL_LOCATOR,
      { p: 'In July 1777, John Burgoyne (British) was the most celebrated general in the empire. His invasion had come down from Canada exactly as he had sold it to London: an army of about 8,000 men moving south along Lake Champlain toward Albany, New York, on a plan to seize the Hudson River corridor and cut New England, the furnace of the rebellion, off from the other colonies. A second, smaller British force under Colonel Barry St. Leger was to swing in from the west, down the Mohawk Valley, and meet him. And in the first week of July, Fort Ticonderoga, the most famous fortress in America, had fallen to Burgoyne in four days, almost without a shot.' },
      { pill: '/war-revolution/battles/ticonderoga-1777', plabel: 'July 1777: the fall of Ticonderoga, this campaign\'s opening act' },
      { p: 'The plan had a hole in it, and the hole was in London: it assumed the main British army in New York City could cooperate up the Hudson, but its commander, General Howe, had sailed against Philadelphia instead, and nobody had ordered him to do otherwise. While Burgoyne\'s army shrank in the north, Howe\'s was fighting Washington at Brandywine and Germantown, three days\' ride to the south. It was not a betrayal. It was a planning failure, and Burgoyne marched south into it.' },
      { p: 'After the triumph came the crawl. South of the lakes, Burgoyne took his army overland through country the Americans were unbuilding in front of him: trees felled across every road, bridges burned. It took roughly three weeks to cover the 23 miles to Fort Edward, on the upper Hudson, and every mile stretched a supply line running all the way back to Canada, short of carts and draft animals.' },
      { fig: '/war-img/rev-saratoga-faden.jpg', cap: 'William Faden\'s map of "the Country in which the Army under Lt. General Burgoyne acted in the Campaign of 1777": the corridor from Lake Champlain down the Hudson toward Albany. Every mile south stretched the supply line behind the army a mile thinner.', credit: 'William Faden · engraved map · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'Then August broke the campaign\'s back twice. Burgoyne sent a German column under Lieutenant Colonel Baum east toward Bennington to forage (to gather horses, draft animals, and food from the countryside), and on August 16 John Stark\'s New Hampshire militia (part-time citizen soldiers, not the Continental regulars) destroyed it, then mauled the relief column that came after it. About a thousand men gone, and not a horse or a barrel of flour to show for them. That same month the western prong collapsed: St. Leger, bloodied at Oriskany and spooked by a ruse that inflated the relief force marching against him, abandoned his siege of Fort Stanwix on August 22 and fell back to Canada. There would be no meeting at Albany. By early September, Burgoyne\'s field force was down to just over 7,000 men.' },
      { pill: '/war-revolution/battles/bennington', plabel: 'August 16: Stark\'s militia destroys the foraging expedition' },
      { p: 'And in the middle of all this came a killing the whole continent would hear about. On July 27, near Fort Edward, a young woman named Jane McCrea, about 25, from a New Jersey family, was seized by a party from Burgoyne\'s Native contingent and killed and scalped; her scalp was recognized in the British camp. She was engaged to David Jones, a Loyalist officer marching with Burgoyne\'s own army. That much is certain, and almost nothing past it is. One account, the one that fixed blame in the British camp, said her escorts had quarreled over the reward for bringing her in and one of them killed her. The other, which began with the accused man himself, said she was hit by American bullets fired at the retreating party and scalped after she was dead. A nineteenth-century exhumation claimed to find bullet wounds and no tomahawk wounds; by the next examination her skull was missing, and the forensics settle nothing. Who killed Jane McCrea is genuinely unknown.' },
      { fig: '/war-img/rev-saratoga-mccrea.jpg', cap: 'John Vanderlyn\'s "The Death of Jane McCrea," painted in 1804, twenty-seven years after her killing. It is the icon of the legend, not a record of the event: who actually killed her was disputed within days and is genuinely unknown now. What the painting documents is the story Americans told each other in the fall of 1777.', credit: 'John Vanderlyn · oil painting · 1804 · Wikimedia Commons · public domain' },
      { p: 'What happened next is the verified story, and it is the one that mattered. Burgoyne demanded the accused warrior for execution. Simon Fraser, his best brigadier, warned him that punishing the man would send every Native ally home or into revenge, and Burgoyne backed down. Fraser was the best soldier in the army, a veteran of Louisbourg and the Plains of Abraham in the last war, the man every advance turned on; when he counseled restraint, Burgoyne listened. Horatio Gates, who had just replaced General Philip Schuyler as the American commander in the north, then did something shrewder than fighting: he wrote Burgoyne an open letter about "a young lady lovely to the sight, of virtuous character and amiable disposition... scalped and mangled," and the letter ran through the newspapers. A Loyalist\'s own fiancée, killed by the King\'s allies, and the King\'s general unable to punish anyone for it: as a recruiting story it was a gift, and it helped fill Gates\'s camp with militia. An American officer who knew of her, James Wilkinson, later deflated the legend ("a country girl... without either beauty or accomplishments"). It made no difference. The legend, not the girl, raised the regiments.' },
      { p: 'The affair cost Burgoyne the other half of the bargain too. He had opened the campaign with about a thousand Native allies, threatening rebels with them in a bombastic proclamation while forbidding violence against non-combatants, and McCrea\'s death exposed the contradiction: he could not punish the accused without losing the alliance, and by not punishing he handed Gates a weapon and lost the alliance anyway. After Bennington, where some 80 Native fighters became casualties and got little thanks for it, the partisan leaders La Corne and Langlade and most of the contingent went home. By mid-September, fewer than 100 scouts remained. The consequence would decide battles: Burgoyne\'s army was nearly blind in the woods, its pickets (the sentries and small guard posts out ahead of the main camp) and foraging parties picked off nightly, while the American screen now included Daniel Morgan\'s rifle corps, roughly 500 frontier marksmen Washington had sent north in August, carrying long rifles with officer-killing accuracy. For the Native nations of this corridor, 1777 was the year neutrality broke into something like civil war, and that is a story of its own.' },
      { pill: '/war-revolution/off-the-battlefield/native-nations', plabel: 'The nations caught between two empires, told whole' },
      { p: 'On September 13, Burgoyne made the bet that decided the campaign, and the line that explains the bet he had written two and a half months earlier, in an order of June 30.' },
      { p: 'This army must not retreat.', q: true },
      { p: 'That was the gambler\'s whole creed in five words, and on September 13 he acted on it. His army crossed to the west bank of the Hudson on a bridge of boats just north of the little settlement of Saratoga, and rather than leave a chain of garrisoned posts behind him, he deliberately cut his communications back to Ticonderoga. A man who tells himself he must not retreat does not keep an open road home; he burns it, so that the only way out is forward, through the enemy, to Albany. From that moment there were two possible endings, Albany or capitulation, and Burgoyne, by temperament a gambler who had sold London this plan and staked his name on it, had chosen to leave himself no third option. He said as much himself later, defending the campaign in Parliament.' },
      { p: 'Ten miles ahead, the Americans were waiting on ground they had chosen. Gates had moved his army north from Stillwater in early September, and his chief engineer, Tadeusz Kościuszko, a Polish volunteer who had sailed for America in 1776, laid out the line on Bemis Heights: a plateau rising 100 to 200 feet above the river, at the exact place where the road to Albany squeezed through a defile (a narrow pass) between the bluff and the water. Entrenchments and batteries commanded the road below; a fortified line ran inland to the west. Behind those lines stood some 8,500 effectives (soldiers fit for duty), with militia arriving daily. Burgoyne could not force the defile, which left him one play: swing west through the forest and try to turn the American left. That is why both battles of Saratoga would be fought in woodland clearings northwest of the lines. One army on that river kept shrinking; the other kept growing, and no one on either side yet knew what those two curves would produce in the woods ahead.' },
      { fig: '/war-img/rev-saratoga-neilson.jpg', cap: 'The Neilson farmhouse on Bemis Heights, the surviving farmhouse on the line Kościuszko fortified in September 1777. The American entrenchments ran along this high ground, with batteries commanding the river road below.', credit: 'photograph · Historic American Buildings Survey, Library of Congress / Wikimedia Commons · public domain' },
    ],
    meanwhile: { region: 'New York City', title: 'The help that was not coming', body: 'While Burgoyne crossed the Hudson, the army his plan had always quietly counted on was hundreds of miles away. General Howe had taken the main British force to sea, bound for Philadelphia by way of the Chesapeake, and no order from London had ever compelled him up the river instead. The only help that would ever come north was a 3,000-man raid in October, and it would burn its way to a town still about 50 miles short of Albany before turning back.' },
  },

  'the-two-battles': {
    eyebrow: 'Saratoga · The two battles',
    title: 'Two battles in the same woods',
    blocks: [
      TACTICAL_LOCATOR,
      { p: 'On the morning of September 19, 1777, the British general John Burgoyne went looking for the American left. His army advanced in three columns: Simon Fraser\'s Advanced Corps swinging wide to the right, four regiments under Brigadier General James Hamilton (British, commanding the center) with Burgoyne himself, and Baron Riedesel\'s Germans with the guns and supplies on the river road. On Bemis Heights, the American commander Horatio Gates wanted to sit behind the entrenchments and let the British come onto the guns. Benedict Arnold, the aggressive Connecticut general commanding the American left wing, pressed him to fight in the forest instead, where British formations and bayonets were worthless. Gates grudgingly let Morgan\'s riflemen and the light infantry of Major Henry Dearborn (American, commanding a light-infantry battalion) go forward. It was the only major decision he had to make that day, and he made it right.' },
      { fig: '/war-img/rev-saratoga-faden-freemans.jpg', cap: 'William Faden\'s engraved plan of the September 19 battle: Burgoyne\'s camp at Sword\'s House on the Hudson and the three columns that went forward to Freeman\'s Farm. Published in London from the army\'s own surveys.', credit: 'William Faden · engraved plan · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'A little after noon, Morgan\'s riflemen met the center column\'s advance party at an abandoned farm clearing, Freeman\'s Farm, about a mile north of the American works, and in the opening fire they picked off virtually every officer in it. Then they over-pursued, ran into Fraser\'s main body, scattered (the story goes that Morgan rallied them with his turkey call), and what followed was a seesaw afternoon: three to four hours of attack and counterattack across a clearing some 350 yards wide, the field changing hands again and again. Several times the Americans took the British guns and could neither hold nor drag them off; they had shot the artillery horses and the crews, 36 of the 48 artillerymen in the center column. The 62nd Foot was reduced to about the strength of a single company; Burgoyne\'s artillery general, Phillips, personally led another regiment in to save the center.' },
      { p: 'What finally stabilized the British line came from the river road. Late in the afternoon Riedesel, on his own initiative, left 500 men on the baggage and threw his Brunswickers (the hired German soldiers from Brunswick who made up about half of Burgoyne\'s army) and two guns against the American right at the double. The shock held until dark, and darkness ended it. The Americans withdrew to their works; Burgoyne held the field and claimed the victory. It had cost him about 600 men to an American 300, and his best regiments were gutted. (Tradition puts Arnold on horseback in the thick of the smoke that afternoon; Luzader, the battlefield\'s own historian, found no contemporary evidence for it. He spent the day at headquarters, feeding regiments into the fight and pressing Gates for more, and his division did the fighting either way.)' },
      { p: 'Burgoyne meant to renew the attack within two days. Then, on September 21, a ciphered note reached him from General Henry Clinton, commanding in New York City, written nine days earlier: "You know my good will & are not ignorant of my poverty. If you think 2000 men can assist you effectually, I will make a push at [Fort] Montgomery in about ten days." On that thin promise Burgoyne dug in to wait. The arithmetic, from inside his tent, was not absurd: Bennington and St. Leger had already eaten his margins, his supply line was failing, and a junction with Clinton was the one path left that still ended at Albany. If Clinton moved, and moved fast, Saratoga was still a campaign rather than a catastrophe. So he waited, and the wait cost him everything. Rations shrank, the horses starved, militia and Morgan\'s men sniped the pickets nearly every night, and the American army grew daily.' },
      { fig: '/war-img/rev-saratoga-faden-bemis.jpg', cap: 'Faden\'s companion plan, "Bræmus Heights" in the engraver\'s spelling: the fortified British camp after September 19, with the Balcarres and Breymann redoubts (small earthwork forts) that anchored the line, and the ground of the October 7 fighting.', credit: 'William Faden · engraved plan · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'It was a poisoned month inside the American lines too. Gates\'s report to Congress credited Freeman\'s Farm to "a detachment of the army," never naming Arnold, then stripped Morgan\'s corps out of Arnold\'s division. Arnold protested in writing; there was a furious confrontation, recorded at the time in letters by his aides (former aides of the Schuyler whom Gates had replaced, which did not help); Gates issued him a formal pass to leave for Philadelphia, effectively sidelining him. But a pass to Philadelphia was also a pass to miss the battle he had spent the summer building toward, and Arnold stayed in camp, with no clear command. Gates, for his part, had stripped Arnold\'s role and could not give it back without conceding the quarrel. The two men were stuck: a commander who could not afford to lose his best fighting general, and a general who would not leave. The feud is documented fact; the shouting-match dialogue in the popular tellings comes from memoirs written decades later, and is not.' },
      { pill: '/war-revolution/two-armies', plabel: '1777, the whole campaign: two British armies, two separate wars' },
      { p: 'By early October Burgoyne\'s army was on short rations and down to about 5,000 effectives. Over the advice of Riedesel and Fraser, who wanted to fall back across the Hudson while it was still possible, he ordered a reconnaissance-in-force (a heavy armed probe) for October 7: some 1,500 to 1,700 picked men and ten guns, led by Burgoyne, Fraser, Riedesel, and Phillips in person, to test the American left and cut forage in the wheat (the army was nearly out of food, and the standing grain in the fields was worth the risk). About two in the afternoon the column halted on an exposed rise in Barber\'s wheat field while the officers studied the woods through their glasses. Told the British were out, Gates is supposed to have said, "Order on Morgan to begin the game."' },
      { p: 'The American counterpunch hit both ends of the line at once. Poor\'s brigade smashed the grenadiers (the British army\'s elite heavy infantry, the biggest and most experienced men in the line) on the British left, where Major John Acland (British, commanding the grenadier battalion) fell shot through both legs and was captured; Morgan swung wide and crushed the light infantry (fast-moving skirmishers who fought in open order, not in the shoulder-to-shoulder line) on the right; Dearborn hit the breaking line head-on. Within about an hour the reconnaissance had lost some 400 men and six of its ten guns and was streaming back toward its fortifications. Fraser, conspicuous on horseback rallying the rearguard, was shot through the stomach by one of Morgan\'s riflemen. Tradition, first written down 68 years later from family stories, credits the marksman Timothy Murphy, and gives Morgan a grim order that the gallant officer had to die; the wounding is fact, the names and the speech are tradition.' },
      { p: 'Then came the ride. Arnold, who still had no command, rode to the firing anyway. In the famous version he galloped off without orders, and Gates sent an aide after him who never caught up. The evidence cuts both ways: Burgoyne wrote that Arnold commanded on the American left that day, another general wrote that Gates ordered him forward, and Gates\'s own report praised "the Gallant General Arnold," strange praise for a mutineer. Whether Gates blessed the ride, tolerated it, or chased it with a messenger is genuinely disputed. What Arnold did on the field is not. He led the attacks on the Balcarres redoubt (a redoubt being a small earthwork fort, a low square of dug walls with firing platforms inside), the fortified line at Freeman\'s Farm, fierce and futile; then spurred across the field, through the crossfire of both armies, untouched, to the weaker Breymann redoubt on the British far right, and led the storming through the gap between the works while Morgan\'s men circled behind. The redoubt fell at dusk. Its commander, Breymann, was killed, reportedly by his own men after he sabered four of them. In the final volleys Arnold\'s horse was shot and fell on him, and a musket ball shattered his left leg, the same leg hit at Quebec two years before. With the Breymann redoubt gone, Burgoyne\'s whole line was turned, his camp open on its right. That night he abandoned the position.' },
      { fig: '/war-img/rev-saratoga-arnold-wounded.jpg', cap: 'Arnold shot at the Breymann redoubt at dusk on October 7, his horse falling, in a 19th-century engraving. Made generations later, it prints the legend; the leg, the horse, and the fallen redoubt are all fact.', credit: '19th-century engraving · New York Public Library / Wikimedia Commons · no known copyright restrictions' },
      { pill: '/war-revolution/battles/quebec-1775', plabel: '1775: the first ball in the same left leg' },
      { p: 'Frederika Riedesel, the German general\'s wife, who had followed the army with their three small daughters, had set a dinner table for the generals that afternoon. Her journal: "About three o\'clock in the afternoon, in place of the guests who were to have dined with me, they brought in to me, upon a litter, poor General Fraser (one of my expected guests), mortally wounded." The table was cleared and a bed made up for him in its place. Through the night she heard him.' },
      { p: 'Oh, fatal ambition! Poor General Burgoyne! My poor wife!', q: true },
      { p: 'Fraser died the next morning, and at sunset on October 8 he was buried as he had asked, inside the Great Redoubt on the river bluff, the chaplain reading the service while American round shot threw dirt over the burial party and Burgoyne and his generals stood bareheaded. Frederika watched from below: "Many cannon balls flew... not far from me, but I had my eyes fixed upon the hill, where I distinctly saw my husband in the midst of the enemy\'s fire."' },
      { fig: '/war-img/rev-saratoga-frederika.jpg', cap: 'Frederika Riedesel, painted by Johann Tischbein in 1762, fifteen years before the campaign, when she was sixteen. She crossed the Atlantic with three small daughters to follow her husband, and her journal of the campaign\'s last weeks is its best eyewitness account.', credit: 'Johann Heinrich Tischbein · oil painting · 1762 · Wikimedia Commons · public domain' },
    ],
    meanwhile: { region: 'The Hudson, by night', title: 'Lady Acland\'s boat', body: 'Major Acland, the captured British grenadier commander, was shot through both legs and in American hands. His wife, Lady Harriet Acland, was pregnant and with the army. She got into a small boat and went down the Hudson under a flag of truce, in the night and the rain, to nurse her husband in his captivity. Burgoyne himself told the story afterward, and made it famous.' },
  },

  'the-convention': {
    eyebrow: 'Saratoga · The surrender',
    title: 'The Convention',
    blocks: [
      STRATEGIC_LOCATOR,
      { p: 'The British army that buried Simon Fraser at sunset on October 8 began retreating that same night, north through cold rain to the settlement of Saratoga (the present town of Schuylerville). It left its hospital behind, some 300 sick and wounded men trusted to American mercy, and most of its baggage. Frederika Riedesel rode the retreat in a calash (a light open carriage) with her three daughters, and spent the next six days in the cellar of a house under American artillery fire. Eleven cannonballs went through the house above her; she wrote of hearing them rolling overhead while the wounded sheltered around her.' },
      { p: 'By October 12 the trap had closed. Gates\'s army stood across the south and west; John Stark, the victor of Bennington, was back with fresh militia, sealing the river to the north at Fort Edward; American guns commanded the camp itself. Around 5,800 worn-down effectives were ringed by a force conservatively put at well over 15,000, with some counts running to 20,000. On October 13 Burgoyne\'s council of war voted to open talks.' },
      { p: 'One last hope was already dead, though nobody at Saratoga knew it. On October 8 Henry Clinton had written Burgoyne from the captured Highlands forts: "Nous y voici, and nothing now between us but Gates. I sincerely hope this little success of ours may facilitate your operations." The courier, Lieutenant Daniel Taylor, was caught two days later. He swallowed the message, sealed inside a hollow silver bullet; New York\'s American governor, George Clinton, ordered him dosed with an emetic, the bullet reappeared, and Taylor was hanged as a spy on October 18, one day after the army he was riding to save had surrendered. Clinton, the British general, had in fact kept his word, in a fashion. He came up the Hudson on October 3 with about 3,000 men, stormed the Highlands forts on October 6, and sent raiders far enough upriver to burn Kingston, still about 50 miles short of Albany: a raid, not a rescue, with no orders and no intention to fight through. Nothing he did could have arrived in time.' },
      { p: 'What Burgoyne salvaged at the table was remarkable. He flatly refused the word "capitulation," and the document signed on October 16 is the Convention of Saratoga. Under its terms the army marched out of camp with the honors of war (meaning the men marched out under their own flags, drums beating and weapons shouldered, not as captives) and grounded its arms at the riverside; in exchange it would march to Boston and embark for Britain, on the condition that its men never serve again in North America during the war; officers kept their sidearms and baggage. Gates accepted terms this generous because Clinton was loose in the Highlands behind him and he wanted Burgoyne\'s army in hand immediately. When he briefly demanded that the British ground their arms inside their own camp, surrender-style, Burgoyne threatened to break off and fight, and Gates folded within hours.' },
      { p: 'On October 17, 1777, nearly 6,000 British, German, and provincial troops marched to the meadow by the ruin of Fort Hardy and laid down their arms: all that remained of the army of nine to ten thousand, counting its auxiliaries, that had left Canada in June, along with more than two dozen guns and some 5,000 muskets. Burgoyne, in full dress, offered his sword to Gates. By the famous account, written down long afterward by an officer who was there, the exchange went like this.' },
      { p: 'The fortune of war, General Gates, has made me your prisoner.', q: true },
      { p: 'Gates, returning the sword: "I shall always be ready to bear testimony that it has not been through any fault of your Excellency." The two generals dined together that day, the captured German officers among the guests, and American bands are said to have played Yankee Doodle. Gates crowed in a letter commonly said to be to his wife: "If Old England is not by this lesson taught humility, then she is an obstinate old slut, bent upon her ruin."' },
      { fig: '/war-img/rev-saratoga-trumbull.jpg', cap: 'John Trumbull\'s "Surrender of General Burgoyne," painted in 1821 for the Capitol rotunda: Burgoyne offering his sword, Gates at center, Morgan in white. Four decades after the event and composed like a state portrait, it is how the new nation chose to remember October 17, not how the meadow by Fort Hardy actually looked.', credit: 'John Trumbull · oil painting · 1821 · United States Capitol / Wikimedia Commons · public domain' },
      { p: 'What happened to the Convention Army afterward is a story Americans tell less often, and it should be told plainly: Congress broke the deal. It never ratified the convention and never let the army sail, reaching for pretext after pretext, a dispute over surrendered cartridge boxes, a bitter line of Burgoyne\'s ("the public faith is broke") seized on as proof Britain would void the bargain, the plain fear that every man shipped home would simply free another soldier for service elsewhere. The army was marched to Cambridge, Massachusetts, then, in the winter of 1778 to 1779, some 700 miles south to Charlottesville, Virginia, and then onward again as the war moved. Thousands deserted or melted into the American population. The officers were eventually exchanged, Riedesel and Phillips in 1780, and Burgoyne himself was paroled home in May 1778 (released on his word of honor not to serve against America until formally exchanged) to defend the campaign in Parliament, which he did for the rest of his public life, never commanding in the field again. Most of the privates who grounded arms at Saratoga did not see home before the peace of 1783. It was a genuinely shabby episode on the winning side.' },
      { p: 'Arnold\'s reward was strange in a different way. He spent months crippled in an Albany hospital while the credit for Saratoga was fought over, and the grievance that ended at West Point three years later arguably begins in that hospital bed; that story belongs elsewhere in this war. At the spot where he fell at the Breymann redoubt there stands a monument, erected in 1887: a single sculpted boot, for the shattered left leg, dedicated to the memory of "the most brilliant soldier" of the Continental Army, "who was desperately wounded on this spot... winning for his countrymen the Decisive Battle of the American Revolution and for himself the rank of Major General." His name appears nowhere on it: a war memorial that honors a man it refuses to name.' },
      { fig: '/war-img/rev-saratoga-boot.jpg', cap: 'The Boot Monument at Saratoga, erected in 1887 at the spot where Arnold fell storming the Breymann redoubt. It honors "the most brilliant soldier of the Continental Army," his shattered leg carved in stone. His name appears nowhere on it.', credit: 'Manuela Michailescu · CC BY-SA 4.0 · Wikimedia Commons' },
      { p: 'And then there is the half of the story that happened across an ocean. The news of Saratoga crossed in about six weeks, carried from Boston by a courier named Jonathan Loring Austin, who reached Benjamin Franklin outside Paris on December 4. The story goes that Franklin called out to ask whether Philadelphia was taken, and Austin answered yes, but that he brought greater news: Burgoyne and his whole army were prisoners of war. Two days later the French foreign ministry summoned the American commissioners; on December 17 France communicated its decision to recognize the United States; and on February 6, 1778, two treaties were signed in Paris, one of friendship and commerce, one of alliance. By June 1778 Britain and France were shooting at each other, and Spain followed the next year. Saratoga moved France because it was proof, the demonstration Versailles had waited two years for, that the Americans could destroy a British field army, and because Paris feared London would now offer the rebels terms they might accept. The rebellion had become a world war, and a world war was something Britain could lose. London did offer terms, in the end: everything short of independence, and it arrived too late. The inside story of that diplomacy is told in its own chapter.' },
      { pill: '/war-revolution/off-the-battlefield/french-alliance', plabel: 'The French alliance: the diplomacy behind the treaties' },
    ],
    meanwhile: { region: 'Ticonderoga', title: 'The corridor handed back', body: 'In November 1777, the British burned and abandoned Fort Ticonderoga, the great prize of July. Everything the campaign had gained, the forts, the lakes, the corridor itself, was given up within weeks of the surrender. Of the army that had come down from Canada to cut the rebellion in half, the only lasting conquest left on the map was the place where it laid down its arms.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={SARATOGA_NARR}
    id={id}
    slug="saratoga"
    battleName="Saratoga"
    date="September 19 – October 17, 1777"
    theatreId="rev-battles"
    battleId="rev-saratoga"
    theatreHref="/war-revolution/battles"
    accent="var(--rev-battles)"
    endHref="/war-revolution?theatre=rev-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
