'use client'

// Champion Hill — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.
//
// VOICE PASS 2026-06-01 (dossier-retrofit): brought to the locked house-voice
// rules — no reader-facing em-dashes; marquee names (Grant, Sherman, Lee) carry
// no side-tag while every other side-affiliated person is tagged once on first
// mention per section (Stephen D. Lee keeps his tag); full rank spelled on first
// mention per section; meta-narrator / editorial asides removed (tell it plainly);
// cross-refs to the Vicksburg campaign are pills. Facts web-verified.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const CHAMPION_HILL_NARR: Record<string, Narr> = {
  'the-crossroads-hill': {
    eyebrow: 'Champion Hill · The hinge',
    title: 'The Hill That Held the Road Home',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -91.5, lonMax: -89.6, latMin: 31.7, latMax: 32.9 },
        states: [
          { name: 'Mississippi', tone: 'focus', label: 'MISSISSIPPI', labelLon: -89.9, labelLat: 32.8 },
          { name: 'Tennessee' }, { name: 'Arkansas' }, { name: 'Louisiana' }, { name: 'Alabama' },
        ],
        dots: [
          { name: 'Champion Hill', date: 'May 16, 1863', lat: 32.2786, lon: -90.4381, heavy: true, anchor: 'middle', dy: 24 },
          { name: 'Jackson', lat: 32.2988, lon: -90.1848, color: '#8a8175', anchor: 'start' },
          { name: 'Vicksburg', lat: 32.3526, lon: -90.8779, color: '#8a8175', anchor: 'end' },
        ],
      } },







      { p: 'By the middle of May 1863, Major General Ulysses S. Grant was loose in the interior of Mississippi, and there was no good way for the Confederacy to put him back. He had crossed the great river south of Vicksburg, cut himself free of his own supply line, and marched inland, winning a string of fights: Port Gibson, Raymond, and then the state capital at Jackson, which he wrecked and left smoking behind him. Now he turned west. Twenty miles (32 km) in front of him, behind the last good defensive ground before the fortress city, waited the army that was supposed to stop him.' },
      { pill: '/war-civil-war/western/vicksburg', plabel: 'Vicksburg: the campaign Champion Hill belongs to' },
      { p: 'The whole point of all this marching was to take Vicksburg, and the whole point of taking Vicksburg was to break the Confederacy in half. Vicksburg held the last stretch of the Mississippi River still in Southern hands. Cut it, and the slaveholding states west of the river (Texas, Arkansas, most of Louisiana) would be severed from the rest of the rebellion. The rebellion was, at bottom, a slaveholders’ republic: the Confederacy had broken away from the United States to protect the enslavement of four million Black people, and Grant’s campaign was a campaign to saw that republic in two. The ground he was about to fight over made the point plainly. Champion Hill took its name from the Champion family, whose plantation it sat on, land in a Mississippi county worked by enslaved people, the very institution the South had seceded to defend. Every mile Grant pushed west, that institution dissolved behind his army: thousands of enslaved people had been freeing themselves along his line of march, walking off the plantations toward the Union columns rather than waiting to be freed.' },
      { p: 'The man waiting for him was Lieutenant General John C. Pemberton (South), commander of the Confederate army charged with holding Vicksburg. Pemberton had been handed contradictory orders: told both to hold the city at all costs and to march out and strike at Grant’s supply line, a supply line Grant had already abandoned, so the order chased a thing that no longer existed. Caught between the two, Pemberton had marched his army out of Vicksburg’s safe works (its ring of defensive fortifications) and into the open, and now he was strung along a low ridge with Grant bearing down on him.' },
      { fig: '/war-img/champion-hill-overview.png', cap: 'The ridge runs about three miles and covers three parallel east-west roads (Jackson, Middle, and Raymond), all leading back toward Vicksburg. The bald seventy-five-foot crest of Champion Hill commands the northern end and the crossroads below it.', credit: 'Stuff Happened map' },
      { p: 'The ridge ran for about three miles, and it covered three roughly parallel roads, all running east to west, all leading back from the Jackson and Edwards Station area toward Vicksburg. From north to south they were the Jackson Road, the Middle Road, and the Raymond Road. Hold those three roads and you held the army’s way home. And the key to the three roads was a single piece of ground at the northern end: a bald crest about seventy-five feet high, rising over the country around it. This was Champion Hill. Grant, who saw the position that morning, judged it shrewdly chosen.' },
      { p: '“...where Pemberton had chosen his position to receive us, whether taken by accident or design, was well selected. It is one of the highest points in that section, and commanded all the ground in the range.”', q: true },
      { p: 'Grant, Personal Memoirs', i: true },
      { p: 'The hill mattered because of what sat just below it. Where the Jackson Road and the Middle Road came together, perhaps a third of a mile down from the crest, there was a crossroads, and that crossroads sat astride Pemberton’s only good road back to Vicksburg. Whoever held the crossroads held the road home, and the crossroads belonged to whoever held the hill above it. The battle for Champion Hill was a battle for a road junction, and behind the road junction was a creek, Baker’s Creek, that the Confederate army would have to get across to escape. (The battle is sometimes called Baker’s Creek for that reason.) Lose the hill, lose the crossroads; lose the crossroads, lose the way over the creek; lose the way over the creek, and you lose the army.' },
      { h: 'A Near-Even Fight', eyebrow: 'The paper edge that never arrived' },
      { p: 'On paper Grant had the bigger army, something on the order of thirty-two thousand men against Pemberton’s twenty-two or twenty-three thousand. Almost none of that edge would reach the field. A Civil War army was built in nested blocks: a handful of regiments made a brigade, a few brigades made a division, and several divisions made a corps, the largest building block of all, ten thousand men or more, the chunk a general like Grant moved around the map like a single piece. Grant had three corps in the area, and on this day two of them barely fought. Major General William T. Sherman’s corps was still back at Jackson, out of range entirely. And Major General John A. McClernand’s (North) corps, marching up on the two southern roads, would sit nearly idle all day despite Grant’s orders, barely firing a shot. That left the fighting to fall on Major General James B. McPherson’s (North) corps and Brigadier General Alvin P. Hovey’s (North) division, a force just about equal in strength to Pemberton’s whole army. Champion Hill was a near-even, savage fight, and Grant won it not by weight of numbers but by where he landed the blow.' },
    ],
    meanwhile: { region: 'Jackson, twenty miles east', title: 'The two armies Grant kept apart', body: 'The reason Grant could fight at near-even odds was that he had spent the previous days making sure the two Confederate armies in Mississippi could never combine against him. General Joseph E. Johnston (South) was gathering a second Confederate force, a relief army, near Jackson, and Pemberton’s army was the one strung along the ridge at Champion Hill. Grant had wedged himself squarely between them. Johnston was not on the field and could not get to it in time, and on May 16 the gap that kept the two Southern armies apart ran right through the crossroads below Champion Hill.' },
  },

  'the-jackson-road': {
    eyebrow: 'Champion Hill · The blow falls',
    title: 'Up the Jackson Road, Onto the Crest',
    blocks: [
      { p: 'Skirmishing, the scattered probing fire of the lead troops feeling out the enemy, opened at dawn as Grant’s three columns groped their way west along the three roads. The first man to grasp what was happening was on the Confederate side. Brigadier General Stephen D. Lee (South), no relation to Robert E. Lee despite the name, held a brigade of Alabamians (a brigade being a few regiments, smaller than a division) posted on top of Champion Hill, and from that high ground he could see what the men down on the roads could not. Off to the north, on the Jackson Road, a heavy Union column was coming on. Lee understood instantly what it meant: that column was aimed at the very flank of the army, the exposed end of a battle line, the place an army is easiest to get around and behind, and if it got past it would cut Pemberton off from Vicksburg. He sent the warning back. The danger was exactly where he said it was.' },
      { fig: '/war-img/champion-hill.png', cap: 'About one o’clock: Grant lands his blow straight up the Jackson Road against the exposed northern end of the line. Hovey’s and Logan’s men carry the seventy-five-foot crest, break Stevenson’s division, and sweep down to take the crossroads below.', credit: 'Stuff Happened map' },
      { p: 'Grant reached the field around ten in the morning and put his blow in where the crossroads could be reached: straight up the Jackson Road, against the northern, exposed end of the Confederate line. Brigadier General Alvin P. Hovey’s (North) men and the division of Major General John A. Logan (North) pushed up the road and into the timber. By about half past eleven they were against the Confederate main line, and the fight became a climb, up the slope of Champion Hill, into Major General Carter L. Stevenson’s (South) division holding the Confederate left, which was the northern end of their line. This was the flank Grant meant to break, and around one o’clock he broke it. The Union men carried the crest. Stevenson’s left came apart and fell back off the hill in disorder, and the Federals swept on down the far slope to the prize below: the crossroads. For a moment, Pemberton’s escape route up the Jackson Road was shut.' },
      { p: 'There was more to what Logan’s men had done than they knew at the time. Pushing up and across the Jackson Road, they had planted a Union division squarely across the one direct road the Confederate army could use to reach its crossing over Baker’s Creek. The men who had helped take the hill were now, without quite realizing it, standing on the road home, and that fact would decide the fate of a whole Confederate division before the day was out.' },
      { h: 'The Hill of Death', eyebrow: 'The cost on Hovey’s division' },
      { p: 'The man whose soldiers paid the most to take that crest gave it the name that stuck. Hovey’s (North) division bore the brunt of the day’s killing, and afterward Hovey himself, walking the ground he had won, wrote it down plainly:' },
      { p: '“Champion Hill was, after the battle, literally the hill of death. Men, horses, cannon, and the debris of an army lay scattered in wild confusion.”', q: true },
      { p: 'Brigadier General Alvin P. Hovey', i: true },
      { p: 'The ground those men climbed for was a slaveholding plantation. The hill was named for the family that owned it, and the county around it was worked by enslaved people, the same human property the Confederacy had been founded to keep. The army Hovey’s men broke on that crest existed to defend that arrangement. The hill of death was a hill on a plantation, and that was not incidental to the war; it was the war.' },
      { h: 'The Crest and the Crossroads', eyebrow: 'Outcome · the morning fight' },
      { p: 'The right blow in the right place: not the heaviest part of the army, but the part aimed at the flank that held the road home.', i: true },
      { p: 'Grant’s main effort up the Jackson Road broke Stevenson’s division, carried the seventy-five-foot crest of Champion Hill by about one o’clock, and pressed on to take the crossroads below, briefly closing Pemberton’s best line of retreat to Vicksburg and planting Logan’s division across the army’s only direct road to the creek. The cost fell hardest on Hovey’s division, the hill of death.' },
    ],
    meanwhile: { region: 'The southern roads', title: 'A whole corps standing still', body: 'While Hovey and Logan were climbing the hill, Major General John A. McClernand’s (North) two southern columns sat nearly still on the Middle and Raymond Roads. Grant sent orders forward to press the attack there; for most of the day the orders went unanswered, and McClernand barely engaged. Hovey’s division, under Grant’s own hand, lost more than six hundred men, while two of McClernand’s idle divisions lost a combined nine. It was the great Union missed opportunity of Champion Hill, a whole corps standing still while a near-even fight was decided a mile to the north. Had those columns pressed Pemberton’s right at the same time, the Confederate army might have been crushed on the field instead of merely beaten off it. As it was, Grant won the battle with half the army he had brought to it.' },
  },

  'the-hill-changes-hands': {
    eyebrow: 'Champion Hill · The counterattack',
    title: 'Bowen’s Charge and the Crest Retaken',
    blocks: [
      { p: 'Pemberton’s army had its own best weapon, and now he used it. Major General John S. Bowen (South) commanded the finest division in the Confederate force, hard-fighting Missourians and Arkansans, and Bowen threw them straight at the men who had just taken the hill. Between two and half past two in the afternoon his line slammed into Brigadier General Alvin P. Hovey’s (North) soldiers, men who had been climbing and fighting since mid-morning and had nothing left in their legs, and rolled them back.' },
      { p: 'For the men on that slope it was the third trip up the same ground in a few hours, and the worst. The Missourians and Arkansans came on through their own dead and over the crest the Federals had just bled to take, close enough that the lines fired into each other at a few paces, and drove the exhausted Union men back down the hill and nearly to the Champion house at its foot. There was no maneuver left in it and no cleverness, just two lines of worn-out men shoving each other up and down a hill of corpses for the better part of an hour. At the height of it the crest of Champion Hill and the crossroads below it were back in Confederate hands.' },
      { p: 'But Bowen had too few men to keep what his charge had taken. He had broken the Union line and seized the ground, and there was nothing behind him to hold it with. A counterattack is only as good as the reserve that follows it, and Bowen had outrun his. The crest he had retaken he could not garrison; that is, he had no fresh troops to leave on it to hold it.' },
      { p: 'Grant had what Bowen lacked: a fresh division in hand. He fed in the reserve, Brigadier General Marcellus Crocker’s (North) men, straight into the path of Bowen’s surge. The fresh Union line stopped the Missourians and Arkansans, then began to push them back up and over the same slope yet again. The Federals retook the crest and retook the crossroads, and this time they kept them. Champion Hill had changed hands three times in a few hours, Union, then Confederate under Bowen, then Union again, and the last hands on it were Grant’s.' },
      { p: 'That was the battle. With the crossroads gone for good and the army’s flank caved in, and with Major General John A. McClernand (North) at last beginning to lean on the southern end of the line, Lieutenant General John C. Pemberton (South) had no choice left but to get what remained of his army off the field before it was surrounded. The decision was forced on him by the loss of a single crest and the road junction it commanded. He ordered the retreat.' },
      { h: 'The Last Hands on the Hill', eyebrow: 'Outcome · the counterattack' },
      { p: 'The hardest fighting of the day: a counterattack that won the ground but could not keep it.', i: true },
      { p: 'Bowen’s charge briefly retook the crest and the crossroads in the hardest fighting of the day, but he could not hold what he had won without a reserve. Grant’s fresh division under Crocker stopped the surge and took the ground back for good; the hill and crossroads changed hands three times before settling with the Union. With his only good escape road in Federal hands, Pemberton had to abandon the field, and the field battle for Vicksburg was lost.' },
    ],
    meanwhile: { region: 'Inside the Confederate command', title: 'A feud that cost an army', body: 'While Bowen’s men were dying to retake the hill, the southern end of the Confederate line was held by Major General William W. Loring (South), and Loring would not move. Pemberton sent order after order for Loring to march north and reinforce the collapsing left. Loring insisted he faced a strong Federal force on the Raymond Road and could not stir, then moved far too late to make any difference. The blame ran both ways and never stopped running, but the effect was simple: a third of Pemberton’s army, a whole division of it, stood idle on the wrong end of the line while the other end was overrun. The same division that would not march to save the hill was about to march out of the campaign entirely.' },
  },

  'the-lost-division': {
    eyebrow: 'Champion Hill · The doom of the city',
    title: 'Across Baker’s Creek, and the Division Lost Forever',
    blocks: [
      { p: 'A beaten army’s worst moment is usually the retreat, and everything Lieutenant General John C. Pemberton (South) had to fear was waiting behind his line: Baker’s Creek, running north to south between the battlefield and Vicksburg, with the army needing to cross it to escape. And here the morning’s fighting came due. Major General John A. Logan’s (North) division had cut the Jackson Road, the direct way to the crossing, so Pemberton’s only road left over the creek was a single bridge on the Raymond Road, to the south. Getting the whole army over that one bridge before Grant’s men arrived was now the only thing that mattered. The job of holding it open fell to the rearguard, Brigadier General Lloyd Tilghman’s (South) brigade, posted at the creek to buy time with their bodies while the rest of the army filed across. A Union artillery shell struck and killed Tilghman at the crossing.' },
      { fig: '/war-img/champion-hill-retreat.png', cap: 'Dusk: Pemberton’s army escapes southwest over the lone Raymond Road bridge across Baker’s Creek, while Loring’s division, cut off by Logan on the Jackson Road, peels away to the southeast and marches clean around the Union army out of the war.', credit: 'Stuff Happened map' },
      { p: 'Most of Pemberton’s army got over. By late afternoon Grant’s troops had seized the Baker’s Creek bridge themselves, and by midnight they held Edwards Station, the little depot to the east. The Confederate army that had stood on the ridge that morning was streaming southwest toward Vicksburg, broken but largely intact, except for one division, and that exception decided the war in Mississippi.' },
      { p: 'Loring’s (South) division, the one that had refused to march all afternoon, came back too late to its own salvation. By the time it turned to follow the army, the single Raymond Road bridge was lost and Union troops sat across the Jackson Road behind it; there was no crossing left for Loring to take. So a whole division of the Confederate army, thousands of men who had barely been bloodied that day, simply turned away from the war they were in. Rather than fight through, Loring peeled his column off to the south and east, marched it clear around the outside of the Union army through the night, and kept going until he reached Johnston (South) near Jackson. He never recrossed the creek. He never rejoined Pemberton. He never entered Vicksburg.' },
      { p: 'The two endings sat side by side. Pemberton walked back into the fortress city to stand the siege of his life, and he walked in a full division short, thousands of men he would need on the works simply not there, gone without a battle to show for it. And somewhere off to the southeast, in the dark, those same thousands were tramping the long way around to another general’s camp, alive, intact, and lost to the cause they were marching for as surely as if they had been killed on the hill. It was the strangest casualty of the day: a loss with no body count to put on a return.' },
      { h: 'Why One Day Decided the Campaign', eyebrow: 'The cost' },
      { p: 'This one day on a plantation hill decided the whole campaign. Champion Hill was the day Grant beat Pemberton in the open, the decisive field battle of the operation, the fight that settled the campaign before the siege ever began. The Confederates lost something like 3,840 men to the Union’s 2,457, and the shape of those losses matters: the killed and wounded were close on both sides, but the Confederate total is blown out by roughly 2,441 men missing or captured, the price of a broken army funneling back across a single creek. It is frequently called the bloodiest single day of the entire Vicksburg campaign. The deepest cost, Loring’s vanished division, never made it onto a casualty return at all.' },
      { p: 'From there the end came fast. The next day Grant’s men ran Pemberton’s rearguard off the field at Big Black River Bridge, the last river crossing before the city, and on May 18 the beaten army was shut up inside Vicksburg’s works. The forty-seven-day siege that followed, ending in the surrender of the city and its garrison (the troops defending it) on the Fourth of July, ran straight out of this hill. When the city fell, slavery fell with it there, the great river opened along its whole length from the North down to the Gulf of Mexico, and the Confederacy was cut in two. All of that was decided, in the open, on the sixteenth of May, on the crest of a slaveholders’ plantation, over a crossroads, in a near-even fight that Grant won because of where he put the blow. Grant himself never doubted what the day had bought. He had ended it, he wrote, with his army planted between Johnston and Pemberton, with no possibility of the two Confederate forces ever joining, which had been the whole point of the campaign from the start.' },
      { pill: '/war-civil-war/western/vicksburg', plabel: 'Vicksburg: the siege and the surrender Champion Hill set in motion' },
      { h: 'The Day That Doomed Vicksburg', eyebrow: 'Outcome · the battle' },
      { p: 'A decisive Union victory, and the day the campaign to split the slaveholders’ republic was actually decided.', i: true },
      { p: 'Grant beat Pemberton in the open in a near-even fight, broke his army off the field, and cut an entire Confederate division (Loring’s) away from it forever, a loss with no body count, the price of Logan’s men holding the Jackson Road and the lone Raymond Road bridge falling to the Federals. Pemberton fell back into Vicksburg short a division and out of options; the siege and the July 4 surrender followed within weeks. Champion Hill is the battle where the campaign to take Vicksburg, and to split the slaveholders’ republic in half, was actually decided.' },
    ],
    meanwhile: { region: 'A thread to the surrender', title: 'The man who almost saved the hill', body: 'The Confederate officer whose charge nearly won the crest back, Major General John S. Bowen (South), would carry the thread of this battle all the way to its end. Seven weeks later it was Bowen who helped carry the surrender flag out of Vicksburg, and days after that he was dead of dysentery. The man who almost saved the hill lived just long enough to give the city away. Champion Hill did not end at Champion Hill; it ended on the Fourth of July, on the Mississippi River, with the Confederacy cut in two and a slave city freed.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={CHAMPION_HILL_NARR} id={id} slug="champion-hill" battleName="Champion Hill" theatreId="west" theatreHref="/war-civil-war/western" battleId="w-championhill" accent="#1d4ed8" />
}
