'use client'

// The Raid on Fort Frontenac (August 1758), battle sections. Produced through the war
// content pipeline (audits/war-content-pipeline.md): fact pack → author (Opus) →
// critic gates (fact-check + storytelling + comprehensiveness + clarity + fairness,
// parallel) → reconcile → revise. Data only; rendered by the shared
// <BattleSectionReader>. House voice: no em-dashes; British/French side-tags once on
// first mention per section; the ground named as Haudenosaunee country and the ~70
// Onondaga and Oneida warriors named by nation (anti-erasure). Sources:
// audits/war-pipeline/fi-frontenac-*.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const FRONTENAC_NARR: Record<string, Narr> = {
  'the-lynchpin-on-the-lake': {
    eyebrow: 'Fort Frontenac · The depot on the water',
    title: 'The lynchpin on the lake',
    blocks: [
      { p: 'Look at a map of French Canada in the middle of the eighteenth century and you find a long, thin lifeline of water. It runs up the St. Lawrence River from Quebec City and Montreal, the two great eastern centers, and then it has to reach a thousand miles into the interior, out to the forts strung across the Great Lakes and down into the Ohio Country. Everything the western posts needed (food, powder, trade goods, the cloth and coats and knives that bought the friendship of Native nations) had to travel that line. And the place where the river opened into the lakes, the gate the whole western system hung on, was a fort at a spot the French called Cataraqui, on the eastern end of Lake Ontario where the lake pours back into the St. Lawrence. The ground was Haudenosaunee land, the country of the Six Nations of the Iroquois, long before either crown drew a line on it. Today it is Kingston, Ontario. Then it was Fort Frontenac.' },
      { p: 'Frontenac was not much to look at by 1758. It was an aging stone fort, its walls crumbling, in poor condition. But what it was mattered far more than how it looked. It was a depot, the hinge of French communications and supply on Lake Ontario. Goods came up the river to Frontenac and went out across the lake from there to the western posts. It was one of only two real supply roads from the eastern heart of Canada to the west; the other ran up the Ottawa River. Cut Frontenac, and you cut half the lifeline, the half that fed Lake Ontario, the lake forts, and the Ohio Country posts farther on, including Fort Duquesne, the French stronghold at the Forks of the Ohio that had humiliated the British more than once.' },
      { p: 'The French felt safe there, and they had a reason to. Two years earlier, in 1756, they had taken away the one thing that could have threatened the fort. On the south shore of Lake Ontario, directly across the water from Frontenac, the British had held a base of their own called Fort Oswego. In 1756 the French commander Louis-Joseph de Montcalm (French) crossed the lake, besieged Oswego, took it, and destroyed it. With Oswego gone, the British had no foothold on Lake Ontario and no fleet there. The French had vessels on the lake and the British did not, and so the governor of New France, the Marquis de Vaudreuil, simply did not believe the British would dare put boats on Lake Ontario at all. The lake was a French lake. Frontenac sat on it, loaded with stores, behind a wall of water nobody expected the enemy to cross.' },
      { pill: '/war-french-indian/battles/fort-oswego', plabel: 'Oswego, the British base Montcalm destroyed in 1756' },
      { p: 'That was the picture the British had to change in 1758, and the man in London who meant to change it was William Pitt, the minister who had taken hold of the war and was pouring men and money into North America for a coordinated set of offensives. Pitt’s plan was to hit New France everywhere at once. It did not all go well. In July of 1758 the British threw themselves at Fort Carillon (later Ticonderoga) on Lake Champlain and were beaten badly, a bloody, demoralizing repulse. The summer needed a win. And one British officer had been waiting years for exactly this opening.' },
    ],
    meanwhile: { region: 'The Ohio Country', title: 'A fort fed from far away', body: 'Fort Duquesne, the French post at the Forks of the Ohio, was hundreds of miles from any French farm. It could not feed itself. Its provisions, its powder, and above all the trade goods that kept its Native allies in the fight all came down the supply line from the east, and a great deal of that line ran through Frontenac. A garrison that far out lived on what the depots sent it. Starve the depot and you starve the fort.' },
  },

  'bradstreets-raid': {
    eyebrow: 'Fort Frontenac · The bold strike',
    title: 'Bradstreet’s raid',
    blocks: [
      { p: 'The officer was Lieutenant Colonel John Bradstreet (British), and he had been thinking about Fort Frontenac for years. Born in Nova Scotia in 1714 to a British army officer and an Acadian mother, he had made his name at the 1745 siege of Louisbourg. What gave him his idea, though, was supply work on the water. In 1755 he ran the boat convoys that kept Fort Oswego fed, hauling provisions up the inland route to the British base on Lake Ontario, and from there he had seen with his own eyes what Frontenac was: the throat of the whole western trade. Take it, he argued, and you choke the French west. (He would not be made deputy quartermaster general, the senior officer in charge of moving an army’s supplies, until January 1758, well after he first understood the lake.)' },
      { p: 'He lobbied for the raid for years, even offering to pay for it himself and be reimbursed only if it worked, and for years the answer was no. The reason it was a hard yes is the whole point of the plan: it meant rowing an army straight out onto a lake the French navy controlled, with no British fleet anywhere on the water to cover the crossing. If the French ships caught the boats in the open, the whole force could be lost. That was the gamble British command would not take, year after year. When the defeat at Carillon left them desperate for any success, Bradstreet finally got his yes.' },
      { p: 'What he asked for was not a regular army. It was a raid, fast and light, and the men who would make it were mostly not the king’s full-time professional soldiers, the regulars. They were provincials, the part-time troops raised in the colonies, drawn from New York, New Jersey, and New England, along with the bateaumen, the boat crews who could handle a bateau, the flat-bottomed riverboat that Bradstreet’s whole plan rode on. His force came to roughly three thousand men, with only a small core of regulars (somewhere around a hundred and fifty), a handful of artillerymen, and about seventy Native warriors. Those warriors were Onondaga and Oneida fighters of the Six Nations, the Haudenosaunee Confederacy whose country the whole campaign crossed, and they came on their own terms: about half the Onondaga turned back along the way, and Bradstreet held the rest only by promising the Oneida first claim on any plunder. It was a provincial army, the kind of force the British regulars looked down on, sent to do what the regulars had not thought worth trying.' },
      { p: 'They went the way Bradstreet knew, the inland water route across upstate New York: up the creeks and lakes to Oswego on the south shore, the whole journey running better than four hundred miles with long stretches where the boats had to be carried overland around rapids. He lost men to desertion along the way, but he kept the column moving and reached the lake. Then came the part Vaudreuil had thought no one would try. Bradstreet put his army into the bateaux and rowed them straight out onto Lake Ontario, the French lake, and across it toward Frontenac.' },
      { p: 'On August 25, 1758, the flotilla landed about a mile from the fort, and not a shot was fired to stop it. The surprise was total. Inside Frontenac the situation was hopeless and everyone in it knew it. The garrison was tiny, about a hundred and ten people, and that number included women and children; the soldiers who could actually fight were fewer still. The fort had sixty cannon and not enough men to work even a dozen of them. The walls were decayed. Help from Montreal had not even been organized yet, and when it finally set out it would not arrive until after the first of September, a week too late. Commanding this was Pierre-Jacques Payen de Noyan (French), an aging veteran in his early sixties, a soldier of the old colonial wars handed the keys to a fort that could not be held.' },
      { p: 'Bradstreet did not rush it. The night after landing his men hauled their guns ashore, set up batteries, and dug trenches working in toward the walls. They tried, and failed, to row out and board the French ships anchored before the fort. On the morning of August 26 the British cannon opened up, and there began a short, lopsided bombardment, British guns hammering a fort that could barely answer.' },
      { p: 'Picture the old man inside it. Noyan was past sixty, a soldier of the old colonial wars, and he had been handed a fort he could not hold: walls that were falling down on their own, sixty cannon and not enough living hands to work even a dozen of them, women and children sheltering behind the stone with the soldiers. He watched the British batteries find their range and pound his crumbling wall with almost nothing of his own to fire back, no help on the road from Montreal, no fleet, no way out. There is no version of this where he holds. After a brief council of war, the white flag went up. The fort surrendered on the morning of August 27, two days after the British stepped ashore. The whole thing cost Bradstreet’s army almost nothing, a handful of men wounded and, by the fullest account, not a single life. Two French defenders were killed.' },
      { p: 'Noyan and his garrison were taken prisoner. Because of his poor health the old commander was paroled to Montreal, and from there a prisoner exchange was arranged: Noyan and his people for Colonel Peter Schuyler, a New Jersey officer the French had been holding, swapped back across the lines. Noyan went home to a bitter retirement.' },
    ],
    meanwhile: { region: 'New France', title: 'The lake nobody guarded', body: 'Vaudreuil had been so sure the British would never put boats on Lake Ontario that the depot holding half the western supply was left with a skeleton garrison and decaying walls. The confidence was the weakness. The very thing that made Frontenac feel safe, French command of the water, was the thing that made it fatal when the British crossed the water anyway and found almost no one home.' },
  },

  'the-blow-to-the-west': {
    eyebrow: 'Fort Frontenac · The supply line cut',
    title: 'The blow to the west',
    blocks: [
      { p: 'The fort itself was the smallest part of the prize. What Bradstreet had captured was the contents of the western war. Riding at anchor or harbored at Frontenac was the French fleet of Lake Ontario, the very vessels that had made the lake French. By the fullest account it was nine sloops, armed lake warships, the entire naval force on the lake, taken in a single morning. Inside the walls were the sixty-odd cannon, and among them, in a neat reversal, British guns that the French had captured at Oswego two years before, now changing hands a second time. And then there were the stores. Hundreds of barrels of provisions. Bales of furs and deer skins waiting to be shipped east to Montreal. Bales of cloth, and as Bradstreet’s own report listed it, “Laist [laced] and plain Coats and Shirts of all sizes.” It was a depot at full load, the food, the goods, and the trade stock meant to keep the whole French west supplied and its Native alliances bought through the coming year. Bradstreet put the value of the haul at thirty-five thousand pounds, or eight hundred thousand French livres.' },
      { p: 'Bailes of Cloth[,] Laist [laced] and plain Coats and Shirts of all sizes[,] a great Number of Dear skins and fur of all sorts.', q: true },
      { p: 'His orders were not to hold the place. He had three thousand men deep in French territory with French reinforcements somewhere behind him, and he had no intention of being besieged in a fort he had just proven could not be held. So he wrecked it. He loaded what two of the captured sloops could carry, sank the rest of the fleet, disabled the cannon he could not take, burned the buildings and the stores he could not carry off, broke down the walls, and rowed back across the lake the way he had come. In a matter of days the hinge of French Lake Ontario had gone from the safest depot in the west to a burned ruin with its fleet on the bottom of the harbor.' },
      { p: 'The meaning of it traveled fast and far. Bradstreet understood exactly what he had done, and said so plainly in his report.' },
      { p: 'Their troops to the southward and western garrisons will suffer greatly, if not entirely starve, for want of the provisions and vessels we have destroyed.', q: true },
      { p: 'He was right, though not all at once. The line west had been cut at the throat: the lake fleet that carried goods to the western posts was gone, and the depot that loaded them was ash. But it was only one of the two supply roads, and the other, the harder route up the Ottawa River, stayed open. That is why the French west did not collapse overnight. The blow starved the Ohio posts first and worst, Fort Duquesne most of all, while some of the Great Lakes posts hung on into 1759 on what could still be pushed up the Ottawa. Every French fort that had lived on Frontenac was now living on what it already had, with little hope of more. Montcalm, looking at it from the east, judged the loss serious. And nowhere did the cut bite harder than at the far end of the line, at Fort Duquesne.' },
      { pill: '/war-french-indian/battles/fort-duquesne', plabel: 'Fort Duquesne, the western fort Frontenac had been feeding' },
      { p: 'Fort Duquesne sat hundreds of miles out at the Forks of the Ohio, and it had no way to feed itself. It depended on supplies sent from the east, and a great deal of what it depended on had just been burned at Frontenac or sunk in its harbor. That autumn a British army under Brigadier General John Forbes, the third prong of Pitt’s 1758 offensive aimed squarely at the Forks, was grinding its way west, slow and methodical, cutting a road through Pennsylvania. The French garrison at Duquesne, already low on provisions and now with the supply line behind it severed, could not hope to be reinforced or fed through a siege. In late November 1758, rather than be trapped and starved in a fort they could no longer supply, the French blew up Fort Duquesne and abandoned it. The British walked into the smoking ruin and began building Fort Pitt on the spot; the town that grew there became Pittsburgh. The fort that had beaten Braddock to pieces in 1755 was given up without a fight, and one large reason was a depot burning on a lake three hundred miles to the north.' },
      { pill: '/war-french-indian/pitts-turn', plabel: 'Pitt’s 1758 offensive, the year the war began to turn' },
      { p: 'It is worth marking what this raid was, because it was so unlike most of what had come before. There was no slaughter, no heroic last stand, almost no blood at all. A provincial army that the regulars had sneered at had rowed across a lake nobody believed they would cross, surprised a fort nobody believed they could reach, and in two days, for the cost of a few wounded men, cut one of the two arteries of New France and helped doom a fort hundreds of miles away that British armies had failed to take by force. After the long string of British disasters, after Braddock and Oswego and Carillon, Frontenac was the kind of win the war had been waiting for, the moment the supply lines started running the British way and the French west began to come apart from the inside.' },
    ],
    meanwhile: { region: 'The Forks of the Ohio', title: 'A fort starved, not stormed', body: 'The British had bled badly trying to take Fort Duquesne by direct assault. In the end they did not have to. By severing the line that fed it, Bradstreet’s raid did to Duquesne from three hundred miles away what no battle there had managed up close. The French abandoned and destroyed it themselves rather than be starved out, and the Forks of the Ohio passed to Britain without the storm everyone had expected.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={FRONTENAC_NARR}
    id={id}
    slug="fort-frontenac"
    battleName="Fort Frontenac"
    theatreId="fi-battles"
    battleId="fi-frontenac"
    theatreHref="/war-french-indian/battles"
    accent="var(--fi-battles)"
    endHref="/war-french-indian?theatre=fi-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
