'use client'

// SECTION narrative (level 4) — a standalone reader chapter for one Gettysburg
// section. Matches the reader-engine shape from the handoff: sticky ChapterHeader
// (eyebrow + title), a cross-modal LineageStrip (war↔civ), an article
// with a drop cap + SectionHeader subsections + inline figures (the day maps),
// and a docked "Meanwhile" card. Standalone prototype; the real reader engine
// integration comes later. Person side-tags applied per the standing rule.
//
// REDONE 2026-05-23 through the full war content pipeline (fact pack → 3 author
// agents → THREE gates [fact-check + storytelling critic + comprehensiveness
// critic] → revise → integrate). The v0 came straight from the design mockup and
// never saw a gate; it was over-tactical, human-light, and had unverified claims.
// Source + gate records: audits/war-pipeline/gettysburg-*.md. The comprehensiveness
// gate (new this session) added: Harrison the spy, Ewell declining Cemetery Hill
// (with the Lost-Cause framing), the Confederate slave-hunt during the march north,
// the "Pickett's Charge" misnomer, and the turning-point mechanism.

import { BattleSectionReader } from '@/components/mode/battle-reader'

type Block =
  | { h: string; eyebrow?: string }
  | { p: string; i?: boolean; q?: boolean }
  | { fig: string; cap: string; credit: string }

interface Lineage { label: string; mode: 'war' | 'civ' }
interface Narr {
  eyebrow: string
  title: string
  progress: number
  from: Lineage[]
  to: Lineage[]
  blocks: unknown[]
  meanwhile?: { region: string; title: string; body: string }
}

const GB_NARR: Record<string, Narr> = {
  setting: {
    eyebrow: 'Gettysburg · Lay of the land',
    title: 'How they got there',
    progress: 0.05,
    from: [{ label: 'Eastern Theatre', mode: 'war' }, { label: 'Chancellorsville', mode: 'war' }],
    to: [{ label: 'McPherson’s Ridge', mode: 'war' }],
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -78.3, lonMax: -76.3, latMin: 39.3, latMax: 40.8 },
        states: [
          { name: 'Pennsylvania', tone: 'focus', label: 'PENNSYLVANIA', labelLon: -78.1, labelLat: 40.7 },
          { name: 'Maryland', label: 'MARYLAND', labelLon: -76.5, labelLat: 39.4, labelSize: 13 },
          { name: 'Virginia' },
          { name: 'West Virginia', label: 'WEST VIRGINIA', labelLon: -78.1, labelLat: 39.4, labelSize: 13 },
          { name: 'New Jersey' },
        ],
        dots: [
          { name: 'Gettysburg', date: 'Jul 1–3, 1863', lat: 39.811, lon: -77.231, heavy: true, anchor: 'middle', dy: 24 },
          { name: 'Cashtown', lat: 39.836, lon: -77.363, color: '#8a8175', anchor: 'end' },
          { name: 'Chambersburg', lat: 39.938, lon: -77.661, color: '#8a8175', anchor: 'end' },
          { name: 'Harrisburg', lat: 40.273, lon: -76.886, color: '#8a8175', anchor: 'middle', dy: -16 },
        ],
      } },




      { h: 'Late spring, 1863', eyebrow: 'Setting' },
      { p: `In May of 1863, Robert E. Lee did something his army had never done. He decided to invade the United States.` },
      { p: `He was doing it from the high-water mark of his career. About a month earlier, at Chancellorsville in Virginia, Lee had attacked a Union army roughly twice the size of his own and beaten it badly. It was the kind of victory that makes a general feel briefly invincible and gets very dangerous ideas taken seriously. Instead of waiting in worn-out Virginia for the next blow to fall, Lee proposed marching the Army of Northern Virginia the other way: north, across the Potomac River, into Pennsylvania, onto Northern ground.` },
      { p: `The reasons were real and they were many, which is part of why it was so hard to argue him out of it. Virginia had been the war’s battlefield for two years and had been picked clean; an army that lived off the land needed land that still had something on it, and Pennsylvania’s farms were fat with the summer’s grain and cattle. A Confederate army loose in the North might draw Union troops away from Vicksburg, the river fortress hundreds of miles to the southwest that Ulysses S. Grant was slowly strangling. It might frighten Northern voters and Northern bankers. It might, if Lee won a big enough victory on Northern soil, finally push Britain or France to recognize the Confederacy as a country, to treat the South as a real nation instead of a rebellion, with everything that came with it: trade, money, maybe even help.` },
      { p: `That was the whole, honest case. It was not, as the legend later had it, an army gone shopping. Lee was reaching for the things that win wars without being battles.` },
      { p: `They left for the North on June 3rd.`, i: true },

      { h: 'Three states, and what the army carried', eyebrow: 'The march' },
      { p: `Lee took his army up the Shenandoah Valley, the long green corridor running northeast through Virginia toward Pennsylvania, the same valley Stonewall Jackson had marched up and down until weeks before, when he was shot by his own men at Chancellorsville and died of it. By the third week of June the Army of Northern Virginia was loose in Pennsylvania: better than seventy thousand men spread across miles of farm country, taking what they needed and, by Lee’s strict orders, trying not to burn or wreck what they didn’t. This was supposed to be the army that proved the South could be a nation. Nations don’t sack the countryside; that was the theory, anyway.` },
      { p: `That was not the whole of what the army did. The Confederacy was fighting to keep human beings as property, and as it marched north it carried that war aim with it in the most literal way there is. Acting under orders sent from Richmond that spring about “fugitive slaves,” the cavalry riding in front of the army (Brig. Gen. Albert Jenkins’s (South) Virginia horsemen, and others) seized free Black people across Maryland and Pennsylvania and sent them south into slavery. Not a handful. Hundreds: men, women, and children, swept up out of towns like Mercersburg and Chambersburg and the country around Gettysburg, many of them free-born people who had never been enslaved at all. A soldier in the 4th Georgia (South) wrote home, plainly and without shame, that the army had “captured… over a hundred negroes.” The army that had come north to win a country built on slavery brought slavery north with it, in chains, on the same roads as the grain and the cattle.` },
      { fig: '/war-img/gettysburg-campaign.png', cap: 'The march north: Lee takes the Shenandoah Valley into Pennsylvania while the Army of the Potomac shadows him east of the mountains.', credit: 'Stuff Happened map' },
      { p: `Trailing him, on the eastern side of the mountains, came the Army of the Potomac (the United States’ main army in the East) under Maj. Gen. Joseph Hooker (North). It moved slowly and argued with Washington the whole way. Hooker had been the loser at Chancellorsville, his confidence was gone, and his superiors had stopped trusting him. On June 28th, three days before the battle, the feud ended the only way it could: Hooker resigned.` },
      { p: `He was replaced overnight by one of his own corps commanders (a corps is a large self-contained chunk of an army, tens of thousands of men under a single general), a sober, reliable Pennsylvanian named George G. Meade (North). Meade had not asked for the job and had not been told he was even being considered. He took command three days before the largest battle of the war, in his own home state, with no clear idea where the enemy was.` },

      { h: 'A town with ten roads', eyebrow: 'Why here' },
      { p: `That last part went both ways. Lee was just as blind. His cavalry (the army’s eyes, the horsemen who ride ahead and report where the enemy is and isn’t) was led by the flamboyant J.E.B. “Jeb” Stuart (South), and Stuart had taken it off on a long, glory-seeking ride clear around the Union army. For days, at the worst possible moment, Lee was marching an army through enemy country without being able to see. He did not know where the whole Army of the Potomac was, or that it was closing on him.` },
      { p: `Nobody planned to fight at Gettysburg. It was a small market town in south-central Pennsylvania, roughly twenty-four hundred people in 1860, a Lutheran seminary, a college, nothing of any military value. What it had was roads. Ten of them came together there, radiating out like spokes from a wheel hub. In an age when armies moved at the speed of a walking man on a dirt road, a place where ten roads met was a place an army could reach fast, leave fast, and feed itself from in every direction. Whichever side got there first and held the high ground around it could make the other side do the attacking: uphill, across open fields, into prepared guns. That was the only thing Gettysburg was worth, and it turned out to be worth a great deal.` },
      { p: `What ended Lee’s blindness was not a cavalry report. It was a spy. On the night of June 28th, a scout named Henry Thomas Harrison (a shabby, theatrical man working for Lt. Gen. James Longstreet (South)) walked into camp with the thing Lee had been missing for a week. The Union army, Harrison said, had crossed the Potomac into Maryland and was already moving north toward him, fast; and the man leading it was no longer Hooker but Meade. Lee had never much trusted Harrison. This time he believed him, because he had nothing else, and because it fit the cold feeling that he had let the enemy get too close. He gave the order to pull his scattered army together near Cashtown, a village about eight miles west of a road hub called Gettysburg. Years later, looking back, Lee wrote that “a battle thus became, in a measure, unavoidable.” Two armies that had each been groping for the other in the dark were now reaching for the same patch of ground, and neither one fully knew it yet.` },
      { p: `It would last three days, leave roughly fifty thousand men killed, wounded, or captured, and decide whether the Confederacy got to keep existing.`, i: true },
    ],
    meanwhile: { region: 'London', title: 'The cotton ministers are watching.', body: 'In Westminster, Confederate envoys are pressing the British government for the recognition the South has wanted since 1861: for Britain to declare the Confederacy a real country. The Foreign Office keeps telling them the same thing: wait for the next great victory, the one that proves the South can win. The men who marched into Pennsylvania were marching, in part, to give them that victory. They are about to be waiting forever.' },
  },

  mcpherson: {
    eyebrow: 'Gettysburg · Day 1 of 3',
    title: 'McPherson’s Ridge',
    progress: 0.28,
    from: [{ label: 'How they got there', mode: 'war' }],
    to: [{ label: 'The Hooks', mode: 'war' }],
    blocks: [
      { h: 'A man who picked his ground', eyebrow: 'First contact, July 1' },
      { p: `The reason there was anything in Gettysburg to stop the Confederate army was one stubborn cavalry officer who had arrived the day before and decided, on his own, that this was the place.` },
      { p: `John Buford (North) was a Union cavalry general (cavalry are soldiers who fight on horseback, used as scouts and fast-moving troops). He had ridden into Gettysburg on June 30th with about twenty-seven hundred troopers and looked at the ground the way Buford looked at ground: not for where to camp, but for where to fight. He saw the ridges west of town (low rises a defending line could hide behind and shoot from) and the roads the Confederates would have to come down to reach them. He saw what the whole battle would later prove: that this was good ground, and that the army holding it could force the other army to bleed for it. And he understood the one thing his cavalry could not change. He had a couple of thousand horsemen. Lee had seventy thousand men coming. Cavalry could not win here. It could only buy time, holding the ridges long enough for the Union infantry, still hours down the road to the south, to arrive and turn a delaying action into a battle.` },
      { p: `Buford’s troopers had one advantage that mattered enormously for the next few hours: their weapons. They carried breech-loading carbines, short rifles that loaded at the back end (the breech), so a man could reload lying down and fire several shots in the time it took a Confederate infantryman to reload his muzzle-loading musket from the front. A dismounted cavalry line was thin, but for a few hours it could throw out fire as if it were thicker than it was. Buford spread his men along the ridges, told his officers the rebels would come at dawn, and waited for the morning to prove him right.` },

      { h: 'The first shots', eyebrow: '~7:30 a.m.' },
      { p: `Coming the other way down the Chambersburg Pike was Henry Heth’s (South) division, roughly seventy-six hundred Confederate infantry, far more men than Buford had. (A division is several brigades together, a brigade several regiments; in this war a division might run five to eight thousand men.) Heth’s move was a reconnaissance in force, a probe in strength to find the enemy, not the shoe-hunting raid of legend. Like Lee, Heth was half-blind. He had been told there might be local militia in the town. He did not believe veteran Union cavalry was anywhere near him, and he came on without enough caution.` },
      { fig: '/war-img/gettysburg-day1.png', cap: 'July 1: Buford’s cavalry delays Heth west of town until the infantry arrives; by evening the Union is pushed back to Cemetery Hill.', credit: 'Stuff Happened map' },
      { p: `A little after seven in the morning, Buford’s pickets opened fire from behind a fence rail in the gray light. The shooting was uneven, then steadier, then unmistakable. Heth deployed for what he thought was a brush with militia and discovered, the hard and slow way, that he was fighting dug-in regulars who would not break and run. By the time he understood what he had walked into, he had committed himself, and through him, piece by piece, he was committing Lee, to a fight on ground the Confederate army had not chosen, started by an encounter no one above him had ordered. The battle grew from a collision, each side feeding in more men to support the men already fighting, until two armies that had been hunting each other in the dark were locked together and could not let go.` },

      { h: 'Reynolds, dead in the first hour', eyebrow: '~10:15 a.m.' },
      { p: `Buford’s cavalry held the ridges through the early morning, fighting and falling back, fighting and falling back, trading ground for the minutes the infantry needed. And then, near mid-morning, the infantry came.` },
      { p: `At the head of it rode Major General John F. Reynolds (North), the senior Union corps commander on the field and one of the most respected soldiers in the army. Reynolds saw what Buford had been holding and decided it was worth holding. He hurried his I Corps forward into the fight himself, riding up close to the firing, personally shoving regiments into line, among them the Iron Brigade, Indiana and Michigan and Wisconsin men who had earned their hard name at South Mountain the autumn before, for standing in a fight that should have broken them and not breaking.` },
      { p: `He was placing those men at the edge of a stand of trees, turned in the saddle to look back for the rest of the corps coming up the road, when a bullet caught him in the back of the head. He was dead before he hit the ground. One moment the general was pointing troops into the woods, the next he was a body being lifted off the field by men who could not quite take it in. The soldiers nearest him kept loading and firing for a while without knowing their general was gone, because there was no time to be told and nothing to be done if they had been. It was a little after ten in the morning. The most senior man who would die at Gettysburg was already dead, and the battle was barely three hours old.` },

      { h: 'Driven back through the town', eyebrow: 'Afternoon' },
      { p: `For a while the Union held. Then the weight came on, and the day turned into the kind of thing the men who lived through it spent the rest of their lives not describing.` },
      { p: `More and more of Lee’s army arrived faster than more of Meade’s (North) could. Heth was reinforced by Pender’s (South) division behind him; then, worse, fresh Confederate divisions under Rodes (South) and Early (South) came down from the north, folding the Union line in from a second direction at once. The outnumbered I and XI Corps, three divisions of the enemy converging on them from two ways, were now being shot at from the west and the north together, and there was no holding it. The line came apart, not all at once but in pieces, regiments giving way and the giving-way spreading.` },
      { p: `Imagine being one of those men. You have been on your feet and under fire since mid-morning; the friend who stood at your shoulder is down and you stepped over him an hour ago; your officers are dead or shouting orders no one can follow; and now the order is to fall back, back the way you came, back across the same fields, except the fields are full of your own dead and dying now, the men you marched up with that morning, and the enemy is behind you and beside you and pouring fire into the crowd you have become. The retreat carried into the streets of Gettysburg itself, soldiers stumbling between the houses of a market town, through gardens and yards and alleys, the townspeople’s families pressed into cellars while two armies fought past their front steps. Order dissolved into a mob. Men got turned around in streets they had never seen, ran into walls and fences and each other, and were taken prisoner by the hundreds because there was nowhere left to run that the enemy was not already standing.` },
      { p: `The townspeople pressed into those cellars were nearly all white. Gettysburg’s free Black community, about 186 people in 1860, concentrated in the Third Ward along South Washington and Breckenridge Streets, had read what was coming and mostly gone before the army arrived. Most had fled north toward Harrisburg or into the countryside, and white neighbors hid others in attics and barns. The Confederate cavalry had been hunting Black people throughout the march north, and it hunted them here too: some who had not gotten out in time were seized in the surrounding county and sent south into slavery, free-born people caught in the same dragnet the army had been running across Maryland and Pennsylvania since June. The community that had lived in the town did not come back whole. By 1870 fewer than half of those 186 had returned.` },
      { p: `But there was high ground south of town. A long, low rise crowned by the town’s graveyard: Cemetery Hill. The broken Union corps fell back onto it and, for the first time all day, found themselves standing somewhere strong, somewhere a beaten army could plant its feet and dare the enemy to come up after it. The day had gone badly, and the ground they ended it on was the one piece of luck in it.` },

      { h: 'Hancock holds the heights', eyebrow: 'After 4 p.m.' },
      { p: `Into that crumbling afternoon, Meade, still miles away and still not on the field, sent the one man he most trusted to think for him. Maj. Gen. Winfield Scott Hancock (North) rode ahead of the army with written authority to take command on the spot and decide a question no one else could: whether Gettysburg was a place to stand and fight at all, or whether the beaten Union army should pull back somewhere else entirely.` },
      { p: `Hancock arrived after four in the afternoon, into a swirl of retreating men and rattled officers, and did what made him one of the great battlefield presences of the war: he steadied it. He rode the cemetery heights, took in the ridges and hills running south, and saw exactly what Buford had seen at dawn. This was ground worth an army. He began grabbing the broken corps and pushing them into a line along the high ground, and he sent word back to Meade that came down to a single decision: bring the whole army here, this is where we fight. Of the position he later said, plainly:` },
      { p: `I think this the strongest position by nature upon which to fight a battle that I ever saw.`, q: true },
      { p: `They dug in along the hills and the ridge in the failing light, scraping out a line on the high ground. What they were starting to build, though no one fighting in the dark could see it yet, would by morning curl across the heights in a long, hooked shape.` },

      { h: 'The hill Ewell didn’t take', eyebrow: 'Evening' },
      { p: `What happened next on Cemetery Hill was argued over for the next fifty years.` },
      { p: `As the Union army streamed up onto Cemetery Hill in the dusk, beaten, disorganized, not yet dug in, it was, for a window of perhaps an hour or two, takeable. And on the Confederate side, the corps best placed to take it belonged to Lt. Gen. Richard Ewell (South), whose divisions had just rolled the Union line up from the north and were closest to the heights. Lee sent Ewell an order to take the hill if he could. Ewell looked at it (his men scattered and tired from a day of hard fighting, the light going, the Union gathering on the high ground in front of him) and judged that he could not, and did not attack. Overnight the Union dug in on that hill, and the next morning it was a fortress.` },
      { p: `It became one of the great what-ifs of the war: the hill that lost the battle, the attack that never came. The story most people have heard about it is a lie with a purpose, and the lie was made in stages. The famous version says Lee ordered Ewell to take the hill “if practicable” and that the timid Ewell, frozen by the word, threw away the victory. That wording, “if practicable,” first surfaced in a report Lee revised and filed in January 1864, months after the fact. And the campaign to pin the lost battle on Ewell came mostly after Lee was dead, pushed hardest by another of Lee’s generals, Jubal Early, as part of what later got called the “Lost Cause,” the long postwar effort to recast the Confederacy’s defeat as the fault of underlings rather than of Lee or of the cause itself. The plainer reading: Lee gave a discretionary order, one that in the same breath told Ewell to avoid bringing on a general engagement before the rest of the army was up. Ewell, looking at exhausted men and a strengthening enemy in fading light, made a defensible call. He may have been wrong. He was not the villain the story needed him to be.` },

      { h: 'Lee, committed', eyebrow: 'Nightfall' },
      { p: `A few miles west, on Seminary Ridge, Lee rode up in the evening and looked east at what the day had made.` },
      { p: `It was, in almost every way, the battle he had not wanted. He had not picked this town or this ground. He had stumbled into a full engagement before he was ready, still half-blind without Stuart’s cavalry, with his army strung out for miles and one of his three corps (Longstreet’s) still a hard day’s march from the field. His men had won the first day, driven the enemy through the streets, taken prisoners and ground. But the enemy he had driven was now dug in on high ground of their choosing, getting stronger by the hour as the rest of the Army of the Potomac marched through the night toward those hills.` },
      { p: `The cautious move was the one Longstreet would press on him: break contact, slip away, and force Meade to come find him on ground Lee picked. But Lee had just won a day of fighting, his blood was up, his army believed it could beat these people anywhere, and turning away now would feel like throwing away a victory already half in hand. He looked at the Union line gathering on the heights, and he decided to take it from them.` },
      { p: `He resolved to attack the next day.` },
      { p: `On the hills south of Gettysburg, in the dark, ten thousand spades bit into the same ground, and a beaten army turned itself into a wall.`, i: true },
    ],
    meanwhile: { region: 'Cemetery Hill', title: 'A battle lost into a battle won', body: 'In losing the first day, driven off the ridges, chased through the town, the Union army had backed, almost by accident, onto the strongest defensive ground on the field: the high hills and the long ridge south of Gettysburg. By morning, that line would harden into a shape that would decide the next two days. Lee had won the day. The Union had won the ground.' },
  },

  hooks: {
    eyebrow: 'Gettysburg · Day 2 of 3',
    title: 'The Hooks: Longstreet at the seams',
    progress: 0.55,
    from: [{ label: 'McPherson’s Ridge', mode: 'war' }, { label: 'Battle of Gettysburg', mode: 'war' }, { label: 'Eastern Theatre', mode: 'war' }],
    to: [{ label: 'Pickett’s Charge', mode: 'war' }, { label: 'A New Birth of Freedom', mode: 'civ' }],
    blocks: [
      { h: 'The morning after Day 1', eyebrow: 'The fishhook' },
      { p: `At dawn on July 2nd, the Army of the Potomac woke up holding one of the strongest defensive positions any American army would ever occupy, and it had gotten there almost by accident, beaten backward onto it the day before.` },
      { p: `You could see it from the air, if anyone could have gotten up there. From a wooded knob called Culp’s Hill in the north, the Union line bent west over Cemetery Hill and then ran straight south down the spine of Cemetery Ridge for nearly two miles to a pair of rocky hills called the Round Tops. Drawn on a map it looked exactly like a fishhook: the barb hooking east at Culp’s Hill, the long shank running south down the ridge, and Little Round Top anchoring the very bottom of the curve.` },
      { p: `A beaten army had stumbled backward onto the best ground on the field.`, i: true },
      { p: `The shape was not just pretty. It was the whole game. A defender curled into a fishhook has what soldiers call interior lines: the inside of the curve is a short, straight chord, so a man (or a brigade, the few-thousand-man building block of a Civil War army) can be marched from the northern barb to the southern shank across the inside of the hook in a fraction of the time it takes an attacker to march the long way around the outside. Meade (North), the careful Pennsylvania engineer who had been handed command of this army only four days earlier, could shuttle troops to whatever part of his line was screaming loudest. Lee, attacking from the outside of the curve, would have to march miles to do the same thing. The Union had lost the first day and won the ground.` },
      { fig: '/war-img/gettysburg-day2.png', cap: 'The fishhook on Day 2: Longstreet swings against the southern point, Ewell against the northern barb.', credit: 'Stuff Happened map' },
      { p: `Stuart (South) came in that afternoon, finally, the cavalry Lee had been missing for a week. He arrived at headquarters on Seminary Ridge with a train of captured Union supply wagons in tow, as if this were the news of a victory and not the end of a long absence that had left an army half-blind. By the later account of Stuart’s own adjutant, Lee’s greeting was brief and cool: “Well, General Stuart, you are here at last.” No one else was in the room, and the men who set the exchange down did it decades after the war, so the exact words belong to tradition rather than a transcript. What is not in doubt is the fact under them: Stuart had ridden clear around the Union army, and while he rode, Lee had fought the first day of the largest battle of the war without knowing where the bulk of Meade’s force was. Whatever was said in that room, Stuart understood it as a rebuke.` },

      { h: 'Lee’s certainty, Longstreet’s dread', eyebrow: 'The plan' },
      { p: `Lee had three choices that morning, and he knew it: pull back and look for better ground, sit on the defensive and let Meade come to him, or attack. His most trusted subordinate, Lieutenant General James Longstreet (South), wanted the second one, or really a version of the first. Longstreet had spent the night studying that fishhook and did not like the look of it. He wanted to slide the whole army south around the Union left, get between Meade and Washington, find some good defensive ground of their own, and make the Federals do the attacking. He had opposed this invasion from the start. Now he was looking at a fortified ridge two miles long and asking, in effect, why they should be the ones to climb it.` },
      { p: `Lee said no. Lee was looking at the same ridge and seeing something different. He had the largest, most confident army he would ever command, deep inside the North, fresh off a year of beating bigger Union armies and a smashing win at Chancellorsville two months before. Hundreds of miles to the southwest, Vicksburg was about to fall to Grant, and a loud victory here might be the thing that changed the war’s whole arithmetic. Lee believed his men could do anything. He had reason to. That belief was about to cost him.` },
      { p: `The plan he gave Longstreet was an oblique attack, not a head-on charge into the strongest part of the line, but a blow up against the Union left flank, the southern end of the shank, rolling the enemy line up from its open end like a rug. While Longstreet hit the left, Ewell (South) would press the right at Culp’s Hill, so Meade couldn’t strip troops from one end to save the other. The center would only feint.` },
      { p: `On paper it was elegant: hit both ends, pin the middle, and let the fishhook tear itself apart trying to defend everywhere at once. On the ground it would unravel almost from the first step, and the first thing to go wrong was simply getting Longstreet into position.` },

      { h: 'Sickles takes a walk', eyebrow: 'The salient' },
      { p: `It turned into an ordeal. Lee wanted Longstreet’s two divisions hidden, so they took a long, looping, concealed approach march, doubling back when the route threatened to expose them to a Union signal station, and waited besides for one of Longstreet’s brigades (Law’s) to come up from a hard march of its own. Noon passed. One o’clock, two o’clock, three. By the time Longstreet was finally ready, it was past four in the afternoon, and the line he was about to hit was no longer the line anyone had planned for.` },
      { p: `The trouble was Major General Daniel Sickles (North), a New York politician in a soldier’s coat, commanding the III Corps at the southern end of Meade’s line. Sickles did not like the low, soft ground he’d been assigned along the bottom of Cemetery Ridge. Out in front of him, three-quarters of a mile west, the ground rose a little to a peach orchard. He decided, entirely on his own authority, that the higher ground was better, and he marched his whole corps forward off the ridge and out into the open, bending his line around the Peach Orchard and back through a wheatfield, with both ends hanging in the air, anchored to nothing.` },
      { p: `When Meade rode out and saw what Sickles had done, he was appalled. Sickles had pushed a salient (a bulge sticking out from the main line, exposed to fire on more than one side) far in front of the army, and there was no time left to pull it back before the Confederates came. Sickles, sensing the storm, offered to withdraw. Meade told him it was too late, and put the whole disaster in a single dry sentence:` },
      { p: `this is neutral ground, our guns command it, as well as the enemy’s.`, q: true },
      { p: `Then the Confederate artillery opened up, and the argument was over. Whether Sickles had committed a brilliant stroke or a court-martial offense would be argued for the rest of his long life. He died fifty-one years later, still arguing. What is certain is that his men were about to pay for the geometry.` },

      { h: 'Devil’s Den', eyebrow: 'The boulders' },
      { p: `Longstreet’s attack opened at the far southern end, around four-thirty, and it opened with Major General John Bell Hood (South). Hood was one of the hardest-driving fighters in Lee’s army, and he did not like his orders. He’d asked repeatedly to swing wider around the Union flank and been refused every time. He attacked straight ahead. Almost at once, an artillery shell burst in the air above him and tore into his left arm, and Hood was carried off the field before his assault had really begun, his division surging on without the man who was supposed to steer it.` },
      { p: `What it surged into first was the Devil’s Den, a jumble of car-sized granite boulders at the base of the slope, a place that looked like the world had been dropped and shattered. Holding it was a Union brigade under Brigadier General J.H. Hobart Ward (North), about 2,200 men in six regiments. The fighting there was close and ugly, men firing at each other across gaps in the rock at a few yards’ range, then clubbing and grabbing when there was no time to reload.` },
      { p: `The hardest of it fell on the 124th New York. Their colonel, Augustus Van Horne Ellis (North), and their major, James Cromwell, both went down dead leading their men among the boulders. Ward’s brigade held the Den for the better part of an hour, and then the weight of Hood’s attack told, and they didn’t. Of the roughly 2,400 Union men engaged around Devil’s Den, 821 were killed, wounded, or captured. The Confederates lost more, somewhere near 1,800 of the 5,500 who came at the rocks. The granite kept the bodies the way a fist keeps a coin.` },
      { fig: '/war-img/gettysburg-day2-photo.jpg', cap: 'Devil’s Den, in a wartime sketch of the fighting. The rocks were as confusing in 1863 as they look now.', credit: 'Library of Congress · public domain' },
      { p: `By the time the rocks belonged to the Confederates, several regiments of Alabamians and Texans were already jogging up the wooded slope just to the south. They couldn’t see the crest through the trees. They didn’t yet know there was anyone up there at all.` },

      { h: 'Little Round Top', eyebrow: 'The hill nobody was holding' },
      { p: `The story everyone knows about Little Round Top is the bayonet charge. Colonel Joshua Lawrence Chamberlain (North), a college professor from Maine who taught rhetoric and modern languages and had talked his way into a uniform two years earlier, in command of the 20th Maine on the far left end of the entire Union army, his men shot down and out of ammunition, ordering them to fix bayonets and charge straight down the hill into the enemy. It is a true story. It happened. And the way it usually gets told, it sounds like the whole battle.` },
      { p: `It is not the whole battle. It is about twenty minutes of it.` },
      { p: `The genuinely decisive thing had happened a little earlier, and it was almost an accident. Brigadier General Gouverneur K. Warren (North), the chief engineer of the Army of the Potomac (a mapmaker, not a combat commander), rode up to the crest of Little Round Top to have a look at the ground and found, to his horror, that the most important hill on the southern end of the field was empty. Sickles had marched everyone forward into his salient and left the army’s anchor undefended. Then Warren looked west through the trees and saw sunlight glinting off the muskets of an entire Confederate line moving straight toward the hill he was standing on, alone. If those men took this crest, they could put guns on it and fire straight down the length of the whole Union line. The battle could be lost in the next half hour, on a hill nobody was holding.` },
      { p: `Warren turned and started screaming for troops, grabbing whole brigades that happened to be marching past below and shoving them up the slope on his own authority. The race that followed was a matter of minutes.` },
      { p: `Strong Vincent’s (North) brigade got there first, sprinting up the back of the hill and flinging itself into line just as Hood’s men came up the front; Vincent was shot down almost at once, mortally wounded. Behind him came Patrick “Paddy” O’Rorke (North), who led the 140th New York up the slope at a dead run and was killed in the first volley. The Union artilleryman who manhandled his guns onto that impossible rocky crest, Charles Hazlett (North), was killed there too. Men were dying to hold a hill they had reached only seconds before the enemy.` },
      { fig: '/war-img/gettysburg-lrt.png', cap: 'Little Round Top: Hood’s men sweep over Devil’s Den and up the slope; Chamberlain anchors the Union far left.', credit: 'Stuff Happened map' },
      { p: `And on the very end of that scrambled line, anchoring the left of the left of the left (the last man on the flank of the entire Army of the Potomac), was Chamberlain and his 20th Maine. In front of him, climbing the slope again and again, was Colonel William C. Oates (South) and the 15th Alabama, men who had already marched far that day in the heat and were now being asked to take a hill by storm. They came up the rocks and were thrown back, re-formed and came again, and again, working around toward Chamberlain’s open flank, until the Maine men were folding their line back on itself like a closing gate and were nearly out of cartridges.` },
      { p: `That is the moment of the famous charge. Chamberlain had no ammunition and no orders that fit the situation, so he invented one: fix bayonets and go downhill, swinging the line like a door to sweep the slope clean. It worked. The 15th Alabama, exhausted and surprised, broke and ran. Chamberlain would win the Medal of Honor for it, and he earned it. But the hill had been saved twenty minutes before he charged, by an engineer who happened to ride up at the right moment and have the nerve to scream. The legend is the bayonet charge; the hill was held by Warren.` },

      { h: 'The Wheatfield', eyebrow: 'The first modern war' },
      { p: `While Little Round Top was being saved, the ground just to the north turned into one of the worst killing grounds of the war. It was a wheatfield (about nineteen acres of waist-high grain on a small farm between the Peach Orchard and the rocks), and over the next few hours it changed hands again and again at close range.` },
      { p: `Somewhere around nineteen or twenty brigades from both armies were fed into those nineteen acres, piece by piece, over the course of the late afternoon and evening. The Wheatfield was taken and lost and taken again so many times that no one could keep an honest count; the figure people remember is six. Lines came across the standing wheat, were shot down in it, were replaced, charged, were driven back across their own dead. Roughly twenty thousand men fought there. Around a third of them became casualties. Two Union colonels, Edward Cross (North) and Samuel Zook (North), were both mortally wounded leading brigades into it.` },
      { p: `The Wheatfield is the kind of fighting people mean when they call the Civil War the first modern war. Not the maps or the railroads, but a flat field of trampled grain where industrial firepower met masses of men standing upright in the open, and ground them up by the thousand for a patch of farmland that, by sundown, belonged to nobody at all.` },
      { fig: '/war-img/gettysburg-wheatfield.png', cap: 'Sickles’ salient: the III Corps line bent forward around the Peach Orchard and the Wheatfield, where the Confederate attack struck it from two sides.', credit: 'Stuff Happened map' },

      { h: 'The Peach Orchard', eyebrow: 'Sickles pays for the geometry' },
      { p: `At the front point of Sickles’s salient, around six o’clock, the bill came due. The Confederate attack rolled up against the Peach Orchard from more than one direction, and the man who broke it was Brigadier General William Barksdale (South), a fire-breathing Mississippi congressman who had been straining at the leash all afternoon to be turned loose. When he finally got the order he led his brigade in personally, on horseback, white hair streaming, out in front of his men, and they cracked Sickles’s salient open like an egg. Barksdale was shot from his horse in the charge he had begged for, and died the next day in a Union field hospital.` },
      { p: `The salient collapsed. The III Corps, strung out in the open exactly as Meade had feared, came apart. And Sickles himself, the politician who had marched these men off the ridge, was hit by a cannonball that mangled his right leg; it was amputated that evening. By one well-worn account he was carried off the field sitting up and smoking a cigar, determined to be seen looking unbothered. For the rest of his long life he insisted that his unauthorized advance had actually won the battle, that it had broken up Longstreet’s attack before it reached the real line. Almost nobody who had been in the Wheatfield agreed with him.` },
      { p: `Behind the wreckage of Sickles’s corps, the broken Union pieces fell back toward the ridge they should never have left, and the line, bending and buckling, held. Meade’s interior lines did exactly what the fishhook had promised: he pulled brigades from the quiet parts of his curve and rushed them to the screaming part, and plugged the holes faster than Longstreet could tear them.` },

      { h: 'Culp’s Hill', eyebrow: 'One brigade, behind the wood' },
      { p: `While the southern end of the field was being fought to a standstill, the northern barb of the fishhook finally caught fire. Ewell had been ordered to attack Culp’s Hill in coordination with Longstreet. He didn’t get going until evening, nearly sundown, by which point most of the day’s damage was done. When his blow finally landed, it landed soft, because the Union had handed almost the entire defense of that hill to a single brigade and a single stubborn old man.` },
      { p: `The hill was held by the brigade of Brigadier General George S. Greene (North), and only Greene’s brigade: the rest of the corps that should have been there had been marched south to help in the crisis around the Wheatfield. It was Edward “Allegheny” Johnson’s Confederate division (South), one division and even that one short a brigade, that came at Greene in the dusk. (The popular telling that three Confederate divisions stormed Culp’s Hill is simply wrong; it was Johnson’s one.) Even so, one division against one brigade is desperate arithmetic, and the only reason it didn’t end in a rout was Greene himself.` },
      { p: `Greene was sixty-two years old, a West Point graduate of the class of 1823 (forty years gone) who had left the army for a distinguished career as a civil engineer (he helped lay out New York City’s water system) before the war called him back. He had spent the afternoon making his men dig, hauling logs and earth into a line of breastworks (chest-high field fortifications of dirt and timber thrown up to stop bullets) along the crest of the hill, over their tired grumbling. Those breastworks were the entire reason a single brigade could hold off a division. Greene’s men fired from behind cover at Johnson’s men climbing in the open, and held, and held, and held, until reinforcements finally came up through the dark and the hill was saved. An engineer’s caution, again, where it counted.` },
      { fig: '/war-img/gettysburg-culps.png', cap: 'Culp’s Hill: Johnson’s division attacks the northern barb at dusk; Greene’s lone brigade holds behind breastworks until reinforcements arrive after dark.', credit: 'Stuff Happened map' },

      { h: 'The line held', eyebrow: 'Lee turns to the center' },
      { p: `By midnight the firing had finally guttered out across the whole fishhook. It had been the largest, bloodiest day of the largest, bloodiest battle of the war: the rough estimates run to something like ten thousand Union casualties and just under seven thousand Confederate in that single afternoon and evening, killed, wounded, and captured. Hood was carried off with a ruined arm. Sickles was carried off with no leg. Barksdale and Vincent and O’Rorke and Cross and Zook and the colonel and major of the 124th New York were dead, and the Wheatfield was a carpet of men who would never be told apart again.` },
      { p: `And the Union line was exactly where it had been at dawn. Bent in the middle where Sickles had bulged it forward and lost it, but unbroken end to end: Little Round Top held, the ridge held, Culp’s Hill held. Lee had thrown his army at both flanks of the fishhook, the left and the right, and both had bent and neither had snapped.` },
      { p: `Robert E. Lee did not take that as a verdict. He took it as a near miss. He had hit the enemy’s left and the enemy’s right, and both times come within an arm’s length of breaking through. The one place he had not yet struck in force was the middle. So in the small hours of July 3rd, looking at the long quiet center of Cemetery Ridge, Lee made the decision that would define the rest of his life and the rest of the war.` },
      { p: `He would attack the center.`, i: true },
    ],
    meanwhile: { region: 'Vicksburg', title: 'Grant takes the Mississippi tomorrow.', body: 'Six hundred miles to the south-west, after seven weeks of siege, the Confederate garrison at Vicksburg is starving. They will surrender on the morning of July 4th, the same morning Lee begins his long retreat from Gettysburg.' },
  },

  pickett: {
    eyebrow: 'Gettysburg · Day 3 of 3',
    title: 'Pickett’s Charge',
    progress: 0.82,
    from: [{ label: 'The Hooks', mode: 'war' }],
    to: [{ label: 'The retreat & the Address', mode: 'war' }, { label: 'High-water mark', mode: 'civ' }],
    blocks: [
      { h: 'The third morning', eyebrow: 'Before the charge' },
      { p: `By the morning of July 3rd, Robert E. Lee had thrown his army at both ends of the Union line and broken neither. Two days of the hardest fighting his army had ever done, and the enemy was still sitting on the ridge.` },
      { p: `So Lee looked at the one place he had not yet hit: the middle.` },
      { p: `The logic ran like this. He had struck the Union left and the Union right, which meant Meade (North) had surely pulled men from his center to shore up the wings. The center, then, was the thin spot. One massive blow straight up the middle, behind the heaviest cannon barrage the continent had ever heard, and the line would crack, and a cracked line is a beaten army. It was the kind of plan that looks clean on a map and costs you a generation of young men on the ground.` },
      { p: `Lieutenant General James Longstreet (South), the senior corps commander who would have to run the attack, thought it was madness, and said so. Longstreet had opposed the whole invasion. He had opposed the attack on the second day. Now, on the third morning, he made his case one more time: don’t do this. Slide the army around Meade’s left, get between the Union army and Washington, and let Meade be the one to attack uphill across open ground. Make the other man pay the butcher’s bill for once.` },
      { p: `Lee would not hear it. To pull back now, after coming this far north, after two days of hurling men at the heights, was to admit the whole campaign had been a mistake, and Lee did not believe it had been. He had beaten this army before. He believed he could beat it here. There is a kind of confidence in a commander that wins battles for years and then, on one July afternoon, walks twelve thousand men into open ground because it cannot imagine losing. By the traditional account Longstreet was so sick at heart he could barely give the order when the moment came.` },
      { p: `The force was about twelve thousand five hundred men, drawn from three divisions under Longstreet’s command: the divisions of Major General George Pickett (South), Brigadier General James Pettigrew (South), and Major General Isaac Trimble (South). Pickett’s was the freshest; his men had not yet been bloodied at Gettysburg, and Pickett himself, a flamboyant figure with perfumed ringlets in his hair, was hungry for the glory the first two days had handed to other men. Eagerness on one side of the field, dread on the other. Longstreet saw a slaughter coming. Pickett saw his chance.` },
      { p: `The famous name gets the first thing wrong: this was not Pickett’s charge alone. Pickett commanded just three of the eleven brigades that stepped off, the all-Virginia ones. The rest of the line belonged to Pettigrew (whose men were North Carolinians, Mississippians, Tennesseans, Alabamians, and Virginians) and to Trimble. When the killing was tallied, Pettigrew’s command lost about as many men as Pickett’s, roughly twenty-seven hundred each. Two-thirds of the brigades in that doomed advance were not Pickett’s at all, and most of the men who died doing it never served under him. The Virginia-centric name, settled on afterward, left out the Carolinians and Tennesseans and the rest, who walked into the same guns and fell in the same numbers. Some historians call it the Pickett–Pettigrew–Trimble Assault instead.` },
      { p: `Their target was a small clump of trees on Cemetery Ridge, with a low stone wall in front of it that jogged at a right angle, a spot the soldiers called the Angle (a kink in the stone fence where the Union line stepped forward, then back). To get there, the men would have to cross roughly three-quarters of a mile of open ground, in the open, in the sun, in full view of every Union gun on the ridge. There was a fence line partway across, the Emmitsburg Road, that would funnel and slow them right under the muzzles. Modern historians still argue over whether Lee meant to aim a little north of the trees, but the copse and the Angle are where the story drove, and where the men died.` },

      { h: 'The cannonade', eyebrow: '1:00 p.m.' },
      { p: `At about one in the afternoon, the largest artillery bombardment ever conducted on the North American continent began.` },
      { p: `A cannonade is exactly what it sounds like: a sustained, hammering barrage of cannon fire, gun after gun after gun, meant to wreck the enemy’s defenses before the infantry goes in. Lee’s gunners opened with somewhere between one hundred fifty and one hundred seventy guns, ranged along Seminary Ridge and aimed at the Union center. The Federals answered with around eighty. For one to two hours the two ridges thundered at each other across the valley, a sound so enormous that people heard it rolling across the countryside for miles in every direction.` },
      { p: `And most of it did nothing.` },
      { p: `The smoke rolled up so thick the Confederate gunners could not see whether their shells were landing on the ridge or sailing over it. They were sailing over it. Round after round screamed past the Union infantry lying flat behind the wall and exploded in the rear: in the supply trains, among the horses, among the staff officers, terrifying and lethal but doing very little to the men who actually had to be killed for the charge to work. Then the Union guns went quiet. Some of that was to save ammunition for what everyone knew was coming. Some of it was a bluff, letting the Confederate gunners believe they had silenced the enemy batteries. Lee’s artillery chief, watching the Union fire slacken, took it for the green light. He sent word to Longstreet that now was the time, before the guns ran dry.` },
      { p: `Longstreet could not bring himself to speak the order. By the traditional account he only nodded.` },
      { fig: '/war-img/gettysburg-day3.png', cap: 'July 3: Pickett’s Charge crosses three-quarters of a mile of open ground at the Union center, the Angle.', credit: 'Stuff Happened map' },

      { h: 'The charge', eyebrow: '3:00 p.m.' },
      { p: `They came out of the tree line on Seminary Ridge a little before three o’clock, and for a moment it was the most beautiful and terrible thing anyone on that field had ever seen.` },
      { p: `Twelve thousand men, dressing their ranks as if on a parade ground, three long lines stepping off together across a front nearly a mile wide, battle flags up, bayonets catching the afternoon sun. The Union soldiers waiting behind the wall, men who had spent two days being hit, looked out across that valley and saw the entire Confederate army, it seemed, walking straight at them in the open. Some of them said later it was the grandest sight of their lives. Then they remembered what they were going to have to do to it.` },
      { p: `The men in gray walked. They did not run; they walked. A man at quick step covers a mile in something like fifteen, twenty minutes, and for the better part of that time the soldiers in the charge had nothing to do but keep walking forward, in step, into the muzzles, while the world came apart around them.` },
      { p: `Stand in their line for a moment, because the charge has too often been told only from behind the wall. You are a Confederate soldier, a Virginian, or a North Carolinian, or a Tennessean, and you have just come out of the trees into the open with three-quarters of a mile of bare Pennsylvania farmland in front of you and not one thing to hide behind on any of it. Ahead, up on the ridge, are the guns. You can see them. You have been told to walk to them. You cannot run, because the line must hold its dressing or it shatters; you cannot fire, because there is nothing yet in range to fire at; you cannot do anything but put one foot in front of the other and keep your place in the rank while the man beside you is taken apart. The Union artillery opens while you are still far off, solid shot and exploding shell tearing lanes straight through the ranks, whole files of men simply gone, and the order comes down the line to close up, close up, which means step over what is left of your friends and fill the hole and keep walking. You do it. Most of you do it. Roughly half the men who started this walk will not finish it, and every one of them can do the arithmetic as they go.` },
      { p: `Then you reach the Emmitsburg Road, a fence line partway across, and the lines bunch and tangle climbing it, slowing right under the muzzles at the worst possible moment. Here the gunners switch to canister, tin cans packed with iron balls that turn a cannon into an enormous shotgun, murderous at close range, and the Union infantry rises up behind the stone wall and adds the rifles. Solid shot far out, canister close in, rifle fire at the last. Some men get to that road and stop, taking what cover the fences give and going no farther, and you cannot honestly call it cowardice when the alternative is the open lane in front of the Angle, which has by now become a place men simply do not survive crossing. The slaughter fell on the men who did not stop, who climbed the fence and kept going into it.` },
      { p: `And some of them crossed it anyway.` },
      { p: `A few hundred Confederates, mostly from Pickett’s division, reached the wall at the Angle, the only ones, out of twelve thousand, to touch the thing they had been sent to take. At their head was Brigadier General Lewis Armistead (South), a brigade commander who put his hat on the tip of his sword and held it high so his men could see him through the smoke, and led them up over the stone wall and in among the Union guns. For a few minutes there was hand-to-hand fighting at the breach, men clubbing each other with rifles, gunners defending their cannon. And then it was over. Armistead fell, mortally wounded, among the guns; he would die in a Union field hospital two days later. The handful who had crossed the wall were killed or captured where they stood. The rest of the charge, the men who were still alive in the field behind them, turned around and began the long walk back across the same three-quarters of a mile they had just crossed, with the Union guns firing into their backs the whole way.` },
      { p: `That spot at the Angle, the farthest point the attack reached, is remembered as the “high-water mark of the Confederacy”: the high tide of the Southern cause, the closest the Confederacy ever came, on its best army’s best day, to forcing the issue on Northern soil. It came up to a stone wall, and a few hundred men got over it, and then it went out, and it never came that far again.` },
      { p: `Of the roughly twelve thousand five hundred who stepped off, more than half did not come back: somewhere around six and a half thousand men killed, wounded, or captured in well under an hour. Pickett’s division alone lost more than two thousand six hundred; Pettigrew’s command lost about as many again. The men who walked out so steadily at three o’clock came back, those who came back at all, in ones and twos, bleeding, some carrying wounded friends, all of them under fire.` },

      { h: '“I have no division”', eyebrow: 'The reckoning' },
      { p: `What Lee did next is one of the most-told scenes in American history, and it is also one of the most uncertain. Scholars including Earl Hess, Stephen Sears, and Jeffry Wert have questioned whether the meeting between Lee and Pickett happened as the legend tells it. What follows is the story the survivors and their descendants kept, and held onto, and may have improved in the keeping. True or not, it is the thing the South chose to remember about that afternoon.` },
      { p: `By the traditional account, Lee rode out alone to meet the survivors as they staggered back across the field, and what he said was not a general’s excuse but a confession. He is remembered to have told them:` },
      { p: `This has all been my fault.`, q: true },
      { p: `He is said to have gone among the broken men telling them to re-form, that the fault was his and the failure was his, that they must hold together for what was left. And when he found Pickett and asked him to ready his division to repel a counterattack, Pickett (whose division had effectively ceased to exist in front of the stone wall) is said to have replied:` },
      { p: `General Lee, I have no division.`, q: true },
      { p: `Whether those exact words were ever spoken, no one can now prove. What is not in doubt is the thing the words point at: a division had walked into that valley, and a division did not walk out, and the man who ordered them in knew it. The attack was broken. The invasion of the North was broken with it. That night, and the next day, the Army of Northern Virginia would begin the long road home.` },
      { p: `Lee had come north to win the war in an afternoon. He had instead given it its turning point, for the other side.`, i: true },
    ],
  },

  aftermath: {
    eyebrow: 'Gettysburg · Aftermath',
    title: 'The retreat & the Address',
    progress: 0.97,
    from: [{ label: 'Pickett’s Charge', mode: 'war' }],
    to: [{ label: 'The Reckoning', mode: 'war' }, { label: 'A New Birth of Freedom', mode: 'civ' }],
    blocks: [
      { h: 'The morning of July 4th', eyebrow: 'After three days' },
      { p: `It rained.` },
      { p: `It rained on the Fourth of July, 1863, and it rained on the dead, who were still where they had fallen: in the wheat, in the orchard, in the woods, along the stone walls, by some counts seven thousand of them between the two armies, with the wounded and the dead horses uncounted on top of that. Three days of fighting around a small Pennsylvania market town had produced something close to fifty thousand casualties (killed, wounded, or captured), split roughly evenly between the two sides, an estimated twenty-three thousand for the Union under George Meade (North) and somewhere between twenty-three and twenty-eight thousand for Robert E. Lee’s army. It was, and remains, the costliest battle ever fought in North America. And now it was over, and it was raining, and somebody had to move.` },
      { p: `Lee moved first, south. His wagon train of wounded stretched for some seventeen miles: ambulances and supply wagons groaning down the muddy roads toward the Potomac and Virginia, escorted by Confederate cavalry under Brig. Gen. John Imboden (South), the men inside it crying out at every jolt of the wheels in the ruts. It was a retreat, and everyone in both armies knew it was a retreat, and the only question left was whether Meade would turn it into a rout.` },
      { p: `He did not. Meade let Lee go. He had a battered army of his own, he had just survived three days that could have lost the war, and he chose to follow rather than fall on the retreating column and try to destroy it. Whether that was prudence or timidity, whether a harder man would have ended the Army of Northern Virginia right there on the swollen banks of the Potomac, became an argument that followed Meade for the rest of his life, all the way to Washington, where an impatient president and an impatient Congress wanted to know why the beaten enemy had been allowed to walk home. It was, almost word for word, the same question that had been asked of McClellan after the Battle of Antietam the year before. The North kept winning the great defensive battle and then standing still while the chance to finish it walked away.` },
      { p: `Lincoln was not standing still about it. On July 14th, as Lee’s column finished its crossing of the Potomac, Lincoln sat down and wrote Meade a letter of the kind it takes real restraint not to send. He told Meade he did not believe he appreciated “the magnitude of the misfortune involved in Lee’s escape,” that Lee had been “within your easy grasp,” that closing on him “would, in connection with our other late successes, have ended the war,” and that “your golden opportunity is gone, and I am distressed immeasurably because of it.” Then he put the letter away. He never signed it and never sent it, and on the envelope he wrote his own verdict on the whole thing: “To Gen. Meade, never sent, or signed.” Meade went the rest of his life not knowing it existed.` },
      { fig: '/war-img/gettysburg-aftermath-photo.jpg', cap: 'A Harvest of Death: Timothy O’Sullivan’s photograph of the Union dead, made in the days after the battle.', credit: 'Timothy H. O’Sullivan · public domain' },
      { p: `There is a photograph from those days, one of the most famous photographs of the entire war. Timothy O’Sullivan, working the battlefield in the rain-soaked aftermath, made an image of the Union dead lying scattered across the open ground, faces to the sky, and it was titled “A Harvest of Death.” The grand parade-ground lines of the day before had become a harvest, and the photographers walked it before the burial parties did, and for the second time in the war (the first was Antietam) the people at home were made to look at exactly what their newspapers’ casualty columns actually meant.` },

      { h: 'Two surrenders, one day', eyebrow: 'The same Fourth of July' },
      { p: `On that same Fourth of July, eight hundred miles to the southwest, the Confederate fortress city of Vicksburg surrendered to Ulysses S. Grant. Vicksburg was the last great Confederate stronghold on the Mississippi River, and with its fall the entire river, from its headwaters down to the Gulf, passed into Union hands. The Confederacy was now cut in two: Texas, Arkansas, and most of Louisiana sliced clean off from the rest of the South, the great water highway that had carried the Southern economy now belonging to the enemy.` },
      { p: `So on a single day (July 4th, 1863) Lee’s invasion of the North broke and turned for home, and the Mississippi River fell, and the Confederacy was split down the middle. Historians ever since have marked this as the hinge of the war, the week the Confederacy stopped being a nation that might win and started being a nation that was running out of time. What earns the word turning point is plain: Lee’s army never invaded the North again. The Army of Northern Virginia turned south after Gettysburg and fought the entire rest of the war on the defensive, on its own ground, reacting to its enemy instead of dictating to him. The South would fight on, hard, for nearly two more years. But after that Fourth of July, it was fighting the clock.` },

      { h: 'Two minutes at the cemetery', eyebrow: 'November 19th' },
      { p: `The words that turned fifty thousand casualties into something a country could carry forward came four and a half months later, and they took about two minutes to say.` },
      { p: `That summer and fall, the town of Gettysburg had been digging. The dead could not be left in the fields where O’Sullivan had photographed them, and so a proper burial ground for the Union soldiers, the Soldiers’ National Cemetery, was created on the very ridge they had died defending. On November 19th, 1863, it was dedicated, and Abraham Lincoln was invited to attend and offer, as the program put it, “a few appropriate remarks.”` },
      { p: `He was not the main event. The featured orator was Edward Everett, the most celebrated public speaker in the country, a former senator and secretary of state and president of Harvard, and Everett did what featured orators did: he spoke for about two hours, some thirteen thousand words, a full classical oration on the battle and the war and the cause. Then Lincoln stood up and spoke for about two minutes.` },
      { p: `He said about two hundred seventy words, ten sentences. It is, line for line, very likely the most important short speech in the English language, and it began:` },
      { p: `Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.`, q: true },
      { p: `Look at the arithmetic in the first sentence. “Four score and seven” is eighty-seven years. Lincoln was speaking in 1863, and eighty-seven years back puts you at 1776, not the Constitution of 1787, but the Declaration of Independence. That was the quiet, enormous move. The Constitution had made its peace with slavery; the Declaration was the older document, the one that said all men are created equal. Lincoln reached past the compromise and named the promise as the nation’s true beginning, and told a country in the middle of killing itself that the war was about finally making that promise real: that “this nation, under God, shall have a new birth of freedom,” and that “government of the people, by the people, for the people, shall not perish from the earth.”` },
      { p: `Twelve thousand men had walked into the open at the Angle. Fifty thousand had fallen across three days. And four months later, in two minutes, the president told the country what all of it had been for.`, i: true },
    ],
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={GB_NARR as never} id={id} slug="gettysburg" battleName="Gettysburg" theatreId="east" battleId="e-gettysburg" />
}
