'use client'

// Westport — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.
//
// House-voice rules applied: no em-dashes in reader text; marquee names carry no
// side-tag (none appear here); every other side-affiliated person tagged once on
// first mention per section; full rank spelled out on first appearance per section;
// the cause named once, plainly. Facts web-verified against the American Battlefield
// Trust, Wikipedia, and Civil War on the Western Border. The only visual is the
// opening {locator} establishing map. Tactical maps + photos are a deferred follow-up.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const WESTPORT_NARR: Record<string, Narr> = {
  'last-raid': {
    eyebrow: 'Westport · The last invasion',
    title: 'Price Comes North',
    blocks: [
      { locator: {
        eyebrow: 'Where and when · October 1864',
        caption: 'Westport sat just south of Kansas City, on the Missouri side of the line with Kansas. Major General Sterling Price marched his Army of Missouri up from Arkansas through the heart of the state, past St. Louis and Jefferson City, until two Union forces closing from the west and the east finally pinned him against the Big Blue River in the southwest corner of Missouri.',
        frame: { lonMin: -96.4, lonMax: -88.4, latMin: 35.6, latMax: 40.8 },
        states: [
          { name: 'Missouri', tone: 'focus', label: 'MISSOURI', labelLon: -92.6, labelLat: 39.9 },
          { name: 'Kansas' }, { name: 'Arkansas' }, { name: 'Iowa' }, { name: 'Illinois' },
          { name: 'Kentucky' }, { name: 'Tennessee' }, { name: 'Nebraska' }, { name: 'Oklahoma' },
        ],
        dots: [
          { name: 'Westport', date: 'Oct 23, 1864', lat: 39.05, lon: -94.59, heavy: true, anchor: 'start' },
          { name: 'Jefferson City', lat: 38.58, lon: -92.17, color: '#8a8175', anchor: 'end' },
          { name: 'St. Louis', lat: 38.63, lon: -90.20, color: '#8a8175', anchor: 'start' },
        ],
      } },
      { p: 'By the fall of 1864, the Confederacy was running out of room. William T. Sherman had taken Atlanta in September and was about to cut loose for the sea. Robert E. Lee was pinned in the trenches around Petersburg and Richmond. The blockade had strangled Southern trade, foreign recognition was a dead hope, and the one thing standing between the Confederacy and the end was the United States election in November, where Abraham Lincoln faced the voters with the war still unwon. If the North lost its nerve and voted him out, a new administration might let the South go. If it did not, the war was lost. The Confederacy needed something loud, and it needed it fast.' },
      { p: 'Out west, a Missourian thought he could provide it. Major General Sterling Price (South) had commanded the Missouri State Guard in the war\'s first summer and had spent the years since aching to take his home state back. Price was a former governor of Missouri, a big, heavy man near sixty, and the Confederate commander of the Trans-Mississippi, General Edmund Kirby Smith (South), gave him an army and turned him loose. The plan was a raid on the grandest scale: march up through Missouri, gather recruits, capture war materiel, take St. Louis or the capital at Jefferson City if he could, and above all make enough noise to draw Union troops away from Sherman and Lee and to shake Northern confidence before the election. He crossed into Missouri in September 1864 with something like 12,000 men, many of them poorly armed, and a column of wagons that grew longer with every town he passed.' },
      { h: 'A raid that bogged down', eyebrow: 'September into October' },
      { p: 'It did not go as drawn up. Price found St. Louis too strongly held to attack and Jefferson City too well fortified to storm, so he gave up on both and turned west, following the Missouri River across the state toward Kansas City and the border. As he marched, his army swelled with raw recruits and Missouri bushwhackers (homegrown Confederate partisan raiders) but slowed under the weight of the booty he was hauling, a wagon train stretched out for miles, loaded with plunder and trailing herds of cattle. An army that was supposed to move fast and hit hard had turned into a slow-moving parade dragging its own loot, and two Union forces were converging on it from opposite directions.' },
      { p: 'In front of him, to the west, was Major General Samuel R. Curtis (North), the Union commander who had broken the Confederate army in the region at Pea Ridge two years earlier. Curtis had thrown together an improvised force he called the Army of the Border, regular troops stiffened with thousands of Kansas state militia, and planted it across Price\'s path along the state line. Behind Price, to the east, came a hard-riding Union cavalry column under Major General Alfred Pleasonton (North), roughly 5,500 troopers driving the rear of the Confederate column and never letting it rest. Price was being squeezed from both ends.' },
      { pill: '/war-civil-war/trans-mississippi/pea-ridge', plabel: 'Pea Ridge: where Curtis broke the Confederate army in the region two years before' },
      { h: 'Three days of running fights', eyebrow: 'October 21 to 23' },
      { p: 'For three days the squeeze tightened. On October 21, Price\'s lead division shoved Curtis\'s men back from the Little Blue River, east of Independence, but the fight cost him hours he did not have. On October 22, Pleasonton\'s troopers caught the Confederate rear at Independence and battered it through the streets of the town, while up ahead Brigadier General Joseph O. Shelby (South), Price\'s best subordinate, forced a crossing of the Big Blue River at Byram\'s Ford by outflanking the Union defenders and driving them back toward Westport. Price had won his way forward another day, but he had won it slowly, and the slowness was killing him. By the night of October 22 his army of perhaps 8,500 effective men was caught in the angle between two rivers, Curtis\'s force planted in front of him to the west and Pleasonton\'s cavalry closing on the Big Blue behind him to the east. There was no longer anywhere to run that did not mean a fight. In the morning he would have to break one of the jaws of the trap or be crushed between them.' },
      { fig: '/war-img/westport-the-squeeze.png', cap: 'By the night of October 22, Price is pinned in the angle of the rivers: Curtis blocking the road west at Westport, Pleasonton driving the rear from Independence, and Shelby forcing the Big Blue River at Byram’s Ford.', credit: 'Stuff Happened map' },
    ],
    meanwhile: { region: 'the North', title: 'Two weeks before the vote', body: 'Everything Price was doing was aimed, in the end, at a ballot box. The 1864 presidential election was barely two weeks off, and the Confederacy\'s last real hope was that war weariness would turn Northern voters against Lincoln and toward a peace that let the South go. A Confederate army loose in Missouri, taking towns and beating Union forces, was meant to make the war look unwinnable just as the North decided whether to keep fighting it. Instead the news from Missouri would soon read the other way.' },
  },

  'brush-creek': {
    eyebrow: 'Westport · The morning fight',
    title: 'Brush Creek',
    blocks: [
      { p: 'On the morning of October 23, 1864, Major General Sterling Price (South) was boxed in. To his west, between him and escape into Kansas, stood Major General Samuel R. Curtis (North) and the Army of the Border along a low stream called Brush Creek, just south of Westport. To his east, across the Big Blue River at Byram\'s Ford, Major General Alfred Pleasonton (North) and his cavalry were closing on the Confederate rear. Outnumbered better than two to one across the whole field, Price made the only choice an aggressive general had: he would throw his weight forward against Curtis first, try to smash through to the west, and clear a road out before Pleasonton could come up behind him and shut the trap.' },
      { p: 'The fight opened at dawn along Brush Creek. Major General James G. Blunt (North), Curtis\'s most aggressive subordinate, had laid out the Union line on the high ground south of Westport and now sent his brigades down across the icy creek into the open fields beyond, ground that is a city park today. They ran straight into the best the Confederacy had west of the Mississippi. Brigadier General Joseph O. Shelby (South), with his veteran cavalrymen fighting on foot, counterattacked hard and drove the Union assault back across the creek. For a while the morning belonged to the South. Shelby pushed the Federals back toward the streets of Westport itself, and it looked as though Price might actually batter his way through to the west.' },
      { h: 'A farmer and a ravine', eyebrow: 'The turn' },
      { p: 'Then the battle turned on a piece of local knowledge. As the fighting stalled, a Missouri farmer named George Thoman, angry at Confederate raiders who had been stealing from the countryside, came to Curtis and showed him a hidden creek bed, a ravine that ran around the flank of Shelby\'s position. Curtis took it. He personally led part of his force, with the guns of a Wisconsin battery, up through the gully and onto the exposed side of the Confederate line, while Blunt\'s men pressed the front. Shelby was suddenly being hit from two directions at once, and his men were running low on ammunition, with no easy way to resupply this far from any Confederate base. The momentum of the morning drained away. The Union line that had nearly been pushed into Westport now began to push back.' },
      { fig: '/war-img/westport-brush-creek.png', cap: 'South of Westport, Blunt’s attack across Brush Creek is thrown back by Shelby’s counterattack until Curtis leads a flanking column up a hidden ravine onto the exposed Confederate line.', credit: 'Stuff Happened map' },
      { h: 'The other jaw closes', eyebrow: 'Byram\'s Ford' },
      { p: 'Three miles to the east, the second half of the trap was shutting. Starting around eight in the morning, Pleasonton\'s troopers hit the Confederate division holding the Big Blue at Byram\'s Ford, the division of Brigadier General John S. Marmaduke (South). Marmaduke\'s men held the west bank and the crossing for a couple of hours under heavy fire, but the Union cavalry forced the ford by about eleven, scrambled up the bank, and broke out into the open ground beyond, driving Marmaduke\'s division back toward the rest of Price\'s army. Now the Confederates were taking pressure from the west, from Curtis and Blunt, and from the east, from Pleasonton, at the same time. The two Union forces that had spent three days closing on Price had finally met around him.' },
      { fig: '/war-img/westport-byrams-ford.png', cap: 'Three miles east, Pleasonton’s cavalry forces the Big Blue River at Byram’s Ford against Marmaduke’s division and breaks into the open ground beyond.', credit: 'Stuff Happened map' },
      { p: 'Price\'s army began to come apart. Caught between converging attacks with its ammunition failing and its line bent back on itself, the Confederate force broke off the fight and started south, away from both jaws of the trap, abandoning ground it had bled for that morning. Some of the retreating men set the dry prairie grass alight to throw up a curtain of smoke and screen the withdrawal. Shelby fought a stubborn rear-guard action to keep the retreat from turning into a rout, and largely succeeded, but there was no mistaking what had happened. The largest battle ever fought west of the Mississippi River, with something like 30,000 men engaged over the wider field, had ended with the Confederate army in flight.' },
    ],
    meanwhile: { region: 'the wagon train', title: 'An army chained to its loot', body: 'Through all of it, Price never put down the thing that was slowing him. His miles-long wagon train, packed with the plunder of half of Missouri and trailing herds of livestock, sat behind his army the whole battle, an anchor he refused to cut loose. It had to be guarded, it had to be moved, and it set the pace of the retreat. An army that needed above all to be fast had spent the campaign tied to its own baggage, and now it would drag that baggage south in a long, hungry, hunted column with Union cavalry snapping at its heels.' },
  },

  'long-retreat': {
    eyebrow: 'Westport · The pursuit',
    title: 'The Long Road South',
    blocks: [
      { p: 'The Battle of Westport was lost, but the campaign was not yet over, and for Major General Sterling Price (South) the worst was still ahead. He turned his beaten army south down the Kansas-Missouri line, his wagon train slowing every mile, and behind him came the Union cavalry of Major General Alfred Pleasonton (North) and Major General James G. Blunt (North), no longer fighting to stop him but to destroy him outright. The retreat from Westport became a running rout that lasted for days.' },
      { p: 'On October 25, two days after Westport, the pursuers ran the Confederate rear to ground in a double disaster along the Marais des Cygnes and at Mine Creek, just over the line in Kansas. At Mine Creek, a sharp cavalry charge smashed Price\'s rear guard and captured two of his generals, Brigadier General John S. Marmaduke (South) and Brigadier General William L. Cabell (South), along with about six hundred men and several of their guns. It was one of the largest cavalry actions of the entire war, and one of the few clear Union victories won by mounted men charging on horseback. Price\'s army, already broken at Westport, was now being dismembered on the road.' },
      { fig: '/war-img/westport-mine-creek.png', cap: 'Two days later in Kansas, the Union pursuit under Pleasonton and Blunt runs down Price’s rear guard at Mine Creek, capturing Marmaduke and shattering the retreat.', credit: 'Stuff Happened map' },
      { pill: '/war-civil-war/off-the-battlefield/guerrilla-war', plabel: 'The guerrilla war: the irregular fighting that made Missouri the war\'s ugliest ground' },
      { h: 'What was left came home', eyebrow: 'November 1864' },
      { p: 'What was left of the Army of Missouri kept going south, into Indian Territory and Arkansas and finally Texas, harried and starving the whole way, eating its own draft animals before it was through. The expedition that had set out in September with about 12,000 men limped back across the Arkansas line with fewer than half that number still under arms. Price had marched well over a thousand miles, fought more than forty engagements, and accomplished almost nothing he set out to do. He had not taken St. Louis or Jefferson City, he had not held any ground, and the recruits he had gathered melted away as fast as the army shrank.' },
      { h: 'The Trans-Mississippi goes quiet', eyebrow: 'The meaning' },
      { p: 'Westport ended the war west of the Mississippi as a contest of armies. It was the last major Confederate offensive in the whole Trans-Mississippi theater, the South\'s final attempt to march an army north and change the course of the war, and it had failed completely. After Westport the United States held Missouri firmly for the rest of the conflict, and the cause Price had marched for, a Confederacy whose founding purpose was the protection of slavery, had run out of armies to send. The fighting that remained in the region would be the guerrilla kind, bushwhackers and raiders in the back country, not armies in the field.' },
      { p: 'The timing made the defeat doubly cruel for the South. Price had launched the raid in part to shake Northern confidence before the election, and it did the opposite. News of the victory at Westport reached the North in the last days of the campaign for the presidency, one more piece of good war news in an autumn that had already brought the fall of Atlanta. Far from turning voters against Abraham Lincoln, the collapse of the last Confederate invasion helped confirm that the war was being won. In November, Lincoln was reelected. The bid to win the war at the ballot box had helped lose it there instead.' },
      { pill: '/war-civil-war/off-the-battlefield/lincolns-rise', plabel: 'Lincoln and the 1864 election: the vote Price\'s raid was meant to swing' },
      { p: 'Some have called Westport the Gettysburg of the West, for its size and for the way it turned back a Confederate invasion. The comparison flatters the battle a little, but the core of it is fair. As Robert E. Lee\'s army had been turned back at Gettysburg in the East, Price\'s was turned back here, and where Lee\'s army survived to fight for nearly two more years, Price\'s simply disintegrated on the long road home. West of the Mississippi, the war as a war of marching armies was over. What was left was the waiting, while the armies in the East ground toward the surrender that would end it for good.' },
    ],
    meanwhile: { region: 'Virginia and Georgia', title: 'The real war was elsewhere', body: 'For all its size and drama, Price\'s raid changed nothing in the theaters that decided the war. It drew almost no Union troops away from the men besieging Lee at Petersburg or from Sherman, who was about to leave Atlanta in flames and march for Savannah and the sea. The end was coming from the East, where the great armies were, and it would arrive the following spring: the fall of Petersburg, the loss of Richmond, and a surrender in a Virginia courthouse town. Westport was the last roar of the war in the West, fought while the war that mattered most moved toward its close a thousand miles away.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={WESTPORT_NARR} id={id} slug="westport" battleName="Westport" theatreId="tmis" theatreHref="/war-civil-war/trans-mississippi" battleId="t-westport" accent="#d97706" />
}
