'use client'

// The Siege of Louisbourg (June–July 1758), battle sections. Produced through the war
// content pipeline (audits/war-content-pipeline.md): fact pack → author (Opus) →
// critic gates (fact-check + storytelling + comprehensiveness + clarity + fairness,
// parallel) → reconcile → revise. Data only; rendered by the shared
// <BattleSectionReader>. House voice: no em-dashes; British/French side-tags once on
// first mention per section; civilian and Mi’kmaq costs named plainly, not sanitized.
// Sources: audits/war-pipeline/fi-louisbourg-*.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const LOUISBOURG_NARR: Record<string, Narr> = {
  'the-fortress-by-the-sea': {
    eyebrow: 'Louisbourg · The sea gate to Canada',
    title: 'The fortress by the sea',
    blocks: [
      { fig: '/war-img/fi-louisbourg-tac1.jpg', cap: 'Louisbourg sat on the rocky southeast coast of Cape Breton Island, a walled town and naval base guarding the Gulf of St. Lawrence and the river road to Quebec. Amherst’s fleet staged out of Halifax, landed in the surf at Gabarus Bay, and closed a seven-week siege around the fortress.', credit: 'Stuff Happened map' },
      { p: 'On the rocky southeast shore of Cape Breton Island, where the cold Atlantic breaks against Nova Scotia, the French had built the strongest place in their North American empire. They called it Louisbourg, a walled town and naval base on Île Royale (the French name for Cape Breton), and it sat across the throat of the continent. Behind it, past the Gulf of St. Lawrence, lay the St. Lawrence River, the one great water road into the heart of New France (French Canada). Quebec, the capital, sat far up that river. Montreal sat farther still. To sail a fleet against them, you first had to get past Louisbourg. That is why the British called it the Gibraltar of the North. It was the lock on the door, and whoever held it held the way in.' },
      { fig: '/war-img/fi-louisbourg-view-lighthouse.jpg', cap: 'A view of Louisbourg taken near the lighthouse while the town was under siege in 1758, the walled sea fortress and its harbor that any fleet bound for the St. Lawrence and Quebec had to pass.', credit: 'Pierre-Charles Canot · engraving · 1762 · John Carter Brown Library · public domain' },
      { p: 'For Britain, by 1758, getting in was the whole point. The man driving the war from London, Secretary of State William Pitt, had a plan for that summer: three blows against New France at once. One army would push west to take Fort Duquesne at the Ohio forks. A second would drive up the Lake Champlain corridor at Fort Carillon (also called Ticonderoga). And the third, the one that mattered for everything that came after, would cross the ocean and take Louisbourg. Take the fortress, and the St. Lawrence opened. With the river open, a fleet could be sent against Quebec itself the following year. Carillon would fail bloodily that summer. Louisbourg and Fort Duquesne would not.' },
      { pill: '/war-french-indian/pitts-turn', plabel: 'Pitt’s three coordinated blows of 1758' },
      { p: 'There was history pressing on all of this, and it was personal for the colonists. Louisbourg had been taken before. In 1745, during an earlier war, a force of New England colonists, farmers and fishermen and tradesmen, not professional soldiers, had sailed up from Boston under William Pepperrell (colonial American), a Maine merchant, with Royal Navy ships in support, and against the odds they had besieged the great French fortress and forced it to surrender after about seven weeks. It was the proudest feat of arms the colonies had ever managed. And then, in 1748, the war in Europe ended, and at the negotiating table in the Treaty of Aix-la-Chapelle, Britain simply gave Louisbourg back to France in exchange for territory elsewhere. The colonists who had bled to take it watched their prize handed back to the enemy by diplomats across an ocean. It left a lasting bitterness toward how London ran its empire. So when the British came again in 1758, they were not just attacking a fortress. They were taking back something they had won and lost once already.' },
    ],
    meanwhile: { region: 'New England', title: 'Won, then given away', body: 'The men of Massachusetts, Connecticut, New Hampshire, and Rhode Island who captured Louisbourg in 1745 thought they had done something permanent. Three years later a treaty signed in Europe returned it to France for reasons that had nothing to do with them. The grudge outlived the peace, and it is part of why the second taking of Louisbourg, by the king’s regulars this time, carried so much weight.' },
  },

  'the-landing': {
    eyebrow: 'Louisbourg · Into the surf',
    title: 'The landing',
    blocks: [
      { p: 'The fleet that came in the spring of 1758 was enormous, the largest force Britain had ever sent against a single point in North America. Major General Jeffery Amherst (British) held overall command on land. The sea belonged to Admiral Edward Boscawen (British) and the Royal Navy, some forty warships and a hundred and fifty transports carrying around fourteen thousand soldiers. Boscawen held joint command of the fleet and the transports, and it was his ships that would seal the harbor and, in the end, send a boarding party into it in the dark. Among Amherst’s brigadiers was a thin, red-haired, restless young officer named James Wolfe (British), thirty-one years old, who would be given the hardest job of the campaign. The defenders, under the French governor, Drucour (French), numbered something like six to seven thousand counting the marines and sailors off the warships in the harbor. The French had the walls. The British had to get ashore first, and getting ashore was the part that nearly did not happen.' },
      { fig: '/war-img/fi-louisbourg-siege.jpg', cap: 'The largest force Britain had ever sent at a single point in North America came ashore at Gabarus Bay into murderous fire. Wolfe signaled the recall, then a few boats that ignored it found a sheltered slot of rock, and the whole assault turned on it.', credit: 'Siege of Louisbourg, 1758 · public domain' },
      { p: 'The chosen landing place was Freshwater Cove (the French called it the Anse de la Cormorandière), a few miles down the coast from the fortress. The French knew it was a likely spot and had prepared for it, digging entrenchments along the shore and planting cannon to sweep the beach. On the morning of June 8, 1758, Wolfe led the assault division in toward the rocks: the grenadiers (the army’s biggest, hardest assault troops), the light infantry (picked marksmen trained to move fast and loose), rangers, and Highlanders, all packed into open boats and rowing through a heavy Atlantic surf. As they came into range the French opened up with grapeshot (clustered iron balls that turned a cannon into a giant shotgun) and musket fire, sweeping the boats. Men were hit. Boats were swamped in the breakers. The fire was murderous, and the landing was going nowhere.' },
      { p: 'Wolfe saw it failing. He raised his hand and signaled the boats to sheer off, to pull back from the slaughter before the whole division was wrecked in the surf. That should have been the end of it for the day.' },
      { p: 'It was not, because of a few boats on the far edge of the line. Three boatloads of light infantry, either not seeing the recall signal in the chaos or choosing not to, kept going. They drove their boats toward a craggy little point of rocks where a jut of land happened to shelter the water from the French guns, a slot of dead ground the defenders’ cannon could not reach. They came in through the breakers, scrambled out onto the rocks, and got a foothold ashore, out of the killing fire. Wolfe saw what they had found. Instead of calling everyone back, he flipped the whole plan and funneled the rest of his division toward that sheltered patch of rock. More men got ashore. Then more. Once the British had a solid body of troops on land and working along the shore, the French entrenchments were outflanked, hit from a direction they could not hold, and the defenders fell back to the fortress. A landing that had been one signal away from collapse had instead won the beach. The young brigadier who had read the slot of rock and turned a failing assault into a foothold would, a year later, die taking Quebec. The siege could begin.' },
    ],
    meanwhile: { region: 'The beach', title: 'The boats that broke off', body: 'The whole campaign turned on a handful of boats and a slot of rock. Had those light infantrymen obeyed the recall like the rest, the assault would have washed back out to sea bloodied and beaten, and the summer’s whole timetable, Louisbourg and the road to Quebec behind it, would have slipped. Battles are supposed to turn on grand plans. This one turned on men who did not pull back when they were told to.' },
  },

  'the-siege': {
    eyebrow: 'Louisbourg · Closing the ring',
    title: 'The siege',
    blocks: [
      { p: 'With the army ashore, the work became methodical and grinding, the textbook business of an eighteenth-century siege. You did not storm a fortress like Louisbourg head-on if you could help it; you strangled it. The British dug trenches and zigzag approaches, hauled their heavy guns forward, and built batteries (clusters of heavy cannon) closer and closer to the walls, tightening the ring week by week. Boscawen’s fleet sealed the sea, so no help and no escape could come by water. Inside, Drucour mounted a far stiffer defense than the fortress had managed in 1745, sending out sorties (armed raids out from the walls) and trading fire, but the math of a siege is patient and cruel, and it ran against him.' },
      { fig: '/war-img/fi-louisbourg-prudent.jpg', cap: 'The end of the French harbor squadron on the night of July 25, 1758: a British boarding party burns the Prudent where she had run aground and tows out the captured Bienfaisant, clearing the harbor for the Royal Navy. With the sea sealed and the squadron gone, the fortress was strangled.', credit: 'Richard Paton · engraving after the painting · 1771 · Maritime Museum of the Atlantic (M55.7.1) · public domain' },
      { p: 'One of Wolfe’s first moves set the pattern. On June 12 he took a detachment around to Lighthouse Point, the high ground across the mouth of the harbor, and planted batteries there. From that perch the British could fire down not only on the fortress defenses but on the French warships moored in the harbor below. Those ships were Louisbourg’s other shield. Drucour had ordered them to stay put in the harbor, over the objections of their own captains, on the theory that their guns would help hold off the British. Instead, penned in and unable to maneuver, they became targets.' },
      { fig: '/war-img/fi-louisbourg-siege-map.jpg', cap: 'The siege end to end: the British landed at Freshwater Cove in Gabarus Bay, closed a ring of trenches and batteries on the fortress from the land, and Wolfe marched around to Lighthouse Point to fire across the harbour mouth at the moored French squadron. A night boat raid cut out the last two ships, Prudent and Bienfaisant.', credit: 'Stuff Happened map' },
      { p: 'The harbor squadron died over a few days in late July, and it died by fire. On July 21 a British mortar shell arced down from Lighthouse Point and set the sixty-four-gun Célèbre ablaze. The flames jumped from ship to ship in the crowded anchorage, catching the Entreprenant, a seventy-four-gun ship of the line, and the Capricieux. By the time the fires burned out, three French ships of the line were gone. Two days later, on July 23, British heated shot (cannonballs deliberately fired red-hot to start fires) ignited the King’s Bastion, the great barracks block at the center of the fortress that served as its headquarters. It was the heart of the place, and it burned in full view of the defenders and the town, the headquarters of the strongest fortress in French North America going up in flame while the British guns kept firing. Then, on the night of July 25, Boscawen sent a Royal Navy cutting-out party rowing quietly into the harbor in the dark, to board the two remaining major warships. They captured the Bienfaisant and set the Prudent on fire. The French fleet at Louisbourg had ceased to exist, and with it went the harbor’s last defense and any hope of relief by sea. (A young sailing master named James Cook, years before his Pacific voyages made him famous, was on hand and noted the night’s work in his log.)' },
      { p: 'Inside the walls, the defense became a matter of stubbornness against the inevitable. The French governor’s wife, Madame Drucour, took her own part in it: by the account of her husband’s biographer, each day throughout the siege she fired three guns from the ramparts to hearten the troops. But the British batteries were now hammering the town from the land and from across the harbor, the walls were breaking up under sustained fire, and there was no relief coming. With the harbor squadron destroyed, Louisbourg had no fleet to defend its waterfront and no chance of rescue by sea, and that, as much as the breaking walls, is what ended the siege. Drucour had run out of fortress to defend.' },
    ],
    meanwhile: { region: 'The harbor', title: 'Ships nailed to their moorings', body: 'Drucour kept his warships bottled in the harbor to help defend it, and that decision sealed their fate. Free to run, some might have escaped to fight again or to carry word for relief. Anchored in a closing trap, raked by guns on the heights and then boarded in the night, they burned where they sat. The shield meant to protect Louisbourg went down with it.' },
  },

  'the-fall-and-the-road-to-quebec': {
    eyebrow: 'Louisbourg · The reckoning',
    title: 'The fall and the road to Quebec',
    blocks: [
      { p: 'On July 26, 1758, after about seven weeks, Drucour surrendered. He had hoped for the honours of war, the customary courtesy by which a garrison that had fought well was allowed to march out with its weapons, its flags, and its dignity, the same courtesy the French had extended to a beaten British garrison at Minorca. Amherst refused. The surrender would be unconditional. He pointed to what had happened at the surrenders of Fort Oswego and, the year before, Fort William Henry, where British soldiers who had laid down their arms under terms were set upon and killed. There would be no honourable march-out here. The hard terms had a hard purpose: an unconditional surrender meant the roughly five thousand six hundred men of the garrison were shipped to England as prisoners of war rather than paroled, the way the French garrison at Fort William Henry had been the year before. Paroled men could be exchanged and fight again; prisoners in England could not. Drucour, pressed by his own commissary on behalf of the trapped civilians in the town, accepted the hard terms. One French regiment, the Cambis, would not stomach it: rather than hand over their colors to the enemy, the men broke their muskets and burned their regimental flags.' },
      { fig: '/war-img/fi-louisbourg-siege-plan.jpg', cap: 'A plan of the 1758 siege with the ships’ positions marked, the textbook ring the British closed around Louisbourg over about seven weeks before Drucour accepted unconditional terms. With the fortress taken, the St. Lawrence lay clear all the way to Quebec.', credit: 'Historical Atlas of Canada (ed. Lawrence J. Burpee, 1927) · map · public domain' },
      { p: 'The cost on the field had been lopsided. The British lost roughly a hundred and seventy killed and three hundred and fifty wounded. The French lost about a hundred killed and three hundred wounded. But the surrender swept up far more than the dead and hurt: more than five thousand six hundred French soldiers became prisoners of war, along with some two hundred cannon and the wreck of the fortress itself.' },
      { pill: '/war-french-indian/battles/quebec', plabel: 'The fall of Louisbourg opened the river road to Quebec, 1759' },
      { p: 'What followed the surrender was harder than the siege, and it fell on people who had not fought it. With Louisbourg gone, the French settlers of the region, the Acadians (the French farming families who had lived in these maritime lands for generations), lost their protection, and the British set about deporting them. This was the second great wave of the expulsion of the Acadians, and it came in two separate clearances. One swept up the Acadians of Île Royale itself, the smaller of the two. The other was its own ordered campaign across the water on Île Saint-Jean (today Prince Edward Island), run by Lieutenant Colonel Andrew Rollo, who was sent to round up the island’s families and ship them to France. Around three thousand one hundred people were deported from Île Saint-Jean, and roughly sixteen hundred and forty-nine of them died, many drowned when the transports Duke William and Violet went down at sea, others killed by disease in the holds. That made the Île Saint-Jean wave the deadliest single episode of the whole Expulsion of the Acadians. It was a deliberate uprooting of a civilian population, and the human cost of taking Louisbourg is not honestly told without it.' },
      { pill: '/war-french-indian/off-the-battlefield/acadian-expulsion', plabel: 'The deportation of the Acadians' },
      { p: 'The army was not done with the Gulf either. Wolfe, with the naval officer Sir Charles Hardy, took some fifteen hundred troops up into the Gulf of St. Lawrence that autumn and worked the French coast. They burned around two hundred fishing vessels, but they burned far more than boats. They put the torch to the settlements themselves, a church and the houses at Miramichi, the villages at Grande-Rivière and Pabos, and they destroyed the dwellings of the Mi’kmaq, the Native people of these lands, who lived along this coast and whose homes were among those burned. The point was cold and strategic: those fisheries fed Quebec, and stripping them, and the people who worked them, weakened the city before the blow that was coming. It is named plainly here because it was a campaign against civilians, not only against ships.' },
      { p: 'And the blow was coming. That was always what Louisbourg was for. With the great fortress in British hands, the sea gate stood open, and the St. Lawrence lay clear all the way up to the capital of New France. The following spring, the same Brigadier Wolfe who had found the slot of rock at Freshwater Cove would sail up that river at the head of the army that took Quebec, and with Quebec, the war for the continent would turn for good. The British later blew Louisbourg’s walls apart with gunpowder so that no treaty could ever hand it back again. They had learned that lesson once.' },
    ],
    meanwhile: { region: 'Île Saint-Jean', title: 'The families on the ships', body: 'The deportation that followed the siege fell on farming families who had built lives in these lands over generations. Loaded into crowded transports and sent across the Atlantic, many never arrived; ships were lost and sickness ran through the holds. The fortress fell in seven weeks. The undoing of the people who lived around it took years, and some of them paid for the fall with their lives.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={LOUISBOURG_NARR}
    id={id}
    slug="louisbourg"
    battleName="Louisbourg"
    theatreId="fi-battles"
    battleId="fi-louisbourg"
    theatreHref="/war-french-indian/battles"
    accent="var(--fi-battles)"
    endHref="/war-french-indian?theatre=fi-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
