'use client'

// Mobile Bay — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise → integrate. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const MOBILE_BAY_NARR: Record<string, Narr> = {
  'the-last-door': {
    eyebrow: 'Mobile Bay · The prize',
    title: 'The Last Door on the Gulf',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -89, lonMax: -87.2, latMin: 29.6, latMax: 30.8 },
        states: [
          { name: 'Alabama', tone: 'focus', label: 'ALABAMA', labelLon: -87.5, labelLat: 30.7 },
          { name: 'Mississippi' }, { name: 'Florida' }, { name: 'Georgia' }, { name: 'Tennessee' },
        ],
        dots: [
          { name: 'Mobile Bay', date: 'Aug 5, 1864', lat: 30.23, lon: -88.02, heavy: true, anchor: 'start' },
          { name: 'Fort Gaines (Dauphin Island)', lat: 30.25, lon: -88.12, color: '#8a8175', anchor: 'end' },
        ],
      } },






      { p: 'By the summer of 1864, the Confederacy was a house with most of its doors nailed shut. The Union navy had spent three years choking off the Southern coast with a blockade, a wall of warships parked off an enemy’s harbors to stop anything from sailing in or out. The point of it was economic strangulation: keep cotton from getting out to be sold, and keep guns, medicine, and manufactured goods from getting in. By August 1864, the blockade had sealed nearly every important harbor on the Gulf of Mexico. Nearly.' },
      { p: 'The one big exception, east of the Mississippi River, was Mobile, Alabama. Mobile Bay was the last major Gulf port still in Confederate hands, and that made it the Gulf’s surviving hub for the blockade-runners, the fast, low-slung ships that made a living slipping through the Union wall in the dark, carrying cotton out and contraband cargo back in. As long as Mobile stayed open, the South had a working back door on the Gulf. Closing it would slam that door and tighten the noose one more notch.' },
      { p: 'The Confederacy fought to preserve and extend slavery, and the blockade-runners feeding through Mobile were the supply line of a republic built on enslaved labor. The door was a door for that.' },
      { h: 'Two Forts and a Minefield', eyebrow: 'The defenses' },
      { p: 'Guarding the door were two forts and a minefield. On the east side of the channel, the right hand as you steam in from the Gulf, stood Fort Morgan, the strong one, mounting forty-six guns on Mobile Point. On the west side, on Dauphin Island, stood the weaker Fort Gaines, with twenty-six guns. A third, Fort Powell, sat off to the northwest covering a back channel, well away from the main passage. Strung across the channel between the forts were the torpedoes, which in 1864 did not mean a self-propelled weapon at all. A "torpedo" was a moored naval mine: a keg of gunpowder anchored under the surface, rigged to blow when a ship’s hull touched it. The Confederates had planted roughly sixty-seven of them across the channel. The man who meant to run that gauntlet was Rear Admiral David G. Farragut.' },
      { fig: '/war-img/mobile-bay-the-bay.png', cap: 'The mouth of Mobile Bay: Fort Morgan on the east shore, Fort Gaines on Dauphin Island to the west, the buoyed minefield across the channel, and the Confederate squadron waiting inside.', credit: 'Map: Stuff Happened' },
      { p: 'The target on August 5, 1864, was the mouth of the bay, the channel ships passed through, not the city of Mobile, which sat miles up the bay and would not be attacked until 1865. The battle corked the bay. It did not take the town.' },
    ],
    meanwhile: { region: 'the Atlantic coast', title: 'The Gulf half of a two-door job', body: 'Mobile Bay was one of the last two big blockade-running ports the Confederacy had left. The other was Wilmington, North Carolina, on the Atlantic side, guarded by Fort Fisher. Mobile Bay shut the Gulf door in August 1864; Fort Fisher would shut the Atlantic door in January 1865. After those two, the Confederacy had essentially no open harbor left on either coast. Mobile Bay was not a sideshow. It was half the job of finally sealing the South off from the sea.' },
  },

  'running-the-forts': {
    eyebrow: 'Dawn, August 5 · Lashed in pairs, straight at the guns',
    title: 'The Fleet Stands In',
    blocks: [
      { p: 'Rear Admiral David G. Farragut (North), commander of the West Gulf Blockading Squadron, flew his flag in the steam sloop USS Hartford (a sloop-of-war being a single-deck warship, smaller than a frigate but still a serious gun platform). His plan was less clever than it was nervy. He would run the forts. "Running" a fort means exactly what it sounds like: instead of stopping to slug it out with the fort’s guns, you steam past at full speed, take your beating on the way through, and get into the water beyond before the fort can finish you. He would push his whole fleet through the channel, past Forts Morgan and Gaines, over the minefield, into the bay, then destroy the Confederate squadron waiting inside and seal the port. The forts themselves he meant to take the slow way, from both sides at once. Major General Gordon Granger (North) had already landed roughly two thousand army troops on Dauphin Island to besiege Forts Gaines and Morgan from the landward side, so that once the fleet was through, each fort would be squeezed between Granger’s infantry behind it and the navy’s guns in front of it.' },
      { p: 'The fleet had two parts. Leading on the starboard side, the right, the Fort Morgan side where the deep water ran, came a single column of four monitors. A monitor was a low, almost-submerged ironclad: a flat iron deck barely above the waterline, with the guns mounted in a revolving armored turret, presenting almost nothing for an enemy to hit. The four were Tecumseh, Manhattan, Winnebago, and Chickasaw, in that order, with Commander Tunis A. M. Craven (North) in the lead aboard Tecumseh.' },
      { p: 'To port came the wooden ships, the big steam sloops and frigates, and here Farragut did something that tells you how much he respected the forts. He lashed them in pairs. Each large wooden warship was tied alongside a smaller gunboat on its disengaged side (the port side, away from Fort Morgan), so the big ship’s hull shielded the little one from the fort’s fire, and if either was crippled the other could tow it clear. Hartford was lashed to the gunboat Metacomet under Lieutenant Commander James E. Jouett (North). At the head of the wooden column came USS Brooklyn, under Captain James Alden (North), with Farragut’s Hartford close behind it and a long line of paired sloops and gunboats trailing after.' },
      { fig: '/war-img/mobile-bay-running-the-forts.png', cap: 'The fleet stands in at dawn: four monitors leading to starboard along the Fort Morgan side, the wooden ships lashed in pairs threading the narrow lane between the buoyed mines and the fort.', credit: 'Map: Stuff Happened' },
      { p: 'Just before dawn the fleet formed up, and around six to seven in the morning it stood in toward the channel, the monitors leading, Brooklyn at the head of the wooden line. Fort Morgan opened fire. The big wooden ships took the hammering on their starboard sides while the lashed gunboats sheltered to port, and the column pushed up the narrow lane, mines and their marker buoys on the left hand, Fort Morgan’s forty-six guns on the right. The fleet had to thread between the two, because the safe water was a tight strip hard up under the fort.' },
      { p: 'Then the lead monitor died in half a minute, and the whole attack nearly died with it.' },
    ],
  },

  'damn-the-torpedoes': {
    eyebrow: '~7:30 a.m. · The minefield and the order',
    title: 'Tecumseh Sinks, Brooklyn Stalls, and Farragut Decides',
    blocks: [
      { p: 'The minefield had a gap in it. The Confederates had left a roughly five-hundred-yard opening on the eastern side of the channel, the Fort Morgan side, so that their own blockade-runners could still slip in and out, and they had marked the edge of the live mines with a line of buoys. The safe lane ran between that buoy line and the fort. Everyone in Rear Admiral David G. Farragut’s (North) fleet had been told the same thing: stay east of the buoys, no matter how close that put you to Fort Morgan’s guns. East was the narrow safe strip. West of the buoys was the minefield.' },
      { p: 'Commander Tunis A. M. Craven (North), in the lead, did not stay east of the buoys. Trying to close on the Confederate ironclad waiting inside the bay, he steered Tecumseh west of the buoy line, across to the mined side. Almost at once she struck a torpedo. The monitor went down bow-first in something like twenty-five to thirty seconds, so fast there was no time to do anything. Of her crew (sources differ a little on the exact complement, but it was about a hundred men) only twenty-one were saved. Somewhere around ninety men went down with her. That single mine, in less than half a minute, killed more Union sailors than the entire rest of the battle combined.' },
      { p: 'And the attack stalled. With the lead monitor gone in front of everyone’s eyes and the channel now visibly full of mines, Brooklyn stopped. Captain James Alden (North) began to back his ship and signaled the flagship for instructions. But a column of warships under a fort’s guns cannot afford to stop. Brooklyn stalling fouled the whole line behind her, leaving the fleet piling up, motionless, directly beneath Fort Morgan. This was the moment the battle could have been lost.' },
      { h: 'The Most Famous Order in the Navy', eyebrow: 'Farragut decides' },
      { p: 'This is where the most famous order in American naval history is supposed to have been given. The version on the monuments and in the schoolbooks is "Damn the torpedoes! Full speed ahead!", Farragut refusing to stop and driving his flagship through the mines. The action is exactly right and fully documented. Farragut ordered Hartford forward, swung her around the stalled Brooklyn into the lead, and drove straight through the mined water, over the very field that had just swallowed an ironclad in thirty seconds, with no way of knowing his own wooden flagship would not go the same way. The whole fleet followed Hartford through, and the mines they passed over did not explode. They had been in the water for weeks. Salt water had crept into many of them and spoiled the powder, or rusted the firing mechanisms, so that ship after ship bumped over live mines that simply failed to go off. That is what won the battle.' },
      { p: 'The words are a different matter. The famous line did not appear in print until years after the battle, first attributed to Farragut something like fourteen years later, and some historians doubt he said it at all. A signal officer close enough to have heard it wrote a detailed account of the action that never mentions the exclamation, and men who were there doubted any shouted order could even have been heard over the guns. What he more plausibly said, if he said anything, was an order to his flag captain and to Lieutenant Commander James E. Jouett (North), something on the order of "Damn the torpedoes. Four bells, Captain Drayton," then "Go ahead, Jouett, full speed." The line we remember was stitched together and polished in the retelling. What is certain is that the lead ship sank, the column froze, and Farragut shoved his own flagship into the front and went through the mines anyway.' },
      { p: 'There is a second iconic image from this morning, and the record qualifies it the same way. We picture Farragut lashed high in Hartford’s rigging, tied aloft so he could see over the gun smoke, binding himself to his ship. The truth is less theatrical and more human. His flag captain, Captain Percival Drayton (North), the officer who actually ran the flagship so the admiral could command the whole fleet, worried that Farragut might be hit and fall to the deck from where he stood up in the shrouds, and had a sailor secure him with a line. As the story is told, Farragut waved the man off, saying he was fine, but the sailor had his orders and lashed him anyway. He was tied up there for his own safety at his captain’s insistence, not out of bravado: the most famous sailor in the country, fussed over by his own crew.' },
    ],
    meanwhile: { region: 'the casualty list', title: 'Most of the dead, in one ship', body: 'The casualty math at Mobile Bay is lopsided. The Union fleet lost roughly 150 killed and 170 wounded in the naval action, and the great majority of those deaths were the men of Tecumseh, gone in under thirty seconds when she struck the mine. The fleet fight that followed, ship against ship, was comparatively cheap in blood. One torpedo accounted for most of the Union dead in the whole battle. The forts, when they fell, were cheaper still: Granger’s land troops besieging them lost about one man killed and seven wounded. The big Confederate "loss" was not battle dead either. It was prisoners, the fort garrisons that eventually surrendered.' },
  },

  'the-tennessee': {
    eyebrow: 'Inside the bay · One ironclad against a fleet',
    title: 'Buchanan Turns and Fights Them All',
    blocks: [
      { p: 'The fleet was now inside Mobile Bay, north of the mines, in open water. Waiting for it was the Confederate squadron, and "squadron" flatters it. Admiral Franklin Buchanan (South), the senior Confederate naval officer afloat, had exactly four ships: the ironclad ram CSS Tennessee, his flagship, and three small wooden gunboats, Selma, Morgan, and Gaines. An ironclad ram was a warship sheathed in iron armor with a reinforced bow meant to be driven straight into an enemy’s hull like a battering ram. Tennessee was the strongest ironclad in Confederate service and carried six guns, but her engines were weak and she was painfully slow. Against her and three gunboats, Farragut had four monitors and more than a dozen wooden warships.' },
      { p: 'The three gunboats were overmatched the moment the fleet was through, and they folded almost at once. Gaines was wrecked, Selma was run down and taken, and Morgan slipped away up toward the city. Buchanan could have run Tennessee under the guns of Fort Morgan and waited. Instead he turned his single ironclad around and steamed it back into the entire Union fleet, alone.' },
      { fig: '/war-img/mobile-bay-the-tennessee.png', cap: 'CSS Tennessee turns back alone into the Union fleet inside the bay; the big sloops ram her again and again while the monitors Manhattan and Chickasaw close in and batter her armor.', credit: 'Map: Stuff Happened' },
      { p: 'What followed was close, brutal, and slow. The big Union sloops bore down and rammed Tennessee again and again, trying to run her under, while the whole fleet pounded her at point-blank range. The monitors Manhattan and Chickasaw closed in and battered her armor. For something like an hour she took it from every direction at once. Her smokestack was shot away, her exposed steering chains were parted so she could no longer steer, and she drifted nearly motionless under the guns of a fleet. Buchanan himself went down with a badly broken leg.' },
      { p: 'With the ship helpless and her commander wounded, Commander James D. Johnston (South), Tennessee’s flag captain, asked the wounded Buchanan’s permission and ran up the white flag. The strongest ironclad in the Confederacy had fought the whole Union fleet single-handed until she was battered into surrender. By around ten in the morning, the bay was won.' },
    ],
    meanwhile: { region: 'the sunken Tecumseh', title: 'Tecumseh’s commander did not jump', body: 'Back at the sunken monitor, the battle’s most-told human moment had played out in the few seconds Tecumseh took to go down, and like the famous order it survives as naval lore more than documented fact, because the only man who could tell it was the one who lived. As the story is handed down, Commander Craven and the ship’s pilot, John Collins, reached the narrow escape scuttle at the same instant, with time for only one man to climb out. Craven is said to have stepped back, "After you, pilot," and let Collins go up first. Collins made it. Craven did not. Collins later described the end: the moment he reached the top of the ladder, the vessel seemed to drop out from under him. The account is ranked alongside "Don’t give up the ship" as a Navy touchstone, though it rests on one survivor’s memory of a dead man’s last words.' },
  },

  'what-it-won': {
    eyebrow: 'The meaning · The door, the reason, and the men on the deck',
    title: 'What the Fleet Shut, and Who Shut It',
    blocks: [
      { p: 'Mobile Bay was a Union victory. Rear Admiral David G. Farragut’s (North) fleet forced the bay, destroyed the last significant Confederate squadron on the Gulf (Tennessee captured, the gunboats wrecked or taken, Admiral Franklin Buchanan (South) a prisoner), and closed Mobile to blockade-runners. Over the following weeks the forts gave up, squeezed between the fleet inside the bay and Major General Gordon Granger’s (North) troops on the land side. Fort Powell, cut off behind the fleet, had its guns spiked and its magazine blown by Lieutenant Colonel James M. Williams (South) the night after the battle. Fort Gaines surrendered on August 8 under Colonel Charles D. Anderson (South), and the strong one, Fort Morgan, under Brigadier General Richard L. Page (South), held out under bombardment until August 23. The last open Gulf door, east of the Mississippi, was shut.' },
      { p: 'The port closed, not the city. Mobile the town, miles up the bay, was never attacked in 1864 and held out until April 1865. What happened on August 5 corked the bottle. It did not drink it.' },
      { h: 'A Vote in the 1864 Election', eyebrow: 'The political payoff' },
      { p: 'The strategic payoff was large, and the political payoff was larger. Mobile Bay came three months before the November 1864 election, at the lowest ebb of Northern morale. The war was grinding on, the casualty lists were endless, and Abraham Lincoln’s re-election was genuinely in doubt. A war-weary North was within reach of voting in a peace candidate and letting the Confederacy go. Then, in a matter of weeks, the news turned. Farragut took Mobile Bay, and almost immediately William T. Sherman captured Atlanta on September 2. The gloom broke. Historian James McPherson described Mobile Bay and Atlanta together as the first blow of a one-two punch that scattered Northern war-weariness and helped assure Lincoln’s re-election, and with it the war’s continuation to total Union victory and the end of slavery. The fleet action in the bay was also a vote in that election.' },
      { p: 'The door was a door for something. The Confederacy fought to preserve and extend slavery, and the blockade-runners feeding through Mobile were the supply line of that slaveholding republic. The blockade that strangled them was, concretely, the instrument shutting down the economy of a society built on owning human beings. Emancipation and the blockade were two halves of one policy, and as Union ships took the coast they began taking fugitive slaves aboard and enlisting the men. Closing the port was, in the most literal sense, an attack on slavery. The port was the object. Slavery was the reason.' },
      { pill: '/war-civil-war/off-the-battlefield/emancipation', plabel: 'The Emancipation Proclamation: the cause behind the blockade' },
      { h: 'Who Was Firing Farragut’s Guns', eyebrow: 'The cause made flesh' },
      { p: 'The clearest proof of that, at Mobile Bay, was who was firing Farragut’s guns. By 1864 the U.S. Navy was a substantially integrated force. Nearly eighteen thousand men of African descent served in it during the war, about a fifth of its entire enlisted strength. In Farragut’s own West Gulf Blockading Squadron the share was lower than in the Navy as a whole, roughly one in five of the enlisted men aboard ship, the smallest proportion of any of the major squadrons. But they were not in the back. They were on the gun decks of the flagship, in the fight.' },
      { p: 'Two of them, working Hartford’s shell-whip (the rope-and-tackle hoist that lifted heavy gunpowder shells up from the magazine below to the guns on deck), earned the Medal of Honor that day. Landsman John Lawson (North), a landsman being the Navy’s entry rating, the lowest rung, given to a man new to the sea, was a free-born Black sailor from Philadelphia. When an enemy shell struck the berth deck, the crew’s deck just below the guns, it wounded him in the leg and slammed him violently against the side of the ship. He was urged to go below for treatment, refused, and stayed at his post for the rest of the action. Landsman Wilson Brown (North) had been born enslaved on Botany Bay Plantation, near Natchez, Mississippi. A shellburst killed a man on the ladder above him and knocked Brown unconscious into the hold. He came to, climbed back to the shell-whip on the berth deck, and kept the ammunition moving though four of the six men at his station had been killed or wounded. Four African American sailors won the Medal of Honor at Mobile Bay, among an extraordinary number awarded for the battle.' },
      { p: 'A man born a slave on a Mississippi plantation was, that August morning, hauling shells to the guns of the fleet that was shutting the Confederacy’s last Gulf door. The war’s cause and the war’s instrument stood on the same deck.' },
    ],
    meanwhile: { region: 'the Atlantic coast', title: 'And then the other door', body: 'Mobile Bay shut the Gulf. It did not, by itself, seal the Confederacy off from the sea. There was still one big door open, on the Atlantic side, where Wilmington, North Carolina ran its blockade-runners out under the guns of Fort Fisher. That door held until January 1865, when a Union fleet and landing force finally took Fort Fisher and closed it too. Mobile Bay in August, Fort Fisher in January, and a Confederacy with its last harbors shut, its armies starving, and the men it had once claimed to own now manning the guns against it had nothing left to run cotton out of or guns into. The bay was where the Gulf half of that ending was won.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={MOBILE_BAY_NARR} id={id} slug="mobile-bay" battleName="Mobile Bay" theatreId="naval" theatreHref="/war-civil-war/naval" battleId="n-mobilebay" accent="#b44d3b" />
}
