'use client'

// Bonhomme Richard vs. Serapis (September 23, 1779), battle sections · American
// Revolution. The vertical's only naval battle and its FIRST naval page, so every
// naval term is inline-defined on first use (frigate, broadside, rake, strike the
// colors, quarter, East Indiaman...). Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → critic gates (fact-check
// + storytelling + newcomer-clarity + framing, parallel) → reconcile → revise.
// Data only; rendered by the shared <BattleSectionReader>. House voice: no
// em-dashes; side-tags once on first mention per section, combatants only.
// Legend control per the final: the famous line is TOLD AS LEGEND (Dale via
// Sherburne, 1825) with the documented alternatives beside it; the QUOTE block is
// the safe "most determined negative" paraphrase, never the famous line; no
// verbatim "double/redoubled fury" anywhere (fact SF1 — the cross-surface
// discrepancy note lives in the final's FACT LEDGER); the Landais broadsides are
// fact, intent alleged only; the grenade sailor stays anonymous; the sword
// ceremony and "make a lord of him" ride "the story goes"; the nailed colors
// ride "by the accounts."
// LOCATORS: this battle was fought off the British coast, so both locators use
// UK / North Sea geography with NO US state outlines (states: [] — the renderer
// must not default to a US-state base; the DottedMap has no UK coastline data,
// so free labels carry the geography). The final's arrows are not renderable in
// the locator block contract; the movement lines live in the captions instead
// (Saratoga/Ticonderoga precedent). The final's "starred" departure dot
// (Lorient) renders heavy (the contract has no star marker).
// Sources: audits/war-pipeline/rev-bonhomme-richard-final.md (+ rev-bonhomme-richard-factpack.md).

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import type { Block } from '@/components/mode/battle-reader'

// Locator 1 · tactical: the battle off Flamborough Head (Section 2). The precise
// battle site is unknown and the wreck never found; the markers are symbolic at
// locator scale (pack §10).
const TACTICAL_LOCATOR: Block = {
  locator: {
    eyebrow: 'The ground · September 23, 1779',
    caption: 'Pearson\'s whole fight was about this geometry. The Baltic convoy ran inshore for the shelter of Bridlington and Scarborough while he stood the Serapis out to sea, between the merchantmen and the raider, and bought their escape with his ship. The two warships then fought a few miles off Flamborough Head, drifting north through the night, close enough that crowds gathered on the chalk cliffs from Scarborough down to the Head to watch by moonlight. The Bonhomme Richard sank two days later in open water off the coast; her wreck has never been found.',
    frame: { lonMin: -0.85, lonMax: 0.45, latMin: 53.45, latMax: 54.65 },
    states: [],
    labels: [
      { text: 'THE NORTH SEA', lon: 0.2, lat: 54.52, kind: 'water', size: 12, anchor: 'middle' },
      { text: 'YORKSHIRE', lon: -0.62, lat: 54.45, kind: 'faint', size: 11, anchor: 'middle' },
    ],
    dots: [
      { name: 'Flamborough Head', date: 'the chalk headland; the crowds on the cliffs', lat: 54.117, lon: -0.083, heavy: true, anchor: 'end', dy: 14, dateBelow: true },
      { name: 'The battle site', date: 'Sept 23, evening', lat: 54.15, lon: 0.02, heavy: true, anchor: 'start', dy: -22, dateBelow: true },
      { name: 'The sinking site', date: 'sank Sept 25; wreck never found', lat: 54.20, lon: 0.10, anchor: 'middle', dy: -26, dateBelow: true },
      { name: 'Scarborough', date: 'northern end of the cliff-top crowds', lat: 54.288, lon: -0.402, anchor: 'end', dateBelow: true },
      { name: 'Filey', lat: 54.210, lon: -0.289, anchor: 'end', dy: 18 },
      { name: 'Bridlington', date: 'the convoy ran inshore to safety', lat: 54.085, lon: -0.187, anchor: 'end', dy: 8, dateBelow: true },
      { name: 'Spurn Head', date: 'the squadron reunited the day before', lat: 53.577, lon: 0.110, anchor: 'end', dateBelow: true },
      { name: 'Kingston upon Hull', date: 'Pearson\'s freedom-of-the-city, after', lat: 53.745, lon: -0.336, anchor: 'start', dateBelow: true },
    ],
  },
}

// Locator 2 · strategic: the cruise that drew the noose (Section 1).
const STRATEGIC_LOCATOR: Block = {
  locator: {
    eyebrow: 'The cruise · August–December 1779',
    caption: 'A French-financed squadron under American colors sailed out of France in August, looped the whole archipelago counter-clockwise scattering panic, stood within sight of Edinburgh until a gale blew it back out, and collided with the Baltic convoy at the elbow of England in September. Then it limped east into neutral Holland, to the Texel, the Dutch naval anchorage, with its flagship on the bottom and a captured British frigate flying its flag. The track reads as a noose drawn around Britain, which is exactly how the British coast, jumpy that summer over a Franco-Spanish invasion scare in the Channel, experienced it.',
    frame: { lonMin: -11.5, lonMax: 5.5, latMin: 47.0, latMax: 59.5 },
    states: [],
    labels: [
      { text: 'THE NORTH SEA', lon: 1.6, lat: 56.6, kind: 'water', size: 12, anchor: 'middle' },
      { text: 'THE ATLANTIC', lon: -9.4, lat: 50.6, kind: 'water', size: 12, anchor: 'middle' },
      { text: 'SCOTLAND', lon: -4.3, lat: 57.0, kind: 'faint', size: 11, anchor: 'middle' },
      { text: 'ENGLAND', lon: -1.7, lat: 52.4, kind: 'faint', size: 11, anchor: 'middle' },
      { text: 'IRELAND', lon: -8.0, lat: 53.3, kind: 'faint', size: 11, anchor: 'middle' },
      { text: 'FRANCE', lon: -0.8, lat: 47.8, kind: 'faint', size: 11, anchor: 'middle' },
    ],
    dots: [
      { name: 'Lorient / Groix roads', date: 'the squadron sails, Aug 14, 1779', lat: 47.748, lon: -3.366, heavy: true, anchor: 'start', dy: -10, dateBelow: true },
      { name: 'Cape Wrath', date: 'about Sept 1', lat: 58.625, lon: -4.997, anchor: 'start', dy: -8, dateBelow: true },
      { name: 'Flannan Isles', date: 'Jones\'s "Flamie Islands," late August', lat: 58.29, lon: -7.59, anchor: 'end', dy: 18, dateBelow: true },
      { name: 'Firth of Forth / Leith', date: 'the aborted descent on Edinburgh\'s port; a gale blew him out', lat: 55.990, lon: -3.171, anchor: 'start', dateBelow: true },
      { name: 'Flamborough Head', date: 'the collision with the convoy, Sept 23', lat: 54.117, lon: -0.083, heavy: true, anchor: 'end', dateBelow: true },
      { name: 'The Texel', date: 'in with the captured Serapis, Oct 3; out Dec 27', lat: 53.05, lon: 4.80, heavy: true, anchor: 'end', dy: -14, dateBelow: true },
      { name: 'Amsterdam', date: 'the celebrity reception', lat: 52.373, lon: 4.893, anchor: 'end', dy: 16, dateBelow: true },
    ],
  },
}

const BONHOMME_RICHARD_NARR: Record<string, Narr> = {
  'a-noose-around-britain': {
    eyebrow: 'Bonhomme Richard · The raider',
    title: 'A noose around Britain',
    blocks: [
      STRATEGIC_LOCATOR,
      { p: 'The American navy never tried to win the war at sea, because it could not. Britain owned the ocean. The Royal Navy moved British armies across it, supplied them, and blockaded the American coast, and the handful of ships the Continental Congress could float were never going to fight that fleet for command of the water. A naval squadron was a handful of ships sailing together; Britain\'s fleet was hundreds of warships, the sea itself. So the American naval war became something else: commerce raiding (preying on merchant shipping), privateering (private armed ships licensed to take enemy vessels for profit), and, above all, propaganda. The job was to make the ocean expensive and embarrassing for Britain, to carry the war to her own coasts and humiliate her there, until a real navy joined the fight. France had allied with the Americans in 1778; Spain came in during the summer of 1779; and that summer a combined Franco-Spanish fleet was maneuvering in the English Channel in an invasion scare. Britain\'s home coasts were already jumpy before John Paul Jones (American) ever appeared off them. His cruise landed on nerves that were frayed before he arrived.' },
      { p: 'Jones was the man for that kind of war, and he was not an easy man. He had been born plain John Paul in 1747, a gardener\'s son on the Solway coast of Scotland, the same firth he would one day raid. He went to sea at about thirteen, rose to merchant captain, and added "Jones" to his name after a bad business in 1773: he killed a mutinous sailor at Tobago, in the West Indies, called it self-defense, and fled to America rather than stand trial. In the Continental Navy he made himself its most aggressive captain, and to the British press its favorite villain. They drew him in the print shops as "Paul Jones the Pirate," a brigand under no lawful flag. The legal charge was simpler than the moral one. Britain had not recognized the United States as a nation, and so did not recognize a Continental Navy commission as a lawful flag at all. To British admiralty law Jones sailed under no recognized authority, which made him a pirate by their definition, and that was not just Grub Street talk: it was the position of the British government, which would later demand he be handed over as a pirate wherever he turned up. The reputation was not entirely unearned. In 1778, in the small warship Ranger, he had carried the war into British home waters: a night raid on the harbor of Whitehaven, on England\'s own northwest coast, the first hostile landing on English soil in roughly a century, materially trivial but loud out of all proportion; a bungled attempt the same day to kidnap a Scottish earl as a hostage, which ended with his crew, against his wishes, making off with the family silver as the only prize on offer, and Jones later buying it back at his own expense and returning it with a famously florid apology letter that did his own reputation no harm at all; and, the next morning, the capture of a Royal Navy warship off the Irish coast in about an hour, an American beating a British warship in a fair fight. He was vain, prickly, chivalrous, and ferociously brave, all at once.' },
      { fig: '/war-img/rev-bonhomme-richard-pirate.jpg', cap: '"Paul Jones the Pirate," a British print. The National Archives catalogs the original caricature as about 1779; this copy carries a later London publisher\'s imprint, the image still selling decades on. To the London press he was not a naval officer at all but a brigand sailing under no recognized flag, a man who had raided the English coast and could expect a rope if he were ever caught. The image is propaganda; the legal danger behind it was real.', credit: 'British print after the wartime caricature · National Archives (NARA) / Wikimedia Commons · public domain' },
      { pill: '/war-revolution/off-the-battlefield/war-at-sea', plabel: 'The whole American war at sea, raiding and prison hulks and one legend' },
      { p: 'France had bought him his ship. It was a tired one: an old East Indiaman, a merchant ship built in 1765 for the long trade run to India, worn out from two voyages to China, that Louis XVI\'s government purchased and handed to Jones early that year. Jones renamed her Bonhomme Richard, "Good-man Richard" or "Poor Richard," in honor of Benjamin Franklin, the American minister in Paris, whose Poor Richard\'s Almanack circulated in France under that name. She mounted about forty guns, an awkward mix that included six old eighteen-pounders (cannon throwing an eighteen-pound iron ball, the heaviest aboard) crammed into a low battery near the waterline. She was old and slow, and Jones\'s own report would call her "the good old Ship." Around her sailed a small squadron, all under American colors and all paid for with French money: the Continental frigate Alliance (a fast new American warship of 36 guns, given to the cause by France) under the French captain Pierre Landais; the French Pallas (32) under Denis-Nicolas Cottineau; and the small brig Vengeance (12). They had sailed from France in August 1779 with one weakness baked in from the start. Before leaving, the captains had signed an agreement that left each of them nearly independent of Jones, who was commodore (the squadron\'s commander) in little more than name. He could give orders. Whether his captains obeyed them was, by the paperwork, up to the captains. He had accepted those terms to get the cruise; the French money came with strings, and a man impatient to sail rather than haggle had signed them. He got both the cruise and the strings. Hold onto that. It explains the worst thing that happened in the battle.' },
      { p: 'The cruise was the noose drawn around Britain. Jones took the squadron counter-clockwise around the whole of the British Isles, up the west coast of Ireland, around the top of Scotland past Cape Wrath, then down the eastern coast, taking and sinking prizes (captured enemy ships) as he went and throwing every coastal town into alarm. In mid-September he sailed up the Firth of Forth (the long sea inlet that runs into the heart of Scotland\'s east coast as far as Edinburgh) meaning to descend on Leith, the port of Edinburgh, and got within cannon shot before a gale blew the squadron back out to sea. By September 23 he was off Flamborough Head, a great chalk headland on the Yorkshire coast in England\'s northeast. And there, late in the afternoon, the topsails of a large convoy came rounding the Head: more than forty merchant ships out of the Baltic, carrying timber, masts, hemp, and tar, the raw materials of British sea power, the very stuff the Royal Navy was built and rigged from. Losing that convoy would have genuinely hurt Britain. Guarding it were two warships: the brand-new HMS Serapis (British), a powerful frigate of 44 guns launched only that March, under Captain Richard Pearson (British), and the smaller hired ship Countess of Scarborough of 20 guns. Jones signaled a general chase, and his tired converted merchantman bore down on the most powerful warship he had ever faced.' },
      { fig: '/war-img/rev-bonhomme-richard-french-print.jpg', cap: 'A French engraving of the battle, after Richard Paton\'s painting, published while Paris was celebrating Jones. Its catalogued title misdates the action to September 22, a small reminder that the first prints of any battle were made fast, from secondhand reports, by men who were not there.', credit: 'French engraving after Richard Paton · National Archives (NARA) / Wikimedia Commons · public domain' },
    ],
    meanwhile: { region: 'The English Channel', title: 'Why the coast was already afraid', body: 'Jones did not arrive on a calm country. That same summer of 1779, a combined fleet of France and Spain, newly Britain\'s enemies, had sailed into the English Channel in such force that southern England braced for an invasion that never came. The coasts were watching the sea nervously for weeks before a single American sail appeared in the north. When Jones looped the islands scattering panic, he was pulling a thread that was already taut.' },
  },

  'the-fight-by-moonlight': {
    eyebrow: 'Bonhomme Richard · The battle',
    title: 'The fight by moonlight',
    blocks: [
      TACTICAL_LOCATOR,
      { p: 'Captain Richard Pearson (British) understood his job in a moment. The convoy, not the glory, was what mattered, so as Jones\'s squadron came on he put the Serapis and the Countess of Scarborough between the strangers and his merchant ships and signaled the convoy to run inshore for the shelter of Scarborough and Bridlington. The merchantmen crowded sail for the coast and got away, nearly all of them. That decision settled the strategic question before a gun was fired: whatever happened next to Pearson\'s own ship, he had already won the only fight that counted to Britain. Then he turned to face an enemy he did not yet know was John Paul Jones.' },
      { p: 'About seven in the evening, in the last of the light, the two big ships drew within pistol shot. Pearson hailed across the water, asking who the stranger was. Jones, who had been flying false British colors to get close, answered with evasions, then ran up American colors and opened fire. Both ships loosed their broadsides at almost the same instant. A broadside is every gun along one side of a ship firing together, the basic blow of a sea fight, a wall of iron thrown at the enemy\'s hull all at once. Each captain afterward believed the other had fired first, and there is no way now to settle it. It hardly mattered. With that first exchange, disaster struck the Bonhomme Richard.' },
      { p: 'Two of Jones\'s six old eighteen-pounders, the heaviest guns he had, burst when they fired. The cannon themselves blew apart, killing almost all the men working them and tearing up the deck above. Jones\'s own report is flat about it: those guns "did no Service Whatever: two out of three of them burst at the first fire, and killed almost all the men Who Were stationed to manage them." He abandoned the whole heavy battery on the spot. Even before they burst, the match had never been fair. The Serapis carried twenty heavy eighteen-pounders on her lower deck alone, while Jones\'s "about forty guns" included only six eighteen-pounders, and two of those had just blown themselves apart. From that moment the Richard could throw only a fraction of the Serapis\'s weight of iron, his lighter guns against her twenty heavy ones. To fight a gunnery duel now, trading broadsides at a distance, was simply to be pounded to splinters and forced to surrender. Jones had one chance, and it was the opposite of caution: get in close and hold on, so close that the enemy\'s advantage in heavy guns turned into a knife fight where his own marksmen and boarders could matter.' },
      { p: 'So he grappled. After a confused half hour of maneuvering, collisions, and a British attempt to board that was thrown back, the two ships fouled together, the Serapis\'s bowsprit caught in the Richard\'s rigging, an anchor hooking, and Jones and his men lashing the hulls fast with their own hands. Pearson dropped anchor, hoping the tide would drag the two apart and let his heavy guns work at a distance again. The lashings held. The moon rose about half past eight into a clear night, and the two ships hung there as one, bow to stern, the gun muzzles of each touching the other\'s planking. And the fight could be seen from the land. Crowds gathered on the high Yorkshire cliffs, from Scarborough down to Flamborough Head, to watch two ships burn and hammer each other by moonlight a few miles off their own coast: England watching an American raider fight under her own cliffs.' },
      { fig: '/war-img/rev-bonhomme-richard-pocock.jpg', cap: 'Nicholas Pocock\'s painting of the battle, with the second fight beyond the main pair: the French Pallas closing the smaller Countess of Scarborough while the Richard and the Serapis burned at the center. Pocock was a working marine painter of the era, and he gives the whole scene its sea room.', credit: 'Nicholas Pocock · oil painting · National Museum of the Royal Navy, Portsmouth / Wikimedia Commons · public domain' },
      { p: 'From then on it was a vertical battle, each ship winning the part of the other it could reach. The Serapis\'s heavy lower guns, firing point-blank, tore the Richard apart at and below the waterline, eventually firing clean through her hull and out the far side. But the Richard\'s tops, the fighting platforms high on her masts, swept the Serapis\'s open upper deck clear with musket fire and grenades (small hand-thrown bombs), until no British sailor could live in the open there. Each ship held a level the other could not. Both caught fire, again and again, and at moments the killing paused while crews on both sides fought the flames that threatened to burn them all together. Into that, the battle\'s single most consequential act came from one anonymous sailor. A man worked his way out along a yard, one of the long spars crossing a mast, the two ships lashed so close that the Richard\'s upper yards swung directly over the Serapis\'s open deck, until he hung over the enemy and dropped grenades down at her open hatches. One went through. It landed among a row of loose powder cartridges (the cloth bags of gunpowder for the guns) laid out along the lower gun deck, and the explosion ran the whole length of that deck, killing or horribly burning dozens of men and silencing gun after gun. Almost nothing else is known about the man who did it, not even, for certain, his name.' },
      { p: 'And then came the worst thing, and it came from Jones\'s own squadron. The Alliance (the American squadron\'s fresh frigate, untouched by the fight), under Pierre Landais (American), came up to the locked pair and fired her broadsides into both ships. Not once. She circled the two and raked them, raking being to fire down a ship\'s whole length, bow to stern, the deadliest angle in a sea fight, and the Alliance did it to her own flagship, again and again. Jones\'s report is anguished and precise: "Every tongue Cried that he Was firing into the Wrong Ship, but nothing availed; he passed round, firing into the B. H. R.\'s head, stern, and broadside, and by one of his Vollies Killed several of my best men, and mortally wounded a good officer on the forecastle." The Richard took shots under the water from her own consort, the ship that was supposed to be helping her. Lanterns were shown to signal recognition; they were ignored. Whether Landais was incompetent, blind in the smoke, panicked, or something darker was argued for years afterward and never settled at the time. What is certain, and what Jones set down in his own hand, is the plain fact: one of the American ships spent the climax of the battle shooting into its own flagship. And it was the ship Jones had been given by France, under the captain the concordat had made his equal instead of his subordinate, doing the killing, the bad bargain of August coming due in iron.' },
      { p: 'By about ten o\'clock the Bonhomme Richard was, by any reasonable judgment, lost. She was holed below the waterline and flooding, on fire and the flames working toward the magazine where the powder was stored, her pumps failing. Three of her warrant officers (the specialist petty officers who ran the guns, the rigging, and the hull), the gunner among them, decided she was sinking and that the only sane thing left was to surrender. The gunner ran aft to haul down the flag and found the flagstaff already shot away, so he began shouting for quarter instead. To ask for quarter is to ask the enemy to stop killing you and accept your surrender; to strike the colors, to haul down your own flag, is the formal signal of it, the universal language of a beaten ship. So consider the position from the cliffs, where the watchers could read it as plainly as the men aboard: the American\'s flag was gone, her gunner was bawling surrender across the water, she was visibly afire and settling, her own consort had just hulled her, and the heavier ship was lashed to her side firing through her hull. By every sign that a sailor or a spectator could see, the Richard was a beaten ship. Pearson hailed to ask whether the American had struck. What Jones said back, and what he did not say, is the most argued-over moment of the whole Revolution at sea, and it gets its own telling in a moment. The short version is that he refused, drove his own men back to their guns, and the battle went on.' },
      { p: 'Because the thing the dying Richard still had was her three remaining quarterdeck guns and Jones\'s refusal to stop. He had concentrated those guns on the Serapis\'s mainmast, firing double-headed shot (two iron balls joined by a short bar, which spun through the air and cut through mast and rigging) to bring it down. And on the British ship the picture was no better than on the American one. The grenade explosion had wrecked her lower gun deck; her upper deck was a killing ground swept by the Richard\'s marksmen; her mainmast was shaking and ready to fall; and the Alliance was loose and untouchable while Pearson was lashed to the one enemy he could not escape. About half past ten, Richard Pearson struck his own colors, in person. By the accounts that come down to us he had nailed the ensign to its staff before the battle so it could not be hauled down in a panic, and so had to tear it free himself. Jones\'s first lieutenant, Richard Dale (American), led the party that boarded and took possession of the Serapis. Moments after Pearson left her deck, his mainmast went overboard. Beyond the locked pair, in the dark, the second fight had already ended: the French Pallas had taken the Countess of Scarborough after about an hour. Jones had won. His own ship was sinking under him as he stood on the deck of the one he had captured.' },
      { pill: '/war-revolution/battles/trenton', plabel: 'Trenton, 1776: the other time a beaten-looking attack stunned the enemy' },
      { p: 'She could not be saved. The Richard\'s rudder was shot away, her transoms (the structural timbers across the stern) torn out, her old timbers, in Jones\'s words, "mangled beyond my power of description." His wounded and his crew were moved across to the Serapis through the next day while men pumped to keep her afloat, and on the morning of September 25, two days after the battle, "it Was impossible to prevent the good old Ship from Sinking… a little after ten, I Saw With inexpressible grief the last glimpse of the B. H. R. No Lives were lost With the Ship," and the Bonhomme Richard went down somewhere off Flamborough Head, where her wreck has never been found. Jones shifted his flag to the captured Serapis and, with his squadron and some five hundred prisoners, ran east across the North Sea for neutral Holland.' },
    ],
    meanwhile: { region: 'Beyond the locked ships', title: 'The forgotten second fight', body: 'While the Richard and the Serapis hammered each other at the center, a second battle was going on in the dark a little way off. The French Pallas, under Denis-Nicolas Cottineau, had closed with the convoy\'s smaller escort, the twenty-gun Countess of Scarborough under Thomas Piercy, and fought her for about an hour before the outgunned British ship struck. It was a clean, competent little action, and it is almost completely forgotten, swallowed whole by the legend taking shape a few hundred yards away.' },
  },

  'the-most-famous-sentence': {
    eyebrow: 'Bonhomme Richard · The legend',
    title: 'The most famous sentence he never wrote',
    blocks: [
      { p: 'Every American schoolchild learns that when the British captain hailed to ask whether the Bonhomme Richard had surrendered, John Paul Jones (American) roared back: "I have not yet begun to fight!" It is one of the most famous sentences in American history. It may also be the best small lesson the Revolution has to offer in how a legend is built, because the documents tell a more interesting story than the slogan does.' },
      { p: 'Start with what Jones himself wrote, ten days after the battle, in his official report to Benjamin Franklin, the only account of the moment in his own hand from that same season. He does not quote himself at all. He writes that the English commodore "asked me if I demanded quarters, and I having answered him in the most determined negative," the battle was renewed harder than before. That is the bedrock. The defiance is real and documented: Jones was asked to surrender and refused flatly, and the fight went on. The words "in the most determined negative" are what he actually set down. What he answered "in the most determined negative" was, he never recorded.' },
      { p: 'The contemporary echoes of the moment are saltier than the official report and nothing like the famous line. Within weeks, British newspapers were printing secondhand versions from escaped prisoners and informants. The Edinburgh Advertiser, on October 12, 1779, gave the earliest and best of them: Jones, it reported, had answered that "I may sink, but I\'ll be damned if I strike." That is probably the closest thing we have to the spirit of what was actually shouted across that water, printed within three weeks of the battle, and it is not the sentence on the monuments. A London paper carried another version, in which Jones said "I have not as yet thought of it, but am determined to make you strike." Jones\'s own memoir, written in the mid-1780s, has him remembering saying something different again: "I haven\'t as yet thought of surrendering, but I am determined to make you ask for quarter." Four early sources, four different lines, and not one of them is the famous one.' },
      { p: 'The famous one appears in 1825. Forty-six years after the battle, and thirty-three years after Jones himself had died, his old first lieutenant Richard Dale (American), by then an old man, gave his recollections to a biographer named John Henry Sherburne. In Dale\'s telling, Pearson hailed "Has your ship struck?" and Jones answered "I have not yet begun to fight!" Dale was a real witness; he had stood with Jones at points in the action. But his station that night was the gun deck, not at his captain\'s elbow for every word, and he was supplying a half-century-old memory to a biographer, with Jones long dead and unable to confirm or deny anything. So the line is real in one sense: a man who was there said Jones said it, and wrote it down. It is not real in the sense most people imagine, a thing recorded as it was spoken. The refusal is documented in Jones\'s own hand. The sentence is a legend built, beautifully, around a true act, and set down by an old man half a century later. That is the honest way to carry it, and it is a better story than the bare quote.' },
      { p: '…answered him in the most determined negative…', q: true },
      { p: 'The same caution belongs to the surrender ceremony that the legend loves to stage. The story goes that Pearson, handing over his sword, said it was painful to deliver it to a man who had fought "with a halter around his neck," meaning to a pirate who could expect a hanging, and that Jones gallantly returned the sword and told him his king would surely reward him. None of that is in either captain\'s report. It comes from memoirs and biographies written long after, and while the formal surrender certainly happened, the script is later invention. The halter image is the one piece of it that is independently true, not as something Pearson said but as a fact about Jones\'s legal standing: Britain really did regard him as a pirate, and the caricatures prove the reputation. There is one more legend-kit line, just as cherished and just as unsourced. On hearing that Pearson had been knighted for the battle, Jones is said to have remarked that if he ever met the man again, "I\'ll make a lord of him." Universally quoted, never contemporaneously recorded. The story goes that he said it. Whether he did, nobody can show.' },
      { p: 'Richard Pearson (British) lost his ship, and he had done the one thing his orders required: he saved his convoy, the strategic prize, by putting his frigate between it and the raider. The Royal Navy court-martialed him, as it automatically did any captain who lost his ship, and acquitted him with honor in March 1780. He was knighted. He was given the freedom of four towns and presented with silver plate by the Russia Company and by the convoy\'s own insurers, the most honest reward of all, since the insurers were thanking the man whose fight had kept them from paying out on forty lost ships. The Royal Navy thought enough of the name to launch a new Serapis in 1782. Pearson lost the battle and won everything that his actual mission was for.' },
      { pill: '/war-revolution/battles/saratoga', plabel: 'Saratoga, 1777: the victory two years earlier that had already brought France in' },
      { p: 'So what did this night change? Not the war at sea, in any material way. Pearson\'s convoy got home. The naval stores reached the dockyards. The Royal Navy still owned the ocean the next morning, and the war\'s truly decisive naval battle, off the Chesapeake Capes in 1781, would be fought and won by the French fleet, not by John Paul Jones. What Flamborough Head changed was the story. The squadron limped into the Texel, a sheltered anchorage on the Dutch coast where neutral Dutch territory gave it cover from the British fleet waiting outside, on October 3, flying the captured Serapis, and set off a diplomatic crisis: the British ambassador demanded the ships and prisoners back, calling Jones a "pirate" sailing under no recognized flag, while crowds in Amsterdam treated him as a celebrity and the Dutch authorities stalled until he could slip back out to sea in December. In Paris, Benjamin Franklin now had a piece of raw propaganda, a British warship beaten on England\'s own coast, to retail at the French court, and he used it. Paris lionized Jones through 1780. Louis XVI gave him a gold-hilted sword and a French order of merit, the sculptor Houdon made his bust, and Congress eventually voted him its gold medal, the only Continental Navy officer ever so honored. For a cause whose largest naval expedition of the very same season had destroyed itself without a battle, a captured Royal Navy frigate was beyond price as theater.' },
      { fig: '/war-img/rev-bonhomme-richard-jones-paris.jpg', cap: 'Jones engraved in Paris in 1780, drawn from life at the height of the lionization that followed Flamborough Head. The portrait is itself a piece of the propaganda victory: a beaten British frigate on its own coast made the Scottish-born raider the most fashionable American in France.', credit: 'Moreau le Jeune · engraving · 1780 · Wikimedia Commons · public domain' },
      { p: 'The man himself never fought another battle like it. Jones was feted in Paris, served briefly and unhappily as a rear admiral in Catherine the Great\'s Russian navy against the Turks, an appointment that fell apart in an unresolved accusation of assaulting a young girl and in court intrigue, both on the record and neither ever settled, and died alone in Paris in 1792, aged forty-five. He was buried in a Paris cemetery for foreign Protestants, and his grave was lost. More than a century later an American ambassador spent six years searching for it, found his lead coffin in 1905 with the body preserved in alcohol, and in 1913 Jones was entombed in a marble crypt beneath the chapel of the U.S. Naval Academy at Annapolis, where a midshipman honor guard stands over him to this day. The navy that barely existed while he lived made him its founding saint after he died. The legend got the last word, which is exactly what legends do.' },
      { fig: '/war-img/rev-bonhomme-richard-crypt.jpg', cap: 'The crypt beneath the chapel of the U.S. Naval Academy at Annapolis, where Jones was finally entombed in 1913. He had died alone in Paris in 1792 and his grave was lost for over a century; an American ambassador found his lead coffin in 1905. The navy that barely existed while he lived made him its founding saint after his death.', credit: 'Historic American Buildings Survey · Library of Congress · public domain' },
    ],
    meanwhile: { region: 'The Texel, Holland', title: 'The pirate who would not be handed over', body: 'When Jones brought his shattered squadron into the neutral Dutch roadstead of the Texel in October, Britain demanded he be turned over as a pirate flying no lawful flag. The Dutch, not eager to fight Britain over him but not eager to oblige her either, stalled for weeks while Amsterdam sang about its visiting American hero. The legal fix was a fiction: the captured Serapis was handed to France, the French ships called French, and Jones eventually slipped out through the blockade in late December to reach a French port. The affair was one of the irritants that helped push Britain and the Dutch into open war the next year.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={BONHOMME_RICHARD_NARR}
    id={id}
    slug="bonhomme-richard"
    battleName="Bonhomme Richard vs. Serapis"
    date="September 23, 1779"
    theatreId="rev-battles"
    battleId="rev-bonhomme-richard"
    theatreHref="/war-revolution/battles"
    accent="var(--rev-battles)"
    endHref="/war-revolution?theatre=rev-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
