// Opus AUTHOR draft of Kant's *Groundwork of the Metaphysics of Morals* (1785) WORK read
// (philosophy pipeline, kind = WORK). Written ONLY from audits/philosophy-pipeline/
// _idealism-author-brief.md, the verified Abbott quotes in kant-fact-pack.md / kant-ledger.md,
// and creation-time string-matching against the public-domain T. K. Abbott translation
// (Project Gutenberg #5682). Fact ledger: groundwork-work-fact-ledger.md (0 open [VERIFY]).
//
// This read goes DEEPER than the Kant thinker read (src .../kant.read.ts, ch5) and must not
// restate it. The thinker read summarizes the formulas + postulates at thinker altitude; this
// WORK read walks the BOOK's argument architecture: the good will → acting from duty vs merely
// in accordance with duty (the shopkeeper) → the two kinds of imperative → the Formula of
// Universal Law and the Formula of Humanity worked on ONE case (the lying promise) → the
// kingdom of ends and autonomy → the freedom/moral-law reciprocity turn of Section III →
// reception and afterlife (rigorism, empty-formalism, the rights legacy).
//
// Quote doctrine: every quoted line is verbatim Abbott (1879), PD, named each time. The
// "starry heavens / moral law within" line belongs to the *Critique of Practical Reason*, NOT
// the *Groundwork*, and is NOT quoted here. The Beck "above me / within me" wording is never
// used. Where wording is uncertain the point is paraphrased in plain prose, never quoted.

import type { PhiNarr } from '@/components/philosophy-reader'

export const GROUNDWORK: PhiNarr = {
  "title": "Kant's Groundwork of the Metaphysics of Morals",
  "throughline": "Kant set out to find the single supreme principle of right and wrong, and he refused to look for it where everyone else had looked: in consequences, in what makes people happy, in feeling, in God's command, in custom. None of those could yield a law that binds absolutely, because all of them are accidents that vary from person to person and place to place. So he went looking, by pure reason, for the one principle every rational being would have to legislate for itself. He found it by stripping morality down. First the only thing good without any qualification at all, a good will. Then the difference between doing the right thing because it is right and merely happening to do it because it pays. Then the one kind of command that could carry moral force, a command with no hidden 'if' in it, a categorical imperative. From that bare form he derived the famous test: act only on a rule that could be willed as a universal law; and a second formulation that has done as much good as anything in philosophy: never treat a person merely as a means. Behind both stands his deepest idea, autonomy, a rational will giving itself the law rather than taking it from outside, which is why the moral law and freedom turn out to be the same discovery seen from two sides. The book is short, dense, and severe, and it founded the rights-based ethics the modern world still runs on.",
  "hero": {
    "fig": "https://upload.wikimedia.org/wikipedia/commons/4/43/Immanuel_Kant_-_Gemaelde_1.jpg",
    "cap": "Immanuel Kant, portrait attributed to Johann Gottlieb Becker, 1768. No photographs of Kant exist; every likeness of him is a painting. He published the *Groundwork of the Metaphysics of Morals* in 1785, between the two editions of his great theory of knowledge and three years before the *Critique of Practical Reason*.",
    "alt": "Painted bust-length portrait of Immanuel Kant in a powdered wig and grey coat",
    "portrait": true
  },
  "hook": [
    "The *Groundwork of the Metaphysics of Morals* is a small book with an enormous aim. In about a hundred pages, published in 1785, [Kant](/philosophy/thinker/kant) tries to do for ethics what he had just tried to do for knowledge in the [Critique of Pure Reason](/philosophy/work/cpr): find the bedrock, the one principle underneath everything, and show that it comes from reason itself and not from the shifting facts of human life. It is not one of his three Critiques. It is the foundation he laid before building the second one, and it is the most influential thing he ever wrote about how to live.",
    "Its ambition is almost reckless. Every ethics before Kant had grounded right and wrong in something: in happiness, in the will of God, in what a wise person feels, in the customs of a people, in the long-run consequences of acting one way rather than another. Kant throws all of it out at the start. None of those, he argues, can give morality the one thing it must have to be morality at all: an absolute, unconditional grip, the same for every rational being anywhere, binding whether or not it makes anyone happy and whether or not anyone feels like obeying. A law that strong cannot rest on anything as local and accidental as desire or upbringing. It has to come from pure reason, worked out in advance of all experience.",
    "So the book is a search for that one principle, conducted by subtraction. Kant keeps asking what is left when the accidental parts are stripped away, and following the answer down. Remove every good thing that can be misused: a good will remains. Remove the inclination that happened to accompany a morally worthy act: only the doing-from-duty remains. Remove every goal a command might serve: the bare demand that the rule hold for everyone remains. Each subtraction takes him one floor lower, until he reaches the thing he was looking for.",
    "What he reaches is the categorical imperative, and the two formulations of it that everyone since has had to argue with: act only on a rule that could be willed to hold for everyone, and treat humanity always as an end and never merely as a means. The first is a logic test for moral rules. The second is the seed of the modern idea of human dignity. The book is hard going, written in the dry technical German of a professor who distrusted eloquence, and it repays every difficult page, because the ideas in it are still the strongest competitor to the view that morality is just about producing good outcomes."
  ],
  "brk": {
    "beforeLabel": "Morality is grounded in something out in the world: the happiness it produces, the commands of God, the wisdom of custom",
    "afterLabel": "Morality is grounded in pure reason and the rational will itself, binding absolutely, before any consequence",
    "paragraphs": [
      "Almost every ethics before Kant pointed outward for its foundation. The ancient schools located the good in happiness or flourishing and asked which life best secured it. Religious ethics located it in the will of God, made known by command and scripture. The British tradition closest to Kant's own time located it in pleasure and pain and in the natural sympathy people feel for one another, the line that would harden into utilitarianism: the right act is the one that produces the most good for the most people. Different as these are, they share a shape. The standard of right and wrong is some fact about the world, and the moral law is true because it tracks that fact.",
      "That shape is the natural one, and it has real force. A rule against cruelty seems to matter precisely because cruelty produces suffering; a rule of honesty seems to matter because trust makes life go better. Tying morality to consequences supplies an answer to the child's question of why be good: because of what follows. The utilitarian version is the cleanest case. Add up the happiness an action produces, subtract the misery, and the arithmetic delivers the verdict. Morality becomes, at least in principle, something calculable.",
      "Kant's break is to deny that any of this can ground morality, because all of it makes the moral law conditional. If honesty is binding only because it produces trust, then honesty stops binding the moment a lie would produce more. If the moral law is true because it tracks happiness, it is hostage to the facts about what happens to make people happy, and those facts are a mess of accident and appetite. A law that holds only when the consequences cooperate is not a moral law at all in Kant's sense; it is a piece of prudent advice. Real obligation, the kind that forbids betraying a friend even when betrayal would pay, cannot be read off any outcome.",
      "So Kant moves the foundation inward and upward, from the world to reason. The supreme principle of morality, he argues, cannot come from experience at all, because experience only ever tells us what people do, never what they ought to do, and it never delivers the unconditional. It has to be found a priori, by reason reflecting on what it would take to be a law for any rational will whatever. This is the same move he made about knowledge, where the mind supplies the structure rather than copying it from outside. Pointed at ethics, it produces a morality that owes nothing to consequences and everything to the form of rational willing, and a permanent rival to every outcome-based account of right and wrong."
    ]
  },
  "chapters": [
    {
      "num": 1,
      "title": "The supreme principle, sought by reason",
      "epigraph": {
        "text": "\"The categorical imperative would be that which represented an action as necessary of itself without reference to another end, i.e., as objectively necessary.\"",
        "attribution": "— Immanuel Kant, *Groundwork of the Metaphysics of Morals*, Second Section (1785), trans. T. K. Abbott"
      },
      "blocks": [
        {
          "p": "The *Groundwork* states its own job on the title page: to seek out and establish the supreme principle of morality. Not to recommend a way of life, not to settle particular cases, but to find the one principle from which all genuine duties flow, the way the axioms of geometry stand under every theorem. Kant thought ordinary people already knew right from wrong perfectly well, better, often, than philosophers. What was missing was the foundation, the account of *why* the moral law binds and *where* its authority comes from. Supply that, and ordinary moral knowledge is protected from the clever arguments that try to explain it away."
        },
        {
          "p": "His first and most consequential decision is about *where* to look. The foundation, he insists, cannot be found in experience. Watching what people do, what makes them happy, what societies reward, will never yield a moral law, because all experience can report is what *is*, and morality is about what *ought* to be, which no amount of fact ever adds up to. Worse, anything drawn from experience is contingent: it could have been otherwise, it varies from person to person, it is hostage to circumstance. A principle binding *absolutely*, on *every* rational being, cannot rest on the accident of how human beings happen to feel. It has to be established *a priori*, the technical term for what reason knows in advance of and independently of experience. So Kant goes looking for the principle of morality the way a mathematician goes looking for a proof: in pure thought, not in the field."
        },
        {
          "p": "The pressure on consequence-grounded morality becomes clear as soon as the logic is followed through. Take a rule against lying that holds only because lies erode trust and damage society. That rule is really a prediction, and predictions have exceptions. The moment a particular lie would *improve* matters, the rule that was only ever a means to good outcomes has no grip left; it has done its job and stepped aside. Kant's claim is that this is the wrong shape entirely for a *duty*. When honesty is genuinely a duty, it is not the case that it lapses the instant dishonesty would pay better. Something in moral obligation refuses to be cashed out as a forecast about results. That something is what the rest of the book is built to capture."
        },
        {
          "p": "The book is short and tightly built, three sections that descend and then return. The First Section starts from ordinary moral thinking and digs down to a first principle. The Second Section rebuilds that principle rigorously, as the categorical imperative, and gives its formulations. The Third Section asks the hardest question of all: what entitles reason to think this law actually binds us, and the answer turns on freedom. The whole structure is a search narrowing to a point and then asking whether the point holds. The chapters here follow that descent: the good will, then duty, then the two imperatives, then the formulations worked on a single case, then freedom and autonomy, then a final reckoning with the objections the book has been collecting for two centuries."
        }
      ]
    },
    {
      "num": 2,
      "title": "The good will, and the difference duty makes",
      "epigraph": {
        "text": "\"Nothing can possibly be conceived in the world, or even out of it, which can be called good, without qualification, except a good will.\"",
        "attribution": "— Immanuel Kant, *Groundwork of the Metaphysics of Morals*, First Section (1785), trans. T. K. Abbott"
      },
      "blocks": [
        {
          "p": "Kant opens the argument with the most famous sentence in the book, and it is a sweeping one. In Abbott's translation: *\"Nothing can possibly be conceived in the world, or even out of it, which can be called good, without qualification, except a good will.\"* The phrase doing all the work is *without qualification*. Plenty of things are good, but conditionally, good in the right hands and bad in the wrong ones. Intelligence is good, except in a brilliant swindler, where it only makes him more dangerous. Courage is good, except in a ruthless man, where it makes him worse. Wealth, health, even happiness can corrupt the person who has them. Every ordinary good can be put to evil use, which means none of them is good *in itself*. The only thing that stays good no matter what surrounds it, that cannot be turned to evil, is a will that aims at what is right because it is right."
        },
        {
          "p": "What makes a good will good, Kant argues, is not what it manages to accomplish. A good will that, through bad luck and no fault of its own, achieves nothing at all would still, he says, shine like a jewel for its own sake. This is the first and hardest break with consequence-thinking, stated right at the start. The moral worth of a person's willing is sealed off from results, from talent, from luck, from everything outside the will itself. A surgeon who tries with all his skill to save a patient and fails has done something morally as worthy as the one who succeeds, because the moral worth lay in the willing, not in the outcome the world allowed."
        },
        {
          "p": "From the good will Kant extracts the book's pivotal distinction, the one that separates his ethics from every account that judges by behavior alone: the difference between acting *from duty* and merely acting *in accordance with* duty. The two look identical from outside. A man does the right thing in both cases. But only one has moral worth, and the difference is the motive. To act *from duty* is to do the right thing *because* it is right, out of respect for the moral law. To act merely *in accordance with* duty is to do the same right thing for some other reason: because it happens to suit one's interest, or because one simply felt like it. Kant's stark definition: *\"Duty is the necessity of acting from respect for the law.\"* The deed is the same; the worth is not."
        },
        {
          "p": "His own worked example is a shopkeeper, and it is sharper than it first looks. In Abbott's words: *\"it is always a matter of duty that a dealer should not over charge an inexperienced purchaser; and wherever there is much commerce the prudent tradesman does not overcharge, but keeps a fixed price for everyone, so that a child buys of him as well as any other.\"* So a child can shop at this merchant's store and be charged the honest price, exactly as an adult would be. The behavior is impeccable. But Kant presses on the *why*. The prudent tradesman keeps honest prices because honesty is good for business, because cheating customers would ruin his reputation and his trade. He is honest, but he is honest *for profit*. And so, Kant concludes, *\"the action was done neither from duty nor from direct inclination, but merely with a selfish view.\"* The honest-for-profit shopkeeper does the right thing and earns no moral credit for it, because had cheating paid better, he would have cheated. His honesty tracks his advantage, not the law."
        },
        {
          "p": "Stated plainly, Kant's claim is that morality lives in *why* a person acts, not in *what* they do or *how it turns out*. Two people can perform the identical honest act, and only the one who does it because it is right has done something of moral worth; the one who does it because it pays has merely been lucky that doing right and doing well lined up. This is austere, and it has always drawn the same complaint, that it seems to value cold dutiful action over warm spontaneous kindness, even to suspect the person who *enjoys* being good. The steelman of Kant's position is this: he is not saying it is bad to enjoy doing good, he is saying that the enjoyment is not what *makes* it good. Whether a kind act is moral rather than merely pleasant is settled by whether it would survive the removal of the pleasure. The will that does right when inclination falls away is the only will whose goodness can be relied on, and reliability is the whole point of a moral law."
        }
      ]
    },
    {
      "num": 3,
      "title": "Two kinds of command",
      "epigraph": {
        "text": "\"All imperatives command either hypothetically or categorically.\"",
        "attribution": "— Immanuel Kant, *Groundwork of the Metaphysics of Morals*, Second Section (1785), trans. T. K. Abbott"
      },
      "blocks": [
        {
          "p": "Having found that moral worth lies in acting from the law, Kant has to say what kind of thing that law could be. His tool is a distinction between two kinds of command, two kinds of *ought*. *\"All imperatives command either hypothetically or categorically.\"* The difference is whether the command has an *if* hidden inside it. The distinction is not subtle once it is in view; it runs under every demand anyone makes on anyone."
        },
        {
          "p": "A **hypothetical imperative** is a command with an *if*: it prescribes an action *in order to* secure some other end that is wanted. \"A person who wants to be healthy ought to exercise.\" \"A person who wants to be trusted ought to keep promises.\" Kant's exact phrasing for the type: such an imperative \"represent[s] the practical necessity of a possible action as means to something else that is willed.\" These commands hold only as long as the underlying desire holds. Remove the desire and the command evaporates, because it was never about the action for its own sake, only about the action as a road to the thing wanted. A man who stops wanting to be trusted is, by a hypothetical imperative, released from keeping his word. The command was always conditional on a want."
        },
        {
          "p": "A **categorical imperative** is a command with no *if* at all. In Abbott's words it is the one \"that represented an action as necessary of itself without reference to another end, i.e., as objectively necessary.\" It does not say do this *in order to* get that. It says: do this, full stop. It binds regardless of what a person happens to want, even against everything desired. \"Do not betray a trust\" is not shorthand for \"do not betray a trust *if* a society where trust survives is preferred.\" It commands flat, unconditionally. Kant's argument is that *this* is the only shape a moral command can have, because a moral command that lapsed the moment its goal stopped being cared about would be exactly the prudent advice he ruled out in the First Section. Morality, if it exists, speaks categorically or not at all."
        },
        {
          "p": "Kant gives the test in a single line: *\"If the action is good only as a means to something else, then the imperative is hypothetical; if it is conceived as good in itself … then it is categorical.\"* That sentence sets up the central problem of the book. Hypothetical imperatives are easy to justify, because the goal supplies the reason: exercise is commanded *by* the wanting of health. But a categorical imperative has no goal behind it to supply a reason, no *if* to lean on. With every particular purpose stripped out, what content is left for the command to have? Kant's answer to that question, in the next chapter, is the famous one, and it is more elegant than the problem makes it look."
        }
      ]
    },
    {
      "num": 4,
      "title": "The one law, in two formulas",
      "epigraph": {
        "text": "\"There is therefore but one categorical imperative, namely, this: Act only on that maxim whereby thou canst at the same time will that it should become a universal law.\"",
        "attribution": "— Immanuel Kant, *Groundwork of the Metaphysics of Morals*, Second Section (1785), trans. T. K. Abbott"
      },
      "blocks": [
        {
          "p": "Here is Kant's elegant trick. Strip every *if* and every particular goal out of a command, and what is left is only the bare *form* of a law: the property of being a rule that holds for everyone, without exception. So the supreme principle of morality can only be the command to act in a way that *could* be a universal law. That is the **Formula of Universal Law**, the first and most famous statement of the categorical imperative, in Abbott's wording: *\"There is therefore but one categorical imperative, namely, this: Act only on that maxim whereby thou canst at the same time will that it should become a universal law.\"* A *maxim* is the personal rule behind an action, stated honestly: the principle actually being acted on in doing it. The test is whether that rule could be willed to hold for *everyone* always, as if it were a law of nature, without the rule wrecking itself."
        },
        {
          "p": "Kant's own test case is the **lying promise**. A man is desperate for money. He can get it only by borrowing, and he knows he will never be able to repay. He is tempted to *promise* repayment anyway, a promise he knows is false, because only a promise will get him the loan. The test proceeds in three moves. First, state the maxim honestly: \"When I need money and cannot get it otherwise, I will promise to repay, knowing I will not.\" Second, universalize it: every person in that situation acts on the same rule, always. Third, try to will that world, and the willing collapses. In a world where everyone makes promises they intend to break whenever convenient, no one believes promises anymore, and a promise no one believes is not a promise, it is noise. The institution of promising stops existing."
        },
        {
          "p": "And that is the contradiction. The man's scheme *requires* the institution of promising, because he needs the lender to believe him; but universalizing his maxim *destroys* the institution of promising. So he cannot even coherently will his rule as a universal law, the willing eats itself. Kant states the result twice in the text. First the test fails on the maxim: *\"Then I presently become aware that while I can will the lie, I can by no means will that lying should be a universal law.\"* Then the verdict on the maxim itself: *\"Hence my maxim, as soon as it should be made a universal law, would necessarily destroy itself.\"* The wrongness is not that a world of liars would be unpleasant. That would be a consequence argument, the kind Kant refuses. The wrongness is that the maxim is *logically self-cancelling*, like a round square. It can be acted on by one person hiding in the crowd, but it cannot be thought as a law for all, and that, for Kant, is precisely what makes it immoral. The categorical imperative is a logic test, not a cost-benefit sum, which is why it can claim the iron necessity of arithmetic."
        },
        {
          "p": "Kant insists there is really only one moral law, but he gives it more than one formulation and says they come to the same thing. The second has done more good in the world than any other sentence he wrote: the **Formula of Humanity**. In Abbott's translation: *\"So act as to treat humanity, whether in thine own person or in that of any other, in every case as an end withal, never as means only.\"* To treat someone *merely as a means* is to use them as a tool for one's own purposes, running them through one's plans with no regard for theirs, the way a hammer is used. To treat them *as an end* is to recognize that they have their own purposes and their own rational will, that they are not simply instruments for another's use. The decisive word is *merely*. Kant is not banning all use of other people. A passenger uses the bus driver as a means of crossing town, and that is fine, because the driver has agreed and remains a free agent pursuing his own ends, a wage, a living. The violation is using a person *only* as a means, overriding their will entirely."
        },
        {
          "p": "Run the same lying-promise case through the second formula, and it fails for a deeper-sounding reason than under the first. When the desperate man extracts a loan by a false promise, he is using the lender as a mere tool. The lender agrees to the loan, but he agrees on false information the borrower deliberately supplied; he cannot share in the borrower's actual end, because that end was kept hidden from him precisely so he would cooperate. A person deceived into serving someone else's scheme has not really consented; he has been steered, like an object, toward a purpose he was never allowed to see and could not have endorsed. The slaveholder and the con artist are the pure cases: both treat people as things to be owned or manipulated, their wills overridden. The lying promise is the same wrong in miniature. This is the formula that stands behind the modern language of human dignity and human rights, the idea that there is something in every person that may never be traded away for someone else's convenience."
        },
        {
          "p": "The second formula is not the Golden Rule, and Kant stops the book to say so, in a footnote, because the two are easily confused and deeply different. The Golden Rule routes everything through personal desire — do unto others as *one* would wish done to oneself — and people's desires are strange and selfish. Kant labels the maxim a mere *\"common\"* rule, only a rough derivative of the categorical imperative, and lists what it cannot do: *\"it cannot be a universal law, for it does not contain the principle of duties to oneself, nor of the duties of benevolence to others (for many a one would gladly consent that others should not benefit him, provided only that he might be excused from showing benevolence to them).\"* The cold misanthrope who genuinely wants nothing from anyone could, by the Golden Rule, leave everyone to suffer, since he is content to suffer un-helped himself. His preference sets the standard, and his preference is poison. The categorical imperative strips preference out entirely. It asks not what any particular person wants, but what any rational being could will as a law for all."
        }
      ]
    },
    {
      "num": 5,
      "title": "Autonomy, and why the law needs freedom",
      "epigraph": {
        "text": "\"Autonomy of the will is that property of it by which it is a law to itself.\"",
        "attribution": "— Immanuel Kant, *Groundwork of the Metaphysics of Morals*, Second Section (1785), trans. T. K. Abbott"
      },
      "blocks": [
        {
          "p": "Behind both formulas stands the idea Kant prized above all the others: **autonomy**, from the Greek *autos*, self, and *nomos*, law. Self-law-giving. The claim is radical. When a person obeys the moral law, Kant says, they are not obeying anything outside themselves, not God, not the state, not society, not their own appetites. They are obeying a law that they, as a rational being, give to themselves. Reason legislates the moral law, and the rational agent is reason's own legislature. In Abbott's words: *\"Autonomy of the will is that property of it by which it is a law to itself.\"* This is why the moral law can bind absolutely without crushing freedom. It is not a chain locked on a person from outside; it is the law of their own deepest rational nature, the law they would write for themselves if they reasoned cleanly. To be moral, for Kant, is to be self-governing. To be immoral is to be dragged around by whatever desire shouts loudest, which is the opposite of free."
        },
        {
          "p": "Autonomy opens onto the most inspiring image in the book, a third way of stating the one law: the **kingdom of ends**, sometimes rendered the realm of ends. Kant proposes a community of all rational beings in which each one is at once subject to the moral law and a co-author of it. Each makes the law and lives under it; each treats every other as an end and never merely as a means; nobody is used. His own definition: *\"By a kingdom I understand the union of different rational beings in a system by common laws.\"* It is not a state that could be found on a map. It is an ideal against which an agent can measure conduct: whether each act is fit for a worthy law-making member of that community of mutual respect. What the picture reveals is that this grandeur is built entirely out of the cold logic-test the book started from. The severity and the grandeur are the same idea: a world in which every will legislates the same law and no will is treated as a thing."
        },
        {
          "p": "The Third Section is the hardest part of the *Groundwork*, and it asks the question the rest of the book postponed: what entitles anyone to think this law actually *binds* us? A self-given law sounds fine, but a will that gives itself the law must first be *free*, free to legislate rather than merely pushed around by causes like any object in nature. So Kant has to talk about freedom, and he does it carefully, because freedom cannot be proved by observation; everything we observe is caught in the chain of cause and effect. He begins by defining the will as a special kind of causality: *\"The will is a kind of causality belonging to living beings in so far as they are rational, and freedom would be this property of such causality that it can be efficient, independently of foreign causes determining it.\"* A free will is one that can act from itself, not merely as the last domino in a line knocked over by earlier dominoes."
        },
        {
          "p": "Then comes the turn the whole book has been building toward, and it has to be handled exactly, because it is easy to garble. Kant argues that *freedom and the moral law are the same thing seen from two sides*. A will that is free, that is genuinely self-determining and not pushed by foreign causes, must give itself *some* law, since a lawless will would just be randomness, no more free than a dice-throw. And the only law a will can give purely from itself, owing nothing to outside goals, is the categorical imperative, the demand to act on what could be universal. So a free will and a will under the moral law turn out to be one and the same. Kant states it flatly: *\"a free will and a will subject to moral laws are one and the same.\"* Freedom is not the licence to do whatever appetite demands; that is just being ruled by the strongest impulse. Freedom is the capacity to act on the law that reason itself gives, which is the moral law. The two ideas are locked together: take either one seriously and the other comes with it."
        },
        {
          "p": "That leaves Kant with a delicate last problem, and he is honest about it. He cannot *prove* that we are free, because freedom belongs to us as rational agents, not as objects in the observable world, and the observable world is where proof lives. What he argues instead is subtler and, he thinks, exactly enough: that any being who has to act *as if* it were free is, for all practical purposes, bound by the moral law as surely as if freedom had been proven. *\"Every being that cannot act except under the idea of freedom is just for that reason in a practical point of view really free.\"* No one can deliberate, weigh reasons, and decide while sincerely believing oneself to be merely a falling domino; the very act of choosing presupposes that the choice is the agent's own. And a being that must regard itself as free must, by the reciprocity just shown, regard itself as under the moral law. Kant does not claim to have shown *how* freedom is possible. He says outright that human reason will never fully explain that. He claims only to have shown that a rational agent cannot coherently think of itself as anything other than free, and so cannot escape the law that freedom carries with it."
        }
      ]
    },
    {
      "num": 6,
      "title": "Reception, objections, and the long afterlife",
      "epigraph": {
        "text": "\"So act as to treat humanity, whether in thine own person or in that of any other, in every case as an end withal, never as means only.\"",
        "attribution": "— Immanuel Kant, *Groundwork of the Metaphysics of Morals*, Second Section (1785), trans. T. K. Abbott"
      },
      "blocks": [
        {
          "p": "The *Groundwork* did exactly what Kant built it to do: it founded a whole approach to ethics, now called *deontology*, from the Greek for the study of duty, the view that some acts are right or wrong in themselves, by their conformity to moral law, regardless of consequences. It is the permanent rival to the consequence-based ethics that runs the other way. The cleanest contrast is with the utilitarianism of [Hume](/philosophy/thinker/hume)'s heirs, sharpened a generation later by John Stuart Mill, which holds that the right act is simply the one that produces the most overall happiness. For the utilitarian, a lie that saves lives is not merely permitted but required; the consequences settle it. For Kant, the lie is forbidden by a law that the arithmetic of consequences has no power to overturn. Two centuries of moral philosophy have largely been an argument between these two camps, and the *Groundwork* is the founding document of one of them."
        },
        {
          "p": "The objections came fast, and they cluster around the book's very severity. The most famous is the charge of **rigorism**, that Kant's absolute rules force monstrous conclusions in hard cases. The test case became notorious. In 1797 the Franco-Swiss writer Benjamin Constant pressed Kant on a scenario: a murderer arrives at the door asking where a friend is hiding, intending to kill him. Surely, Constant argued, a lie is permissible. Kant's reply, in a short essay with the unlovely title *On a Supposed Right to Tell Lies from Benevolent Motives*, was that it is not. The duty of truthfulness is unconditional; lying to the murderer at the door is still forbidden. To many readers this looked like a *reductio* of the whole system, a proof that an ethics of absolute rules, blind to consequences, must eventually demand something no decent person could accept. Defenders have argued ever since over whether Kant overstated his own theory in that essay, and whether the categorical imperative really requires the harsh answer; the debate is alive today. But the worry it crystallized, that consequence-blind duty can become cruelty, has shadowed Kantian ethics from the start."
        },
        {
          "p": "The second great objection runs deeper and came from [Hegel](/philosophy/thinker/hegel): the charge of **empty formalism**. The Formula of Universal Law is supposed to sort right maxims from wrong ones by a pure test of consistency, with no appeal to any actual goal. Hegel's complaint was that a purely formal test, with all real content stripped out, cannot actually generate a moral code; it either smuggles in some end it pretends not to use, or it passes too much. Almost any maxim, Hegel argued, can be universalized without strict contradiction when described carefully enough, and the cases where universalizing really does self-destruct, like the lying promise, work only because the institution of promising has been quietly assumed to be something that *ought* to survive. Strip every substantive value out of the test, the objection runs, and the result is a beautiful machine that grinds out nothing. Whether the categorical imperative is genuinely empty or whether its formality is exactly its strength, a test that owes nothing to anyone's particular interests, has been argued ever since, and it remains the central technical dispute about the book."
        },
        {
          "p": "What survived every objection is the Formula of Humanity and the idea underneath it. The thought that every person is an end in themselves, possessed of a dignity that may never be traded away for someone else's benefit, became one of the load-bearing ideas of the modern world. It runs through the language of inalienable rights, through the conviction that there are things that may not be done to a human being no matter how much good would come of it, through the twentieth century's attempts to write that conviction into law after the century had shown what its denial looked like. When a constitution declares human dignity inviolable, it is speaking Kant's sentence in other words. The most demanding moral philosophers of the last hundred years, the builders of rights-based theories of justice, took the *Groundwork* as their starting point, either extending it or arguing with it, which comes to the same kind of tribute."
        },
        {
          "p": "The book also pointed past itself. By grounding morality in the autonomy and freedom of the rational will, Kant handed his successors a problem and a program. If the self that legislates the moral law is the free self behind the world of appearances, then the next question is what that self is, and how its freedom fits a world otherwise ruled by cause and effect. The thinkers who came after him, [Fichte](/philosophy/thinker/fichte) and [Hegel](/philosophy/thinker/hegel) and the movement called *German Idealism*, the view that reality is fundamentally mind-like, structured through and through by the activity of thought rather than a mind-independent lump of matter, took the free self-legislating will Kant had placed at the center of ethics and tried to build a whole picture of reality around it. The little book on duty turned out to be a hinge. It closed one era of moral philosophy, the era that grounded right in consequences and feeling, and opened another, the era that grounds it in reason and freedom, which is the era the modern world still inhabits."
        }
      ]
    }
  ]
}
