'use client'

// First Bull Run — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.
//
// VOICE PASS 2026-06-01 (dossier-retrofit strand 2): brought to the locked
// house-voice rules — no reader-facing em-dashes; marquee names (Lincoln,
// Davis, Lee, Grant) carry no side-tag
// while every other side-affiliated person is tagged once on first mention per
// section; full rank spelled out on first appearance per section; meta-narrator
// / editorial asides removed (tell it plainly); the cause named once, plainly;
// bold emphasis stripped; cross-refs are pills. Facts web-verified.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

export const BULL_RUN_NARR: Record<string, Narr> = {
  'on-to-richmond': {
    eyebrow: 'First Bull Run · The clock that forced the issue',
    title: 'On to Richmond',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -78.8, lonMax: -75.7, latMin: 36.9, latMax: 39.6 },
        states: [
          { name: 'Virginia', tone: 'focus', label: 'VIRGINIA', labelLon: -78.5, labelLat: 38 },
          { name: 'Maryland', label: 'MARYLAND', labelLon: -76.1, labelLat: 38.5, labelSize: 13 },
          { name: 'West Virginia', label: 'WEST VIRGINIA', labelLon: -78.5, labelLat: 39.3, labelSize: 13 },
          { name: 'North Carolina' },
          { name: 'Pennsylvania' },
        ],
        dots: [
          { name: 'Bull Run (Manassas)', date: 'Jul 21, 1861', lat: 38.815, lon: -77.522, heavy: true, anchor: 'middle', dy: 24 },
          { name: 'Washington, D.C.', lat: 38.907, lon: -77.037, color: '#8a8175', anchor: 'middle', dy: -16 },
          { name: 'Richmond', lat: 37.541, lon: -77.434, color: '#8a8175', anchor: 'end' },
        ],
      } },







      { p: 'In the spring of 1861, a remarkable number of Americans believed the war that had just started would be over by autumn, and that they would win it in an afternoon. The Confederate States (the eleven Southern states that had broken away from the United States rather than accept limits on slavery) had fired on Fort Sumter, a U.S. fort in the harbor of Charleston, South Carolina, on April 12 and 13, and President Abraham Lincoln had answered by calling for 75,000 volunteers. Those volunteers signed up for 90-day enlistments, meaning they had promised the army only three months of their lives. That number was a confession of how short everyone expected this to be. Three months was thought to be plenty of time to march south, smash the rebellion in one big battle, and send everyone home before the harvest. Nobody enlists for ninety days if they think they are starting a four-year war.' },
      { pill: '/war-civil-war/naval/fort-sumter', plabel: 'Fort Sumter: the shots that opened the war' },
      { p: 'The two sides were fighting over slavery, the system that held roughly four million human beings as property and on which the Southern economy was built. The Southern states had seceded, formally declared themselves out of the Union, to protect it, and several of those states said so directly in their official declarations of secession. The North did not march out that summer to end slavery; most of the men heading for Virginia would have told you they were fighting to put the Union back together. But the thing the Confederacy had seceded to defend, and the thing the war would ultimately be about, was whether human beings could be owned.' },
      { h: 'The 90-day war', eyebrow: 'A clock that forced the issue' },
      { p: 'The trouble with a 90-day army is that the clock runs out. By the middle of July 1861, those three-month enlistments were starting to expire, which meant the United States was about to watch its only real army melt back into a crowd of civilians without having fought anything. Two Union regiments (a regiment being roughly a thousand men, the basic building block of a Civil War army) had their time run out and literally turned around and marched back to Washington while the battle was beginning. They went home rather than re-enlist for one more day. If there was going to be a quick, war-ending victory, it had to happen now, before the men who were supposed to win it walked off the job.' },
      { p: 'The newspapers were not helping anyone stay calm. Starting June 26, 1861, the New York Tribune, the most influential paper in the country, run by the famous editor Horace Greeley, ran a standing demand at the top of its columns: "Forward to Richmond!", printed day after day like a drumbeat. Richmond, Virginia, was the prize. The Confederacy had moved its capital there from Montgomery, Alabama back in May, which put the rebel seat of government barely 100 miles (160 km) from Washington, close enough to feel like a quick march, and important enough that taking it might end everything. Between Greeley\'s drumbeat, an impatient Congress, and a public certain of victory, the pressure to attack became a wall.' },
      { p: 'You are green, it is true, but they are green also; you are all green alike.', q: true },
      { p: 'The general who would have to do the attacking was Brigadier General Irvin McDowell (North), and he did not want to go. McDowell knew exactly what his army was: a mob of enthusiastic amateurs who had never fought, never marched far, never done any of it. He wanted more time to train them. He was overruled. The famous reply about both armies being equally raw is usually put in Lincoln\'s mouth in popular retellings, but careful scholarship attributes it to General Winfield Scott (North), the aging general-in-chief of the whole U.S. Army, and that is the safer attribution. Whoever said it, the sentiment was true and it did not save McDowell from the consequences. On the march to the battlefield, soldiers broke ranks to pick blackberries and wander off looking for water, because nobody had taught them yet that you do not do that. McDowell\'s plan would require precise, coordinated movements by exactly this army.' },
      { h: 'The spectators', eyebrow: 'A battle as a day out' },
      { p: 'When McDowell\'s army marched out of Washington toward Virginia, it was followed by a crowd. Hundreds of civilians, including United States senators and congressmen with their wives and families, rode out from the capital in carriages, packing picnic baskets and opera glasses, planning to find a good hill and watch the United States win the war the way you would watch a horse race. Senators Zachariah Chandler of Michigan, Ben Wade of Ohio, Henry Wilson of Massachusetts, and James Grimes of Iowa were among them. So was Representative Alfred Ely (North), a congressman from Rochester, New York, who had come out partly to check on a regiment he had helped recruit. They were certain it was going to be a show, and they had front-row seats. Almost none of them grasped that the thing they had come to watch was men killing each other a few hundred yards away.' },
      { h: 'Two armies and one railroad', eyebrow: 'Why Manassas mattered' },
      { p: 'The Confederates had not been waiting passively. They had two armies in northern Virginia, and the whole battle turns on the relationship between them. The first, under Brigadier General P.G.T. Beauregard (South), the hero of Fort Sumter, sat at Manassas Junction, a spot whose entire importance was its railroads. It was where two rail lines crossed: the Orange & Alexandria Railroad and the Manassas Gap Railroad. Whoever held Manassas Junction held the overland gateway to Richmond, which is exactly why Beauregard, with around 21,000 to 22,000 soldiers, was dug in along a winding stream called Bull Run to block McDowell\'s path. The South would call the coming fight First Manassas, after the junction; the North would call it First Bull Run, after the creek. The two sides named battles by different rules all war long, the North after rivers, the South after towns, and the same fight often carries two names because of it.' },
      { p: 'The second Confederate army, around 11,000 to 12,000 soldiers under Brigadier General Joseph E. Johnston (South), was off to the west in the Shenandoah Valley, the long fertile farming valley that runs down the western side of Virginia behind the mountains. Johnston was being watched there by a Union force under Major General Robert Patterson (North), and that watching was the linchpin of McDowell\'s entire plan. The whole scheme only worked if Patterson kept Johnston pinned in the Valley, unable to come help Beauregard. The danger nobody on the Union side had fully reckoned with was that crossing rail line at Manassas. The Manassas Gap Railroad ran from the Valley straight to Beauregard\'s junction. If Johnston ever slipped away from Patterson, those tracks could carry his whole army to the battlefield faster than any army in history had ever moved.' },
      { fig: '/war-img/bull-run-campaign.png', cap: "On to Richmond: McDowell marches south from Washington through Centreville toward Manassas Junction, while Johnston's army slips out of the Shenandoah Valley and rides the railroad east to reach the field in time.", credit: 'Stuff Happened map' },
    ],
    meanwhile: { region: 'Washington', title: 'The socialite who had the plan first', body: 'The most important piece of intelligence in the campaign had already changed hands, and not on any battlefield. A Washington socialite named Rose O\'Neal Greenhow (South), a widow with friends all over the capital\'s political class, was spying for the Confederacy from inside the city. In early July she got word of McDowell\'s intended advance on Manassas and got it to Beauregard. The message went south the colorful way: a young courier named Betty Duvall, dressed as a farm girl, carried it through the lines coiled inside a bun of her own hair. Greenhow sent a second warning on July 16. It was on the strength of her information that the Confederates pressed to bring Johnston\'s army over from the Valley in time. After the war was won, Jefferson Davis is supposed to have told her, in effect, that but for her there would have been no victory at Bull Run. So when the Confederate response that morning looks uncannily well-timed, it was not pure improvisation. The other side had read the Union\'s mail.' },
  },

  'the-flank-march': {
    eyebrow: 'First Bull Run · The plan that nearly won the war',
    title: 'The Flank March',
    blocks: [
      { p: 'Brigadier General Irvin McDowell\'s (North) plan was a good one. On the morning of Sunday, July 21, 1861, he set in motion a scheme that, with one more hour of speed or one more drilled division, might have won the war that summer. It was a smart plan handed to an army that could not yet walk in a straight line.' },
      { p: 'A Civil War army was built in nested layers: a regiment (roughly a thousand men) was the basic unit; a few regiments made a brigade (a few thousand); a few brigades made a division (bigger still). Generals moved these pieces around like a stack of blocks. Two more plain words are worth keeping handy: infantry are soldiers who fight on foot; cavalry are soldiers who fight on horseback. That is the whole vocabulary you need for the day.' },
      { h: 'Morning, July 21', eyebrow: 'A punch and a hook' },
      { p: 'The plan had two parts, the way a good boxing combination does. The first part was a feint, a fake attack meant to grab the enemy\'s attention and hold it in the wrong place. McDowell sent a division under Brigadier General Daniel Tyler (North), one of his division commanders, to make a loud demonstration at the Stone Bridge, where the main east-west road, called the Warrenton Turnpike, crossed Bull Run. Lots of noise, lots of cannon fire, the look of a serious assault, all designed to convince Beauregard that the real blow was coming there, at his right and center.' },
      { p: 'It was not. While Tyler hammered at the Stone Bridge, the bulk of McDowell\'s army, two divisions under Colonel David Hunter (North) and Colonel Samuel Heintzelman (North), two more of his division commanders, was swinging in a wide arc to the north and west to hit the Confederate flank, the exposed end of an army\'s line where it can be rolled up sideways like a rug. To get there they had to cross Bull Run at a ford, a shallow spot where a stream can be waded rather than bridged. The ford they aimed for was Sudley Springs Ford, about 3 miles (4.8 km) north of the Stone Bridge, well past the end of the Confederate line, so the Union flanking column could cross unopposed, then turn south and come crashing down on the rebel left from a direction Beauregard was not watching. Smash the flank, roll up the line, and cut Beauregard off from Manassas Junction behind him. On paper it was beautiful.' },
      { fig: '/war-img/bull-run-morning.png', cap: 'McDowell\'s flank march: while Tyler feinted at the Stone Bridge, Hunter and Heintzelman\'s divisions swung wide north across Sudley Springs Ford to hit the Confederate left.', credit: 'Stuff Happened map' },
      { p: 'The trouble was the marching. Thousands of untrained men were strung out for miles on a narrow back road in the July heat, the column stretching and bunching like an accordion because nobody had drilled them in how to move this far, men falling out to gulp at every stream they passed, officers hoarse from shouting them back into line. The wide hook that was supposed to land at dawn instead dragged on for hours. The lead troops did not splash across Sudley Springs Ford until around 9:30 a.m., somewhere between two and a half and three hours behind schedule, and in those hours the surprise leaked away.' },
      { fig: '/war-img/bull-run-sudley-church.jpg', cap: 'Sudley Church, near the ford where the Union flanking column crossed Bull Run, later pressed into service as a field hospital after the fighting came.', credit: 'Battlefield photograph, March 1862 · public domain' },
      { p: 'The warning came from one sharp-eyed man on the other side. A young Confederate signal officer, Captain Edward Porter Alexander (South), was scanning the country to the north when he caught a glint, sunlight bouncing off the bayonets of a column of men miles off, where no friendly troops should be. He worked out in an instant what it meant: an army was coming around the flank. Using wig-wag signaling, a system of waving flags in coded patterns to send messages across distance, used here in combat for the first time in history, he flashed a warning to the Confederate left: "Look out for your left, your position is turned." The total surprise was gone, but the flank attack was still coming, and it still had the weight to win.' },
      { h: 'Morning, July 21', eyebrow: 'The hour it looked won' },
      { p: 'The Confederate officer holding the threatened left, Colonel Nathan Evans (South), had barely 1,100 men, and he made a fast, smart decision: realizing the Stone Bridge attack was a bluff, he pulled most of his command away from it and rushed them north to Matthews Hill, the high ground sitting directly in the path of the oncoming Union flankers, and planted them there to buy time. Reinforcements scrambled up to help him: the brigades of Brigadier General Barnard Bee (South) and Colonel Francis Bartow (South). For a couple of hours Matthews Hill was a furious, stand-up fight, a handful of outnumbered Confederate brigades trying to hold back the entire weight of McDowell\'s hook.' },
      { p: 'They could not. There were too many Union troops, and worse was coming. Colonel William T. Sherman (North), the same Sherman who would become one of the war\'s most famous generals, found a second, unguarded ford upstream from the Stone Bridge, crossed with his brigade around 10:00 a.m., and slammed into the Confederate right on Matthews Hill, adding his weight to the pile. By around 11:30 in the morning, the Confederate line on Matthews Hill broke. Evans, Bee, and Bartow\'s men streamed back in retreat, southward across the Warrenton Turnpike and up the slope of the next high ground, a plateau called Henry House Hill. To the Union officers watching, and to the picnicking spectators craning through their opera glasses from the hills behind, it looked exactly like what they had all come to see: the rebels running, the Union advancing, the short war ending right on schedule.' },
      { p: 'It looked, for an hour around noon, exactly like the quick triumph everyone had marched out to watch.', q: true },
      { p: 'It was about to come apart.', i: true },
    ],
    meanwhile: { region: 'the Shenandoah Valley', title: 'The railroad as a weapon', body: 'While McDowell\'s hook was still grinding toward Sudley Springs, the gun pointed at his plan was already going off, nearly 60 miles (97 km) to the west. Patterson, the Union general whose one job was to keep Johnston bottled up in the Shenandoah Valley, had failed to do it. He never pressed Johnston hard, and Johnston took full advantage. He screened his departure behind a screen of cavalry under Colonel J.E.B. Stuart (South), riders spread out ahead of the army to keep Union scouts from seeing what was moving, quietly peeled his infantry away, and on July 18 and 19 marched them to Piedmont Station (present-day Delaplane, Virginia) on the Manassas Gap Railroad. There, his soldiers climbed aboard trains. The Manassas Gap Railroad carried Johnston\'s army roughly 34 miles (55 km) east to the battlefield, the first time in history that railroads were used to rush troops to a major battle. Patterson, meanwhile, believed he had Johnston contained, and reported as much to Washington, even as Johnston\'s men were already riding the rails toward Beauregard. The army that was supposed to be stuck in the Valley was, that very morning, stepping off the trains behind the Confederate line.' },
  },

  'stone-wall': {
    eyebrow: 'First Bull Run · The legend born on a hill',
    title: 'There Stands Jackson',
    blocks: [
      { p: 'By midday on July 21, the broken Confederate brigades were streaming back from Matthews Hill in something close to rout, climbing the slope of Henry House Hill with a victorious Union army coming on behind them. The battle had a few hours left to run, and the things that made it famous, the legend, the turn, the rebel yell, and the only civilian death, happened on this one plateau.' },
      { h: 'Henry House Hill', eyebrow: 'A man who would not move' },
      { p: 'The reason the Confederate retreat did not become a collapse was a brigade of Virginians that had not run, because it had not yet fought. Brigadier General Thomas J. Jackson (South) had brought his fresh brigade up near noon and positioned it on the reverse slope of Henry House Hill, the back side of the hill, the side facing away from the enemy, where the crest of the ground itself shielded his men from incoming artillery fire. It was a deliberate piece of tactics: his infantry waited in cover while he set 13 cannon on the crest above them to do the killing. Cavalry under Colonel J.E.B. Stuart (South) and the men of Wade Hampton\'s Legion, a privately raised South Carolina outfit, regiment-sized, mixing infantry, cavalry, and artillery under one wealthy planter, Colonel Wade Hampton (South), guarded his flanks. While the rest of the Confederate left fell apart, Jackson\'s line stood on that hill like a fixed point, unmoving, waiting. Somewhere in the long fire of that afternoon a bullet broke a finger on Jackson\'s left hand; he wrapped it, refused to leave, and kept building the legend while he bled.' },
      { p: 'That is where the most famous sentence of the battle was spoken. Brigadier General Barnard Bee (South), his own brigade shot to pieces and falling back, tried to rally his broken men. He pointed toward the Virginians on the hill and said the line that would name Jackson forever:' },
      { p: 'There stands Jackson like a stone wall! Rally behind the Virginians!', q: true },
      { fig: '/war-img/bull-run-henryhill.png', cap: 'Jackson\'s stand on Henry House Hill: the reverse-slope position that held the Confederate line while the rest of the left fell apart around it.', credit: 'Stuff Happened map' },
      { p: 'Nobody actually knows what Bee meant. The popular reading is pure praise: look how Jackson stands firm, rally on him, be like that. But there is a real and unresolved second reading. One Confederate officer, Major Chase Whiting (South), reported afterward that Jackson had refused to bring his brigade forward to support Bee\'s men while they were being slaughtered, and that Bee spoke the words in fury, not admiration: Jackson just stands there like a stone wall doing nothing while we are cut to pieces. We will never know which it was, because Bee was mortally wounded minutes after he spoke and died the next day, July 22, without ever explaining himself. The praise version became the legend; the rebuke version has serious historians behind it. Either way, the name stuck. From that hill on, he was Stonewall Jackson.' },
      { h: 'Henry House Hill', eyebrow: 'The widow in the house' },
      { p: 'There was a house on the crest of that hill, and there was a person inside it.' },
      { p: 'Judith Carter Henry was around 85 years old, a bedridden widow, and the hill the two armies were now tearing apart already bore her family\'s name. It was her hill, the one she had lived on for the better part of a lifetime, long before either army had ever heard of it. When the fighting closed in, her family tried to carry her out of the house to safety. The old woman begged to be taken back to her own bed, and they did. Union artillery, convinced Confederate sharpshooters were firing from the house, turned its guns on it. A shell came through the bedroom wall and tore off one of her feet, with other wounds, and she died that same day in the bed she had refused to leave.' },
      { fig: '/war-img/bull-run-henry-house.jpg', cap: 'The ruined Henry house on the crest of Henry House Hill, where Judith Carter Henry, the first civilian killed in the Civil War, died in her own bed when Union artillery shelled the building.', credit: 'Battlefield photograph, March 1862 · public domain' },
      { p: 'The first major battle of a war that would go on to kill three quarters of a million people took its first civilian life in an old widow\'s bedroom. Not a soldier, not a combatant, not anyone who had chosen a side, but an elderly woman who asked only to be carried back to her own bed and was killed in it by a shell fired at a house she happened to live in. The whole country would learn the name Henry House Hill. Almost no one would remember it was named for her. Judith Henry is considered the first civilian killed in the American Civil War, and the hill that made her famous is the hill that killed her.' },
      { h: 'Henry House Hill', eyebrow: 'The trains turn the tide' },
      { p: 'For hours the two armies tore at each other across the plateau, and the worst of it gathered around the guns. Union artillery captains James Ricketts (North) and Charles Griffin (North) pushed their batteries (a battery being a cluster of cannon, here about 11 guns between them) forward onto the hill, into close, confused, point-blank fighting. Then a line of soldiers in blue came up out of the smoke toward the Union guns. They were Confederates, the 33rd Virginia, but early in the war uniform colors were not yet standardized, and plenty of Southern units still wore blue, the same shade as the U.S. Army. Griffin saw them, suspected the worst, and wanted to fire. He was overruled. Major William F. Barry (North), McDowell\'s chief of artillery, was certain the approaching men were friendly Union troops and ordered Griffin to hold his fire. They were not friendly. At a few dozen yards the 33rd Virginia leveled their muskets and shattered the gun crews, and the batteries were overrun. The guns changed hands again and again after that, in brutal close fighting, but that one held order, do not fire, they are ours, given to men dressed identically to the enemy, was the hinge.' },
      { p: 'What finally broke the day came off the railroad. The last of Johnston\'s brigades from the Shenandoah Valley, the men the trains had shuttled in, were still reaching the field through the afternoon, and they arrived on the exposed Union flank at the worst possible moment for McDowell. Brigadier General Edmund Kirby Smith\'s (South) brigade got there by rail around 3:30 to 4:00 p.m.; Kirby Smith was almost instantly shot down, wounded badly in the neck and shoulder, and command passed to Colonel Arnold Elzey (South), who drove the brigade in a charge that smashed into the right end of the Union line on Chinn Ridge, just west of Henry House Hill. At the same moment, Colonel Jubal Early\'s (South) brigade struck the same flank from another angle. Fresh Confederate troops, delivered by railroad to the exact spot where they would do the most damage, slammed into a Union army that was running out of strength.' },
      { p: 'And as they came on, the Confederates made a sound.' },
      { p: 'a high, broken, screaming cry, rising out of the smoke and coming straight at you', q: true },
      { p: 'Through the afternoon\'s counterattacks the rebel infantry raised a battle cry that the men who heard it never forgot: the rebel yell, somewhere between a scream and a howl. First Bull Run is generally credited as its first appearance in a major battle. The order that supposedly set it off, a command from Jackson to "yell like furies," comes only from post-war accounts and does not appear in Jackson\'s own official reports, so we can describe the yell but not vouch for the order. Whatever started it, the effect on exhausted Union troops already bending under the flank attack was real. The tide on Henry House Hill had turned.' },
    ],
    meanwhile: { region: 'the same morning', title: 'The plan that mirrored the plan', body: 'McDowell spent that morning swinging wide to crush the Confederate left. Beauregard, that same morning, had his own offensive ready to go, a plan to swing around and crush the Union left, driving up toward Centreville. Johnston, the senior man, had approved it. Both green armies, both green commanders, each one planning the identical move against the other\'s weak flank at the same dawn. The only thing that decided who held the initiative was who moved first, and McDowell moved first, which is the whole reason the battle was fought on the Confederate left instead of the Union one. The saying that the two sides were green alike was truer at the level of the two commanders\' war plans than anyone watching could possibly have known.' },
  },

  'the-rout': {
    eyebrow: 'First Bull Run · The day the short war died',
    title: 'The Rout',
    blocks: [
      { p: 'A battle that has gone one way for six hours can change in twenty minutes, and that is what happened to the Union army on the afternoon of July 21. One moment Brigadier General Irvin McDowell\'s (North) men were fighting a hard, even battle on Henry House Hill; the next, with fresh Confederates pouring onto their flank and that unearthly yell rising out of the smoke, they were an army no longer. Around 4:00 p.m. the Union line gave way, and the retreat began.' },
      { h: 'The Great Skedaddle', eyebrow: 'From near-victory to panic' },
      { p: 'It did not start as a panic. An exhausted army that has fought all day and is finally pushed too far will often pull back in reasonable order at first, and McDowell tried to organize a withdrawal behind a rear guard, a small force left in place to slow the enemy while the rest of the army gets away. What turned an orderly retreat into a stampede was an accident on a bridge. As the Union troops fell back toward their base at Centreville, they had to cross Cub Run Creek on a single bridge, and a Confederate artillery shell overturned a wagon right on the span. The road jammed. With the only easy way out suddenly blocked and rebels behind them, the tired retreat dissolved into a terrified mob, men throwing away rifles, packs, anything that slowed them down, all running the same direction at once. The Southern press named it the Great Skedaddle.' },
      { p: 'Those roads back toward Washington were not empty. They were clogged with the carriages of the picnickers, the senators and congressmen and their families who had ridden out to watch a victory. Now the fleeing army and the fleeing spectators collided on the same narrow roads, and the panic fed on itself.' },
      { p: 'The four senators came back into the story here. They did not all flee. Senator Ben Wade of Ohio (North) snatched up a discarded rifle, planted himself across the road, and threatened to shoot any soldier who kept running, a United States senator trying to stop a routed army by himself, until a still-intact regiment came up and restored a little order. Senator Zachariah Chandler of Michigan (North) tried much the same thing, throwing himself across the road to block the retreat. Senator Henry Wilson of Massachusetts (North) had been handing out sandwiches when a Confederate shell smashed his buggy to splinters; he finished the day escaping toward Washington on the back of a stray mule. Senator James Grimes of Iowa (North) barely dodged capture and swore he would never go near a battlefield again. The crowd that had treated a battle like a horse race got the most realistic possible education in what war actually was, and a few of them stood in the road and tried to turn it around with their bare hands.' },
      { fig: '/war-img/bull-run-stone-bridge.jpg', cap: 'The Stone Bridge over Bull Run, on the main road back toward Washington, part of the retreat route the Union army scrambled across after the line broke around 4:00 p.m.', credit: 'Battlefield photograph, March 1862 · public domain' },
      { h: 'The Great Skedaddle', eyebrow: 'A congressman in the bag' },
      { p: 'One of the spectators did not make it back at all. Representative Alfred Ely (North), the New York congressman who had come out to look in on a regiment he had helped recruit, got swept up in the collapse and was captured by advancing Confederate troops. Brought before rebel officers, he announced himself: "the Honorable Alfred Ely, Representative in Congress from New York." They took him to Richmond and held him in Libby Prison, a converted tobacco warehouse where captured Union officers were kept. Ely had the strange distinction of being the only member of the United States Congress to reach Richmond that day, not in triumph, the way Greeley\'s headline had promised, but as a prisoner of war. He was finally freed in a prisoner exchange, the negotiated system by which each side traded captured men for its own, on Christmas Day, 1861.' },
      { pill: '/war-civil-war/off-the-battlefield/prisons', plabel: 'Prisons: Libby, Andersonville, and the captured' },
      { h: 'The Great Skedaddle', eyebrow: 'The victory they could not finish' },
      { p: 'The Confederates had won a stunning victory, and they almost entirely failed to cash it in. The road to Washington was, for a few hours, wide open, a fleeing, disintegrating enemy and a captured capital practically begging to be taken. Jefferson Davis arrived on the field and urged a pursuit. It did not happen. The winning army was nearly as wrecked by victory as the losing army was by defeat. These were green Confederate troops too, exhausted, scattered, their units tangled, their officers as inexperienced as McDowell\'s. An attempt to push brigades forward to intercept the retreat ran into McDowell\'s rear guard and stalled out. The South had broken the Union army and then discovered it was in no condition to chase it. The same rawness that doomed McDowell\'s plan saved his army from total destruction.' },
      { h: 'The reckoning', eyebrow: 'The day the short war died' },
      { p: 'Then came the counting. The standard tally puts the day\'s casualties at roughly 4,878 men killed, wounded, captured, or missing, about 2,896 on the Union side and 1,982 on the Confederate (and the scholarly figures vary, running somewhere in the range of 4,700 to 4,900 total, because the sources disagree on how to count the missing and the captured). To a public that had packed picnic baskets, the numbers were a hammer blow. Around 847 Americans were killed in this single afternoon, roughly half of all the U.S. battle deaths in the entire Mexican-American War, the country\'s last big war, which had taken two years to accumulate them. One Sunday in Virginia had killed about half as many Americans as two years of war in Mexico.' },
      { p: 'Today will be known as BLACK MONDAY. We are utterly and disgracefully routed, beaten, whipped by secessionists.', q: true },
      { p: 'That was the New York diarist George Templeton Strong, whose journal is one of the great records of Northern feeling during the war, writing the morning after. The reaction split along the two sides. The North was sobered into seriousness: the very next day Lincoln signed legislation authorizing 500,000 three-year volunteers, three years rather than ninety days, the federal government finally admitting in law what the battlefield had just proven. Congress went looking for someone to blame, and within months it created the Joint Committee on the Conduct of the War, a standing body of senators and congressmen chaired by Ben Wade, the same man who had stood in the road with a rifle, that would investigate, second-guess, and hound the Union\'s generals for the rest of the war. McDowell himself was relieved within days, and George B. McClellan (North), fresh off small victories in western Virginia, was summoned to Washington to build and train a real army out of the wreckage, the Army of the Potomac, which would become the main Union army in the East and fight the war\'s biggest battles for the next four years. The South swung the other way, into a dangerous elation; the easy victory bred a confidence that some historians think did the Confederacy long-term harm, teaching it to expect wins that would not keep coming.' },
      { p: 'One last figure is worth following off the field. A farmer named Wilmer McLean owned land near Manassas; Beauregard had used his house as a headquarters, and during the fighting a Union cannonball came down through McLean\'s kitchen. So McLean moved his family well away from the armies, about 120 miles (190 km) south, to a quiet crossroads called Appomattox Court House. The war followed him there. Four years later, in the spring of 1865, Robert E. Lee surrendered the Confederacy to Ulysses S. Grant in Wilmer McLean\'s parlor. The war that began in his front yard at Bull Run ended in his front room.' },
    ],
    meanwhile: { region: 'the North', title: 'The morning the long war began', body: 'For three months, North and South alike had been living inside the same comfortable story: one battle, a quick win, everyone home by fall. Bull Run ended that story for the whole country. The men in Washington who woke up on Black Monday understood, many of them for the first time, that this was not going to be quick and was not going to be cheap, that the casualty list from a single Sunday in Virginia was a down payment on something enormous. The South came out of it with a hero and a name for him; Stonewall Jackson was born on that hill, and the legend would follow him to his death. But the bill that came due that morning was real. An old woman was dead in her own bedroom. Nearly nine hundred Americans were dead in a single afternoon, half a war\'s worth of dying in a war the country had thought it could win before harvest. In those sobered Northern minds, on that gray morning, the four-year war that was actually coming, the one that would finally settle whether a man could own another man, began.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={BULL_RUN_NARR} id={id} slug="bull-run" battleName="First Bull Run" theatreId="east" battleId="e-bullrun1" />
}
