'use client'

// THEME section — The Turning (Off the Battlefield, kind=theme). Built through
// the war content pipeline (fact pack → author(Opus) → five gates [fact-check +
// storytelling + comprehensiveness + clarity + Lost Cause/framing] → revise → images).
// Source + gate records: audits/war-pipeline/the-turning-*.md. Green accent; no stat
// block, no map. 'use client' is REQUIRED (reads ACCENTS from a client module).
// GENERATED from the-turning-final.md by scripts/_build-war-themes.mjs — do not hand-edit
// the prose here; edit the final.md and rebuild.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS, WAR_ACCENT } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: `The year the war was decided`,
    title: `The Turning`,
    blocks: [
      { p: `In 1863 the Civil War turned, and it turned in a place most of the country wasn’t looking. The headlines belonged to the East, to the hundred-mile corridor between Washington and Richmond where Robert E. Lee’s army kept winning and the press kept watching. But the war was being decided a thousand miles west, on the Mississippi River, where a stubborn Union general named Ulysses S. Grant was about to cut the Confederacy in half. Gettysburg is the famous turn. Vicksburg is the deeper one.` },
      { p: `This is the third chapter of the military story: how, in a single year, the Union stopped fighting a scatter of separate campaigns and started fighting one war with one design. It does not re-tell the battles blow by blow; it links down to those. What it carries is the shape of the year, and the year had two spines. One was geographic: hold and bleed Lee in the East, and win the war in the West by taking the river. The other was a change in what the Union armies were made of. In 1863 emancipation stopped being a piece of paper and became a weapon, because the men the South had enslaved began putting on Union blue and walking into the fire.` },
      { fig: '/war-img/the-turning-fig1-mississippi-map.jpg', cap: `Robert Knox Sneden’s 1863 map of the rebel position at Vicksburg, showing the Confederate fortifications, the Union gunboats, and the river closed above and below the city.`, credit: `Robert Knox Sneden · 1863 · Library of Congress Geography & Map Division (gvhs01.vhs00140) · public domain` },
      { h: `Two fronts, one plan`, eyebrow: `The maturing design` },
      { p: `By 1863 the Union had finally settled on a way to think about the whole war at once, and the bones of it were two years old. Back in the spring of 1861, General-in-Chief Winfield Scott had proposed a strategy the country mocked. It had two parts: a naval blockade to seal every Confederate port, and a powerful column driving straight down the Mississippi to split the Confederacy in two. Critics jeered that it was too slow, a snake’s slow squeeze instead of a quick knockout, and they nicknamed it the Anaconda. But the logic outlived the laughter. Strangle the South, don’t just smash it: cut off its cotton from the world, cut off its imported guns and food, and cut its own territory in half.` },
      { p: `The river was the prize for a plain reason. It was the spine of the western Confederacy, and whoever held it controlled whether the western states could feed and reinforce the rest. Open the Mississippi and you split the rebellion: Texas, Arkansas, and most of Louisiana, the country west of the river that supplied cattle, food, and men, would be sliced off from everything east of it. By the autumn of 1862 the Confederacy held just one stretch of the river, roughly 150 miles of it, between Vicksburg, Mississippi, in the north and Port Hudson, Louisiana, in the south. Take both forts and the river would run Union from its headwaters to the Gulf.` },
      { p: `That gave the year its division of labor. The East was where Lee’s Army of Northern Virginia, the Confederacy’s best army and the shield in front of Richmond, had to be contained, ground down in a war of attrition the South could not win outright but could lose slowly. The West was where the war could actually be won, because the geography opened up, the targets were decisive, and the Union had aggressive generals there who would fight. Many historians now argue that the West was the theater that decided the result, that accessible rivers, valuable targets, and commanders willing to take risks made it the place the war was actually settled. The East got the headlines and the monuments. The West got the result.` },
      { p: `Behind it all stood the obvious question of what these armies were fighting over, and the answer was not in doubt. The Confederacy had been built to preserve and extend slavery; eleven states had broken away rather than accept any limit on the enslavement of roughly four million people, and they had raised their armies, run their economy, and ordered their society around it. Every strategic target in this chapter, the river, Vicksburg, the supply line of the Trans-Mississippi (the Confederate states west of the Mississippi River), fed a war effort whose purpose was to keep human beings as property. That is the thing the year was about to begin turning against the South.` },
      { p: `The two commanders-in-chief approached it differently. Abraham Lincoln was groping toward a single national strategy: advance on several fronts at once, aim at destroying Confederate armies and resources rather than just taking ground, and find a general who would actually carry it out. Jefferson Davis had a coherent doctrine of his own, an “offensive-defensive” meant to defend the whole Confederacy and then concentrate against any invading column. But he ran the war through a rigid system of semi-independent departments whose commanders rarely cooperated, and he seldom forced them to. The result undid his own doctrine: the South tried to defend everywhere and ended up strong nowhere.` },
      { h: `Winning the wrong way`, eyebrow: `The East bleeds` },
      { p: `The East in 1863 is the strange spectacle of Lee winning battles and losing the war anyway. The clearest case is Chancellorsville, fought from April 30 to May 6, 1863, in the tangled second-growth forest of Spotsylvania County, Virginia, that everyone called the Wilderness. Outnumbered something like two to one, Lee beat Major General Joseph Hooker’s (North) Army of the Potomac by doing the riskiest thing in the book: he divided his smaller army, twice. Lieutenant General Thomas “Stonewall” Jackson took roughly 28,000 men on a long flank march around the Union right and crushed an entire Union corps at dusk. It is widely called Lee’s masterpiece, his perfect battle.` },
      { pill: '/war-civil-war/eastern/chancellorsville', plabel: `Chancellorsville` },
      { p: `And it cost more than it bought. In raw numbers the North lost more men, around 17,300 to about 13,000, but the South lost a far larger share of a much smaller army, roughly a fifth of Lee’s entire force against perhaps an eighth of Hooker’s. That is a trade the Confederacy could not keep making. The “hold and bleed Lee” half of the Union plan worked exactly like this: not by Union victory, but by an arithmetic in which even a brilliant Confederate win drained the side that could least afford it.` },
      { p: `The single steepest part of the bill came on the night of May 2. Jackson, riding forward in the dark to press his advantage, was shot by his own men. His left arm was amputated, and he died of pneumonia on May 10, 1863, at thirty-nine. He was Lee’s most aggressive corps commander, the engine of the flank attack, and he could not be replaced. Lee had to reorganize his army before his next campaign, and historians have drawn a straight line from Jackson’s death to the command failures that followed. The South’s leadership was running out the same way its men were, even in its triumphs.` },
      { p: `There was one more cost, the kind you only see later. Chancellorsville filled Lee with exactly the confidence that talked him into invading the North again in June. So the East’s best Confederate victory of 1863 set up its worst defeat. And it was fought four months after the Emancipation Proclamation took effect on January 1, 1863, which meant every man in those armies was now fighting a war openly about whether slavery would survive.` },
      { pill: '/war-civil-war/off-the-battlefield/emancipation', plabel: `Emancipation` },
      { h: `The river that split the rebellion`, eyebrow: `Vicksburg, the true hinge` },
      { p: `Vicksburg sat on high bluffs on the east bank of the Mississippi, above a hairpin bend, its guns looking straight down the channel. It was the last great Confederate lock on the river, and through the winter of 1862 and into 1863 Grant could not crack it. He tried four water experiments to get at the city, digging canals and pushing gunboats through flooded bayous, and all four failed. The Northern papers wrote him off as stuck, as a drunk, as finished.` },
      { p: `In mid-April Grant had Rear Admiral David Dixon Porter (North) run his fleet straight downriver past the Vicksburg batteries in the dark, taking two and a half hours of bombardment to get gunboats and transports below the city. Then Grant marched his army down the far bank, ferried it across the river at Bruinsburg on April 30 in the largest amphibious landing in American history before D-Day, and did the thing the textbooks said you must never do: he cut loose from his supply base and lived off the country.` },
      { p: `Inland, he moved fast. In eighteen days his army fought five battles, drove between two separate Confederate forces so they could never join, took Jackson, the Mississippi state capital, and scattered the army General Joseph E. Johnston (South) was assembling there. The decisive fight was Champion Hill on May 16. By winning it, Grant stayed wedged between Johnston’s force outside the city and Lt. Gen. John C. Pemberton’s (South) army inside it, and one whole Confederate division was cut off and never made it back into Vicksburg at all. After that the city’s fate was sealed.` },
      { pill: '/war-civil-war/western/champion-hill', plabel: `Champion Hill` },
      { pill: '/war-civil-war/western/vicksburg', plabel: `Vicksburg` },
      { p: `Pemberton pulled his army inside the defenses, and Grant settled into a 47-day siege, from May 18 to July 4. The contrast inside it was the whole war in miniature. Grant’s army grew, resupplied now by the river he half-controlled; Pemberton’s shrank and starved, the garrison and the trapped townsfolk eating mule and horse and rat, hundreds of civilians living in caves dug into the bluffs to escape the shelling. On July 4, 1863, Pemberton surrendered the city and roughly 29,500 men, who were paroled (released on their word of honor not to fight again until they were formally exchanged), along with some 172 cannon.` },
      { p: `The payoff was enormous and permanent. Five days later, on July 9, Port Hudson, the downstream lock, surrendered too, and the Union held the entire Mississippi from source to Gulf. Texas, Arkansas, and most of Louisiana were cut off from the rest of the Confederacy for good. Lincoln put it better than anyone: “The Father of Waters again goes unvexed to the sea.” And it remade Grant, turning the general the papers had buried into the man Lincoln would eventually hand the whole war.` },
      { pill: '/war-civil-war/trans-mississippi/port-hudson', plabel: `Port Hudson` },
      { fig: '/war-img/the-turning-fig3-vicksburg.jpg', cap: `Union soldiers of Logan’s division march into Vicksburg on July 4, 1863, the day of Pemberton’s surrender. The Confederacy’s last lock on the Mississippi had fallen.`, credit: `Theodore R. Davis · “Battles and Leaders of the Civil War,” 1887 · British Library · public domain` },
      { h: `Twin July turning point`, eyebrow: `Why the river mattered more` },
      { p: `The same week Vicksburg fell, the East got its famous turn. From July 1 to 3, 1863, in and around the town of Gettysburg in Adams County, Pennsylvania, Lee’s second invasion of the North ran into Major General George G. Meade (North) and the Army of the Potomac. The climax was a doomed frontal assault against the center of the Union line on the third day, remembered as Pickett’s Charge though it was the work of three commands, not one, and it broke apart against Cemetery Ridge in what is still called the high-water mark of the Confederacy. Combined casualties ran somewhere between 46,000 and 51,000. Lee never invaded the North again, and that, more than the body count, is what made it a turning point.` },
      { pill: '/war-civil-war/eastern/gettysburg', plabel: `Gettysburg` },
      { fig: '/war-img/the-turning-fig4-gettysburg.jpg', cap: `Timothy O’Sullivan’s “A Harvest of Death,” Union dead on the field at Gettysburg, July 1863. It is the war’s most famous photograph of what the fighting cost, made days after Pickett’s Charge.`, credit: `Timothy H. O’Sullivan (negative), Alexander Gardner (print) · July 1863 · Library of Congress Prints & Photographs Division · public domain` },
      { p: `Gettysburg and Vicksburg are conventionally paired as the twin July hinge of the war, the moment the Confederacy lost the initiative and never got it back. Both happened in the same few days, Vicksburg surrendering on July 4 as Lee’s beaten army began its retreat from Pennsylvania. But the two were not equal in weight, and it is worth saying plainly which one mattered more.` },
      { p: `Gettysburg was a battle Lee survived. His army was bloodied, but it escaped back across the Potomac and fought on for nearly two more years. Vicksburg destroyed an army and a strategic line: an entire Confederate field force was captured, and a permanent asset, the river itself and the supply it carried from the Trans-Mississippi, was lost forever. Gettysburg ended an invasion and put Lee back where he had started, in Virginia. Vicksburg ended a theater. It split the Confederacy in two and turned the Mississippi into a Union highway running straight into the Deep South, a change that could not be undone.` },
      { p: `There is a forgotten campaign that makes the same point in miniature. While the country fixed on Gettysburg and Vicksburg, Major General William Rosecrans (North) ran one of the most elegant operations of the entire war, the Tullahoma Campaign of late June, maneuvering General Braxton Bragg (South) clean out of Middle Tennessee toward Chattanooga at almost no cost in lives. It ended the same week as the two famous victories and was instantly forgotten because nobody had bled enough for the papers to notice. Rosecrans saw it coming and protested to the War Department: “I beg in behalf of this army that the War Department may not overlook so great an event because it is not written in letters of blood.” The West kept winning the war while the East kept getting the attention. That is the year’s real shape.` },
      { h: `Emancipation becomes a weapon`, eyebrow: `Black soldiers enter the fight` },
      { p: `The other turning of 1863 had nothing to do with geography. It was that the people the South had enslaved began fighting in the Union army, and that changed the arithmetic of the whole war.` },
      { p: `The machinery for it came together fast. The Emancipation Proclamation, in effect since January 1, had explicitly authorized enlisting freed people into Union service. Then General Order 143, issued May 22, 1863, created the Bureau of Colored Troops and formally organized those regiments as the United States Colored Troops. By the end of the war roughly 186,000 Black men had served in the Union army, close to one in ten of all Union soldiers. Lincoln, in his annual message to Congress in December 1863, reckoned that a “full 100,000” formerly enslaved men were already in U.S. service, “about one-half of which number actually bear arms.”` },
      { pill: '/war-civil-war/off-the-battlefield/usct', plabel: `Freedom Seekers & the USCT` },
      { p: `Lincoln understood exactly what this was, and he said so. Black soldiering, he argued, was a resource that, vigorously applied, would help close the contest, because it worked doubly: every enslaved man who joined the Union ranks was a soldier subtracted from the labor that kept the Confederacy running and added to the army fighting it. In a letter that summer he laid out the bargain plainly: “If they stake their lives for us, they must be prompted by the strongest motive, even the promise of freedom. And the promise being made, must be kept.”` },
      { pill: '/war-civil-war/off-the-battlefield/freedom-struggle', plabel: `The Freedom Struggle` },
      { p: `It was one thing to write the order and another to prove the men would fight, and 1863 settled that in three battles. At Port Hudson, on May 27, the 1st and 3rd Louisiana Native Guard, regiments raised in occupied New Orleans and full of formerly enslaved men, charged the Confederate bluffs in a failed assault. Captain André Cailloux (North), among the first African American officers in any army on the continent, kept waving his company forward with his sword after his arm was shattered, until a shell killed him; his body lay on the field until the surrender, and his New Orleans funeral that summer drew thousands and made him a martyr and a recruiting symbol.` },
      { p: `Ten days later, on June 7, came the hand-to-hand proof. At Milliken’s Bend, a Union supply post on the river about fifteen miles above Vicksburg, a garrison of newly recruited, barely armed formerly enslaved men held off a Confederate attack in some of the closest, ugliest fighting of the war. One regiment, the 9th Louisiana of African descent, lost about 68 percent of its strength, the heaviest proportional loss of any Black regiment in the war.` },
      { fig: '/war-img/the-turning-fig5-fort-wagner.jpg', cap: `Kurz & Allison’s print of the 54th Massachusetts storming Battery Wagner on July 18, 1863, the assault that proved to a skeptical North that Black soldiers would fight and die for the Union.`, credit: `Kurz & Allison · chromolithograph, 1890 · Library of Congress Prints & Photographs Division (LC-DIG-cph-3b52016) · public domain` },
      { p: `Then, on July 18, the famous charge. The 54th Massachusetts Volunteer Infantry led a doomed twilight assault on Battery Wagner, guarding Charleston harbor. Its commander, Colonel Robert Gould Shaw (North), was killed on the parapet and buried by the Confederates in a mass grave with his Black soldiers, an insult that became an honor. The regiment took the heaviest loss of the assault, about 270 of some 600 engaged. Sergeant William Harvey Carney (North), wounded, saved the regimental flag after the color-bearer fell and carried it through the fight; his actions at Battery Wagner were among the earliest by any Black Medal of Honor recipient, though his medal itself did not come until 1900. Battery Wagner held. Tactically it was a defeat. Strategically it convinced a doubting North that Black troops would fight, and the formerly enslaved soldier, as Secretary of War Edwin Stanton (North) put it, had proved his manhood.` },
      { p: `This is the cause made flesh. Men who had been legal property a year earlier were charging the army that fought to keep them property, and emancipation had become a manpower resource the Confederacy, by the very thing it was fighting for, could never match. Every mile the Union advanced into the South now turned into a recruiting ground. In 1863 the thing the South had seceded to protect became an engine of its defeat.` },
      { fig: '/war-img/the-turning-fig2-usct.jpg', cap: `“Come and Join Us Brothers,” a recruiting broadside for the United States Colored Troops, showing Black soldiers in Union blue marching behind the flag.`, credit: `Supervisory Committee for Recruiting Colored Regiments, Philadelphia · 1865 · public domain` },
      { h: `The arithmetic of the war`, eyebrow: `The manpower machine strains` },
      { p: `Underneath the battles ran a slower crisis. By 1863 both governments had run out of volunteers and had to start compelling men into the ranks, and the way each one did it exposed the war’s deepest fault line.` },
      { p: `In the North it took the form of the Enrollment Act of March 3, 1863, the first true national draft, which made men aged twenty to forty-five liable to conscription wherever volunteering fell short. What enraged people were two escape hatches written into it. A drafted man could avoid service by furnishing a substitute to go in his place, or by paying a $300 commutation fee, roughly a year’s wages for a laborer. Both were meant to cushion the propertied classes, and both gave the war a bitter slogan: “a rich man’s war and a poor man’s fight.”` },
      { p: `That anger exploded in New York City from July 13 to 16, 1863, in the worst urban riot in American history to that point. Working-class crowds, many of them Irish immigrants who saw themselves being conscripted to free Black workers who competed for their jobs, turned the city over to days of looting and murder. Mobs burned the Colored Orphan Asylum, with more than two hundred children inside who barely escaped, and lynched Black New Yorkers in the streets. About 120 people were killed by the official count, with much higher figures contested, and the rioting was put down only when Union regiments returning from Gettysburg were diverted into the city, combat troops pulled off the war’s biggest battlefield to police the home front. The draft meant to fill the armies had briefly drained them instead.` },
      { pill: '/war-civil-war/off-the-battlefield/war-within-north', plabel: `The War Within the North` },
      { p: `The Confederacy had reached this point first, and harder. Its First Conscription Act came on April 16, 1862, a full year before the Union’s, making white men aged eighteen to thirty-five liable to three years’ service; later acts pushed the ceiling to forty-five and finally widened the net to ages seventeen to fifty. The South was scraping its manpower barrel earlier and deeper because it simply had fewer men. And it cut its own class wound just as the North did: the so-called Twenty-Negro Law of October 1862 exempted one white man from the draft on any plantation with twenty or more enslaved people, ostensibly to keep slavery and its policing running while the soldiers were away. It raised the same howl of “rich man’s war, poor man’s fight” in the South, and it fed desertion and resentment.` },
      { p: `Read as one system, the manpower numbers were the war’s deepest asymmetry, and 1863 is when they bit. The Confederacy had to conscript more men, younger and older and for longer, because it was a smaller population fighting a larger one, and it could not touch the four million enslaved people whose bondage was the whole point of the war. Emancipation handed that resource to the other side.` },
      { h: `Lincoln finds his general`, eyebrow: `The rise of Grant` },
      { p: `The year had one act left, and it ran through the gateway to the Deep South at Chattanooga.` },
      { p: `The South got its last great Western victory first. After Rosecrans (North) maneuvered Bragg (South) out of Chattanooga, Bragg turned and fought, reinforced by part of Lt. Gen. James Longstreet’s (South) corps sent west by rail from Lee’s own army, and won the bloodiest battle of the Western theater along Chickamauga Creek in Georgia on September 18 through 20. A gap opened in the Union line, much of the army broke and fled back toward Chattanooga, and only the stand of Maj. Gen. George H. Thomas (North), who earned the name “the Rock of Chickamauga” that day, kept the defeat from becoming a destruction. Then Bragg laid siege to the city.` },
      { pill: '/war-civil-war/western/chickamauga', plabel: `Chickamauga` },
      { p: `And then he threw it all away, his army quarreling and Bragg failing to press his advantage, which was Davis’s broken command system doing exactly what it always did. Lincoln answered with the pivotal command decision of the year. On October 16, 1863, the War Department created the Military Division of the Mississippi, folding together every Union army between the Mississippi River and the Appalachian Mountains, and gave the whole thing to Grant. For the first time the western war had a single hand on it, and Grant immediately replaced Rosecrans with Thomas and went to break the siege.` },
      { p: `He broke it in two days in late November. First, Lookout Mountain on the 24th, the small fight with the giant name that men called the Battle Above the Clouds, which pried open the Confederate left.` },
      { pill: '/war-civil-war/western/lookout-mountain', plabel: `Lookout Mountain` },
      { p: `Then, on the 25th, Missionary Ridge, where the Army of the Cumberland did something nobody ordered: the men started up the ridge to take the rifle pits at its base and just kept climbing, straight up a slope that should have been impossible, until they burst over the crest and shattered Bragg’s army outright. Chattanooga, the gateway to Atlanta and the Deep South, was firmly Union, and the Confederacy’s last Western win had been erased inside two months.` },
      { pill: '/war-civil-war/western/missionary-ridge', plabel: `Missionary Ridge` },
      { fig: '/war-img/the-turning-fig6-chattanooga.jpg', cap: `Alfred Waud’s field sketch of the Union charge up Missionary Ridge, November 25, 1863, the day Grant’s western armies shattered Bragg’s line and opened the road to Atlanta.`, credit: `Alfred R. Waud · 1863 · Library of Congress Prints & Photographs Division · public domain` },
      { p: `That settled it. Lincoln had spent two years cycling through Eastern generals who would not fight, and the line he is said to have used to defend Grant after the bloodbath at Shiloh the year before, “I can’t spare this man; he fights,” now read like prophecy. Vicksburg and Chattanooga made the choice obvious. Congress revived the rank of lieutenant general, last held in full by George Washington; the Senate confirmed Grant’s promotion to lieutenant general on March 2, 1864, and he received the commission at the White House on March 9, making him general-in-chief of all the armies of the United States. The year closed with the Union holding, at last, both a strategy and the general to run all of it at once. The man who had taken the Mississippi was about to take command of the whole war.` },
    ],
    meanwhile: {
      region: `all theaters, 1864`,
      title: `Coordinated Attrition`,
      body: `With Grant now general-in-chief, 1864 becomes the first year the Union armies move as one machine, advancing on every front at once so the South can no longer shuttle troops to plug each hole in turn. Grant grinds south toward Richmond while Sherman drives on Atlanta, and the arithmetic that had been bleeding the Confederacy slowly turns into a vise. As the casualty lists grow unbearable, the battlefield collides with the ballot box.`,
    },
  },
}

export default function TheTurningThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="the-turning"
      battleName="The Turning"
      theatreId="howfought"
      battleId="mil-1863"
      theatreHref="/war-civil-war/how-the-war-was-fought"
      accent={WAR_ACCENT}
      heroImage="/war-img/the-turning-hero.jpg"
      heroPalette={["#404040","#404020","#402020"]}
      heroCredit={`Kurz & Allison · “Siege of Vicksburg,” chromolithograph, c. 1888 · Library of Congress Prints & Photographs Division (LC-DIG-pga-01871) · public domain`}
      heroFocus="center 42%"
      heroScale={1.06}
      endHref="/war-civil-war/how-the-war-was-fought"
      endKicker={`The war was won in the West`}
      endLabel={`Back to the Military Story`}
    />
  )
}
