'use client'

// THEME section — Improvising a War (Off the Battlefield, kind=theme). Built through
// the war content pipeline (fact pack → author(Opus) → five gates [fact-check +
// storytelling + comprehensiveness + clarity + Lost Cause/framing] → revise → images).
// Source + gate records: audits/war-pipeline/improvising-a-war-*.md. Green accent; no stat
// block, no map. 'use client' is REQUIRED (reads ACCENTS from a client module).
// GENERATED from improvising-a-war-final.md by scripts/_build-war-themes.mjs — do not hand-edit
// the prose here; edit the final.md and rebuild.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS, WAR_ACCENT } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: `The war both sides thought would be short`,
    title: `Improvising a War`,
    blocks: [
      { p: `In the spring of 1861, eleven Southern states broke away from the United States and raised armies. The Confederacy was formed to preserve slavery, and that is what its armies defended; its own leaders said so, in their own founding documents, at the time. Roughly four million people were held in bondage across the South, and the war that began that spring was, at bottom, about whether people could be owned.` },
      { pill: '/war-civil-war/off-the-battlefield/two-governments', plabel: `Two Governments` },
      { p: `This is the first chapter of the military story: how the war was planned, how wins and losses reshaped strategy, and how two men who had never run a war learned to run one. It does not re-tell the battles blow by blow; it links down to those. What it carries is the shape of the whole thing. And the shape, in 1861, was a paradox neither side had braced for.` },
      { fig: '/war-img/improvising-a-war-fig1-recruiting-poster.jpg', cap: `An actual 1861 recruiting broadside for the “Scott Legion Regiment,” one of fourteen called up from Pennsylvania, posted on the streets of Philadelphia. Notice the fine print: officers “who have served in Mexico,” and a “three months enlistment.” Everybody, the paperwork included, thought this would be a short war.`, credit: `J. H. Jones & Co., Philadelphia · 1861 · Library Company of Philadelphia / Wikimedia Commons · public domain` },
      { h: `Two republics, unequal`, eyebrow: `The asymmetry` },
      { p: `On paper this looked like a wildly lopsided fight. The Union had about 22 million people; the Confederacy had fewer than 9 million, and of those, nearly 4 million were enslaved, roughly a third of the South’s entire population, and the very people the war was being fought to keep in chains. The South would not, for most of the war, put guns in their hands. So the pool of free men the Confederacy could actually mobilize was a fraction of the North’s. Split the national population and you get something like 71 percent on the Union side, 29 percent on the Confederate side.` },
      { pill: '/war-civil-war/off-the-battlefield/slavery-cotton', plabel: `Slavery & the Cotton Economy` },
      { p: `The industrial gap was even starker. By 1860 the North made nearly all the country’s manufactured goods: somewhere around 97 percent of its firearms, 96 percent of its railroad locomotives, 94 percent of its cloth, and 93 percent of its pig iron (the raw iron everything else is made from). The industrial revolution had, more or less, stopped at the Mason–Dixon line, the old surveyor’s boundary that had come to mark the divide between free North and slave South. The Confederacy was a farming country about to fight an industrial war.` },
      { p: `Then there were the railroads, and railroads in this war were not a convenience. They were the nervous system that let a government move and feed armies across a continent. The North had roughly 21,000 to 22,000 miles of track; the South had about 9,000 (again, near enough to that 71/29 split). And the South’s existing rail network was a patchwork of different gauges (the distance between the rails) that couldn’t share rolling stock, so a Northern army could be supplied down one continuous iron road where a Southern army frequently had to stop, unload, cart its supplies across a gap, and reload onto a different train. The U.S. Navy, though small, was a real national navy with ships, yards, and trained officers; the Confederacy began the war with essentially no navy at all and had to build one from scratch.` },
      { p: `So: fewer people, almost no factories, a crippled rail network, no fleet. By the numbers the South should have lost in a season. It did not, and the reason it didn’t is the strategic heart of this chapter.` },
      { p: `The Confederacy that fought at Bull Run was bigger than the one that had fired on Fort Sumter. Lincoln’s call for troops after Sumter drove Virginia, North Carolina, Tennessee, and Arkansas out of the Union, taking it from seven states to eleven. That added the industrial and agricultural weight of the upper South, and handed the new nation a capital at Richmond, barely a hundred miles from Washington. The 71/29 split was not a pre-war baseline. It was already the post-Sumter reality, the South at its strongest.` },
      { pill: '/war-civil-war/off-the-battlefield/road-to-war', plabel: `The Road to War` },
      { p: `The Confederacy also had one advantage that none of those numbers capture: it only had to survive. The North had to win. The South could “win” simply by not losing, by hanging on long enough and bleeding the North badly enough that the Northern public gave up and let the eleven states go. A draw was a Confederate victory. To make a draw happen, the Union had to do the genuinely hard thing: invade, conquer, and garrison a territory comparable in size to all of Western Europe. The South had to do the easier thing: endure, and outlast the enemy’s patience.` },
      { p: `Fighting on home ground sharpened that advantage two ways. The South could use interior lines, the shorter routes that run inside your own territory, which let you shift troops quickly from one threatened point to another, like a defender moving across the middle of a circle. The Union, attacking from outside, had to operate on exterior lines, the long way around the rim. Shifting a Northern army from one front to another often meant a vast detour the South could short-cut. And the South was defending its own soil, with shorter supply lines and the home-field knowledge that comes with it.` },
      { p: `The South had one more reason for confidence, and it sat outside the battlefield entirely. Southern leaders believed cotton was so essential to the mills of Britain and France that those powers would have to break any Union blockade to get it, that “King Cotton” would drag Europe into the war on the Confederate side. It was a bad bet (Britain happened to be sitting on a cotton surplus in 1861), but in 1861 it shaped Southern nerve.` },
      { pill: '/war-civil-war/off-the-battlefield/cotton-diplomacy', plabel: `Britain, France & Cotton` },
      { p: `The numbers favored the North. The nature of the task, conquer a continent versus simply refuse to die, partly evened it out. The Union’s problem was never beating the Confederate army on a given afternoon. It was beating, occupying, and holding an entire country the size of Western Europe, and persuading its own people to pay for it, year after year, in blood. Almost nobody, on either side, understood that yet.` },
      { h: `Building armies in a hurry`, eyebrow: `From almost nothing` },
      { p: `The United States Army that was supposed to put down a continental rebellion was tiny. At the start of 1861 the Regular Army (the full-time, professional, peacetime force) numbered only about 16,000 men in the entire country. And most of them weren’t even gathered anywhere useful; they were scattered in tiny posts out on the western frontier, guarding wagon routes and watching for raids. The Confederacy had it even leaner in one sense: it had no regular army at all. Every Confederate regiment had to be raised from absolute scratch.` },
      { p: `So both sides had to invent armies, fast, almost from zero. The basic building block was the regiment, a unit of about 1,000 men at full strength (usually fewer once disease and desertion went to work). The way they actually got built in 1861 tells you everything about how amateur this all was. A prominent local man, a lawyer, a merchant, a politician with a name people knew, would stand up in his town and raise a regiment from his own neighbors. The men would frequently elect their own officers, voting for the company captain the way you’d vote for a club president; the state governor then formally appointed the regimental officers. Units often supplied their own uniforms and sometimes their own weapons. The result was glorious chaos: regiments in every color and cut, armed with whatever was at hand, led by men whose qualification was popularity rather than training.` },
      { p: `Three days after the bombardment of Fort Sumter (the federal fort in Charleston harbor whose fall on April 13, 1861, opened the war, its garrison marching out the next day), Lincoln made his first move to fill that gap. On April 15, 1861, he issued a proclamation calling for 75,000 militia. (Militia are citizen-soldiers called up for a short term of service, as opposed to the full-time regulars.) The men were to serve 90 days, three months, and Lincoln summoned Congress into special session for the Fourth of July. Their first stated job: to “repossess” the federal property the seceded states had seized.` },
      { pill: '/war-civil-war/naval/fort-sumter', plabel: `Fort Sumter` },
      { p: `Why ninety days? Partly because an old law capped this kind of call-up at three months. But also because almost everyone assumed the war would be over by then. Ninety days felt generous. The paperwork itself was built on the assumption of a short war, which is why, when the first Union army marched toward its first big battle that July, its soldiers’ enlistments were running out underneath it.` },
      { p: `These were green troops on both sides, citizen-volunteers who had been drilling for a few weeks, led by amateur officers, neither trained nor scaled for the war that was actually coming. The two armies that would collide in July 1861 were, in the plain words of the time, “very green recruits.” The hard skill of running an army of hundreds of thousands, feeding it, moving it, keeping it from dying of dysentery before it ever saw the enemy, had to be learned the expensive way, in the field.` },
      { h: `Scott and the “Anaconda”`, eyebrow: `The slow war` },
      { p: `In all the noise of 1861, one professional soldier was thinking about the war as a single, continent-sized problem, and the country mocked him for it.` },
      { p: `He was General-in-Chief Winfield Scott, the senior officer of the U.S. Army. (The General-in-Chief is the top uniformed commander, not the commander-in-chief, who is the civilian president.) Scott was a genuine legend, a hero of the War of 1812 and the Mexican–American War. He was also, by 1861, seventy-four years old, heavy, and so infirm he could barely mount a horse. But his mind was clear, and it was working on a scale nobody around him wanted to hear.` },
      { p: `In early May 1861, first in a letter to Major General George B. McClellan on May 3, then in a fuller version dated May 21, Scott sketched out a strategy. It had two parts. One: a strict naval blockade of every Confederate port, sealing the South off from the world by sea. Two: a powerful army column, Scott proposed perhaps 80,000 men, driving straight down the Mississippi River to split the Confederacy in two and cut its western states off from its eastern ones. The whole idea was to envelop and strangle the South economically, to squeeze it until it gave up, in Scott’s own framing, to “bring them to terms with less bloodshed than by any other plan.” It was a strategy of patient pressure, not of one glorious knockout battle.` },
      { p: `The country hated it. Critics jeered that it was too slow, too passive, too cowardly, a plan that would take years. Opponents likened it to the coils of an anaconda, the great snake that suffocates its prey by slowly squeezing, and the sneering nickname stuck: the “Anaconda Plan.” The press piled on; the *Chicago Tribune* ran it down as a “Torpid Anaconda.” What the public wanted instead could be chanted in three words, “On to Richmond!”, a fast, glorious march on the new Confederate capital that would end the whole thing in an afternoon. The mood of 1861 was action, and a wheezing old general talking about blockades and river campaigns measured in years was exactly the wrong music. (The “Anaconda Plan” was never an official, adopted master-plan; it was Scott’s proposal, mocked into a nickname.)` },
      { p: `Scott didn’t last the year. Aged and ailing, and elbowed aside by younger men hungry for the offensive, he retired on November 1, 1861, and the dashing McClellan replaced him as General-in-Chief. He left office a laughingstock.` },
      { fig: '/war-img/improvising-a-war-fig2-winfield-scott.jpg', cap: `General-in-Chief Winfield Scott, the old hero of 1812 and Mexico, photographed in uniform around the start of the war. By 1861 he was seventy-four, heavy, and could barely sit a horse, and the country laughed at his slow strangle-the-South plan. He turned out to be right.`, credit: `Mathew Brady studio, New York · c. 1861 · Library of Congress / Wikimedia Commons · public domain` },
      { h: `The blockade`, eyebrow: `The patient weapon` },
      { p: `If “On to Richmond!” was the war the public wanted, the blockade was the war Scott was actually describing, and Lincoln reached for it almost immediately, days into the fighting.` },
      { p: `On April 19, 1861, Lincoln issued a proclamation declaring a blockade of the seceded states: South Carolina, Georgia, Alabama, Florida, Mississippi, Louisiana, and Texas. On April 27 he extended it to add Virginia and North Carolina. On paper, the entire Confederate coast was now to be sealed off from the world.` },
      { p: `On paper. Because the task was staggering and the means weren’t there. The Confederate coastline ran roughly 3,500 miles, pocked with dozens of ports, river mouths, and inlets, and the U.S. Navy in 1861 was nowhere near big enough to actually plug it. For a long time the blockade was a legal declaration far more than a physical reality, a line drawn on a chart that the Navy spent years growing into.` },
      { p: `It also came with a diplomatic snag. By proclaiming a “blockade,” rather than simply announcing he was closing his own country’s ports, Lincoln implicitly treated the Confederacy as a belligerent under international law: a recognized warring party with legal rights, rather than simply a band of domestic rebels. That mattered for the question of whether Europe would recognize the South, and it’s a thread that runs through the cotton-diplomacy story.` },
      { p: `The blockade was the patient, unglamorous half of the war, the opposite of “On to Richmond.” It promised no quick triumph, no flag planted on Richmond by summer. It promised instead a slow tightening of the noose over years: cutting off the South’s ability to sell its cotton and buy the guns, machinery, and medicine it couldn’t make for itself. It was strangulation, not a knockout. In April 1861, almost nobody wanted that war. It was the war they got.` },
      { pill: '/war-civil-war/off-the-battlefield/ironclads', plabel: `Ironclads & the Blockade` },
      { h: `The border states`, eyebrow: `The prize in the middle` },
      { p: `There were slave states that did not secede, and in 1861 they were arguably the most important ground in the war, not for sentiment but for cold strategy.` },
      { p: `Border states were the slaveholding states that stayed in the Union: Kentucky, Maryland, Missouri, and tiny Delaware. They sat in the gap between North and South, and what they held was decisive: railroads, river crossings, manpower, and the physical approaches to Washington itself and to the Ohio and Mississippi rivers. Losing them could have flipped the whole strategic problem from merely hard to nearly impossible. This wasn’t a matter of which side they felt loyal to. It was geography and logistics, and Lincoln understood it as clearly as he understood anything.` },
      { p: `He understood it so clearly that he put it in writing, in a private letter to Senator Orville H. Browning on September 22, 1861, in words that have become the single clearest statement of his 1861 strategy:` },
      { p: `“I think to lose Kentucky is nearly the same as to lose the whole game. Kentucky gone, we can not hold Missouri, nor, as I think, Maryland. These all against us, and the job on our hands is too large for us.” — Abraham Lincoln`, q: true },
      { p: `Lose Kentucky, he was saying, and you lose Missouri and Maryland after it; lose all three, and the war is simply too big to win. He played the most delicate of them with great care.` },
      { p: `Kentucky tried to sit the war out. On May 20, 1861, Governor Beriah Magoffin declared the state neutral, refusing to send troops to either side. It was a strategic tightrope, and Lincoln, instead of stomping on it, handled Kentucky with enormous care. He declined to force the issue, declined to march in, declined to give either side an excuse to call him the aggressor. He waited.` },
      { p: `His patience paid off when the Confederacy lost its nerve and moved first. On September 4, 1861, the Confederate general Maj. Gen. Leonidas Polk (South) marched troops into Columbus, Kentucky, violating the neutrality. It was a blunder. It let the Union respond as the defender of Kentucky rather than its invader: Brigadier General Ulysses S. Grant seized Paducah two days later, on September 6, and the Kentucky legislature, furious at the Confederate move, ordered only the Confederates out. The neutrality broke, and it broke toward the Union. Lincoln had won Kentucky largely by refusing to grab for it.` },
      { p: `Maryland was more urgent and more simply solved: it wrapped around Washington, D.C., on three sides, so losing it would have left the national capital an island in hostile territory. Lincoln moved hard to hold it, including suspending habeas corpus (the legal right that stops the government from jailing you without showing cause before a court) along the vital rail line so he could arrest secessionists without the usual process. Missouri controlled where the Missouri and Mississippi rivers met and held the big federal arsenal at St. Louis, and Missouri, unlike the others, was settled by force, the state’s pro-secession governor having raised a pro-Confederate militia of his own. That is where the war’s second front opens.` },
      { fig: '/war-img/improvising-a-war-fig3-secession-map.jpg', cap: `The country splits apart, 1860 to 1861. Dark red states seceded before Fort Sumter (the lower South), bright red went after (the upper South), and the blue states stayed in the Union. The four loyal slave states (Kentucky, Maryland, Missouri, Delaware) sit in yellow, right in the gap, which is exactly why Lincoln guarded them so carefully. Gray is unsettled territory.`, credit: `Júlio Reis · 2007 · Wikimedia Commons · CC BY-SA 3.0` },
      { h: `A second front opens`, eyebrow: `The war goes continental` },
      { p: `While the country fixated on the hundred miles between Washington and Richmond, the war quietly became continental, and it did so out in Missouri, in the summer of 1861.` },
      { p: `The biggest battle west of the Mississippi that year was Wilson’s Creek, fought on August 10, 1861, about ten miles southwest of Springfield, Missouri. A Union force of roughly 5,400 men under the aggressive Brig. Gen. Nathaniel Lyon (North) attacked a combined Confederate and Missouri State Guard army (the state’s pro-Confederate militia, the one the secessionist governor had raised) of more than 10,000 under Brig. Gen. Benjamin McCulloch (South) and Maj. Gen. Sterling Price (South). Lyon was badly outnumbered, and in the fighting he was killed, the first Union general to die in the Civil War. Tactically, the Confederates won the field.` },
      { pill: '/war-civil-war/trans-mississippi/wilsons-creek', plabel: `Wilson’s Creek` },
      { p: `But it is what the battle meant that matters here. Even though the South won the field, Lyon’s reckless, headlong campaign had already done the larger strategic job: it kept Missouri from falling into the Confederacy. People started calling Wilson’s Creek “the Bull Run of the West,” and the nickname carried the real lesson. This war was not going to be decided on one front along the Richmond–Washington line. It had just sprouted a second front, a thousand miles away, in its very first summer. The map of the war was the whole country.` },
      { p: `Missouri also produced the year’s sharpest collision between strategy and slavery, and it came from a Union general getting ahead of his president. On August 30, 1861, Maj. Gen. John C. Frémont (North), commanding in Missouri, declared martial law (military rule, suspending the normal civil courts and authority) and issued his own proclamation: he would confiscate the property of armed rebels and free the people they held as slaves. This was sixteen months before Lincoln’s own Emancipation Proclamation, and it was politically explosive, because Lincoln feared that freeing slaves now, by military order, would terrify the border states (Kentucky above all) into bolting to the Confederacy. He asked Frémont to soften it. Frémont refused unless ordered. So Lincoln publicly overruled him on September 11, 1861, rescinding the emancipation order.` },
      { pill: '/war-civil-war/off-the-battlefield/freedom-struggle', plabel: `The Freedom Struggle` },
      { p: `Lincoln did not object to the idea of freeing enslaved people. He objected to the timing, and the timing was governed entirely by the need to hold Kentucky. In 1861, military necessity outranked emancipation in his calculus: the right end, at the wrong moment. The cause the war was being fought over was already sitting right on the surface of the strategy, and the strategy was making it wait.` },
      { pill: '/war-civil-war/off-the-battlefield/emancipation', plabel: `Emancipation` },
      { h: `The day the dream died`, eyebrow: `First Bull Run` },
      { p: `And then came the day the whole illusion of 1861 died on a single battlefield.` },
      { p: `The battle was First Bull Run (the Confederates called it First Manassas), fought on July 21, 1861, near Manassas, Virginia. It was the first major battle of the war, and the public approached it as a spectacle rather than a slaughter. Washington civilians, U.S. senators among them, packed picnic baskets and rode out with opera glasses to watch the Union army win a quick, glorious victory and start the march to Richmond. They expected an afternoon’s entertainment with a happy ending.` },
      { p: `What they got was a rout. The green Union troops, many of them the very 90-day men from Lincoln’s April call, their enlistments expiring as they marched, broke under Confederate pressure and fled back toward Washington in a panicked, tangled mess, picnickers and soldiers streaming up the roads together. The casualties were shocking for 1861 (though they would look almost trivial by the war’s later standards): roughly 2,900 Union and 2,000 Confederate, with something like 850 men killed all told. These are approximate, the exact counts vary by source, but the magnitude was the point.` },
      { pill: '/war-civil-war/eastern/bull-run', plabel: `First Bull Run` },
      { fig: '/war-img/improvising-a-war-fig4-bull-run-rout.jpg', cap: `“The Stampede from Bull Run,” drawn on the spot for the illustrated press. Soldiers, wagons, and the sightseers who had ridden out to watch all tangle together in a panicked scramble back toward Washington. This is the afternoon the dream of a short war died.`, credit: `Frank Vizetelly · 1861 · New York Public Library / Wikimedia Commons · public domain` },
      { p: `Bull Run changed the country’s entire understanding of what the war would be. It dispelled, in one afternoon, the illusion of a short conflict. The “picnic battle” turned into the day the 90-day dream died, for the public, for the press, and for Lincoln. The men who had marched out singing about a three-month war marched back having learned, at a cost of hundreds of lives, that there wasn’t going to be one. And the lesson was instantly written into law: on July 22 and July 25, 1861, the day after the battle and the days just after, Congress authorized the President to raise up to 500,000 volunteers on three-year (or war-duration) enlistments. In four days the country swapped its 90-day militia for the framework of a long-war army.` },
      { p: `Back in the spring, Winfield Scott had been mocked for proposing a patient, years-long strategy of strangulation while everyone else chanted “On to Richmond!” Bull Run was “On to Richmond!”, the quick, decisive march the public demanded, and it ended in a humiliating wreck. The lesson the rout taught was exactly the one Scott had been laughed out of the room for teaching: this was going to be a long, grinding, continental war, and you could not win it with one glorious charge. His two pillars were the real shape of victory. The blockade tightened, slowly, for years; and the Mississippi was finally severed when the fortress city of Vicksburg fell in July 1863, splitting the Confederacy exactly as Scott had drawn it. None of that meant the war could have been short if only someone had been smarter. The length was the war slavery made necessary, and it took a defeat at Bull Run to make the country admit it.` },
      { pill: '/war-civil-war/western/vicksburg', plabel: `Vicksburg` },
      { h: `Two presidents at war`, eyebrow: `Two presidents` },
      { p: `The two men who had to direct all of this, the manpower, the plans, the border-state chess, the long war nobody wanted, had never run a war in their lives. And the paradox of 1861 is that the side with the better-credentialed war president was the South.` },
      { p: `On paper, Jefferson Davis was almost perfectly built for the job. He was a West Point graduate (Class of 1828, from the U.S. Army’s officer academy), a U.S. Army officer in his youth, and a genuine combat hero of the Mexican–American War, wounded in the foot at the Battle of Buena Vista in 1847. He had been U.S. Secretary of War from 1853 to 1857, running the United States Army and championing its modernization, and he’d been a U.S. senator, all of it in the service of the slaveholding South whose cause he had spent his Senate career defending. Elected provisional Confederate president in February 1861, he was a soldier-statesman with deep military knowledge. Davis had wanted a military command, not the presidency. He’d rather have been a general. And as president he tended to involve himself deeply, often too deeply, in military matters, keeping tight personal control of strategy and, before long, feuding with his own generals.` },
      { p: `Abraham Lincoln had almost none of that. His entire military résumé was a brief, combat-free stint in the Illinois militia during the Black Hawk War of 1832 (a small conflict with Native American forces on the Midwestern frontier), service so uneventful that, though he was elected captain of his company, he joked his only battles had been with mosquitoes. He was a self-taught prairie lawyer who had never commanded anything. But he had a particular kind of mind: fast, analytical, and humble enough to learn out loud. He checked books on military strategy out of the Library of Congress and read them. He studied his generals’ wins and losses, learned from his own mistakes, and applied a relentless, hard-edged common sense to problems the West Pointers overcomplicated. Historians broadly agree on the verdict: despite the enormous experience gap, Lincoln became the more effective commander-in-chief of the two.` },
      { p: `Their command setups in 1861 reflected the two men. Lincoln sat above the aging General-in-Chief Winfield Scott, soon replaced by McClellan, and he would cycle through general after general for years before he finally found Ulysses S. Grant. Davis, the soldier-president, kept the strategy close to his own chest and worked through several commanders, relationships that were prickly almost from the start. Davis’s early strength was a coherent doctrine, the “offensive-defensive”: use those short interior lines to defend the South’s own territory, but strike north whenever a real opening appeared. His early weakness was the micromanaging and the feuding. Lincoln’s early strength was political-strategic: the border-state restraint and the overruling of Frémont, both of which subordinated military romance to cold necessity. Both men shared the era’s great error: both badly under-planned for length. The 90-day call and the universal short-war assumption were the mistake they made together.` },
      { fig: '/war-img/improvising-a-war-fig5a-lincoln.jpg', cap: `Abraham Lincoln in 1861, the self-taught prairie lawyer whose entire military record was a mosquito-bitten stint in the Black Hawk War. He would teach himself how to run a war out loud, and become the better commander-in-chief of the two.`, credit: `Mathew Brady · 1861 · Library of Congress / Wikimedia Commons · public domain` },
      { fig: '/war-img/improvising-a-war-fig5b-davis.jpg', cap: `Jefferson Davis around 1861, the new Confederate president. On paper he was built for the job (West Point, a Mexican War wound, a turn as U.S. Secretary of War), and would rather have been a general. He raised an army for a republic founded to keep four million people enslaved.`, credit: `Unknown photographer · c. 1861 · Library of Congress / Wikimedia Commons · public domain` },
      { p: `The two presidents were not, though, mirror images. They were raising armies for opposite causes, and the causes were not morally equivalent. Davis was raising an army to defend a republic founded to keep four million people enslaved, the Confederacy’s reason for existing, stated plainly in its own founding. Lincoln was raising an army to preserve the Union, a war that, as Frémont’s overruled order already hinted, would in time become a war to end slavery itself. One of them was fighting to keep human beings as property; the other was on his way, step by step, to setting them free.` },
      { pill: '/war-civil-war/off-the-battlefield/lincolns-rise', plabel: `Lincoln’s Rise & the Election of 1860` },
      { p: `So 1861 closed with the illusion gone. Two presidents who had each expected a short, contained war now understood, one of them faster than the other, that they were locked into a long one: a continental war of conquest on one side and a war of survival on the other, fought over the ownership of human beings, with the armies still being invented even as they marched. They had improvised their way into it. Now they would have to learn how to fight it.` },
    ],
    meanwhile: {
      region: `the war at large, 1862`,
      title: `The Limited War Ends`,
      body: `After Bull Run, both sides finally stopped pretending. Through 1862 the war shed the last of its illusions (short enlistments, gentlemen’s rules, slavery left untouched) and hardened into the total, grinding war it was always going to be, as the North turned from “restore the Union as it was” toward a war that would have to break slavery to win.`,
    },
  },
}

export default function ImprovisingAWarThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="improvising-a-war"
      battleName="Improvising a War"
      theatreId="howfought"
      battleId="mil-1861"
      theatreHref="/war-civil-war/how-the-war-was-fought"
      accent={WAR_ACCENT}
      heroImage="/war-img/improvising-a-war-hero.jpg"
      heroPalette={["#3a342a","#23201a","#0a0806"]}
      heroCredit={`“Scott’s Great Snake” (the Anaconda Plan) · J.B. Elliott, Cincinnati · 1861 · Library of Congress · public domain`}
      heroFocus="center 42%"
      heroScale={1.04}
      endHref="/war-civil-war/how-the-war-was-fought"
      endKicker={`Now they had to learn to fight it`}
      endLabel={`Back to the Civil War story`}
    />
  )
}
