'use client'

// The Siege of Charleston (March 29 – May 12, 1780), battle sections ·
// American Revolution. The catastrophe battle: Britain's bet on the South, the
// methodical siege that closed every door, and the honors refused. Produced
// through the war content pipeline (audits/war-content-pipeline.md): fact pack
// → author → critic gates (fact-check + storytelling + newcomer-clarity +
// framing, parallel) → reconcile → revise. Data only; rendered by the shared
// <BattleSectionReader>. House voice: no em-dashes; side-tags combatants only,
// once on first mention per section. HANDLE-WITH-CARE framings per the final:
// captured framed "more than 5,000" with the regulars range, never a clean
// 5,466 soldier count; the magazine explosion "perhaps two hundred"; the
// "severest blow" and Clinton boast dropped; "Tarleton's quarter" / "Bloody
// Ban" FIREWALLED to the Waxhaws handoff (the prose stops at "ran them down");
// no surrender-ceremony or prison-hulk image invented; the six hulk ship names
// dropped. The final's locator arrows are not renderable in the locator block
// contract; the movement lines live in the captions instead (Saratoga
// precedent). The tactical peninsula locator opens Sections 1 AND 2 per the
// final (Sections 1–2 + dossier), with the optional southern-theater context
// inset folded into its caption as an off-frame note (the locator block draws
// no inset panel); the Cooper-back-door locator sits mid-Section 2, opening
// the Monck's Corner beat it maps. The final's Locator-1 frame is widened
// slightly south and west so its own listed dots (the Simmons Island landing,
// Drayton Hall) sit inside the frame.
// Sources: audits/war-pipeline/rev-charleston-final.md (+ rev-charleston-factpack.md).

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import type { Block } from '@/components/mode/battle-reader'

// Locator 1 · tactical: the peninsula and the harbor. Opens Sections 1 AND 2
// per the final; each section page stands alone. The strategic
// southern-theater context (Savannah, Camden, the Waxhaws, Clinton's coastal
// passage) rides the caption tail as an off-frame note.
const TACTICAL_LOCATOR: Block = {
  locator: {
    eyebrow: 'The ground · February–May 1780',
    caption: 'The whole battle is geography. Charleston sits on a peninsula between two rivers, with only one land door, the neck at the top, and Lincoln\'s army fortified the door. Clinton would not storm it; he landed thirty miles south, worked up the sea islands and the Ashley\'s west bank for six weeks, crossed at Drayton Hall, and dug his way down the Neck. Arbuthnot\'s fleet ran past Fort Moultrie into the harbor in April, closing the city to the sea. The only way out left was north, across the Cooper. Off the frame: Savannah, taken in December 1778, lies a hundred miles down the coast, the fleet\'s February rendezvous on Clinton\'s long winter passage from New York; inland to the northwest sit Camden, the next disaster (August 16, 1780), and the Waxhaws, near the North Carolina line, where this story hands off (May 29).',
    frame: { lonMin: -80.24, lonMax: -79.76, latMin: 32.53, latMax: 32.94 },
    states: [
      { name: 'South Carolina', tone: 'focus', label: 'SOUTH CAROLINA', labelLon: -80.215, labelLat: 32.925, labelSize: 11 },
    ],
    labels: [
      { text: 'ASHLEY RIVER', lon: -79.995, lat: 32.825, kind: 'water', size: 9, anchor: 'end' },
      { text: 'COOPER RIVER', lon: -79.905, lat: 32.865, kind: 'water', size: 9, anchor: 'start' },
      { text: 'ATLANTIC OCEAN', lon: -79.86, lat: 32.585, kind: 'water', size: 10, anchor: 'middle' },
    ],
    dots: [
      { name: 'Charleston', date: 'the city on the lower peninsula', lat: 32.776, lon: -79.931, heavy: true, anchor: 'start', dy: 14, dateBelow: true },
      { name: 'The Hornwork', date: 'the American line across the Neck', lat: 32.788, lon: -79.937, heavy: true, anchor: 'end', dy: 0, dateBelow: true },
      { name: 'The siege parallels', date: 'ground broken Apr 1', lat: 32.800, lon: -79.937, color: '#8a8175', anchor: 'start', dy: -10, dateBelow: true },
      { name: 'Fort Moultrie, Sullivan\'s Island', date: 'fell without a shot, May 7', lat: 32.760, lon: -79.857, anchor: 'start', dy: 6, dateBelow: true },
      { name: 'The harbor bar', date: 'Arbuthnot\'s run past the fort, Apr 8', lat: 32.710, lon: -79.830, color: '#8a8175', anchor: 'end', dy: 8, dateBelow: true },
      { name: 'Fort Johnson', date: 'the British battery on James Island', lat: 32.690, lon: -79.899, anchor: 'end', dy: -6, dateBelow: true },
      { name: 'Drayton Hall', date: 'the Ashley crossing, Mar 29', lat: 32.870, lon: -80.075, anchor: 'start', dy: -6, dateBelow: true },
      { name: 'The British landing', date: 'Simmons Island, Feb 11', lat: 32.577, lon: -80.170, anchor: 'start', dy: -8, dateBelow: true },
    ],
  },
}

// Locator 2 · strategic: the Cooper River back door (Section 2). The escape
// road and Tarleton's two strokes live in the caption (arrows are not
// renderable in the locator contract).
const BACKDOOR_LOCATOR: Block = {
  locator: {
    eyebrow: 'The back door · April–May 1780',
    caption: 'The last way out ran north: out of the city, across the Cooper River, up the roads toward the Santee, and away. Huger\'s cavalry held that road open at Monck\'s Corner, thirty miles up the river. Tarleton hit them at three in the morning on April 14 and took the door, and the horses he badly needed; when the remnant regrouped on the Santee, he destroyed it again at Lenud\'s Ferry on May 6. After that there was no organized American force outside Charleston at all.',
    frame: { lonMin: -80.2, lonMax: -79.5, latMin: 32.7, latMax: 33.4 },
    states: [
      { name: 'South Carolina', tone: 'focus', label: 'SOUTH CAROLINA', labelLon: -80.16, labelLat: 33.37, labelSize: 11 },
    ],
    labels: [
      { text: 'COOPER RIVER', lon: -79.95, lat: 33.04, kind: 'water', size: 9, anchor: 'end' },
      { text: 'SANTEE RIVER', lon: -79.93, lat: 33.345, kind: 'water', size: 9, anchor: 'middle' },
    ],
    dots: [
      { name: 'Charleston', date: 'the trapped army', lat: 32.776, lon: -79.931, heavy: true, anchor: 'start', dy: 10, dateBelow: true },
      { name: 'Monck\'s Corner / Biggin Bridge', date: 'Tarleton\'s night strike, Apr 14', lat: 33.196, lon: -80.013, heavy: true, anchor: 'end', dy: -6, dateBelow: true },
      { name: 'Lenud\'s Ferry', date: 'Tarleton again, May 6', lat: 33.305, lon: -79.675, heavy: true, anchor: 'end', dy: 8, dateBelow: true },
    ],
  },
}

const CHARLESTON_NARR: Record<string, Narr> = {
  'the-armada': {
    eyebrow: 'Charleston · The bet',
    title: 'The whole war on the South',
    blocks: [
      TACTICAL_LOCATOR,
      { p: 'By the end of 1779, the war in the North had gone nowhere. Five years in, Britain held New York City and not much else, France had come into the war on the American side, and George Washington\'s army could not be destroyed and would not go away. So Britain changed the board. It decided to win the war in the South.' },
      { p: 'The reasoning was not foolish. The southern colonies were rich: rice and indigo (a plant that yields a deep blue dye) were the export crops whose wealth helped finance the rebellion, and the ports that shipped them sat conveniently near the British sugar islands of the Caribbean. Better still, London believed the South was full of Loyalists (Americans loyal to the king) who would rise the moment a British army gave them cover, and then hold the reconquered ground themselves, so that Britain could roll the rebellion up colony by colony with only a thin garrison. There was even a proof of the idea. In December 1778 a small British force had taken Savannah, Georgia, and in October 1779 it held the city against a combined French and American siege that ended in a bloody allied failure. Benjamin Lincoln (American), the major general commanding the American forces in the South, had led the American half of that failed assault and fallen back to Charleston. Savannah\'s successful defense convinced the British commander in chief, Sir Henry Clinton (British), that the moment had come to go for the real prize.' },
      { p: 'The prize was Charleston, or Charles Town as it was then spelled: the largest and richest city in the South and the fourth largest in America, around 12,000 people, roughly half of them enslaved. It was the South\'s principal port and the seat of the rebel government in South Carolina. Take Charleston and the whole door to the South stood open.' },
      { fig: '/war-img/rev-charleston-french-map.jpg', cap: 'A French manuscript map of Charleston, its entrenchments, and the British siege of 1780. France had been in the war two years by now, and watched the southern campaign closely; this is a French hand drawing the city Britain was about to take.', credit: 'manuscript map · 1780 · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'Clinton sailed from New York on December 26, 1779, with about 8,500 troops and 5,000 sailors aboard some ninety transports, escorted by fourteen warships under Vice Admiral Marriot Arbuthnot (British), with Lord Cornwallis (British) as his second in command. And then the weather nearly destroyed the whole expedition before it ever reached Carolina. The winter of 1779 to 1780 was one of the worst of the century, the same "Hard Winter" that was freezing Washington\'s army at Morristown, and it fell on the fleet at sea. Storms scattered and battered the ships for five weeks on what should have been a ten-day run. An ordnance ship (carrying the army\'s heavy guns and stores) foundered and went down. One transport with about 200 Hessians aboard (German soldiers hired into British service) was blown clean across the Atlantic and fetched up in Cornwall, in England. And worst of all for what was coming, nearly all the cavalry and artillery horses died in the holds or were thrown overboard to lighten the laboring ships. A Hessian officer of the Jäger (light troops), Captain Johann Hinrichs, counted fifteen of his thirty-six days at sea as outright storm. Tarleton\'s cavalry (dragoons, mounted soldiers trained to fight from horseback) would step ashore in Carolina with no horses at all.' },
      { p: 'The fleet regrouped off Savannah at the start of February, and now Clinton\'s caution took over completely. He had been to Charleston before. In 1776 a British attempt on the city had been beaten off in humiliating fashion at the harbor mouth, and Clinton, who had been there, was not going to repeat it. He landed his army thirty miles south of the city, on Simmons Island (today Seabrook Island), on February 11 and 12, and then he simply refused to hurry. For six weeks the army worked its methodical way north through a maze of marsh and sea islands: across the Stono River, onto James Island by early March, through the Wappoo Cut, then up the west bank of the Ashley River. Hinrichs wrote of the country they crossed.' },
      { p: 'Through a wilderness of deep sand, marshland, and impenetrable woods where human feet had never trod! What a land to wage war in!', q: true },
      { p: 'On March 29 the army crossed the Ashley unopposed near Drayton Hall and walked down onto Charleston Neck, the strip of land at the top of the peninsula that was the city\'s only land door. Clinton had taken three months to move thirty miles, and he had not put a foot wrong. Now he stood on the one piece of ground from which Charleston could be besieged.' },
      { p: 'Inside the city waited Benjamin Lincoln and the entire Continental establishment in the South. He held the lines across the Neck with roughly 2,500 to 2,800 Continentals (the full-time paid regulars of the Continental Army), Carolinians and Georgians, soon joined by some 750 Virginians under Brigadier General William Woodford (American), who marched in on April 7 after a brutal forced march of some 800 miles from Morristown, arriving just in time to be trapped. Add 2,000 to 3,000 militia (part-time citizen soldiers) and armed townsmen, and Lincoln had perhaps 5,500 to 6,000 men behind a fortified line, fronted by a wet ditch and anchored at the gate by a strongpoint of tabby (a local concrete of oyster shells and lime, very hard) called the Hornwork. It was a respectable force. It was also, as the professional soldiers among them could see, in the wrong place.' },
      { p: 'For a moment, set the scene against a memory the city was very proud of. Four years earlier, on June 28, 1776, this same harbor had been the site of one of the Revolution\'s great early victories. A half-finished fort of palmetto logs on Sullivan\'s Island, the island on the north side of the harbor mouth, held by about 400 men under William Moultrie (American), had stood up to nine British warships for a whole day. The spongy palmetto logs swallowed the cannonballs instead of splintering, the fort\'s blue-and-crescent flag (Moultrie\'s own design) became the icon of southern resistance, and the British were kept out of the South for three years. Charleston\'s myth was built on that harbor. In 1780 the British were about to take the city by ignoring the harbor entirely, and the fort that had wrecked a fleet would change hands without firing a shot.' },
      { fig: '/war-img/rev-charleston-sullivans-1776.jpg', cap: 'The British fleet attacking the palmetto fort on Sullivan\'s Island, June 28, 1776, in a period print: the day Moultrie\'s spongy palmetto logs swallowed Sir Peter Parker\'s broadsides and kept the British out of the South for three years. Four years later the same harbor fell without a shot.', credit: 'period print · 1776 · Library of Congress / Wikimedia Commons · public domain' },
    ],
    meanwhile: { region: 'Savannah, Georgia', title: 'Where the bet was placed', body: 'The whole southern strategy rested on a single piece of evidence: that a British garrison could take a southern city and hold it. Savannah, taken in December 1778 and successfully defended a year later, was that evidence. It was also where Lincoln\'s bad year had started, with the failed allied assault of October 1779 that sent him back to Charleston to wait for what was coming. Britain read Savannah as proof the South could be conquered cheaply. The reading was about to be tested on a far bigger city.' },
  },

  'the-noose': {
    eyebrow: 'Charleston · The siege',
    title: 'Every door but one',
    blocks: [
      TACTICAL_LOCATOR,
      { p: 'A siege in the eighteenth century was not a battle so much as a piece of engineering, and Clinton was a master of it. On the night of April 1, the British broke ground about 800 yards from the American lines and dug their first parallel: a trench running parallel to the enemy works, so the diggers were never exposed broadside to the defenders\' guns. From a parallel, zigzag trenches called saps (dug at an angle to the enemy so no single cannon shot could sweep their whole length) creep forward toward the enemy, and then a second, closer parallel is dug, and the process repeats, the trenches walking steadily nearer until the attacker\'s guns can fire point-blank into the defense. This was the textbook reduction of a fortified place, slow and nearly bloodless and very hard to stop. Clinton, who had been beaten off this very ground in 1776, was now taking the city by arithmetic.' },
      { fig: '/war-img/rev-charleston-siege-plan.jpg', cap: 'The siege plan drawn under Clinton\'s chief engineer, James Moncrief: the parallel trenches creeping toward the American lines across the neck of the peninsula, the lines of fire of both sides, the ships drawn in the harbor. Clinton took the city by digging, not by storming, and this is the geometry of it.', credit: 'period manuscript plan · 1780 · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'It went almost exactly to the book. On April 8, Arbuthnot ran eight warships past Fort Moultrie on a flood tide and into the harbor, losing only a handful of men and one supply vessel, the whole passage taking well under two hours. The fort that had wrecked a British fleet in 1776 was simply sailed past in 1780. And the man it was named for was inside the lines to watch it happen: William Moultrie, the hero of the palmetto logs, could only listen to his own guns bark at ships that did not stop to fight them and slide past into the harbor he had once owned. The harbor was now British water, and the city could no longer be supplied or escaped by sea. The same day, Woodford\'s exhausted Virginians marched in, the last reinforcement to make it through. Two days later, on April 10, Clinton and Arbuthnot together summoned Lincoln to surrender. He refused, replying that duty and inclination alike pointed to defending the place to the last extremity. The next day the British batteries opened, and the bombardment of the city began.' },
      BACKDOOR_LOCATOR,
      { p: 'Now the trap had a single weak seam, and both sides knew where it was. The only escape route left to the American army ran north: out of the city, across the Cooper River on the eastern side of the peninsula, and up the roads beyond, toward the Santee River and away. That route was held open by Brigadier General Isaac Huger (American), with about 500 cavalry and militia posted thirty miles up the Cooper at Monck\'s Corner, where the road crossed at Biggin Bridge. Whoever held Monck\'s Corner held the back door. On the night of April 13, Banastre Tarleton (British) marched for it with his British Legion and Major Patrick Ferguson\'s light infantry (British), about 1,400 men. On the way they captured a letter that betrayed the American dispositions, and at three in the morning on April 14 they fell on Huger\'s camp without firing a warning shot. The surprise was total. A few dozen Americans were killed or wounded, sixty or seventy captured, and the rest, Huger among them, escaped on foot into the swamps. And Tarleton took the thing the expedition needed most. His own horses had gone overboard in the winter storms; now the Legion seized the American cavalry\'s mounts and rode out of Monck\'s Corner superbly horsed. The near door was shut.' },
      { p: 'A few days later, Cornwallis crossed to the east bank of the Cooper with more than 2,300 men, and the American outposts on that side folded back. Now the city was ringed on every side, by land and by water. The investment, the complete encirclement of a place under siege, was finished.' },
      { fig: '/war-img/rev-charleston-investment-map.jpg', cap: '"The Investiture of Charleston, with the position of each corps," a manuscript map drawn at the time: the city on its peninsula, the Ashley and Cooper Rivers on either side, the fleet in the harbor, and the British camps and lines drawn corps by corps. This is the noose, on paper.', credit: 'period manuscript siege map · 1780 · Library of Congress / Wikimedia Commons · public domain' },
      { p: 'This is the moment the siege of Charleston stops being a story about engineering and becomes a story about politics, and it is the heart of what happened to Benjamin Lincoln. A soldier in his position had two honest options. He could fight the siege out, or he could save the army, the irreplaceable thing, by marching it across the Cooper while the route was still open and abandoning the city. By the rules of his trade the second was the right answer: a city can be retaken, an army cannot be remade. But the civil government of South Carolina made the second option politically impossible. Governor John Rutledge had left the city around April 13 at Lincoln\'s own urging, taking several councilmen with him to keep a government alive in the state. But Lieutenant Governor Christopher Gadsden (American), the fierce Charleston radical who had designed the "DON\'T TREAD ON ME" rattlesnake flag, stayed, and he was utterly opposed to giving up the city. When Lincoln\'s council of war took up the question of evacuation around April 19 and 20, Gadsden was admitted to it along with members of the South Carolina Privy Council (the governor\'s executive advisers), and one of them, Thomas Ferguson, made the threat that defined the siege: that if the Continentals tried to withdraw, the townspeople would open the gates to the British themselves and help attack the retreating army in its boats. There was the whole geometry of Lincoln\'s bind in a single sentence: by his trade the army was the irreplaceable thing, and he was being told that the act of saving it would turn the city he was defending into an enemy at his back, his own boats fired on by the people he had stayed to protect. The generals McIntosh and Moultrie wanted the army out. So did Louis Duportail (American), a French officer serving as Washington\'s own chief engineer, who had slipped into the city in late April; he took one look at the works, pronounced them untenable, and urged evacuation. That was the professional case closed: Washington\'s own engineer, brought in to judge, said get the army out. It changed nothing. The same government that would not let the army leave had also refused Lincoln\'s plea, weeks earlier, to arm enslaved men for the defense, as John Laurens had proposed the year before; in a city where half the population was enslaved, the men on the council who would not free their army to save it were also the men who would not arm the people they owned. Pressed from both sides, with a government threatening to turn on him if he saved his army, Lincoln stayed.' },
      { p: 'On April 21, Lincoln made one professional offer: he proposed to surrender the city if the garrison could march out with the honors of war and go free. The honors of war were the courtesies a respected enemy was granted on surrender, marching out under their own colors, drums beating, the dignity of soldiers rather than the shame of captives. Clinton, holding every card, refused flatly. A spirited American sortie before dawn on April 24, Virginians and Carolinians striking at the British trenches, drew blood and changed nothing; it was the only offensive blow the garrison struck in the entire siege.' },
      { p: 'Then, in the first week of May, everything fell at once. On May 6, the American cavalry had regrouped under two American colonels, Anthony Walton White and William Washington, about forty miles north, on the bank of the Santee River at Lenud\'s Ferry. Tarleton found them resting and destroyed them a second time: thirty or forty killed and wounded, dozens captured, the commanders escaping by swimming the river. Now there was no organized American force outside Charleston at all. On May 7, a Royal Navy landing party of some 500 sailors and marines summoned Fort Moultrie. Its garrison of about 200 men was cut off, outnumbered, and beyond any rescue, and it surrendered without firing a shot. The shrine of 1776 fell to a politely worded demand, and the British renamed it for their admiral. On May 8, Clinton summoned Lincoln to surrender unconditionally. The talks over the next two days broke on the same two points as before, the status of the militia and the honors of war, with Lincoln still asking for the full honors and Clinton still refusing them.' },
      { p: 'When the truce lapsed around nine o\'clock on the night of May 9, both sides opened up with everything they had. By Moultrie\'s count it was the heaviest cannonade of the whole siege, something like 180 to 200 guns firing through the night, shells crossing overhead and magazines and ammunition chests blowing up along the lines. Moultrie left the unforgettable record of it.' },
      { p: 'it was a glorious sight, to see them like meteors crossing each other, and bursting in the air; it appeared as if the stars were tumbling down... it was a dreadful night!', q: true },
      { p: 'And in the siege\'s final days the bombardment stopped being beautiful and started burning the town. The British began firing hot shot, cannonballs heated red in furnaces to set wooden buildings alight, and fires caught among the houses. From the lines the men could watch the glow spread roof to roof down toward the wharves, the same families who had crowded the streets all spring now beating at their own burning homes in the dark with the British guns still working. By morning the closest parallel was at the very lip of the lines, the wet ditch was drained, and the city had nothing left to hold with and no one left who wanted it held. That was what finally broke the city\'s will. The leading citizens of Charleston, Christopher Gadsden among them, the same men who had refused to let the army leave, petitioned Lincoln to surrender on whatever terms he could get. The militia in the garrison sent word that the British terms were acceptable to them. On the evening of May 11, Lincoln reopened negotiations. There was nothing left to defend the city for, and no one left who wanted him to try.' },
      { pill: '/war-revolution/off-the-battlefield/civil-war-among-themselves', plabel: 'Loyalist against Patriot: the war between Americans, told whole' },
    ],
    meanwhile: { region: 'The Cooper River', title: 'The horses', body: 'The detail that decided the cavalry war was a stable, not a battle. Tarleton\'s dragoons had arrived in Carolina with no mounts, their horses dead at sea, and a cavalryman without a horse is just a tired man with a sword. At Monck\'s Corner on April 14 they took the American cavalry\'s horses and became, overnight, the best-mounted corps in the South. Everything Tarleton did afterward, Lenud\'s Ferry, the run to the Waxhaws, the terror of the backcountry, he did on Carolina horses captured at the back door of Charleston.' },
  },

  'the-cased-colors': {
    eyebrow: 'Charleston · The surrender',
    title: 'The honors refused',
    blocks: [
      { p: 'Around eleven in the morning on May 12, 1780, the Continental troops marched out of the Hornwork at the gate and laid down their arms between the lines. And here Clinton drove home the one piece of deliberate cruelty in an otherwise coldly professional siege. He refused them the honors of war, the precise humiliation Yorktown would one day answer. The colors were cased, furled and sheathed in their covers rather than flown, and the drummers were forbidden to beat a British march (to play a tune from the victor\'s own repertoire, the traditional salute that said the beaten enemy had fought with honor), the gesture by which a victor acknowledged a brave foe. It was a calculated humiliation, the formal denial of the courtesies owed a respected enemy. By Moultrie\'s account the drums were permitted only a Turkish march, the nothing-tune that said nothing. British and Hessian grenadiers lined the works, and the British flag went up over the Hornwork. The militia turned in their arms over the following days and were paroled (released on their word of honor not to take up arms again until formally exchanged for a British prisoner) to their homes; the Continentals went into captivity. More than 5,000 men had surrendered.' },
      { p: 'That number needs care, because it is the headline of the worst American defeat of the war and it is easy to get wrong. Clinton\'s official return counted 5,466 prisoners, but the figure is misleading: the return swept in militia, armed citizens, and sailors along with the regulars, and the genuinely effective Continentals numbered closer to 2,650. The honest statement is the one that holds: more than five thousand men were taken, the entire Continental army in the South, about half of them regulars, along with seven generals, more than 300 guns, some 5,000 muskets, fifteen stands of colors, and three frigates of the little Continental Navy squadron trapped in the harbor. It was the largest surrender of American troops in the whole war, a military disaster sitting inside a political one.' },
      { p: 'And then, three days after the city fell, came the deadliest single hour of the entire affair, and nobody had been shooting at anyone. On May 15, British work parties were stockpiling thousands of captured muskets in a brick magazine near the main powder store. American officers had warned that many of the surrendered muskets were still loaded; the warnings were ignored. One musket went off in someone\'s hands, the loose powder caught, and the magazine blew up. The explosion touched off stored cartridges and thousands of muskets, threw burning debris across the neighborhood, and set fire to the barracks, the jail, and the house of correction nearby. Bodies were flung across the streets; loaded muskets kept cooking off in the wreckage and hitting the men who came to help. Captain Johann Ewald (British), a Hessian officer a hundred yards away, recorded charred arms and legs scattered in every direction, a deplorable sight. A British officer of the 42nd, Captain John Peebles, called it a melancholy accident born of "Very Strange Management, to Store up loaded Arms in a Magazine, of Powder." The death toll was disputed even at the time, running from near a hundred to rumors of three hundred; the figure usually printed is about 200 killed, British and Hessian soldiers, American prisoners, townspeople, and the inmates of the burning jail. Perhaps two hundred people, in other words, more than had died on both sides in the whole six-week siege.' },
      { p: 'What happened to the prisoners afterward loaded the rest of the southern war with grievance. The paroled militia went home, for now. The Continental privates went first to the barracks and to Haddrell\'s Point across the harbor, and then, from later that summer, into prison hulks, old ships moored in the harbor and used as floating prisons. Over the following year, roughly 800 of about 2,500 Continental prisoners died in those hulks, of disease and heat and starvation, about one man in three. These were the regulars who had held Charleston\'s lines for six weeks; a third of them never left the harbor alive, and they died slowly, of neglect, after the shooting was over. Hundreds more escaped the hulks only by agreeing to enlist in British regiments bound for the West Indies, the Caribbean garrisons where fever killed more soldiers than any battle. The officers sat in crowded parole at Haddrell\'s Point, where one of Lincoln\'s brigadiers, James Hogun (American), died that January; Woodford, the Virginian who had marched in just in time to be captured, died on a British prison ship in New York harbor in November. The general exchange that freed the survivors did not come until the middle of 1781.' },
      { p: 'The city was won. And then came the order that turned the conquest against itself. At first Clinton offered easy terms: paroles, protection, and neutrality for any man who would stay quiet. Then, on June 3, 1780, days before sailing home, he issued the proclamation that undid all of it. The existing militia paroles were declared void; every man was now required to swear allegiance to the Crown and actively support it, or be treated as a rebel. Neutrality was abolished at a stroke. Thousands of paroled men who had been perfectly content to sit out the war did the arithmetic and concluded that if they were going to be forced to fight for somebody, it would not be for the king. The proclamation was one of the causes that helped ignite the partisan war, the war of the backcountry bands under leaders like Sumter and Marion and Pickens that ate the British conquest from the inside over the next year. Clinton had disarmed the rebellion; one piece of paper helped arm it again.' },
      { p: 'Clinton himself sailed for New York in early June with about a third of the army, not because he thought the South was fragile, he genuinely believed it was secured, but because a French fleet on the northern coast was the larger danger; he left Cornwallis behind with some 8,300 men and the whole conquered South to hold. And there is one more thread to pick up before this page ends, but only to set it down again. One American column had missed the trap: Colonel Abraham Buford\'s roughly 350 Virginians had been marching to reinforce Charleston and turned back when the city fell. Cornwallis sent Tarleton after them. On May 29, near the North Carolina line at a place called the Waxhaws, Tarleton\'s Legion ran them down. What happened there is a story this page does not tell. It belongs to the next one.' },
      { pill: '/war-revolution/southern-turn', plabel: 'The southern war that followed: Greene, the partisans, and the road to Yorktown' },
      { p: 'Which leaves Benjamin Lincoln, and the fairest reading of him, which is also the truest. His defeat was at least as much political as military. He could have saved the army in early April, and was forbidden to by the very government he was defending; the men who threatened to open the gates if he marched out were the same men who petitioned him to surrender five weeks later. Congress and Washington understood this. Lincoln was exchanged within six months, never charged with anything, and restored to Washington\'s side. And at Yorktown, on October 19, 1781, when Cornwallis surrendered his own trapped army, Washington refused to let Cornwallis\'s deputy hand over the sword to anyone but his own second in command. He directed the British surrender to Benjamin Lincoln, and he granted Cornwallis\'s garrison exactly, and only, what Lincoln\'s had been granted at Charleston. He had written it to Cornwallis in his own hand the day before.' },
      { p: 'The same Honors will be granted to the Surrendering Army as were granted to the Garrison of Charlestown.', q: true },
      { p: 'Colors cased. The march denied. The most deliberate exchange in the entire war, and the man who gave up Charleston was standing there to collect it.' },
    ],
    meanwhile: { region: 'The Castillo de San Marcos, St. Augustine', title: 'Gadsden\'s reckoning', body: 'Christopher Gadsden, the loudest voice for holding the city and then the voice that begged Lincoln to give it up, was paroled as a civil officer. It did not save him. That August the British seized him along with other leading men of Charleston and shipped him to the old Spanish fortress at St. Augustine, in British Florida. Offered a second parole, he refused it, and spent about ten months in a dungeon of the Castillo de San Marcos. The man who personified the political trap that lost the army paid for it in a stone cell, on his own terms.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={CHARLESTON_NARR}
    id={id}
    slug="charleston"
    battleName="Charleston"
    date="March 29 – May 12, 1780"
    theatreId="rev-battles"
    battleId="rev-charleston"
    theatreHref="/war-revolution/battles"
    accent="var(--rev-battles)"
    endHref="/war-revolution?theatre=rev-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
