'use client'

// Glorieta Pass — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

export const GLORIETA_PASS_NARR: Record<string, Narr> = {
  'the-dream': {
    eyebrow: 'Glorieta Pass · The Confederate plan',
    title: 'The Confederate Dream of the Pacific',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -106.5, lonMax: -104.2, latMin: 35.1, latMax: 36.4 },
        states: [
          { name: 'New Mexico', tone: 'focus', label: 'NEW MEXICO', labelLon: -105.5, labelLat: 36.2 },
          { name: 'Colorado' }, { name: 'Texas' }, { name: 'Arizona' }, { name: 'Oklahoma' },
        ],
        dots: [
          { name: 'Glorieta Pass', date: 'Mar 26–28, 1862', lat: 35.57, lon: -105.73, heavy: true, anchor: 'middle', dy: 24 },
          { name: 'Santa Fe', lat: 35.687, lon: -105.937, color: '#8a8175', anchor: 'end' },
          { name: 'Fort Union', lat: 35.905, lon: -104.842, color: '#8a8175', anchor: 'start' },
        ],
      } },





      { p: 'In the winter of 1862, the Civil War had a western front almost nobody back East was thinking about, and a Confederate general was about to bet a small army on the most far-reaching gamble of the whole war: the Pacific Ocean. His name was Brigadier General Henry Hopkins Sibley (South), and his plan, which he had personally sold to Confederate President Jefferson Davis the year before, was to march a force of Texans up the Rio Grande (the great river that runs the length of New Mexico, north to south), conquer New Mexico Territory (the vast stretch of land that today makes up New Mexico and Arizona, then a single sparsely settled U.S. territory, not yet a state), and keep going. Past New Mexico lay the gold fields of Colorado and the silver of Nevada. Past those lay California, with its ports and its harbors and its open door to the rest of the world. A Confederacy that reached the Pacific would have money to fund the war and seacoast the Union navy could not blockade. It was, on paper, breathtaking.' },
      { fig: '/war-img/cmdr/sibley.jpg', cap: 'Brigadier General Henry Hopkins Sibley (South), architect of the Confederate bid for New Mexico and the Pacific, a plan he personally sold to Jefferson Davis the year before the march began.', credit: 'Period photograph · public domain' },
      { p: 'And it was, at bottom, a bid to extend slavery across the continent. Strip away the gold and the ports and the maps, and the Confederate dream of the Southwest was the same thing the Confederacy was everywhere else: an attempt to push a slaveholding republic, by force, all the way to the Pacific. The men marching up the Rio Grande were carrying that cause west with them. The rest was real estate.' },
      { h: 'A plan stitched out of nothing', eyebrow: 'The grab for the West' },
      { p: 'Sibley raised roughly 2,500 mounted Texans (an "army" by the loose standards of the far frontier) and brought along 15 cannon. They called themselves the Army of New Mexico. They had a weakness baked into the plan from the start: there was almost nothing to eat or wear out there. New Mexico Territory was thinly populated and poorly supplied, and the Confederacy was openly counting on living off the land it conquered, recruiting New Mexicans, Utah Mormons, and Colorado miners along the way to fill out the ranks and capturing Union stockpiles to feed the men. By early 1862, the Confederate Congress had even formally organized a Confederate Territory of Arizona out of the southern half of New Mexico, paper proof of how far the ambition reached. But ambition does not feed an army, and an army that has to take its food from the enemy as it goes is an army with a knife at its own throat.' },
      { h: 'Valverde and the road to Santa Fe', eyebrow: 'The grab for the West' },
      { p: 'The first real test came on February 21, 1862, at a ford of the Rio Grande called Valverde, just north of Fort Craig, a Union strongpoint commanded by Colonel Edward R.S. Canby (North), who commanded all Union forces in the territory. Sibley\'s Texans fought Canby\'s garrison and won the field, driving the Union troops back inside the fort\'s walls. But it was the kind of victory that loses wars. Canby\'s men refused to surrender, pulled back into Fort Craig with their supplies, and stayed there, a Union force sitting squarely behind the Confederate line of march, denying Sibley the very stockpiles he had come to capture.' },
      { p: 'So Sibley did the only thing a hungry army can do: he kept going north and hoped for better. On March 2 his advance occupied Albuquerque. On March 13 the Confederates marched into Santa Fe, the territorial capital, and raised their flag over it. And then the prize slipped through their fingers a third time. The Texans broke into the storerooms expecting the food and forage a capital should hold, and found them stripped bare. The Union had hauled off nearly everything before the first Confederate rider came into view. Sibley now held the capital of New Mexico and almost nothing his men could eat.' },
      { p: 'That left one target worth taking: Fort Union, the main Union supply depot for the entire Southwest, about 90 miles (145 km) northeast of Santa Fe. Whoever held Fort Union held the territory. It was packed with the food, ammunition, and gear a campaign needs to survive. For Sibley, it was no longer a goal. It was a necessity. Everything an army hauled with it to stay alive (the wagon convoy of rations, cartridges, medicine, and spare gear that soldiers called the supply train) was waiting inside Fort Union for whoever got there first.' },
      { fig: '/war-img/glorieta-pass-campaign.png', cap: "The grab for the West: Sibley's Texans push up the Rio Grande from Fort Craig through Albuquerque to Santa Fe, while the Pike's Peakers race down from Colorado to Fort Union, the supply depot both armies had to have.", credit: 'Stuff Happened map' },
      { h: 'The Pike\'s Peakers come down the mountains', eyebrow: 'The grab for the West' },
      { p: 'The Union\'s answer to all this did not come from Washington, which was busy bleeding in Virginia. It came from Colorado. The 1st Colorado Volunteers (a volunteer regiment is a unit of civilians who enlisted for the war rather than career soldiers, this one recruited straight out of the mining camps around Denver and Pike\'s Peak, which got them the nickname the "Pike\'s Peakers") set out to save the territory on foot. They marched. They marched the way almost no one in this war marched. Starting from Denver in late February, they crossed something on the order of 300 to 400 miles (480 to 640 km) of cold high country, much of it above 7,000 feet with snow still on the ground, and the final leg of it is the part that survives in every account: roughly 67 miles in about 24 hours. Men who had already walked the spine of the Rockies pushed through a day and a night without real rest, boots gone to ruin, falling out and catching up, driven by the knowledge that if they were late the territory was lost. They reeled into Fort Union around March 10 or 11, half-dead and exactly in time.' },
      { p: 'The regiment was led overall by Colonel John P. Slough (North), with the advance under Major John M. Chivington (North), a hulking former Methodist minister. On March 22, Slough\'s column (his marching force) left Fort Union and started south down the Santa Fe Trail (the old wagon route that ran from the Missouri frontier all the way to Santa Fe, and the only practical road through this country) looking for the Confederate army. By March 25, Chivington\'s advance guard had reached Kozlowski\'s Ranch, a stage stop east of the pass that the Union turned into its staging point. The Texans were camped at the other end of that same notch.' },
      { p: 'The notch was Glorieta Pass, and it was the gate. At the southern tip of the Sangre de Cristo Mountains (the long range running along New Mexico\'s eastern edge), it was the one practical way for an army and its wagons to move along the Santa Fe Trail between Santa Fe and Fort Union. If the Confederates wanted Fort Union (and they had to have it), they had to come through the pass. If the Union wanted to stop them, this was where it would happen. Both armies were walking toward the same 20-mile (32 km) stretch of canyon and ridge southeast of Santa Fe, and neither quite knew the other was so close.' },
    ],
    meanwhile: { region: 'the far West', title: 'A campaign no one was watching', body: 'Two thousand miles from the cornfields and creeks where the country thought the Civil War was being decided, the war\'s westernmost campaign was unfolding almost in secret. This was the only serious Confederate attempt to conquer and hold Union territory west of the Mississippi River, and the stakes were enormous, the gold and silver that financed the Union, blockade-free Pacific ports, the whole shape of a continental war. Yet the men who would decide it were not famous generals with the eyes of the nation on them. They were Texas volunteers, Colorado miners, and New Mexico frontiersmen, fighting for the future of half a continent in a mountain pass most Americans had never heard of.' },
  },

  'the-battle': {
    eyebrow: 'Glorieta Pass · The fighting',
    title: 'The Gettysburg of the West',
    blocks: [
      { p: 'People would later call Glorieta Pass "the Gettysburg of the West," and the phrase, however worn it has gotten, points at something real. This was no skirmish. The federal government would eventually rate Glorieta Pass at its highest possible level of strategic importance, the same tier as Gettysburg and Antietam, one of only 11 battles in the entire war to earn it. What happened over three days in this New Mexico canyon decided the fate of the Confederate bid for the Pacific. The strange part, the part that makes Glorieta unlike almost any other battle in the war, is that the side that won the fighting lost everything anyway.' },
      { h: 'Apache Canyon', eyebrow: 'March 26–28' },
      { p: 'It opened on March 26, in the narrow western arm of the pass called Apache Canyon, and it opened by accident. Major John M. Chivington (North) pushed forward with about 400 picked men and came around a bend in the canyon straight into the Confederate vanguard (the leading edge of the Texan force, roughly 300 to 420 men under Major Charles L. Pyron (South)) around 2:30 in the afternoon. There was no maneuvering up to it: one moment the trail was empty, the next Pyron\'s cannon were firing down it, and the first Union rush broke and scattered backward under the blast.' },
      { p: 'Then Chivington did the thing the terrain begged for. The canyon walls rose steep and close on either side, so he sent his infantry scrambling straight up them, climbing above the trail onto ledges the Texans below could not easily reach, until the Confederate line was caught in a crossfire pouring down from both rims at once. While the Texans were ducking that, a mounted Colorado company spurred straight up the middle of the canyon and tore the line apart. Pyron pulled back about a mile and tried to set a new line, and the Union infantry flanked him again, swinging around his sides faster than he could form up. By around 4:00 p.m. it was over, the Confederates streaming back west with somewhere between 70 and 75 of them captured. Both sides broke off, agreed a short truce to gather their wounded, and pulled apart, Chivington east toward Pigeon\'s Ranch, Pyron west to Johnson\'s Ranch to wait for the rest of the army.' },
      { p: 'March 27 brought no fighting at all, just the sound of two armies getting bigger. Lieutenant Colonel William R. Scurry (South) arrived with the bulk of the Texan force, the main body that had been marching up the trail behind Pyron\'s advance guard all along, and now the senior man on the field. Colonel John P. Slough (North) came up with the main Union force. Both sides spent the day planning to attack the other the next morning. Neither knew the other was planning the same thing.' },
      { fig: '/war-img/glorieta-pass.png', cap: 'Three days at Glorieta Pass: Apache Canyon on March 26, the stalemate of March 27, and Pigeon\'s Ranch on March 28, fought on the Santa Fe Trail while Chivington\'s column crossed the mesa to burn the Confederate supply train.', credit: 'Stuff Happened map' },
      { h: 'Pigeon\'s Ranch', eyebrow: 'March 26–28' },
      { p: 'The real battle came on March 28, and it began the way the first one had, with two armies blundering into each other. Slough\'s plan was to crush the Confederates between two forces: send Chivington with 450 to 490 men south over the high ground to come down behind the enemy and cut off their retreat from the west, while Slough himself pushed roughly 850 to 900 men straight up the Santa Fe Trail to drive them from the east, a hammer swinging the Texans onto an anvil. What Slough did not know was that Scurry was already marching east up that same trail with about 1,100 to 1,200 men, meaning to do almost exactly the same thing to him.' },
      { p: 'So the two columns walked into each other. Around 11:00 in the morning, near a stage stop and inn called Pigeon\'s Ranch (a low adobe way station on Glorieta Creek where travelers on the trail had stopped for years), the advance riders of each side rounded into view of each other, opened fire, and the whole absurd arithmetic of the day became plain in an instant: each commander had set out that morning to surprise an enemy who was, at that same moment, marching to surprise him.' },
      { p: 'What followed was hours of hard, close fighting, and the Texans got the better of it. Scurry threw attack after attack at the Union line, three to five assaults by various counts, and he had the numbers, about 1,100 men against Slough\'s 850 on the trail. The union guns held for a while, silencing Confederate artillery and breaking up charges, but Confederate sharpshooters worked their way onto a ridge above the field and pinned the Union infantry where it stood. The dying was real on both sides. Major John Shropshire (South) was killed throwing his men at the Union left. Around 3:00 p.m., Major Henry Raguet (South) was mortally wounded as Scurry curled around the Union right and broke it.' },
      { p: 'That flanking move ended it. With his right giving way in the late afternoon, Slough ordered a retreat east to Kozlowski\'s Ranch, skirmishing as he went until the light failed. The Texans held the field. By the only measure a soldier on the ground could see that day, they had won. Scurry put it this way in his official report on the battle:' },
      { p: '"The loss of my supplies so crippled me that after burying my dead I was unable to follow up the victory."', q: true },
      { p: 'That report carries one more line, scrawled by a man who did not yet understand what had been done to him: "I do not know if I write intelligently. I have not slept for three nights." He had the field, the dead to bury, three sleepless nights behind his eyes, and a victory he could not use.' },
    ],
    meanwhile: { region: 'the canyon', title: 'A victory with a hole in the middle of it', body: 'While Scurry\'s exhausted Texans bedded down on the ground they had just taken at Pigeon\'s Ranch, something had gone badly wrong miles to their rear, and not one of them knew it yet. They had pushed the enemy back. They had held the trail. By every signal a battlefield gives a soldier, they were the victors. But Scurry\'s supplies were gone, and a victory you cannot eat is not a victory at all.' },
  },

  'the-wagons': {
    eyebrow: 'Glorieta Pass · The decisive stroke',
    title: 'The Wagons at Johnson\'s Ranch',
    blocks: [
      { p: 'The battle of Glorieta Pass was not decided by the men who fought it. It was decided by about 450 men who spent the day climbing a mesa. While Scurry and Slough hammered at each other on the Santa Fe Trail, Major John M. Chivington\'s (North) flanking detachment was doing something the Confederates had not planned for and could not see: crossing the high tableland to come down in the Confederate rear, where the entire Texan army had left its lifeline sitting in the sun, almost unguarded.' },
      { p: 'The two halves of the Union force fought their separate fights in total ignorance of each other all day. There was no way to send word across that ground in time. Miles of mountain, no line of sight, no way for a message to climb the mesa and come down the far side faster than events were moving, so Slough on the trail never knew where Chivington was, and Chivington on the mesa never knew Slough was losing. The day\'s two halves were not a plan working in concert. They were two blind blows that happened to land together.' },
      { h: 'Over the mesa', eyebrow: 'The decisive stroke' },
      { p: 'A mesa is a flat-topped highland with steep sides, a tableland standing well above the valley floor, and the one south of the trail, Glorieta Mesa, rose roughly 2,000 feet (610 m) above the canyon. Chivington\'s men had to get over it. They could not have done it alone. Their guide was Lieutenant Colonel Manuel Chaves (North), a New Mexican frontiersman who had spent his life in this mountain country and now served as an officer in the territory\'s own Union militia, chosen by Colonel Edward R.S. Canby (North) and Chivington precisely because no Coloradan or Texan knew this ground the way he did. Chaves and his New Mexico volunteers led the detachment on a roughly 16-mile (26 km) march, up through a canyon, across the top of the mesa, and out to a vantage point on its edge, and from up there, looking down, they could see what they had come for. Below them, at the western mouth of the pass at Johnson\'s Ranch (the Confederate supply depot, also called Cañoncito), sat the entire forward supply reserve of the Army of New Mexico.' },
      { fig: '/war-img/glorieta-pass-wagons.png', cap: "The blow that decided it: Chivington's column climbs over Glorieta Mesa and drops onto Johnson's Ranch, burning the Confederate supply train eight miles behind Scurry's fighting at Pigeon's Ranch.", credit: 'Stuff Happened map' },
      { p: 'It was guarded by perhaps a couple hundred men and a single cannon. Everything else, all the Texan fighting strength, was eight long mountain miles away, winning the battle at Pigeon\'s Ranch.' },
      { h: 'The fire that ended the campaign', eyebrow: 'The decisive stroke' },
      { p: 'Chivington\'s men came down the steep western face of the mesa, by one account descending the cliffs in about half an hour, and fell on the camp. The fight for it was short. They overwhelmed the guard, spiked the lone cannon (driving a metal spike into the touch-hole so it could not be fired), and took 17 prisoners, whom they paroled (released them on their sworn word not to fight again until formally exchanged, a standard practice on both sides of the war). Then they went to work on the wagons.' },
      { p: 'What they destroyed was the Confederate campaign itself. The supply train held food, ammunition, medicine, forage (feed for the horses and mules), clothing, even the officers\' baggage, essentially everything the Texan army needed to keep existing in a territory that could not feed it. They burned roughly 60 to 80 wagons of it (the sources split on the exact count, with figures running from 60 to 73 to 80) and killed or drove off the horses and mules (the draft animals that hauled the wagons and dragged the cannon, the muscle that moved the army), somewhere on the order of 500 to 600 of them. When it was done, the supply train was ash and the animals were dead or gone.' },
      { p: 'The man who led this raid was Chivington, and the mainstream record is clear that he commanded it. (A single New Mexico newspaper, writing two years later in 1864, claimed that someone else proposed the attack and that Chivington had to be talked into it, and that a Captain William Lewis (North) actually led the assault. No other source backs this up, the account appeared when Chivington had become a controversial figure, and the standard histories do not echo it.) What is not in dispute is the result, which Slough reported in his official dispatch:' },
      { p: '"we took and destroyed their train of about 60 wagons, with their contents."', q: true },
      { h: 'A victory you cannot eat', eyebrow: 'The decisive stroke' },
      { p: 'Scurry had won the field at Pigeon\'s Ranch. He held the ground, he had beaten Slough, he had every reason to think he had opened the road to Fort Union. And in those same hours, eight miles behind him, he had lost every wagon of food and every cartridge in reserve and most of the animals that could have hauled what was left. A Civil War army in 1862 could not fight, or march, or even stay alive, without its supply train. Scurry had nowhere to go but back. His own report says it plainly: the loss of his supplies so crippled him that, after burying his dead, he could not follow up the victory he had bled for. The Texans had won the battle and lost the campaign in the same afternoon, and they had to walk past their own burned wagons to understand it.' },
      { p: 'The retreat that followed was a slow catastrophe. The Confederate army could not be resupplied anywhere in New Mexico, Fort Union still in Union hands, Santa Fe\'s provisions thin, Canby\'s troops closing in. On April 12, Brigadier General Henry Hopkins Sibley (South), the campaign\'s architect, who had not even been present on the battlefield at Glorieta, ordered his men to abandon Albuquerque and start the long retreat south to Texas. It was a march through misery. Blocked along the river by Canby, the army was forced through the mountains and across the Jornada del Muerto (the "Journey of the Dead Man"), a roughly 90-to-100-mile (145 to 160 km) waterless desert basin along the Rio Grande, a flat, sun-scorched stretch of the old Spanish road with no reliable water for days at a time, named for exactly what it did to travelers. Hungry soldiers stripped food from New Mexican civilians along the way, and some of those civilians fought back. Of the roughly 2,500 men Sibley had marched up the Rio Grande, only about 1,500 made it back to San Antonio by that summer. Something like 500 were dead of fighting, starvation, or disease, and another 500 captured, about 40 percent of the army gone. The Confederacy never again mounted a serious campaign for the Southwest or the Pacific. The dream of a slaveholding republic stretching to the ocean died in a burning wagon park at the mouth of a canyon.' },
      { fig: '/war-img/cmdr/chivington.jpg', cap: 'Major John Chivington (North), who led the raid over the mesa that burned the Confederate supply train, and who two years later commanded the Sand Creek Massacre of a peaceful Cheyenne and Arapaho encampment.', credit: 'Period photograph · public domain' },
      { p: 'There is a darker chapter to the man who lit that fire. Just over two years later, in November 1864, the same John Chivington, by then a colonel commanding in Colorado, led the Sand Creek Massacre, in which his men attacked a peaceful Cheyenne and Arapaho encampment and killed scores of people, most of them women and children. The officer who saved the Union\'s hold on the Southwest became one of the worst perpetrators of anti-Native violence in the West. Both of those things are true, and the second does not erase the first, or the first the second.' },
    ],
    meanwhile: { region: 'the West', title: 'The continent stays whole', body: 'With the wagons gone and Sibley\'s army stumbling home across the desert, the far Southwest stopped being contested ground. Union control of New Mexico, Colorado, and the road to California\'s gold was secure for the rest of the war, and the men who had secured it were not the marquee generals of the East but Colorado\'s mining-camp volunteers and New Mexico\'s own frontiersmen. The "Pike\'s Peakers" had supplied the manpower; Manuel Chaves and his New Mexico volunteers had supplied the one thing that made the decisive blow possible, the knowledge of how to get over the mesa and where the wagons would be. The westernmost gamble of the Confederacy was finished, undone not by the battle it won but by the wagons it never thought to guard.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={GLORIETA_PASS_NARR} id={id} slug="glorieta-pass" battleName="Glorieta Pass" theatreId="tmis" theatreHref="/war-civil-war/trans-mississippi" battleId="t-glorieta" accent="#d97706" />
}
