'use client'

// The Siege of Fort Oswego (August 1756), battle sections. Produced through the war
// content pipeline (audits/war-content-pipeline.md): fact pack → author (Opus) →
// critic gates (fact-check + storytelling + comprehensiveness + clarity + fairness,
// parallel) → reconcile → revise. Data only; rendered by the shared
// <BattleSectionReader>. House voice: no em-dashes; British/French side-tags once on
// first mention per section; the war named plainly (an imperial war that was, on the
// ground, a war over Native land and Native war aims). Sources:
// audits/war-pipeline/fi-oswego-*.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const OSWEGO_NARR: Record<string, Narr> = {
  'the-prize-on-the-lake': {
    eyebrow: 'Oswego · The only door on the lake',
    title: 'The prize on the lake',
    blocks: [
      { p: 'Lake Ontario is the smallest of the Great Lakes and one of the most important pieces of ground in North America, because of where it sits. It is the hinge between the settled British and French colonies in the east and the vast interior to the west, the country the French called the pays d’en haut (the “upper country,” meaning the whole Great Lakes basin and the lands beyond). Whoever controlled the lake controlled the water road that fed Fort Niagara, the Ohio Country, and every French post in the west. The fur trade ran along it. The empires of Britain and France both reached for it. And the land around it was not theirs to begin with. It was the country of the Haudenosaunee, the Six Nations of the Iroquois, and the nation nearest to the lake’s southeast corner, the Onondaga, watched both crowds of newcomers with a careful eye.' },
      { p: 'On that southeast corner, at the mouth of the Oswego River, the British held the one thing the French could not stand: a base on the lake itself. Oswego was the only British naval and trading post on Lake Ontario, a wedge driven straight into the side of French communications west. From it the British could trade for furs that would otherwise have gone to the French, and from it, in theory, they could threaten Fort Niagara and the whole western lifeline. As long as Oswego stood, the French hold on the interior had a knife at its throat.' },
      { p: 'It was a strong idea built on weak ground. Oswego was not one fort but three, and all three were poorly placed. The oldest, raised in 1727 on the low west bank right at the river’s mouth, was the original trading fort, sometimes called Fort Pepperrell. It sat on low ground, which is the wrong place to put a fort if anyone can shoot down into it. Across the river on the high east bank stood the newest work, Fort Ontario, built in 1755 on the commanding height, the one piece of ground that overlooked everything. About half a mile (0.8 km) to the southwest sat the third post, an unfinished palisade (a wall of sharpened timber logs) so feeble the men called it “Fort Rascal,” held by roughly 150 New Jersey militia (part-time troops raised in the colonies). The garrison had wintered over in this place and come out of it sick, hungry, and short of everything. Provisions were low. Disease was through the ranks. Few of the cannon were even mounted and ready to fire. The base meant to be Britain’s spearhead on the lake was, by the summer of 1756, a tired and rotting thing.' },
      { p: 'And across the lake, at Fort Frontenac on the northern shore, the French were gathering to take it.' },
      { pill: '/war-french-indian/battles/fort-frontenac', plabel: 'Fort Frontenac, the French base across the lake' },
      { p: 'The man who would lead them had been in North America for only three months. Major General Louis-Joseph de Montcalm, Marquis de Montcalm (French), had arrived in Quebec in mid-May 1756, sent from France to command the king’s regular troops in the New World. He had soldiered nearly his whole life. Born in 1712 near Nîmes in the south of France, made an ensign at the age of nine, he saw his first action in 1733 at twenty-one. Nine years later he fought in the defense of Prague in 1742, made colonel the next year, and at the battle of Piacenza in 1746 took five sabre wounds and was captured, then exchanged. He was exactly what Europe meant by a professional soldier, schooled in the formal warfare of the Old World, with its sieges run by the rulebook and its surrenders settled by etiquette. That schooling was also his blind spot. He had little use for the way the Canadians and their Native allies fought, the raids and ambushes and forest war that actually won battles on this continent, and he would clash again and again with the governor-general of New France over how the war should be run. Montcalm had come to fight a European war. The continent had other ideas. But over the next three years he would become the central French figure of the whole conflict, and Oswego was where his American career began.' },
      { p: 'His force numbered about 3,000. There were French regulars from the regiments of La Sarre, Guyenne, and Béarn; there were troupes de la marine (the French colonial regular troops, the professional soldiers raised for service in the colonies); there were Canadian militia under François-Pierre de Rigaud de Vaudreuil, the governor-general’s brother, who had spent the early summer cutting Oswego off from the outside world; and there were roughly 250 Native allies drawn from across New France and the pays d’en haut. The French staged the whole expedition out of Fort Frontenac and rowed it across the lake.' },
    ],
    meanwhile: { region: 'New France', title: 'A recruiting surge', body: 'The French victory the year before, the destruction of General Braddock’s army on the Monongahela, had been seen by every Native nation watching. It proved the British could be beaten badly, and it drew a wave of warriors from the upper country to fight alongside the French, a wave Vaudreuil worked hard to encourage. The men who came to Oswego came on the strength of that reputation. They were betting the French were winning.' },
  },

  'the-siege': {
    eyebrow: 'Oswego · Four days',
    title: 'The siege',
    blocks: [
      { p: 'The French came ashore on August 10, 1756, landing about two miles (3.2 km) east of Fort Ontario, the commanding height on the high east bank. This was Montcalm’s element. A formal siege is a slow, methodical, almost mathematical thing, and he ran it by the book. Over the next two days his men dug siege trenches, the zigzag approaches that let attackers creep their guns and their bodies forward toward a fort’s walls without being shot down in the open, working them steadily toward Fort Ontario.' },
      { p: 'The British made the decision that lost them the battle. Fort Ontario was the strong card, the high ground that overlooked the river and both other forts. On August 13, rather than fight for it, the garrison abandoned it and fell back across the river into the old low fort on the west bank. They had handed Montcalm the one piece of ground that mattered.' },
      { p: 'On August 14 the French mounted their siege guns, roughly nine cannon (some accounts say twelve), on the captured heights of Fort Ontario, and fired down into the old fort on the low ground across the river. The old fort, built low, lay exposed to plunging fire from above, and under it the works began to crumble. Then Montcalm sent troops across the river upstream, so that the old fort caught fire from a second direction as well and sat in a crossfire with nowhere to hide.' },
      { p: 'Into that bombardment went the garrison’s commander. Colonel James Mercer (British) was killed in the firing, struck down by a cannonball; the well-attested telling is that the shot took off his head, though gentler accounts only say he was killed by a shell. To the sick, hungry men still in the works it was the worst possible loss at the worst possible moment, the steady hand gone in an instant with the fort coming apart around them. With Mercer dead, command fell to Lieutenant Colonel John Littlehales (British), and Littlehales had seen enough. The high ground was lost, the commander was dead, the fort was coming apart under fire from two sides, and inside the walls were not only soldiers but laborers, shipbuilders, and the women and children of the post. He surrendered within about an hour. The forts that were supposed to be Britain’s grip on Lake Ontario had fallen in four days.' },
      { p: 'Then Montcalm made a decision that mattered far beyond the etiquette of the moment. He denied the garrison the honours of war. The honours of war were a European courtesy: a garrison that had put up a brave, proper defense was allowed to march out under its own flags, drums beating, with its dignity and sometimes its weapons intact, a formal recognition that it had fought well before yielding. Montcalm judged that this brief, collapsing defense had not earned that courtesy, and he refused it. He was thinking like a European officer keeping score by European rules. But that refusal also meant something he understood far less well. To his Native allies, who reckoned the value of a victory in captives, weapons, and plunder, a surrender that denied them their due was an insult and a broken promise. They had come a long way on the strength of French victories, expecting to be paid in the only currency that made the journey worth it. Montcalm had just told them, in effect, that the spoils were not theirs to take. The anger of that moment did not stay quiet for long.' },
    ],
    meanwhile: { region: 'Albany', title: 'The end of a plan', body: 'Far to the southeast, at the British supply hub of Albany, the loss of Oswego wrecked the year’s strategy. A British push against Fort Niagara had depended on Oswego as its springboard. With the base gone, captured, and soon to be burned, there was no springboard, and the western offensive collapsed before it began.' },
  },

  'the-killings-and-the-cost': {
    eyebrow: 'Oswego · Two ways of war collide',
    title: 'The killings and the cost',
    blocks: [
      { p: 'What followed the surrender is the hardest part of the story to tell honestly, and it has to be told as two different ideas of war crashing into each other, because that is what it was.' },
      { p: 'By the rules Montcalm fought under, a surrender agreement handed the victorious commander control of the prisoners and the spoils, to dispose of as he saw fit. By the war aims of his Native allies, the captives, the scalps, the weapons, and the supplies were the point of fighting at all, the proof of courage and the source of prestige that made a warrior’s standing among his own people, and they were the warriors’ earned due, not the French commander’s to give away. These were not lawless impulses. They were the central, honored practice of war as the nations understood it, as old and as serious to them as the honours of war were to Montcalm. The two systems could not both be satisfied, and at Oswego they collided over the heads of the prisoners.' },
      { p: 'After the surrender, Canadian militia and Native allies fell on the plunder, and some of them got drunk on captured rum. In the disorder, prisoners were killed. Some British captives trying to slip away were tomahawked. Littlehales himself, the man who had just surrendered the fort, was seized and badly beaten by Abenaki warriors. How many people died this way is genuinely uncertain and has been argued over ever since. The lowest accounts describe a group of perhaps thirty soldiers and civilians killed or tomahawked while trying to escape in the night; the higher ones put the toll at as many as a hundred or more. Several French-leaning sources leave the killings out altogether. The honest answer is a range, a few dozen to upward of a hundred, and a flag that the true number is disputed. No one should hand you a precise figure here, because no one has one.' },
      { p: 'Montcalm intervened to stop it. He moved to halt the killing and protect the prisoners, and his reasoning, as he gave it, was as much practical as humane: restoring order would, he said, cost the King “eight or ten thousand livres in presents.” Livres were French currency, and the presents were gifts, the goods the French routinely handed to their Native allies to keep the alliance running, and here they were the price of buying back the prisoners and the peace, of compensating warriors for the plunder they had been denied. It is a revealing line. It puts the whole tragedy in one sentence: the French could command the alliance only so far as they could pay for it, and the bill for an order Montcalm had broken by denying the honours of war came due in lives and livres at once. His role in it is still debated. He helped provoke the anger that led to the killings, and he personally stepped in to stop the slaughter. Both are true.' },
      { p: 'It was also a rehearsal. The same fault line, a French commander’s European rules running headlong into his allies’ war aims over the disposition of prisoners, would tear open again the next summer, far more infamously, at Fort William Henry.' },
      { pill: '/war-french-indian/battles/fort-william-henry', plabel: 'Fort William Henry, where it happened again in 1757' },
      { p: 'When the violence was past, the French burned the forts and left. They destroyed the Oswego posts that had been Britain’s only foothold on Lake Ontario, and withdrew across the lake. The site was left abandoned, and it stayed that way until 1758.' },
      { p: 'Before he went, Montcalm made a gesture aimed past the battle. He ceremonially returned the cleared Oswego ground to the Onondaga, on whose country it sat, a diplomatic offering meant to draw the Iroquois nations toward France, and by most accounts it had some effect on where the Six Nations leaned in the years that followed.' },
      { p: 'The cost, set down plainly: the French now held undisputed control of Lake Ontario, securing their western communications and removing the threat that Oswego had posed to Fort Frontenac. Britain’s plans for 1756 were in ruins, the Niagara expedition among them. Somewhere between 1,600 and 1,700 people surrendered and were carried off to Canada and Montreal as prisoners, soldiers and laborers and shipbuilders and the women and children of the post among them. The French captured 121 cannon, along with ships, boats, and great stores of provisions. British dead numbered somewhere around 80 to 150; French losses were far lighter, on the order of a few dozen. For a British year already going badly, it was a heavy blow to prestige, a victory that announced Montcalm’s arrival and confirmed, to every nation watching the lake, that the French were the side that won.' },
      { p: 'And that is the thread to hold onto, because it is the heart of the thing. The men who came the farthest to Oswego, and who turned its surrender into something terrible, did not come as anyone’s auxiliaries. They came for their own war, fought for their own ends, on what was their own country, and they expected to be paid in the terms their world ran on. The collision at the moment of surrender was not a breakdown of the battle. It was two whole ways of understanding what a victory is, meeting at the one place they could not be reconciled.' },
      { p: 'eight or ten thousand livres in presents', q: true },
    ],
    meanwhile: { region: 'The Lake Ontario frontier', title: 'The Onondaga, watching', body: 'This was Haudenosaunee country, and the Onondaga lived nearest to the contested corner of the lake. They watched the British base they had tolerated on their land burn, and watched the French row away as the new masters of Lake Ontario. The empires kept score in forts and cannon and prisoners. For the nations whose country this was, the question underneath was always the same one: which of these newcomers, if either, could be lived with, and on whose terms.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader
    sections={OSWEGO_NARR}
    id={id}
    slug="fort-oswego"
    battleName="Fort Oswego"
    theatreId="fi-battles"
    battleId="fi-oswego"
    theatreHref="/war-french-indian/battles"
    accent="var(--fi-battles)"
    endHref="/war-french-indian?theatre=fi-battles"
    endKicker="Back to the war"
    endLabel="All the battles"
  />
}
