'use client'

// THEME section — Slavery & the Cotton Economy (Off the Battlefield, kind=theme).
// The causes-phase OPENER of the war: the economic root the whole conflict grows
// from. NOTE: 'use client' is REQUIRED — this page reads ACCENTS (a value exported
// from a 'use client' module); in a server component that import resolves to a
// client reference and ACCENTS.otbf is undefined, so the accent silently falls
// back to violet. Any war page that passes an ACCENTS color must be a client
// component. Built through the war content pipeline (fact pack → author(Opus) →
// fact-check + storytelling critic(Sonnet) → revise). Source + gate records:
// audits/war-pipeline/slavery-cotton-*.md. Green accent. No stat block, no
// tactical map — one arc-driven section (pressure → turning point → consequence).

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'
import { ACCENTS } from '@/components/mode/war-chrome'

const NARR: Record<string, Narr> = {
  main: {
    eyebrow: 'The root the war grew from',
    title: 'King Cotton, and the Wealth the South Would Kill to Keep',
    blocks: [
      { p: `In 1793, slavery in the United States looked, to a hopeful few, like a problem that might quietly solve itself. The crop that had built the Upper South — tobacco — was wearing out the very soil it grew in. The fields of Virginia and Maryland were tired, the profits thinner every year, and a number of planters (the large landowners whose fortunes were built on enslaved labor) were beginning to wonder, in private, whether owning human beings was even going to stay worth the trouble. Slavery was not dying. But for one strange moment, you could squint and imagine it fading.` },
      { p: `Then a young schoolteacher fresh out of Yale built a small wooden box with a hand crank, and the moment was over. What he made was meant to *save* labor. Instead it created the hungriest demand for forced human labor the continent had ever seen, set off a cotton boom that would make the American South one of the richest agricultural regions on earth, and turned roughly four million enslaved people into the single most valuable thing the country owned. By 1860, the South was not merely rich. It was *certain* — certain enough to gamble a nation on the belief that no one would ever dare take that wealth away. This is the story of how cotton made that certainty, and why it is the deepest root of the war that followed.` },

      { h: 'A fortune locked behind a sticky seed', eyebrow: 'Pressure' },
      { p: `To understand what the cotton gin unleashed, you first have to understand the wall it tore down.` },
      { p: `There are different kinds of cotton, and the difference decided the fate of millions of people. Along the warm, sandy coast of Georgia and the Carolina Sea Islands grew long-staple cotton (also called Sea Island cotton), prized for its long, silky fibers and, crucially, its smooth seeds that pulled free of the fiber easily. The trouble was geography: long-staple cotton would only grow in that narrow coastal strip. Push it inland and it died.` },
      { p: `The whole vast interior of the South — the future plantation country — could grow a different variety: short-staple cotton, sometimes called green-seed cotton. It thrived almost everywhere across the Southern uplands. It had exactly one fatal flaw. Its seeds were small, sticky, and tangled deep in the fiber, and getting them out was agonizing, mind-numbing work. (“Ginning” simply means separating the cotton fiber from its seeds — “gin” is short for “engine.”) By hand, a single worker needed about ten hours to clean one pound of fiber. Ten hours. For one pound. At that pace, the South’s most plantable crop was barely worth planting. A fortune in cotton was sitting in the soil of half a dozen future states, and it was locked behind a seed no one could remove fast enough to matter.` },
      { p: `That was the world in the early 1790s: a declining tobacco economy, an uncertain future for slavery in the Upper South, and a wildly profitable crop that nobody could process. All it would take to change everything was a faster way to clean the seed.` },

      { h: 'Eli Whitney’s box', eyebrow: 'Turning point' },
      { p: `In 1793, a Massachusetts-born inventor named Eli Whitney (pronounced “WIT-nee”), recently graduated from Yale and visiting a Georgia plantation, built a device to do exactly that. His cotton gin was almost embarrassingly simple: a hand crank pulled the cotton fiber through a comb-like grid of slender wires, set too narrow to let the seeds pass, so the fiber was dragged free and the seeds were left behind. Whitney applied for the patent on October 28, 1793, and it was granted on March 14, 1794.` },
      { p: `The math of it was staggering. A single hand laborer could clean about one pound of short-staple cotton in ten hours. Whitney’s gin could clean roughly fifty pounds of fiber a day. The seed bottleneck — the one thing standing between the South and a cotton fortune — simply vanished.` },
      { fig: '/war-img/cotton-gin.jpg', cap: 'Enslaved people working an early cotton gin while white planters look on — the machine at the center of the boom, and the human labor it multiplied rather than spared.', credit: 'William L. Sheppard, “The First Cotton-Gin,” Harper’s Weekly, December 18, 1869 · public domain' },

      { h: 'The machine that backfired' },
      { fig: '/war-img/slavery-cotton-plantation-hands.jpg', cap: `The "hands" the boom demanded were people. Enslaved men, women, and children gathered around a cart at James Hopkinson's cotton plantation on Edisto Island, South Carolina, photographed in 1862 — one of the earliest real photographs of plantation slavery in the Deep South, made only because Union troops had just taken this stretch of coast.`, credit: `Henry P. Moore · albumen print · 1862 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `And here is the cruel twist at the very center of this entire history, the hinge the whole story turns on.` },
      { p: `The cotton gin was a labor-*saving* machine. It should have meant less work. By every intuition, a device that did the work of dozens of people should have *reduced* the demand for those people. It did the opposite. By making short-staple cotton suddenly, wildly profitable, the gin set off a frenzy to plant more of it everywhere it would grow — and growing and picking cotton, unlike cleaning it, could not be mechanized. Every acre of new cotton still had to be sown, tended, and picked by human hands, bent double under a brutal sun, dragging a sack down endless rows. The faster the gin cleaned the crop, the more cotton was worth planting; the more cotton was planted, the more hands were needed to plant and pick it; and in the American South, “hands” meant enslaved people.` },
      { p: `A machine built to reduce labor multiplied the demand for enslaved labor instead. The institution that some had imagined fading away was not fading. It was about to explode.` },

      { h: 'The boom' },
      { fig: '/war-img/slavery-cotton-levee-new-orleans.jpg', cap: `Cotton bales stacked the length of the New Orleans levee, the great clearinghouse where the South's crop met the world. By 1860 some 3,500 vessels and roughly $220 million in goods moved across these docks in a year — the visible end of an economy whose hidden end was the auction block.`, credit: `William Henry Jackson · Detroit Publishing Co. · glass negative · 1880–1897 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `The numbers tell the story of the explosion. In 1800, the United States produced about 156,000 bales of cotton. (A bale is a tightly compressed bundle of cleaned cotton; in this era one weighed somewhere between 400 and 500 pounds.) By 1830 the crop had reached 750,000 bales. By 1850, 2.85 million bales. By 1860, more than four million bales — roughly two billion pounds of cotton in a single year.` },
      { p: `That cotton remade the country’s place in the world. By 1860, cotton accounted for nearly 60 percent of everything the United States sold abroad — by some counts more than 60 percent — worth on the order of $200 million a year. By that year the American South was growing roughly two-thirds of the entire world’s cotton, and feeding about three-quarters of the cotton flowing into the mills of Britain, the heart of the global textile industry. New Orleans alone moved around $220 million in goods through its docks, carried by some 3,500 vessels.` },
      { p: `The geography of all this wealth had a name: the Cotton Belt, also called the Black Belt (originally for its dark, rich soil). It swept in a great arc from Georgia and the Carolinas across Alabama, Mississippi, and Louisiana and on into Texas — much of it land that had been frontier a generation earlier, now carved into plantations and worked by people who had not chosen to be there. Because here is the part the export figures hide. Someone had to clear that new land, plant it, and pick it. The cotton boom was, at bottom, a sudden, ravenous demand for human beings — and in 1808, the most obvious way to supply them was about to be cut off.` },
      { p: `And before we follow that demand south, one thing the export figures quietly hide: the North was no horrified bystander to all this. The same cotton that fed Britain’s mills fed America’s own, and America’s mills were Northern. New England’s textile factories ran on Southern cotton — by 1860 they consumed something like two-thirds of all the cotton used inside the country, and Massachusetts alone spun roughly a third of the nation’s cotton thread. Northern banks, meanwhile, were knee-deep in the business: they financed plantations, brokered the crop, and routinely accepted enslaved human beings as collateral on loans (human beings pledged as security a bank could seize if the debt went unpaid) — predecessor firms of banks still trading today held thousands of people as security against a planter’s debt. The cloth on a Boston merchant’s back and the ledgers in a New York counting-house were stitched out of the same forced labor as the bales on the New Orleans docks. This is why ending slavery would prove so wrenchingly hard even in the “free” states: it was not a distant Southern sin the North could simply disown. The whole country, North and South, had its hands in the same cotton.` },

      { h: 'The door closes, and the population grows anyway', eyebrow: 'Consequence' },
      { fig: '/war-img/slavery-cotton-coffle-capitol.jpg', cap: `A coffle of enslaved people — chained together at the wrist, driven on foot toward the cotton frontier — marched past the unfinished United States Capitol, the building that protected the trade that bound them. The line covered roughly twenty miles a day; the families it walked away from would, more often than not, never hear of them again.`, credit: `unattributed · wood engraving (from *A Popular History of the United States*) · 1876 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `When the Constitution was written, it contained a quiet compromise: Congress was forbidden from banning the importation of enslaved people from across the Atlantic before the year 1808. The moment that deadline arrived, Congress acted. The Act Prohibiting Importation of Slaves took effect on January 1, 1808, and after that almost no new enslaved people were legally brought into the country from abroad.` },
      { p: `By the simple logic of supply and demand, this should have throttled slavery just as the cotton boom was creating a desperate hunger for labor. It did not. Consider the arithmetic: there were roughly 700,000 enslaved people in the United States in 1790. By the census of 1860 — the last federal count ever taken of the enslaved — there were 3,953,760 (some sources put it a few hundred shy of that, at 3,950,511). The enslaved population had nearly *quadrupled* even after the door to the Atlantic trade slammed shut.` },
      { p: `How? The grim answer is that the population grew from within, overwhelmingly through births. The American South appears to have been the only major slave society in the Americas to grow its enslaved population mainly by natural increase rather than by continuously importing new captives. What that arithmetic meant in human terms is monstrous: enslaved people themselves became a self-replenishing form of property, a crop that reproduced. And a self-replenishing asset, born in one region and demanded in another, creates a market.` },

      { h: 'The Second Middle Passage' },
      { fig: '/war-img/slavery-cotton-auction-south.jpg', cap: `An enslaved man, woman, and child stand on the block before a crowd of bidders at a Southern auction. This is the ordinary mechanism Solomon Northup watched tear Eliza from her son — families priced, divided, and sold apart as routine business, the moral heart of the cotton economy.`, credit: `after a sketch by Theodore R. Davis · wood engraving (*Harper's Weekly*, July 13, 1861) · 1861 · Library of Congress, Prints & Photographs Division · public domain` },
      { fig: '/war-img/slavery-cotton-slave-pen-alexandria.jpg', cap: `The slave pen of Price, Birch & Co. on Duke Street in Alexandria, Virginia, its sign reading "DEALERS IN SLAVES." This brick building was a holding jail in the machinery of the trade — the same Franklin & Armfield operation that ran the business at near-corporate scale earlier leased it — photographed after Union troops seized it and posted a guard at the door.`, credit: `unattributed · albumen photograph · c. 1862–1865 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `So a trade rose up to move human beings from where they were to where the cotton was. It is one of the least-remembered chapters of American history and one of the most devastating. Historians call it the Second Middle Passage — an echo of the original Middle Passage, the horrific Atlantic crossing that had carried captive Africans to the Americas in the first place. To understand what it was, do not start with the numbers. Start in a slave pen in New Orleans, with a man who wrote down what he saw.` },
      { p: `In 1841, Solomon Northup — a free-born Black man from Saratoga Springs, New York, a carpenter and a violinist with a wife and children — was lured to Washington, D.C. with the promise of work, drugged, kidnapped, and sold into slavery. He would spend twelve years enslaved, mostly in Louisiana, before regaining his freedom in 1853 and writing it all down in a memoir, “Twelve Years a Slave.” He was shipped to New Orleans and sold through the pen of a trader named Theophilus Freeman — the same New Orleans market that stood at the center of the whole lower-South trade. And in that pen, Northup watched a sale that he could never afterward forget.` },
      { p: `There was an enslaved woman named Eliza, held with her two children — a son, Randall, and a daughter, Emily. A planter from Baton Rouge came to buy, and he wanted Randall, the boy, alone. Eliza begged. She pleaded to be sold together with her children, asking only to stay with them for “the little time she had to live,” promising “how very faithful and obedient she would be; how hard she would labor day and night.” The planter would not take all three. The trader Freeman, Northup recorded, “damned her, calling her a blubbering, bawling wench, and ordered her to go to her place.” As the boy was led away, Randall called back to his mother: “Don’t cry, mama. I will be a good boy. Don’t cry.”` },
      { p: `He was gone. Eliza never saw or heard of either of her children again. “What has become of the lad, God knows,” Northup wrote. “It was a mournful scene indeed.”` },
      { p: `That scene was not a tragic exception. It was the ordinary mechanism of the trade, repeated in pens and at auction blocks across the South tens of thousands of times. The thing the domestic slave trade did most routinely, most casually, was exactly what it did to Eliza: it broke families apart. A husband sold one direction and a wife another; parents and children, brothers and sisters, separated at a trader’s convenience and a buyer’s whim, most of them never to see one another again in this life. It severed, again and again and again, the most basic human bonds there are — and it did so as ordinary business, recorded in ledgers, the way a merchant records the movement of any other goods. This is the moral heart of the cotton economy. Everything else — the bales, the export figures, the certainty — was built on top of it.` },
      { p: `Behind every such scene was a real industry, with a geography and brand-name firms. The trade ran in one direction. The Upper South — Virginia and Maryland above all, along with Kentucky, North Carolina, Tennessee, and Missouri — had tired soil, a surplus of enslaved people, and shrinking use for them. The Deep South — Georgia, Alabama, Mississippi, Louisiana, Arkansas, and Texas — had the booming cotton frontier and an endless appetite for labor. So the Upper South sold its people south and west into the cotton country. By one count, about 835,000 people were forcibly relocated between 1790 and 1860; another estimate puts the number moved after 1808 at roughly a million or more. The figures are genuinely contested, but historians commonly summarize it as roughly a million people torn from their homes and marched or shipped to the cotton frontier. The largest of the trading firms, Franklin & Armfield, ran the business at near-corporate scale; Bolton, Dickens & Co. was another of the big traders. New Orleans — the very market that swallowed Eliza’s son — was the great clearinghouse of the lower-South trade: by 1827 it was the chief center of the business, and economists estimate that more than 135,000 people were sold there between 1804 and 1862. Up the Mississippi at Natchez, Mississippi, stood a market grimly known as the “Forks of the Road.” Richmond, Charleston, Savannah, and Memphis ran markets of their own.` },
      { p: `The journeys to these markets were brutal. Those moved overland were driven in coffles — long columns of people chained together at the neck or wrist, walking south for weeks, covering roughly 20 miles a day on foot, guarded by men on horseback. Those sent by water were loaded onto boats and carried down the Mississippi, which is the literal origin of the phrase to be “sold down the river.” It became a byword for the worst fate imaginable, and not only because of the harder labor and shorter lives that waited in the Deep South. It was the *severance* — final, total, and unknowable. The family left behind had no address for you and no way to send or receive a single word. They could not learn whether you had survived the journey, whether you were sick or well, whether you were alive at all. And they would never see you again. To be sold down the river was to vanish from the lives of everyone you loved while still drawing breath, into a silence that lasted the rest of your life.` },
      { p: `And yet — this has to be said, because the ledgers and the auction blocks make it easy to forget — the people caught in this machine were never merely its objects. The enslaved fought it at every turn: they slowed their work and broke their tools, they ran, they sheltered escapees and passed them north along the secret network of safe houses that came to be called the Underground Railroad, and now and then they rose in open revolt — most famously when Nat Turner led a rebellion through Southampton County, Virginia, in 1831 that killed roughly 60 white Southerners and left the whole slaveholding South in a permanent state of fear. That fear is itself the proof. A contented labor force does not need slave patrols, pass laws, and ever-harsher fugitive-slave statutes to hold it down; the South built exactly that apparatus of surveillance and terror precisely because the people it held never stopped pushing back. They were not an asset waiting to be valued. They were human beings refusing, in a thousand daily ways, to be one.` },

      { h: 'The richest thing in America' },
      { fig: '/war-img/slavery-cotton-richmond-auction.jpg', cap: `A sale in progress at Richmond, Virginia — one of the Upper South's busiest markets for selling people south. By 1860 the nation's four million enslaved people were worth an estimated three billion dollars, more than every railroad, factory, and bank in the country combined. Scenes like this one were the form that fortune actually took.`, credit: `unattributed · wood engraving (*The Illustrated London News*, Sept. 27, 1856) · 1856 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `Now stack up what all of this had created by 1860, because the dollar figure is the key that unlocks the war.` },
      { p: `The enslaved people of the United States were, collectively, worth an estimated more than $3 billion. That number is hard to feel in the abstract, so anchor it: it was more than the total capital invested in all the railroads, all the factories, and all the banks in the United States *combined*. It was worth more than the South’s farmland. Enslaved human beings were not just *part* of the Southern economy. They were the single largest capital asset in the entire American economy — the biggest pool of wealth the country possessed, and the great bulk of it concentrated in the hands of the Southern planter class. (The $3 billion figure is an estimate, but every serious accounting lands in the same neighborhood: an almost unimaginable fortune.)` },
      { p: `Sit with what that meant, because it explains everything that came after. To the men who held it, emancipation was not a moral argument to be won or lost over dinner. It was the threatened destruction of the largest concentration of wealth in the United States — *their* wealth, the foundation of their entire world. Asking the planter class to give up slavery was asking them to set fire to more money than existed in every railroad and bank in the country. That is the cold engine underneath all the speeches and the principles and the talk of states’ rights. That is *why the South would fight.*` },
      { p: `That wealth bought something even harder to give up than money: power. Here is the part that turns the South’s economic certainty into a political one. When the Constitution was written, the slave states won a bargain known as the Three-Fifths Compromise — enslaved people, who could not vote and were counted as property in every other respect, were nonetheless counted as three-fifths of a person when it came time to divide up seats in the House of Representatives (where a state’s population set how many it got). The effect was a kind of phantom electorate: the planter class got extra representation in Congress, and extra weight in the Electoral College (the system that picks the president, where a state’s say is tied to its number of seats in Congress), on the strength of the very human beings it owned. Within a few years of the Constitution’s ratification it had handed the slave states roughly a dozen or more extra House seats they would never otherwise have held, and that structural thumb on the scale never let up.` },
      { p: `For decades it tilted the whole federal government South. Enslavers held the presidency for the great bulk of the country’s first seventy years — most of the early presidents owned human beings — and they dominated the Supreme Court and the key committees of Congress besides. Northerners eventually gave this bloc a name: the “Slave Power,” a Southern minority that ran the national government as if slavery were not a local custom but a permanent, federally protected interest of the entire United States. (And it was a remarkably small minority doing the running — by 1860 only a sliver of white Southerners owned enough people to count as planters at all, yet that handful set the policy and told the region who it was.) For most of the nation’s life that arrangement had simply been the way things worked. Which is exactly why, in 1860, an election the South could not control would feel less like an ordinary defeat and more like the loss of a country it had always assumed was its own.` },

      { h: '“Cotton is king”' },
      { fig: '/war-img/slavery-cotton-hammond-portrait.jpg', cap: `James Henry Hammond of South Carolina, photographed for the 35th Congress in 1859 — the senator who rose on the Senate floor in 1858 to declare "Cotton is king," and to call enslaved people the "mud-sill" the rest of society was built on. The confidence in this portrait is the confidence that would gamble a nation.`, credit: `Julian Vannerson · salted-paper print (from McClees' gallery of the 35th Congress) · 1859 · Library of Congress, Prints & Photographs Division · public domain` },
      { p: `Out of all that wealth grew a dangerous confidence. By the late 1850s, Southern leaders had convinced themselves not merely that cotton made them rich, but that cotton made them *untouchable* — that the world’s hunger for it was a weapon they held in their own hands.` },
      { p: `The man who gave that confidence its slogan was James Henry Hammond (pronounced “HAM-und”), a United States Senator from South Carolina from 1857 to 1860. On March 4, 1858, Hammond rose on the floor of the Senate and delivered a speech that would echo for the rest of the era. The South’s grip on the world’s cotton supply, he argued, made it invincible:` },
      { p: `No, you dare not make war on cotton. No power on earth dares to make war upon it. Cotton is king.`, q: true },
      { p: `In the same speech, Hammond laid out the brutal philosophy underneath the bravado — his defense of slavery as the natural foundation of any society. Every civilization, he claimed, needed a permanent laboring class to do its drudgery, a class on which the finer life of everyone above could rest:` },
      { p: `In all social systems there must be a class to do the menial duties, to perform the drudgery of life… It constitutes the very mud-sill of society.`, q: true },
      { p: `A “mud-sill” is the lowest beam of a building, the timber laid right on the ground that the entire structure rests on. Hammond was saying, out loud, in the Senate, that enslaved people were the foundation timber of civilization itself — and that this was as it should be.` },
      { p: `The phrase “Cotton is king” hardened into an actual foreign-policy doctrine, the strategy historians call King Cotton diplomacy. The conviction was that Europe — Britain and France especially — was so dependent on Southern cotton for its mills that it could never afford to let the South fall. If it ever came to a fight, the reasoning went, the South need only choke off its cotton, and Britain and France would be forced to step in, recognize the South as a nation, and break any blockade against it. (This belief would be put to the test once war came — and it would fail, as Britain turned to cotton from India, Egypt, and Brazil, and refused to publicly take the side of a slaveholding rebellion. But that reckoning belongs to a later chapter.) What matters here is that in 1860, before a single shot, the *belief* in cotton’s power made the Southern planter class dangerously, fatally sure of itself.` },

      { h: 'A society that staked everything on human property' },
      { p: `This is the root the entire war grew from. Trace it back and the chain is brutally simple. A tired tobacco economy made slavery look, for one fragile moment, like it might fade. A small wooden machine meant to save labor instead made an unpicked crop worth a fortune, and the fortune demanded hands, and the hands meant people. A ban on importing those people only turned the enslaved themselves into a self-replenishing asset, and a trade rose to move a million of them south in coffles and down the river, ripping families apart as ordinary business. By 1860, those four million human beings were the richest thing the country owned — worth more than all its railroads, factories, and banks combined — and a class of men had come to believe that this wealth made them untouchable.` },
      { p: `Cotton did not merely make the South rich. It made the South *certain* — certain of its wealth, certain of its righteousness, certain that the world would never dare cross it. It was a society that had staked everything — its economy, its politics, its very picture of itself — on the ownership of human beings, and it had no intention of giving any of it up.` },
      { p: `The question now was no longer whether such a society could exist. It already did. The question was how much longer it could exist *alongside* a country that was, slowly and unevenly, beginning to decide it shouldn’t. That collision — the politics of it, the broken compromises, the road that ran from cotton wealth to open war — is where the story turns next.` },
    ],
    meanwhile: {
      region: 'the nation’s politics',
      title: 'The Road to War',
      body: 'Cotton built the wealth and the certainty; the country’s politics had to contain them — and couldn’t. Compromise after compromise tried to settle whether slavery would spread into the West, each one holding for a while and then breaking. That long unraveling, from the halls of Congress to the violence on the frontier, is where the story goes next.',
    },
  },
}

export default function SlaveryCottonThemePage() {
  return (
    <BattleSectionReader
      sections={NARR}
      id="main"
      slug="slavery-cotton"
      battleName="Slavery & the Cotton Economy"
      theatreId="offfield"
      battleId="th-slavery"
      theatreHref="/war-civil-war/off-the-battlefield"
      accent={ACCENTS.otbf}
      heroImage="/war-img/slavery-cotton-hero.jpg"
      heroPalette={['#4a3d2c', '#2a2118', '#0a0705']}
      heroCredit="Eyre Crowe, “Slaves Waiting for Sale, Richmond, Virginia,” 1861 · public domain"
      endHref="/war-civil-war/off-the-battlefield"
      endKicker="End of this story"
      endLabel="Back to Off the Battlefield"
    />
  )
}
