'use client'

// Missionary Ridge — battle sections. Produced through the war content pipeline
// (audits/war-content-pipeline.md): fact pack → author → fact-check + storytelling
// critic → revise. Data only; rendered by the shared <BattleSectionReader>.

import { BattleSectionReader, type Narr } from '@/components/mode/battle-reader'

const MISSIONARY_RIDGE_NARR: Record<string, Narr> = {
  'the-siege': {
    eyebrow: 'Missionary Ridge · The army that wanted revenge',
    title: 'A City the South Couldn’t Lose',
    blocks: [
      { locator: {
        eyebrow: 'Where and when',
        frame: { lonMin: -86.2, lonMax: -83.5, latMin: 33.1, latMax: 35.7 },
        states: [
          { name: 'Tennessee', tone: 'focus', label: 'TENNESSEE', labelLon: -84.2, labelLat: 35.4 },
          { name: 'Georgia' }, { name: 'Alabama' }, { name: 'Kentucky' }, { name: 'North Carolina' },
        ],
        dots: [
          { name: 'Missionary Ridge', date: 'Nov 25, 1863', lat: 35.02, lon: -85.24, heavy: true, anchor: 'middle', dy: -30 },
          { name: 'Chickamauga', lat: 34.93, lon: -85.29, color: '#8a8175', anchor: 'end' },
          { name: 'Atlanta', lat: 33.749, lon: -84.388, color: '#8a8175', anchor: 'start' },
        ],
      } },







      { p: 'By late November 1863, two armies were staring at each other across a valley in southeastern Tennessee, and the one on the high ground was slowly winning a war of patience. The city of Chattanooga sits on the south bank of the Tennessee River, hemmed in by mountains, and it had a value out of all proportion to its size: it was the rail gateway into the Deep South. The railroads that ran out of it pointed straight at Atlanta and the cotton-and-plantation interior beyond, the economic core of the rebellion. The Confederacy had seceded and built its armies for one overriding reason, to protect and extend the enslavement of four million Black people, and Atlanta was the rail-and-supply heart of that economy. Whoever held Chattanooga held the door to it.' },
      { p: 'The Union army was inside the city, and it was trapped. Two months earlier, in September, the Army of the Cumberland (one of the United States’ named field armies in the West) had been beaten at Chickamauga, driven back into Chattanooga in a near-rout that only Maj. Gen. George H. Thomas (North) had kept from becoming a catastrophe, holding the rear line so stubbornly he came out of it called “the Rock of Chickamauga.” The victorious Confederates under Gen. Braxton Bragg (South) had followed the beaten army to the edge of the city, climbed the heights around it, and settled in to starve it out. By November the besieged Federals (the Union troops) had nearly chewed through their rations, until a daring nighttime operation in late October cracked open a supply route, the “Cracker Line,” and got food and men flowing back in. The crisis eased. But the Confederates still sat on the mountains, and the city was still a cage.' },
      { pill: '/war-civil-war/western/chickamauga', plabel: 'Chickamauga: the defeat that trapped the army in Chattanooga' },
      { p: 'Then Maj. Gen. Ulysses S. Grant arrived. Lincoln had consolidated the western armies under one commander after Chickamauga, and Grant, fresh off the capture of Vicksburg that summer (the Mississippi River fortress whose fall split the Confederacy in two), was that man. He came to Chattanooga to break the siege, not survive it. By late November he had three full armies gathered around the city and a plan to drive Bragg off the heights for good.' },
      { pill: '/war-civil-war/western/vicksburg', plabel: 'Vicksburg: the victory that made Grant the man for the job' },
      { p: 'The chief obstacle was the longest of the heights: Missionary Ridge, a steep, narrow spine of high ground running north to south a couple of miles east of the city, its crest rising several hundred feet above the valley floor. Bragg’s whole army was strung along the top of it, facing west across the valley toward the trapped Union lines. To a Federal soldier looking up from the bottom, it looked unassailable.' },
      { fig: '/war-img/missionary-ridge-overview.png', cap: 'The ground at Chattanooga: the trapped Union city in the west, the long Confederate ridge to the east, and the two flanks where Grant means to win.', credit: 'Stuff Happened map' },
    ],
    meanwhile: { region: 'Orchard Knob', title: 'The view above the valley', body: 'Three days before the climax, on November 23, Grant pushed his lines forward and seized a detached hill standing alone on the valley floor between Chattanooga and the ridge. It was called Orchard Knob, and it gave him a clear, elevated view straight across at Missionary Ridge. For the next two days it was his command post, the spot from which he and Thomas watched the battle unfold, and from which, on the afternoon of the 25th, Grant turned to the men beside him to ask who had ordered his soldiers up the ridge.' },
  },

  'the-plan': {
    eyebrow: 'Missionary Ridge · The hammer that wouldn’t fall',
    title: 'Sherman Stalls, Hooker Lags',
    blocks: [
      { p: 'Grant’s plan for November 25 was simple on paper. A quick word on how an army of that day was built, because the whole battle turns on it: the basic blocks were the brigade (a couple thousand men), several of which made a division (several thousand), several divisions a corps (bigger still), and the corps together an army (the whole force). The generals’ ranks ran in the same order, biggest command to smallest: general at the top, then lieutenant general, then major general (Maj. Gen.), then brigadier general (Brig. Gen.).' },
      { p: 'The blow would land on the north end of Missionary Ridge, where the ridge ran into a feature called Tunnel Hill (named for a railroad tunnel bored through it). There Grant put his hardest-hitting weapon: Maj. Gen. William T. Sherman and the Army of the Tennessee, a second named Union field army, and almost the same name as the Confederate Army of Tennessee they were all there to destroy. One is the river, one is the state, and they are enemies. Sherman commanded the troops he and Grant had won with at Vicksburg. He was the hammer, sent to crush the Confederate right and roll the whole line up from the north.' },
      { p: 'At the south end, Grant gave a supporting role to Maj. Gen. Joseph Hooker (North), who commanded a detachment sent west from the Army of the Potomac (the main Union army back in Virginia). Hooker had just taken Lookout Mountain the day before in the fog-shrouded fight nicknamed “the Battle Above the Clouds.” Now he was to come down off the mountain, swing around to the southern tip of the ridge through a pass called Rossville Gap, and press up the Confederate left.' },
      { pill: '/war-civil-war/western/lookout-mountain', plabel: 'Lookout Mountain: Hooker’s “Battle Above the Clouds,” the day before' },
      { p: 'And in the center, facing the steep heart of the ridge, stood Thomas’s Army of the Cumberland, the army that had been beaten at Chickamauga and had been seething about it ever since. Their job, in Grant’s design, was the smallest of the three: a hold, a feint, a diversion to pin the Confederate center in place while Sherman did the real work on the flank (the flank being the end of the enemy’s line). Nobody expected the battle to be won in the center, and that was the one assumption everyone got wrong.' },
      { fig: '/war-img/missionary-ridge-flanks.png', cap: 'The two flanks: Sherman stalled at Tunnel Hill against Cleburne in the north, Hooker coming up through Rossville Gap in the south, Bragg’s army later streaming east toward Dalton.', credit: 'Stuff Happened map' },
      { h: 'The Hammer Won’t Fall', eyebrow: 'Both ends fail' },
      { p: 'By midday, the plan was failing at both ends. On the north, Sherman never even reached his target cleanly: misled by bad maps and a distant view that made the high ground look like one continuous ridge, he had crossed over and seized a separate, detached hill, only to find a deep ravine yawning between him and the real Tunnel Hill. So his roughly 16,600 men went in against the actual height piecemeal (a few brigades at a time rather than all at once, so each wave could be beaten on its own) and ran headlong into one of the finest division commanders in the Confederate army: Maj. Gen. Patrick Cleburne (South), holding the height with only about 4,000 men. Cleburne’s outnumbered division beat back assault after assault all day, counterattacking each time, and Sherman’s men were shredded against the slope, nearly 2,000 casualties for no breakthrough at all. Grant’s hammer would not fall.' },
      { p: 'On the south, Hooker was late. He had left Lookout Mountain around mid-morning, but when his column reached Chattanooga Creek, the bridge across it had been burned, and his advance stalled for some three hours while his engineers rebuilt it under the pressure of the clock. He didn’t reach Rossville Gap until mid-afternoon, around 3:30, and only then began working up the south end of the ridge.' },
      { p: 'So by late afternoon Grant was watching his battle stall from Orchard Knob. The hammer was stuck in the north. The flanking column was hours behind in the south. The day was burning down, and Bragg’s army was still sitting on the ridge, having lost almost nothing. Grant needed to pull pressure off Sherman, and the only fresh, idle force he had was the diversion in the center, Thomas’s revenge-hungry Army of the Cumberland.' },
    ],
    meanwhile: { region: 'Tunnel Hill', title: 'The one part that went to plan', body: 'The fight on the north end belonged to Patrick Cleburne (South), and he won it cleanly. His division, sometimes called the best in the western Confederate army, held Tunnel Hill against three or four times its number and never gave way. It was the one part of November 25 that went exactly as the Confederates wanted, and it would matter again two days later: when Bragg’s whole army was streaming south in retreat, it was Cleburne who turned at Ringgold Gap on November 27 and threw back the Union pursuit, acting as the rear guard (the force left behind to fight off pursuers and cover a retreat) long enough to save the army’s wagons. The man who could not be moved on the ridge became the rear guard that kept the rout from becoming an annihilation.' },
  },

  'the-order': {
    eyebrow: 'Missionary Ridge · A diversion that turned into a trap',
    title: 'Take the Rifle Pits, and Stop?',
    blocks: [
      { p: 'Late in the afternoon, around half past three, Grant ordered Thomas’s army forward. The target was the first of two Confederate lines on the ridge. The Confederates had split their force between a row of rifle pits (shallow trenches for infantry) dug along the base of the ridge, and a second line up on the crest at the top. Thomas’s men were to cross the open valley, take those lower trenches at the base, and pull Confederate attention off Sherman.' },
      { p: 'So they went. Across the open valley they came, some 23,000 to 24,000 men, straight into the lower rifle pits, which held only about 9,000 Confederate defenders. The Federals overran the trenches, and then found themselves in the worst possible place: pinned at the foot of the ridge, in the open, with the second Confederate line firing down on them from the crest several hundred feet above. Staying put meant being shot to pieces. Going back meant recrossing the valley under the same fire. Going up, straight up that brutal slope, meant closing with the guns that were killing them.' },
      { p: 'Nobody is entirely sure what the men were supposed to do once they had taken the lower trenches, and it changes who gets the credit. By one telling, the base was the only sanctioned objective: seize the first line and stop. By another, drawn from the National Park Service, Grant was already impatient before the assault even began, pressing Brig. Gen. Thomas J. Wood (North) about why his attack had not gone in:' },
      { p: '“I ordered your attack an hour ago. Why has it not been made?… I order you to attack.”', q: true },
      { p: 'Grant to Wood, before the assault', i: true },
      { p: 'The surviving record cannot fully settle which it was, and standing where the men stood it almost did not matter. The position made the decision for them. Pinned and furious at the bottom of the ridge, the soldiers of the Army of the Cumberland made the choice their generals had not made for them.' },
    ],
    meanwhile: { region: 'the Confederate crest', title: 'Bragg’s badly-built line', body: 'The flaw that would doom the Confederate center was partly self-inflicted, and partly dug into the ridge before the battle began. In the weeks before, Gen. Braxton Bragg (South) had hollowed his own army out: feuding with subordinates who had openly tried to have him removed after Chickamauga, he had detached Lt. Gen. James Longstreet’s (South) corps north to Knoxville, stripping thousands of men from the very line that was about to break. What was left, he split between the two positions, base and crest, so that neither was strong. Worse, his engineers ran the upper works along the true top of the ridge instead of the military crest (the line a little below the summit, the place from which defenders can actually see and shoot down the whole face of the slope). From the true top there were stretches of the lower slope the defenders simply could not see or fire on: dead ground, blind spots. As one account put it, the works were placed “along the physical crest rather than what is termed the military crest,” and the error “severely handicapped the defenders.” Bragg’s line, in the same telling, was “only a thin crust,” with no real reserve to be had on a ridge too narrow to hold one. The Union soldiers about to climb did not know any of this, and the ground would let them live long enough to reach the top.' },
  },

  'the-charge': {
    eyebrow: 'Missionary Ridge · The diversion that won the battle',
    title: '“Who Ordered Those Men Up the Ridge?”',
    blocks: [
      { p: 'They went up. Without orders, on their own initiative, the Army of the Cumberland began climbing Missionary Ridge: first a few color-bearers (the soldiers who carry the unit’s flag, and so lead where it goes) and knots of men scrambling up out of the deadly trenches, then whole regiments, then the entire line, surging up the slope toward the top. As they climbed they took up a cry, the name of the field where they had been humiliated two months before: Chickamauga! Chickamauga! This was the army that had run at Chickamauga, and it was running uphill now, into the fire, with something to settle.' },
      { fig: '/war-img/missionary-ridge.png', cap: 'The decisive center assault: the Army of the Cumberland sweeps east into the rifle pits, then turns and surges straight up the slope, breaking Bragg’s center on the crest.', credit: 'Stuff Happened map' },
      { p: 'On Orchard Knob, Grant watched his plan dissolve into something he had not authorized and could not stop. He had ordered a diversion against the base. His army was storming the mountain. He turned, stunned, to the men around him and demanded to know who had ordered those men up the ridge. Maj. Gen. George H. Thomas (North) said it had not been him. Grant turned to Maj. Gen. Gordon Granger (North), his corps commander on that part of the field. Granger had not ordered it either, and his answer is the line the whole battle carries:' },
      { p: '“When those fellows get started, all hell can’t stop them.”', q: true },
      { p: 'Maj. Gen. Gordon Granger (North), to Grant', i: true },
      { p: 'And nothing did stop them. Up on the crest, the badly-sited Confederate line met exactly the catastrophe its placement invited: the blind spots had let the Federals climb out of the defenders’ fire, the thin reserveless line had nothing behind it to plug a break, and the men coming up were past stopping. The divisions of Maj. Gen. Philip Sheridan (North) and Brig. Gen. Thomas J. Wood (North) crested the ridge near the center and broke through. The first crack, near Bird’s Mill Road, opened around 5 p.m., and from there it spread in both directions like a seam tearing, Brig. Gen. August Willich (North) and Brig. Gen. William B. Hazen (North) rolling the broken Confederate line up north to south, peeling off regiment after regiment.' },
      { p: 'This was the sector held by Maj. Gen. John C. Breckinridge (South), the center of the ridge, commanded by a man who had been Vice President of the United States only a few years earlier and was now watching his line evaporate under him. (On the north end, Lt. Gen. William J. Hardee’s (South) sector around Tunnel Hill, with Cleburne, was still holding; it was the center that gave way.) By around six in the evening the whole Confederate line had unraveled. Bragg’s veterans, men who had won at Chickamauga and besieged this very army, turned and ran off the back of the ridge they had been told was impregnable.' },
      { h: 'The Arithmetic of a Rout', eyebrow: 'The cost on the crest' },
      { p: 'The numbers tell the shape of it. At Missionary Ridge that day, roughly 56,000 Union troops faced about 44,000 Confederates. To read the losses you have to know what “casualties” means, because it is not just the dead: it counts everyone an army loses to a fight, the killed and the wounded and the captured and the missing all together. The Union, charging uphill into prepared positions, took most of its loss in wounded men shot on the slope: about 5,824 casualties, with 753 killed, 4,722 wounded, and 349 missing. The Confederate total ran higher, about 6,667, but the breakdown tells the story. Only 361 killed and 2,160 wounded, and 4,146 captured. When an army loses far more men captured than killed or wounded, it did not get ground down in a stand-up fight; it came apart and let the enemy scoop up whole bodies of men where they stood. That is the arithmetic of an army that broke and ran, leaving some 40 cannon abandoned on the crest. Whole regiments simply surrendered as the line dissolved: about 700 of one Confederate command (Holtzclaw’s) gave up at the south end. Bragg’s army fled east across Chickamauga Creek and kept going, southeast toward Dalton, Georgia.' },
      { p: 'One soldier, watching the rout, called it the death-knell of the Confederacy.', i: true },
    ],
    meanwhile: { region: 'the road south, Dalton', title: 'The army streams off the heights', body: 'As the sun went down, the Confederate Army of Tennessee was streaming off the eastern slope of Missionary Ridge in the dark, abandoning the heights it had held for two months. The retreat ran east across Chickamauga Creek and then southeast toward Dalton, Georgia, with Maj. Gen. Patrick Cleburne (South), the one commander who had not been beaten, peeling off to form the rear guard. Two days later, on November 27, he made his stand at Ringgold Gap and bloodied the pursuing Federals badly enough to save Bragg’s wagon trains. It was the only good news the Confederates carried out of Chattanooga, and it came from the same man whose stand had been the only good news during the battle itself. Everything else was wreckage: an army routed, a state lost, and the door to Georgia swinging open behind it.' },
  },

  'the-meaning': {
    eyebrow: 'Missionary Ridge · The miracle, and the door to the Deep South',
    title: 'The Gateway Thrown Open',
    blocks: [
      { p: 'It went into legend almost immediately as “the miracle on Missionary Ridge,” the result so improbable that nobody quite knew how to explain it. A feint meant only to pull pressure off a stalled flank had, against the plan and without orders, stormed a fortified ridge and routed a veteran army off the top of it. The generals’ design had failed at both ends; it was the men’s revenge and their refusal to die pinned at the bottom that won the day. Grant himself never fully claimed it. He had ordered the base. His army took the mountain.' },
      { p: 'For the Confederacy, the cost was not just bodies but cohesion. Gen. Braxton Bragg (South), who had besieged this army at the edge of victory in September, had now lost it the chance and lost his command with it: within days he asked to be relieved, and in early December his resignation of command was accepted. His Army of Tennessee, the South’s main force in the West, was wrecked as an offensive weapon and driven clean out of the state. The siege of Chattanooga, the slow strangulation that had begun after Chickamauga, was lifted for good. The Union now held the city and all of eastern Tennessee, permanently.' },
      { h: 'The Door to the Slave South', eyebrow: 'Why it mattered beyond Tennessee' },
      { p: 'And that is where slavery and the railroad come back into the story, because they are the reason the battle mattered beyond Tennessee. Chattanooga was the rail gateway into the Deep South, and the charge up Missionary Ridge cracked that gateway open. The city became the supply and logistics base for the campaign that came next: Maj. Gen. William T. Sherman’s drive on Atlanta in 1864, and from Atlanta his march through Georgia, the campaign that broke slavery across the Deep South by sheer force, freeing the enslaved as the army passed. That march begins logistically here, at Chattanooga, on the ridge. The men who cried “Chickamauga!” going up the slope were avenging a defeat in a war whose purpose, by late 1863, was the destruction of slavery itself. The ridge was the last barrier between the United States Army and the plantation interior. They went over it.' },
      { fig: '/war-img/cmdr/grant.jpg', cap: 'Maj. Gen. Ulysses S. Grant: Missionary Ridge was his last battle in the West, and three months later he commanded all the Union armies.', credit: 'Period photograph · public domain' },
      { p: 'There was one more consequence, and it shaped the rest of the war. Missionary Ridge was Grant’s last battle in the West. A few months later, in March 1864, he was promoted to lieutenant general (a rank above any he had held, the new top of the army) and given command of all the Union armies, general-in-chief. The man who had taken Vicksburg and now broken the siege of Chattanooga went east to finish the war against Lee. The road that ended at Appomattox ran through this ridge.' },
    ],
    meanwhile: { region: 'Washington and Richmond', title: 'Redemption and catastrophe', body: 'In Washington, Chattanooga read as redemption: the disaster of Chickamauga reversed, the western army saved, the road to Georgia opened, and confirmation that the right man was now running all the Union armies. Within months Lincoln would hand Grant everything. In Richmond, it read as catastrophe. The Confederacy’s main western army had been driven off an “impregnable” ridge by a charge nobody ordered, surrendering thousands of men and dozens of guns, and the gateway to the heart of the slaveholding South now stood open. The Confederate soldier who, watching the rout, called the day the death-knell of the Confederacy was closer to right than the men in Richmond wanted to believe.' },
  },
}

export function SectionNarrative({ id }: { id: string }) {
  return <BattleSectionReader sections={MISSIONARY_RIDGE_NARR} id={id} slug="missionary-ridge" battleName="Missionary Ridge" theatreId="west" theatreHref="/war-civil-war/western" battleId="w-missionary" accent="#1d4ed8" />
}
